EnterpriseDB/docs

advocacy_docs/getting-started/index.mdx

adding content to the index file

first test

---

src/constants/index-link-list.js

in the sidenav, change link headings and links to sample stubs, so that the user knows that she's looking at the advo site and not the full edb docs site

switch sidenav to sample content

---

.devcontainer/Dockerfile
.devcontainer/devcontainer.json
advocacy_docs/advocacy-index-nav.json
advocacy_docs/building/index.mdx
advocacy_docs/getting-started/connecting_to_postgres/java/01_hibernate.mdx
advocacy_docs/getting-started/connecting_to_postgres/java/02_ JDBC.mdx
advocacy_docs/getting-started/connecting_to_postgres/java/03_spring_data.mdx
advocacy_docs/getting-started/connecting_to_postgres/java/index.mdx
advocacy_docs/getting-started/connecting_to_postgres/python/01_psycopg2.mdx
advocacy_docs/getting-started/connecting_to_postgres/python/02_django.mdx
advocacy_docs/getting-started/connecting_to_postgres/python/03_ SQLAlchemy.mdx
advocacy_docs/getting-started/connecting_to_postgres/python/04_Pandas.mdx
advocacy_docs/getting-started/installing_postgres/docker.mdx
advocacy_docs/getting-started/installing_postgres/linux.mdx
advocacy_docs/getting-started/installing_postgres/macos.mdx
advocacy_docs/getting-started/installing_postgres/windows.mdx
advocacy_docs/optimizing/index.mdx
src/components/katacoda.js
src/styles/_docs.css

This should suffice to flush out some other minor issues with appearance vs the mockup. 
- need nav titles in cards
- remove "hi" cruft at end of pages

skeletal outline w/ some partial content filled in

---

advocacy_docs/getting-started/connecting_to_postgres/java/02_JDBC.mdx
advocacy_docs/getting-started/connecting_to_postgres/python/02_django.mdx

just a sanity-check before merging

minor cleanup to two connect topics / add related links

---

advocacy_docs/getting-started/connecting_to_postgres/java/02_JDBC.mdx
advocacy_docs/getting-started/connecting_to_postgres/python/02_django.mdx
advocacy_docs/getting-started/installing_postgres/linux.mdx
src/components/katacoda.js

Demonstrate a couple of different options for Katacoda embedding:
1. Click to load for the full UI, inline
2. Click to load for the "panel" UI (terminal window pinned to the bottom of the page)

Katacoda click to load

---

advocacy_docs/getting-started/connecting_to_postgres/java/01_hibernate.mdx
advocacy_docs/getting-started/connecting_to_postgres/java/02_JDBC.mdx
advocacy_docs/getting-started/connecting_to_postgres/java/03_springdata.mdx
advocacy_docs/getting-started/connecting_to_postgres/java/index.mdx
advocacy_docs/getting-started/connecting_to_postgres/python/01_psycopg2.mdx
advocacy_docs/getting-started/connecting_to_postgres/python/02_django.mdx
advocacy_docs/getting-started/connecting_to_postgres/python/03_ SQLAlchemy.mdx
advocacy_docs/getting-started/connecting_to_postgres/python/index.mdx
advocacy_docs/getting-started/installing_postgres/docker.mdx
advocacy_docs/getting-started/installing_postgres/linux.mdx
advocacy_docs/getting-started/installing_postgres/macos.mdx
advocacy_docs/getting-started/installing_postgres/windows.mdx

For the exploratory work that @epbarger is doing

add additional metadata: product, platform and tags

---

.github/ISSUE_TEMPLATE/problem-with-topic.md
.github/ISSUE_TEMPLATE/propose-new-topic.md
.github/ISSUE_TEMPLATE/suggest-addition-to-topic.md

Also pre-fill titles for page-specific templates to encourage noting the page there

add labels, "suggest additions" to issue templates

---

advocacy_docs/community/contribute/planning/demo.mdx

The problem with repeatedly resetting a demo after a heapin' pile of dry-runs is... It becomes easy to forget the steps that didn't contribute to the final result. If no one else, noting the need to branch first before creating content will be a reminder for ME!

nothin' like screwing up a demo to point out the one step you missed

---

advocacy_docs/building/sql/views.mdx
advocacy_docs/getting-started/installing_postgres/docker.mdx
advocacy_docs/getting-started/installing_postgres/linux.mdx

Update these tutorials to add output listings for executable code blocks, along with clarifying explanations where necessary (primarily Docker).

add output listings to panel tutorials

---

.github/workflows/deploy-develop.yml
.github/workflows/deploy-main.yml

- merging in new workflows that treat netlify test as production

"Production" merge 10/28/2020

---

.github/workflows/deploy-main.yml
README.md

- disable index update for now

Production merge II 10/28/2020

---

build-sources.json
gatsby-config.js
gatsby-node.js
scripts/source/pull_sources.py
scripts/source/source_barman.py
src/constants/index-navigation.js
src/templates/gh-doc.js

quick MVP integration of barman md files

barman mvp

---

src/components/advanced-search/filtering.js
src/components/advanced-search/form.js
src/pages/search.js

- Remove back link
- Remove unneeded "Advanced Search" link
- Focus input on initial render

advanced search ux tweaks

---

src/components/advanced-search/filtering.js
src/components/dark-mode-toggle.js
src/pages/search.js
src/styles/_docs.scss

- Add clickable label to theme toggle button
- tweak advanced search filter labels to match index navigation headers
- add side navigation footer to advanced search

toggle theme label

---

src/components/code-block.js
src/styles/_docs.scss

Output code block styling

---

gatsby-config.js
src/components/layout.js
src/hooks/use-sitemetadata.js
src/pages/404.js
src/pages/index.js
src/pages/search.js

- Don't use default description everywhere
- add pageMeta to index, search ch, and 404
- comment out rel canonical tag

head changes (remove rel canonical)

---

README.md
README_ADDING_NEW_SOURCES.md
build-sources.json
dev-sources.sample
gatsby-config.js
gatsby-node.js
scripts/source/config_sources.py
scripts/source/pull_sources.py
src/constants/index-navigation.js
src/templates/gh-doc.js
src/templates/learn-doc.js

- adds ability to source individual products
- adds readme content about adding sources
- streamline index-navigation file
- improvements to config-sources script, include prompted to pull external sources

source individual products

---

advocacy_docs/community/authoring/index.mdx
advocacy_docs/community/contribute/index.mdx
product_docs/README.md
src/components/side-navigation.js

This guide will help onboard newer developers.

Creating detailed macOS setup guide

---

product_docs/docs/epas/13/epas_compat_bip_guide/index.mdx

Fixed the Oracle trademark In BIP guide

Fixing 422 Oracle registered symbol added

---

product_docs/docs/epas/13/epas_inst_windows/02_requirements_overview.mdx
product_docs/docs/epas/13/epas_inst_windows/03_installing_advanced_server_with_the_interactive_installer/01_performing_a_graphical_installation_on_windows.mdx
product_docs/docs/epas/13/epas_inst_windows/03_installing_advanced_server_with_the_interactive_installer/02_invoking_the_graphical_installer_from_the_command_line/02_performing_an_installation_with_limited_privileges.mdx
product_docs/docs/epas/13/epas_inst_windows/03_installing_advanced_server_with_the_interactive_installer/02_invoking_the_graphical_installer_from_the_command_line/03_reference_command_line_options.mdx
product_docs/docs/epas/13/epas_inst_windows/03_installing_advanced_server_with_the_interactive_installer/02_invoking_the_graphical_installer_from_the_command_line/index.mdx
product_docs/docs/epas/13/epas_inst_windows/03_installing_advanced_server_with_the_interactive_installer/03_using_stackbuilder_plus.mdx
product_docs/docs/epas/13/epas_inst_windows/03_installing_advanced_server_with_the_interactive_installer/index.mdx
product_docs/docs/epas/13/epas_inst_windows/04_connecting_to_advanced_server_with_the_pgadmin_4_client.mdx
product_docs/docs/epas/13/epas_inst_windows/05_managing_an_advanced_server_installation/01_using_the_windows_services_applet.mdx
product_docs/docs/epas/13/epas_inst_windows/05_managing_an_advanced_server_installation/03_controlling_server_startup_behavior_on_windows.mdx
product_docs/docs/epas/13/epas_inst_windows/06_configuring_advanced_server/02_connecting_to_advanced_server_with_psql.mdx
product_docs/docs/epas/13/epas_inst_windows/06_configuring_advanced_server/index.mdx
product_docs/docs/epas/13/epas_inst_windows/07_uninstalling_advanced_server.mdx
product_docs/docs/epas/13/epas_inst_windows/index.mdx

Updated the windows guide with formatting fixes

Windows guide formatting fixes

---

product_docs/docs/epas/13/epas_qs_linux_7/index.mdx

QS guide, code-block formatting fixed

QS guide, fixed the code-block

---

product_docs/docs/epas/13/epas_qs_linux_8/index.mdx

QS 8 Guide, code block fixed

---

product_docs/docs/epas/13/epas_qs_windows/index.mdx

Image name that was missing added to the bottom of the image

Image name added to the bottom of the image

---

product_docs/docs/epas/13/epas_rel_notes/index.mdx

Release notes updated with minor tweaks

Updated release notes with minor tweaks

---

product_docs/docs/epas/13/epas_compat_bip_guide/02_packages/01_package_components.mdx
product_docs/docs/epas/13/epas_compat_bip_guide/02_packages/02_creating_packages.mdx
product_docs/docs/epas/13/epas_compat_bip_guide/02_packages/03_referencing_a_package.mdx
product_docs/docs/epas/13/epas_compat_bip_guide/02_packages/04_using_packages_with_user_defined_types.mdx
product_docs/docs/epas/13/epas_compat_bip_guide/02_packages/05_dropping_a_package.mdx
product_docs/docs/epas/13/epas_compat_bip_guide/02_packages/index.mdx
product_docs/docs/epas/13/epas_compat_bip_guide/03_built-in_packages/01_dbms_alert.mdx
product_docs/docs/epas/13/epas_compat_bip_guide/03_built-in_packages/index.mdx

Formatting fixes

---

product_docs/docs/epas/13/epas_upgrade_guide/03_limitations.mdx
product_docs/docs/epas/13/epas_upgrade_guide/04_upgrading_an_installation_with_pg_upgrade/01_performing_an_upgrade/index.mdx
product_docs/docs/epas/13/epas_upgrade_guide/04_upgrading_an_installation_with_pg_upgrade/02_invoking_pg_upgrade/01_command_line_options_reference.mdx
product_docs/docs/epas/13/epas_upgrade_guide/04_upgrading_an_installation_with_pg_upgrade/02_invoking_pg_upgrade/index.mdx
product_docs/docs/epas/13/epas_upgrade_guide/04_upgrading_an_installation_with_pg_upgrade/03_upgrading_to_advanced_server.mdx
product_docs/docs/epas/13/epas_upgrade_guide/04_upgrading_an_installation_with_pg_upgrade/04_upgrading_a_pgAgent_installation.mdx
product_docs/docs/epas/13/epas_upgrade_guide/04_upgrading_an_installation_with_pg_upgrade/05_pg_upgrade_troubleshooting.mdx
product_docs/docs/epas/13/epas_upgrade_guide/04_upgrading_an_installation_with_pg_upgrade/index.mdx
product_docs/docs/epas/13/epas_upgrade_guide/05_performing_a_minor_version_update_of_an_rpm_installation.mdx
product_docs/docs/epas/13/epas_upgrade_guide/06_using_stackbuilder_plus_to_perform_a_minor_version_update.mdx
product_docs/docs/epas/13/epas_upgrade_guide/07_migration.mdx

Formatting issues fixed for upgrade guide

Formatting issues fixed for upgrade guide

---

product_docs/docs/epas/13/epas_compat_bip_guide/03_built-in_packages/04_dbms_crypto/01_decrypt.mdx
product_docs/docs/epas/13/epas_compat_bip_guide/03_built-in_packages/04_dbms_crypto/02_encrypt.mdx
product_docs/docs/epas/13/epas_compat_bip_guide/03_built-in_packages/04_dbms_crypto/03_hash.mdx
product_docs/docs/epas/13/epas_compat_bip_guide/03_built-in_packages/04_dbms_crypto/04_mac.mdx
product_docs/docs/epas/13/epas_compat_bip_guide/03_built-in_packages/04_dbms_crypto/05_randombytes.mdx
product_docs/docs/epas/13/epas_compat_bip_guide/03_built-in_packages/04_dbms_crypto/06_randominteger.mdx
product_docs/docs/epas/13/epas_compat_bip_guide/03_built-in_packages/04_dbms_crypto/07_randomnumber.mdx
product_docs/docs/epas/13/epas_compat_bip_guide/03_built-in_packages/04_dbms_crypto/index.mdx
yarn.lock

DBMS_CRYPTO package formatting issues fixed

DBMS_CRYPTO package formatting issues fixed

---

product_docs/scripts/sort_toc_nested.py

Couple updates to support PEM 8.0 online documentation conversion
- handle multiple TOCs in a file
- be slightly more robust
- better naming

Update sort_toc_nested.py (Juicer script)

---

product_docs/docs/epas/13/epas_compat_bip_guide/02_packages/01_package_components.mdx
product_docs/docs/epas/13/epas_compat_bip_guide/03_built-in_packages/02_dbms_aq/01_enqueue.mdx
product_docs/docs/epas/13/epas_compat_bip_guide/03_built-in_packages/02_dbms_aq/02_dequeue.mdx
product_docs/docs/epas/13/epas_compat_bip_guide/03_built-in_packages/02_dbms_aq/03_register.mdx
product_docs/docs/epas/13/epas_compat_bip_guide/03_built-in_packages/02_dbms_aq/04_unregister.mdx
product_docs/docs/epas/13/epas_compat_bip_guide/03_built-in_packages/03_dbms_aqadm/04_create_queue_table.mdx
product_docs/docs/epas/13/epas_compat_bip_guide/03_built-in_packages/03_dbms_aqadm/07_purge_queue_table.mdx
product_docs/docs/epas/13/epas_compat_reference/02_the_sql_language/02_data_types/04_date_time_types.mdx

Revert "Sd/content/epas/13/reference guide/formatting fixes data types"

---

src/components/footer.js

Put actual links in the footer instead of dead links.

Updated links in footer

---

product_docs/docs/epas/13/epas_compat_bip_guide/03_built-in_packages/03_dbms_aqadm/index.mdx
product_docs/docs/epas/13/epas_compat_bip_guide/03_built-in_packages/04_dbms_crypto/01_decrypt.mdx
product_docs/docs/epas/13/epas_compat_bip_guide/03_built-in_packages/04_dbms_crypto/02_encrypt.mdx
product_docs/docs/epas/13/epas_compat_bip_guide/03_built-in_packages/05_dbms_job/01_broken.mdx
product_docs/docs/epas/13/epas_compat_bip_guide/03_built-in_packages/05_dbms_job/02_change.mdx
product_docs/docs/epas/13/epas_compat_bip_guide/03_built-in_packages/05_dbms_job/03_interval.mdx
product_docs/docs/epas/13/epas_compat_bip_guide/03_built-in_packages/05_dbms_job/04_next_date.mdx
product_docs/docs/epas/13/epas_compat_bip_guide/03_built-in_packages/05_dbms_job/05_remove.mdx
product_docs/docs/epas/13/epas_compat_bip_guide/03_built-in_packages/05_dbms_job/06_run.mdx
product_docs/docs/epas/13/epas_compat_bip_guide/03_built-in_packages/05_dbms_job/07_submit.mdx
product_docs/docs/epas/13/epas_compat_bip_guide/03_built-in_packages/05_dbms_job/08_what.mdx
product_docs/docs/epas/13/epas_compat_bip_guide/03_built-in_packages/05_dbms_job/index.mdx
product_docs/docs/epas/13/epas_compat_bip_guide/03_built-in_packages/16_dbms_session.mdx
product_docs/docs/epas/13/epas_compat_reference/02_the_sql_language/02_data_types/02_character_types.mdx

BIP guide formatting fixed for dbms_job, dbms_aqadm package

BIP guide formatting fixes

---

product_docs/docs/efm/4.1/efm_pgpool_ha_guide/03_components_ha_pgpool.mdx
product_docs/docs/epas/13/epas_compat_spl/03_variable_declarations/index.mdx
product_docs/docs/epas/13/epas_compat_spl/08_static_cursors/index.mdx
product_docs/docs/pem/7.10/pem_ent_feat/04_performance_monitoring_and_management.mdx
product_docs/docs/pem/7.11/pem_ent_feat/04_performance_monitoring_and_management.mdx
product_docs/docs/pem/7.12/pem_ent_feat/04_performance_monitoring_and_management.mdx
product_docs/docs/pem/7.13/pem_ent_feat/05_performance_monitoring_and_management.mdx
product_docs/docs/pem/7.15/pem_ent_feat/04_performance_monitoring_and_management.mdx
product_docs/docs/pem/7.16/pem_ent_feat/04_performance_monitoring_and_management.mdx
product_docs/docs/pem/8.0/pem_ent_feat/04_performance_monitoring_and_management.mdx
product_docs/docs/pem/8.0/pem_online_help/04_toc_pem_features/07_pem_postgres_expert/03_pe_configuration_expert_recommendations.mdx
product_docs/docs/pem/8.0/pem_online_help/12_release_notes/04_pem_release_notes_7_14.mdx

Forgot to save like... Half the files i'd been working on in #718

Fix things that aren't really RST links

---

product_docs/docs/bart/2.5.1/bart_inst_guide/03_configuration.mdx
product_docs/docs/bart/2.6.1/bart_inst/03_configuring_bart.mdx
product_docs/docs/bart/2.6.1/bart_user/02_overview/01_block-level_incremental_backup/01_incremental_backup_limitations_and_requirements.mdx
product_docs/docs/bart/2.6.1/bart_user/03_using_bart/01_bart_management_overview/02_point_in_time_recovery_operation.mdx
product_docs/docs/bart/2.6.1/bart_user/03_using_bart/02_managing_backups_using_a_retention_policy/01_overview_managing_backups_using_a_retention_policy.mdx
product_docs/docs/bart/2.6.1/bart_user/03_using_bart/02_managing_backups_using_a_retention_policy/04_managing_the_backups_based_on_the_retention_policy.mdx
product_docs/docs/migration_toolkit/53.0.0/04_functionality_overview.mdx
product_docs/docs/migration_toolkit/53.0.0/06_building_toolkit.properties_file.mdx
product_docs/docs/migration_toolkit/53.0.1/06_building_toolkit.properties_file.mdx
product_docs/docs/migration_toolkit/54.0.0/06_building_toolkit.properties_file.mdx

Fixes for misc formatting issues; collecting these as I go through bugs
Fixes #623
Fixes #621 
Fixes #619
...others noted in commits

Misc formatting

---

product_docs/docs/pem/8.0/pem_inst_guide_windows/02_pem_hardware_software_requirements.mdx
product_docs/docs/pem/8.0/pem_inst_guide_windows/03_pem_architecture.mdx
product_docs/docs/pem/8.0/pem_inst_guide_windows/04_installing_postgres_enterprise_manager/01_installing_pem_server_on_windows.mdx
product_docs/docs/pem/8.0/pem_inst_guide_windows/04_installing_postgres_enterprise_manager/02_installing_pem_agent_on_windows.mdx
product_docs/docs/pem/8.0/pem_inst_guide_windows/05_the_pem_web_interface.mdx
product_docs/docs/pem/8.0/pem_inst_guide_windows/06_uninstalling_pem_components.mdx

Formatting issues are fixed

---

src/html.js

- Add html.js file, previously handled by gatsby. Only change from gatsby's default file is a tweak to the viewport tag, and a warning against making other changes

Add html.js file

---

product_docs/docs/pem/8.0/pem_security_best_practices/01_apache_httpd_security_configuration.mdx
product_docs/docs/pem/8.0/pem_security_best_practices/02_pem_application_configuration.mdx

Formatting issues fixed for PEM Security Guide

Formatting issues fixed for PEM Security Guide

---

product_docs/docs/pem/8.0/pem_sqlprofiler/01_installing_the_sql_profiler_plugin.mdx
product_docs/docs/pem/8.0/pem_sqlprofiler/02_using_sql_profiler.mdx

Formatting issues fixed for PEM SQL Profiler Guide

Formatting issues fixed for PEM SQL Profiler Guide

---

src/templates/doc-stub.js
src/templates/doc.js

Show product in title when within a products docs

---

product_docs/docs/epas/13/epas_compat_bip_guide/03_built-in_packages/11_dbms_profiler.mdx
product_docs/docs/epas/13/epas_compat_bip_guide/03_built-in_packages/12_dbms_random.mdx
product_docs/docs/epas/13/epas_compat_bip_guide/03_built-in_packages/13_dbms_redact.mdx

Huge table fixed...pls merge so that I can verify it on staging

BIP guide table fixes

---

product_docs/docs/epas/13/epas_compat_bip_guide/03_built-in_packages/18_dbms_utility.mdx
product_docs/docs/epas/13/epas_compat_bip_guide/03_built-in_packages/19_utl_encode/01_base64_decode.mdx
product_docs/docs/epas/13/epas_compat_bip_guide/03_built-in_packages/19_utl_encode/02_base64_encode.mdx
product_docs/docs/epas/13/epas_compat_bip_guide/03_built-in_packages/19_utl_encode/03_mimeheader_decode.mdx
product_docs/docs/epas/13/epas_compat_bip_guide/03_built-in_packages/19_utl_encode/04_mimeheader_encode.mdx
product_docs/docs/epas/13/epas_compat_bip_guide/03_built-in_packages/19_utl_encode/05_quoted_printable_decode.mdx
product_docs/docs/epas/13/epas_compat_bip_guide/03_built-in_packages/19_utl_encode/06_quoted_printable_encode.mdx
product_docs/docs/epas/13/epas_compat_bip_guide/03_built-in_packages/19_utl_encode/07_text_decode.mdx
product_docs/docs/epas/13/epas_compat_bip_guide/03_built-in_packages/19_utl_encode/08_text_encode.mdx
product_docs/docs/epas/13/epas_compat_bip_guide/03_built-in_packages/19_utl_encode/09_uudecode.mdx
product_docs/docs/epas/13/epas_compat_bip_guide/03_built-in_packages/19_utl_encode/10_uuencode.mdx
product_docs/docs/epas/13/epas_compat_bip_guide/03_built-in_packages/19_utl_encode/index.mdx

dbms-utility fixes

---

product_docs/docs/pem/8.0/pem_pgbouncer/02_preparing_the_pem_database_server.mdx
product_docs/docs/pem/8.0/pem_pgbouncer/03_configuring_pgBouncer.mdx
product_docs/docs/pem/8.0/pem_pgbouncer/04_configuring_the_pem_agent.mdx

Table Format is fixed in PEM Enterprise Features Guide

Formatting issues fixed for PEM PgBouncer Configuration

---

README.md

Also prettier formatted README.
Changes of interest are in https://github.com/EnterpriseDB/docs/pull/871/commits/8298e708279e1b43ba3cccb47e677d71244c16b5.

Update README with more robust troubleshooting steps

---

product_docs/docs/pem/8.0/pem_admin/01_overview.mdx
product_docs/docs/pem/8.0/pem_admin/02_registering_server.mdx
product_docs/docs/pem/8.0/pem_admin/04_managing_certificates.mdx
product_docs/docs/pem/8.0/pem_admin/07_managing_pem_agent.mdx

Formatting issues and hyperlink fix for PEM Admin Guide

Formatting issues and hyperlink fix for PEM Admin Guide

---

product_docs/docs/pem/8.0/pem_online_help/01_toc_pem_getting_started/01_pem_architecture.mdx
product_docs/docs/pem/8.0/pem_online_help/01_toc_pem_getting_started/02_pem_server_logon.mdx
product_docs/docs/pem/8.0/pem_online_help/01_toc_pem_getting_started/03_pem_managing_configuration_settings.mdx
product_docs/docs/pem/8.0/pem_online_help/01_toc_pem_getting_started/04_pem_roles.mdx
product_docs/docs/pem/8.0/pem_online_help/01_toc_pem_getting_started/05_group_dialog.mdx
product_docs/docs/pem/8.0/pem_online_help/01_toc_pem_getting_started/06_auto_discovery_dialog.mdx
product_docs/docs/pem/8.0/pem_online_help/01_toc_pem_getting_started/07_pem_define_connection.mdx
product_docs/docs/pem/8.0/pem_online_help/01_toc_pem_getting_started/09_pem_connect_to_server.mdx
product_docs/docs/pem/8.0/pem_online_help/01_toc_pem_getting_started/10_control_server.mdx
product_docs/docs/pem/8.0/pem_online_help/01_toc_pem_getting_started/11_connect_error.mdx
product_docs/docs/pem/8.0/pem_online_help/01_toc_pem_getting_started/index.mdx

Formatting issues fixed for Getting Started topic of PEM Online Help

Formatting issues fixed for Getting Started topic of PEM Online Help

---

product_docs/docs/pem/8.0/pem_upgrade/01_upgrading_pem_installation/02_upgrading_pem_installation_linux_rpm.mdx
product_docs/docs/pem/8.0/pem_upgrade/01_upgrading_pem_installation/04_upgrading_pem_installation_linux_graphical.mdx
product_docs/docs/pem/8.0/pem_upgrade/02_upgrading_backend_database.mdx
product_docs/docs/pem/8.0/pem_upgrade/03_moving_pem_server.mdx

Formatting issues and hyperlink fix for PEM Upgrade guide

Formatting issues and hyperlink fix for PEM Upgrade guide

---

advocacy_docs/supported-open-source/barman/index.mdx
advocacy_docs/supported-open-source/barman/tutorials/index.mdx
advocacy_docs/supported-open-source/pgadmin/index.mdx
advocacy_docs/supported-open-source/pgbackrest/index.mdx
advocacy_docs/supported-open-source/postgresql/index.mdx
src/components/advanced-search/filtering.js

- Add product to supported-open-source stubs frontmatter
- Fix bug in advanced search filtering to enable filtering of non versioned products
Addresses #770

Show advocacy_doc product stubs (barman, pgbackrest, etc) in advanced search product filtering

---

product_docs/docs/pem/8.0/pem_inst_guide_windows/03_pem_architecture.mdx

Hyperlink fix for PEM Windows Installation guide

Hyperlink fix for PEM Windows Installation guide

---

product_docs/docs/epas/13/edb_plus/03_installing_edb_plus.mdx

edbplus guide image caption fix

Image caption fix

---

src/components/advanced-search/filtering.js
src/components/advanced-search/queryParams.js
src/components/advanced-search/results.js

- Convert underlying product/version faceting to use refinementList instead of hierarchicalMenu
Addresses #876

Fix missing facets when no result in facet (Advanced Search) 

---

advocacy_docs/playground/1/01_examples/admonitions.mdx
gatsby-config.js
package.json
src/styles/_admonitions.scss
src/styles/_dark.scss
src/styles/index.scss
yarn.lock

May need more styling, I just went with the most basic bootstrap styling and a simple default icon to replace the default

Add admonitions, and basic example page in playground

---

product_docs/docs/migration_toolkit/54.0.0/05_installing_mtk.mdx

Revert "removed rhel 6 support"

---

advocacy_docs/community/authoring/index.mdx

This may need some elaboration, lemme know what you think @shannon7wallace

add note about syncing with the develop branch

---

src/components/search/index.js
src/pages/404.js
src/pages/search.js

Also swap out algolia search keys for the generic one, instead of the one tied to Ed's account.

Strip pathPrefix from 404 advanced search query link

---

advocacy_docs/supported-open-source/pgbackrest/index.mdx

last quick change to #935 undid all the careful planning to avoid having to reconcile these

pgBackRest - forgot I changed this key

---

product_docs/docs/epas/13/epas_guide/03_database_administration/01_configuration_parameters/03_configuration_parameters_by_functionality/07_auditing_settings/09_edb_audit_statement.mdx
product_docs/docs/epas/13/epas_guide/03_database_administration/05_edb_audit_logging/01_audit_logging_configuration_parameters.mdx
product_docs/docs/epas/13/epas_guide/03_database_administration/05_edb_audit_logging/02_selecting_sql_statements_to_audit.mdx
product_docs/docs/epas/13/epas_guide/03_database_administration/05_edb_audit_logging/03_enabling_audit_logging.mdx

Feature enhancement for EDB Auditing section: SET parameter included in the documentation.

DB-904 SET parameter added to EDB Audting

---

product_docs/docs/pem/8.0/pem_inst_guide_linux/02_pem_hardware_software_requirements.mdx

Removed extra tags from PEM Linux Installation guide

Removed extra tags from PEM Linux Installation guide

---

product_docs/docs/pem/8.0/pem_inst_guide_linux/02_pem_hardware_software_requirements.mdx

Added note to PEM Linux Installation guide

Added note to PEM Linux Installation guide

---

docs/proposals/branch-and-release/README.md

[View rendered version](https://github.com/EnterpriseDB/docs/tree/proposal/george/branch-and-release/docs/proposals/branch-and-release).

Propose branch and release strategies

---

product_docs/docs/epas/13/epas_compat_bip_guide/index.mdx
product_docs/docs/epas/13/epas_compat_cat_views/index.mdx
product_docs/docs/epas/13/epas_compat_ora_dev_guide/index.mdx
product_docs/docs/epas/13/epas_compat_reference/index.mdx
product_docs/docs/epas/13/epas_compat_sql/index.mdx
product_docs/docs/epas/13/epas_compat_tools_guide/index.mdx
product_docs/docs/epas/13/epas_guide/index.mdx
product_docs/docs/epas/13/epas_security_guide/index.mdx
product_docs/docs/epas/13/index.mdx
product_docs/docs/migration_toolkit/54.0.0/index.mdx
src/constants/product-stubs.js

Delete all TM and (r) symbols

---

advocacy_docs/supported-open-source/postgresql/index.mdx

Update PostgreSQL index.mdx

---

src/pages/index.js

adding private, public, hybrid copy to the CNP teaser

home page hero copy update

---

scripts/pdf/generate_pdf.py

- for review only! the site will not serve these pdfs

Enable basic generation of pdfs for individual guides

---

product_docs/docs/epas/13/edb_pgadmin_linux_qs/index.mdx

Merge with develop epas 13 branch and publish on EDB website.

Removed RHEL/CentOS 6.x references

---

product_docs/docs/epas/13/epas_compat_cat_views/02_all_all_tables.mdx
product_docs/docs/epas/13/epas_compat_cat_views/23_all_tab_partitions.mdx
product_docs/docs/epas/13/epas_compat_cat_views/24_all_tab_subpartitions.mdx
product_docs/docs/epas/13/epas_compat_cat_views/26_all_tables.mdx
product_docs/docs/epas/13/epas_compat_cat_views/32_dba_all_tables.mdx
product_docs/docs/epas/13/epas_compat_cat_views/56_dba_tab_partitions.mdx
product_docs/docs/epas/13/epas_compat_cat_views/57_dba_tab_subpartitions.mdx
product_docs/docs/epas/13/epas_compat_cat_views/59_dba_tables.mdx
product_docs/docs/epas/13/epas_compat_cat_views/65_user_all_tables.mdx
product_docs/docs/epas/13/epas_compat_cat_views/84_user_tab_partitions.mdx
product_docs/docs/epas/13/epas_compat_cat_views/85_user_tab_subpartitions.mdx
product_docs/docs/epas/13/epas_compat_cat_views/87_user_tables.mdx

Merge with v13 branch on develop and publish on EDB website.

DB-906 add tablespace name in case of default tablespace in dba_*views -Reviewed by Rohit

---

product_docs/docs/epas/13/language_pack/01_supported_database_server_versions.mdx

Language pack

---

product_docs/docs/migration_portal/3.0.1/02_supported_platforms.mdx
product_docs/docs/migration_portal/3.0.1/index.mdx

updated the title supported versions in the index

---

product_docs/docs/pem/8.0/pem_online_help/11_appendices/02_kerberos.mdx

Reverts EnterpriseDB/docs#1065

Revert "Update 02_kerberos.mdx"

---

advocacy_docs/playground/demo/index.mdx

Working on performance tutorial outline

---

product_docs/docs/epas/13/epas_inst_linux/03_using_a_package_manager_to_install_advanced_server.mdx

Minor tweaks to linux guide, pls publish the same on docs 2.0 site

Minor tweaks to Linux guide

---

gatsby-node.js
src/components/back-button.js
src/components/left-nav.js
src/templates/katacoda-page.js

- Change "<-  Back" link to always go to home page
- Fix KatacodaPage path generation
**Content**

Change back link (<- Back) behaviour

---

src/constants/algolia-indexing.js

- Update algolia indexing to use /latest paths, avoiding redirects
- Add new `pagePath` attribute for deduping
**Content**

Use latest paths in algolia search

---

product_docs/docs/eprs/6.2/01_introduction/index.mdx

fixing_issues commit to develop

---

product_docs/docs/bart/2.6.2/bart_inst/04_upgrading_bart.mdx

Removed Upgrade from 2.0 section in the BART 2.6.2 Installation Guide
**Content**
-`[x]` This PR removes existing content

Removed_upgrade_from_2.0_section

---

src/components/advanced-search/results.js
src/components/card-decks.js
src/components/search/formComps.js
src/components/search/index.js
src/styles/_dark.scss
src/styles/_search.scss

* orange fill for icon in card decks
* improving legibility of search results, badge counts in quick search and advanced search
* dark mode for both types of search
* added a border to the search input to make it easier to see

Visual Enhancements

---

src/pages/index.js

Updating homepage to reflect the information architecture described in issue #1109 
**Content**

Updating homepage links

---

docs/overviews/search/README.md

- add search overview doc
**Content**

Add search overview doc

---

product_docs/docs/bart/2.6.2/bart_inst/04_upgrading_bart.mdx
product_docs/docs/bart/2.6.2/bart_inst/index.mdx

- Added Upgrade commands for Zypper and Debian hosts
**Content**

Edited_Upgrade_Section

---

product_docs/docs/pgpool/1.0/01_installing_and_configuring_the_pgpool-II.mdx
product_docs/docs/pgpool/1.0/02_extensions.mdx
product_docs/docs/pgpool/1.0/03_configuring_connection_pooling.mdx
product_docs/docs/pgpool/1.0/04_connecting_a_client_to_pgpool-II.mdx
product_docs/docs/pgpool/1.0/05_upgrade.mdx
product_docs/docs/pgpool/1.0/06_uninstalling_pgpool-II.mdx
product_docs/docs/pgpool/1.0/index.mdx

- Added RHEL8 support on EPAS11
**Content**

D_746_Pgpool_Updates

---

.husky/_/husky.sh
product_docs/docs/bart/2.6.2/bart_inst/04_upgrading_bart.mdx
product_docs/docs/bart/2.6.2/bart_inst/index.mdx
product_docs/docs/bart/2.6.2/bart_qs_7/index.mdx
product_docs/docs/bart/2.6.2/bart_qs_8/index.mdx
product_docs/docs/bart/2.6.2/bart_user/03_using_bart/04_running_the_bart_wal_scanner.mdx

- Removed_third digit version number
**Content**

removed_third_digit_version_number

---

product_docs/docs/postgis/1.0/01_installing_postgis.mdx
product_docs/docs/postgis/1.0/03_upgrading_postgis.mdx
product_docs/docs/postgis/1.0/04_using_postgis.mdx
product_docs/docs/postgis/1.0/05_uninstalling_postgis.mdx
product_docs/docs/postgis/1.0/index.mdx

- Added RHEL8 for EPAS11
**Content**

EPAS11_RHEL8_Update

---

gatsby-config.js
src/styles/_admonitions.scss

Add a "Hint" admonition type - this is used in a couple of places in the CNP docs. Ex:
```
!!! Hint
Some sort of informational content
```
Just re-using the styling for "tip" since these seem logically identical.
**Content**

add "hint" admonition type for CNP

---

product_docs/docs/bart/2.6/bart_inst/index.mdx

- Removed third-digit minor version number in index file.
**Content**

minor_update

---

product_docs/docs/epas/12/epas_security_guide/02_protecting_against_sql_injection_attacks/02_configuring_sql_protect.mdx
product_docs/docs/epas/12/epas_security_guide/02_protecting_against_sql_injection_attacks/03_common_maintenance_operations.mdx
product_docs/docs/epas/12/epas_security_guide/02_protecting_against_sql_injection_attacks/04_backing_up_restoring_sql_protect.mdx
product_docs/docs/epas/12/epas_security_guide/05_data_redaction.mdx
product_docs/docs/epas/13/epas_security_guide/02_protecting_against_sql_injection_attacks/02_configuring_sql_protect.mdx
product_docs/docs/epas/13/epas_security_guide/02_protecting_against_sql_injection_attacks/03_common_maintenance_operations.mdx
product_docs/docs/epas/13/epas_security_guide/05_data_redaction.mdx

Updated the Security Features Guides for v12 release.
**Content**

Security Features Guides fixes

---

product_docs/docs/epas/13/epas_compat_table_partitioning/03_using_partition_pruning/01_example_partition_pruning.mdx
product_docs/docs/epas/13/epas_compat_table_partitioning/04_partitioning_commands_compatible_with_oracle_databases/01_create_table_partition_by/07_example_partition_by_range_subpartition_by_list.mdx
product_docs/docs/epas/13/epas_compat_table_partitioning/04_partitioning_commands_compatible_with_oracle_databases/01_create_table_partition_by/index.mdx
product_docs/docs/epas/13/epas_compat_table_partitioning/04_partitioning_commands_compatible_with_oracle_databases/02_alter_table_add_partition/index.mdx
product_docs/docs/epas/13/epas_compat_table_partitioning/04_partitioning_commands_compatible_with_oracle_databases/03_alter_table_add_subpartition/01_example_adding_a_subpartition_to_a_list_range_partitioned_table.mdx
product_docs/docs/epas/13/epas_compat_table_partitioning/04_partitioning_commands_compatible_with_oracle_databases/03_alter_table_add_subpartition/02_example_adding_a_subpartition_to_a_range_list_partitioned_table.mdx
product_docs/docs/epas/13/epas_compat_table_partitioning/04_partitioning_commands_compatible_with_oracle_databases/03_alter_table_add_subpartition/index.mdx
product_docs/docs/epas/13/epas_compat_table_partitioning/04_partitioning_commands_compatible_with_oracle_databases/04_alter_table_split_partition/index.mdx
product_docs/docs/epas/13/epas_compat_table_partitioning/04_partitioning_commands_compatible_with_oracle_databases/05_alter_table_split_subpartition/01_example_splitting_a_list_subpartition.mdx
product_docs/docs/epas/13/epas_compat_table_partitioning/04_partitioning_commands_compatible_with_oracle_databases/05_alter_table_split_subpartition/02_example_splitting_a_range_subpartition.mdx
product_docs/docs/epas/13/epas_compat_table_partitioning/04_partitioning_commands_compatible_with_oracle_databases/10_alter_table_set_partitioning_automatic/01_example_setting_an_automatic_list_partition.mdx
product_docs/docs/epas/13/epas_compat_table_partitioning/05_handling_stray_values_in_a_list_or_range_partitioned_table.mdx
product_docs/docs/epas/13/epas_compat_table_partitioning/06_specifying_multiple_partitioning_keys_in_a_range_partitioned_table.mdx

Minor tweaks to the table partitioning guide to make it consistent.
**Content**

Minor tweaks to table partitioning guide

---

product_docs/docs/bdr/3.6/index.mdx

* fixes for #1243 and #1206
**Content**

Amendments to BDR via issues

---

advocacy_docs/supported-open-source/pgbackrest/06-use_case_1.mdx
advocacy_docs/supported-open-source/pgbackrest/07-use_case_2.mdx
advocacy_docs/supported-open-source/pgbackrest/index.mdx

- pgBackRest 2.33 is released
- GCS support added
**Content**

bump pgBackRest release to 2.33

---

product_docs/docs/jdbc_connector/42.2.19.1/02_requirements_overview.mdx
product_docs/docs/jdbc_connector/42.2.19.1/04_installing_and_configuring_the_jdbc_connector/02_installing_the_connector_on_an_sles_12_host.mdx

Fixed review comments for platform support page and SLES installation steps.
**Content**

Fixed review comments

---

product_docs/docs/efm/4.2/efm_pgpool_ha_guide/03_components_ha_pgpool.mdx

Fixed review comments from Pgpool developers regarding additional parameter configuration required only for Pgpool 4.2 integration.
**Content**

Fixing review comment for EFM HA Guide

---

product_docs/docs/pem/7.16/pem_upgrade/01_upgrading_pem_installation/01_upgrading_pem_installation_windows.mdx
product_docs/docs/pem/7.16/pem_upgrade/01_upgrading_pem_installation/04_upgrading_pem_installation_linux_graphical.mdx
product_docs/docs/pem/7.16/pem_upgrade/01_upgrading_pem_installation/index.mdx
product_docs/docs/pem/7.16/pem_upgrade/02_upgrading_backend_database.mdx
product_docs/docs/pem/7.16/pem_upgrade/03_moving_pem_server.mdx
product_docs/docs/pem/7.16/pem_upgrade/index.mdx

Updated the content of the PEM 7.16 Upgrade and Migration guide.
**Content**

Updated the content of PEM 7.16 upgrade guide

---

product_docs/docs/pem/7.16/pem_inst_guide_linux/01_whats_new.mdx
product_docs/docs/pem/7.16/pem_inst_guide_linux/02_pem_hardware_software_requirements.mdx
product_docs/docs/pem/7.16/pem_inst_guide_linux/03_pem_architecture.mdx
product_docs/docs/pem/7.16/pem_inst_guide_linux/04_installing_postgres_enterprise_manager/01_prerequisites_for_installing_pem_server.mdx
product_docs/docs/pem/7.16/pem_inst_guide_linux/04_installing_postgres_enterprise_manager/02_installing_pem_server_and_apache_web_server_preferences.mdx
product_docs/docs/pem/7.16/pem_inst_guide_linux/04_installing_postgres_enterprise_manager/03_installing_pem_server_on_linux.mdx
product_docs/docs/pem/7.16/pem_inst_guide_linux/04_installing_postgres_enterprise_manager/05_configuring_the_pem_server_on_linux.mdx
product_docs/docs/pem/7.16/pem_inst_guide_linux/04_installing_postgres_enterprise_manager/06_installing_pem_agent_on_linux.mdx
product_docs/docs/pem/7.16/pem_inst_guide_linux/05_the_pem_web_interface.mdx

Updated the screenshots and content of PEM Linux Installation guide 7.16
Updated the screenshots and content of PEM Linux Installation guide 7.16
**Content**

Updated PEM 7.16 Linux Installation guide

---

product_docs/docs/pem/7.16/pem_inst_guide_windows/01_whats_new.mdx
product_docs/docs/pem/7.16/pem_inst_guide_windows/02_pem_hardware_software_requirements.mdx
product_docs/docs/pem/7.16/pem_inst_guide_windows/03_pem_architecture.mdx
product_docs/docs/pem/7.16/pem_inst_guide_windows/04_installing_postgres_enterprise_manager/01_installing_pem_server_on_windows.mdx

Updated the content of PEM 7.16 Windows Installation guide
**Content**

Updated PEM 7.16 Windows Installation guide

---

product_docs/docs/epas/13/epas_upgrade_guide/04_upgrading_an_installation_with_pg_upgrade/03_upgrading_to_advanced_server.mdx

Minor tweak to pg_upgrade guide.
**Content**

Minor tweak to pg_upgrade guide

---

product_docs/docs/pem/7.16/pem_sqlprofiler/02_using_sql_profiler.mdx

Updated the content of PEM 7.16 SQL Profiler Guide
**Content**

Updated the content of PEM 7.16 SQL Profiler Guide

---

product_docs/docs/pem/7.16/pem_bart/01_managing_bart.mdx

Updated the content of PEM 7.16 BART maangement guide
**Content**

Updated the content of PEM 7.16 BART maangement guide

---

build-sources.json
gatsby-config.js
product_docs/docs/repmgr/5.2.1/index.mdx
src/constants/products.js
src/pages/index.js

* adding repmgr stub
* link on homepage
**Content**

feature: adding repmgr stub

---

product_docs/docs/epas/13/edb_plus/03_installing_edb_plus.mdx
product_docs/docs/epas/13/edb_plus/04_using_edb_plus.mdx
product_docs/docs/epas/13/edb_plus/05_using_edb_plus_with_ssl.mdx
product_docs/docs/epas/13/edb_plus/06_command_summary.mdx

Minor tweaks to EDB*Plus guide, pls merge with develop.
**Content**

Minor tweaks to EDB Plus guide

---

advocacy_docs/kubernetes/cloud_native_postgresql/interactive/index.mdx
advocacy_docs/kubernetes/cloud_native_postgresql/interactive_demo.mdx

*fixed links on interactive demos page
**Content**

Hotfix: CNP links

---

product_docs/docs/epas/13/epas_guide/03_database_administration/01_configuration_parameters/03_configuration_parameters_by_functionality/01_top_performance_related_parameters/16_pg_prewarm.autoprewarm.mdx
product_docs/docs/epas/13/epas_guide/03_database_administration/02_index_advisor/02_index_advisor_configuration.mdx
product_docs/docs/epas/13/epas_guide/03_database_administration/02_index_advisor/03_using_index_advisor.mdx
product_docs/docs/epas/13/epas_guide/03_database_administration/02_index_advisor/04_reviewing_the_index_advisor_recommendations.mdx
product_docs/docs/epas/13/epas_guide/03_database_administration/04_pgsnmpd.mdx

Minor tweaks to code blocks, also corrected the parameter name for section preautoprewarm.
**Content**

Minor tweaks to code blocks

---

product_docs/docs/eprs/6.2/05_smr_operation/08_optimizing_performance/01_optimizing_snapshot_replication.mdx

**Examples**
- updated `\05_smr_operation\08_optimizing_performance\01_optimizing_snapshot_replication\` page
**Content**

Default value for useFastCopy is true

---

product_docs/docs/epas/13/epas_guide/03_database_administration/05_edb_audit_logging/02_selecting_sql_statements_to_audit.mdx
product_docs/docs/epas/13/epas_guide/03_database_administration/05_edb_audit_logging/03_enabling_audit_logging.mdx
product_docs/docs/epas/13/epas_guide/03_database_administration/06_unicode_collation_algorithm.mdx
product_docs/docs/epas/13/epas_guide/10_edb_resource_manager.mdx
product_docs/docs/epas/13/epas_guide/12_debugger.mdx
product_docs/docs/epas/13/epas_guide/13_performance_analysis_and_tuning.mdx
product_docs/docs/epas/13/epas_guide/14_edb_clone_schema.mdx
product_docs/docs/epas/13/epas_guide/15_enhanced_sql_and_other_misc_features.mdx
product_docs/docs/epas/13/epas_guide/16_system_catalog_tables.mdx

Fixed the code blocks and system catalog table info.
**Content**

Fixed the code blocks and system catalog table

---

product_docs/docs/jdbc_connector/42.2.19.1/02_requirements_overview.mdx

Added a sub-section for supported JDK distibution.
**Content**

Doc Update for EC-1419

---

advocacy_docs/supported-open-source/postgresql/installer/02_installing_postgresql_with_the_graphical_installation_wizard/index.mdx
advocacy_docs/supported-open-source/postgresql/installer/03_using_stackbuilder.mdx

Couple of Notes didn't get converted to admonition syntax in installer docs. This converts them.
**Content**

html notes -> admonitions

---

product_docs/docs/epas/13/epas_compat_table_partitioning/04_partitioning_commands_compatible_with_oracle_databases/06_alter_table_exchange_partition/01_example_exchanging_a_table_for_a_partition.mdx
product_docs/docs/epas/13/epas_compat_table_partitioning/04_partitioning_commands_compatible_with_oracle_databases/08_alter_table_rename_partition/01_example_renaming_a_partition.mdx
product_docs/docs/epas/13/epas_compat_table_partitioning/04_partitioning_commands_compatible_with_oracle_databases/13_alter_table_drop_partition/01_example_deleting_a_partition.mdx
product_docs/docs/epas/13/epas_compat_table_partitioning/04_partitioning_commands_compatible_with_oracle_databases/14_alter_table_drop_subpartition/01_example_deleting_a_subpartition.mdx
product_docs/docs/epas/13/epas_compat_table_partitioning/04_partitioning_commands_compatible_with_oracle_databases/15_truncate_table/01_example_emptying_a_table.mdx
product_docs/docs/epas/13/epas_compat_table_partitioning/06_specifying_multiple_partitioning_keys_in_a_range_partitioned_table.mdx

Code blocks fixed for readability.
**Content**

Code block fixed

---

advocacy_docs/supported-open-source/barman/single-server-streaming/step01-db-setup.mdx
advocacy_docs/supported-open-source/barman/single-server-streaming/step02-backup-setup.mdx
advocacy_docs/supported-open-source/barman/single-server-streaming/step03-backup.mdx
advocacy_docs/supported-open-source/barman/single-server-streaming/step04-restore.mdx

Robert created this new admonition type for the CNP demo, and it looks snazzy - should be consistent by using it here as well.
**Content**

Use the 'interactive' admonition type for barman demo

---

product_docs/docs/mongo_data_adapter/5.2.8/02_requirements_overview.mdx

Updated supported MongoDB C Driver as per FDW-263.
**Content**

Doc update for FDW-263

---

product_docs/docs/efm/4.2/efm_user/04_configuring_efm/01_cluster_properties/index.mdx

Updated cluster properties topic with notes
**Content**

Doc update for EFM-1436

---

README_DOCKER_VSCODE.md

* Without Git installed the clone step fails (silently?).
* I think the "isolated" is now called "unique" now.
**Content**

Updates found while installing on Windows for the first time.

---

product_docs/docs/epas/12/language_pack/01_supported_database_server_versions.mdx
product_docs/docs/epas/12/language_pack/03_using_the_procedural_languages.mdx

- Fixed broken links
**Content**

fixed_hyperlink

---

product_docs/docs/ocl_connector/12.1.2.1/04_open_client_library/01_installing_and_configuring_the_ocl_connector.mdx

- Fixed formatting
**Content**

minor_tweaks

---

product_docs/docs/epas/12/epas_compat_tools_guide/02_edb_loader.mdx
product_docs/docs/epas/13/epas_compat_tools_guide/02_edb_loader.mdx

Customer escalation ticket, pls merge and publish on docs 2.0.
**Content**

DB-1096 reviewed by Jeevan L

---

product_docs/docs/bdr/3.7/index.mdx

Adds a stub page for BDR 3.7 per John Dalton's request. Fixes #1348 
THIS SHOULD NOT BE MERGED UNTIL May 14th!
**Content**

add content for BDR 3.7 per issue #1348

---

product_docs/docs/efm/4.1/efm_user/04_configuring_efm/01_cluster_properties/index.mdx

Updated cluster properties for EFM-1436.
**Content**

Update for EFM-1436

---

product_docs/docs/hadoop_data_adapter/2.0.7/05_installing_the_hadoop_data_adapter.mdx

Updated the Installation topics for DF-230.
Fixed the alignment issues (a result of the conversion).
**Content**

Update for DF-230: Hadoop 2.0.7

---

product_docs/docs/mongo_data_adapter/5.2.8/04_installing_the_mongo_data_adapter.mdx

Updated the Installation topics for DF-230.
Fixed the alignment issues (a result of the conversion).
**Content**

Update for DF-230: MongoDB 5.2.8

---

product_docs/docs/mysql_data_adapter/2.5.5/04_installing_the_mysql_data_adapter.mdx

- Updated the Installation topics for DF-230. 
- Fixed the alignment issues (a result of the conversion).
**Content**

update for DF-230: MySQL 2.5.5

---

product_docs/docs/mysql_data_adapter/2.6.0/04_installing_the_mysql_data_adapter.mdx

Updated the Installation topics to incorporate the MySQL repo changes. 
**Content**

Updates for MySQL repo changes

---

product_docs/docs/mysql_data_adapter/2.6.0/01_whats_new.mdx
product_docs/docs/mysql_data_adapter/2.6.0/02_requirements_overview.mdx

- Fixed grammar and syntax in MySQL FDW 2.6.0 guide.
**Content**

Fixing grammer and syntax

---

product_docs/docs/jdbc_connector/42.2.12.3/04_installing_and_configuring_the_jdbc_connector/01_installing_the_connector_with_an_rpm_package.mdx

Updated the Installation topics for DF-229
**Content**

Updates for DF-229: JDBC 42.2.12.3

---

product_docs/docs/jdbc_connector/42.2.19.1/04_installing_and_configuring_the_jdbc_connector/01_installing_the_connector_with_an_rpm_package.mdx

Updated the Installation topics for DF-229
**Content**

Updates for DF-229: JDBC 42.2.19.1

---

product_docs/docs/odbc_connector/12.2.0.2/03_edb-odbc_overview/01_installing_edb-odbc.mdx

Updated the Installation topics for DF-229.
**Content**

Updates for DF-229: ODBC 12.2.0.2

---

product_docs/docs/ocl_connector/12.1.2.1/04_open_client_library/01_installing_and_configuring_the_ocl_connector.mdx

Updated the Installation topics for DF-229.
**Content**

Updates for DF-229: OCL 12.1.2.1

---

product_docs/docs/ocl_connector/13.1.4.2/04_open_client_library/01_installing_and_configuring_the_ocl_connector.mdx

Updated the Installation topics for DF-229.
**Content**

Updates for DF-229: OCL 13.1.4.2

---

product_docs/docs/odbc_connector/12.0.0.2/03_edb-odbc_overview/01_installing_edb-odbc.mdx

Updated the Installation topic for DF-229.
**Content**

Updates for DF-229: ODBC 12.0.0.2

---

product_docs/docs/postgis/1.0/01_installing_postgis.mdx

- Added note in the installing on Windows section
**Content**

Added_note

---

product_docs/docs/bart/2.5/bart_inst/index.mdx
product_docs/docs/bart/2.6/bart_inst/index.mdx

Changed "OEL" to "OL" in the BART Installation Guide version 2.5.
**Content**

DF-260_Bart_2.5

---

product_docs/docs/pgbouncer/1.0/01_installation/index.mdx
product_docs/docs/pgpool/1.0/01_installing_and_configuring_the_pgpool-II.mdx
product_docs/docs/postgis/1.0/01_installing_postgis.mdx
product_docs/docs/slony/1.0/01_installation/index.mdx

- Changed references of "OEL" to "OL" in DB-Infra guides.
**Content**

DF-260_DB-Infra

---

product_docs/docs/pem/8.0/pem_online_help/04_toc_pem_features/01_dashboards/03_database_analysis_dashboard.mdx
product_docs/docs/pem/8.0/pem_online_help/04_toc_pem_features/01_dashboards/05_io_analysis_dashboard.mdx
product_docs/docs/pem/8.0/pem_online_help/04_toc_pem_features/01_dashboards/08_os_analysis_dashboard.mdx
product_docs/docs/pem/8.0/pem_online_help/04_toc_pem_features/01_dashboards/12_session_activity_analysis_dashboard.mdx
product_docs/docs/pem/8.0/pem_online_help/04_toc_pem_features/01_dashboards/index.mdx

Fixed the toctree and other formatting issues for the Dashboards section in PEM 8.0 online help.
**Content**

Fixed the toctree and other formatting issues

---

advocacy_docs/supported-open-source/postgresql/installer/01_requirements_overview.mdx

- Removed the note as currently, we have documented only the installation on Windows.
**Content**

Removed the note

---

product_docs/docs/pem/8.0/pem_online_help/01_toc_pem_getting_started/index.mdx

Fixed the Toctree in the Pem Getting Started Section of PEM 8.0 Online Help
**Content**

Fixed the Toctree in the Pem Getting Started Section

---

product_docs/docs/pem/8.0/pem_online_help/02_toc_pem_agent/02_pem_agent_binding/01_pem_agent_config_params.mdx
product_docs/docs/pem/8.0/pem_online_help/02_toc_pem_agent/02_pem_agent_binding/index.mdx

Toctree and Formatting issues fixed for the PEM Agent Binding section of the PEM 8.0 Online Help
**Content**

Toctree and Formatting issues fixed

---

product_docs/docs/odbc_connector/12.0.0.2/06_edb-odbc_driver_functionality.mdx

Updated content for ADO users.
**Content**

Updating ODBC docs for EC-1699

---

product_docs/docs/postgis/1.0/01_installing_postgis.mdx

- Removed the statement about installing Advanced Server dependency in the Centos, RHEL, and Debian sections.
**Content**

PostGIS_Update_May27

---

product_docs/docs/odbc_connector/12.2.0.2/06_edb-odbc_driver_functionality.mdx

Included prerequisite for ADO users.
**Content**

Adding prereq for ADO users

---

product_docs/docs/efm/4.2/efm_user/11_supported_scenarios.mdx

Adding note in EFM 4.2 for DF-234

---

product_docs/docs/pem/8.0/pem_online_help/08_toc_pem_developer_tools/01_debugger.mdx
product_docs/docs/pem/8.0/pem_online_help/08_toc_pem_developer_tools/02_query_tool.mdx
product_docs/docs/pem/8.0/pem_online_help/08_toc_pem_developer_tools/04_editgrid/index.mdx
product_docs/docs/pem/8.0/pem_online_help/08_toc_pem_developer_tools/05_schema_diff.mdx
product_docs/docs/pem/8.0/pem_online_help/08_toc_pem_developer_tools/index.mdx

Toctree and formatting issues are fixed for the PEM Developer Tools Section in PEM 8.0 Online help.
**Content**

Toctree issue is fixed

---

product_docs/docs/pem/8.0/pem_online_help/06_toc_pem_bart_management/02_configuring_bart_server.mdx
product_docs/docs/pem/8.0/pem_online_help/06_toc_pem_bart_management/08_restoring_bart_backups.mdx
product_docs/docs/pem/8.0/pem_online_help/06_toc_pem_bart_management/index.mdx

Toctree issues fixed for the PEM BART Management section of PEM 8.0 Online help.
**Content**

Toctree issues fixed

---

product_docs/docs/efm/4.0/efm_user/11_supported_scenarios.mdx

Adding note in EFM 4.0 for DF-234

---

product_docs/docs/efm/4.1/efm_user/11_supported_scenarios.mdx

Adding note in EFM 4.1 for DF-234

---

product_docs/docs/epas/12/epas_inst_windows/02_requirements_overview.mdx
product_docs/docs/epas/13/epas_inst_windows/02_requirements_overview.mdx

Minor content tweaked in window guide.
**Content**

Minor tweaks to windows guide

---

product_docs/docs/jdbc_connector/42.2.12.3/02_requirements_overview.mdx
product_docs/docs/jdbc_connector/42.2.19.1/02_requirements_overview.mdx

Replaced OEL with OL.
**Content**

Content/jdbc connector/ev 259

---

advocacy_docs/supported-open-source/pgbackrest/08-multiple-repositories.mdx

Let's add the pgBackRest update as well. Full changelog:
* initial draft for multi repo feature
* Updated: 2021-04-20 12:16:44
* missing history files rephrasal
* fix after review
* fix after another review
* various updates after review
* various updates after review

pgBackRest multi-repo feature (#1264)

---

product_docs/docs/eprs/6.2/01_introduction/04_supported_jdk_versions.mdx

**Examples**
- Changed OEL to OL as per Oracle's new naming convention
**Content**

OEL Changes

---

advocacy_docs/supported-open-source/pgbackrest/02-installation.mdx
advocacy_docs/supported-open-source/pgbackrest/index.mdx

- Remove pgBackRest packages from EDB repos, per @sebasmannem request.
- Update latest pgBackRest release
**Content**

Remove pgBackRest packages from EDB repos

---

product_docs/docs/hadoop_data_adapter/2.0.7/02_requirements_overview.mdx
product_docs/docs/mongo_data_adapter/5.2.8/02_requirements_overview.mdx
product_docs/docs/mysql_data_adapter/2.5.5/02_requirements_overview.mdx
product_docs/docs/mysql_data_adapter/2.6.0/02_requirements_overview.mdx

OEL to OL changes in FDW Guides

---

product_docs/docs/efm/4.0/efm_user/05_using_efm.mdx
product_docs/docs/efm/4.1/efm_user/05_using_efm.mdx
product_docs/docs/efm/4.2/efm_user/05_using_efm.mdx

Updating 'Changing priority of a standby' section as per feedback by Development team
**Content**

Updating 'Changing priority of a standby' section

---

product_docs/docs/repmgr/5.2.1/index.mdx

Added paragraph per #1461 
**Content**
- [ x] This PR adds new content

Added text per #1461

---

build-sources.json
gatsby-config.js
product_docs/docs/harp/1.0/index.mdx
src/constants/products.js
src/pages/index.js

Fixes #1450 by adding a stub section for HARP based on https://docs.google.com/document/d/1ZsGRLAoHlATt1KOyZfCKlke6jOF6Zvk46pWEC4qFRnM/edit#
@sebasmannem if this is acceptable we'll build out tomorrow morning. Should match the doc; I added only a link to the BDR stub upon first use. Results can be viewed here: https://zen-clarke-09b685.netlify.app/docs/harp/latest/
**Content**

Add HARP stub

---

product_docs/docs/pem/8.1.0/pem_bart/index.mdx
product_docs/docs/pem/8.1.0/pem_ent_feat/01_what's_new.mdx
product_docs/docs/pem/8.1.0/pem_ent_feat/index.mdx
product_docs/docs/pem/8.1.0/pem_inst_guide_linux/01_whats_new.mdx
product_docs/docs/pem/8.1.0/pem_inst_guide_windows/01_whats_new.mdx
product_docs/docs/pem/8.1.0/pem_inst_guide_windows/02_pem_hardware_software_requirements.mdx
product_docs/docs/pem/8.1.0/pem_inst_guide_windows/03_pem_architecture.mdx
product_docs/docs/pem/8.1.0/pem_inst_guide_windows/index.mdx

Fixed some content in some guides of PEM 8.1.0
**Content**
- [ X ] This PR changes existing content

Fixed some content in some guides of PEM 8.1.0

---

product_docs/docs/pem/8.1.0/pem_admin/index.mdx
product_docs/docs/pem/8.1.0/pem_agent/01_pem_architecture.mdx
product_docs/docs/pem/8.1.0/pem_agent/index.mdx
product_docs/docs/pem/8.1.0/pem_ent_feat/index.mdx
product_docs/docs/pem/8.1.0/pem_inst_guide_linux/02_pem_hardware_software_requirements.mdx
product_docs/docs/pem/8.1.0/pem_inst_guide_linux/index.mdx
product_docs/docs/pem/8.1.0/pem_inst_guide_windows/02_pem_hardware_software_requirements.mdx
product_docs/docs/pem/8.1.0/pem_upgrade/index.mdx

The Note is removed and Typos are fixed from all the guides
**Content**

The Note is removed and Typos are fixed from all the guides

---

product_docs/docs/pem/8.1.0/pem_ent_feat/index.mdx

Used navigation directive for changing navigation.
**Content**

Fixed navigation for PEM Enterprise Features Guide

---

src/pages/index.js

Recategorizing HARP on dashboard

Fix per Sebastiaan moving title of HARP

---

.github/workflows/deploy-develop.yml
.github/workflows/deploy-main.yml
.github/workflows/update-pdfs-on-develop.yml

* Added a new clean disk job to all GitHub Actions to resolve #1458.

Cleanup disk space before building out.

---

advocacy_docs/kubernetes/cloud_native_postgresql/api_reference.mdx
advocacy_docs/kubernetes/cloud_native_postgresql/installation_upgrade.mdx
advocacy_docs/kubernetes/cloud_native_postgresql/interactive_demo.mdx
advocacy_docs/kubernetes/cloud_native_postgresql/operator_capability_levels.mdx
advocacy_docs/kubernetes/cloud_native_postgresql/operator_conf.mdx
advocacy_docs/kubernetes/cloud_native_postgresql/release_notes.mdx
merge_sources/kubernetes/cloud_native_postgresql/interactive_demo.mdx

Update CNP docs to version 1.5.1 (bugfix release)
**Content**

CNP 1.5.1 update

---

product_docs/docs/postgis/1.0/01_installing_postgis.mdx
product_docs/docs/slony/1.0/01_installation/index.mdx

- Changed references of OEL to OL
**Content**

Changed_OEL_to_OL

---

product_docs/docs/efm/4.2/efm_user/07_using_efm_utility.mdx

Changed 42 to 4.2 in the directory path.
**Content**

Fixed version in directory 

---

product_docs/docs/epas/12/epas_inst_linux/02_supported_platforms.mdx

- Change reference of OEL to OL.
- LLVM JIT package is supported on SLES.
**Content**

Changed reference of OEL to OL

---

product_docs/docs/pgpool/1.0/01_installing_and_configuring_the_pgpool-II.mdx
product_docs/docs/pgpool/1.0/02_extensions.mdx
product_docs/docs/pgpool/1.0/03_configuring_connection_pooling.mdx
product_docs/docs/pgpool/1.0/04_connecting_a_client_to_pgpool-II.mdx
product_docs/docs/pgpool/1.0/index.mdx

Added Pgpool 4.2.3 updates
**Content**

Pgpool_4.2.3_Updates

---

product_docs/docs/ocl_connector/12.1.2.1/02_supported_platforms.mdx
product_docs/docs/ocl_connector/13.1.4.2/02_supported_platforms.mdx
product_docs/docs/odbc_connector/12.0.0.2/02_requirements_overview.mdx
product_docs/docs/odbc_connector/12.2.0.2/02_requirements_overview.mdx

Replaced OEL to OL.
**Content**

Fixing OEL to OL

---

product_docs/docs/efm/4.2/efm_user/03_installing_efm.mdx
product_docs/docs/efm/4.2/efm_user/index.mdx

Added a note about mixed-mode platform support.
**Content**

Adding note about mixed mode support

---

product_docs/docs/efm/4.1/efm_pgpool_ha_guide/03_components_ha_pgpool.mdx
product_docs/docs/efm/4.2/efm_pgpool_ha_guide/03_components_ha_pgpool.mdx
product_docs/docs/efm/4.2/efm_pgpool_ha_guide/04_appendix_a.mdx

Modified the variable names and values for Pgpool HA configuration.
**Content**

Updates for EFM-1456

---

product_docs/docs/epas/12/epas_compat_sql/04_alter_procedure.mdx
product_docs/docs/epas/12/epas_compat_sql/05_alter_profile.mdx
product_docs/docs/epas/12/epas_compat_sql/07_alter_queue_table.mdx
product_docs/docs/epas/12/epas_compat_sql/12_alter_table.mdx
product_docs/docs/epas/12/epas_compat_sql/18_comment.mdx
product_docs/docs/epas/12/epas_compat_sql/21_create_public_database_link.mdx
product_docs/docs/epas/12/epas_compat_sql/23_create_function.mdx
product_docs/docs/epas/12/epas_compat_sql/25_create_materialized_view.mdx
product_docs/docs/epas/12/epas_compat_sql/28_create_procedure.mdx
product_docs/docs/epas/12/epas_compat_sql/39_create_type.mdx
product_docs/docs/epas/12/epas_compat_sql/40_create_type_body.mdx
product_docs/docs/epas/12/epas_compat_sql/57_drop_table.mdx
product_docs/docs/epas/12/epas_compat_sql/64_grant.mdx
product_docs/docs/epas/12/epas_compat_sql/71_select.mdx
product_docs/docs/epas/13/epas_compat_sql/04_alter_procedure.mdx
product_docs/docs/epas/13/epas_compat_sql/05_alter_profile.mdx
product_docs/docs/epas/13/epas_compat_sql/07_alter_queue_table.mdx
product_docs/docs/epas/13/epas_compat_sql/12_alter_table.mdx
product_docs/docs/epas/13/epas_compat_sql/18_comment.mdx
product_docs/docs/epas/13/epas_compat_sql/21_create_public_database_link.mdx
product_docs/docs/epas/13/epas_compat_sql/23_create_function.mdx
product_docs/docs/epas/13/epas_compat_sql/25_create_materialized_view.mdx
product_docs/docs/epas/13/epas_compat_sql/28_create_procedure.mdx
product_docs/docs/epas/13/epas_compat_sql/39_create_type.mdx
product_docs/docs/epas/13/epas_compat_sql/40_create_type_body.mdx
product_docs/docs/epas/13/epas_compat_sql/57_drop_table.mdx
product_docs/docs/epas/13/epas_compat_sql/64_grant.mdx
product_docs/docs/epas/13/epas_compat_sql/71_select.mdx

During working on v11 SQL guide for migration, found bugs related to code-blocks, syntax etc. Fixed.
**Content**

SQL Guide Fixes

---

src/components/archive.js
src/components/stub-cards.js
src/constants/product-stubs.js

Download PDFs directly from the archived-docs repo

Download PDFs from Github repo

---

product_docs/docs/eprs/6.2/index.mdx

Adding redirection for EPRS HTML set on Docs 1.0 site.
**Content**

Adding redirection to EPRS docset

---

advocacy_docs/kubernetes/cloud_native_postgresql/interactive_demo.mdx
merge_sources/kubernetes/cloud_native_postgresql/interactive_demo.mdx

missed a newline on the ending block fence, causing it to eat next several paragraphs.
Fixes #1564 
**Content**

missed a newline in interactive demo output

---

product_docs/docs/eprs/6.2/08_xdb_cli/03_xdb_cli_commands/44_configure_mmr_schedule.mdx

mmr should be lower case

---

product_docs/docs/migration_toolkit/55.0.0/08_mtk_command_options.mdx

**Examples**
- Fixed typo in `/migration_toolkit/55.0.0/08_mtk_command_options/` page
**Content**

Fixed Typo for MTK Rel 55.0.0

---

product_docs/docs/pem/8.1.1/index.mdx

Created a new branch for PEM 8.1.1 patch release
**Content**

Created a new branch for PEM 8.1.1 patch release

---

product_docs/docs/epas/12/epas_guide/03_database_administration/05_edb_audit_logging/03_enabling_audit_logging.mdx
product_docs/docs/epas/12/epas_guide/03_database_administration/06_unicode_collation_algorithm.mdx
product_docs/docs/epas/13/epas_guide/03_database_administration/05_edb_audit_logging/03_enabling_audit_logging.mdx
product_docs/docs/epas/13/epas_guide/03_database_administration/06_unicode_collation_algorithm.mdx

During reviewing epas guide for v11 migration, found bugs. Fixed the same.
**Content**

EPAS Guide Fixes

---

static/_redirects

Added redirects from minor and patch release versions to major versions - part of version consolidation project 
See #1592

added redirects for 7 and 8

---

product_docs/docs/efm/4.2/efm_pgpool_ha_guide/02_architecture.mdx
product_docs/docs/efm/4.2/efm_pgpool_ha_guide/04_efm_client_connect_failover.mdx
product_docs/docs/efm/4.2/efm_pgpool_ha_guide/05_efm_pgbouncer.mdx
product_docs/docs/efm/4.2/efm_pgpool_ha_guide/06_efm_pgpool.mdx

Fixed review comments.
**Content**

Fixing review comments for EFM HA Guide

---

product_docs/docs/pem/7/pem_rel_notes/03_714_rel_notes.mdx

Updated the 7.14 release notes with ID column
**Content**

Updated the 7.14 release notes with ID column

---

product_docs/docs/pem/7/pem_rel_notes/04_713_rel_notes.mdx

Added ID column and its content in 7.13 release notes
**Content**

Added ID column and its content in 7.13 release notes

---

product_docs/docs/pem/8/pem_rel_notes/index.mdx

Fix for broken link Anthony pointed out

---

product_docs/docs/pem/7/pem_rel_notes/05_712_rel_notes.mdx

Added ID column and its contents to 7.12 release notes
Added ID column and its contents to 7.12 release notes
**Content**

Added ID column and its contents to 7.12 release notes

---

product_docs/docs/eprs/6.2/10_appendix/01_permitted_conf_and_permutations.mdx

**Examples**
- Added a note as per the customer escalation
**Content**
- [X ] This PR adds new content

Added a note as per the customer escalation

---

product_docs/docs/epas/12/epas_rel_notes/index.mdx
product_docs/docs/epas/13/epas_rel_notes/index.mdx

Changed the OEL reference to OL in the release notes.
**Content**

DB-1251 Changed OEL Reference to OL

---

product_docs/docs/migration_toolkit/55.0.0/08_mtk_command_options.mdx

**Examples**
Added a note for parallel data loading
**Content**

Added a note_for parallel data loading

---

product_docs/docs/pem/7/pem_admin/index.mdx
product_docs/docs/pem/7/pem_agent/index.mdx
product_docs/docs/pem/7/pem_inst_guide_linux/02_pem_hardware_software_requirements.mdx
product_docs/docs/pem/7/pem_inst_guide_windows/02_pem_hardware_software_requirements.mdx

Changed OEL to OL in PEM 7 docs
**Content**

Changed OEL to OL in PEM 7 docs

---

product_docs/docs/edbcloud/beta/getting_started/03_create_cluster.mdx

- Updated create cluster document.
Updated "create cluster" document.
**Examples**
- Fixed typo in version in create cluster document
- Added password description for superuser 'edb_admin'
**Content**

Update "create cluster" document

---

product_docs/docs/edbcloud/beta/administering_cluster/organization_and_access/02_users.mdx

Changing the organization of information related to Users and Roles
**Examples**
- Added a Adding Users section
- Added a Removing Users section
- Updated Viewing Users section
- Moved Role Definitions from Roles page to allow consolidation
**Content**

Restructure Access Admin functionality.mdx

---

product_docs/docs/edbcloud/beta/administering_cluster/organization_and_access/02_users.mdx

Update 02_users.mdx
Added intros to the two main sections and made some minor edits 
**Content**

Update 02_users.mdx - added intros and minor edits

---

product_docs/docs/edbcloud/beta/getting_started/01_connect_cloud_account.mdx

Updated 01_connect_cloud_account.mdx with heading change
Incorporated edits to Connecting to Your Cloud topic as discussed with Kelly
**Content**

Minor edits to various topics

---

product_docs/docs/edbcloud/beta/getting_started/03_create_cluster.mdx

fix spacing

---

product_docs/docs/edbcloud/beta/getting_started/01_connect_cloud_account.mdx

Formatting fix

---

product_docs/docs/edbcloud/beta/getting_started/01_connect_cloud_account.mdx

Added functional higher level steps to the Create your Subscription procedure to support linking

Added headers to last procedure

---

product_docs/docs/edbcloud/beta/using_cluster/02_connect_to_cluster.mdx

I have an outstanding terminology question: should we refer to psql and similar tools as clients, applications, tools, maybe something else?

preliminary style edit pass

---

product_docs/docs/edbcloud/beta/pricing_and_billing/index.mdx

Incorporated Jozef's first and third comments on UPM-932

updates to pricing and billing

---

product_docs/docs/edbcloud/beta/administering_cluster/index.mdx

Update index.mdx for Administering your account

---

product_docs/docs/edbcloud/beta/using_cluster/03_modify_and_scale_cluster.mdx

Fixed note formatting on modifying and scaling clusters

Fixed note formatting on modifying and scaling clusters

---

product_docs/docs/edbcloud/beta/administering_cluster/02_activity_log.mdx
product_docs/docs/edbcloud/beta/getting_started/01_check_resource_limits.mdx
product_docs/docs/edbcloud/beta/getting_started/index.mdx

Changed title of resource topic
Set nav for Getting Started
Initial review of activity logs

misc changes

---

advocacy_docs/kubernetes/cloud_native_postgresql/api_reference.mdx
advocacy_docs/kubernetes/cloud_native_postgresql/architecture.mdx
advocacy_docs/kubernetes/cloud_native_postgresql/bootstrap.mdx
advocacy_docs/kubernetes/cloud_native_postgresql/container_images.mdx
advocacy_docs/kubernetes/cloud_native_postgresql/e2e.mdx
advocacy_docs/kubernetes/cloud_native_postgresql/index.mdx
advocacy_docs/kubernetes/cloud_native_postgresql/installation_upgrade.mdx
advocacy_docs/kubernetes/cloud_native_postgresql/interactive_demo.mdx
advocacy_docs/kubernetes/cloud_native_postgresql/operator_capability_levels.mdx
advocacy_docs/kubernetes/cloud_native_postgresql/operator_conf.mdx
advocacy_docs/kubernetes/cloud_native_postgresql/release_notes.mdx
advocacy_docs/kubernetes/cloud_native_postgresql/replication.mdx
advocacy_docs/kubernetes/cloud_native_postgresql/samples/cluster-example-initdb.yaml
advocacy_docs/kubernetes/cloud_native_postgresql/storage.mdx
merge_sources/kubernetes/cloud_native_postgresql/interactive_demo.mdx

- Import of the docs for Cloud Native PostgreSQL 1.7.1
**Content**

CNP 1.7.1 import

---

product_docs/docs/epas/13/edb_plus/05_using_edb_plus_with_ssl.mdx

**Examples**
- Updated the build version to 39.0.1
**Content**

Updated the build version to 39.0.1

---

product_docs/docs/epas/13/edb_plus/04_using_edb_plus.mdx

**Examples**
- Update the build version of EDB*Plus
**Content**

Update the build version of EDB*Plus

---

product_docs/docs/edbcloud/beta/overview/06_support.mdx

edits to Support

---

product_docs/docs/edbcloud/beta/getting_started/01_check_resource_limits.mdx

Changed "EDB Cloud Postgres clusters" to "EDB clusters"

check resource topic - Aislinn feedback

---

product_docs/docs/edbcloud/beta/overview/02_high_availibility.mdx

Removed steps to view your HA settings

ha topic edits

---

.github/workflows/deploy-develop.yml
.github/workflows/deploy-draft.yml
.github/workflows/deploy-main.yml

* Added `lfs: true` option to the checkout step on each GitHub Action. (See https://github.com/EnterpriseDB/docs/runs/3325337804?check_suite_focus=true)

Bugfix/jon/1673 GitHub actions lfs

---

product_docs/docs/edbcloud/beta/administering_cluster/01_portal_access.mdx
product_docs/docs/edbcloud/beta/administering_cluster/02_postgres_access.mdx
product_docs/docs/edbcloud/beta/administering_cluster/03_account_activity.mdx
product_docs/docs/edbcloud/beta/getting_started/01_check_resource_limits.mdx
product_docs/docs/edbcloud/beta/getting_started/02_connect_cloud_account.mdx
product_docs/docs/edbcloud/beta/getting_started/03_create_cluster.mdx
product_docs/docs/edbcloud/beta/overview/02_high_availibility.mdx
product_docs/docs/edbcloud/beta/overview/03_security.mdx
product_docs/docs/edbcloud/beta/overview/04_responsibility_model.mdx
product_docs/docs/edbcloud/beta/overview/05_database_version_policy.mdx
product_docs/docs/edbcloud/beta/overview/06_support.mdx
product_docs/docs/edbcloud/beta/overview/index.mdx
product_docs/docs/edbcloud/beta/using_cluster/02_connect_to_cluster.mdx
product_docs/docs/edbcloud/beta/using_cluster/03_modify_and_scale_cluster.mdx
product_docs/docs/edbcloud/beta/using_cluster/04_backup_and_restore.mdx
product_docs/docs/edbcloud/beta/using_cluster/05_monitoring_and_logging.mdx

Applied style changes to links, updated font treatments, etc.

Docs/edbcloud beta/dee/end to end review

---

product_docs/docs/edbcloud/beta/getting_started/01_check_resource_limits.mdx

Refer to https://docs.google.com/document/d/1e00Or2IFkmD9uytmvWNnhafPVTFVkkkVLogzL1aBW0M/edit# for more background and discussion of it.
* Updated guidance about how resources are limited.
**Content**

update check_resource_limits for correct term (vCPU cores)

---

.husky/_/husky.sh
.husky/post-checkout
.husky/post-commit
.husky/post-merge
.husky/pre-push
package.json
yarn.lock

* Upgrade husky
* Add missing autogenerated LFS hooks

Upgrade husky

---

.husky/_/husky.sh
.husky/post-checkout
.husky/post-commit
.husky/post-merge
.husky/pre-push
package.json
product_docs/docs/edbcloud/beta/getting_started/02_connect_cloud_account.mdx
product_docs/docs/pem/8/pem_online_help/04_toc_pem_features/21_performance_diagnostic.mdx
src/components/link.js
src/templates/doc.js
yarn.lock

- EDB Cloud: Updated text on the table to match the names we use in production and Azure. (#1766)
- build: upgrade husky, add autogenerated husky LFS hooks (#1763)
- bugfix: Handle URLs to .md or .mdx with fragment or query (#1762)
- bugfix: Remove path-based defaults for card deck nav style (#1761)
- PEM: Note that Performance Diagnostics runs on most supported platforms (#1760)

Release: 2021-08-18

---

product_docs/docs/edbcloud/beta/getting_started/01_check_resource_limits.mdx

in 01_check_resource_limits added section ## Virtual Machine Quota Requirements
**Content**
- [*] This PR adds new content
- [*] This PR changes existing content

Virtual Machine requrements

---

product_docs/docs/edbcloud/beta/getting_started/01_check_resource_limits.mdx

check resource limit topic style edit

---

product_docs/docs/epas/13/epas_rel_notes/index.mdx

Updated the EDB*Plus version number in release notes.
**Content**

ED-114:Updated the EDB Plus version number 

---

advocacy_docs/partner_docs/ThalesGuide/02-PartnerInformation.mdx
advocacy_docs/partner_docs/ThalesGuide/03-SolutionSummary.mdx
advocacy_docs/partner_docs/ThalesGuide/04-ImplementingCTE.mdx
advocacy_docs/partner_docs/ThalesGuide/05-UsingCTE.mdx
advocacy_docs/partner_docs/ThalesGuide/06-CertificationEnvironment.mdx
advocacy_docs/partner_docs/ThalesGuide/07-Appendix.mdx
advocacy_docs/partner_docs/ThalesGuide/Images/EDBPostgresExtendedwithBDRAlwaysOn.png
advocacy_docs/partner_docs/ThalesGuide/Images/GreenLogo.jpg
src/pages/index.js

Pulls JUST the changes to the Thales integration guide from #1781 
**Content**

Pull in changes to Thales from futureguides branch

---

src/pages/index.js

reordered products by priority and so that the columns are better balanced
also streamlined connectors and FDW product names
**Content**

reorganized homepage

---

product_docs/docs/eprs/6.2/02_overview/04_design_replication_system/03_restrictions_on_replicated_database_objects.mdx

**Examples**
Made changes to supported data types for XDB for patch Rel 6.2.15
**Content**

XDB changes for Patch Rel 6.2.15

---

product_docs/docs/eprs/6.2/02_overview/02_replication_concepts_and_definitions/13_table_filters.mdx

Updated the User Guide with the filter restrictions for the mod operator.
**Content**
- [X ] This PR adds new content

Added the restrictions for mod operator for XDB 6.2.15 release

---

product_docs/docs/epas/13/edb_plus/index.mdx

Fixing redirection from Docs 1.0 site for EDB*Plus Guide. Currently, it is added to the second topic in the HTML folder, I am adding it to the index.html file.
**Content**

Fixing redirection

---

.github/workflows/sync-and-process-files.yml

Updated name of the event that triggers sync and processing of file to be more descriptive

Update event name to sync and process files

---

product_docs/docs/edbcloud/beta/index.mdx
product_docs/docs/edbcloud/beta/reference/index.mdx

Added API topic
- [x ] This PR adds new content

added API topic

---

product_docs/docs/pem/8/pem_inst_guide_linux/04_installing_postgres_enterprise_manager/07_1_configuring_2fa_authentication.mdx

Dee's review comments

---

advocacy_docs/supported-open-source/pgbackrest/03-quick_start.mdx
advocacy_docs/supported-open-source/pgbackrest/index.mdx

- pgBackRest 2.35 has been released last week and PGDG packages are now available
**Content**

Add pgBackRest 2.35 availability

---

.dockerignore
README.md
docker/docker-compose.quickstart.yaml
docker/images/Dockerfile.quickstart

* bake node_modules/ into the image
* use native Docker volumes for Gatsby artifacts

build: optimize Docker config for local development

---

product_docs/docs/edbcloud/beta/getting_started/02_connect_cloud_account.mdx

added note about need for Global Admin approval in connect_cloud_account.mdx
**Content**

docs(UPM-2183): add note about need for Global Admin approval

---

product_docs/docs/edbcloud/beta/getting_started/03_create_cluster.mdx

Updated note re: storage support in step 10

Updated note re: storage support - UPM-1936 - EDB Cloud

---

.github/pull_request_template.md
docs/agreements/branch-and-release.md
docs/agreements/doc-release-tag-format.md

Tagging process
Added info to release process
Updated PR template
**Content**

Tagging process

---

product_docs/docs/edbcloud/beta/getting_started/01_check_resource_limits.mdx
product_docs/docs/edbcloud/beta/getting_started/images/raising-limits-video.png

This is a POC.
added a video to raising limits topic showing two approaches:
- using a thumbnail screenshot
- just showing the link

added a video to raising limits topic

---

product_docs/docs/edbcloud/beta/reference/index.mdx

links were to local build instead of relative
**Content**

fixing links

---

product_docs/docs/epas/11/epas_compat_bip_guide/03_built-in_packages/05_dbms_job/index.mdx
product_docs/docs/epas/12/epas_compat_bip_guide/03_built-in_packages/05_dbms_job/index.mdx
product_docs/docs/epas/13/epas_compat_bip_guide/03_built-in_packages/05_dbms_job/index.mdx

DF-262: Updated dbms_job package and added content for dbms_job extension. 
**Content**

DF-262 DBMS_JOB Extension update

---

.github/workflows/deploy-develop.yml
.github/workflows/deploy-draft.yml
.github/workflows/deploy-main.yml

update the deploy scripts to use the latest version of npm (v7) and use an npm token secret so that icons can be downloaded

update deploy scripts to use npm 7 and the npm token secret

---

README.md

Added information about how to resolve issues with the docker dev environment, and organized the additional troubleshooting so it makes more sense.

add troubleshooting for docker dev env

---

src/components/index-sub-nav.js
src/components/side-navigation.js

Changed label for Support link in left nav

Changed label for Support link in left nav

---

product_docs/docs/migration_toolkit/55/02_supported_operating_systems_and_database_versions.mdx

Updated the MySQL versions
**Content**

Updated mysql_versions

---

src/components/search-navigation-links.js
src/components/search/formComps.js
src/pages/404.js
src/pages/search.js

Attempting to change Advanced Search label. See solution option 2 in https://github.com/EnterpriseDB/docs/issues/1874

Attempt to change Advanced Search

---

advocacy_docs/kubernetes/cloud_native_postgresql/index.mdx
scripts/fileProcessor/processors/cnp/add-frontmatters.mjs

Script to add this was still referencing old icon name; this updates both the script and the index file.
**Content**

Update CNP to new icon name

---

product_docs/docs/migration_toolkit/55/index.mdx

Updated the version in frontmatter
**Content**

updated the version in frontmatter

---

product_docs/docs/efm/4/efm_pgpool_ha_guide/05_efm_pgbouncer.mdx

Made instructions more specific about where the attach script should be specified.
**Content**

Clarify where script property should be set

---

advocacy_docs/partner_docs/ThalesGuide/06-CertificationEnvironment.mdx

updated versions and split BDR and Postgres per PM request.
EDB Postgres Extended   11
Postgres-BDR                   3.6.25
**Content**

Thales guide: updated versions, split BDR and Postgres

---

product_docs/docs/edbcloud/beta/using_cluster/01_postgres_access.mdx

Step #2 under "One Database with One Application" was describing the reverse of the action actually needed (and demonstrated).
Fixes #1893
**Content**

Align description of step with action

---

product_docs/docs/edbcloud/beta/overview/02_high_availibility.mdx

feedback re replica defaults

---

.gitignore
build-sources.json
gatsby-config.js
product_docs/docs/livecompare/1.17/advanced_usage.mdx
product_docs/docs/livecompare/1.17/appendix_a.mdx
product_docs/docs/livecompare/1.17/appendix_b.mdx
product_docs/docs/livecompare/1.17/bdr_support.mdx
product_docs/docs/livecompare/1.17/command_line_usage.mdx
product_docs/docs/livecompare/1.17/index.mdx
product_docs/docs/livecompare/1.17/oracle_support.mdx
product_docs/docs/livecompare/1.17/requirements.mdx
product_docs/docs/livecompare/1.17/settings.mdx
product_docs/docs/livecompare/1.17/supported_technologies.mdx
scripts/source/livecompare.js
src/pages/index.js

Initial import of the LiveCompare docs. I've not really reviewed these; they may need some cleanup.
**Content**

LiveCompare initial import

---

advocacy_docs/partner_docs/RepostorGuide/02-PartnerInformation.mdx
advocacy_docs/partner_docs/RepostorGuide/04-Configuration.mdx
advocacy_docs/partner_docs/RepostorGuide/05-CertificationEnvironment.mdx

Update partner info page.  removed date.  Don't use.
configuration page.  added IBM in front of Spectrum connect in prerequisite.  Don't need it other places.
Cert env page
Moved Advanced up to first line in table.
Moved Repostor to second line in table
**Content**

Scottatchue patch 1

---

product_docs/docs/eprs/6.2/eprs_rel_notes/index.mdx
product_docs/docs/eprs/6.2/index.mdx

Release notes for EPRS Rel 6.2.15
**Content**
- [X ] This PR adds new content

Release Notes for 6.2.15

---

product_docs/docs/edbcloud/beta/reference/index.mdx

This PR 
- added new content in the `product_docs/docs/edbcloud/beta/reference/index.mdx` to describe one new step required the end-user to follow when the user is trying to get a token for accessing the EDB Cloud API.
Please note the relevant changes to the EDB Cloud production system have already been released. 
**Content**

update the "using EDB Cloud API" doc with latest account management behavior change

---

product_docs/docs/bdr/3.7/backup.mdx
product_docs/docs/bdr/3.7/catalogs.mdx
product_docs/docs/bdr/3.7/durability.mdx
product_docs/docs/bdr/3.7/known-issues.mdx
product_docs/docs/bdr/3.7/libraries.mdx
product_docs/docs/bdr/3.7/repsets.mdx
product_docs/docs/bdr/3.7/scaling.mdx
product_docs/docs/bdr/3.7/striggers.mdx
product_docs/docs/bdr/3.7/tssnapshots.mdx
product_docs/docs/bdr/3.7/twophase.mdx
product_docs/docs/bdr/3.7/upgrades.mdx
scripts/source/bdr.js

- BDR: more public content
**Content**

dependency update

---

product_docs/docs/biganimal/release/using_cluster/05_monitoring_and_logging.mdx
product_docs/docs/biganimal/release/using_cluster/06_metrics.mdx

EDB Cloud product documentation: Add a list of metrics exposed by EDB Cloud to the customer Azure Log Workspace. Include details on metrics and log entry structure, custom tables exposed, and some guidance on how to get started querying them.
**Content**

doc(UPM-2321): Document CNP metrics exposed by UPM

---

product_docs/docs/biganimal/release/reference/cli.mdx
product_docs/docs/biganimal/release/reference/index.mdx
product_docs/docs/biganimal/release/using_cluster/05_monitoring_and_logging/06_metrics.mdx
product_docs/docs/biganimal/release/using_cluster/05_monitoring_and_logging/index.mdx

Made topic a child page to Monitoring and logging
Applied sentence case format to titles and headings to reflect the new style guide

quick edit on Metrics topic

---

product_docs/docs/biganimal/release/reference/cli.mdx

added get cluster info use case

added BigAnimal CLI use case 

---

product_docs/docs/migration_portal/3.4.0/01_mp_release_notes/index.mdx

Minor updates to the Release Notes after feedback
**Content**

Updated the release notes

---

product_docs/docs/edbcloud/beta/index.mdx
product_docs/docs/edbcloud/beta/migration/cold_migration.mdx
product_docs/docs/edbcloud/beta/migration/index.mdx
product_docs/docs/migration_portal/3.3.0/04_mp_migrating_database/04_mp_data_migration.mdx
product_docs/docs/migration_toolkit/55/06_building_toolkit.properties_file.mdx

Migrating section in EDB Cloud docs

---

product_docs/docs/biganimal/release/overview/images/ha-not-enabled.png
product_docs/docs/biganimal/release/overview/images/high-availability.png

replaced images on BigAnimal  Supported architecture topic

HA diagrams with new BigAnimal branding

---

product_docs/docs/biganimal/release/using_cluster/05_monitoring_and_logging/06_metrics.mdx

Fixup for broken link in commit aa1117b0e
**Content**

Fix broken internal link in BigAnimal docs

---

product_docs/docs/biganimal/release/migration/index.mdx

BigAnimal: correcting typo Prashant pointed out

---

product_docs/docs/biganimal/release/reference/cli.mdx

edb-cli-fix: animal ->biganinmal
**Content**

edb-cli-fix: animal ->biganimal

---

product_docs/docs/bart/2.5/bart_inst/index.mdx
product_docs/docs/bart/2.6/bart_inst/index.mdx
product_docs/docs/biganimal/release/overview/05_database_version_policy.mdx
product_docs/docs/efm/3/efm_user/index.mdx
product_docs/docs/efm/4/efm_user/03_installing_efm.mdx
product_docs/docs/epas/11/epas_inst_linux/02_supported_platforms.mdx
product_docs/docs/epas/11/epas_inst_windows/02_requirements_overview.mdx
product_docs/docs/epas/11/epas_rel_notes/index.mdx
product_docs/docs/epas/11/epas_upgrade_guide/01_supported_platforms.mdx
product_docs/docs/epas/12/epas_inst_linux/02_supported_platforms.mdx
product_docs/docs/epas/12/epas_inst_windows/02_requirements_overview.mdx
product_docs/docs/epas/12/epas_rel_notes/index.mdx
product_docs/docs/epas/12/epas_upgrade_guide/01_supported_platforms.mdx
product_docs/docs/epas/13/epas_inst_linux/02_supported_platforms.mdx
product_docs/docs/epas/13/epas_inst_windows/02_requirements_overview.mdx
product_docs/docs/epas/13/epas_rel_notes/index.mdx
product_docs/docs/epas/13/epas_upgrade_guide/02_supported_platforms.mdx
product_docs/docs/pem/7/pem_admin/index.mdx
product_docs/docs/pem/7/pem_agent/index.mdx
product_docs/docs/pem/7/pem_inst_guide_linux/02_pem_hardware_software_requirements.mdx
product_docs/docs/pem/7/pem_inst_guide_windows/02_pem_hardware_software_requirements.mdx
product_docs/docs/pem/7/pem_sqlprofiler/02_using_sql_profiler.mdx
product_docs/docs/pem/8/pem_admin/index.mdx
product_docs/docs/pem/8/pem_agent/index.mdx
product_docs/docs/pem/8/pem_ha_setup/index.mdx
product_docs/docs/pem/8/pem_inst_guide_linux/02_pem_hardware_software_requirements.mdx
product_docs/docs/pem/8/pem_inst_guide_windows/02_pem_hardware_software_requirements.mdx
product_docs/docs/postgis/3.1.2/03_upgrading_postgis.mdx

fixed links to platform support page on the corporate web site

Fixed old platform support links

---

product_docs/docs/epas/13/epas_inst_linux/02_supported_platforms.mdx
product_docs/docs/epas/13/epas_inst_windows/02_requirements_overview.mdx

- added missing periods after links to Platform Availability page

misses in the 2021-11-5 release build

---

product_docs/docs/biganimal/release/reference/cli.mdx
src/components/index-sub-nav.js
src/components/side-navigation.js

Fixed broken link to the KB from the nav panel
Fixed incorrect command name in the BigAnimal CLI topic (animal > biganimal)

fix KB link and BigAnimal CLI typo

---

product_docs/docs/biganimal/release/using_cluster/06_demonstration_oracle_compatibility.mdx

- Clarity in the intro
- Qualify "Oracle" in titles
- "Call to action" lead into the video
- Responsive styling for the video
- Link to migration topic in closing
Reviewer request: take a look at the new intro & lemme know if it could still be made less wishy-washy.
**Content**

Cleanup on the BA Oracle-compat demo

---

gatsby-config.js
product_docs/docs/biganimal/release/using_cluster/06_demonstration_oracle_compatibility.mdx
src/components/index-sub-nav.js
src/components/side-navigation.js

- BigAnimal: demo fixes and tweaks
- Bugfix: eliminate redirects to www.
- Bugfix: don't index temporary PDF URLs (EW-7470)
**Content**

Release: 2021-11-09

---

scripts/fileProcessor/processors/cnp/update-yaml-links.mjs

Reverts EnterpriseDB/docs#2029 - I misdiagnosed the problem!

Revert "Use synchronous processing to avoid race condition with rename plugin"

---

scripts/fileProcessor/package-lock.json
scripts/fileProcessor/package.json

2nd crack at getting the AST link-rewriter to actually do what it's supposed to

add overlooked dependencies

---

product_docs/docs/biganimal/release/reference/cli.mdx

Updated the curl statements in the BigAnimal CLI topic

changed download CLI link per UPM-3163

---

advocacy_docs/kubernetes/cloud_native_postgresql/interactive_demo.mdx
merge_sources/kubernetes/cloud_native_postgresql/interactive_demo.mdx
product_docs/docs/biganimal/release/getting_started/creating_a_cluster/01_cluster_networking.mdx
product_docs/docs/biganimal/release/reference/cli.mdx
product_docs/docs/efm/4/efm_pgpool_ha_guide/05_efm_pgbouncer.mdx

- Updated CNP demo
- Updated download link in BigAnimal CLI topic
- Addressed typo in BigAnimal private networking topic
- Updated the script in "Using Failover Manager with PgBouncer" topic

2021 11 12

---

README.md
docs/agreements/doc-release-tag-format.md

Adding column for PMs, POs, and any other interested parties who want to be informed about updates to their product docs.
The plan is for PR owners to include the interested parties as reviewers, as appropriate.

updating doc-release-tag-format table

---

product_docs/docs/migration_toolkit/55/images/installing_mtk_sbp_download_complete.png
product_docs/docs/migration_toolkit/55/images/installing_mtk_sbp_inst_complete.png
product_docs/docs/migration_toolkit/55/images/installing_mtk_sbp_welcome.png

Updated the images in the MTK guide
**Content**

Updated the images

---

product_docs/docs/biganimal/release/index.mdx

* BigAnimal sidebar icon updated (fixing #2056)

BigAnimal sidebar icon

---

product_docs/docs/biganimal/release/using_cluster/06_demonstration_oracle_compatibility.mdx

Re-uploaded the video with a tweak to branding (edbcloud.io -> biganimal.io)
**Content**

Edited video with branding corrections

---

product_docs/docs/biganimal/release/overview/06_support.mdx
src/components/index-sub-nav.js
src/components/side-navigation.js

Changed support topic title and KB link label

Feedback from Support re support topic and KB link

---

product_docs/docs/biganimal/release/pricing_and_billing/index.mdx

Added new management costs section to BigAnimal Pricing and billing topic

upm-3116-costs

---

product_docs/docs/livecompare/1.18/advanced_usage.mdx
product_docs/docs/livecompare/1.18/appendix_a.mdx
product_docs/docs/livecompare/1.18/appendix_b.mdx
product_docs/docs/livecompare/1.18/bdr_support.mdx
product_docs/docs/livecompare/1.18/command_line_usage.mdx
product_docs/docs/livecompare/1.18/index.mdx
product_docs/docs/livecompare/1.18/oracle_support.mdx
product_docs/docs/livecompare/1.18/requirements.mdx
product_docs/docs/livecompare/1.18/settings.mdx
product_docs/docs/livecompare/1.18/supported_technologies.mdx

Importing LiveCompare 1.18 documentation.
**Content**

Add LiveCompare 1.18

---

product_docs/docs/eprs/7.0/03_installation/03_installing_rpm_package.mdx
product_docs/docs/eprs/7.0/10_appendix/02_upgrading_to_xdb6_2/03_upgrading_with_xdb_rpm_package.mdx

- Updated RPM install topic
- Changed title of RPM upgrade topic in the appendix

first draft of changes for XDB-1052

---

product_docs/docs/bdr/3.7/backup.mdx
product_docs/docs/bdr/3.7/catalogs.mdx
product_docs/docs/bdr/3.7/ddl.mdx
product_docs/docs/bdr/3.7/durability.mdx
product_docs/docs/bdr/3.7/functions.mdx
product_docs/docs/bdr/3.7/index.mdx
product_docs/docs/bdr/3.7/known-issues.mdx
product_docs/docs/bdr/3.7/monitoring.mdx
product_docs/docs/bdr/3.7/nodes.mdx
product_docs/docs/bdr/3.7/overview.mdx
product_docs/docs/bdr/3.7/release-notes.mdx
product_docs/docs/bdr/3.7/scaling.mdx
product_docs/docs/bdr/3.7/security.mdx
product_docs/docs/bdr/3.7/sequences.mdx
product_docs/docs/bdr/3.7/twophase.mdx
scripts/source/bdr.js

* Updated BDR 3.7 to 3.7.13
* Made the destination of AuthenticatedContentPlaceholder variable based on verion
**Content**

Import BDR 3.7.13

---

product_docs/docs/biganimal/release/getting_started/02_connect_cloud_account.mdx

- Add "Privileged Role Administrator" the connect your cloud to BA section for Azure.
Please check https://enterprisedb.atlassian.net/browse/UPM-2268 for more details.
In short: we tested and validated that "Privileged Role Administrator" can also be used to approve the BA application in the customer's Azure AD. 
**Content**

Update BA connect cloud account with new role for consent the BA application

---

product_docs/docs/biganimal/release/migration/cold_migration.mdx
product_docs/docs/biganimal/release/overview/05_database_version_policy.mdx
product_docs/docs/biganimal/release/reference/cli.mdx

Updated EPAS versions in examples in the supported Postgres versions table

change references to epas 13 to epas 14

---

docs/agreements/doc-release-tag-format.md

We don't have the LiveCompare product listed, so I thought I'd add it.
**Content**

Added LiveCompare to the list of releases.

---

product_docs/docs/migration_toolkit/54/05_installing_mtk.mdx
product_docs/docs/migration_toolkit/54/index.mdx
product_docs/docs/migration_toolkit/55/05_installing_mtk.mdx
product_docs/docs/migration_toolkit/55/index.mdx

Fixed the broken links of the downloads page in Migration Toolkit
**Content**

Fixed the broken links

---

product_docs/docs/pem/8/images/pem_server_web_properties_member_of.png
product_docs/docs/pem/8/pem_inst_guide_linux/04_installing_postgres_enterprise_manager/06_configuring_the_pem_server_to_use_kerberos_authentication.mdx
product_docs/docs/pem/8/pem_inst_guide_linux/04_installing_postgres_enterprise_manager/07_configuring_the_pem_server_to_use_windows_kerberos_server.mdx

Done the edits to PEM Installation on Linux guide as per the https://enterprisedb.atlassian.net/browse/PEM-4235
**Content**

Done the edits as per the PEM-4235

---

product_docs/docs/biganimal/release/getting_started/01_preparing_azure/index.mdx

Fixed link to script (removed .sh)

fixed link to script

---

product_docs/docs/epas/10/epas_compat_ora_dev_guide/05_optimizer_hints/index.mdx
product_docs/docs/epas/11/epas_compat_ora_dev_guide/05_optimizer_hints/index.mdx
product_docs/docs/epas/12/epas_compat_ora_dev_guide/05_optimizer_hints/index.mdx
product_docs/docs/epas/13/epas_compat_ora_dev_guide/05_optimizer_hints/index.mdx
product_docs/docs/epas/14/epas_compat_ora_dev_guide/05_optimizer_hints/index.mdx

Fixed the optimizer hint content as per DB-1614
**Content**

Fixed the optimizer hint content as per DB-1614

---

product_docs/docs/biganimal/release/using_cluster/04_backup_and_restore.mdx

UPM-3798: Support for cross region restores

---

product_docs/docs/efm/3/efm_quick_start/index.mdx

EFM-1485 - fix property name
**Examples**
**Content**

EFM-1485 - update property name

---

product_docs/docs/efm/4/efm_quick_start/index.mdx

EFM-1485 - Fix property name
**Examples**
**Content**

EFM-1485 - fix property name

---

product_docs/docs/biganimal/release/using_cluster/06_demonstration_oracle_compatibility.mdx

Use new Vimeo version of the demo video w/ intro & outro (h/t @aaronfitzsimmons-edb )
**Content**

Use new Vimeo upload w/ intro & outro for demo

---

product_docs/docs/biganimal/release/getting_started/01_preparing_azure/01_understanding_qotas_in_azure.mdx

- Add a missing Azure service provider "Azure.ContainerInstance" in BigAnimal "Get-Started" documentation. 
**Content**

Add BigAnimal Azure dependent service provider containerinstance

---

product_docs/docs/efm/4/efm_rel_notes/07_efm_43_rel_notes.mdx
product_docs/docs/efm/4/efm_rel_notes/index.mdx

EFM 4.3 release

---

product_docs/docs/biganimal/release/using_cluster/03_modifying_your_cluster/05_db_configuration_parameters.mdx

Added link for more information on parameter values

UPM-3491-Allow users to specify GUC values as memory "shorthands"

---

product_docs/docs/efm/4/efm_pgpool_ha_guide/05_efm_pgbouncer.mdx
product_docs/docs/efm/4/efm_quick_start/index.mdx
product_docs/docs/efm/4/efm_user/04_configuring_efm/01_cluster_properties/index.mdx
product_docs/docs/efm/4/efm_user/04_configuring_efm/06_configuring_for_eager_failover.mdx
product_docs/docs/efm/4/efm_user/06_monitoring_efm_cluster.mdx

New EFM docs, some broken links - not all of them new.
**Content**

Fix various broken links in EFM 4.3 update

---

product_docs/docs/bdr/3.7/nodes.mdx
product_docs/docs/bdr/4.0/functions.mdx
product_docs/docs/bdr/4.0/nodes.mdx
product_docs/docs/bdr/4.0/repsets.mdx
product_docs/docs/bdr/4.0/striggers.mdx
product_docs/docs/bdr/4.0/transaction-streaming.mdx

Admonitions component wasn't handling tabs properly, resulting in eating the first few characters of each paragraph in a !!! Note, Warning, etc.
Fixed these, as well as a few other random formatting issues. 
Fixes #2154
**Content**

Fix various issues with admonitions introduced during import

---

product_docs/docs/migration_toolkit/55/02_supported_operating_systems_and_database_versions.mdx
product_docs/docs/migration_toolkit/55/03_migration_methodology.mdx
product_docs/docs/migration_toolkit/55/04_functionality_overview.mdx
product_docs/docs/migration_toolkit/55/06_building_toolkit.properties_file.mdx
product_docs/docs/migration_toolkit/55/07_invoking_mtk.mdx
product_docs/docs/migration_toolkit/55/08_mtk_command_options.mdx
product_docs/docs/migration_toolkit/55/09_mtk_errors.mdx
product_docs/docs/migration_toolkit/55/10_error_codes.mdx
product_docs/docs/migration_toolkit/55/11_unsupported_features.mdx
product_docs/docs/migration_toolkit/55/index.mdx

Copyediting of doc for consistency

Editing of MTK doc 

---

product_docs/docs/migration_portal/3.4.0/index.mdx

Fixed a borken link

---

advocacy_docs/supported-open-source/pgbackrest/99-faq.mdx
advocacy_docs/supported-open-source/pgbackrest/index.mdx

- Add pgBackRest 2.37 release availability
- Mention TLS server in the FAQ
**Content**

pgBackRest 2.37 availability

---

product_docs/docs/biganimal/release/overview/04_responsibility_model.mdx

We've received some feedback on the clarity of the BigAnimal shared responsibility document. This changeset rewrites several points for clarity and correctness.
**Content**

Rework responsibility model for clarity

---

product_docs/docs/efm/4/efm_rel_notes/08_efm_42_rel_notes.mdx

Added missing release note to address https://github.com/EnterpriseDB/docs/issues/2205

Added missing rel note to EFM 4.2

---

product_docs/docs/migration_toolkit/54/mtk_rel_notes/index.mdx
product_docs/docs/migration_toolkit/55/mtk_rel_notes/06_mkt_5521_rel_notes.mdx
product_docs/docs/migration_toolkit/55/mtk_rel_notes/07_mkt_552_rel_notes.mdx
product_docs/docs/migration_toolkit/55/mtk_rel_notes/index.mdx

- added release notes for 55.2.1
- updated date format for 54 rel notes
Related release announcement draft: https://docs.google.com/document/d/16QW-oVd5GzZFKUvNobkaU3FHkE-j0fL6RC4SdQB7_Tw/edit

release notes for MTK 55.2.1 release

---

product_docs/docs/biganimal/release/using_cluster/03_modifying_your_cluster/05_db_configuration_parameters.mdx
product_docs/docs/biganimal/release/using_cluster/03_modifying_your_cluster/images/restart_icon.png

Added warning on db config page about certain parameter updates causing restarts

BigAnimal: UPM-4047 restarts

---

product_docs/docs/biganimal/release/overview/support/01_case_management.mdx
product_docs/docs/biganimal/release/overview/support/index.mdx
product_docs/docs/biganimal/release/using_cluster/03_modifying_your_cluster/05_db_configuration_parameters.mdx
product_docs/docs/biganimal/release/using_cluster/03_modifying_your_cluster/images/restart_icon.png

BigAnimal:
- Added Managing your Support cases topic
- Added additional information about parameter updates that cause restarts

Release: 2022-01-17

---

product_docs/docs/epas/13/edb_plus/04_using_edb_plus.mdx
product_docs/docs/epas/13/edb_plus/05_using_edb_plus_with_ssl.mdx
product_docs/docs/epas/13/epas_rel_notes/20_epas13_rel_notes.mdx

https://enterprisedb.atlassian.net/browse/ED-137

Updated EDB*Plus version

---

product_docs/docs/epas/13/edb_plus/04_using_edb_plus.mdx
product_docs/docs/epas/13/edb_plus/05_using_edb_plus_with_ssl.mdx
product_docs/docs/epas/13/epas_rel_notes/20_epas13_rel_notes.mdx

Updated the version of EDB*Plus

Release: 2022-01-18

---

product_docs/docs/biganimal/release/overview/02_high_availability.mdx

BigAnimal: updated the definition of replicas (removed that you can use them for read-only workloads)

Release: 2022-01-19

---

advocacy_docs/kubernetes/cloud_native_postgresql/interactive_demo.mdx
merge_sources/kubernetes/cloud_native_postgresql/interactive_demo.mdx

Lot has changed since v1.10! Update the installed version in the demo, and associated output, to reflect that of 1.12
**Content**

Update CNP demo version and output to v1.12.0

---

product_docs/docs/biganimal/release/using_cluster/06_demonstration_oracle_compatibility.mdx

IT had to rebuild this cluster, changing the ID in the process.
**Content**

Update demo host (old one crashed)

---

advocacy_docs/kubernetes/cloud_native_postgresql/interactive_demo.mdx
merge_sources/kubernetes/cloud_native_postgresql/interactive_demo.mdx
product_docs/docs/biganimal/release/using_cluster/06_demonstration_oracle_compatibility.mdx

Updates to CNP demo.
Minor changes to BigAnimal demo.

Release: 2022-01-24

---

product_docs/docs/odbc_connector/12.0.0.2/02_requirements_overview.mdx
product_docs/docs/odbc_connector/12.0.0.2/03_edb-odbc_overview/01_installing_edb-odbc.mdx
product_docs/docs/odbc_connector/12.2.0.2/02_requirements_overview.mdx
product_docs/docs/odbc_connector/12.2.0.2/03_edb-odbc_overview/01_installing_edb-odbc.mdx
product_docs/docs/odbc_connector/13.0.0.1/02_requirements_overview.mdx
product_docs/docs/odbc_connector/13.0.0.1/03_edb-odbc_overview/01_installing_edb-odbc.mdx
product_docs/docs/odbc_connector/13.1.0.1/02_requirements_overview.mdx
product_docs/docs/odbc_connector/13.1.0.1/03_edb-odbc_overview/01_installing_edb-odbc.mdx
product_docs/docs/odbc_connector/13.1.0.2/02_requirements_overview.mdx
product_docs/docs/odbc_connector/13.1.0.2/03_edb-odbc_overview/01_installing_edb-odbc.mdx

Updated platform support info
Added rhel8 power install info

ODBC connector rhel8 power

---

product_docs/docs/pgpool/4.2/01_installing_and_configuring_the_pgpool-II.mdx
product_docs/docs/pgpool/4.2/02_extensions.mdx
product_docs/docs/pgpool/4.2/03_configuring_connection_pooling.mdx
product_docs/docs/pgpool/4.2/05_upgrade.mdx
product_docs/docs/pgpool/4.2/06_uninstalling_pgpool-II.mdx

Reworked platform support matrix
Added rhel 8 power info

pgpool rhel8 power

---

product_docs/docs/postgis/3.1.2/01_installing_postgis.mdx
product_docs/docs/postgis/3.1.2/05_uninstalling_postgis.mdx
product_docs/docs/postgis/3.1.4/01a_installing_postgis.mdx
product_docs/docs/postgis/3.1.4/05_uninstalling_postgis.mdx

Restructured platform support matrix
Added RHEL 8 for Power install indo

PostGIS rhel8 Power updates

---

product_docs/docs/ocl_connector/12.1.2.1/02_supported_platforms.mdx
product_docs/docs/ocl_connector/12.1.2.1/04_open_client_library/01_installing_and_configuring_the_ocl_connector.mdx
product_docs/docs/ocl_connector/13.1.4.2/02_supported_platforms.mdx
product_docs/docs/ocl_connector/13.1.4.2/04_open_client_library/01_installing_and_configuring_the_ocl_connector.mdx
product_docs/docs/ocl_connector/14.1.0.1/02_supported_platforms.mdx
product_docs/docs/ocl_connector/14.1.0.1/04_open_client_library/01_installing_and_configuring_the_ocl_connector.mdx

Updated platform support info
Added RHEL 8 Power install info

OCL connector rhel 8 power updates

---

product_docs/docs/jdbc_connector/42.2.12.3/02_requirements_overview.mdx
product_docs/docs/jdbc_connector/42.2.12.3/04_installing_and_configuring_the_jdbc_connector/01_installing_the_connector_with_an_rpm_package.mdx
product_docs/docs/jdbc_connector/42.2.19.1/02_requirements_overview.mdx
product_docs/docs/jdbc_connector/42.2.19.1/04_installing_and_configuring_the_jdbc_connector/01_installing_the_connector_with_an_rpm_package.mdx
product_docs/docs/jdbc_connector/42.2.24.1/02_requirements_overview.mdx
product_docs/docs/jdbc_connector/42.2.24.1/04_installing_and_configuring_the_jdbc_connector/01_installing_the_connector_with_an_rpm_package.mdx
product_docs/docs/jdbc_connector/42.2.24.1/04_installing_and_configuring_the_jdbc_connector/index.mdx

Updated platform support info
Added RHEL 8 ppc64le install info

JDBC Connector RHEL 8 Power updates

---

product_docs/docs/efm/3/efm_pgpool_ha_guide/04_appendix_a.mdx
product_docs/docs/efm/3/efm_quick_start/index.mdx
product_docs/docs/efm/3/efm_user/03_installing_efm.mdx
product_docs/docs/efm/3/efm_user/04_configuring_efm/01_cluster_properties/01_encrypting_database_password.mdx
product_docs/docs/efm/3/efm_user/05_using_efm.mdx
product_docs/docs/efm/3/efm_user/08_controlling_efm_service.mdx
product_docs/docs/efm/3/efm_user/12_upgrading_existing_cluster.mdx
product_docs/docs/efm/4/03_installing_efm.mdx
product_docs/docs/efm/4/04_configuring_efm/02_encrypting_database_password.mdx
product_docs/docs/efm/4/05_using_efm.mdx
product_docs/docs/efm/4/08_controlling_efm_service.mdx
product_docs/docs/efm/4/12_upgrading_existing_cluster.mdx
product_docs/docs/efm/4/efm_quick_start/index.mdx

Added new section on installing on RHEL 8 Power

EFM rhel8 Power install instructions

---

product_docs/docs/eprs/6.2/01_introduction/04_supported_jdk_versions.mdx
product_docs/docs/eprs/6.2/03_installation/03_installing_rpm_package.mdx
product_docs/docs/eprs/6.2/03_installation/03a_installing_rhel8_ppcle.mdx
product_docs/docs/eprs/6.2/03_installation/05_post_installation_host_environment.mdx
product_docs/docs/eprs/6.2/05_smr_operation/01_prerequisites/06_verifying_host_accessibility.mdx
product_docs/docs/eprs/6.2/05_smr_operation/03_creating_subscription/01_registering_subscription_server.mdx
product_docs/docs/eprs/6.2/10_appendix/04_miscellaneous_xdb_processing_topics/01_publications_and_subscriptions_server_conf_options/index.mdx
product_docs/docs/eprs/7.0/01_introduction/04_supported_jdk_versions.mdx
product_docs/docs/eprs/7.0/03_installation/03_installing_rpm_package.mdx
product_docs/docs/eprs/7.0/03_installation/05_post_installation_host_environment.mdx
product_docs/docs/eprs/7.0/05_smr_operation/01_prerequisites/06_verifying_host_accessibility.mdx
product_docs/docs/eprs/7.0/05_smr_operation/02_creating_publication/01_registering_publication_server.mdx
product_docs/docs/eprs/7.0/05_smr_operation/03_creating_subscription/01_registering_subscription_server.mdx
product_docs/docs/eprs/7.0/10_appendix/04_miscellaneous_xdb_processing_topics/01_publications_and_subscriptions_server_conf_options/index.mdx

Updated platform support info
Organized installing using RPMs topic by architecture
Added section for RHEL8 Power installation

Replication Server RHEL8 Power updates

---

product_docs/docs/migration_toolkit/54/02_supported_operating_systems_and_database_versions.mdx
product_docs/docs/migration_toolkit/54/05_installing_mtk.mdx
product_docs/docs/migration_toolkit/55/02_supported_operating_systems_and_database_versions.mdx
product_docs/docs/migration_toolkit/55/05_installing_mtk.mdx
product_docs/docs/mysql_data_adapter/2.7.0/02_requirements_overview.mdx
product_docs/docs/mysql_data_adapter/2.7.0/04_installing_the_mysql_data_adapter.mdx
product_docs/docs/mysql_data_adapter/2.7.0/05_updating_the_mysql_data_adapter.mdx
product_docs/docs/mysql_data_adapter/2.7.0/12_uninstalling_the_mysql_data_adapter.mdx

Updated the platform support topic
Added RHEL 8 Power install instructions

MKT RHEL 8 Power updates

---

product_docs/docs/mysql_data_adapter/2.5.5/02_requirements_overview.mdx
product_docs/docs/mysql_data_adapter/2.5.5/04_installing_the_mysql_data_adapter.mdx
product_docs/docs/mysql_data_adapter/2.5.5/05_updating_the_mysql_data_adapter.mdx
product_docs/docs/mysql_data_adapter/2.5.5/11_uninstalling_the_mysql_data_adapter.mdx
product_docs/docs/mysql_data_adapter/2.6.0/02_requirements_overview.mdx
product_docs/docs/mysql_data_adapter/2.6.0/04_installing_the_mysql_data_adapter.mdx
product_docs/docs/mysql_data_adapter/2.6.0/05_updating_the_mysql_data_adapter.mdx
product_docs/docs/mysql_data_adapter/2.6.0/12_uninstalling_the_mysql_data_adapter.mdx
product_docs/docs/mysql_data_adapter/2.7.0/02_requirements_overview.mdx
product_docs/docs/mysql_data_adapter/2.7.0/04_installing_the_mysql_data_adapter.mdx

Updated platform support
Restructured install topic and added RHEL 8 Power section

MySQL FDW updates for RHEL 8 Power

---

product_docs/docs/mongo_data_adapter/5.2.8/02_requirements_overview.mdx
product_docs/docs/mongo_data_adapter/5.2.8/04_installing_the_mongo_data_adapter.mdx
product_docs/docs/mongo_data_adapter/5.2.8/05_updating_the_mongo_data_adapter.mdx
product_docs/docs/mongo_data_adapter/5.2.8/11_uninstalling_the_mongo_data_adapter.mdx
product_docs/docs/mongo_data_adapter/5.2.9/02_requirements_overview.mdx
product_docs/docs/mongo_data_adapter/5.2.9/04_installing_the_mongo_data_adapter.mdx
product_docs/docs/mongo_data_adapter/5.2.9/05_updating_the_mongo_data_adapter.mdx
product_docs/docs/mongo_data_adapter/5.2.9/11_uninstalling_the_mongo_data_adapter.mdx
product_docs/docs/mongo_data_adapter/5.3.0/02_requirements_overview.mdx
product_docs/docs/mongo_data_adapter/5.3.0/04_installing_the_mongo_data_adapter.mdx
product_docs/docs/mongo_data_adapter/5.3.0/05_updating_the_mongo_data_adapter.mdx
product_docs/docs/mongo_data_adapter/5.3.0/11_uninstalling_the_mongo_data_adapter.mdx

- Updated platform support info
- Restructured the install topic and added section for RHEL 8 Power

Mongo FDW updates for RHEL 8 Power

---

product_docs/docs/hadoop_data_adapter/2.0.7/02_requirements_overview.mdx
product_docs/docs/hadoop_data_adapter/2.0.7/05_installing_the_hadoop_data_adapter.mdx
product_docs/docs/hadoop_data_adapter/2.0.7/06_updating_the_hadoop_data_adapter.mdx
product_docs/docs/hadoop_data_adapter/2.0.7/11_uninstalling_the_hadoop_data_adapter.mdx
product_docs/docs/hadoop_data_adapter/2.0.8/02_requirements_overview.mdx
product_docs/docs/hadoop_data_adapter/2.0.8/05_installing_the_hadoop_data_adapter.mdx
product_docs/docs/hadoop_data_adapter/2.0.8/06_updating_the_hadoop_data_adapter.mdx
product_docs/docs/hadoop_data_adapter/2.0.8/11_uninstalling_the_hadoop_data_adapter.mdx
product_docs/docs/hadoop_data_adapter/2.1.0/02_requirements_overview.mdx
product_docs/docs/hadoop_data_adapter/2.1.0/05_installing_the_hadoop_data_adapter.mdx
product_docs/docs/hadoop_data_adapter/2.1.0/06_updating_the_hadoop_data_adapter.mdx
product_docs/docs/hadoop_data_adapter/2.1.0/11_uninstalling_the_hadoop_data_adapter.mdx

- Updated the platform support info 
- Reformatted the install topic and added new section for RHEL8 Power

Hadoop FDW: platform support updates and new Power install section

---

.github/workflows/sync-and-process-files.yml
scripts/source/dispatch_product.py
scripts/source/livecompare.js

* Added LiveCompare to the sync-and-process-files workflow
* Moved the logic for which process commands to use out of the workflow and into a dispatch script
**Content**

Add LiveCompare automation and use a dispatch script.

---

product_docs/docs/biganimal/release/using_cluster/04_backup_and_restore.mdx

Updated Backing up and restoring topic based on feedback from free trail feedback

BigAnimal: Additional restore info 

---

product_docs/docs/biganimal/release/administering_cluster/01a_superset_access.mdx
product_docs/docs/biganimal/release/administering_cluster/index.mdx
product_docs/docs/biganimal/release/using_cluster/04_backup_and_restore.mdx
product_docs/docs/biganimal/release/using_cluster/06_analyze_with_superset.mdx
product_docs/docs/biganimal/release/using_cluster/index.mdx

BigAnimal: 
- Added documentation for Superset feature
- Added more info on restores

Release: 2022-01-27

---

scripts/source/bdr.js
scripts/source/dispatch_product.py
scripts/source/livecompare.js
scripts/source/pglogical.js

@jericson-edb and @josh-heyer, I'd like us to get into the habit of using code formatters:
* Python: black
* JS: prettier

style: format using prettier and black

---

gatsby-node.js
static/_redirects

Catch-all redirects for everything not remapped under /edb-docs

Release: 2022-01-28

---

advocacy_docs/supported-open-source/barman/single-server-streaming/step01-db-setup.mdx
advocacy_docs/supported-open-source/barman/single-server-streaming/step02-backup-setup.mdx
advocacy_docs/supported-open-source/barman/single-server-streaming/step03-backup.mdx
advocacy_docs/supported-open-source/barman/single-server-streaming/step04-restore.mdx

George got this repo moved into the fold; point to the EDB version so that I can retire the personal repo.
**Content**

Update Barman demo Compose URL to point to EDB repo

---

advocacy_docs/supported-open-source/barman/single-server-streaming/step01-db-setup.mdx
advocacy_docs/supported-open-source/barman/single-server-streaming/step02-backup-setup.mdx
advocacy_docs/supported-open-source/barman/single-server-streaming/step03-backup.mdx
advocacy_docs/supported-open-source/barman/single-server-streaming/step04-restore.mdx
product_docs/docs/biganimal/release/using_cluster/06_demonstration_oracle_compatibility.mdx
scripts/source/dispatch_product.py
scripts/source/package-lock.json
scripts/source/package.json

- Fixes for the LiveCompare import script
- Update Barman demo to point to EDB repo
- Import instructions for Chinook sample database on BA Oracle compat demo

Release: 2022-01-28b

---

product_docs/docs/epas/14/epas_guide/03_database_administration/04_pgsnmpd.mdx

Add deprecation notice
**Content**
- [ x] This PR removes existing content

EPAS: added pgsnmpd deprecation note

---

product_docs/docs/biganimal/release/getting_started/00_free_trial.mdx

Added BigAnimal free trial topic to Getting started

BigAnimal: Free trial topic

---

product_docs/docs/efm/4/12_upgrading_existing_cluster.mdx
product_docs/docs/efm/4/index.mdx

Updated landing page and upgrading topic

EFM: clarifying use of cluster terminology

---

product_docs/docs/harp/2.0/04_configuration.mdx
product_docs/docs/harp/2.0/07_harp_proxy.mdx
product_docs/docs/harp/2.0/08_harpctl.mdx
product_docs/docs/harp/2.0/11_release-notes.mdx

* Import HARP 2.0.1 content.
**Content**

Import HARP 2.0.1 from source

---

product_docs/docs/biganimal/release/using_cluster/06_analyze_with_superset.mdx

Added a note about Superset requirements with private network database clusters.

BigAnimal: UPM-4539 Superset

---

product_docs/docs/migration_portal/3.5.0/04_mp_migrating_database/01_mp_schema_extraction.mdx
static/_redirects

Changes suggested after GA doc review.

MP: Issue #2294 - Extracting schema changes

---

product_docs/docs/eprs/7.0/07_common_operations/11_using_ssl_connections.mdx
product_docs/docs/eprs/7.0/images/add_db_ssl.png

Replication Server XDB-1146 SSL changes

---

product_docs/docs/biganimal/release/getting_started/00_free_trial.mdx

BigAnimal: free trial storage info

---

product_docs/docs/biganimal/release/using_cluster/06_analyze_with_superset.mdx

Updated links to Superset docs

BigAnimal: UPM-4680 - Superset links

---

scripts/source/package-lock.json
scripts/source/package.json

- Rolled back package versions to avoid `ERR_REQUIRE_ESM` failures.

Revert to older versions of packages to avoid ESM problems

---

scripts/source/bdr.js
scripts/source/dispatch_product.py

* Fixed a typo in dispatch_product.py
* Added BDR automation

Fixed a typo and add BDR

---

product_docs/docs/pgpool/4.3/03_configuring_connection_pooling.mdx

Noted pool_conn_dbname is removed

noted parameter has been removed

---

product_docs/docs/biganimal/release/overview/support/index.mdx

Added links to SLO info and terms

BigAnimal: support links

---

.github/workflows/sync-and-process-files.yml
scripts/source/dispatch_product.py
scripts/source/pglogical.js
scripts/source/test/README.md
scripts/source/test/sync-bdr.json
scripts/source/test/sync-harp.json
scripts/source/test/sync-lc.json
scripts/source/test/sync-pglogical.json
scripts/source/test/test_all_syncs.ksh

* Added test for the sync-and-process action
* Add pglogical
* Add HARP (broken in testing because I don't have rsync installed in the image)
* Don't try creating a PR in testing
* Make sure Node scripts fail properly if they don't work.

Test sync-and-process action

---

product_docs/docs/pglogical/3.7/configuration.mdx
product_docs/docs/pglogical/3.7/ddl.mdx
product_docs/docs/pglogical/3.7/index.mdx
product_docs/docs/pglogical/3.7/nodes.mdx
product_docs/docs/pglogical/3.7/release-notes.mdx
product_docs/docs/pglogical/3.7/replication-sets.mdx
product_docs/docs/pglogical/3.7/restrictions.mdx
product_docs/docs/pglogical/3.7/subscriptions/index.mdx
product_docs/docs/pglogical/3.7/subscriptions/pglogical-writer.mdx
product_docs/docs/pglogical/3.7/troubleshooting.mdx

* Import pglogical 3.7.15
**Content**

Import pglogical 3.7.15 from source

---

product_docs/docs/bdr/3.7/appusage.mdx
product_docs/docs/bdr/3.7/camo_clients.mdx
product_docs/docs/bdr/3.7/functions.mdx
product_docs/docs/bdr/3.7/index.mdx
product_docs/docs/bdr/3.7/isolation_details.mdx
product_docs/docs/bdr/3.7/known-issues.mdx
product_docs/docs/bdr/3.7/licenses.mdx
product_docs/docs/bdr/3.7/release-notes.mdx
product_docs/docs/bdr/3.7/repsets.mdx

* Import BDR 3.7.15 from source
**Content**

Content/bdr 3.7.15

---

product_docs/docs/migration_portal/3.5.0/01_mp_release_notes/index.mdx

 Missed an update to the MP 3.5 rel notes

---

static/_redirects

Correct my misunderstanding from #2295

redirect edb*plus from ALL epas versions

---

product_docs/docs/migration_portal/3.5.0/03_mp_using_portal/03_mp_quick_start.mdx
product_docs/docs/migration_portal/3.5.0/03_mp_using_portal/index.mdx
product_docs/docs/migration_portal/3.5.0/index.mdx

Made 3.5.1 Quick Start topic changes to 3.5

added quick start topic to MP 3.5

---

product_docs/docs/biganimal/release/getting_started/creating_a_cluster/index.mdx
product_docs/docs/biganimal/release/using_cluster/03_modifying_your_cluster/index.mdx

Added information about selecting the category of instance types

BigAnimal: additional instance types

---

gatsby-node.js
src/templates/file.js

Bugfix for an issue that was preventing CNP's sample files from loading.

Release: 2022-02-25

---

product_docs/docs/biganimal/release/using_cluster/05_monitoring_and_logging/index.mdx

- Deleted the instructions to find the BigAnimal Shared Dashboards as Shared Dashboards are decommissioned
- Added the instructions to find the BigAnimal Customer Azure Workbook as they replace the Shared Dashboards
**Content**

fix(UPM-5034): Update documentation to direct users to customer Workbooks

---

product_docs/docs/biganimal/release/administering_cluster/01_portal_access.mdx

Updated Managing portal access topic to reflect current behavior

BigAnimal: upm-5119 users can't change permissions

---

product_docs/docs/biganimal/release/using_cluster/03_modifying_your_cluster/05_db_configuration_parameters.mdx

Added a note to the Parameters topic listing the parameters that can't be decreased

BigAnimal: UPM-5228 - parameters change

---

product_docs/docs/biganimal/release/getting_started/01_preparing_azure/01_understanding_qotas_in_azure.mdx
product_docs/docs/biganimal/release/getting_started/01_preparing_azure/index.mdx

Added link to Azure topic about choosing instance types

Additional instance types in preflight script - UPM-5123

---

product_docs/docs/pgpool/4.3/02_extensions.mdx

Fixed the platforms under the respective topics.
**Content**

Clarified OS support in PgPool extensions topic

---

product_docs/docs/epas/10/epas_limitations/index.mdx
product_docs/docs/epas/11/epas_limitations/index.mdx
product_docs/docs/epas/12/epas_limitations/index.mdx
product_docs/docs/epas/13/epas_limitations/index.mdx
product_docs/docs/epas/14/epas_limitations/index.mdx

Updated NFS limitation language for v10-14

EPAS: updated NFS limitation language

---

product_docs/docs/biganimal/release/reference/cli.mdx

- Fixed the binary validation typo.
- Update configure setting commands.
- Update shell completion guide.
- Add postgresql cluster configuration update guide.
- Add restore-cluster commands introduction.
**Content**

feat(UPM-4125): Update biganimal CLI document to catch up v1.2.0 changes

---

product_docs/docs/epas/11/epas_inst_linux/03_using_a_package_manager_to_install_advanced_server.mdx
product_docs/docs/epas/12/epas_inst_linux/03_using_a_package_manager_to_install_advanced_server.mdx
product_docs/docs/epas/13/epas_inst_linux/03_using_a_package_manager_to_install_advanced_server.mdx
product_docs/docs/pem/8/pem_inst_guide_linux/04_installing_postgres_enterprise_manager/03_installing_pem_server_using_edb_repository/04_pem_server_sles12_x86.mdx
product_docs/docs/pem/8/pem_inst_guide_linux/04_installing_postgres_enterprise_manager/03_installing_pem_server_using_edb_repository/10_pem_server_sles12_ppcle.mdx

Added SLES 12 install steps for EPAS 11 to 13
**Content**

Added SLES 12 install steps for EPAS 11 to 13

---

product_docs/docs/biganimal/release/getting_started/creating_a_cluster/index.mdx

Removed note re preview on Create Cluster topic

Removed note re preview

---

product_docs/docs/epas/14/epas_rel_notes/20_epas14_rel_notes.mdx

replaced v13 included component content with the correct v14 information

EPAS 14: Fixed included components section

---

product_docs/docs/eprs/7.0/02_overview/04_design_replication_system/03_restrictions_on_replicated_database_objects.mdx

Updated Restrictions on Postgres database objects topic with changes listed on XDB-1093

EPRS 7.0: XDB-1093- Data types

---

product_docs/docs/epas/14/epas_rel_notes/20_epas14_rel_notes.mdx
product_docs/docs/eprs/7.0/02_overview/04_design_replication_system/03_restrictions_on_replicated_database_objects.mdx

- EPRS 7: updated data type information
- EPAS 14: Fixed included components section

Release: 2022-03-07

---

product_docs/docs/biganimal/release/using_cluster/06_analyze_with_superset.mdx

Fixed the links to the Superset documentation

BigAnimal: Fixed superset links

---

advocacy_docs/supported-open-source/pgbackrest/06-use_case_1.mdx
advocacy_docs/supported-open-source/pgbackrest/09-tls_server.mdx
advocacy_docs/supported-open-source/pgbackrest/99-faq.mdx
advocacy_docs/supported-open-source/pgbackrest/index.mdx

- 2.38 release
- FAQ about cpu cores needed on a backup server
- WebIdentity authentication for AWS S3
- AWS S3 server-side encryption using KMS
- TLS Server Support Feature
**Content**
(it would be great to see the TLS page live on a staging area before pushing to production)

pgBackRest release update and new features

---

advocacy_docs/supported-open-source/pgbackrest/06-use_case_1.mdx
advocacy_docs/supported-open-source/pgbackrest/09-tls_server.mdx
advocacy_docs/supported-open-source/pgbackrest/99-faq.mdx
advocacy_docs/supported-open-source/pgbackrest/index.mdx
product_docs/docs/biganimal/release/using_cluster/05_monitoring_and_logging/06_metrics.mdx

pgBackRest 2.38 release
BigAnimal: metrics update

Release: 2022-03-09a

---

product_docs/docs/biganimal/release/using_cluster/04_backup_and_restore.mdx

added default info to backup topic

BigAnimal: add default backup retention period

---

product_docs/docs/migration_toolkit/55/02_supported_operating_systems_and_database_versions.mdx
product_docs/docs/migration_toolkit/55/08_mtk_command_options.mdx
product_docs/docs/migration_toolkit/55/mtk_rel_notes/05_mkt_5522_rel_notes.mdx
product_docs/docs/migration_toolkit/55/mtk_rel_notes/index.mdx

MTK 55.2.2 release

---

product_docs/docs/edb_plus/39/02a_release_notes/07_edbplus39.03_rel_notes.mdx
product_docs/docs/edb_plus/39/02a_release_notes/index.mdx
product_docs/docs/edb_plus/39/04_using_edb_plus.mdx
product_docs/docs/edb_plus/39/05_using_edb_plus_with_ssl.mdx
product_docs/docs/epas/13/epas_rel_notes/20_epas13_rel_notes.mdx

Added EDB*Plus 39.0.3 version as per ED-154

Added EDB*Plus 39.0.3 version

---

product_docs/docs/migration_toolkit/55/mtk_rel_notes/05_mkt_5522_rel_notes.mdx

Updated MTK 55.2.2 release notes with correct CVE identified in the security fixes

Updated MTK 55.2.2 release notes

---

advocacy_docs/migrating/oracle/overview.mdx

Update intro section and removed section discussing Migration approaches (i.e., Re-hosting, Re-platforming, and Restructuring)  EDB's migration capabilities, and this document in particular, is primarily focused on re-platforming an Oracle database application on EDB Postgres Advanced Server.

Update Migration Handbook Overview Section

---

product_docs/docs/migration_portal/3.5.2/04_mp_migrating_database/03_mp_schema_migration.mdx

MP fix for Issue #2467

---

product_docs/docs/efm/4/efm_deploy_arch/05_efm_pgbouncer.mdx

This is a fix for https://enterprisedb.atlassian.net/browse/EFM-1459
**Content**

add explicit ssh notes about users

---

advocacy_docs/migrating/oracle/edb_migration_tools.mdx

Reorganized and rewrote the section

Rewrote section

---

src/templates/learn-doc.js

This has been there for over a year and apparently @sethijs was the first to notice.

Remove errant "could"

---

product_docs/docs/pem/8/pem_admin/01_overview/02_installing_pem_overview.mdx

PEM: fix broken links

---

product_docs/docs/biganimal/release/getting_started/00_free_trial.mdx
product_docs/docs/biganimal/release/getting_started/creating_a_cluster/index.mdx
product_docs/docs/biganimal/release/overview/03a_region_support.mdx

Updated the Free trial topic with AWS info

BigAnimal: UPM-4772 - AWS Free Trial

---

advocacy_docs/supported-open-source/barman/pg-backup-api/01-installation.mdx
advocacy_docs/supported-open-source/barman/pg-backup-api/02-securing-pg-backup-api.mdx
advocacy_docs/supported-open-source/barman/pg-backup-api/index.mdx
product_docs/docs/ocl_connector/14.1.0.1/01_ocl_release_notes.mdx
product_docs/docs/ocl_connector/14.1.0.1/02_supported_platforms.mdx
product_docs/docs/ocl_connector/14.1.0.1/03_libpq_compatibility.mdx
product_docs/docs/ocl_connector/14.1.0.1/04_open_client_library/01_installing_and_configuring_the_ocl_connector/index.mdx
product_docs/docs/ocl_connector/14.1.0.1/04_open_client_library/01_installing_and_configuring_the_ocl_connector/install_on_linux_using_edb_repo/01_ocl_connector14_rhel_variants8_x86.mdx
product_docs/docs/ocl_connector/14.1.0.1/04_open_client_library/01_installing_and_configuring_the_ocl_connector/install_on_linux_using_edb_repo/02_ocl_connector14_rhel_variants7_x86.mdx
product_docs/docs/ocl_connector/14.1.0.1/04_open_client_library/01_installing_and_configuring_the_ocl_connector/install_on_linux_using_edb_repo/03_ocl_connector14_sles15_x86.mdx
product_docs/docs/ocl_connector/14.1.0.1/04_open_client_library/01_installing_and_configuring_the_ocl_connector/install_on_linux_using_edb_repo/07_ocl_connector14_rhel8_ppcle.mdx
product_docs/docs/ocl_connector/14.1.0.1/04_open_client_library/01_installing_and_configuring_the_ocl_connector/install_on_linux_using_edb_repo/09_ocl_connector14_sles15_ppcle.mdx
product_docs/docs/ocl_connector/14.1.0.1/04_open_client_library/01_installing_and_configuring_the_ocl_connector/install_on_linux_using_edb_repo/10_ocl_connector14_sles12_ppcle.mdx
product_docs/docs/ocl_connector/14.1.0.1/04_open_client_library/01_installing_and_configuring_the_ocl_connector/install_on_linux_using_edb_repo/11_updating_rpm_install.mdx
product_docs/docs/ocl_connector/14.1.0.1/04_open_client_library/01_installing_and_configuring_the_ocl_connector/install_on_linux_using_edb_repo/index.mdx
product_docs/docs/ocl_connector/14.1.0.1/04_open_client_library/02_forming_a_connection_string.mdx
product_docs/docs/ocl_connector/14.1.0.1/04_open_client_library/03_compiling_and_linking_a_program.mdx
product_docs/docs/ocl_connector/14.1.0.1/04_open_client_library/04_ref_cursor_support.mdx
product_docs/docs/ocl_connector/14.1.0.1/04_open_client_library/05_ocl_function_reference.mdx
product_docs/docs/ocl_connector/14.1.0.1/04_open_client_library/06_ocl_error_codes_reference.mdx
product_docs/docs/ocl_connector/14.1.0.1/04_open_client_library/07_multithreading_support.mdx
product_docs/docs/ocl_connector/14.1.0.1/04_open_client_library/08_otl_support.mdx
product_docs/docs/ocl_connector/14.1.0.1/04_open_client_library/index.mdx
product_docs/docs/ocl_connector/14.1.0.1/05_generating_the_ocl_trace.mdx
product_docs/docs/ocl_connector/14.1.0.1/06_using_ssl.mdx
product_docs/docs/ocl_connector/14.1.0.1/07_scram_compatibility.mdx
product_docs/docs/ocl_connector/14.1.0.1/index.mdx

- Barman: Postgres Backup API 
- OCL connector editing pass

Release: 2022-04-07

---

product_docs/docs/biganimal/release/using_cluster/04_backup_and_restore.mdx

Updated the first sentence of the Restores section

BigAnimal: clarifying when restores are possible

---

product_docs/docs/biganimal/release/administering_cluster/04_customizing_policy_definitions.mdx

BigAnimal: cleanup of new Azure policies topic

Release: 2022-04-14

---

product_docs/docs/biganimal/release/reference/api.mdx

- Updated the BigAnimal "How to use API" guidance with the latest `/auth/provider` API change.
- Updated the BigAnimal `get-token.sh` script with the latest help message. 
**Content**

Update BigAnimal get-token.sh script and how to use API guidance

---

product_docs/docs/odbc_connector/13/03_installing_edb_odbc/index.mdx

created a PR for a commit I forgot to make on a branch I already merged

ODBC connector: adding the corrected redirect

---

advocacy_docs/migrating/oracle/index.mdx
src/pages/index.js

- Put PostGIS under EPAS
- Changed Migration Handbook title to Migration Overview and put MTK and MP under it
- Moved Migration to top right

Prototyping home page changes

---

product_docs/docs/biganimal/release/pricing_and_billing/index.mdx

Updates to existing Pricing and billing topic

BigAnimal: direct billing

---

.dockerignore
product_docs/docs/biganimal/release/overview/03_security/index.mdx
product_docs/docs/biganimal/release/using_cluster/02_connecting_your_cluster/01_connecting_from_azure/01_private_endpoint.mdx
product_docs/docs/efm/4/03_installing_efm/index.mdx
product_docs/docs/hadoop_data_adapter/2/05_installing_the_hadoop_data_adapter/index.mdx
product_docs/docs/migration_toolkit/55/05_installing_mtk/install_on_linux/ibm_power_ppc64le/11_mtk55_sles15_ppcle.mdx
product_docs/docs/migration_toolkit/55/05_installing_mtk/install_on_linux/ibm_power_ppc64le/12_mtk55_sles12_ppcle.mdx
product_docs/docs/migration_toolkit/55/05_installing_mtk/install_on_linux/index.mdx
product_docs/docs/migration_toolkit/55/05_installing_mtk/install_on_linux/x86_amd64/03_mtk55_rhel7_x86.mdx
product_docs/docs/mongo_data_adapter/5/04_installing_the_mongo_data_adapter/index.mdx
product_docs/docs/mysql_data_adapter/2/04_installing_the_mysql_data_adapter/ibm_power_ppc64le/13_mysql_rhel8_ppcle.mdx
product_docs/docs/mysql_data_adapter/2/04_installing_the_mysql_data_adapter/ibm_power_ppc64le/15_mysql_rhel7_ppcle.mdx
product_docs/docs/mysql_data_adapter/2/04_installing_the_mysql_data_adapter/ibm_power_ppc64le/17_mysql_sles15_ppcle.mdx
product_docs/docs/mysql_data_adapter/2/04_installing_the_mysql_data_adapter/ibm_power_ppc64le/19_mysql_sles12_ppcle.mdx
product_docs/docs/mysql_data_adapter/2/04_installing_the_mysql_data_adapter/ibm_power_ppc64le/index.mdx
product_docs/docs/mysql_data_adapter/2/04_installing_the_mysql_data_adapter/index.mdx
product_docs/docs/mysql_data_adapter/2/04_installing_the_mysql_data_adapter/x86_amd64/01_mysql_rhel8_x86.mdx
product_docs/docs/mysql_data_adapter/2/04_installing_the_mysql_data_adapter/x86_amd64/02_mysql_other_linux8_x86.mdx
product_docs/docs/mysql_data_adapter/2/04_installing_the_mysql_data_adapter/x86_amd64/03_mysql_rhel7_x86.mdx
product_docs/docs/mysql_data_adapter/2/04_installing_the_mysql_data_adapter/x86_amd64/04_mysql_centos7_x86.mdx
product_docs/docs/mysql_data_adapter/2/04_installing_the_mysql_data_adapter/x86_amd64/05_mysql_sles15_x86.mdx
product_docs/docs/mysql_data_adapter/2/04_installing_the_mysql_data_adapter/x86_amd64/07_mysql_sles12_x86.mdx
product_docs/docs/mysql_data_adapter/2/04_installing_the_mysql_data_adapter/x86_amd64/09_mysql_ubuntu20_deb10_x86.mdx
product_docs/docs/mysql_data_adapter/2/04_installing_the_mysql_data_adapter/x86_amd64/11_mysql_ubuntu18_deb9_x86.mdx
product_docs/docs/mysql_data_adapter/2/04_installing_the_mysql_data_adapter/x86_amd64/index.mdx

- BigAnimal: 
- fixed broken links in Security topic
- fixed typo in Private Endpoint example topic
- MySQL Connector: more restructuring of install topics

Release: 2022-04-25

---

static/_redirects

Made the comment clearer so that we know how to set up the redirect correctly

updated comment for MP in redirect file

---

product_docs/docs/odbc_connector/13/03_installing_edb_odbc/01_installing_linux/ibm_power_ppc64le/09_odbc13_rhel8_ppcle.mdx
product_docs/docs/odbc_connector/13/03_installing_edb_odbc/01_installing_linux/ibm_power_ppc64le/10_odbc13_rhel7_ppcle.mdx
product_docs/docs/odbc_connector/13/03_installing_edb_odbc/01_installing_linux/ibm_power_ppc64le/12_odbc13_sles12_ppcle.mdx
product_docs/docs/odbc_connector/13/03_installing_edb_odbc/01_installing_linux/ibm_power_ppc64le/index.mdx
product_docs/docs/odbc_connector/13/03_installing_edb_odbc/01_installing_linux/index.mdx
product_docs/docs/odbc_connector/13/03_installing_edb_odbc/01_installing_linux/x86_amd64/01_odbc13_rhel8_x86.mdx
product_docs/docs/odbc_connector/13/03_installing_edb_odbc/01_installing_linux/x86_amd64/02_odbc13_other_linux8_x86.mdx
product_docs/docs/odbc_connector/13/03_installing_edb_odbc/01_installing_linux/x86_amd64/03_odbc13_rhel7_x86.mdx
product_docs/docs/odbc_connector/13/03_installing_edb_odbc/01_installing_linux/x86_amd64/04_odbc13_centos7_x86.mdx
product_docs/docs/odbc_connector/13/03_installing_edb_odbc/01_installing_linux/x86_amd64/05_odbc13_sles15_x86.mdx
product_docs/docs/odbc_connector/13/03_installing_edb_odbc/01_installing_linux/x86_amd64/06_odbc13_sles12_x86.mdx
product_docs/docs/odbc_connector/13/03_installing_edb_odbc/01_installing_linux/x86_amd64/07_odbc13_ubuntu20_deb10_x86.mdx
product_docs/docs/odbc_connector/13/03_installing_edb_odbc/01_installing_linux/x86_amd64/08_odbc13_ubuntu18_deb9_x86.mdx
product_docs/docs/odbc_connector/13/03_installing_edb_odbc/01_installing_linux/x86_amd64/index.mdx
product_docs/docs/odbc_connector/13/13_upgrading_rpm_install.mdx

added an hierarchical toc based on architecture for linux installation on ODBC

---

product_docs/docs/efm/4/efm_rel_notes/08_efm_42_rel_notes.mdx

More information about the change:
https://enterprisedb.atlassian.net/browse/EFM-1369
**Content**

add note about repeated 'primary left' email warning

---

product_docs/docs/biganimal/release/administering_cluster/01a_superset_access.mdx

Updated Owner to Account Owner on Superset topic

BigAnimal: updated EDB role names for Superset

---

product_docs/docs/efm/4/architecture.mdx
product_docs/docs/efm/4/efm_deploy_arch/index.mdx
product_docs/docs/efm/4/efm_quick_start/index.mdx
product_docs/docs/efm/4/index.mdx

Moved architecture info out of the main landing page into a separate topic. 
Did some consolidation of the intros to the architecture topic and the choosing your deployment topics

EFM: applying more content model changes

---

product_docs/docs/pgd/4/deployments/self-managed.mdx
product_docs/docs/pgd_cli/1/index.mdx
product_docs/docs/pgd_cli/1/rel_notes/epd_cli_1_rel_notes.mdx
product_docs/docs/pgd_cli/1/rel_notes/index.mdx
product_docs/docs/pgd_cli/1/rel_notes/pgd_cli_1_rel_notes.mdx
product_docs/docs/pgd_cli/1/release-notes.mdx

Updates to main landing page and release notes

PGD CLI copy edits

---

advocacy_docs/supported-open-source/cloud_native_pg/index.mdx

Replaced PostgreSQL boilerplate with CloudNativePG information.

CloudNativePG stub file updates

---

product_docs/docs/pgd_cli/1/pgd.mdx
product_docs/docs/pgd_cli/1/pgd_check-health.mdx
product_docs/docs/pgd_cli/1/pgd_show-camo.mdx
product_docs/docs/pgd_cli/1/pgd_show-clockskew.mdx
product_docs/docs/pgd_cli/1/pgd_show-events.mdx
product_docs/docs/pgd_cli/1/pgd_show-nodes.mdx
product_docs/docs/pgd_cli/1/pgd_show-raft.mdx
product_docs/docs/pgd_cli/1/pgd_show-replslots.mdx
product_docs/docs/pgd_cli/1/pgd_show-subscriptions.mdx
product_docs/docs/pgd_cli/1/pgd_show-version.mdx

- Update pgdcli auto-generated files as per review comments
- Fixed some formatting issues such as removed extra blank lines, added code type (sh or text) for examples/command section etc
**Content**

Update pgdcli auto-generated files as per review comments

---

gatsby-node.js

CNP is now EDB Postgres for Kubernetes and lives in the versioned docs - we never bothered adding support for sample files there, but one sample remains so we'll need to support it.
**Content**

add support for sample files in versioned docs

---

product_docs/docs/biganimal/release/getting_started/creating_a_cluster/index.mdx
product_docs/docs/biganimal/release/using_cluster/02_connecting_your_cluster/01_connecting_from_azure/01_private_endpoint.mdx
product_docs/docs/biganimal/release/using_cluster/02_connecting_your_cluster/01_connecting_from_azure/index.mdx
product_docs/docs/biganimal/release/using_cluster/02_connecting_your_cluster/index.mdx
product_docs/docs/biganimal/release/using_cluster/03_modifying_your_cluster/index.mdx

Added notes indicating that you can't switch to public networking after setting up private networking.

BigAnimal: private networking restrictions

---

product_docs/docs/biganimal/release/getting_started/creating_a_cluster/index.mdx
product_docs/docs/biganimal/release/using_cluster/02_connecting_your_cluster/01_connecting_from_azure/01_private_endpoint.mdx
product_docs/docs/biganimal/release/using_cluster/02_connecting_your_cluster/01_connecting_from_azure/index.mdx
product_docs/docs/biganimal/release/using_cluster/02_connecting_your_cluster/index.mdx
product_docs/docs/biganimal/release/using_cluster/03_modifying_your_cluster/index.mdx
product_docs/docs/efm/4/12_upgrading_existing_cluster.mdx

BigAnimal: added notes re: private > public networking
EFM: added note to uninstall section

Release: 2022-05-13

---

product_docs/docs/biganimal/release/getting_started/identity_provider/okta.mdx

Small spacing tweak to avoid restarting list numbering after the table.
**Content**

Fix break in list numbering for BA Okta topic

---

product_docs/docs/pgd/4/deployments/dbaas.mdx
product_docs/docs/pgd/4/deployments/index.mdx
product_docs/docs/pgd/4/deployments/kubernetes.mdx
product_docs/docs/pgd/4/deployments/tpaexec/configuration_syntax.mdx
product_docs/docs/pgd/4/deployments/tpaexec/index.mdx
product_docs/docs/pgd/4/deployments/tpaexec/overview.mdx
product_docs/docs/pgd/4/deployments/tpaexec/quick_start.mdx
product_docs/docs/pgd/4/images/nodes.png
product_docs/docs/pgd/4/overview/index.mdx
product_docs/docs/pgd/4/rel_notes/index.mdx

Restructured Deployment options section
Other cleanup

PGD copy edits by Dee Dee

---

product_docs/docs/pgd/4/images/ha-ao-bdr.png
product_docs/docs/pgd/4/images/ha-ao.png
product_docs/docs/pgd/4/images/ha-unit-bdr.png
product_docs/docs/pgd/4/images/ha-unit.png
product_docs/docs/pgd/4/overview/index.mdx

High priority changes that didn't get into initial PGD build.

PGD changes for May 17 build

---

product_docs/docs/postgres_for_kubernetes/1/index.mdx

removed an extra "is"

---

product_docs/docs/pgd_cli/1/index.mdx
product_docs/docs/pgd_cli/1/installing_cli.mdx
product_docs/docs/pgd_cli/1/using_cli.mdx

Moved content out of the main index file and created an Installing and Using topic

PGD CLI - restructure prototype

---

product_docs/docs/bdr/4/conflicts.mdx
product_docs/docs/pgd/4/compatibility_matrix.mdx
product_docs/docs/pgd_cli/1/index.mdx
product_docs/docs/pgd_cli/1/installing_cli.mdx
product_docs/docs/pgd_cli/1/using_cli.mdx
product_docs/docs/postgres_for_kubernetes/1/index.mdx

- BDR: copy edited Conflicts section
- PGD: added PGD CLI to compatibility matrix
- PGD CLI restructure
- EDB PG for Kubernetes: fixed typo

Release: 2022-05-18

---

product_docs/docs/bdr/4/index.mdx
product_docs/docs/pgd/4/cli.mdx
product_docs/docs/pgd/4/deployments/tpaexec/index.mdx
product_docs/docs/pgd/4/index.mdx
product_docs/docs/pgd/4/known_issues.mdx
product_docs/docs/pgd/4/overview/index.mdx
product_docs/docs/pgd/4/terminology.mdx
src/pages/index.js

- Changed Terminology to Concepts
- Added blurb from TCAexec doc about getting access
- Changed pglogical section to a note

PGD: latest comments from Kelly

---

product_docs/docs/pgd/4/deployments/tpaexec/index.mdx

forgot to submit a commit from previous PR review

typos in PGD TPAexec content

---

product_docs/docs/biganimal/release/getting_started/preparing_cloud_account/index.mdx

Added redirect for older file name change

BigAnimal: added redirect

---

product_docs/docs/bdr/3.7/backup.mdx
product_docs/docs/bdr/3.7/configuration.mdx
product_docs/docs/bdr/3.7/nodes.mdx
product_docs/docs/bdr/3.7/release-notes.mdx
product_docs/docs/bdr/3.7/repsets.mdx
product_docs/docs/pgd/4/deployments/tpaexec/index.mdx
product_docs/docs/pglogical/3.7/configuration.mdx
product_docs/docs/pglogical/3.7/release-notes.mdx
product_docs/docs/pglogical/3.7/subscriptions/index.mdx

- BDR 3.7.16 release
- pglogical 3.7.16 release

Release: 2022-05-19a

---

product_docs/docs/pgd/4/backup.mdx
product_docs/docs/pgd/4/deployments/tpaexec/index.mdx
product_docs/docs/pgd/4/index.mdx
product_docs/docs/pgd/4/known_issues.mdx

Fixed a couple topic titles and removed broken link

PGD: capitalization issues and broken link

---

product_docs/docs/biganimal/release/using_cluster/02_connecting_your_cluster/02_connecting_from_aws/index.mdx
product_docs/docs/pgd/4/backup.mdx
product_docs/docs/pgd/4/deployments/tpaexec/index.mdx
product_docs/docs/pgd/4/index.mdx
product_docs/docs/pgd/4/known_issues.mdx

PGD: fixed or removed broken links, capitalization, and location of known issues
BigAnimal: fixed spacing typo

Release: 2022-05-23

---

product_docs/docs/edb_plus/40/03_installing_edb_plus/install_on_linux/ibm_power_ppc64le/11_edbplus_sles15_ppcle.mdx
product_docs/docs/edb_plus/40/03_installing_edb_plus/install_on_linux/ibm_power_ppc64le/12_edbplus_sles12_ppcle.mdx

two small errors introduced into EDB*Plus during restructure process

fixed two editing errors

---

product_docs/docs/postgis/3.1/01a_installing_postgis/index.mdx

Fixed Installing PostGIS topic

PostGIS: fixing install topic typos

---

product_docs/docs/edb_plus/40/03_installing_edb_plus/install_on_linux/ibm_power_ppc64le/11_edbplus_sles15_ppcle.mdx
product_docs/docs/edb_plus/40/03_installing_edb_plus/install_on_linux/ibm_power_ppc64le/12_edbplus_sles12_ppcle.mdx
product_docs/docs/efm/4/01_prerequisites.mdx
product_docs/docs/postgis/3.1/01a_installing_postgis/index.mdx
src/styles/_docs.scss

Added support for nested ordered lists
EFM: update to autostart instructions
PostGIS: fixed Installing topic typos
EDP*Plus: fixed install topic typos

Release: 2022-05-24

---

product_docs/docs/pgd/4/deployments/tpaexec/index.mdx
product_docs/docs/pgd/4/deployments/tpaexec/installing_tpaexec.mdx
product_docs/docs/pgd/4/deployments/tpaexec/quick_start.mdx
product_docs/docs/pgd/4/deployments/tpaexec/using_tpaexec.mdx
product_docs/docs/pgd_cli/1/index.mdx
product_docs/docs/pgd_cli/1/installing_cli.mdx
product_docs/docs/pgd_cli/1/requirements.mdx
product_docs/docs/pgd_cli/1/using_cli.mdx

PGD-CLI: fixed a typo and added a requirements topic
PGD: updates to the TPAexec section

Release: 2022-05-25

---

product_docs/docs/biganimal/release/getting_started/identity_provider/auth0.mdx
product_docs/docs/biganimal/release/getting_started/identity_provider/index.mdx

BigAnimal: new Auth0 topic

---

product_docs/docs/biganimal/release/getting_started/identity_provider/auth0.mdx
product_docs/docs/biganimal/release/getting_started/identity_provider/index.mdx
product_docs/docs/hadoop_data_adapter/2/07_features_of_hdfs_fdw.mdx
product_docs/docs/hadoop_data_adapter/2/10b_example_aggregate_pushdown.mdx
product_docs/docs/hadoop_data_adapter/2/hadoop_rel_notes/hadoop_rel_notes_2.2.0.mdx
product_docs/docs/hadoop_data_adapter/2/hadoop_rel_notes/index.mdx
product_docs/docs/hadoop_data_adapter/2/index.mdx
product_docs/docs/mongo_data_adapter/5/06_features_of_mongo_fdw.mdx
product_docs/docs/mongo_data_adapter/5/08_example_using_the_mongo_data_adapter.mdx
product_docs/docs/mongo_data_adapter/5/08a_example_join_pushdown.mdx
product_docs/docs/mongo_data_adapter/5/08b_example_aggregate_pushdown.mdx
product_docs/docs/mongo_data_adapter/5/index.mdx
product_docs/docs/mongo_data_adapter/5/mongo_rel_notes/index.mdx
product_docs/docs/mongo_data_adapter/5/mongo_rel_notes/mongo5.4.0_rel_notes.mdx
product_docs/docs/mysql_data_adapter/2/06_features_of_mysql_fdw.mdx
product_docs/docs/mysql_data_adapter/2/07_configuring_the_mysql_data_adapter.mdx
product_docs/docs/mysql_data_adapter/2/10a_example_aggregate_func_push_down.mdx
product_docs/docs/mysql_data_adapter/2/10b_example_order_by_push_down.mdx
product_docs/docs/mysql_data_adapter/2/10c_example_limit_offset_push_down.mdx
product_docs/docs/mysql_data_adapter/2/index.mdx
product_docs/docs/mysql_data_adapter/2/mysql_rel_notes/index.mdx
product_docs/docs/mysql_data_adapter/2/mysql_rel_notes/mysql2.8.0_rel_notes.mdx

- Hadoop FDW 2.2.0 release
- Mongo FDW 5.4.0 release
- MySQL 2.8.0 release
- BigAnimal new Auth0 Idp topic

Release: 2022-05-26

---

product_docs/docs/biganimal/release/pricing_and_billing/index.mdx

Fixed typo ($4007-$600) > ($400-$600) in Pricing topic

BigAnimal: Pricing typo

---

product_docs/docs/pgd/4/choosing_server.mdx

A couple of minor typo fixes (e.g. "PostgeSQL") and minor rewording for clarity.
Cherry picked from https://github.com/EnterpriseDB/docs/pull/2728

PGD: typos and content improvements

---

product_docs/docs/biganimal/release/getting_started/identity_provider/google.mdx
product_docs/docs/biganimal/release/getting_started/identity_provider/index.mdx

https://enterprisedb.atlassian.net/browse/UPM-7537

Configure Google IDP

---

product_docs/docs/pem/8/tuning_performance/index.mdx

Fixed typo on index page: Tunind --> Tuning

Tuning performance: Typo fix

---

product_docs/docs/hadoop_data_adapter/2/05_installing_the_hadoop_data_adapter/index.mdx
product_docs/docs/hadoop_data_adapter/2/06_updating_the_hadoop_data_adapter.mdx
product_docs/docs/hadoop_data_adapter/2/07_features_of_hdfs_fdw.mdx
product_docs/docs/hadoop_data_adapter/2/08_configuring_the_hadoop_data_adapter.mdx
product_docs/docs/hadoop_data_adapter/2/09_using_the_hadoop_data_adapter.mdx
product_docs/docs/hadoop_data_adapter/2/10_identifying_data_adapter_version.mdx
product_docs/docs/hadoop_data_adapter/2/11_uninstalling_the_hadoop_data_adapter.mdx
product_docs/docs/hadoop_data_adapter/2/index.mdx
product_docs/docs/mongo_data_adapter/5/04_installing_the_mongo_data_adapter/index.mdx
product_docs/docs/mongo_data_adapter/5/05_updating_the_mongo_data_adapter.mdx
product_docs/docs/mongo_data_adapter/5/06_features_of_mongo_fdw.mdx
product_docs/docs/mongo_data_adapter/5/07_configuring_the_mongo_data_adapter.mdx
product_docs/docs/mongo_data_adapter/5/08_example_using_the_mongo_data_adapter.mdx
product_docs/docs/mongo_data_adapter/5/09_identifying_data_adapter_version.mdx
product_docs/docs/mongo_data_adapter/5/11_uninstalling_the_mongo_data_adapter.mdx
product_docs/docs/mongo_data_adapter/5/index.mdx
product_docs/docs/mysql_data_adapter/2/04_installing_the_mysql_data_adapter/index.mdx
product_docs/docs/mysql_data_adapter/2/05_updating_the_mysql_data_adapter.mdx
product_docs/docs/mysql_data_adapter/2/06_features_of_mysql_fdw.mdx
product_docs/docs/mysql_data_adapter/2/07_configuring_the_mysql_data_adapter.mdx
product_docs/docs/mysql_data_adapter/2/08_example_using_the_mysql_data_adapter.mdx
product_docs/docs/mysql_data_adapter/2/09_example_import_foreign_schema.mdx
product_docs/docs/mysql_data_adapter/2/11_identifying_data_adapter_version.mdx
product_docs/docs/mysql_data_adapter/2/12_uninstalling_the_mysql_data_adapter.mdx
product_docs/docs/mysql_data_adapter/2/13_troubleshooting.mdx
product_docs/docs/mysql_data_adapter/2/index.mdx

FDWs: restructuring prototype

---

product_docs/docs/hadoop_data_adapter/2/05_installing_the_hadoop_data_adapter/index.mdx
product_docs/docs/hadoop_data_adapter/2/06_updating_the_hadoop_data_adapter.mdx
product_docs/docs/hadoop_data_adapter/2/07_features_of_hdfs_fdw.mdx
product_docs/docs/hadoop_data_adapter/2/08_configuring_the_hadoop_data_adapter.mdx
product_docs/docs/hadoop_data_adapter/2/09_using_the_hadoop_data_adapter.mdx
product_docs/docs/hadoop_data_adapter/2/10_identifying_data_adapter_version.mdx
product_docs/docs/hadoop_data_adapter/2/11_uninstalling_the_hadoop_data_adapter.mdx
product_docs/docs/hadoop_data_adapter/2/index.mdx
product_docs/docs/mongo_data_adapter/5/04_installing_the_mongo_data_adapter/index.mdx
product_docs/docs/mongo_data_adapter/5/05_updating_the_mongo_data_adapter.mdx
product_docs/docs/mongo_data_adapter/5/06_features_of_mongo_fdw.mdx
product_docs/docs/mongo_data_adapter/5/07_configuring_the_mongo_data_adapter.mdx
product_docs/docs/mongo_data_adapter/5/08_example_using_the_mongo_data_adapter.mdx
product_docs/docs/mongo_data_adapter/5/09_identifying_data_adapter_version.mdx
product_docs/docs/mongo_data_adapter/5/11_uninstalling_the_mongo_data_adapter.mdx
product_docs/docs/mongo_data_adapter/5/index.mdx
product_docs/docs/mysql_data_adapter/2/04_installing_the_mysql_data_adapter/index.mdx
product_docs/docs/mysql_data_adapter/2/05_updating_the_mysql_data_adapter.mdx
product_docs/docs/mysql_data_adapter/2/06_features_of_mysql_fdw.mdx
product_docs/docs/mysql_data_adapter/2/07_configuring_the_mysql_data_adapter.mdx
product_docs/docs/mysql_data_adapter/2/08_example_using_the_mysql_data_adapter.mdx
product_docs/docs/mysql_data_adapter/2/09_example_import_foreign_schema.mdx
product_docs/docs/mysql_data_adapter/2/11_identifying_data_adapter_version.mdx
product_docs/docs/mysql_data_adapter/2/12_uninstalling_the_mysql_data_adapter.mdx
product_docs/docs/mysql_data_adapter/2/13_troubleshooting.mdx
product_docs/docs/mysql_data_adapter/2/index.mdx
product_docs/docs/pem/8/tuning_performance/index.mdx
product_docs/docs/pgd/4/deployments/tpaexec/index.mdx

- FDWs: restructure
- Fixed typos in PGD and PEM

Release: 2022-06-02

---

product_docs/docs/eprs/7/07_common_operations/11_using_ssl_connections.mdx

Updates to the  Configuring SSL for the publication server and subscription server section per XDB-1392

EPRS: updates for XDB-1392

---

product_docs/docs/eprs/7/07_common_operations/09_offline_snapshot.mdx
product_docs/docs/eprs/7/07_common_operations/11_using_ssl_connections.mdx

Made changes to instructions according to feedback from XDB-1097

eprs user guide: description fixes

---

product_docs/docs/efm/4/03_installing_efm/index.mdx
product_docs/docs/efm/4/03_installing_efm/x86_amd64/07_efm4_ubuntu18_20_x86.mdx
product_docs/docs/efm/4/03_installing_efm/x86_amd64/07a_efm4_deb10_x86.mdx
product_docs/docs/efm/4/03_installing_efm/x86_amd64/index.mdx

EFM: implemented latest Ubuntu/Debian install structure

---

product_docs/docs/biganimal/release/reference/api.mdx

Added a deprecation notice, updated the URLs, added a link to the change log.

BigAnimal: API versioning

---

product_docs/docs/biganimal/release/getting_started/creating_a_cluster/index.mdx
product_docs/docs/biganimal/release/reference/api.mdx

Updated Creating your cluster topic

BigAnimal: UPM-7790 EPAS name change

---

product_docs/docs/biganimal/release/administering_cluster/01_portal_access.mdx

- fix incorrect permission of "owner" role against billing in BigAnimal product
**Content**

remove billing:update permission from the BigAnimal protal_access doc

---

product_docs/docs/migration_toolkit/55/mtk_rel_notes/index.mdx
product_docs/docs/migration_toolkit/55/mtk_rel_notes/mtk_5523_rel_notes.mdx

https://docs.google.com/document/d/1cdEZrPhCuJ91xKGa39Fy8xP7nb6VicQwFqGnBURuyy0/edit#

Migration toolkit - release 55.2.3

---

product_docs/docs/migration_toolkit/55/06_building_toolkit.properties_file.mdx

https://enterprisedb.atlassian.net/browse/DF-299

Updating URL for Defining a SQL Server URL

---

product_docs/docs/biganimal/release/getting_started/creating_a_cluster/index.mdx
product_docs/docs/biganimal/release/getting_started/preparing_cloud_account/01_preparing_azure/index.mdx
product_docs/docs/biganimal/release/getting_started/preparing_cloud_account/02_preparing_aws.mdx
product_docs/docs/biganimal/release/overview/02_high_availability.mdx
product_docs/docs/biganimal/release/overview/03a_region_support.mdx
product_docs/docs/biganimal/release/overview/04_responsibility_model.mdx
product_docs/docs/biganimal/release/overview/05_database_version_policy.mdx
product_docs/docs/biganimal/release/overview/images/Extreme-HA-Diagram-2x.png
product_docs/docs/biganimal/release/overview/images/HA-diagram-2x.png
product_docs/docs/biganimal/release/overview/images/Single-Node-Diagram-2x.png
product_docs/docs/biganimal/release/overview/images/extreme-availability.png
product_docs/docs/biganimal/release/pricing_and_billing/index.mdx
product_docs/docs/biganimal/release/using_cluster/03_modifying_your_cluster/index.mdx
product_docs/docs/biganimal/release/using_cluster/05_monitoring_and_logging/metrics/index.mdx
product_docs/docs/biganimal/release/using_cluster/05_monitoring_and_logging/monitoring_from_aws/index.mdx
product_docs/docs/biganimal/release/using_cluster/05_monitoring_and_logging/monitoring_from_azure/index.mdx
product_docs/docs/epas/14/epas_rel_notes/epas14_3_0_rel_notes.mdx
product_docs/docs/epas/14/epas_rel_notes/epas14_4_0_rel_notes.mdx
product_docs/docs/epas/14/epas_rel_notes/index.mdx
product_docs/docs/migration_toolkit/55/06_building_toolkit.properties_file.mdx
product_docs/docs/migration_toolkit/55/mtk_rel_notes/index.mdx
product_docs/docs/migration_toolkit/55/mtk_rel_notes/mtk_5523_rel_notes.mdx

- BigAnimal EHA release
- EPAS 14.4 release
- Migration Toolkit:
-  55.2.3 release
- Updates to Defining a SQL Server URL section

Release: 2022-06-16

---

product_docs/docs/bdr/3.6/index.mdx
product_docs/docs/bdr/3.7/backup.mdx
product_docs/docs/bdr/3.7/camo.mdx
product_docs/docs/bdr/3.7/camo_clients.mdx
product_docs/docs/bdr/3.7/configuration.mdx
product_docs/docs/bdr/3.7/eager.mdx
product_docs/docs/bdr/3.7/index.mdx
product_docs/docs/bdr/3.7/isolation_details.mdx
product_docs/docs/bdr/3.7/monitoring.mdx
product_docs/docs/bdr/3.7/overview.mdx
product_docs/docs/bdr/4/camo.mdx
product_docs/docs/bdr/4/configuration.mdx
product_docs/docs/bdr/4/eager.mdx
product_docs/docs/bdr/4/functions.mdx
product_docs/docs/bdr/4/group-commit.mdx
product_docs/docs/bdr/4/release_notes/bdr4.1.1_rel_notes.mdx
product_docs/docs/bdr/4/release_notes/index.mdx
product_docs/docs/bdr/4/repsets.mdx
product_docs/docs/bdr/4/scaling.mdx
product_docs/docs/bdr/4/security.mdx
product_docs/docs/harp/2/01_release_notes/harp2.1.1_rel_notes.mdx
product_docs/docs/harp/2/01_release_notes/index.mdx
product_docs/docs/harp/2/03_installation.mdx
product_docs/docs/pgd/4/backup.mdx
product_docs/docs/pgd/4/monitoring.mdx
product_docs/docs/pgd/4/rel_notes/epd_4_1_1_rel_notes.mdx
product_docs/docs/pgd/4/rel_notes/epd_4_rel_notes.mdx
product_docs/docs/pgd/4/rel_notes/index.mdx

BDR 4.1.1 release
BDR copyedits

Release: 2022-06-21

---

product_docs/docs/eprs/7/08_xdb_cli/02_general_use.mdx

Updated the paths of two commands as per [XDB-1005](https://enterprisedb.atlassian.net/browse/XDB-1005).

EPRS: command path update

---

product_docs/docs/mysql_data_adapter/2/05_updating_the_mysql_data_adapter.mdx
product_docs/docs/mysql_data_adapter/2/07_configuring_the_mysql_data_adapter.mdx
product_docs/docs/mysql_data_adapter/2/08_example_using_the_mysql_data_adapter.mdx
product_docs/docs/mysql_data_adapter/2/09_example_import_foreign_schema.mdx
product_docs/docs/mysql_data_adapter/2/10_example_join_push_down.mdx
product_docs/docs/mysql_data_adapter/2/10a_example_aggregate_func_push_down.mdx
product_docs/docs/mysql_data_adapter/2/10b_example_order_by_push_down.mdx
product_docs/docs/mysql_data_adapter/2/10c_example_limit_offset_push_down.mdx
product_docs/docs/mysql_data_adapter/2/11_identifying_data_adapter_version.mdx

MySQL FDW code block type updates, excluding install topics

MySQL FDW: updating code blocks

---

product_docs/docs/mongo_data_adapter/5/06_features_of_mongo_fdw.mdx
product_docs/docs/mongo_data_adapter/5/07_configuring_the_mongo_data_adapter.mdx
product_docs/docs/mongo_data_adapter/5/08_example_using_the_mongo_data_adapter.mdx
product_docs/docs/mongo_data_adapter/5/08a_example_join_pushdown.mdx
product_docs/docs/mongo_data_adapter/5/08b_example_aggregate_pushdown.mdx
product_docs/docs/mongo_data_adapter/5/09_identifying_data_adapter_version.mdx

Updated Mongo FDW code block types, excluding install topics

Mongo FDW: updating code blocks

---

product_docs/docs/hadoop_data_adapter/2/08_configuring_the_hadoop_data_adapter.mdx
product_docs/docs/hadoop_data_adapter/2/09_using_the_hadoop_data_adapter.mdx
product_docs/docs/hadoop_data_adapter/2/10_identifying_data_adapter_version.mdx
product_docs/docs/hadoop_data_adapter/2/10a_example_join_pushdown.mdx
product_docs/docs/hadoop_data_adapter/2/10b_example_aggregate_pushdown.mdx

Hadoop FDW code block types updates, excluding install topics

Hadoop: code block updates

---

product_docs/docs/ocl_connector/14.1.0.1/04_open_client_library/04_ref_cursor_support.mdx
product_docs/docs/ocl_connector/14.1.0.1/04_open_client_library/05_ocl_function_reference.mdx
product_docs/docs/ocl_connector/14.1.0.1/04_open_client_library/07_multithreading_support.mdx
product_docs/docs/ocl_connector/14.1.0.1/04_open_client_library/08_otl_support.mdx
product_docs/docs/ocl_connector/14.1.0.1/06_using_ssl.mdx

Updated code blocks (mostly to C) and excluded install topics

OCL: code block updates

---

product_docs/docs/migration_portal/4.0/04_mp_migrating_database/01_mp_schema_extraction/01_data_pump_utility.mdx

https://enterprisedb.atlassian.net/browse/MIG-3790

Migration portal MIG-3790

---

install_template/templates/platformBase/debian-9.njk
install_template/templates/platformBase/ubuntu.njk
install_template/templates/products/postgis/ubuntu-18.04.njk
install_template/templates/products/postgis/ubuntu-20.04.njk
product_docs/docs/postgis/3.1/01a_installing_postgis/installing_on_linux/x86_amd64/07_postgis_ubuntu20_x86.mdx
product_docs/docs/postgis/3.1/01a_installing_postgis/installing_on_linux/x86_amd64/07a_postgis_ubuntu18_x86.mdx

Fixed the Ubuntu 18 and 20 install topics and respective install template files.

PostGis - Ubuntu fixes

---

install_template/templates/platformBase/debian-9.njk
product_docs/docs/efm/4/03_installing_efm/x86_amd64/07_efm4_ubuntu20_x86.mdx
product_docs/docs/efm/4/03_installing_efm/x86_amd64/07a_efm4_ubuntu18_x86.mdx
product_docs/docs/efm/4/03_installing_efm/x86_amd64/07b_efm4_deb10_x86.mdx
product_docs/docs/efm/4/03_installing_efm/x86_amd64/08_efm4_deb9_x86.mdx
product_docs/docs/epas/14/epas_inst_linux/installing_epas_using_edb_repository/x86_amd64/epas_deb10_x86.mdx
product_docs/docs/epas/14/epas_inst_linux/installing_epas_using_edb_repository/x86_amd64/epas_deb9_x86.mdx
product_docs/docs/epas/14/epas_inst_linux/installing_epas_using_edb_repository/x86_amd64/epas_ubuntu18_x86.mdx
product_docs/docs/epas/14/epas_inst_linux/installing_epas_using_edb_repository/x86_amd64/epas_ubuntu20_x86.mdx
product_docs/docs/hadoop_data_adapter/2/05_installing_the_hadoop_data_adapter/x86_amd64/07_hadoop_ubuntu20_x86.mdx
product_docs/docs/hadoop_data_adapter/2/05_installing_the_hadoop_data_adapter/x86_amd64/07a_hadoop_ubuntu18_x86.mdx
product_docs/docs/hadoop_data_adapter/2/05_installing_the_hadoop_data_adapter/x86_amd64/07b_hadoop_deb10_x86.mdx
product_docs/docs/hadoop_data_adapter/2/05_installing_the_hadoop_data_adapter/x86_amd64/08_hadoop_deb9_x86.mdx
product_docs/docs/mongo_data_adapter/5/04_installing_the_mongo_data_adapter/x86_amd64/07_mongo_ubuntu20_x86.mdx
product_docs/docs/mongo_data_adapter/5/04_installing_the_mongo_data_adapter/x86_amd64/07a_mongo_ubuntu18_x86.mdx
product_docs/docs/mongo_data_adapter/5/04_installing_the_mongo_data_adapter/x86_amd64/07b_mongo_deb10_x86.mdx
product_docs/docs/mongo_data_adapter/5/04_installing_the_mongo_data_adapter/x86_amd64/08_mongo_deb9_x86.mdx
product_docs/docs/pem/8/installing_pem_server/pem_server_inst_linux/installing_pem_server_using_edb_repository/x86_amd64/pem_server_deb10_x86.mdx
product_docs/docs/pem/8/installing_pem_server/pem_server_inst_linux/installing_pem_server_using_edb_repository/x86_amd64/pem_server_deb9_x86.mdx
product_docs/docs/pem/8/installing_pem_server/pem_server_inst_linux/installing_pem_server_using_edb_repository/x86_amd64/pem_server_ubuntu18_x86.mdx
product_docs/docs/pem/8/installing_pem_server/pem_server_inst_linux/installing_pem_server_using_edb_repository/x86_amd64/pem_server_ubuntu20_x86.mdx
product_docs/docs/postgis/3.1/01a_installing_postgis/installing_on_linux/x86_amd64/07_postgis_ubuntu20_x86.mdx
product_docs/docs/postgis/3.1/01a_installing_postgis/installing_on_linux/x86_amd64/07a_postgis_ubuntu18_x86.mdx
product_docs/docs/postgis/3.1/01a_installing_postgis/installing_on_linux/x86_amd64/07b_postgis_deb10_x86.mdx
product_docs/docs/postgis/3.1/01a_installing_postgis/installing_on_linux/x86_amd64/08_postgis_deb9_x86.mdx

These commits were intended for https://github.com/EnterpriseDB/docs/pull/2857

Generated install topics for unbuntu debian mongo hadoop

---

install_template/templates/products/edb-postgres-advanced-server/base.njk
product_docs/docs/epas/14/epas_inst_linux/installing_epas_using_edb_repository/ibm_power_ppc64le/epas_sles12_ppcle.mdx
product_docs/docs/epas/14/epas_inst_linux/installing_epas_using_edb_repository/ibm_power_ppc64le/epas_sles15_ppcle.mdx
product_docs/docs/epas/14/epas_inst_linux/installing_epas_using_edb_repository/x86_amd64/epas_deb10_x86.mdx
product_docs/docs/epas/14/epas_inst_linux/installing_epas_using_edb_repository/x86_amd64/epas_deb9_x86.mdx
product_docs/docs/epas/14/epas_inst_linux/installing_epas_using_edb_repository/x86_amd64/epas_sles12_x86.mdx
product_docs/docs/epas/14/epas_inst_linux/installing_epas_using_edb_repository/x86_amd64/epas_sles15_x86.mdx
product_docs/docs/epas/14/epas_inst_linux/installing_epas_using_edb_repository/x86_amd64/epas_ubuntu18_x86.mdx
product_docs/docs/epas/14/epas_inst_linux/installing_epas_using_edb_repository/x86_amd64/epas_ubuntu20_x86.mdx

Fixed typo in Install the package section

EPAS: fixed typo in install template

---

scripts/fileProcessor/processors/cnp/add-frontmatters.mjs
scripts/fileProcessor/processors/cnp/update-yaml-links.mjs
scripts/source/dispatch_product.py
scripts/source/files-to-ignore.mjs
scripts/source/process-cnp-docs.sh

Convert old CNP source script to work with Postgres for Kubernetes

Convert to work with Postgres for Kubernetes repo

---

product_docs/docs/biganimal/release/getting_started/creating_a_cluster/index.mdx
product_docs/docs/biganimal/release/overview/02_high_availability.mdx
product_docs/docs/biganimal/release/using_cluster/03_modifying_your_cluster/index.mdx

BigAnimal updates:
- Tunable IOPS
- Azure Ultra Disks
- 2 node replicas

Release: 2022-07-01

---

product_docs/docs/biganimal/release/using_cluster/03_modifying_your_cluster/05_db_configuration_parameters.mdx

Added a section entitled "Using equations for parameter values" in the "Modifying database configuration parameters" topic

BigAnimal: updates for UPM-4607 - support for GUC equations

---

product_docs/docs/biganimal/release/getting_started/creating_a_cluster/index.mdx
product_docs/docs/biganimal/release/using_cluster/03_modifying_your_cluster/index.mdx
product_docs/docs/biganimal/release/using_cluster/04_backup_and_restore.mdx

Added information about new backup retention options

BigAnimal: backup retention period

---

product_docs/docs/bdr/4/overview.mdx

Added more detail around what consensus is

BDR overview: added more information about consensus

---

product_docs/docs/edb_plus/40/04_using_edb_plus.mdx
product_docs/docs/edb_plus/40/05_using_edb_plus_with_ssl.mdx
product_docs/docs/edb_plus/40/06_command_summary.mdx

Updated EDB*Plus code blocks, excluding install topics

EDB*Plus: updating code blocks

---

product_docs/docs/pgpool/4.3/02_extensions/creating_pgpool_extensions.mdx
product_docs/docs/pgpool/4.3/02_extensions/ibm_power_ppc64le/10_pgpoolext_rhel7_ppcle.mdx
product_docs/docs/pgpool/4.3/02_extensions/x86_amd64/01_pgpoolext_rhel8_x86.mdx
product_docs/docs/pgpool/4.3/02_extensions/x86_amd64/02_pgpoolext_other_linux8_x86.mdx
product_docs/docs/pgpool/4.3/02_extensions/x86_amd64/03_pgpoolext_rhel7_x86.mdx
product_docs/docs/pgpool/4.3/02_extensions/x86_amd64/04_pgpoolext_centos7_x86.mdx
product_docs/docs/pgpool/4.3/02_extensions/x86_amd64/07_pgpoolext_ubuntu20_x86.mdx
product_docs/docs/pgpool/4.3/02_extensions/x86_amd64/07a_pgpoolext_ubuntu18_x86.mdx
product_docs/docs/pgpool/4.3/02_extensions/x86_amd64/08_pgpoolext_deb10_x86.mdx
product_docs/docs/pgpool/4.3/02_extensions/x86_amd64/08a_pgpoolext_deb9_x86.mdx
product_docs/docs/pgpool/4.3/03_configuring_connection_pooling.mdx
product_docs/docs/pgpool/4.3/04_connecting_a_client_to_pgpool-II.mdx
product_docs/docs/pgpool/4.3/05_upgrade.mdx
product_docs/docs/pgpool/4.3/06_uninstalling_pgpool-II.mdx

Updated PgPool and extensions code blocks, excluded install PgPool install topics

PgPool: updating code blocks

---

product_docs/docs/postgis/3.1/02_creating_extensions.mdx
product_docs/docs/postgis/3.1/03_upgrading_postgis.mdx
product_docs/docs/postgis/3.1/04_using_postgis.mdx
product_docs/docs/postgis/3.1/05_uninstalling_postgis.mdx

Updated code blocks for PostGIS

PostGIS: code block changes

---

product_docs/docs/biganimal/release/pricing_and_billing/index.mdx

Added am Apache Superset costs section to the Pricing and billing topic.

BigAnimal: Superset costs

---

product_docs/docs/migration_portal/4.0/04_mp_migrating_database/03_mp_schema_migration.mdx

Fixed list alignment issues and note formatting

MP: formatting issues

---

product_docs/docs/biganimal/release/overview/02_high_availability.mdx

Reverted change added in #2962

BigAnimal: reverting change to number of standbys for HA

---

src/pages/index.js

Removed abbreviation
Removed categories
Moved EPRS to Migration

Home page changes to HA section

---

product_docs/docs/eprs/7/01_introduction/04_supported_jdk_versions.mdx
product_docs/docs/eprs/7/eprs_rel_notes/16_eprs_rel_notes_7.2.1.mdx
product_docs/docs/eprs/7/eprs_rel_notes/index.mdx

- Added new release notes topic
- Added release notes content
- Updated index file
- Updated supported platforms

EPRS: 7.2.1 release notes

---

advocacy_docs/supported-open-source/pgbackrest/09-tls_server.mdx
advocacy_docs/supported-open-source/pgbackrest/index.mdx

- Fixed pgBackRest service file (for the TLS feature)
- pgBackRest 2.40 has been released

pgBackRest 2.40 released

---

product_docs/docs/biganimal/release/free_trial/quickstart.mdx

BigAnimal: fixed broken link on Quick Start topic

---

product_docs/docs/eprs/7/eprs_rel_notes/index.mdx

Added upgrade requirements to release notes landing page

EPRS: adding upgrade path info

---

product_docs/docs/eprs/7/eprs_rel_notes/index.mdx

Updated the note on the release notes landing page:

EPRS: xdb-1584 - upgrade note

---

product_docs/docs/pgd/4/architectures/index.mdx

Fixed issue on Choosing your architecture topic

EPD: fixed note formatting issue

---

product_docs/docs/biganimal/release/getting_started/02_azure_market_setup.mdx
product_docs/docs/biganimal/release/getting_started/creating_a_cluster/index.mdx
product_docs/docs/biganimal/release/getting_started/identity_provider/index.mdx

Updated link labels where appropriate and updated links.

BigAnimal: fixing Connecting to your cloud links

---

product_docs/docs/pgd/4/overview/bdr/index.mdx

This dates back to the single-page stub for BDR 3 I believe. It serves no purpose now that BDR sits below pgd.
**Content**

Remove cascading description for BDR

---

product_docs/docs/postgis/3.2/01a_installing_postgis/installing_on_linux/x86_amd64/postgis_centos7_x86.mdx
product_docs/docs/postgis/3.2/01a_installing_postgis/installing_on_linux/x86_amd64/postgis_deb10_x86.mdx
product_docs/docs/postgis/3.2/01a_installing_postgis/installing_on_linux/x86_amd64/postgis_other_linux8_x86.mdx
product_docs/docs/postgis/3.2/01a_installing_postgis/installing_on_linux/x86_amd64/postgis_rhel7_x86.mdx
product_docs/docs/postgis/3.2/01a_installing_postgis/installing_on_linux/x86_amd64/postgis_ubuntu18_x86.mdx

PostGIS: included deployed topics with EPAS fixes

---

product_docs/docs/epas/10/epas_compat_table_partitioning/04_partitioning_commands_compatible_with_oracle_databases/01_create_table_partition_by/index.mdx
product_docs/docs/epas/11/epas_compat_table_partitioning/04_partitioning_commands_compatible_with_oracle_databases/01_create_table_partition_by/index.mdx
product_docs/docs/epas/12/epas_compat_table_partitioning/04_partitioning_commands_compatible_with_oracle_databases/01_create_table_partition_by/index.mdx
product_docs/docs/epas/13/epas_compat_table_partitioning/04_partitioning_commands_compatible_with_oracle_databases/01_create_table_partition_by/index.mdx
product_docs/docs/epas/14/epas_compat_table_partitioning/04_partitioning_commands_compatible_with_oracle_databases/01_create_table_partition_by/index.mdx

Added content to v10-14 according to [DB-1743](https://enterprisedb.atlassian.net/browse/DB-1743).

EPAS: adding ENABLE ROW MOVEMENT content to v10-14 as per DB-1743

---

product_docs/docs/biganimal/release/getting_started/creating_a_cluster/index.mdx
product_docs/docs/biganimal/release/using_cluster/03_modifying_your_cluster/index.mdx

https://enterprisedb.atlassian.net/browse/UPM-8272

io2 and io2 Block Express

---

product_docs/docs/biganimal/release/getting_started/creating_a_cluster/index.mdx
product_docs/docs/biganimal/release/overview/04_responsibility_model.mdx
product_docs/docs/biganimal/release/using_cluster/03_modifying_your_cluster/index.mdx
product_docs/docs/epas/10/epas_compat_table_partitioning/04_partitioning_commands_compatible_with_oracle_databases/01_create_table_partition_by/index.mdx
product_docs/docs/epas/11/epas_compat_table_partitioning/04_partitioning_commands_compatible_with_oracle_databases/01_create_table_partition_by/index.mdx
product_docs/docs/epas/12/epas_compat_table_partitioning/04_partitioning_commands_compatible_with_oracle_databases/01_create_table_partition_by/index.mdx
product_docs/docs/epas/13/epas_compat_table_partitioning/04_partitioning_commands_compatible_with_oracle_databases/01_create_table_partition_by/index.mdx
product_docs/docs/epas/14/epas_compat_table_partitioning/04_partitioning_commands_compatible_with_oracle_databases/01_create_table_partition_by/index.mdx
src/pages/index.js

- BigAnimal: 
- io2 support
- update to Shared responsibilities topic HA section 
- EPAS: ENABLE ROW MOVEMENT content - DB-1743
- Infrastructure: changes to home page layout

Release: 2022-08-11

---

product_docs/docs/migration_toolkit/55/06_building_toolkit.properties_file.mdx

https://enterprisedb.atlassian.net/browse/MIG-3921

MTK: MIG-3921

---

product_docs/docs/biganimal/release/getting_started/preparing_cloud_account/01_preparing_azure/index.mdx

- Fixed Azure register command link error in Preparing your Azure account
**Content**

Update Azure register command link

---

product_docs/docs/postgres_for_kubernetes/1/rel_notes/1_15_3_rel_notes.mdx
product_docs/docs/postgres_for_kubernetes/1/rel_notes/1_16_1_rel_notes.mdx
product_docs/docs/postgres_for_kubernetes/1/rel_notes/index.mdx

EDB PG for Kubernetes: v1.15.3 and v1.16.1 rel notes

---

product_docs/docs/biganimal/release/getting_started/preparing_cloud_account/01_preparing_azure/index.mdx
product_docs/docs/migration_toolkit/55/06_building_toolkit.properties_file.mdx
product_docs/docs/postgres_for_kubernetes/1/postgis.mdx
product_docs/docs/postgres_for_kubernetes/1/postgresql_conf.mdx
product_docs/docs/postgres_for_kubernetes/1/rel_notes/1_15_3_rel_notes.mdx
product_docs/docs/postgres_for_kubernetes/1/rel_notes/1_16_1_rel_notes.mdx
product_docs/docs/postgres_for_kubernetes/1/rel_notes/index.mdx
product_docs/docs/postgres_for_kubernetes/1/samples/postgis-example.yaml
product_docs/docs/postgres_for_kubernetes/1/ssl_connections.mdx

- EDB Postgres for Kubernetes v1.15.3 and v1.16.1 releases
- Migration Toolkit: MIG-3921 - Clarifying note in Defining a MySQL URL
- BigAnimal: Update Azure register command link

Release: 2022-08-15

---

product_docs/docs/livecompare/2.3/advanced_usage.mdx
product_docs/docs/livecompare/2.3/bdr_support.mdx
product_docs/docs/livecompare/2.3/command_line_usage.mdx
product_docs/docs/livecompare/2.3/index.mdx
product_docs/docs/livecompare/2.3/licenses.mdx
product_docs/docs/livecompare/2.3/oracle_support.mdx
product_docs/docs/livecompare/2.3/release_notes.mdx
product_docs/docs/livecompare/2.3/requirements.mdx
product_docs/docs/livecompare/2.3/settings.mdx
product_docs/docs/livecompare/2.3/supported_technologies.mdx

- Add LiveCompare 2.3
**Content**

LiveCompare 2.3

---

product_docs/docs/livecompare/2.3/release_notes.mdx

Fixed the 2.3 release date in the release notes

LiveCompare: date updated

---

install_template/templates/products/postgis/debian-10.njk
install_template/templates/products/postgis/sles-12.njk
install_template/templates/products/postgis/sles-12_ppc64le.njk
product_docs/docs/postgis/3.2/01a_installing_postgis/installing_on_linux/ibm_power_ppc64le/postgis_sles12_ppcle.mdx
product_docs/docs/postgis/3.2/01a_installing_postgis/installing_on_linux/x86_amd64/postgis_deb10_x86.mdx
product_docs/docs/postgis/3.2/01a_installing_postgis/installing_on_linux/x86_amd64/postgis_sles12_x86.mdx

- Added v11 for 3.1 for SLES 12 x86 
- Removed 11 for 3.2 for Debian 10

PostGIS: DI-942 - install command fixes

---

product_docs/docs/bdr/4/repsets.mdx
product_docs/docs/pgd/4/overview/bdr/repsets.mdx

Documented missing parameters for `bdr.replication_set_add_ddl_filter` function in BDR
**Content**

Document the new 4.1 options in bdr.replication_set_add_ddl_filter

---

product_docs/docs/pgd/3.7/bdr/release-notes.mdx
product_docs/docs/pgd/3.7/pglogical/release-notes.mdx

release notes for 3.7.17 release.
**Content**

Release notes for 3.7.17

---

product_docs/docs/migration_portal/4/04_mp_migrating_database/01_mp_schema_extraction/index.mdx
product_docs/docs/pgd/4/overview/harp/02_overview.mdx

-fixed typos in PGD and Migration Portal according to [DF-305](https://enterprisedb.atlassian.net/browse/DF-305)

typo fixes as per DF-305

---

product_docs/docs/pem/8/pem_upgrade/upgrading_backend_database.mdx

Clarification on upgrade support in regards to the backend PEM server
Moved changes from https://github.com/EnterpriseDB/docs/pull/2983 as the updates were not release specific.

PEM: PEM-4498

---

product_docs/docs/biganimal/release/free_trial/detail/create_an_account/index.mdx
product_docs/docs/biganimal/release/getting_started/preparing_cloud_account/01_preparing_azure/01_understanding_qotas_in_azure.mdx
product_docs/docs/migration_portal/4/04_mp_migrating_database/01_mp_schema_extraction/index.mdx
product_docs/docs/pem/8/pem_upgrade/upgrading_backend_database.mdx
product_docs/docs/pgd/4/overview/bdr/catalogs.mdx
product_docs/docs/pgd/4/overview/harp/02_overview.mdx

- BigAnimal: 
- Changed quota recommendations for Azure (https://github.com/EnterpriseDB/docs/pull/3070)
- Clarified free trial info
- Fixed typos in PGD and Migration Portal according to [DF-305](https://enterprisedb.atlassian.net/browse/DF-305)
- PEM: clarified upgrade info
- BDR: updated catalog info

Release: 2022-08-25

---

product_docs/docs/pgd/3.7/harp/01_release_notes/harp2.2.0_rel_notes.mdx
product_docs/docs/pgd/3.7/harp/01_release_notes/index.mdx

Added HARP 2.2 rel notes for PGD 3.7

PGD 3.7: Harp 2.2 rel notes

---

product_docs/docs/biganimal/release/using_cluster/05a_deleting_your_cluster.mdx
product_docs/docs/pgd/3.7/harp/01_release_notes/harp2.2.0_rel_notes.mdx
product_docs/docs/pgd/3.7/harp/01_release_notes/index.mdx

- Added HARP 2.2 rel notes for PGD 3.7 doc
- BigAnimal: clarified deleting clusters info

Release: 2022-08-26

---

product_docs/docs/pgd/4/overview/bdr/catalogs.mdx

Added details to the description of the `bdr.queue.message_type` column.
**Content**

Add description of bdr.queue.message_type values

---

product_docs/docs/pgd/4/overview/bdr/catalogs.mdx

Build is breaking due to br command syntax, I believe. Testing with a test deploy.

BDR: fix br command syntax

---

product_docs/docs/pgd/4/architectures/bronze.mdx
product_docs/docs/pgd/4/architectures/gold.mdx
product_docs/docs/pgd/4/architectures/platinum.mdx
product_docs/docs/pgd/4/architectures/silver.mdx
product_docs/docs/pgd/4/rel_notes/index.mdx

- Updated TPAexec version in rel notes 
- Removed parenthetical phrases from arch topic titles 
- Removed first two images in Gold topic - the first wasn't a recommended arch and the second was for BA

PGD 4.2: misc clean up

---

product_docs/docs/efm/4/04_configuring_efm/01_cluster_properties.mdx
product_docs/docs/efm/4/05_using_efm.mdx

Changes for the 4.5 release. This does not include changes to the release notes, which will happen separately.
Am marking this as a draft for now just to make sure it's not published before we release 4.5, but will look for comments ahead of that.
**Content**
The PR is for a release, but I don't know what tag applies here.

Documentation updates for efm v4.5

---

product_docs/docs/efm/4/efm_rel_notes/05_efm_45_rel_notes.mdx
product_docs/docs/efm/4/efm_rel_notes/index.mdx

Release notes for EFM 4.5.
Jira ticket https://enterprisedb.atlassian.net/browse/EFM-1526
We should release by the 31st at the latest.
**Content**

Release notes for v4.5.

---

product_docs/docs/biganimal/release/overview/03_security/compliance_and_certifications.mdx
product_docs/docs/biganimal/release/overview/03_security/index.mdx

- Added Security compliance and certifications topic
- Added paragraph in parent topic with link

BigAnimal: Security compliance and certifications topic

---

product_docs/docs/pgd/4/index.mdx

Simplify overview page and move image down.
**Content**

PGD: main landing page simplification

---

product_docs/docs/efm/4/efm_rel_notes/index.mdx

Change release date for 4.5 to be 8/30 instead of 8/31

Update EFM 4.5 release date

---

product_docs/docs/biganimal/release/getting_started/creating_a_cluster/index.mdx

https://enterprisedb.atlassian.net/browse/UPM-10378

BigAnimal: maximizing disk size

---

static/_redirects

Added redirect after bumping the version number for the 42.5.0.1 release

JDBC: added redirect after changing version

---

product_docs/docs/postgres_for_kubernetes/1/interactive_demo.mdx

Minor changes to keep demo output in sync with current version
**Content**

Update p4k demo output for 1.17.0

---

product_docs/docs/pgd/4/bdr/index.mdx
product_docs/docs/pgd/4/harp/index.mdx
static/_redirects

moved redirects to _redirects file

PGD: fixed bdr and harp redirects

---

product_docs/docs/biganimal/release/getting_started/02_azure_market_setup.mdx
product_docs/docs/biganimal/release/getting_started/02_connecting_to_your_cloud/index.mdx

- Remove global administrator and Privileged Admin consent requirement 
for Azure Marketplace user onboarding guide
**Content**

BigAnimal: remove global administrator and Privileged Admin consent requirement

---

product_docs/docs/biganimal/release/getting_started/02_azure_market_setup.mdx
product_docs/docs/biganimal/release/getting_started/02_connecting_to_your_cloud/index.mdx
product_docs/docs/ocl_connector/14.1.0.1/02_supported_platforms.mdx
product_docs/docs/pem/8/changing_default_port.mdx
product_docs/docs/pem/8/index.mdx
product_docs/docs/pem/8/installing_pem_server/pem_server_inst_linux/configuring_the_pem_server_on_linux.mdx
product_docs/docs/pem/8/installing_pem_server/pem_server_inst_windows/pem_server_and_httpd_on_same_host.mdx
product_docs/docs/pem/8/tuning_performance/performance_diagnostic.mdx

- BigAnimal: removed global administrator and Privileged Admin for Azure marketplace instructions
- PEM: Changing port for Linux installations
- OCL connector: updated supported platforms topic to point to web site

Release: 2022-09-07

---

product_docs/docs/pem/8/installing_pem_server/pem_server_inst_linux/installing_pem_server_using_edb_repository/x86_amd64/pem_server_other_linux8_x86.mdx
product_docs/docs/pgd/4/index.mdx

PGD: updates to product compatibility section
PEM: broken link in generated install topics identifed - fix needs to be made in the template files and will be in the next build

Release: 2022-09-09a

---

product_docs/docs/pgd/3.7/pglogical/subscriptions/index.mdx

Fixed duplicate content issue in pglogical 3.7 doc

Release: 2022-09-12a

---

product_docs/docs/pgd/4/bdr/appusage.mdx

One last broken link for PGD 
**Content**

Fix link to release notes from appusage.mdx

---

product_docs/docs/pgd/4/bdr/functions.mdx
product_docs/docs/pgd/4/bdr/index.mdx
product_docs/docs/pgd/4/bdr/transaction-streaming.mdx
product_docs/docs/pgd/4/cli/installing_cli.mdx

A few more URLs that didn't get updated during reorg.
**Content**

PGD relative url fixes for monitoring, CLI

---

product_docs/docs/biganimal/release/using_cluster/05_monitoring_and_logging/metrics/index.mdx

Added new BDR metrics to existing metrics documentation located here:
/docs/product_docs/docs/biganimal/release/using_cluster/05_monitoring_and_logging/metrics/index.mdx
This was generated with the script written by @ringerc which I've also now commited to our scripts repo here:
https://github.com/EnterpriseDB/starlight-scripts/blob/main/docs/metrics_to_markdown_txt.py
**Content**

chore(UPM-10477): Adding new BDR metrics to documentation

---

static/_redirects

Updated _redirect to reflect removal of the Overview topic

PGD: updated harp redirect

---

product_docs/docs/pgd/4/bdr/durability.mdx

PGD: soften language against using legacy options

---

product_docs/docs/biganimal/release/using_cluster/01_postgres_access.mdx
product_docs/docs/biganimal/release/using_cluster/05_monitoring_and_logging/metrics/index.mdx
product_docs/docs/pgd/4/bdr/durability.mdx
product_docs/docs/pgd/4/bdr/functions.mdx
product_docs/docs/pgd/4/bdr/index.mdx
product_docs/docs/pgd/4/bdr/transaction-streaming.mdx
product_docs/docs/pgd/4/cli/installing_cli.mdx
product_docs/docs/pgd/4/overview/index.mdx
static/_redirects

- PGD: 
- Softened language around using legacy options instead of Group Commit
- Fixed redirects for HARP and BDR
- BigAnimal:
- Updated metrics details
- Fixed typos on Managing Postgres access topic

Release: 2022-09-18

---

product_docs/docs/pgd/4/deployments/index.mdx

PGD: Moved BA out of Coming soon section

---

product_docs/docs/biganimal/release/using_cluster/01_postgres_access.mdx

BigAnimal: another typo on Managing Postgres access topic

---

product_docs/docs/biganimal/release/getting_started/02_connecting_to_your_cloud/index.mdx
product_docs/docs/biganimal/release/getting_started/index.mdx
product_docs/docs/biganimal/release/reference/cli.mdx

As per [UPM-9904](https://enterprisedb.atlassian.net/browse/UPM-9904)
- updated Connecting to your cloud topic with permissions info

BigAnimal: reducing privileges 

---

product_docs/docs/biganimal/release/getting_started/02_azure_market_setup.mdx
product_docs/docs/biganimal/release/getting_started/02_connecting_to_your_cloud/index.mdx

- Removed note about deprecated manual onboarding process in the Azure Marketplace topic
- Removed errant mention of AWS Cloud Shell in Azure bullet in the Connecting your cloud topic

BigAnimal: Azure onboarding clarifications

---

product_docs/docs/pem/8/managing_bart.mdx

Fix typo in managing_bart.mdx

---

product_docs/docs/pgd/3.7/bdr/index.mdx
product_docs/docs/pgd/3.7/bdr/monitoring.mdx
product_docs/docs/pgd/3.7/bdr/nodes.mdx
product_docs/docs/pgd/3.7/index.mdx
product_docs/docs/pgd/4/index.mdx

add compatibility matrix and reorder content to align to table
modified intro paragraph to match better with v4
**Content**
- [x ] This PR adds new content

Update PGD 3.7 overview

---

product_docs/docs/pgd/4/bdr/repsets.mdx

Remove unnecessary COALESCE on repset membership

---

product_docs/docs/biganimal/release/getting_started/02_azure_market_setup.mdx

Updated the Azure Marketplace topic with important info about user type that had gotten dropped along the way.

BigAnimal: adding back in the member user type info for Azure

---

product_docs/docs/biganimal/release/getting_started/02_connecting_to_your_cloud/index.mdx

Added permissions back for connecting from Azure

BigAnimal: adding permissions back in for Azure

---

product_docs/docs/jdbc_connector/42.5.0.1/index.mdx

Addresses issue: https://github.com/EnterpriseDB/docs/issues/3172

JDBC - broken link fix as per DF-312

---

product_docs/docs/migration_portal/4/04_mp_migrating_database/02_mp_schema_assessment.mdx

https://github.com/EnterpriseDB/docs/issues/3164

Assessment report page improvements

---

product_docs/docs/migration_portal/4/04_mp_migrating_database/02_mp_schema_assessment.mdx

Changed note format in the Feature compatibility section to a regular note as opposed to a footnote

MP: change note format

---

install_template/templates/products/migration-toolkit/base.njk
product_docs/docs/migration_toolkit/55/05_installing_mtk/index.mdx
product_docs/docs/migration_toolkit/55/05_installing_mtk/install_on_linux/ibm_power_ppc64le/mtk55_rhel8_ppcle.mdx
product_docs/docs/migration_toolkit/55/05_installing_mtk/install_on_linux/ibm_power_ppc64le/mtk55_sles12_ppcle.mdx
product_docs/docs/migration_toolkit/55/05_installing_mtk/install_on_linux/ibm_power_ppc64le/mtk55_sles15_ppcle.mdx
product_docs/docs/migration_toolkit/55/05_installing_mtk/install_on_linux/index.mdx
product_docs/docs/migration_toolkit/55/05_installing_mtk/install_on_linux/x86_amd64/mtk55_centos7_x86.mdx
product_docs/docs/migration_toolkit/55/05_installing_mtk/install_on_linux/x86_amd64/mtk55_deb10_x86.mdx
product_docs/docs/migration_toolkit/55/05_installing_mtk/install_on_linux/x86_amd64/mtk55_other_linux8_x86.mdx
product_docs/docs/migration_toolkit/55/05_installing_mtk/install_on_linux/x86_amd64/mtk55_rhel7_x86.mdx
product_docs/docs/migration_toolkit/55/05_installing_mtk/install_on_linux/x86_amd64/mtk55_rhel8_x86.mdx
product_docs/docs/migration_toolkit/55/05_installing_mtk/install_on_linux/x86_amd64/mtk55_sles12_x86.mdx
product_docs/docs/migration_toolkit/55/05_installing_mtk/install_on_linux/x86_amd64/mtk55_sles15_x86.mdx
product_docs/docs/migration_toolkit/55/05_installing_mtk/install_on_linux/x86_amd64/mtk55_ubuntu18_x86.mdx
product_docs/docs/migration_toolkit/55/05_installing_mtk/install_on_linux/x86_amd64/mtk55_ubuntu20_x86.mdx
product_docs/docs/migration_toolkit/55/05_installing_mtk/install_on_mac.mdx
product_docs/docs/migration_toolkit/55/05_installing_mtk/install_on_windows.mdx
product_docs/docs/migration_toolkit/55/05_installing_mtk/installing_jdbc_driver.mdx

Adding instructions for installing EDB's JDBC driver for MTK vs assuming it's installed by default.
**Content**
- [x ] This PR adds new content

MTK: updates for installing JDBC driver 

---

product_docs/docs/pgd/4/bdr/index.mdx

According to our customer's request, added content to "Characteristics affecting BDR performance" that conflicts of other nodes does not occur due to long-running SELECT query. 
These requests can be viewed by referring to our support ticket number #85708.
- Added content to "Characteristics affecting BDR performance" regarding immune to replication conflicts on other nodes caused by long-running SELECT queries.
**Content**

Add content to bdr/index.mdx page by customer request.

---

product_docs/docs/epas/14/epas_guide/13_performance_analysis_and_tuning.mdx

Updated EPAS content as per [DF-311](https://enterprisedb.atlassian.net/browse/DF-311)

EPAS: Module name update

---

product_docs/docs/migration_toolkit/55/mtk_rel_notes/index.mdx

MTK: fix 55.3 release date

---

product_docs/docs/biganimal/release/using_cluster/02_connecting_your_cluster/index.mdx

Added a new section about connecting your cluster to EDB's migration tools

BigAnimal: adding a link to migration products in Connecting topic

---

product_docs/docs/biganimal/release/using_cluster/02_connecting_your_cluster/index.mdx
product_docs/docs/pgd/3.7/bdr/upgrades/index.mdx
product_docs/docs/pgd/3.7/bdr/upgrades/supported_paths.mdx
product_docs/docs/pgd/4/other_considerations.mdx
product_docs/docs/pgd/4/upgrades/upgrade_paths.mdx

PGD: 
- more adjustments to Considerations topic
- Added Upgrade paths topic for 3.7 
BigAnimal: Added link to Migration topic

Release: 2022-10-06c

---

product_docs/docs/pgd/4/deployments/tpaexec/installing_tpaexec.mdx

Updated Installing TPAexec topic with deb repo details

PGD: added url for deb repo

---

product_docs/docs/biganimal/release/getting_started/index.mdx

Last PR didn't have correct file name

BigAnimal: Fixed nav order - with latest commit

---

product_docs/docs/biganimal/release/getting_started/index.mdx
product_docs/docs/biganimal/release/using_cluster/06_analyze_with_superset.mdx
product_docs/docs/pgd/4/deployments/tpaexec/installing_tpaexec.mdx

- BigAnimal:
- Fixed nav order in Getting started
- Removed note about SSO in Superset topic
- PGD: included Debian/Ubuntu repo instructions

Release: 2022-10-07

---

product_docs/docs/postgres_for_kubernetes/1/rel_notes/1_15_5_rel_notes.mdx
product_docs/docs/postgres_for_kubernetes/1/rel_notes/1_16_3_rel_notes.mdx
product_docs/docs/postgres_for_kubernetes/1/rel_notes/1_17_1_rel_notes.mdx
product_docs/docs/postgres_for_kubernetes/1/rel_notes/index.mdx

Added release notes for 17.1, 16.3, and 15.5

Kubernetes: patch releases

---

advocacy_docs/migrating/oracle/index.mdx
src/constants/products.js
src/pages/index.js

Migration: Changing Migration Overview to Migration Handbook

---

product_docs/docs/biganimal/release/overview/03a_region_support.mdx

Added Germany to both sets of cluster types

BigAnimal: Germany region

---

product_docs/docs/eprs/6.2/07_common_operations/08_replicating_ddl_changes/01_ddl_change_replication.mdx
product_docs/docs/eprs/7/07_common_operations/08_replicating_ddl_changes/01_ddl_change_replication.mdx

Added note as per most recent comments on [XDB-1595](https://enterprisedb.atlassian.net/browse/XDB-1595)

EPRS: DDL change replication process note

---

product_docs/docs/migration_toolkit/55/06_building_toolkit.properties_file.mdx

https://github.com/EnterpriseDB/docs/issues/3078

Added location for toolkit file in Mac OS

---

product_docs/docs/epas/14/language_pack/02_installing_language_pack.mdx

Pretty sure this was a typo @ccestes - double-check?

fix incorrect path for language pack

---

install_template/templates/products/replication-server/base.njk
product_docs/docs/eprs/7/03_installation/03_installing_rpm_package/ibm_power_ppc64le/eprs_rhel8_ppcle.mdx
product_docs/docs/eprs/7/03_installation/03_installing_rpm_package/ibm_power_ppc64le/eprs_sles12_ppcle.mdx
product_docs/docs/eprs/7/03_installation/03_installing_rpm_package/ibm_power_ppc64le/eprs_sles15_ppcle.mdx
product_docs/docs/eprs/7/03_installation/03_installing_rpm_package/x86_amd64/eprs_centos7_x86.mdx
product_docs/docs/eprs/7/03_installation/03_installing_rpm_package/x86_amd64/eprs_deb10_x86.mdx
product_docs/docs/eprs/7/03_installation/03_installing_rpm_package/x86_amd64/eprs_deb11_x86.mdx
product_docs/docs/eprs/7/03_installation/03_installing_rpm_package/x86_amd64/eprs_other_linux8_x86.mdx
product_docs/docs/eprs/7/03_installation/03_installing_rpm_package/x86_amd64/eprs_rhel7_x86.mdx
product_docs/docs/eprs/7/03_installation/03_installing_rpm_package/x86_amd64/eprs_rhel8_x86.mdx
product_docs/docs/eprs/7/03_installation/03_installing_rpm_package/x86_amd64/eprs_sles12_x86.mdx
product_docs/docs/eprs/7/03_installation/03_installing_rpm_package/x86_amd64/eprs_sles15_x86.mdx
product_docs/docs/eprs/7/03_installation/03_installing_rpm_package/x86_amd64/eprs_ubuntu18_x86.mdx
product_docs/docs/eprs/7/03_installation/03_installing_rpm_package/x86_amd64/eprs_ubuntu20_x86.mdx

Addresses https://enterprisedb.atlassian.net/browse/XDB-1652

EPRS: Java note

---

advocacy_docs/supported-open-source/barman/index.mdx
advocacy_docs/supported-open-source/barman/pg-backup-api/01-installation.mdx
install_template/templates/products/replication-server/base.njk
product_docs/docs/biganimal/release/using_cluster/06_analyze_with_superset.mdx
product_docs/docs/eprs/7/03_installation/03_installing_rpm_package/ibm_power_ppc64le/eprs_rhel8_ppcle.mdx
product_docs/docs/eprs/7/03_installation/03_installing_rpm_package/ibm_power_ppc64le/eprs_sles12_ppcle.mdx
product_docs/docs/eprs/7/03_installation/03_installing_rpm_package/ibm_power_ppc64le/eprs_sles15_ppcle.mdx
product_docs/docs/eprs/7/03_installation/03_installing_rpm_package/x86_amd64/eprs_centos7_x86.mdx
product_docs/docs/eprs/7/03_installation/03_installing_rpm_package/x86_amd64/eprs_deb10_x86.mdx
product_docs/docs/eprs/7/03_installation/03_installing_rpm_package/x86_amd64/eprs_deb11_x86.mdx
product_docs/docs/eprs/7/03_installation/03_installing_rpm_package/x86_amd64/eprs_other_linux8_x86.mdx
product_docs/docs/eprs/7/03_installation/03_installing_rpm_package/x86_amd64/eprs_rhel7_x86.mdx
product_docs/docs/eprs/7/03_installation/03_installing_rpm_package/x86_amd64/eprs_rhel8_x86.mdx
product_docs/docs/eprs/7/03_installation/03_installing_rpm_package/x86_amd64/eprs_sles12_x86.mdx
product_docs/docs/eprs/7/03_installation/03_installing_rpm_package/x86_amd64/eprs_sles15_x86.mdx
product_docs/docs/eprs/7/03_installation/03_installing_rpm_package/x86_amd64/eprs_ubuntu18_x86.mdx
product_docs/docs/eprs/7/03_installation/03_installing_rpm_package/x86_amd64/eprs_ubuntu20_x86.mdx
product_docs/docs/pem/8/pem_online_help/04_toc_pem_features/09_pem_alerting/01_pem_alerting_dialog.mdx
product_docs/docs/pem/8/pem_online_help/04_toc_pem_features/09_pem_alerting/04_pem_custom_alert_templates.mdx

- Replication Server: added note about Java/JDK to install topics
- Barman: updated Debian support info and added info about repo
- BigAnimal: added info on using PGD dashboard template
- PEM: added info about updating threshold units

Release: 2022-10-18

---

product_docs/docs/biganimal/release/getting_started/preparing_cloud_account/01_preparing_azure/01_understanding_qotas_in_azure.mdx
product_docs/docs/pem/8/registering_agent.mdx

PEM: addressed customer issue with by updating the registering pemagent with nonroot user topic
BigAnimal: added clarifications to Understanding requirements in Azure topic

Release: 2022-10-19

---

product_docs/docs/pgd/4/bdr/nodes.mdx

Fix monospace formatting in BDR node types doc

---

product_docs/docs/biganimal/release/using_cluster/02_connecting_your_cluster/connecting_from_a_client.mdx
product_docs/docs/biganimal/release/using_cluster/02_connecting_your_cluster/index.mdx

- Restructured the topic a bit: 
- Organized content into connecting from your applications, connecting from integration points, and connecting from clients categories. 
- Created separate sections for the two integration points (migration tools and pgBouncer) for better visibility in the right nav.
- Moved the client sections to a sub-topic as our customers should know how to connect this way.
- Changed order of the sections so that connecting from your apps got top billing as that information is the most likely to be needed.
- Included note about edb-psql per https://enterprisedb.atlassian.net/browse/UPM-12238

BigAnimal: restructuring Connecting cluster topic

---

product_docs/docs/biganimal/release/using_cluster/02_connecting_your_cluster/connecting_from_a_client.mdx
product_docs/docs/biganimal/release/using_cluster/02_connecting_your_cluster/index.mdx
product_docs/docs/epas/13/epas_inst_linux/05_managing_an_advanced_server_installation.mdx
product_docs/docs/epas/13/epas_inst_windows/06_configuring_advanced_server/02_connecting_to_advanced_server_with_psql.mdx
product_docs/docs/epas/14/epas_inst_linux/managing_an_advanced_server_installation.mdx
product_docs/docs/epas/14/epas_inst_windows/managing_an_advanced_server_installation/configuring_epas.mdx
product_docs/docs/migration_portal/4/04_mp_migrating_database/01_mp_schema_extraction/01_data_pump_utility.mdx
product_docs/docs/migration_portal/4/04_mp_migrating_database/01_mp_schema_extraction/index.mdx
product_docs/docs/pgd/4/bdr/nodes.mdx

- BigAnimal: restructured Connecting your cluster topic and added note about EDB-psql
- EPAS: clarified what EDB-psql is
- Migration Portal: improved format of some code blocks
- PGD: fixed monospace formatting in BDR node types

Release: 2022-19-21

---

product_docs/docs/biganimal/release/reference/api.mdx

Fixed the example to match the output given.
See https://edb.slack.com/archives/C02UY58G6HJ/p1666373499772499

BigAnimal: API output example

---

product_docs/docs/biganimal/release/overview/02_high_availability.mdx
product_docs/docs/biganimal/release/overview/05_database_version_policy.mdx

Added 15 (beta) to Supported cluster types and Database version policy topics

BigAnimal: PostgreSQL 15 beta support

---

product_docs/docs/biganimal/release/overview/02_high_availability.mdx
product_docs/docs/biganimal/release/overview/05_database_version_policy.mdx
product_docs/docs/biganimal/release/reference/api.mdx

BigAnimal:
- Added support for PostgreSQL 15 (beta)
- Updated API example for match output

Release: 2022-10-24

---

.github/pull_request_template.md

**Cut the following text from the PR template:** 
**Examples**
**Content**

PR template: Removed majority of the user instructions

---

product_docs/docs/biganimal/release/getting_started/creating_a_cluster/index.mdx
product_docs/docs/biganimal/release/using_cluster/03_modifying_your_cluster/index.mdx
product_docs/docs/biganimal/release/using_cluster/04_backup_and_restore.mdx

Updated references to the Backups tab as it has changed to Additional Settings

BigAnimal: updating Backups tab name

---

product_docs/docs/biganimal/release/getting_started/creating_a_cluster/index.mdx
product_docs/docs/biganimal/release/reference/cli.mdx
product_docs/docs/biganimal/release/using_cluster/03_modifying_your_cluster/index.mdx
product_docs/docs/biganimal/release/using_cluster/04_backup_and_restore.mdx

BigAnimal:
- Fixed Create a cluster tab name (was Backups, now is Additional Settings)
- Added description for the CLI -warning flag

Release: 2022-10-28

---

product_docs/docs/biganimal/release/using_cluster/05_monitoring_and_logging/metrics/index.mdx

Updated working of CNP metrics documentation based on documentation team's feedback in https://github.com/EnterpriseDB/docs/pull/3161/files

chore(UPM-11145): Updated working of CNP metrics descriptions based on documentation team's feedback

---

product_docs/docs/epas/14/epas_upgrade_guide/03_limitations.mdx

Addressing feedback provided in the Slack thread: https://edb.slack.com/archives/CDV042H1D/p1665642577945449

Updated the Upgrade EPAS considerations

---

install_template/deploy.mjs
install_template/templates/products/edb-odbc-connector/base.njk
install_template/templates/products/edb-odbc-connector/debian.njk
install_template/templates/products/edb-odbc-connector/sles-12.njk
install_template/templates/products/edb-odbc-connector/sles-15.njk
install_template/templates/products/edb-odbc-connector/ubuntu.njk
product_docs/docs/biganimal/release/using_cluster/05_monitoring_and_logging/metrics/index.mdx
product_docs/docs/epas/14/epas_upgrade_guide/03_limitations.mdx
product_docs/docs/eprs/7/03_installation/03_installing_rpm_package/x86_amd64/eprs_centos7_x86.mdx
product_docs/docs/jdbc_connector/42.5.0.1/images/selecting_the_connectors_installer.png
product_docs/docs/ocl_connector/12.1.2.1/images/selecting_the_connectors_installer.png
product_docs/docs/ocl_connector/13.1.4.2/images/selecting_the_connectors_installer.png
product_docs/docs/ocl_connector/14.1.0.1/images/selecting_the_connectors_installer.png
product_docs/docs/odbc_connector/12/images/selecting_the_connectors_installer.png
product_docs/docs/odbc_connector/13/01_odbc_rel_notes/index.mdx
product_docs/docs/odbc_connector/13/03_installing_edb_odbc/01_installing_linux/ibm_power_ppc64le/odbc13_rhel8_ppcle.mdx
product_docs/docs/odbc_connector/13/03_installing_edb_odbc/01_installing_linux/ibm_power_ppc64le/odbc13_sles12_ppcle.mdx
product_docs/docs/odbc_connector/13/03_installing_edb_odbc/01_installing_linux/ibm_power_ppc64le/odbc13_sles15_ppcle.mdx
product_docs/docs/odbc_connector/13/03_installing_edb_odbc/01_installing_linux/x86_amd64/odbc13_centos7_x86.mdx
product_docs/docs/odbc_connector/13/03_installing_edb_odbc/01_installing_linux/x86_amd64/odbc13_deb10_x86.mdx
product_docs/docs/odbc_connector/13/03_installing_edb_odbc/01_installing_linux/x86_amd64/odbc13_deb11_x86.mdx
product_docs/docs/odbc_connector/13/03_installing_edb_odbc/01_installing_linux/x86_amd64/odbc13_other_linux8_x86.mdx
product_docs/docs/odbc_connector/13/03_installing_edb_odbc/01_installing_linux/x86_amd64/odbc13_rhel7_x86.mdx
product_docs/docs/odbc_connector/13/03_installing_edb_odbc/01_installing_linux/x86_amd64/odbc13_rhel8_x86.mdx
product_docs/docs/odbc_connector/13/03_installing_edb_odbc/01_installing_linux/x86_amd64/odbc13_sles12_x86.mdx
product_docs/docs/odbc_connector/13/03_installing_edb_odbc/01_installing_linux/x86_amd64/odbc13_sles15_x86.mdx
product_docs/docs/odbc_connector/13/03_installing_edb_odbc/01_installing_linux/x86_amd64/odbc13_ubuntu18_x86.mdx
product_docs/docs/odbc_connector/13/03_installing_edb_odbc/01_installing_linux/x86_amd64/odbc13_ubuntu20_x86.mdx
product_docs/docs/odbc_connector/13/images/selecting_the_connectors_installer.png

- EPAS: updates to upgrade considerations topic
- BigAnimal: copy edits to Metrics details topic
- Connectors: misc improvements

Release: 2022-11-02

---

product_docs/docs/biganimal/release/getting_started/02_connecting_to_your_cloud/connecting_aws.mdx
product_docs/docs/biganimal/release/getting_started/02_connecting_to_your_cloud/connecting_azure.mdx
product_docs/docs/biganimal/release/getting_started/02_connecting_to_your_cloud/index.mdx

BigAnimal: connecting your cloud restructure

---

.github/workflows/deploy-main.yml

- Use correct branch
- Deploy to correct site

Hotfix: correct production deployment workflow

---

product_docs/docs/net_connector/6.0.2.1/04_installing_and_configuring_the_net_connector.mdx
product_docs/docs/net_connector/6.0.2.1/14_using_plugins.mdx

[EC-2414 - removed deprecated plugins](https://github.com/EnterpriseDB/docs/commit/2598401d977e944f0cc3bfb88be3daaa83f3f3b9)
[EC-2413 - fixes to install topic](https://enterprisedb.atlassian.net/browse/EC-2413)

Connectors:  OCL fixes

---

install_template/templates/products/edb-ocl-connector/almalinux-8-or-rocky-linux-8.njk
install_template/templates/products/edb-ocl-connector/base.njk
install_template/templates/products/edb-ocl-connector/centos-7.njk
install_template/templates/products/edb-ocl-connector/debian.njk
install_template/templates/products/edb-ocl-connector/rhel-7-or-ol-7.njk
install_template/templates/products/edb-ocl-connector/rhel-8-or-ol-8.njk
install_template/templates/products/edb-ocl-connector/sles-12.njk
install_template/templates/products/edb-ocl-connector/sles-12_ppc64le.njk
install_template/templates/products/edb-ocl-connector/sles-15.njk
install_template/templates/products/edb-ocl-connector/sles-15_ppc64le.njk
install_template/templates/products/edb-ocl-connector/ubuntu.njk
product_docs/docs/ocl_connector/14.1.0.1/04_open_client_library/01_installing_and_configuring_the_ocl_connector/install_on_linux_using_edb_repo/ibm_power_ppc64le/ocl_connector14_rhel8_ppcle.mdx
product_docs/docs/ocl_connector/14.1.0.1/04_open_client_library/01_installing_and_configuring_the_ocl_connector/install_on_linux_using_edb_repo/ibm_power_ppc64le/ocl_connector14_sles12_ppcle.mdx
product_docs/docs/ocl_connector/14.1.0.1/04_open_client_library/01_installing_and_configuring_the_ocl_connector/install_on_linux_using_edb_repo/ibm_power_ppc64le/ocl_connector14_sles15_ppcle.mdx
product_docs/docs/ocl_connector/14.1.0.1/04_open_client_library/01_installing_and_configuring_the_ocl_connector/install_on_linux_using_edb_repo/x86_amd64/ocl_connector14_centos7_x86.mdx
product_docs/docs/ocl_connector/14.1.0.1/04_open_client_library/01_installing_and_configuring_the_ocl_connector/install_on_linux_using_edb_repo/x86_amd64/ocl_connector14_deb10_x86.mdx
product_docs/docs/ocl_connector/14.1.0.1/04_open_client_library/01_installing_and_configuring_the_ocl_connector/install_on_linux_using_edb_repo/x86_amd64/ocl_connector14_deb11_x86.mdx
product_docs/docs/ocl_connector/14.1.0.1/04_open_client_library/01_installing_and_configuring_the_ocl_connector/install_on_linux_using_edb_repo/x86_amd64/ocl_connector14_other_linux8_x86.mdx
product_docs/docs/ocl_connector/14.1.0.1/04_open_client_library/01_installing_and_configuring_the_ocl_connector/install_on_linux_using_edb_repo/x86_amd64/ocl_connector14_rhel7_x86.mdx
product_docs/docs/ocl_connector/14.1.0.1/04_open_client_library/01_installing_and_configuring_the_ocl_connector/install_on_linux_using_edb_repo/x86_amd64/ocl_connector14_rhel8_x86.mdx
product_docs/docs/ocl_connector/14.1.0.1/04_open_client_library/01_installing_and_configuring_the_ocl_connector/install_on_linux_using_edb_repo/x86_amd64/ocl_connector14_sles12_x86.mdx
product_docs/docs/ocl_connector/14.1.0.1/04_open_client_library/01_installing_and_configuring_the_ocl_connector/install_on_linux_using_edb_repo/x86_amd64/ocl_connector14_sles15_x86.mdx
product_docs/docs/ocl_connector/14.1.0.1/04_open_client_library/01_installing_and_configuring_the_ocl_connector/install_on_linux_using_edb_repo/x86_amd64/ocl_connector14_ubuntu18_x86.mdx
product_docs/docs/ocl_connector/14.1.0.1/04_open_client_library/01_installing_and_configuring_the_ocl_connector/install_on_linux_using_edb_repo/x86_amd64/ocl_connector14_ubuntu20_x86.mdx

https://enterprisedb.atlassian.net/browse/EC-2400

OCL connector: added correct 2nd install command

---

product_docs/docs/biganimal/release/getting_started/activating_regions.mdx

The link previously went to the BA Support Options page, not the page listing supported regions

Fix supported regions link

---

product_docs/docs/postgis/3.2/03_upgrading_postgis.mdx

The sentence has "Upgrade ... version 10 to to 14"
This change makes it "Upgrade ... version 10 to 14"

Fix to-to typo

---

advocacy_docs/pg_extensions/index.mdx
scripts/source/extensions-table.js
scripts/source/package-lock.json
scripts/source/package.json

Extensions: refreshing extensions table

---

product_docs/docs/pgd/3.7/harp/01_release_notes/harp2.2.1_rel_notes.mdx
product_docs/docs/pgd/3.7/harp/01_release_notes/index.mdx

Create release notes for harp 2.2.1

HNG-636-Create release notes for harp 2.2.1

---

product_docs/docs/biganimal/release/overview/03a_region_support.mdx

https://enterprisedb.atlassian.net/browse/UPM-13216

BigAnimal: Canada Central region

---

product_docs/docs/biganimal/release/overview/02_high_availability.mdx
product_docs/docs/biganimal/release/overview/05_database_version_policy.mdx

https://enterprisedb.atlassian.net/browse/UPM-13219

Biganimal: remove beta from PostgreSQL

---

product_docs/docs/biganimal/release/using_cluster/05_monitoring_and_logging/alerts.mdx
product_docs/docs/biganimal/release/using_cluster/05_monitoring_and_logging/index.mdx

https://docs.google.com/spreadsheets/d/1zOHx9lcn0zEnpghGwT9jVajr4uZn3wfaydCwsQ2WBws/edit#gid=885830594

BigAnimal: Log Alerts in Azure

---

product_docs/docs/eprs/6.2/eprs_rel_notes/index.mdx

Added note to release notes landing page.

EPRS: XDB-1592 exclude option requirement
