product_docs/docs/biganimal/release/free_trial/index.mdx, product_docs/docs/biganimal/release/free_trial/quickstart.mdx
Updates to the Getting started section:
- Updated latest version of PostgreSQL to be 15 (beta)
- Updated creating a cluster procedure to reflect UI changes
=> BigAnimal: updates to quick start and pg version number

product_docs/docs/epas/14/epas_compat_tools_guide/index.mdx, product_docs/docs/epas/14/epas_guide/02_enhanced_compatibility_features.mdx
=> EPAS: improving feature links

product_docs/docs/biganimal/release/free_trial/index.mdx, product_docs/docs/biganimal/release/free_trial/quickstart.mdx, product_docs/docs/efm/4/efm_deploy_arch/index.mdx, product_docs/docs/epas/14/epas_compat_tools_guide/index.mdx, product_docs/docs/epas/14/epas_guide/02_enhanced_compatibility_features.mdx, product_docs/docs/mongo_data_adapter/5/configuring.mdx, product_docs/docs/pem/8/profiling_workloads/pem_sqlprofiler/installing_the_sql_profiler_plugin.mdx
Added note about disconnecting and reconnecting before configuring SQL Profiler.
https://github.com/EnterpriseDB/docs/issues/3357
=> PEM: GitHub Issue 3357

advocacy_docs/pg_extensions/advanced_storage_pack/configuring.mdx, advocacy_docs/pg_extensions/advanced_storage_pack/index.mdx, advocacy_docs/pg_extensions/advanced_storage_pack/installing.mdx, advocacy_docs/pg_extensions/advanced_storage_pack/rel_notes/asp_1.0.0_rel_notes.mdx, advocacy_docs/pg_extensions/advanced_storage_pack/rel_notes/index.mdx, advocacy_docs/pg_extensions/advanced_storage_pack/using.mdx, advocacy_docs/pg_extensions/ldap_sync/configuring.mdx, advocacy_docs/pg_extensions/ldap_sync/index.mdx, advocacy_docs/pg_extensions/ldap_sync/installing.mdx, advocacy_docs/pg_extensions/ldap_sync/rel_notes/index.mdx, advocacy_docs/pg_extensions/ldap_sync/rel_notes/ldap_sync_1.0.0_rel_notes.mdx, advocacy_docs/pg_extensions/ldap_sync/using.mdx, advocacy_docs/pg_extensions/pg_tuner/configuring.mdx, advocacy_docs/pg_extensions/pg_tuner/index.mdx, advocacy_docs/pg_extensions/pg_tuner/installing.mdx, advocacy_docs/pg_extensions/pg_tuner/rel_notes/index.mdx, advocacy_docs/pg_extensions/pg_tuner/rel_notes/pg_tuner_1.0.0_rel_notes.mdx, advocacy_docs/pg_extensions/pg_tuner/using.mdx, gatsby-node.js, product_docs/docs/pgd/4/bdr/camo.mdx, src/pages/index.js
Initial Postgres Tuner, ASP, LDAP Sync release
PGD: fixed CAMO typo
=> Release: 2022-11-29

product_docs/docs/livecompare/2/rel_notes/2.4_rel_notes.mdx, product_docs/docs/livecompare/2/rel_notes/index.mdx
Release notes updated for LiveCompare 2.4
=> Added release notes for LC2.4

product_docs/docs/biganimal/release/pricing_and_billing/index.mdx
Added subscription plans to the database pricing table
=> BigAnimal: subscription pricing

advocacy_docs/pg_extensions/index.mdx, scripts/source/extensions-table.js
=> Extensions table update

product_docs/docs/pgd/4/harp/index.mdx
Minor fixes for spelling and grammar, but highly visible as most are in the opening paragraph.
=> spelling, grammar

product_docs/docs/biganimal/release/getting_started/creating_a_cluster/index.mdx, product_docs/docs/biganimal/release/using_cluster/01_postgres_access.mdx, product_docs/docs/biganimal/release/using_cluster/03_modifying_your_cluster/index.mdx
=> Updates for IAM authentication feature

advocacy_docs/pg_extensions/index.mdx, product_docs/docs/biganimal/release/getting_started/creating_a_cluster/index.mdx, product_docs/docs/biganimal/release/getting_started/index.mdx, product_docs/docs/biganimal/release/pricing_and_billing/index.mdx, product_docs/docs/biganimal/release/using_cluster/01_postgres_access.mdx, product_docs/docs/biganimal/release/using_cluster/03_modifying_your_cluster/index.mdx, product_docs/docs/biganimal/release/using_cluster/terraform_provider.mdx, product_docs/docs/pgd/4/harp/index.mdx, product_docs/docs/pgd/4/upgrades/upgrade_paths.mdx, scripts/source/extensions-table.js
- BigAnimal:
- Terraform
- Subscription pricing
- IAM
- HARP: fixed typos on landing page
- BDR: fixed broken link in upgrade topic
=> Release: 2022-12-01

product_docs/docs/biganimal/release/overview/03a_region_support.mdx
https://enterprisedb.atlassian.net/browse/UPM-10255
=> BigAnimal: EU Central 1 region

product_docs/docs/efm/4/04_configuring_efm/01_cluster_properties.mdx, product_docs/docs/efm/4/04_configuring_efm/06_configuring_for_eager_failover.mdx, product_docs/docs/efm/4/installing/prerequisites.mdx, product_docs/docs/efm/4/upgrading.mdx, product_docs/docs/postgis/3.2/01_release_notes/rel_notes312.mdx, product_docs/docs/postgis/3.2/installing/upgrading.mdx
various small changes to correct broken links
=> fixed broken links for EFM and PostGIS

product_docs/docs/pgd/3.7/bdr/durability.mdx, product_docs/docs/pgd/4/bdr/durability.mdx
BDR-2852
BDR3.7 and BDR4 docs related to synchronous replication.
=> Warn about synchronous replication issues with multiple bdr databases

product_docs/docs/biganimal/release/reference/cli.mdx, product_docs/docs/biganimal/release/using_cluster/01_postgres_access.mdx
https://enterprisedb.atlassian.net/browse/UPM-11990
=> BigAnimal: CLI updates

product_docs/docs/biganimal/release/free_trial/detail/connect_to_a_cluster/connect_using_pgadmin.mdx, product_docs/docs/biganimal/release/free_trial/detail/create_a_cluster/create_cluster_portal.mdx
Updates based on feedback from Sarah Conway in the ba-internal-product Slack channel:
- https://edb.slack.com/archives/C02UY58G6HJ/p1669874673906139
- https://edb.slack.com/archives/C02UY58G6HJ/p1670098668298379
=> BigAnimal: updates to Free Trial topics

advocacy_docs/pg_extensions/advanced_storage_pack/using.mdx
- fixed typo
- fixed spacing in tables
=> Extensions release edits 2

advocacy_docs/pg_extensions/advanced_storage_pack/using.mdx, product_docs/docs/biganimal/release/free_trial/detail/connect_to_a_cluster/connect_using_pgadmin.mdx, product_docs/docs/biganimal/release/free_trial/detail/create_a_cluster/create_cluster_portal.mdx, product_docs/docs/biganimal/release/getting_started/activating_regions.mdx, product_docs/docs/biganimal/release/reference/cli.mdx, product_docs/docs/biganimal/release/using_cluster/01_postgres_access.mdx, product_docs/docs/pgd/3.7/bdr/durability.mdx, product_docs/docs/pgd/4/bdr/durability.mdx, product_docs/docs/pgd/4/harp/09_consensus-layer.mdx
- Extensions:  fixed a couple small issues in ASP topic
- BA:
- Updated some more out-of-date content and addressed some feedback in the Free trial section
- Updated some out-of-date content in the Activating regions topic
- Added a sample use case section for IAM BA CLI commands 
- PGD: 
- Warn about synchronous replication issues with multiple bdr databases 
- Harp update: Subscriber-Only nodes are not considered in quorum
=> Release: 2022-12-05

product_docs/docs/pgd/4/bdr/functions.mdx
Addresses https://github.com/EnterpriseDB/docs/issues/1979
=> PGD: removed stray text

product_docs/docs/epas/14/epas_guide/03_database_administration/02_index_advisor/index.mdx
Changed link from generic EDB docs link to specific topic in PEM docs
=> EPAS: updated link from Index Advisor to PEM doc

product_docs/docs/epas/11/epas_guide/03_database_administration/02_index_advisor/index.mdx, product_docs/docs/epas/12/epas_guide/03_database_administration/02_index_advisor/index.mdx, product_docs/docs/epas/13/epas_guide/03_database_administration/02_index_advisor/index.mdx
Neglected to commit the link fix to older versions before merging #3419
=> EPAS: missing commit to #3419

product_docs/docs/eprs/7/eprs_rel_notes/18_eprs_rel_notes_7.1.0.mdx
=> EPRS: 7.1.0 rel note update

product_docs/docs/pgd/3.7/bdr/release-notes.mdx, product_docs/docs/pgd/3.7/pglogical/release-notes.mdx, product_docs/docs/pgd/4/rel_notes/index.mdx, product_docs/docs/pgd/4/rel_notes/pgd_4.2.2_rel_notes.mdx
BDR-2882
Release notes for PGD 4.2.2 and 3.7.19
=> Add release notes for PGD 4.2.2 and 3.7.19

product_docs/docs/migration_toolkit/55/installing/installing_jdbc_driver.mdx
=> MTK: fixed errant redirect on JDBC topic

product_docs/docs/migration_portal/4/04_mp_migrating_database/01_mp_schema_extraction/01_data_pump_utility.mdx
Fixed link that had an extra /
=> Migration Portal: link fix

product_docs/docs/pgd/4/bdr/camo.mdx, product_docs/docs/pgd/4/bdr/functions.mdx
=> PGD: Added Connection pools section

product_docs/docs/epas/14/epas_compat_sql/44_delete.mdx
=> EPAS 14 - Updated FROM clause as per DF-296

advocacy_docs/pg_extensions/index.mdx
Trying to fix issues caused by yellow background color in the source doc. Removed the color in the Doc Preview, but the source_extension step isn't finding differences in the file and is erroring out.
https://docs.google.com/spreadsheets/d/1GXzzVYT6CULGgGcyp0VtBfOtbxuWxkOU2pRYW42W4pM/edit#gid=1884264748
=> Extensions: fix table formatting

advocacy_docs/pg_extensions/index.mdx, product_docs/docs/biganimal/release/overview/02_high_availability.mdx, product_docs/docs/biganimal/release/overview/images/FarawayReplicas-afterpromotion.png, product_docs/docs/biganimal/release/overview/images/FarawayReplicas-generic.png, product_docs/docs/biganimal/release/overview/index.mdx, product_docs/docs/biganimal/release/overview/replication.mdx, product_docs/docs/biganimal/release/using_cluster/02_connecting_your_cluster/index.mdx, product_docs/docs/biganimal/release/using_cluster/03_modifying_your_cluster/index.mdx, product_docs/docs/biganimal/release/using_cluster/04_backup_and_restore.mdx, product_docs/docs/biganimal/release/using_cluster/05a_deleting_your_cluster.mdx, product_docs/docs/biganimal/release/using_cluster/index.mdx, product_docs/docs/biganimal/release/using_cluster/managing_replicas.mdx, product_docs/docs/epas/14/epas_compat_sql/44_delete.mdx, product_docs/docs/pgd/4/bdr/camo.mdx, product_docs/docs/pgd/4/bdr/functions.mdx
BigAnimal: Faraway replicas feature
Extensions: Fixed background color issue
PGD: Added missing CAMO section
EPAS: addressed feedback on DELETE FROM syntax
=> Release: 2022-12-16

product_docs/docs/biganimal/release/using_cluster/04_backup_and_restore.mdx
The deleted paragraph has already been detailed in the preceding paragraph.
=> Duplicate content regarding backups

product_docs/docs/biganimal/release/using_cluster/managing_replicas.mdx
Fixed link and updated content related to pre-populated fields
=> BigAnimal: fixes to Faraway replica content

product_docs/docs/biganimal/release/administering_cluster/01_portal_access.mdx, product_docs/docs/biganimal/release/administering_cluster/01a_superset_access.mdx, product_docs/docs/biganimal/release/administering_cluster/03_account_activity.mdx, product_docs/docs/biganimal/release/administering_cluster/images/projects.png, product_docs/docs/biganimal/release/administering_cluster/index.mdx, product_docs/docs/biganimal/release/administering_cluster/projects.mdx, product_docs/docs/biganimal/release/getting_started/02_azure_market_setup.mdx, product_docs/docs/biganimal/release/getting_started/02_connecting_to_your_cloud/connecting_aws.mdx, product_docs/docs/biganimal/release/getting_started/02_connecting_to_your_cloud/connecting_azure.mdx, product_docs/docs/biganimal/release/getting_started/02_connecting_to_your_cloud/index.mdx, product_docs/docs/biganimal/release/getting_started/identity_provider/index.mdx, product_docs/docs/biganimal/release/reference/cli.mdx, product_docs/docs/biganimal/release/using_cluster/04_backup_and_restore.mdx, product_docs/docs/biganimal/release/using_cluster/index.mdx, product_docs/docs/biganimal/release/using_cluster/managing_replicas.mdx, product_docs/docs/pgd/4/bdr/camo.mdx, product_docs/docs/pgd/4/bdr/group-commit.mdx
- BigAnimal: Added new Projects feature by @moiznalwalla in #3346 
- BigAnimal: Faraway Replica content fixes by @drothery-edb in #3464 
- BigAnimal: Deleted duplicate content by @sandeeparoraedb in #3461
=> Production Release: 2022-12-19

product_docs/docs/biganimal/release/using_cluster/managing_replicas.mdx
Removed text for the region related changes, Region is not modifiable.
=> Section - "Modify a faraway replica"

product_docs/docs/biganimal/release/administering_cluster/01a_superset_access.mdx, product_docs/docs/biganimal/release/getting_started/02_azure_market_setup.mdx, product_docs/docs/biganimal/release/getting_started/identity_provider/index.mdx
Fixed broken links in BigAnimal
=> BigAnimal: Fixed broken links 

product_docs/docs/edb_plus/40/installing/index.mdx, product_docs/docs/efm/4/installing/index.mdx, product_docs/docs/hadoop_data_adapter/2/installing/index.mdx, product_docs/docs/jdbc_connector/42.5.1.1/installing/index.mdx, product_docs/docs/migration_toolkit/55/installing/index.mdx, product_docs/docs/mongo_data_adapter/5/installing/index.mdx, product_docs/docs/mysql_data_adapter/2/installing/index.mdx, product_docs/docs/ocl_connector/14.1.0.1/installing/index.mdx, product_docs/docs/odbc_connector/13/installing/index.mdx, product_docs/docs/pgbouncer/1.17/installing/index.mdx, product_docs/docs/postgis/3.2/installing/index.mdx
/installing/index.mdx for various products - added stem sentence for all and added heading for Windows, if applicable
=> Main landing page - stem sentence and Windows 19 if necessary

product_docs/docs/biganimal/release/overview/replication.mdx, product_docs/docs/biganimal/release/using_cluster/managing_replicas.mdx
Add a prerequisite block for faraway replicas.
=> docs(UPM-14667): Add Prerequisite section for faraway replica

product_docs/docs/epas/14/epas_guide/03_database_administration/05_edb_audit_logging/04_audit_log_file.mdx
=> EPAS 14 - Updated CSV audit log and added note for XML as per DB-1871

product_docs/docs/eprs/6.2/03_installation/03_installing_rpm_package.mdx
Fixed broken link and updated link title.
=> EPRS link fix

product_docs/docs/biganimal/release/administering_cluster/images/projects.jpg, product_docs/docs/biganimal/release/administering_cluster/images/projects.png, product_docs/docs/biganimal/release/administering_cluster/projects.mdx
Added a diagram to the Managing projects topic
=> BigAnimal: projects diagram

product_docs/docs/biganimal/release/using_cluster/02_connecting_your_cluster/02_connecting_from_aws/index.mdx
The example was showing K8 cluster, so changed it and updated to Load balancer example. Please review it with the dev/product team
=> Loadbalancer example

product_docs/docs/biganimal/release/administering_cluster/projects.mdx, product_docs/docs/biganimal/release/getting_started/creating_a_cluster/index.mdx, product_docs/docs/biganimal/release/reference/cli/index.mdx, product_docs/docs/biganimal/release/reference/cli/managing_clusters.mdx, product_docs/docs/biganimal/release/reference/cli/using_features.mdx, product_docs/docs/biganimal/release/using_cluster/02_connecting_your_cluster/index.mdx, product_docs/docs/biganimal/release/using_cluster/managing_replicas.mdx, product_docs/docs/biganimal/release/using_cluster/terraform_provider.mdx
Added sub topics under CLI topic for use cases that can be linked to from the feature topics
=> BigAnimal: prototype of stop gap CLI restructure

advocacy_docs/pg_extensions/advanced_storage_pack/index.mdx, advocacy_docs/pg_extensions/advanced_storage_pack/using.mdx, advocacy_docs/supported-open-source/pgbackrest/index.mdx, product_docs/docs/biganimal/release/getting_started/creating_a_cluster/index.mdx, product_docs/docs/biganimal/release/overview/03a_region_support.mdx, product_docs/docs/biganimal/release/overview/replication.mdx, product_docs/docs/biganimal/release/reference/cli/index.mdx, product_docs/docs/biganimal/release/reference/cli/managing_clusters.mdx, product_docs/docs/biganimal/release/reference/cli/using_features.mdx, product_docs/docs/biganimal/release/using_cluster/02_connecting_your_cluster/02_connecting_from_aws/index.mdx, product_docs/docs/biganimal/release/using_cluster/02_connecting_your_cluster/index.mdx, product_docs/docs/biganimal/release/using_cluster/managing_replicas.mdx, product_docs/docs/biganimal/release/using_cluster/terraform_provider.mdx
- pgBackRest 2.42 release
- Incorporated feedback on the new extensions
- BigAnimal:
- AWS loadbalancer example updates
- Region limitations for faraway replica
- Added content from faraway replicas FAQ 
- Corrected what was editable when creating a faraway replica
- Added child topics for CLI use cases and added faraway replica commands
=> Release: 2023-01-11

product_docs/docs/biganimal/release/overview/updates.mdx
https://enterprisedb.atlassian.net/browse/UPM-11184
=> BigAnimal: retry logic

product_docs/docs/biganimal/release/reference/cli/using_features.mdx
Included info on update, delete, and restore
=> BigAnimal: more detail for CLI commands for faraway replicas

product_docs/docs/biganimal/release/using_cluster/01_postgres_access.mdx, product_docs/docs/biganimal/release/using_cluster/terraform_provider.mdx
Changed API version to v3
Moved errant See also section to the correct topic - see https://deploy-preview-3539--edb-docs-staging.netlify.app/docs/biganimal/latest/using_cluster/01_postgres_access/#see-also
=> BigAnimal: Terraform updates

install_template/templates/products/edb-pgpool-ii-extensions/base.njk, product_docs/docs/biganimal/release/reference/cli/using_features.mdx, product_docs/docs/biganimal/release/using_cluster/01_postgres_access.mdx, product_docs/docs/biganimal/release/using_cluster/terraform_provider.mdx, product_docs/docs/eprs/7/installing/linux_ppc64le/eprs_rhel_8.mdx, product_docs/docs/eprs/7/installing/linux_x86_64/eprs_rhel_8.mdx, product_docs/docs/pgd/4/bdr/ddl.mdx, product_docs/docs/pgpool/4.3/installing_extensions/linux_ppc64le/pgpoolext_rhel_8.mdx, product_docs/docs/pgpool/4.3/installing_extensions/linux_ppc64le/pgpoolext_sles_12.mdx, product_docs/docs/pgpool/4.3/installing_extensions/linux_ppc64le/pgpoolext_sles_15.mdx, product_docs/docs/pgpool/4.3/installing_extensions/linux_x86_64/pgpoolext_centos_7.mdx, product_docs/docs/pgpool/4.3/installing_extensions/linux_x86_64/pgpoolext_debian_10.mdx, product_docs/docs/pgpool/4.3/installing_extensions/linux_x86_64/pgpoolext_debian_11.mdx, product_docs/docs/pgpool/4.3/installing_extensions/linux_x86_64/pgpoolext_other_linux_8.mdx, product_docs/docs/pgpool/4.3/installing_extensions/linux_x86_64/pgpoolext_rhel_7.mdx, product_docs/docs/pgpool/4.3/installing_extensions/linux_x86_64/pgpoolext_rhel_8.mdx, product_docs/docs/pgpool/4.3/installing_extensions/linux_x86_64/pgpoolext_sles_12.mdx, product_docs/docs/pgpool/4.3/installing_extensions/linux_x86_64/pgpoolext_sles_15.mdx, product_docs/docs/pgpool/4.3/installing_extensions/linux_x86_64/pgpoolext_ubuntu_18.mdx, product_docs/docs/pgpool/4.3/installing_extensions/linux_x86_64/pgpoolext_ubuntu_20.mdx
- PGD: added a note on PASSWORD_PROFILE_FUNCTION
- EPRS: removed codeready-builder info fro RHEL install topics
- PgPool: fixed typo in the PgPool extensions install topics
- BigAnimal:
- Updated the API version on the Terraform topic and moved an errant See also section
- Added more info about CLI commands for faraway replicas
=> Release: 2023-01-16

advocacy_docs/supported-open-source/postgresql/installer/02_installing_postgresql_with_the_graphical_installation_wizard/01_invoking_the_graphical_installer.mdx, advocacy_docs/supported-open-source/postgresql/installer/images/the_port_dialog.png
Added Port graphic and some minor wording changes
This PR addresses issue addresses issue [3460](https://github.com/EnterpriseDB/docs/issues/3460).
=> Add Port dialog graphic to PostgreSQL installation on Windows

product_docs/docs/migration_portal/4/02_supported_platforms.mdx
Updated Supported platforms topic
=> MP: remove support for EPAS 10

product_docs/docs/biganimal/release/overview/03a_region_support.mdx
https://enterprisedb.atlassian.net/browse/UPM-15187
=> fix(UPM-15187): Adding support for AWS Sydney Region

product_docs/docs/biganimal/release/overview/03a_region_support.mdx, product_docs/docs/migration_portal/4/02_supported_platforms.mdx
BigAnimal: Added Sydney region for AWS
Migration Portal: removed support for EPAS 10
=> Release: 2023-01-20

product_docs/docs/epas/14/epas_compat_tools_guide/04_dynamic_runtime_instrumentation_tools_architecture_DRITA.mdx, product_docs/docs/epas/14/epas_compat_tools_guide/index.mdx
=> Rest of compatibility guide

product_docs/docs/biganimal/release/getting_started/activating_regions.mdx
Updated region status reference table
=> BigAnimal: possible regions error cause - quota issue

advocacy_docs/supported-open-source/postgresql/installer/05_uninstalling_postgresql.mdx
Added a note to uninstall topic about uninstalling components that Stack Builder installed
=> Uninstalling stack builder components

src/templates/doc.js, src/templates/learn-doc.js
"Edit this page" -> "Suggest Edits" (+ small tooltip for context)
Fixes #3533
=> Rename the Edit this page button

advocacy_docs/supported-open-source/postgresql/installer/02_installing_postgresql_with_the_graphical_installation_wizard/index.mdx, advocacy_docs/supported-open-source/postgresql/installer/02_installing_postgresql_with_the_graphical_installation_wizard/macos.mdx, advocacy_docs/supported-open-source/postgresql/installer/02_installing_postgresql_with_the_graphical_installation_wizard/windows.mdx, advocacy_docs/supported-open-source/postgresql/installer/04_installation_troubleshooting.mdx, advocacy_docs/supported-open-source/postgresql/installer/05_uninstalling_postgresql.mdx, advocacy_docs/supported-open-source/postgresql/installer/index.mdx, product_docs/docs/biganimal/release/pricing_and_billing/index.mdx, product_docs/docs/biganimal/release/reference/cli/using_features.mdx, product_docs/docs/biganimal/release/using_cluster/01_postgres_access.mdx, product_docs/docs/biganimal/release/using_cluster/managing_replicas.mdx, src/templates/doc.js, src/templates/learn-doc.js
- Renamed Edit this page button and added tip
- BigAnimal: 
- refinements to CLI content model
- added info about EHA pricing
- Minor improvements to PostgreSQL instructions
=> Release: 2023-01-25

product_docs/docs/biganimal/release/getting_started/identity_provider/aws_sso.mdx
=> BigAnimal: fixed typo in AWS SSO topic

advocacy_docs/partner_docs/ImpervaDataSecurityFabric/02-PartnerInformation.mdx, advocacy_docs/partner_docs/ImpervaDataSecurityFabric/03-SolutionSummary.mdx, advocacy_docs/partner_docs/ImpervaDataSecurityFabric/04-ConfiguringImpervaDataSecurityFabric.mdx, advocacy_docs/partner_docs/ImpervaDataSecurityFabric/05-UsingImpervaDataSecurityFabric.mdx, advocacy_docs/partner_docs/ImpervaDataSecurityFabric/06-CertificationEnvironment.mdx, advocacy_docs/partner_docs/ImpervaDataSecurityFabric/07-Support.mdx, advocacy_docs/partner_docs/ImpervaDataSecurityFabric/Images/ImpervaAgentConfiguration.png, advocacy_docs/partner_docs/ImpervaDataSecurityFabric/Images/ImpervaDBAudits.png, advocacy_docs/partner_docs/ImpervaDataSecurityFabric/Images/ImpervaDataSecurityFabricOverview.png, advocacy_docs/partner_docs/ImpervaDataSecurityFabric/Images/ImpervaDataSecurityFabricforPostgreSQL.png, advocacy_docs/partner_docs/ImpervaDataSecurityFabric/Images/ImpervaLogRetrieval.png, advocacy_docs/partner_docs/ImpervaDataSecurityFabric/Images/ImpervaSitesTree.png, advocacy_docs/partner_docs/ImpervaDataSecurityFabric/Images/PartnerProgram.jpg.png, advocacy_docs/partner_docs/ImpervaDataSecurityFabric/index.mdx, src/pages/index.js
Added Imperva Data Security Fabric partner guide
=> Release: 2023-01-30

product_docs/docs/biganimal/release/getting_started/identity_provider/auth0.mdx, product_docs/docs/biganimal/release/getting_started/identity_provider/aws_sso.mdx, product_docs/docs/biganimal/release/getting_started/identity_provider/azure_ad.mdx, product_docs/docs/biganimal/release/getting_started/identity_provider/index.mdx, product_docs/docs/biganimal/release/getting_started/identity_provider/okta.mdx
https://enterprisedb.atlassian.net/browse/UPM-10159
Added a section in the IdP parent topic.
=> BigAnimal: quick sign-in URL

advocacy_docs/supported-open-source/postgresql/index.mdx, advocacy_docs/supported-open-source/postgresql/installer/01_requirements_overview.mdx, advocacy_docs/supported-open-source/postgresql/installer/02_installing_postgresql_with_the_graphical_installation_wizard/index.mdx, advocacy_docs/supported-open-source/postgresql/installer/02_installing_postgresql_with_the_graphical_installation_wizard/macos.mdx, advocacy_docs/supported-open-source/postgresql/installer/02_installing_postgresql_with_the_graphical_installation_wizard/windows.mdx, advocacy_docs/supported-open-source/postgresql/installer/03_using_stackbuilder.mdx, advocacy_docs/supported-open-source/postgresql/installer/04_installation_troubleshooting.mdx, advocacy_docs/supported-open-source/postgresql/installer/05_uninstalling_postgresql.mdx, advocacy_docs/supported-open-source/postgresql/installer/index.mdx
Edit of entire space to apply department standards
=> General copy edit of PostgreSQL

product_docs/docs/biganimal/release/using_cluster/02_connecting_your_cluster/01_connecting_from_azure/02_virtual_network_peering.mdx, product_docs/docs/biganimal/release/using_cluster/02_connecting_your_cluster/01_connecting_from_azure/03_vnet_vnet.mdx, product_docs/docs/biganimal/release/using_cluster/02_connecting_your_cluster/01_connecting_from_azure/index.mdx, product_docs/docs/biganimal/release/using_cluster/02_connecting_your_cluster/02_connecting_from_aws/02_vpc_peering.mdx, product_docs/docs/biganimal/release/using_cluster/02_connecting_your_cluster/02_connecting_from_aws/index.mdx
- Updated the text references to cluster IDs to use the shorter version
- Removed any screenshots that showed the old cluster ID
Made these changes in the Connecting your cluster section
=> BigAnimal: cluster ID updates

product_docs/docs/biganimal/release/getting_started/identity_provider/aws_sso.mdx, product_docs/docs/biganimal/release/getting_started/identity_provider/index.mdx
Changed name to AWS IAM Identity Center
Fixes https://github.com/EnterpriseDB/docs/issues/3583
=> BigAnimal: updated AWS SSO name

product_docs/docs/biganimal/release/using_cluster/02_connecting_your_cluster/01_connecting_from_azure/index.mdx
replace the old pg cluster id `p-c4iabjleig40jngmac40` with the new one `p-mckwlbakq5`
=> replace the old pg cluster id `p-c4iabjleig40jngmac40` with the new one `p-mckwlbakq5`

product_docs/docs/efm/4/index.mdx
Fixes https://github.com/EnterpriseDB/docs/issues/3604
=> EFM: clarifying support for PostgreSQL

advocacy_docs/partner_docs/ImpervaDataSecurityFabric/02-PartnerInformation.mdx, advocacy_docs/partner_docs/ImpervaDataSecurityFabric/06-CertificationEnvironment.mdx
=> Tech Partner Imperva DSF Guide Updates

advocacy_docs/pg_extensions/advanced_storage_pack/using.mdx
Changes as per [ASP-17](https://enterprisedb.atlassian.net/browse/ASP-17)
[ASP-17]: https://enterprisedb.atlassian.net/browse/ASP-17?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ASP DDL fix

.devcontainer/library-scripts/git-lfs-debian.sh, .github/workflows/deploy-develop.yml, .github/workflows/deploy-draft.yml, .github/workflows/deploy-main.yml, advocacy_docs/partner_docs/ChemaxonJChemPostgreSQLCartridge/02-PartnerInformation.mdx, advocacy_docs/partner_docs/ChemaxonJChemPostgreSQLCartridge/03-SolutionSummary.mdx, advocacy_docs/partner_docs/ChemaxonJChemPostgreSQLCartridge/04-Configuration.mdx, advocacy_docs/partner_docs/ChemaxonJChemPostgreSQLCartridge/05-Using.mdx, advocacy_docs/partner_docs/ChemaxonJChemPostgreSQLCartridge/06-CertificationEnvironment.mdx, advocacy_docs/partner_docs/ChemaxonJChemPostgreSQLCartridge/Images/PartnerProgram.png, advocacy_docs/partner_docs/ChemaxonJChemPostgreSQLCartridge/Images/UpdatedChemaxonSolutionSummary.png, advocacy_docs/partner_docs/ChemaxonJChemPostgreSQLCartridge/index.mdx, src/pages/index.js
Added new Chemaxon JChem PostgreSQL Cartridge partner guide
=> Release: 2023-02-06

advocacy_docs/partner_docs/ChemaxonJChemPostgreSQLCartridge/index.mdx, advocacy_docs/supported-open-source/postgresql/installer/02_installing_postgresql_with_the_graphical_installation_wizard/command_line_parameters.mdx, advocacy_docs/supported-open-source/postgresql/installer/02_installing_postgresql_with_the_graphical_installation_wizard/index.mdx, install_template/templates/products/postgres-enterprise-manager-server/base.njk, product_docs/docs/pem/9/considerations/authentication_options/configuring_the_pem_server_to_use_kerberos_authentication.mdx, product_docs/docs/pem/9/considerations/authentication_options/configuring_the_pem_server_to_use_windows_kerberos_server.mdx, product_docs/docs/pem/9/considerations/authentication_options/index.mdx, product_docs/docs/pem/9/considerations/index.mdx, product_docs/docs/pem/9/considerations/installing_pem_server_and_apache_web_server_preferences.mdx, product_docs/docs/pem/9/considerations/pem_pgbouncer/configuring_the_pem_agent.mdx, product_docs/docs/pem/9/considerations/setup_ha_using_efm.mdx, product_docs/docs/pem/9/installing/index.mdx, product_docs/docs/pem/9/installing/linux_ppc64le/pem_rhel_8.mdx, product_docs/docs/pem/9/installing/linux_ppc64le/pem_sles_12.mdx, product_docs/docs/pem/9/installing/linux_ppc64le/pem_sles_15.mdx, product_docs/docs/pem/9/installing/linux_x86_64/pem_centos_7.mdx, product_docs/docs/pem/9/installing/linux_x86_64/pem_debian_10.mdx, product_docs/docs/pem/9/installing/linux_x86_64/pem_debian_11.mdx, product_docs/docs/pem/9/installing/linux_x86_64/pem_other_linux_8.mdx, product_docs/docs/pem/9/installing/linux_x86_64/pem_rhel_7.mdx, product_docs/docs/pem/9/installing/linux_x86_64/pem_rhel_8.mdx, product_docs/docs/pem/9/installing/linux_x86_64/pem_sles_12.mdx, product_docs/docs/pem/9/installing/linux_x86_64/pem_sles_15.mdx, product_docs/docs/pem/9/installing/linux_x86_64/pem_ubuntu_18.mdx, product_docs/docs/pem/9/installing/linux_x86_64/pem_ubuntu_20.mdx, product_docs/docs/pem/9/installing/prerequisites.mdx, product_docs/docs/pem/9/installing/windows/index.mdx, product_docs/docs/pem/9/profiling_workloads/pem_sqlprofiler/installing_the_sql_profiler_plugin.mdx, product_docs/docs/pem/9/upgrading/upgrading_pem_installation/upgrading_pem_installation_linux_rpm.mdx
- Partner docs: updated product name in Chemaxon JChem PostgreSQL Cartridge Implementation Guide
- PostgreSQL install docs: added command line options
- PEM: fixed broken PDF links
=> Release: 2023-02-07

product_docs/docs/pgd/5/index.mdx
BDR-3157
Added  compatibility matrix for pgd5
=> Adjust compatibility matrix for PGD5

.github/workflows/deploy-develop.yml, .github/workflows/deploy-draft.yml, .github/workflows/deploy-main.yml, .github/workflows/source-extensions.yml, .github/workflows/sync-and-process-files.yml
update node js version if needed and actions
=> fix(UPM-12035): update yaml file form github workflows with node js superior at 16

product_docs/docs/biganimal/release/using_cluster/01_postgres_access.mdx
draft in response to this feedback: https://edb.slack.com/archives/C02UY58G6HJ/p1675716338560079
=> BigAnimal: db auth clarification

.github/workflows/deploy-develop.yml, .github/workflows/deploy-draft.yml, .github/workflows/deploy-main.yml, .github/workflows/source-extensions.yml, .github/workflows/sync-and-process-files.yml, product_docs/docs/biganimal/release/using_cluster/01_postgres_access.mdx
BigAnimal: added clarification around the distinction between db and portal authentication
=> Release: 2023-02-10

product_docs/docs/biganimal/release/pricing_and_billing/index.mdx
Updated based on https://drive.google.com/file/d/1RHImUCy5rUEjIE0chl0CI9XY9Vbc7IMC/view
=> BigAnimal: updated pricing

product_docs/docs/biganimal/release/pricing_and_billing/index.mdx
=> Release: 2023-02-10a

product_docs/docs/efm/4/04_configuring_efm/06_configuring_for_eager_failover.mdx
Fixed typo reported by GitHub issue #3640
=> EFM: fixed typo

product_docs/docs/eprs/7/installing/upgrading_replication_server/index.mdx, product_docs/docs/eprs/7/installing/upgrading_replication_server/upgrading_linux.mdx, product_docs/docs/eprs/7/installing/upgrading_replication_server/upgrading_with_xdb_rpm_package.mdx
Addresses https://enterprisedb.atlassian.net/browse/XDB-1887
Fixes https://github.com/EnterpriseDB/docs/issues/3599
=> EPRS: clarifying upgrade instructions

product_docs/docs/efm/4/04_configuring_efm/06_configuring_for_eager_failover.mdx, product_docs/docs/eprs/7/installing/upgrading_replication_server/index.mdx, product_docs/docs/eprs/7/installing/upgrading_replication_server/upgrading_linux.mdx, product_docs/docs/eprs/7/installing/upgrading_replication_server/upgrading_with_xdb_rpm_package.mdx
- Replication Server: added clarity to upgrade instructions
- EFM: fixed typo
=> Release: 2023-02-13

advocacy_docs/supported-open-source/postgresql/installer/04_installation_troubleshooting.mdx
Small change to troubleshooting topic
=> Update troubleshooting regarding ASCII user names

product_docs/docs/pgd/4/rel_notes/index.mdx, product_docs/docs/pgd/4/rel_notes/pgd_4.3.0_rel_notes.mdx
BDR-3181
Add Release notes for BDR 4.3.0
=> Add release notes for PGD 4.3.0

product_docs/docs/pgd/3.7/bdr/release-notes.mdx, product_docs/docs/pgd/3.7/pglogical/release-notes.mdx
=> Add release notes for PGD 3.7.20

product_docs/docs/eprs/7/02_overview/04_design_replication_system/03_restrictions_on_replicated_database_objects.mdx
Changes as per [XDB-1884](https://enterprisedb.atlassian.net/browse/XDB-1884)
[XDB-1884]: https://enterprisedb.atlassian.net/browse/XDB-1884?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> EPRS: Adding limitations section for re-snapshot for views

product_docs/docs/migration_toolkit/55/mtk_rel_notes/index.mdx, product_docs/docs/migration_toolkit/55/mtk_rel_notes/mtk_555_rel_notes.mdx
Added release notes as per [MIG-4356](https://enterprisedb.atlassian.net/browse/MIG-4356)
[MIG-4356]: https://enterprisedb.atlassian.net/browse/MIG-4356?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Migration Toolkit: 55.5 release

product_docs/docs/eprs/7/01_introduction/03_certified_supported_versions.mdx, product_docs/docs/eprs/7/02_overview/04_design_replication_system/02_design_considerations.mdx, product_docs/docs/eprs/7/02_overview/04_design_replication_system/03_restrictions_on_replicated_database_objects.mdx, product_docs/docs/eprs/7/eprs_rel_notes/eprs_rel_notes_7.5.0.mdx, product_docs/docs/eprs/7/eprs_rel_notes/index.mdx
Changes part of the 7.5 release are: 
- [XDB-1885](https://enterprisedb.atlassian.net/browse/XDB-1885)
- [XDB-1889](https://enterprisedb.atlassian.net/browse/XDB-1889)
- [XDB-1888](https://enterprisedb.atlassian.net/browse/XDB-1888)
[XDB-1885]: https://enterprisedb.atlassian.net/browse/XDB-1885?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[XDB-1889]: https://enterprisedb.atlassian.net/browse/XDB-1889?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[XDB-1888]: https://enterprisedb.atlassian.net/browse/XDB-1888?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> EPRS: 7.5 release

product_docs/docs/tde/15/index.mdx
Temporarily removing image that is causing the builds to fail. Will troubleshoot it later.
=> TDE: removing image that is causing the build to fail

product_docs/docs/odbc_connector/13/01_odbc_rel_notes/odbc_13.2.0.02_rel_notes.mdx, product_docs/docs/pem/9/pem_rel_notes/index.mdx, product_docs/docs/pge/15/installing/linux_x86_64/pge_debian_10.mdx, product_docs/docs/pge/15/installing/linux_x86_64/pge_debian_11.mdx, product_docs/docs/pge/15/installing/linux_x86_64/pge_ubuntu_18.mdx, product_docs/docs/pge/15/installing/linux_x86_64/pge_ubuntu_20.mdx, product_docs/docs/pge/15/release_notes/rel_notes15.2.mdx, product_docs/docs/tde/15/affected_commands.mdx, product_docs/docs/tde/15/enabling_tde.mdx, product_docs/docs/tde/15/images/tde1.png, product_docs/docs/tde/15/index.mdx, product_docs/docs/tde/15/pg_upgrade.mdx
Added TDE image back in
Fixed release date for PEM
Fixed EPAS version number in ODBC rel notes
PGE install topic changes and rel note addition
=> EPAS 15 release - misc fixes

product_docs/docs/odbc_connector/13/01_odbc_rel_notes/odbc_13.2.0.02_rel_notes.mdx, product_docs/docs/odbc_connector/13/installing/upgrading.mdx
Added a note to the release notes and the Upgrading topic
=> ODBC: Debian/Ubuntu upgrades

product_docs/docs/odbc_connector/13/01_odbc_rel_notes/odbc_13.2.0.02_rel_notes.mdx, product_docs/docs/odbc_connector/13/installing/upgrading.mdx
Updates for Debian/Ubuntu upgrade behavior on ODBC
=> Release: 2023-02-14b

product_docs/docs/postgres_for_kubernetes/1/rel_notes/index.mdx
Fixed link in Kubernetes rel notes
=> Release: 2023-02-14d

product_docs/docs/pgd/5/bdr/catalogs.mdx
- Added documentation related to `bdr.event_history` and
`bdr.event_summary`.
=> Docs: document the event history view

product_docs/docs/hadoop_data_adapter/2/02_requirements_overview.mdx, product_docs/docs/mongo_data_adapter/5/02_requirements_overview.mdx, product_docs/docs/mysql_data_adapter/2/02_requirements_overview.mdx
https://enterprisedb.atlassian.net/browse/FDW-587
=> FDW - fixed supported database and versions as per FDW-587

product_docs/docs/postgres_for_kubernetes/1/rel_notes/1_17_4_rel_notes.mdx, product_docs/docs/postgres_for_kubernetes/1/rel_notes/1_18_2_rel_notes.mdx, product_docs/docs/postgres_for_kubernetes/1/rel_notes/index.mdx
=> Kubernetes: added rel notes for 1.17.4 and 1.18.2

product_docs/docs/epas/11/epas_rel_notes/epas11_19_30_rel_notes.mdx, product_docs/docs/epas/11/epas_rel_notes/index.mdx, product_docs/docs/epas/12/epas_rel_notes/epas12_14_18_rel_notes.mdx, product_docs/docs/epas/12/epas_rel_notes/index.mdx, product_docs/docs/epas/13/epas_rel_notes/epas13_10_14_rel_notes.mdx, product_docs/docs/epas/13/epas_rel_notes/index.mdx, product_docs/docs/epas/14/epas_rel_notes/epas14_7_0_rel_notes.mdx, product_docs/docs/epas/14/epas_rel_notes/index.mdx
Release notes for EPAS v14.7.0, 13.10.14, 12.14.18, and 11.19.30
=> EPAS: v14.7.0, 13.10.14, 12.14.18, 11.19.30 release notes

advocacy_docs/pg_extensions/advanced_storage_pack/installing.mdx, advocacy_docs/pg_extensions/ldap_sync/installing.mdx, advocacy_docs/pg_extensions/pg_tuner/installing.mdx
Updated Installing docs with PGE information
=> Postgres Extensions: PGE updates

product_docs/docs/pgd/5/bdr/appusage.mdx
Please review document changes for Table Access methods.
=> Add document for Table access methods.

product_docs/docs/biganimal/release/overview/02_high_availability.mdx, product_docs/docs/biganimal/release/overview/05_database_version_policy.mdx
Updated EPAS and PGE versions to 15
https://enterprisedb.atlassian.net/browse/UPM-15349
=> BigAnimal: epas 15 updates

product_docs/docs/biganimal/release/reference/cli/connecting_to_clusters.mdx, product_docs/docs/biganimal/release/using_cluster/02_connecting_your_cluster/01_connecting_from_azure/index.mdx, product_docs/docs/biganimal/release/using_cluster/02_connecting_your_cluster/images/image3.png
Updating Azure private connectivity doc to refer the BigAnimal managed Private Link Service
Please wait merging this, needs to be merged when the BA release that includes https://enterprisedb.atlassian.net/browse/UPM-15557 gets delivered into Production.
=> fix(UPM-15559): update BigAnimal private cluster connectivity

product_docs/docs/pgd/5/durability/lag-control.mdx
Remove GUC variable references for configuration of Lag Control.
=> Document Lag Control configuration using commit scopes

product_docs/docs/biganimal/release/using_cluster/02_connecting_your_cluster/01_connecting_from_azure/index.mdx, product_docs/docs/biganimal/release/using_cluster/02_connecting_your_cluster/create_private_endpoint.png, product_docs/docs/biganimal/release/using_cluster/02_connecting_your_cluster/images/create_private_endpoint.png, product_docs/docs/biganimal/release/using_cluster/02_connecting_your_cluster/images/create_private_endpoint_resource.png, product_docs/docs/biganimal/release/using_cluster/02_connecting_your_cluster/images/create_private_endpoint_virtual_network.png
=> BigAnimal: corrections to Connecting from Azure topic

product_docs/docs/pgd/4/bdr/nodes.mdx, product_docs/docs/pgd/5/appusage.mdx, product_docs/docs/pgd/5/catalogs.mdx, product_docs/docs/pgd/5/configuration.mdx, product_docs/docs/pgd/5/ddl.mdx, product_docs/docs/pgd/5/durability/index.mdx, product_docs/docs/pgd/5/functions.mdx, product_docs/docs/pgd/5/nodes.mdx, product_docs/docs/pgd/5/repsets.mdx, product_docs/docs/pgd/5/scaling.mdx, product_docs/docs/pgd/5/security.mdx, product_docs/docs/pgd/5/sequences.mdx, product_docs/docs/pgd/5/striggers.mdx, product_docs/docs/pgd/5/transaction-streaming.mdx, product_docs/docs/pgd/5/tssnapshots.mdx, product_docs/docs/pgd/5/twophase.mdx, scripts/pdf/cleanup_combined_markdown.mjs, scripts/pdf/package-lock.json
=> PGD5 broken links and redirects

advocacy_docs/migrating/oracle/oracle_epas_comparison/app_devel_capabilities.mdx, advocacy_docs/migrating/oracle/oracle_epas_comparison/database_features.mdx, advocacy_docs/migrating/oracle/oracle_epas_comparison/notable_differences.mdx, advocacy_docs/migrating/oracle/oracle_epas_comparison/operational_capabilities.mdx
Updates of Oracle and EPAS comparison to account for new capabilities introduced in EPAS 15 and to make other corrections.
=> Docs/migration handbook/matt edits

product_docs/docs/biganimal/release/reference/api.mdx
Changed the starting string of refresh_token example to 'v1'. 
Background information in this slack chat https://edb-starlight.slack.com/archives/C02J6HXMH0F/p1677033253522169.
=> Kunliuedb patch 1

install_template/templates/platformBase/base.njk, install_template/templates/products/postgres-enterprise-manager-server/base.njk, product_docs/docs/pem/9/installing/linux_ppc64le/pem_rhel_8.mdx, product_docs/docs/pem/9/installing/linux_ppc64le/pem_sles_12.mdx, product_docs/docs/pem/9/installing/linux_ppc64le/pem_sles_15.mdx, product_docs/docs/pem/9/installing/linux_x86_64/pem_centos_7.mdx, product_docs/docs/pem/9/installing/linux_x86_64/pem_debian_10.mdx, product_docs/docs/pem/9/installing/linux_x86_64/pem_debian_11.mdx, product_docs/docs/pem/9/installing/linux_x86_64/pem_other_linux_8.mdx, product_docs/docs/pem/9/installing/linux_x86_64/pem_rhel_7.mdx, product_docs/docs/pem/9/installing/linux_x86_64/pem_rhel_8.mdx, product_docs/docs/pem/9/installing/linux_x86_64/pem_sles_12.mdx, product_docs/docs/pem/9/installing/linux_x86_64/pem_sles_15.mdx, product_docs/docs/pem/9/installing/linux_x86_64/pem_ubuntu_18.mdx, product_docs/docs/pem/9/installing/linux_x86_64/pem_ubuntu_20.mdx, product_docs/docs/pem/9/installing/prerequisites.mdx
Changes to templates to move first two items into templatized content
Mostly wordsmithing and formatting on the remaining prerequisites page
=> Restructure preqrequisites section for Linux install in PEM

src/pages/index.js
=> Featured content: EPAS 15 and new extensions

product_docs/docs/tpa/23/reference/INSTALL-docker.mdx, product_docs/docs/tpa/23/rel_notes/index.mdx, product_docs/docs/tpa/23/rel_notes/tpa_23.13_rel_notes.mdx
- Note on Docker invocation for ARM
- Release notes
=> TPA 23.13 release

product_docs/docs/pem/8/pem_online_help/01_toc_pem_getting_started/04_pem_roles.mdx, product_docs/docs/pem/9/pem_online_help/01_toc_pem_getting_started/04_pem_roles.mdx
Fixes https://github.com/EnterpriseDB/docs/issues/3637
=> PEM - roles fix

product_docs/docs/pgd/5/durability/commit-scopes.mdx, product_docs/docs/pgd/5/durability/index.mdx
=> Adjust GROUP COMMIT examples.

product_docs/docs/pgd/5/configuration.mdx, product_docs/docs/pgd/5/routing/index.mdx, product_docs/docs/pgd/5/routing/installing_proxy.mdx, product_docs/docs/pgd/5/routing/proxy.mdx
- fixed links
- typos
- restructure proxy page
=> Fix hyperlinks, typos, restructure some proxy info

product_docs/docs/tpa/23/rel_notes/index.mdx, product_docs/docs/tpa/23/rel_notes/tpa_23.14_rel_notes.mdx
=> TPA: 23.14 release

advocacy_docs/supported-open-source/barman/pg-backup-api/01-installation.mdx, product_docs/docs/biganimal/release/overview/02_high_availability.mdx, product_docs/docs/biganimal/release/using_cluster/05_monitoring_and_logging/other_monitoring/index.mdx, product_docs/docs/efm/4/06_monitoring_efm_cluster.mdx
- EFM: updates to Promote Status description
- BigAnimal: 
- EHA doesn't support epas 15
- Fixed broken link from Other monitoring methods topic
- Barman: fixes to install topic
=> Release: 2023-02-28

product_docs/docs/pgd/5/tpa/quick_start.mdx
=> PGD: typo in AWS quick start topic

advocacy_docs/pg_extensions/advanced_storage_pack/index.mdx, product_docs/docs/tpa/23/INSTALL.mdx, product_docs/docs/tpa/23/architecture-BDR-Always-ON.mdx, product_docs/docs/tpa/23/architecture-M1.mdx, product_docs/docs/tpa/23/architecture-PGD-Always-ON.mdx, product_docs/docs/tpa/23/misc-troubleshooting.mdx, product_docs/docs/tpa/23/reference/2q_and_edb_repositories.mdx, product_docs/docs/tpa/23/reference/barman.mdx, product_docs/docs/tpa/23/reference/bdr.mdx, product_docs/docs/tpa/23/reference/edb_repositories.mdx, product_docs/docs/tpa/23/reference/git-credentials.mdx
TPA updates
pgtuner postgres terminology update
=> Release: 2023-03-03

product_docs/docs/edb_plus/41/installing/windows.mdx
Rewrote the EDB*Plus procedure using the style developed for EPRS (no screen shots, different introductory material).
=> Edit of Windows install procedure for EDB*Plus

product_docs/docs/eprs/7/installing/windows.mdx
Removed the step asking for account registration information
=> Remove account registration step from EPRS

advocacy_docs/partner_docs/ChemaxonJChemPostgreSQLCartridge/04-Configuration.mdx
=> Minor change to Chemaxon guide

install_template/templates/products/migration-toolkit/base.njk, product_docs/docs/migration_toolkit/55/installing/linux_ppc64le/mtk_rhel_8.mdx, product_docs/docs/migration_toolkit/55/installing/linux_ppc64le/mtk_sles_12.mdx, product_docs/docs/migration_toolkit/55/installing/linux_ppc64le/mtk_sles_15.mdx, product_docs/docs/migration_toolkit/55/installing/linux_x86_64/mtk_centos_7.mdx, product_docs/docs/migration_toolkit/55/installing/linux_x86_64/mtk_debian_10.mdx, product_docs/docs/migration_toolkit/55/installing/linux_x86_64/mtk_debian_11.mdx, product_docs/docs/migration_toolkit/55/installing/linux_x86_64/mtk_other_linux_8.mdx, product_docs/docs/migration_toolkit/55/installing/linux_x86_64/mtk_rhel_7.mdx, product_docs/docs/migration_toolkit/55/installing/linux_x86_64/mtk_rhel_8.mdx, product_docs/docs/migration_toolkit/55/installing/linux_x86_64/mtk_sles_12.mdx, product_docs/docs/migration_toolkit/55/installing/linux_x86_64/mtk_sles_15.mdx, product_docs/docs/migration_toolkit/55/installing/linux_x86_64/mtk_ubuntu_18.mdx, product_docs/docs/migration_toolkit/55/installing/linux_x86_64/mtk_ubuntu_20.mdx
Changed template and generated files for Linux installs of MTK
=> Added Java prerequisite to Linux installs for MTK

src/pages/index.js
=> Homepage: What's new announcements for March 8

advocacy_docs/postgresql_journey/02_installing/03_linux.mdx, gatsby-config.js, product_docs/docs/biganimal/release/overview/03_security/compliance_and_certifications.mdx, product_docs/docs/biganimal/release/using_cluster/terraform_provider.mdx, product_docs/docs/epas/15/epas_compat_reference/02_the_sql_language/03_functions_and_operators/11_aggregate_functions.mdx, product_docs/docs/eprs/6.2/07_common_operations/11_using_ssl_connections.mdx, product_docs/docs/eprs/7/06_mmr_operation/06_conflict_resolution/09_manual_conflict_resolution_trigger_based_method/06_correction_using_shadow_table_txn.mdx, product_docs/docs/pem/8/pem_online_help/pem_worker_usage_guide.mdx, product_docs/docs/pem/9/pem_online_help/pem_worker_usage_guide.mdx, product_docs/docs/postgres_for_kubernetes/1/postgresql_conf.mdx
BigAnimal: PCI compliance
Doc infrastructure: more code block language updates
Replication Server: v6.2 SSL path note
=> Release: 2023-03-13

product_docs/docs/pgd/4/harp/04_configuration.mdx
Formatting fixes follow on from 3439 ticket.
=> HARP formatting fixes for defaults

src/components/main-content.js
=> Remove pgvision banner

product_docs/docs/postgres_for_kubernetes/1/installation_upgrade.mdx, product_docs/docs/postgres_for_kubernetes/1/monitoring.mdx, product_docs/docs/postgres_for_kubernetes/1/quickstart.mdx
Fixed paths for renamed repo
Deploying preview to check image rendering (as not working in local build)
=> Quickstart paths fixed

product_docs/docs/biganimal/release/overview/replication.mdx
The limitation in SEA doesn't exist anymore
Remove the region limitation since it's supported now.
=> The limitation in SEA doesn't exist anymore

advocacy_docs/supported-open-source/pgbackrest/index.mdx
Update latest pgBackRest release
=> pgBackRest 2.44 released

product_docs/docs/epas/15/epas_guide/03_database_administration/01_configuration_parameters/01_setting_new_parameters.mdx
https://enterprisedb.atlassian.net/browse/DB-1985
=> EPAS: ldap password hook typo in code sample

product_docs/docs/epas/15/epas_compat_spl/05_control_structures/09_pragma_exception_init.mdx
Fixed the typos and added missing keywords to correct the examples
=> EPAS 15 - Fixed the typo as per DF-315

product_docs/docs/eprs/7/05_smr_operation/01_prerequisites/04_preparing_pub_database.mdx
As per [XDB-1956](https://enterprisedb.atlassian.net/browse/XDB-1956)
[XDB-1956]: https://enterprisedb.atlassian.net/browse/XDB-1956?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Replication Server: SQL Server publication database code fix

product_docs/docs/tpa/23/architecture-BDR-Always-ON.mdx, product_docs/docs/tpa/23/architecture-M1.mdx, product_docs/docs/tpa/23/architecture-PGD-Always-ON.mdx, product_docs/docs/tpa/23/index.mdx, product_docs/docs/tpa/23/reference/pgd-proxy.mdx, product_docs/docs/tpa/23/tower.mdx, product_docs/docs/tpa/23/tpaexec-configure.mdx
Sync with TPA repo docs. See also: #3832
=> TPA 23.16 docs updates

product_docs/docs/pem/9/considerations/pem_pgbouncer/configuring_the_pem_agent.mdx, product_docs/docs/pem/9/registering_database_server.mdx
Added a note to the "Registering a Postgres server" in PEM docs based on the JIRA ticket
=> PEM-4565-Note on PEM agent-server binding

product_docs/docs/pgd/5/quickstart/quick_start_aws.mdx, product_docs/docs/pgd/5/quickstart/quick_start_docker.mdx, product_docs/docs/pgd/5/tpa.mdx
Missed a few places during yesterday's update.
=> PGD Quickstart link fixes, TPA option change

product_docs/docs/biganimal/release/using_cluster/01_postgres_access.mdx, product_docs/docs/biganimal/release/using_cluster/02_connecting_your_cluster/01_connecting_from_azure/index.mdx, product_docs/docs/efm/4/efm_deploy_arch/06_efm_pgpool.mdx, product_docs/docs/epas/15/epas_security_guide/02_protecting_against_sql_injection_attacks/01_sql_protect_overview.mdx, product_docs/docs/epas/15/installing/linux_install_details/managing_an_advanced_server_installation.mdx
Fixed broken links in:
- BigAnimal
- Failover Manager
- EPAS 15
=> Fixing broken links

product_docs/docs/pem/9/certificates/index.mdx, product_docs/docs/pem/9/considerations/pem_security_best_practices/pem_application_configuration.mdx, product_docs/docs/pem/9/pem_architecture.mdx
Updated SQL Profiler descriptions in architecture topic
Fixed broken links related to SQL Profiler and SSL certificate updates
=> PEM: SQL Provider clean up and fixing links

product_docs/docs/epas/15/epas_compat_spl/10_collections/02_nested_tables.mdx
=> Small link fix to correctly nav to the SQL guide

install_template/templates/products/edb*plus/base.njk, product_docs/docs/edb_plus/41/installing/linux_ppc64le/edbplus_rhel_8.mdx, product_docs/docs/edb_plus/41/installing/linux_ppc64le/edbplus_sles_12.mdx, product_docs/docs/edb_plus/41/installing/linux_ppc64le/edbplus_sles_15.mdx, product_docs/docs/edb_plus/41/installing/linux_x86_64/edbplus_centos_7.mdx, product_docs/docs/edb_plus/41/installing/linux_x86_64/edbplus_debian_10.mdx, product_docs/docs/edb_plus/41/installing/linux_x86_64/edbplus_debian_11.mdx, product_docs/docs/edb_plus/41/installing/linux_x86_64/edbplus_other_linux_8.mdx, product_docs/docs/edb_plus/41/installing/linux_x86_64/edbplus_rhel_7.mdx, product_docs/docs/edb_plus/41/installing/linux_x86_64/edbplus_rhel_8.mdx, product_docs/docs/edb_plus/41/installing/linux_x86_64/edbplus_sles_12.mdx, product_docs/docs/edb_plus/41/installing/linux_x86_64/edbplus_sles_15.mdx, product_docs/docs/edb_plus/41/installing/linux_x86_64/edbplus_ubuntu_18.mdx, product_docs/docs/edb_plus/41/installing/linux_x86_64/edbplus_ubuntu_20.mdx
https://enterprisedb.atlassian.net/browse/ED-210
=> EDB*Plus: removed java prereq

product_docs/docs/epas/15/epas_compat_ora_dev_guide/index.mdx
Updated the first sentence of the Oracle compat section
=> EPAS: improved wording in intro of Oracle compat section

product_docs/docs/pgd/4/rel_notes/pgd_4.3.0_rel_notes.mdx
Add release note entry for HARP dependencies upgrade
=> BDR-3342 - Add release note entry for HARP dependencies upgrade

gatsby-config.js
=> Cache breaker

product_docs/docs/biganimal/release/getting_started/creating_a_cluster/index.mdx
=> BigAnimal: softening maintenance window note

advocacy_docs/supported-open-source/postgresql/installer/05_uninstalling_postgresql.mdx, advocacy_docs/supported-open-source/postgresql/installer/images/mac_uninstallation_completed.png, advocacy_docs/supported-open-source/postgresql/installer/images/uninstallation_completed.png
Fixed reference to screenshot, then fixed screenshot
=> Fixed mac screenie, updated screenshot

product_docs/docs/epas/15/epas_compat_sql/65a_merge.mdx
https://github.com/EnterpriseDB/docs/issues/3735
Updated the content as per comments from Triveni.
=> EPAS 15 - Merge statement

advocacy_docs/pg_extensions/pg_failover_slots/configuring.mdx, advocacy_docs/pg_extensions/pg_failover_slots/index.mdx, advocacy_docs/pg_extensions/pg_failover_slots/installing.mdx, advocacy_docs/pg_extensions/pg_failover_slots/rel_notes/index.mdx, advocacy_docs/pg_extensions/pg_failover_slots/rel_notes/pg_failover_slots_1.0.0_rel_notes.mdx, advocacy_docs/pg_extensions/pg_failover_slots/using.mdx, src/pages/index.js
https://enterprisedb.atlassian.net/browse/EXT-192
Source material: https://github.com/EnterpriseDB/edb_failover_slots#readme
=> EDB Failover Slots: first release

product_docs/docs/biganimal/release/administering_cluster/01_portal_access.mdx, product_docs/docs/biganimal/release/administering_cluster/01a_superset_access.mdx, product_docs/docs/biganimal/release/administering_cluster/03_account_activity.mdx, product_docs/docs/biganimal/release/administering_cluster/customizing_compliance/aws_config_rules.mdx, product_docs/docs/biganimal/release/administering_cluster/customizing_compliance/azure_policy_definitions.mdx, product_docs/docs/biganimal/release/administering_cluster/projects.mdx, product_docs/docs/biganimal/release/free_trial/detail/connect_to_a_cluster/connect_using_dbeaver.mdx, product_docs/docs/biganimal/release/free_trial/detail/connect_to_a_cluster/connect_using_pgadmin.mdx, product_docs/docs/biganimal/release/free_trial/detail/connect_to_a_cluster/connect_using_psql.mdx, product_docs/docs/biganimal/release/free_trial/detail/connect_to_a_cluster/index.mdx, product_docs/docs/biganimal/release/free_trial/detail/create_a_cluster/create_cluster_cli.mdx, product_docs/docs/biganimal/release/free_trial/detail/create_a_cluster/create_cluster_portal.mdx, product_docs/docs/biganimal/release/free_trial/detail/create_a_cluster/index.mdx, product_docs/docs/biganimal/release/free_trial/detail/create_an_account/index.mdx, product_docs/docs/biganimal/release/free_trial/detail/experiment/backup_and_restore.mdx, product_docs/docs/biganimal/release/free_trial/detail/experiment/import_data.mdx, product_docs/docs/biganimal/release/free_trial/detail/experiment/index.mdx, product_docs/docs/biganimal/release/free_trial/detail/index.mdx, product_docs/docs/biganimal/release/free_trial/index.mdx, product_docs/docs/biganimal/release/free_trial/quickstart.mdx
Includes free trial text. Keeping casual tone there, but edited some idioms that might not translate to non-native English speakers.
=> First chunk of biganimal edits

install_template/config.yaml, product_docs/docs/ocl_connector/14.1.0.1/installing/index.mdx, product_docs/docs/ocl_connector/14.1.0.1/installing/linux_ppc64le/index.mdx, product_docs/docs/ocl_connector/14.1.0.1/installing/linux_x86_64/index.mdx
Added 14.1.0.1 back into config.yaml
generated new index files
=> OCL: install template updates

product_docs/docs/pgd/5/cli/command_ref/index.mdx
If this content is generated the fix needs to be made in the source
=> PGD: CLI typo

product_docs/docs/pgbouncer/1/installing/windows.mdx
Updated Windows install procedure to make it consistent with other Windows installation procedures. This update removes screen shots.
=> Revised Windows install procedure for PgBouncer

product_docs/docs/jdbc_connector/42.5.4.1/installing/windows.mdx, product_docs/docs/ocl_connector/15.2.0.1/installing/windows.mdx, product_docs/docs/odbc_connector/13/installing/windows.mdx
Simplified and standardized procedure for Windows install for JDBC, OCI, and ODBC
=> Revised Windows install procedure for Connectors

product_docs/docs/biganimal/release/getting_started/02_connecting_to_your_cloud/connecting_aws.mdx, product_docs/docs/biganimal/release/getting_started/02_connecting_to_your_cloud/connecting_azure.mdx, product_docs/docs/biganimal/release/getting_started/02_connecting_to_your_cloud/index.mdx, product_docs/docs/biganimal/release/getting_started/creating_a_cluster/01_cluster_networking.mdx, product_docs/docs/biganimal/release/getting_started/creating_a_cluster/index.mdx, product_docs/docs/biganimal/release/getting_started/identity_provider/auth0.mdx, product_docs/docs/biganimal/release/getting_started/identity_provider/aws_sso.mdx, product_docs/docs/biganimal/release/getting_started/identity_provider/azure_ad.mdx, product_docs/docs/biganimal/release/getting_started/identity_provider/google.mdx, product_docs/docs/biganimal/release/getting_started/identity_provider/index.mdx, product_docs/docs/biganimal/release/getting_started/identity_provider/okta.mdx, product_docs/docs/biganimal/release/using_cluster/03_modifying_your_cluster/index.mdx
Light edits to getting started section.
=> Next chunk of BigAnimal edits from getting started section

product_docs/docs/biganimal/release/overview/03a_region_support.mdx
=> BigAnimal: regions typo

product_docs/docs/biganimal/release/using_cluster/terraform_provider.mdx
=> BigAnimal: Terraform provider v4

product_docs/docs/biganimal/release/getting_started/00_free_trial.mdx, product_docs/docs/biganimal/release/getting_started/02_azure_market_setup.mdx, product_docs/docs/biganimal/release/getting_started/activating_regions.mdx, product_docs/docs/biganimal/release/getting_started/index.mdx, product_docs/docs/biganimal/release/migration/cold_migration.mdx, product_docs/docs/biganimal/release/migration/index.mdx, product_docs/docs/biganimal/release/overview/02_high_availability.mdx, product_docs/docs/biganimal/release/overview/03_security/compliance_and_certifications.mdx, product_docs/docs/biganimal/release/overview/03_security/index.mdx, product_docs/docs/biganimal/release/overview/03a_region_support.mdx, product_docs/docs/biganimal/release/overview/04_responsibility_model.mdx, product_docs/docs/biganimal/release/overview/05_database_version_policy.mdx, product_docs/docs/biganimal/release/overview/extensions_tools.mdx, product_docs/docs/biganimal/release/overview/replication.mdx, product_docs/docs/biganimal/release/overview/support/01_case_management.mdx, product_docs/docs/biganimal/release/overview/support/index.mdx, product_docs/docs/biganimal/release/overview/updates.mdx, product_docs/docs/biganimal/release/pricing_and_billing/index.mdx, product_docs/docs/biganimal/release/reference/cli/index.mdx, product_docs/docs/biganimal/release/reference/cli/managing_clusters.mdx, product_docs/docs/biganimal/release/reference/cli/using_features.mdx
=> First pass through this batch of BigAnimal topics

product_docs/docs/pgd/5/quickstart/index.mdx
Reapplied the edit in this [PR](https://github.com/EnterpriseDB/docs/pull/3902), which got inadvertently wiped out in a merge.
=> PGD: edit redo

product_docs/docs/pgd/5/quickstart/index.mdx, product_docs/docs/pgd/5/quickstart/quick_start_aws.mdx, product_docs/docs/pgd/5/quickstart/quick_start_docker.mdx
wrong host names in a command
wrong config in the index and aws for the examples
=> First pass errata

product_docs/docs/tde/15/enabling_tde.mdx
Found a few spelling and syntax errors while going through the doc today.
=> Update Enabling TDE.mdx

product_docs/docs/biganimal/release/index.mdx, product_docs/docs/biganimal/release/knowledge_base.mdx
https://github.com/EnterpriseDB/docs/issues/3810
Implemented the MVP for adding a knowledge base topic to BigAnimal.
=> BigAnimal: adding a KB topic

product_docs/docs/biganimal/release/knowledge_base.mdx, product_docs/docs/biganimal/release/reference/cli/using_features.mdx
=> BigAnimal: FAQ topic title, broken link

advocacy_docs/pg_extensions/pg_failover_slots/index.mdx
Updates based on the Release Announcement text.
=> Failover Slots: landing page updates

product_docs/docs/biganimal/release/using_cluster/05_monitoring_and_logging/index.mdx
added links to SQL Profiler and Index Advisor topics in the PEM docs
=> BigAnimal: Q1 PEM features

src/pages/index.js
=> Failover Slots: fixed name on home page

advocacy_docs/partner_docs/NutanixAHV/02-PartnerInformation.mdx, advocacy_docs/partner_docs/NutanixAHV/03-SolutionSummary.mdx, advocacy_docs/partner_docs/NutanixAHV/04-ConfiguringNutanixAHV.mdx, advocacy_docs/partner_docs/NutanixAHV/05-UsingNutanixAHV.mdx, advocacy_docs/partner_docs/NutanixAHV/06-CertificationEnvironment.mdx, advocacy_docs/partner_docs/NutanixAHV/07-Appendix.mdx, advocacy_docs/partner_docs/NutanixAHV/07-Support.mdx, advocacy_docs/partner_docs/NutanixAHV/Images/CreateaVM2.png, advocacy_docs/partner_docs/NutanixAHV/Images/SampleDeployment.png, advocacy_docs/partner_docs/NutanixAHV/Images/VMConfiguration2.png, advocacy_docs/partner_docs/NutanixAHV/index.mdx, advocacy_docs/pg_extensions/pg_failover_slots/index.mdx, product_docs/docs/biganimal/release/using_cluster/05_monitoring_and_logging/index.mdx, product_docs/docs/pgd/5/routing/proxy.mdx, src/pages/index.js
- BigAnimal: Q1 PEM features
- Nutanix partner doc updates
- PGD: proxy clarification
- PG Failover Slots: fixed product name and updated landing page text
=> Release: 2023-04-17

src/pages/index.js
Updated the featured docs tabs in the EDB Docs home page to highlight the updated PEM SSL topics and the new PG Failover Slots extension
See https://deploy-preview-3938--edb-docs-staging.netlify.app/docs/.
=> What's New: PEM SSL topics and PG Failover Slots

product_docs/docs/biganimal/release/getting_started/creating_a_cluster/index.mdx
=> BigAnimal: users can now set Ultra Disk throughput

product_docs/docs/edb_plus/41/02_release_notes/edbplus_41.1_rel_notes.mdx, product_docs/docs/edb_plus/41/02_release_notes/index.mdx, product_docs/docs/edb_plus/41/06_command_summary.mdx
Changes as part of the v41.1.0 release are as follows:
- [ED-244](https://enterprisedb.atlassian.net/browse/ED-244)
- [ED-246](https://enterprisedb.atlassian.net/browse/ED-246)
[ED-244]: https://enterprisedb.atlassian.net/browse/ED-244?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[ED-246]: https://enterprisedb.atlassian.net/browse/ED-246?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> EDB*Plus: v41.1.0 release

src/pages/access-denied.js, static/_redirects
=> Need to restrict access to countries under sanction

product_docs/docs/pem/9/index.mdx
Updated the version number, fixed capitalization, and changed to generic Postgres terminology
=> PEM: updated version number in front matter description

product_docs/docs/biganimal/release/getting_started/creating_a_cluster/creating_an_eha_cluster.mdx, product_docs/docs/biganimal/release/overview/updates.mdx
Added info about Maintenance Windows being separate and un-overlapping for each data group
=> BigAnimal: Maintenance window info for EHA

src/pages/index.js
Used wording from BA release notes announcing multi-region EHA release
=> BigAnimal: Featured content - Multi-region EHA preview

product_docs/docs/pgd/5/known_issues.mdx
Added known issue to pgd docs for bdr-3462
=> Added known issue for bdr-3462

product_docs/docs/biganimal/release/overview/02_high_availability.mdx
Added back a rewritten HARP description
=> BigAnimal: add PGD Proxy info

product_docs/docs/biganimal/release/overview/02_high_availability.mdx
=> BigAnimal: added link to PGD docs from PGD Proxy para

product_docs/docs/biganimal/release/knowledge_base.mdx, product_docs/docs/biganimal/release/using_cluster/01_postgres_access.mdx, product_docs/docs/biganimal/release/using_cluster/04_backup_and_restore.mdx, product_docs/docs/biganimal/release/using_cluster/05a_deleting_your_cluster.mdx, product_docs/docs/biganimal/release/using_cluster/06_analyze_with_superset.mdx, product_docs/docs/biganimal/release/using_cluster/06_demonstration_oracle_compatibility.mdx, product_docs/docs/biganimal/release/using_cluster/managing_replicas.mdx, product_docs/docs/biganimal/release/using_cluster/terraform_provider.mdx
=> Rest of edits to BigAnimal

product_docs/docs/eprs/7/07_common_operations/10_replicating_postgres_partitioned_tables.mdx
=> Replication Server: fixed capitalization

product_docs/docs/biganimal/release/free_trial/detail/create_a_cluster/create_cluster_cli.mdx, product_docs/docs/biganimal/release/free_trial/detail/create_a_cluster/create_cluster_portal.mdx, product_docs/docs/biganimal/release/free_trial/detail/create_a_cluster/index.mdx, product_docs/docs/biganimal/release/free_trial/detail/experiment/backup_and_restore.mdx, product_docs/docs/biganimal/release/free_trial/detail/experiment/import_data.mdx, product_docs/docs/biganimal/release/free_trial/detail/experiment/index.mdx
Updating the Free Trial Going Deeper section for Postgres 15
=> BigAnimal: Free Trial Going Deeper Postgres 15 updates

product_docs/docs/pge/15/index.mdx
Fixes https://github.com/EnterpriseDB/docs/issues/4001
=> PGE: stronger language on the landing page

product_docs/docs/tpa/23/INSTALL.mdx
Noticed two back quotes had got into the added title (and weren't showing on some previews). Removed for clarity.
=> Fix on fix for INSTALL.mdx

product_docs/docs/pem/9/certificates/index.mdx
@sonotley noticed the admonition at the end leaked through and revealed a frontmatter block - added in a closing fence to the admonition.
=> Update index.mdx - add fencing

advocacy_docs/pg_extensions/pg_failover_slots/installing.mdx
Updated the docs to mention v11 as we have added support for this version.
=> Support has been added for v11

advocacy_docs/migrating/oracle/oracle_epas_comparison/database_features.mdx, advocacy_docs/pg_extensions/pg_failover_slots/installing.mdx, product_docs/docs/pem/9/certificates/index.mdx, product_docs/docs/pgd/5/quickstart/index.mdx, product_docs/docs/pgd/5/quickstart/quick_start_cloud.mdx, product_docs/docs/pge/15/index.mdx, product_docs/docs/tpa/23/INSTALL.mdx
- PGD: new cloud quick start topic
- PG Failover Slots: added v11 support
- Migration Handbook: global indexes support 
- PGE: updated language on the landing page
=> Release: 2023-05-05

product_docs/docs/biganimal/release/knowledge_base.mdx, product_docs/docs/biganimal/release/migration/index.mdx
Adding links to the EPAS docs and the KB articles
=> BigAnimal: linking to Oracles dbs

product_docs/docs/biganimal/release/free_trial/detail/create_a_cluster/create_cluster_portal.mdx
link worked in online content, but not in the PDF
=> BigAnimal: fixed link reported by PDF link checker

advocacy_docs/supported-open-source/pglogical2/requirements.mdx
Will also want to update the source readme: https://github.com/2ndQuadrant/pglogical/pull/421
Fixes #4026
=> Link directly to "Limitations and restrictions" section

product_docs/docs/pgd/5/index.mdx
=> Too many m's

product_docs/docs/tpa/23/rel_notes/index.mdx, product_docs/docs/tpa/23/rel_notes/tpa_23.17_rel_notes.mdx
=> Add release notes for TPA 23.17

product_docs/docs/pgd/5/quickstart/quick_start_aws.mdx, product_docs/docs/pgd/5/quickstart/quick_start_docker.mdx, product_docs/docs/pgd/5/quickstart/quick_start_linux.mdx, product_docs/docs/pgd/5/tpa.mdx
Quickstart entries for --active-locations removed, added --pgd-proxy-routing, adjusted some other docs similarly.
=> Changes quickstart for 23.17 --pgd-proxy-routing

product_docs/docs/tde/15/enabling_tde.mdx
=> Update broken link on enabling_tde.mdx

product_docs/docs/tpa/23/INSTALL.mdx, product_docs/docs/tpa/23/architecture-BDR-Always-ON.mdx, product_docs/docs/tpa/23/architecture-M1.mdx, product_docs/docs/tpa/23/architecture-PGD-Always-ON.mdx, product_docs/docs/tpa/23/configure-instance.mdx, product_docs/docs/tpa/23/configure-source.mdx, product_docs/docs/tpa/23/index.mdx, product_docs/docs/tpa/23/misc-troubleshooting.mdx, product_docs/docs/tpa/23/platform-aws.mdx, product_docs/docs/tpa/23/platform-bare.mdx, product_docs/docs/tpa/23/reference/air-gapped.mdx, product_docs/docs/tpa/23/reference/bdr.mdx, product_docs/docs/tpa/23/reference/distributions.mdx, product_docs/docs/tpa/23/reference/harp.mdx, product_docs/docs/tpa/23/reference/local-repo.mdx, product_docs/docs/tpa/23/reference/locale.mdx, product_docs/docs/tpa/23/reference/pgd-proxy.mdx, product_docs/docs/tpa/23/reference/pglogical.mdx, product_docs/docs/tpa/23/reference/repmgr.mdx, product_docs/docs/tpa/23/reference/tpaexec-support.mdx, product_docs/docs/tpa/23/reference/yum_repositories.mdx, product_docs/docs/tpa/23/tpaexec-configure.mdx, product_docs/docs/tpa/23/tpaexec-hooks.mdx, product_docs/docs/tpa/23/tpaexec-server-pool.mdx, product_docs/docs/tpa/23/tpaexec-switchover.mdx, product_docs/docs/tpa/23/tpaexec-update-postgres.mdx
Import from tpaexec docs. Many changes...
=> Import TPA 23.17 Updates

product_docs/docs/mysql_data_adapter/2/02_requirements_overview.mdx
=> MySQL FDW: Platform Support Updates

build-sources.json, gatsby-config.js, product_docs/docs/postgres_distributed_for_kubernetes/1/api_reference.mdx, product_docs/docs/postgres_distributed_for_kubernetes/1/architecture.mdx, product_docs/docs/postgres_distributed_for_kubernetes/1/connectivity.mdx, product_docs/docs/postgres_distributed_for_kubernetes/1/images/openshift/all-namespaces.png, product_docs/docs/postgres_distributed_for_kubernetes/1/images/openshift/find-pgd-openshift.png, product_docs/docs/postgres_distributed_for_kubernetes/1/images/openshift/operatorhub_1.png, product_docs/docs/postgres_distributed_for_kubernetes/1/images/pg4k-pgd-basic-architecture.png, product_docs/docs/postgres_distributed_for_kubernetes/1/index.mdx, product_docs/docs/postgres_distributed_for_kubernetes/1/installation_upgrade.mdx, product_docs/docs/postgres_distributed_for_kubernetes/1/quickstart.mdx, product_docs/docs/postgres_distributed_for_kubernetes/1/rel_notes/0_6_rel_notes.mdx, product_docs/docs/postgres_distributed_for_kubernetes/1/rel_notes/index.mdx, product_docs/docs/postgres_distributed_for_kubernetes/1/samples.mdx, product_docs/docs/postgres_distributed_for_kubernetes/1/samples/flexible_3regions.yaml, product_docs/docs/postgres_distributed_for_kubernetes/1/samples/flexible_cleanup.yaml, scripts/source/dispatch_product.py, scripts/source/process-pgd4k-docs.sh, src/constants/products.js, src/templates/doc.js
Initial content import
Preview: https://deploy-preview-4074--edb-docs-staging.netlify.app/postgres_distributed_for_kubernetes/latest/
=> Postgres Distributed for Kubernetes preview release 0.6

product_docs/docs/pgd/4/rel_notes/pgd_4.3.1_rel_notes.mdx
* Add CLI 1.1.1 release notes
* Add HARP 2.2.3 release notes
* Add BDR Utilities 1.1.0 release notes
=> PGD 4.3.1 release notes for CLI, HARP and BDR Utilities

product_docs/docs/tde/15/key_stores.mdx
Fixes https://github.com/EnterpriseDB/docs/issues/4060
=> TDE: update option

product_docs/docs/pgd/4/rel_notes/index.mdx, product_docs/docs/pgd/4/rel_notes/pgd_4.3.1_rel_notes.mdx
=> Add 4.3.1 release notes

product_docs/docs/pgd/3.7/bdr/release-notes.mdx, product_docs/docs/pgd/3.7/harp/01_release_notes/harp2.2.3_rel_notes.mdx, product_docs/docs/pgd/3.7/harp/01_release_notes/index.mdx, product_docs/docs/pgd/3.7/pglogical/release-notes.mdx
=> Add 3.7.21 release notes

product_docs/docs/postgres_for_kubernetes/1/openshift.mdx
Mis-named product inside note section
=> Update openshift.mdx to correct mis-naming

product_docs/docs/tde/15/key_stores.mdx
=> TDE: fixed encryption method

product_docs/docs/tpa/23/reference/distributions.mdx
=> Fix reference TPA path

product_docs/docs/biganimal/release/pricing_and_billing/index.mdx
Addresses feedback from the CSAs
=> BigAnimal: additional PgBouncer pricing info

product_docs/docs/pgd/5/rel_notes/pgd_5.1.0_rel_notes.mdx
* Add rel notes for CLI 5.1.0
* Add rel notes for Proxy 5.1.0
* Add rel notes for Utilities 1.1.0
=> v5.1.0 rel notes for CLI, Proxy and Utilities

product_docs/docs/biganimal/release/pricing_and_billing/index.mdx
=> BigAnimal: correct instance types for PgBouncer

product_docs/docs/pgd/5/nodes.mdx
=> Update nodes.mdx on PGD docs

gatsby-node.js, product_docs/docs/biganimal/release/index.mdx, src/components/side-navigation.js, src/templates/doc.js
Adds
hideKBLink: 
as a front matter option.
When set to true, will omit the KB footnote from the headers.
=> Simple KB excluder

product_docs/docs/pgd/5/rel_notes/index.mdx, product_docs/docs/pgd/5/rel_notes/pgd_5.1.0_rel_notes.mdx
=> Add 5.1.0 release notes

product_docs/docs/pgd/5/nodes.mdx
=> PGD 5.1: Add bdr.drop_node_group docs

product_docs/docs/biganimal/release/overview/replication.mdx, product_docs/docs/biganimal/release/using_cluster/04_backup_and_restore.mdx
=> BigAnimal: faraway clusters replication lag

product_docs/docs/pge/15/release_notes/index.mdx, product_docs/docs/pge/15/release_notes/rel_notes15.3.mdx
=> PGE: 15.3 rel notes

product_docs/docs/tpa/23/rel_notes/index.mdx, product_docs/docs/tpa/23/rel_notes/tpa_23.18_rel_notes.mdx
=> Release notes for TPA 23.18

product_docs/docs/pgd/5/rel_notes/pgd_5.1.0_rel_notes.mdx, product_docs/docs/tpa/23/architecture-M1.mdx, product_docs/docs/tpa/23/platform-aws.mdx, product_docs/docs/tpa/23/platform-docker.mdx, product_docs/docs/tpa/23/reference/2q_and_edb_repositories.mdx, product_docs/docs/tpa/23/reference/distributions.mdx, product_docs/docs/tpa/23/reference/edb_repositories.mdx, product_docs/docs/tpa/23/reference/efm.mdx, product_docs/docs/tpa/23/reference/local-repo.mdx, product_docs/docs/tpa/23/reference/packages.mdx, product_docs/docs/tpa/23/reference/postgres_installation_method_pkg.mdx, product_docs/docs/tpa/23/reference/tpa_2q_repositories.mdx, product_docs/docs/tpa/23/tpaexec-configure.mdx
Release Notes (Highlights and order and labelling)
More to follow.
=> 5.1 Release Party Here

product_docs/docs/biganimal/release/overview/replication.mdx, product_docs/docs/biganimal/release/using_cluster/04_backup_and_restore.mdx, product_docs/docs/pgd/5/rel_notes/pgd_5.1.0_rel_notes.mdx, product_docs/docs/pge/15/release_notes/index.mdx, product_docs/docs/pge/15/release_notes/rel_notes15.3.mdx, product_docs/docs/tpa/23/architecture-M1.mdx, product_docs/docs/tpa/23/platform-aws.mdx, product_docs/docs/tpa/23/platform-docker.mdx, product_docs/docs/tpa/23/reference/2q_and_edb_repositories.mdx, product_docs/docs/tpa/23/reference/distributions.mdx, product_docs/docs/tpa/23/reference/edb_repositories.mdx, product_docs/docs/tpa/23/reference/efm.mdx, product_docs/docs/tpa/23/reference/local-repo.mdx, product_docs/docs/tpa/23/reference/packages.mdx, product_docs/docs/tpa/23/reference/postgres_installation_method_pkg.mdx, product_docs/docs/tpa/23/reference/tpa_2q_repositories.mdx, product_docs/docs/tpa/23/rel_notes/index.mdx, product_docs/docs/tpa/23/rel_notes/tpa_23.18_rel_notes.mdx, product_docs/docs/tpa/23/tpaexec-configure.mdx
- PGD 5.3 release
- TPA release 23.18
- BigAnimal: Updates to replica lag description
=> Release: 2023-05-23

product_docs/docs/pem/9/pem_rel_notes/920_rel_notes.mdx, product_docs/docs/pem/9/pem_rel_notes/index.mdx
Added first draft of PEM 9.2 release notes
=> PEM - 9.2 Release branch

product_docs/docs/biganimal/release/overview/replication.mdx, product_docs/docs/pgd/5/routing/proxy.mdx
=> Fixing links in BigAnimal and PGD

product_docs/docs/biganimal/release/overview/replication.mdx, product_docs/docs/pem/9/pem_rel_notes/920_rel_notes.mdx, product_docs/docs/pem/9/pem_rel_notes/index.mdx, product_docs/docs/pgd/5/routing/proxy.mdx, product_docs/docs/tpa/23/rel_notes/index.mdx
- Fixed links in TPA rel note, BigAnimal, and PGD
- PEM 9.2 release
=> Release: 2023-05-24

product_docs/docs/biganimal/release/free_trial/detail/create_a_cluster/create_cluster_cli.mdx
Fixes https://github.com/EnterpriseDB/docs/issues/4128
=> BigAnimal: remove typo in CLI topic in Free trial section

product_docs/docs/biganimal/release/overview/03a_region_support/index.mdx
added region with note that it needs to be enabled on AWS first
See  https://edb-starlight.slack.com/archives/C056GEQSL3T/p1685001868465349?thread_ts=1684995199.381619&cid=C056GEQSL3T
=> BigAnimal: ap-southeast-3 region

product_docs/docs/biganimal/release/free_trial/detail/create_a_cluster/create_cluster_cli.mdx, product_docs/docs/biganimal/release/overview/03a_region_support/index.mdx, product_docs/docs/tde/15/key_stores.mdx, product_docs/docs/tpa/23/rel_notes/tpa_23.14_rel_notes.mdx
- BigAnimal: 
- new AWS region
- removed sentence fragment in Free trial section
- added TPA rel note
- TDE: fixed code issue
=> Release: 2023-05-26

product_docs/docs/biganimal/release/getting_started/activating_regions.mdx, product_docs/docs/biganimal/release/overview/03a_region_support/index.mdx
[UPM-20329](https://enterprisedb.atlassian.net/browse/UPM-20329) - updated Preparing your cloud changes are reflected in this branch but the changes were made in this [commit](https://github.com/EnterpriseDB/docs/pull/4146/commits/cab88ff35324a1009fc093a3986a5cf6da98f448) to the main [BigAnimal: Digital Self-Service & BigAnimal-Hosted PR](https://github.com/EnterpriseDB/docs/pull/4146)
[UPM-20327](https://enterprisedb.atlassian.net/browse/UPM-20327)
[UPM-20329]: https://enterprisedb.atlassian.net/browse/UPM-20329?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[UPM-20327]: https://enterprisedb.atlassian.net/browse/UPM-20327?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> BigAnimal: BAH regions

advocacy_docs/supported-open-source/patroni/cluster_management.mdx, advocacy_docs/supported-open-source/patroni/debian11_quick_start.mdx, advocacy_docs/supported-open-source/patroni/installing_etcd.mdx, advocacy_docs/supported-open-source/patroni/installing_patroni.mdx, advocacy_docs/supported-open-source/patroni/rhel8_quick_start.mdx, advocacy_docs/supported-open-source/patroni/tips.mdx
Clarified edit related to listening on ports
Removed prompt from code blocks so that the contents can be copied and pasted in a terminal and work
=> Patroni: correction from copy edit - code block adjustments

advocacy_docs/pg_extensions/pg_tuner/using.mdx
Added recommendation entries for the dynamic entries in the table - values are based on a cursory review of the source.
Would this be something that @eulerto could review for accuracy?
=> Adjusted for more detail on recommendations

product_docs/docs/biganimal/release/overview/03a_region_support/index.mdx
=> BigAnimal: AWS ap-south-2 region

src/pages/index.js
=> What's new tab fix

product_docs/docs/pgd/5/scaling.mdx, product_docs/docs/tpa/23/architecture-M1.mdx, scripts/source/tpaexec.js, src/pages/index.js
- Fixed title and links on PGD quick start What's new tab on the home page
- TPA update
=> Release: 2023-06-02

product_docs/docs/biganimal/release/overview/extensions_tools.mdx, product_docs/docs/biganimal/release/overview/foreign_data_wrappers.mdx, product_docs/docs/biganimal/release/overview/index.mdx, product_docs/docs/biganimal/release/overview/poolers.mdx
Moved poolers and FDWs topics to their own topics with links to them from the Postgres extensions and tools topic
=> BigAnimal: giving poolers more visibility

product_docs/docs/biganimal/release/overview/03a_region_support/index.mdx
=> BigAnimal: fixed Supported AWS region typo

product_docs/docs/pem/9/pem_rel_notes/920_rel_notes.mdx
=> Cleanup of release notes for PEM 9.2 release

product_docs/docs/pgd/5/durability/commit-scopes.mdx
=> More corrections to missing articles

product_docs/docs/biganimal/release/administering_cluster/01_portal_access.mdx, product_docs/docs/biganimal/release/getting_started/identity_provider/index.mdx, product_docs/docs/biganimal/release/pricing_and_billing/index.mdx, product_docs/docs/biganimal/release/using_cluster/01_postgres_access.mdx
Replaces https://github.com/EnterpriseDB/docs/pull/3920. The changes from #3920 are available in this branch.
Changes as per [UPM-17325](https://enterprisedb.atlassian.net/browse/UPM-17325)
[UPM-17325]: https://enterprisedb.atlassian.net/browse/UPM-17325?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> BigAnimal: Idp changes for DSS/BAH

product_docs/docs/biganimal/release/getting_started/creating_a_cluster/index.mdx
=> BigAnimal: fixed PgBouncer link

product_docs/docs/epas/15/epas_guide/13_performance_analysis_and_tuning.mdx
https://enterprisedb.atlassian.net/browse/DF-340
=> EPAS: update wait states package name

advocacy_docs/supported-open-source/barman/single-server-streaming/step01-db-setup.mdx
Added inline content to address #2090 so is clear when loooking at data what the data is.
=> Clarifying comments inline added

product_docs/docs/hadoop_data_adapter/2/02_requirements_overview.mdx, product_docs/docs/mongo_data_adapter/5/02_requirements_overview.mdx
Updated supported platform topics for Mongo and Hadoop Foreign data wrappers.
https://enterprisedb.atlassian.net/browse/DF-338
=> FDWs: updated supported platforms topics

product_docs/docs/pgd/4/harp/09_consensus-layer.mdx, product_docs/docs/pgd/4/harp/images/HARPsequencediagram.png
BDR 4 additional content for consensus layer with sequence diagram
=> Docs/fix/bdr4split - Adding BDR4 content by request

product_docs/docs/pgd/5/upgrades/bdr_pg_upgrade.mdx
Added details of pg_upgrade parameters that can be passed down (and be meaningful) to pg_upgrade.
=> Added pg_upgrade parameter details. pgd 5 only.

product_docs/docs/pgd/5/routing/raft/02_raft_subgroups_and_pgd_cli.mdx, product_docs/docs/pgd/5/routing/raft/index.mdx
=> Fix bad links

product_docs/docs/pgd/5/routing/raft/02_raft_subgroups_and_pgd_cli.mdx, product_docs/docs/pgd/5/routing/raft/index.mdx
Fixed a couple links in PGD Raft content
=> 2023-06-12a

product_docs/docs/epas/15/connectors.mdx
Added information about using Postgres community drivers with EPAS
Fixes https://github.com/EnterpriseDB/docs/issues/3972
=> EPAS: using Postgre community drivers

src/styles/_overrides.scss
Added a soupcon of offset underlining for lovelier links.
=> Update _overrides.scss with code link styling

product_docs/docs/mysql_data_adapter/2/02_requirements_overview.mdx
=> Small edit to PR4085

product_docs/docs/pgd/4/rel_notes/index.mdx, product_docs/docs/pgd/4/rel_notes/pgd_4.3.1_rel_notes.mdx
=> Edits to PR 4081

product_docs/docs/pgd/5/index.mdx, product_docs/docs/pgd/5/overview/index.mdx, product_docs/docs/pgd/5/terminology.mdx
=> Minor edits to PR4064

product_docs/docs/pgd/3.7/bdr/release-notes.mdx
Edited latest release notes, did some very global basic cleanup on earlier releases
=> Edits to PR 4080

product_docs/docs/transporter/preview/preparing_db/preparing_oracle_source_databases.mdx, product_docs/docs/transporter/preview/preparing_db/preparing_postgres_source_databases.mdx
Added docs for source DB config validation scripts.
=> Add docs for transporter db config validation scripts

product_docs/docs/eprs/7/02_overview/01_why_replication.mdx, product_docs/docs/eprs/7/05_smr_operation/05_managing_subscription.mdx, product_docs/docs/eprs/7/06_mmr_operation/06_conflict_resolution/10_manual_conflict_resolution_log_based_method/03_overview_correction_strategies_log_based.mdx, product_docs/docs/eprs/7/installing/uninstalling.mdx
Did not review format-only changes, as this text has been edited and overall is very clean.
=> Edits to PR3516

product_docs/docs/livecompare/2/advanced_usage.mdx, product_docs/docs/livecompare/2/bdr_support.mdx, product_docs/docs/livecompare/2/command_line_usage.mdx, product_docs/docs/livecompare/2/index.mdx, product_docs/docs/livecompare/2/licenses.mdx, product_docs/docs/livecompare/2/oracle_support.mdx, product_docs/docs/livecompare/2/requirements.mdx, product_docs/docs/livecompare/2/settings.mdx, product_docs/docs/livecompare/2/supported_technologies.mdx
Draft deploy: https://deploy-preview-4029--edb-docs-staging.netlify.app/docs/livecompare/latest/
=> first set of edits to LiveCompare

product_docs/docs/biganimal/release/using_cluster/managing_replicas.mdx
=> BigAnimal: fix link issue on Managing replicas topic

product_docs/docs/epas/15/epas_compat_spl/15_object_types_and_objects/02_object_type_components/01_object_type_specification_syntax.mdx, product_docs/docs/epas/15/epas_compat_spl/15_object_types_and_objects/02_object_type_components/02_object_type_body_syntax.mdx
=> EPAS - Constructor fix as per DB-2320

product_docs/docs/pem/9/monitoring_failover_manager.mdx
Font treatment of user and missing punctuation.
=> Edits to PR 4232

product_docs/docs/pem/9/considerations/pem_pgbouncer/configuring_pgBouncer.mdx
=> Update configuring_pgBouncer.mdx - recursive permissions

product_docs/docs/biganimal/release/overview/03_security/index.mdx, product_docs/docs/biganimal/release/overview/deployment_options/index.mdx, product_docs/docs/biganimal/release/using_cluster/01_postgres_access/pg_ba_admin.mdx
=> BigAnimal: fixing links

install_template/templates/products/failover-manager/base.njk, product_docs/docs/efm/4/04_configuring_efm/01_cluster_properties.mdx, product_docs/docs/efm/4/04_configuring_efm/02_encrypting_database_password.mdx, product_docs/docs/efm/4/04_configuring_efm/03_cluster_members.mdx, product_docs/docs/efm/4/04_configuring_efm/04_extending_efm_permissions.mdx, product_docs/docs/efm/4/05_using_efm.mdx, product_docs/docs/efm/4/08_controlling_efm_service.mdx, product_docs/docs/efm/4/efm_quick_start/index.mdx, product_docs/docs/efm/4/efm_rel_notes/03_efm_47_rel_notes.mdx, product_docs/docs/efm/4/efm_rel_notes/index.mdx, product_docs/docs/efm/4/installing/linux_ppc64le/efm_rhel_8.mdx, product_docs/docs/efm/4/installing/linux_ppc64le/efm_sles_12.mdx, product_docs/docs/efm/4/installing/linux_ppc64le/efm_sles_15.mdx, product_docs/docs/efm/4/installing/linux_x86_64/efm_centos_7.mdx, product_docs/docs/efm/4/installing/linux_x86_64/efm_debian_10.mdx, product_docs/docs/efm/4/installing/linux_x86_64/efm_debian_11.mdx, product_docs/docs/efm/4/installing/linux_x86_64/efm_other_linux_8.mdx, product_docs/docs/efm/4/installing/linux_x86_64/efm_rhel_7.mdx, product_docs/docs/efm/4/installing/linux_x86_64/efm_rhel_8.mdx, product_docs/docs/efm/4/installing/linux_x86_64/efm_sles_12.mdx, product_docs/docs/efm/4/installing/linux_x86_64/efm_sles_15.mdx, product_docs/docs/efm/4/installing/linux_x86_64/efm_ubuntu_18.mdx, product_docs/docs/efm/4/installing/linux_x86_64/efm_ubuntu_20.mdx, product_docs/docs/efm/4/installing/linux_x86_64/efm_ubuntu_22.mdx, product_docs/docs/efm/4/upgrading.mdx
Version changes through user's guide.
Added 4.7 release notes page.
=> First draft of documentation changes for efm 4.7

product_docs/docs/biganimal/release/using_cluster/01_postgres_access/pg_ba_admin.mdx
Incorporated comments from Andrew - see https://edb.slack.com/archives/C052WN4HNTY/p1687293191543979
=> BigAnimal: adjustments to pg_ba_admin topic

advocacy_docs/supported-open-source/barman/single-server-streaming/step01-db-setup.mdx
Added notes on setting slots and other server settings. Addresses #2089 .
=> Added note on setting other server settings

product_docs/docs/biganimal/release/overview/03a_region_support/index.mdx
Added new regions for BigAnimal's cloud account
=> BigAnimal: new regions for BigAnimal's cloud account

advocacy_docs/supported-open-source/barman/single-server-streaming/step01-db-setup.mdx, product_docs/docs/biganimal/release/overview/03a_region_support/index.mdx, product_docs/docs/biganimal/release/using_cluster/01_postgres_access/pg_ba_admin.mdx
- BigAnimal: new regions for BigAnimal's cloud account #4279 by @ccestes 
- BigAnimal: adjustments to pg_ba_admin topic #4275 by @drothery-edb 
- Added note on setting other server settings #4270 by @djw-m
=> Release: 2023-06-21

product_docs/docs/pgd/5/consistency/eager.mdx
Badly formed note - was obscuring important info
=> Fix note formatting

product_docs/docs/biganimal/release/using_cluster/01_postgres_access/index.mdx
=> BigAnimal: fixed repeated word

product_docs/docs/biganimal/release/getting_started/creating_a_cluster/index.mdx, product_docs/docs/biganimal/release/using_cluster/05_monitoring_and_logging/index.mdx, product_docs/docs/biganimal/release/using_cluster/05_monitoring_and_logging/other_monitoring/index.mdx
minor tweaks pending input from SMEs
=> BigAnimal: clarifying BAH behavior

product_docs/docs/pgd/5/reference/pgd-settings.mdx
Noticed a stray formatting issue in the docs - fixed here
End of page formatting
=> Update pgd-settings.mdx - formatting fix

product_docs/docs/pgd/5/reference/pgd-settings.mdx
Added connectivity settings to PGD v5 product docs
=> Add a section on TCP connectivity settings to product docs

gatsby-node.js
=> This should stop package-lock.json being overwritten

product_docs/docs/eprs/7/08_xdb_cli/03_xdb_cli_commands/52_reload_conf_file.mdx, tools/user/reorg/redirects/README.md, tools/user/reorg/redirects/package-lock.json, tools/user/reorg/redirects/package.json, tools/user/reorg/redirects/renames-to-redirects.js
Created script to apply redirects to the epas restructure branch. Also fix broken frontmatter in some random file.
See [the README](https://github.com/EnterpriseDB/docs/blob/bugfix/josh-heyer/4294-Script-to-apply-redirects-to-the-epas-restructure-branch/tools/user/reorg/redirects/README.md) for details
Fixes #4294
Fixes #2380
=> A script to create redirects based on renamed files in a branch  

docker/docker-compose.quickstart.yaml
Made product docs folder rw to allow refbuilder to update when previewing locally
Should fix #4318
=> Make product docs rw in docker

advocacy_docs/supported-open-source/pgbackrest/04-recommended_settings.mdx
Explain which settings to change to support TDE and why this is needed.
=> pgBackRest and TDE support

product_docs/docs/pgd/5/durability/lag-control.mdx
Fixed another infinite admonition by fencing it. This one was removing many headings from the ToC too.
=> Fixed infinite admonition by fencing it

product_docs/docs/biganimal/release/getting_started/preparing_cloud_account/preparing_gcp/index.mdx
https://enterprisedb.atlassian.net/browse/UPM-21148
=> BigAnimal: Preparing your GCP account

gatsby-node.js, product_docs/docs/pgd/5/reference/functions.mdx, product_docs/docs/pgd/5/reference/pgd-settings.mdx, src/components/table-of-contents.js, src/templates/doc.js
Added deepToC option to frontmatter.
First design pass with italic headings.
=> Adds deepToC frontmatter option

product_docs/docs/pem/9/pem_rel_notes/921_rel_notes.mdx, product_docs/docs/pem/9/pem_rel_notes/index.mdx
=> PEM - 9.2.1 release branch

product_docs/docs/pem/9/pem_rel_notes/index.mdx
=> PEM: 9.2.1 release date

product_docs/docs/biganimal/release/overview/03a_region_support/index.mdx
Here is the draft link: https://deploy-preview-4195--edb-docs-staging.netlify.app/docs/biganimal/latest/overview/03a_region_support/#supported-google-cloud-regions
=> BigAnimal: GCP regions

product_docs/docs/pgd/5/reference/pgd-settings.mdx
=> Edits to new Decoding worker text added with PR 4266

product_docs/docs/biganimal/release/overview/extensions_tools.mdx
=> Fixed typo

product_docs/docs/biganimal/release/getting_started/creating_a_cluster/01_cluster_networking.mdx
https://enterprisedb.atlassian.net/browse/UPM-21150
=> docs: Adding BigAnimal GCP cluster architecture section

product_docs/docs/biganimal/release/administering_cluster/customizing_compliance/gcp_policy_definitions.mdx
https://enterprisedb.atlassian.net/browse/UPM-21152
=> docs: Adding BigAnimal GCP customizing compliance page

product_docs/docs/pgd/4/rel_notes/index.mdx
The CLI version 5.1.0 is released and supported with PGD 5.1.x and not 4.x
For PGD 4.3.1, CLI version 1.1.1 was released.
=> Update the version for CLI to 1.1.1 from 5.1.0. 

advocacy_docs/supported-open-source/postgresql/installing/index.mdx, advocacy_docs/supported-open-source/postgresql/installing/linux_ppc64le/index.mdx, advocacy_docs/supported-open-source/postgresql/installing/linux_ppc64le/postgresql_rhel_9.mdx, advocacy_docs/supported-open-source/postgresql/installing/linux_x86_64/index.mdx, advocacy_docs/supported-open-source/postgresql/installing/linux_x86_64/postgresql_other_linux_9.mdx, advocacy_docs/supported-open-source/postgresql/installing/linux_x86_64/postgresql_rhel_9.mdx, install_template/config.yaml, install_template/templates/products/postgresql/almalinux-9-or-rocky-linux-9.njk, install_template/templates/products/postgresql/rhel-9-or-ol-9.njk, install_template/templates/products/postgresql/rhel-9_ppc64le.njk
Changed config.yaml and files in install_template/products to support RHEL 9. Then generated new topics based on template changes
=> Added RHEL 9 to installing topics for PostgreSQL

product_docs/docs/epas/15/application_programming/epas_compat_spl/05_control_structures/07_exception_handling.mdx
Removed semi-colon use, paragraphed to improve readability
=> Edited for wordiness

product_docs/docs/hadoop_data_adapter/2/02_requirements_overview.mdx, product_docs/docs/mongo_data_adapter/5/02_requirements_overview.mdx
Typo had been corrected already...simplified reference language.
=> tightened references

product_docs/docs/epas/14/epas_rel_notes/index.mdx, product_docs/docs/epas/15/epas_rel_notes/index.mdx
=> Edits to release note text

product_docs/docs/biganimal/release/pricing_and_billing/index.mdx
=> fixed capitalization of initialism

product_docs/docs/pgd/5/reference/pgd-settings.mdx
=> edits to connectivity settings section

product_docs/docs/pgd/5/reference/pgd-settings.mdx
=> fixed double word

product_docs/docs/biganimal/release/getting_started/creating_a_cluster/index.mdx, product_docs/docs/biganimal/release/using_cluster/05_monitoring_and_logging/index.mdx
=> Small edits to release for PR4285

advocacy_docs/pg_extensions/wait_states/index.mdx, advocacy_docs/pg_extensions/wait_states/using.mdx, product_docs/docs/epas/15/managing_performance/evaluating_wait_states.mdx
=> Edits to Wait States doc

product_docs/docs/biganimal/release/using_cluster/02_connecting_your_cluster/connecting_from_gcp/index.mdx, product_docs/docs/biganimal/release/using_cluster/02_connecting_your_cluster/connecting_from_gcp/vpc_peering.mdx
=> BigAnimal: Connecting from GCP

advocacy_docs/pg_extensions/ldap_sync/installing.mdx, advocacy_docs/pg_extensions/pg_failover_slots/installing.mdx, advocacy_docs/pg_extensions/pg_tuner/installing.mdx, advocacy_docs/pg_extensions/query_advisor/installing.mdx
=> Extensions: RHEL 9 support

src/pages/index.js
=> Fix index.js and security section

product_docs/docs/biganimal/release/overview/deployment_options/index.mdx
removing "only" from not about BAH CSP support
=> BigAnimal: update to note about csp support for bha

advocacy_docs/partner_docs/HashicorpVault/02-PartnerInformation.mdx, advocacy_docs/partner_docs/HashicorpVault/03-SolutionSummary.mdx, advocacy_docs/partner_docs/HashicorpVault/04-ConfiguringHashicorpVault.mdx, advocacy_docs/partner_docs/HashicorpVault/05-UsingHashicorpVault.mdx, advocacy_docs/partner_docs/HashicorpVault/06-CertificationEnvironment.mdx, advocacy_docs/partner_docs/HashicorpVault/07-SupportandLogging.mdx, advocacy_docs/partner_docs/HashicorpVault/Images/HashicorpVaultSolutionSummaryImage.png, advocacy_docs/partner_docs/HashicorpVault/Images/PartnerProgram.jpg.png, advocacy_docs/partner_docs/HashicorpVault/index.mdx, src/pages/index.js
=> TechPartner Hashicorp Vault Guide

product_docs/docs/net_connector/7.0.4.1/06_opening_a_database_connection.mdx
https://enterprisedb.atlassian.net/browse/EC-2771
=> NET Connector typo

product_docs/docs/biganimal/release/using_cluster/01_postgres_access/pg_ba_admin.mdx
added executing SET SESSION AUTHORIZATION to the list of things pg_ba_admin can't do
https://enterprisedb.atlassian.net/browse/PGBA-54
=> BigAnimal: SET SESSION AUTHORIZATION

product_docs/docs/epas/15/application_programming/epas_compat_spl/10_collections/about_collections.mdx
=> small edit for clarity

product_docs/docs/pem/9/registering_agent.mdx
font of utility and missing article.
=> Small edit to new text

product_docs/docs/epas/14/epas_compat_ora_dev_guide/02_sql_tutorial/09_the_sql_language.mdx, product_docs/docs/epas/14/epas_compat_ora_dev_guide/08_oracle_catalog_views.mdx, product_docs/docs/epas/14/epas_compat_ora_dev_guide/11_system_catalog_tables.mdx
https://github.com/EnterpriseDB/docs/pull/4383
=> EPAS: reverted v14 link changes from #4383

product_docs/docs/efm/4/efm_quick_start/index.mdx
Changed to "47" to match the rest of the example.
=> update install version of efm

product_docs/docs/pgd/4/rel_notes/index.mdx
Added blank line into footnotes
=> Fix footnotes by putting a blank line in.

product_docs/docs/efm/4/efm_quick_start/index.mdx, product_docs/docs/pgd/4/rel_notes/index.mdx, product_docs/docs/tpa/23/rel_notes/index.mdx, product_docs/docs/tpa/23/rel_notes/tpa_23.17_rel_notes.mdx, product_docs/docs/tpa/23/rel_notes/tpa_23.18_rel_notes.mdx, product_docs/docs/tpa/23/rel_notes/tpa_23.19_rel_notes.mdx
- TPA 23.19 release
- HARP: release note foot note fix
=> Release: 2023-07-12b

product_docs/docs/tde/15/enabling_tde.mdx
=> Added note on TDE presence check

product_docs/docs/tpa/23/rel_notes/index.mdx
Quick fix for version number .12 -> .19
=> Quick fix for version number

product_docs/docs/efm/4/04_configuring_efm/05_using_vip_addresses.mdx
and did a little bit of other cleanup
=> added missing word

product_docs/docs/net_connector/7.0.4.1/03_the_advanced_server_net_connector_overview.mdx, product_docs/docs/net_connector/7.0.4.1/04_installing_and_configuring_the_net_connector.mdx, product_docs/docs/net_connector/7.0.4.1/06_opening_a_database_connection.mdx, product_docs/docs/net_connector/7.0.4.1/07_retrieving_database_records.mdx, product_docs/docs/net_connector/7.0.4.1/10_deleting_records_in_a_database.mdx, product_docs/docs/net_connector/7.0.4.1/11_using_spl_stored_procedures_in_your_net_application.mdx, product_docs/docs/net_connector/7.0.4.1/12_using_advanced_queueing.mdx, product_docs/docs/net_connector/7.0.4.1/13_using_a_ref_cursor_in_a_net_application.mdx, product_docs/docs/net_connector/7.0.4.1/14_using_plugins.mdx, product_docs/docs/net_connector/7.0.4.1/15_using_object_types.mdx, product_docs/docs/net_connector/7.0.4.1/16_scram_compatibility.mdx, product_docs/docs/net_connector/7.0.4.1/17_advanced_server_net_connector_logging.mdx, product_docs/docs/net_connector/7.0.4.1/index.mdx
=> Edits to EDB .Net doc

product_docs/docs/biganimal/release/overview/02_high_availability.mdx
=> Fixed a typo

product_docs/docs/pgd/5/durability/lag-control.mdx
Fixed infinite admonition with fencing
(also some wrapping noise as I tidied before descending on this more)
=> Fixed infinite admonition with fencing

src/pages/index.js
=> Updated headlines for July

product_docs/docs/migration_portal/4/01_mp_release_notes/mp_4.5.1_rel_notes.mdx
https://enterprisedb.atlassian.net/browse/MIG-4701
=> Migration Portal: fix version number

product_docs/docs/pgd/5/architectures.mdx
Content that was originally omitted from the White Paper now added.
=> Added text to choosing architectures

product_docs/docs/pem/8/pem_rel_notes/863_rel_notes.mdx, product_docs/docs/pem/8/pem_rel_notes/index.mdx, product_docs/docs/pem/9/pem_rel_notes/922_rel_notes.mdx, product_docs/docs/pem/9/pem_rel_notes/index.mdx
Added release notes for PEM 9.2.2 and 8.6.3
=> PEM - 9.2.2 and 8.6.3 release

product_docs/docs/tpa/23/rel_notes/index.mdx, product_docs/docs/tpa/23/rel_notes/tpa_23.1-11_rel_notes.mdx
Added archive page for older formatted release notes for interim linkage
=> Added archive page

product_docs/docs/biganimal/release/getting_started/creating_a_cluster/index.mdx
Indented the note so that the next steps were included in the list
=> BigAnimal: Creating a cluster hierarchy fix 

product_docs/docs/tde/15/index.mdx
Added a link to the performance blog.
Fixes https://github.com/EnterpriseDB/docs/issues/4145
=> TDE: performance

install_template/README.md
=> cookbook for adding new platform

product_docs/docs/net_connector/7.0.4.1/03_the_advanced_server_net_connector_overview.mdx
Added content as per [EC-2775](https://enterprisedb.atlassian.net/browse/EC-2775)
[EC-2775]: https://enterprisedb.atlassian.net/browse/EC-2775?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> NET connector - added EDBDataSource to overview section

product_docs/docs/epas/15/database_administration/02_edb_loader/building_the_control_file/control_file_examples.mdx, product_docs/docs/epas/15/database_administration/02_edb_loader/building_the_control_file/index.mdx
This has been edited before so I stopped after a few files.
=> Some edits to the restructured content

src/pages/index.js
=> Partner docs: restoring Security section on home page

product_docs/docs/pem/9/upgrading/upgrading_pem_installation/upgrading_pem_installation_linux_rpm.mdx
=> edits to upgrading topic

product_docs/docs/tde/15/enabling_tde.mdx
=> edits to new tde text

product_docs/docs/pgd/4/harp/04_configuration.mdx
Changed link from index#health-check to ./#health-check
=> Fix bad link to index

product_docs/docs/migration_portal/4/known_issues_notes.mdx
https://enterprisedb.atlassian.net/browse/MIG-4702
=> Migration Portal: granting RESOURCE role

product_docs/docs/biganimal/release/overview/03a_region_support/index.mdx, product_docs/docs/biganimal/release/overview/deployment_options/index.mdx
Added regions per [Regions Supported in BigAnimal + BA-hosted](https://docs.google.com/spreadsheets/d/1FQiRA-OIzX8CWchY1UGxgJvIblUIf5Ie5SSF2FJ_bOE/edit#gid=830197369)
=> BigAnimal: GCP on BAH

product_docs/docs/net_connector/7.0.4.1/03_the_advanced_server_net_connector_overview.mdx
=> Edits to release text

product_docs/docs/biganimal/release/getting_started/preparing_cloud_account/preparing_gcp/index.mdx, product_docs/docs/biganimal/release/using_cluster/02_connecting_your_cluster/02_connecting_from_aws/index.mdx
=> BigAnimal: fixing GCP links

product_docs/docs/biganimal/release/administering_cluster/customizing_compliance/gcp_policy_definitions.mdx, product_docs/docs/biganimal/release/getting_started/02_connecting_to_your_cloud/connecting_aws.mdx, product_docs/docs/biganimal/release/getting_started/02_connecting_to_your_cloud/connecting_gcp.mdx, product_docs/docs/biganimal/release/getting_started/creating_a_cluster/01_cluster_networking.mdx, product_docs/docs/biganimal/release/getting_started/preparing_cloud_account/preparing_gcp/index.mdx, product_docs/docs/biganimal/release/getting_started/preparing_cloud_account/preparing_gcp/understanding_quotas_in_gcp.mdx, product_docs/docs/biganimal/release/overview/03a_region_support/index.mdx, product_docs/docs/biganimal/release/using_cluster/02_connecting_your_cluster/02_connecting_from_aws/index.mdx
=> Edits to PR4191

product_docs/docs/biganimal/release/overview/02_high_availability.mdx
Added hyphen for compound adjective
=> Edits to PR4472

product_docs/docs/migration_portal/4/known_issues_notes.mdx
=> Edits to PR4456

advocacy_docs/pg_extensions/pg_failover_slots/index.mdx
=> Edits to failover slots content

product_docs/docs/pgd/3.7/harp/02_overview.mdx, product_docs/docs/pgd/3.7/harp/04_configuration.mdx, product_docs/docs/pgd/4/harp/04_configuration.mdx, product_docs/docs/pgd/4/harp/index.mdx, product_docs/docs/pgd/5/ddl.mdx
=> edits to new Health check content

product_docs/docs/pgd/4/rel_notes/pgd_4.3.1-1_rel_notes.mdx
=> Simplify upgrade messaging

product_docs/docs/pgd/5/architectures.mdx
=> Some cleanup to the new text

package-lock.json, product_docs/docs/mysql_data_adapter/2/mysql_rel_notes/mysql2.5.3_rel_notes.mdx, product_docs/docs/mysql_data_adapter/2/mysql_rel_notes/mysql2.5.5_rel_notes.mdx, product_docs/docs/mysql_data_adapter/2/mysql_rel_notes/mysql2.6.0_rel_notes.mdx, product_docs/docs/mysql_data_adapter/2/mysql_rel_notes/mysql2.7.0_rel_notes.mdx, product_docs/docs/pgd/5/overview/index.mdx, src/components/left-nav.js, src/components/main-content.js, src/pages/access-denied.js
Update icons package version to 1.26
Misc little changes to drive away build warnings
=> Update icons for transporter, fix warnings

product_docs/docs/biganimal/release/overview/extensions_tools.mdx
=> BigAnimal: another link

product_docs/docs/biganimal/release/reference/cli/managing_clusters.mdx
=> BigAnimal: updated format for cluster show-architectures command

product_docs/docs/biganimal/release/getting_started/preparing_cloud_account/01_preparing_azure/index.mdx, product_docs/docs/biganimal/release/getting_started/preparing_cloud_account/02_preparing_aws.mdx, product_docs/docs/biganimal/release/getting_started/preparing_cloud_account/preparing_gcp/index.mdx
https://enterprisedb.atlassian.net/browse/UPM-21239
=> BigAnimal: CLI 2.0.1 updates

product_docs/docs/pem/8/pem_rel_notes/863_rel_notes.mdx, product_docs/docs/pem/9/pem_rel_notes/921_rel_notes.mdx, product_docs/docs/pem/9/pem_rel_notes/922_rel_notes.mdx
=> PEM: updated rel note type for security fixes

product_docs/docs/pgd/3.7/harp/01_release_notes/harp2.3.1_rel_notes.mdx, product_docs/docs/pgd/4/rel_notes/pgd_4.3.1-2_rel_notes.mdx
=> Doc/fix - crop issue rel note

product_docs/docs/biganimal/release/getting_started/preparing_cloud_account/01_preparing_azure/index.mdx, product_docs/docs/biganimal/release/getting_started/preparing_cloud_account/02_preparing_aws.mdx, product_docs/docs/biganimal/release/getting_started/preparing_cloud_account/preparing_gcp/index.mdx, product_docs/docs/biganimal/release/reference/cli/managing_clusters.mdx, product_docs/docs/pem/8/pem_rel_notes/863_rel_notes.mdx, product_docs/docs/pem/9/pem_rel_notes/921_rel_notes.mdx, product_docs/docs/pem/9/pem_rel_notes/922_rel_notes.mdx, product_docs/docs/pgd/3.7/harp/01_release_notes/harp2.3.1_rel_notes.mdx, product_docs/docs/pgd/3.7/harp/01_release_notes/index.mdx, product_docs/docs/pgd/4/rel_notes/index.mdx, product_docs/docs/pgd/4/rel_notes/pgd_4.3.1-2_rel_notes.mdx
- HARP: 2.3.1 release
- PEM: fixed security terminology in rel notes
- BigAnimal: CLI 2.0.1 updates
=> Release: 2023-07-28

product_docs/docs/pgd/4/limitations.mdx, product_docs/docs/pgd/5/limitations.mdx
=> Copy edits to PR4510

product_docs/docs/biganimal/release/overview/extensions_tools.mdx, product_docs/docs/biganimal/release/using_cluster/extensions.mdx
=> edits to PR4292

product_docs/docs/pgd/5/parallelapply.mdx
=> Editing pass at parallel apply content

product_docs/docs/biganimal/release/overview/extensions_tools.mdx
https://enterprisedb.atlassian.net/browse/UPM-15346
Added Wait States, Query Advisor, and Failover Slots - will generate a new Extensions table once the spreadsheet is updated with the other extension support
=> BigAnimal: Q2 extensions

product_docs/docs/postgres_for_kubernetes/1/rel_notes/1_18_6_rel_notes.mdx
=> PG4K: fixed product name in 1.8.6 rel notes

product_docs/docs/biganimal/release/getting_started/preparing_cloud_account/preparing_gcp/index.mdx
changed broken link to absolute link as we can use absolute links in unversioned doc
=> BigAnimal link

product_docs/docs/biganimal/release/getting_started/preparing_cloud_account/preparing_gcp/index.mdx, product_docs/docs/biganimal/release/overview/extensions_tools.mdx, product_docs/docs/biganimal/release/using_cluster/extensions.mdx, product_docs/docs/pgd/4/limitations.mdx, product_docs/docs/pgd/5/limitations.mdx, product_docs/docs/pgd/5/parallelapply.mdx, product_docs/docs/postgres_for_kubernetes/1/api_reference.mdx, product_docs/docs/postgres_for_kubernetes/1/bootstrap.mdx, product_docs/docs/postgres_for_kubernetes/1/index.mdx, product_docs/docs/postgres_for_kubernetes/1/installation_upgrade.mdx, product_docs/docs/postgres_for_kubernetes/1/interactive_demo.mdx, product_docs/docs/postgres_for_kubernetes/1/openshift.mdx, product_docs/docs/postgres_for_kubernetes/1/rel_notes/1_18_6_rel_notes.mdx, product_docs/docs/postgres_for_kubernetes/1/rel_notes/1_19_4_rel_notes.mdx, product_docs/docs/postgres_for_kubernetes/1/rel_notes/1_20_2_rel_notes.mdx, product_docs/docs/postgres_for_kubernetes/1/rel_notes/index.mdx, product_docs/docs/postgres_for_kubernetes/1/troubleshooting.mdx
- EDB Postgres for Kubernetes 1.20.2, 1.19.4, and 1.18.6 releases
- Misc copy edits
- BigAnimal: extension updates and fix for broken link
=> Release: 2023-07-28a

product_docs/docs/pem/9/profiling_workloads/installing_sql_profiler.mdx
Updated content to mention - create SQL Profiler extension in the maintenance database as per [DF-353](https://enterprisedb.atlassian.net/browse/DF-353)
[DF-353]: https://enterprisedb.atlassian.net/browse/DF-353?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> PEM - SQL Profiler fix as per DF-353

product_docs/docs/ocl_connector/15/ocl_rel_notes/index.mdx
=> OCL Connector: release notes error

product_docs/docs/biganimal/release/getting_started/preparing_cloud_account/preparing_gcp/index.mdx
https://enterprisedb.atlassian.net/browse/UPM-20346
Updates for preflight GCP terminology - no other changes had doc impact
=> BigAnimal: CLI 2.1

product_docs/docs/pem/9/images/stackbuilder_pemhttpd.png, product_docs/docs/pem/9/upgrading/index.mdx, product_docs/docs/pem/9/upgrading/upgrading_httpd.mdx
We get a lot of questions about updating HTTPD.
Having a single page that summarizes this will save a lot of time.
=> Add new page on updating HTTPD

product_docs/docs/pem/9/upgrading/upgrading_pem_installation/upgrading_pem_installation_linux_rpm.mdx
Revisions to one topic describing Linux upgrades. These revisions parallel similar language used for other product upgrades.
=> Revised upgrade language to be more consistent with other product

product_docs/docs/biganimal/release/reference/cli/index.mdx
=> BigAnimal: remove CLI limitation

advocacy_docs/supported-open-source/pgbackrest/06-use_case_1.mdx, advocacy_docs/supported-open-source/pgbackrest/99-faq.mdx, advocacy_docs/supported-open-source/pgbackrest/index.mdx, product_docs/docs/biganimal/release/reference/cli/index.mdx, product_docs/docs/hadoop_data_adapter/2/upgrading.mdx, product_docs/docs/jdbc_connector/42.5.4.1/installing/upgrading.mdx, product_docs/docs/migration_toolkit/55/upgrading.mdx, product_docs/docs/mongo_data_adapter/5/upgrading.mdx, product_docs/docs/mysql_data_adapter/2/upgrading.mdx, product_docs/docs/ocl_connector/15/installing/upgrading.mdx, product_docs/docs/odbc_connector/13/installing/upgrading.mdx, product_docs/docs/pem/9/upgrading/upgrading_pem_installation/upgrading_pem_installation_linux_rpm.mdx, product_docs/docs/pgbouncer/1/upgrading.mdx, product_docs/docs/pgpool/4/installing/upgrading.mdx, product_docs/docs/pgpool/4/installing_extensions/upgrading_extensions.mdx
- PgBackrest 2.47
- BigAnimal: removed CLI limitation
- Cleanup of upgrade instructions
=> Release: 2023-08-02

product_docs/docs/epas/15/epas_security_guide/05_edb_audit_logging/03_enabling_audit_logging.mdx
=> EPAS: Update to audit logging list

advocacy_docs/partner_docs/DBeaverPRO/02-PartnerInformation.mdx, advocacy_docs/partner_docs/DBeaverPRO/03-SolutionSummary.mdx, advocacy_docs/partner_docs/DBeaverPRO/04-ConfiguringDBeaverPRO.mdx, advocacy_docs/partner_docs/DBeaverPRO/05-UsingDBeaverPRO.mdx, advocacy_docs/partner_docs/DBeaverPRO/06-CertificationEnvironment.mdx, advocacy_docs/partner_docs/DBeaverPRO/07-SupportandLogging.mdx, advocacy_docs/partner_docs/DBeaverPRO/Images/CompareMigrateSchema.png, advocacy_docs/partner_docs/DBeaverPRO/Images/DBeaverErrorLogs.png, advocacy_docs/partner_docs/DBeaverPRO/Images/DBeaverLogViewer.png, advocacy_docs/partner_docs/DBeaverPRO/Images/EPASConnectionSettings.png, advocacy_docs/partner_docs/DBeaverPRO/Images/EPASDatabaseConfiguration.png, advocacy_docs/partner_docs/DBeaverPRO/Images/EPASTestConnection.png, advocacy_docs/partner_docs/DBeaverPRO/Images/ExtendedTestConnection.png, advocacy_docs/partner_docs/DBeaverPRO/Images/JDBCConnection.png, advocacy_docs/partner_docs/DBeaverPRO/Images/SameSchemaCompareResults.png, advocacy_docs/partner_docs/DBeaverPRO/Images/SchemaCompareDiffResults.png, advocacy_docs/partner_docs/DBeaverPRO/Images/SchemaCompareSettings.png, advocacy_docs/partner_docs/DBeaverPRO/Images/SchemasToCompare.png, advocacy_docs/partner_docs/DBeaverPRO/Images/SelectTargetSourceforCompare.png
=> Tech Partner DBeaver Guide Updates

product_docs/docs/biganimal/release/using_cluster/02_connecting_your_cluster/01_connecting_from_azure/index.mdx, product_docs/docs/biganimal/release/using_cluster/02_connecting_your_cluster/02_connecting_from_aws/index.mdx, product_docs/docs/biganimal/release/using_cluster/02_connecting_your_cluster/connecting_from_a_client.mdx, product_docs/docs/biganimal/release/using_cluster/02_connecting_your_cluster/connecting_from_gcp/index.mdx
Source material: 
https://docs.google.com/document/d/1Qqa6XZrwqdVBi__UVxhasEhgEtLhge2lh2yFfNmzA1w/edit
https://docs.google.com/document/d/1IOJLQ-Dv1BjofY0p14T5itaZo5tNEu4J309TnedcFkw/edit
=> BigAnimal: GCP private endpoints

.github/workflows/deploy-draft.yml, gatsby-config.js
Gonna feel pretty dumb if this is why it hasn't been working for ... a while
=> Use correct path for PDF noindex headers

advocacy_docs/pg_extensions/pg_tuner/using.mdx
=> BigAnimal: auto tuning support

product_docs/docs/biganimal/release/using_cluster/02_connecting_your_cluster/connecting_from_gcp/index.mdx
=> Fix BigAnimal link in release branch

advocacy_docs/pg_extensions/pg_tuner/using.mdx, gatsby-config.js, product_docs/docs/biganimal/release/using_cluster/02_connecting_your_cluster/01_connecting_from_azure/index.mdx, product_docs/docs/biganimal/release/using_cluster/02_connecting_your_cluster/02_connecting_from_aws/index.mdx, product_docs/docs/biganimal/release/using_cluster/02_connecting_your_cluster/connecting_from_a_client.mdx, product_docs/docs/biganimal/release/using_cluster/02_connecting_your_cluster/connecting_from_gcp/index.mdx
- BigAnimal: updates to Connecting from Google Cloud topic
- Pg Tuner: added BigAnimal limitation 
- PDF fix
=> Release: 2023-08-07

product_docs/docs/pgd/4/harp/04_configuration.mdx
Added previously proposed line on ssl in #3089 
(HARP content had moved in the interim)
=> Added previously proposed line on ssl in #3089

product_docs/docs/pem/9/index.mdx
=> Add support for PGE as a backend

product_docs/docs/biganimal/release/getting_started/index.mdx, product_docs/docs/pem/9/upgrading/upgrading_httpd.mdx
RHEL-like systems are also subject to the same constraints documented for RHEL.
=> Clarify for RHEL-like systems

product_docs/docs/efm/4/07_using_efm_utility.mdx
fixes https://github.com/EnterpriseDB/docs/issues/4598
=> EFM: allow-node fix

product_docs/docs/epas/15/epas_security_guide/05_edb_audit_logging/03_enabling_audit_logging.mdx
Flipped sentence to make it consistent with the rest of the list and to conform to "goal before action" principle.
=> Edit to pr4563

product_docs/docs/biganimal/release/overview/02_high_availability.mdx, product_docs/docs/biganimal/release/reference/cli/managing_clusters.mdx
Minimal edits as this is updated more recently with changes to high-availability naming conventions.
=> edits to PR4511

docs/how-tos/markdown-tips.md
Added outline and included content from readme
=> Markdown guide

product_docs/docs/biganimal/release/getting_started/creating_a_cluster/creating_an_eha_cluster.mdx, product_docs/docs/biganimal/release/overview/05_database_version_policy.mdx
=> BigAnimal: fixed missed cluster name changes

product_docs/docs/biganimal/release/overview/02_high_availability.mdx, product_docs/docs/biganimal/release/reference/cli/index.mdx, product_docs/docs/biganimal/release/reference/cli/managing_clusters.mdx, product_docs/docs/biganimal/release/reference/cli/using_features.mdx
https://enterprisedb.atlassian.net/browse/UPM-23155
spec: https://enterprisedb.atlassian.net/wiki/spaces/PD/pages/3452207113/pgd
=> BigAnimal: updates to PGD CLI commands

product_docs/docs/pgd/4/harp/04_configuration.mdx
=> Edit to PR4592

product_docs/docs/pem/9/index.mdx
=> edits to pr4558

product_docs/docs/pem/9/upgrading/upgrading_httpd.mdx
=> Edits to PR4559

product_docs/docs/epas/15/managing_performance/02_index_advisor/05_index_advisor_limitations.mdx, product_docs/docs/epas/15/managing_performance/03_sql_profiler.mdx, product_docs/docs/epas/15/managing_performance/using_dynatune.mdx
=> edits to PR4554

product_docs/docs/biganimal/release/overview/02_high_availability.mdx
=> BigAnimal: fixed CLI link label

product_docs/docs/biganimal/release/using_cluster/02_connecting_your_cluster/connecting_from_a_client.mdx
https://enterprisedb.atlassian.net/browse/UPM-23202
=> BigAnimal: link to edb-psql doc

product_docs/docs/biganimal/release/using_cluster/terraform_provider.mdx
=> BigAnimal: removing free trial reference from Terraform topic

product_docs/docs/pgd/5/cli/configuring_cli.mdx, product_docs/docs/pgd/5/known_issues.mdx
Fixed bad links reffing pgd cli - changes in known issues and within the docs.
=> Fixed bad links reffing pgd cli

product_docs/docs/biganimal/release/using_cluster/02_connecting_your_cluster/connecting_from_gcp/index.mdx
=> Edits to pr4564

advocacy_docs/partner_docs/VeritasNetBackupforPostgreSQL/02-PartnerInformation.mdx, advocacy_docs/partner_docs/VeritasNetBackupforPostgreSQL/03-SolutionSummary.mdx, advocacy_docs/partner_docs/VeritasNetBackupforPostgreSQL/04-ConfiguringVeritasNetBackupforPostgreSQL.mdx, advocacy_docs/partner_docs/VeritasNetBackupforPostgreSQL/05-UsingVeritasNetBackupForPostgreSQL.mdx, advocacy_docs/partner_docs/VeritasNetBackupforPostgreSQL/06-CertificationEnvironment.mdx, advocacy_docs/partner_docs/VeritasNetBackupforPostgreSQL/index.mdx
=> Edits to Veritas doc

product_docs/docs/biganimal/release/using_cluster/02_connecting_your_cluster/connecting_from_gcp/index.mdx
=> Small improvements to end points procedures based on UI doc

advocacy_docs/partner_docs/SIBVisionsVisionX/02-PartnerInformation.mdx, advocacy_docs/partner_docs/SIBVisionsVisionX/03-SolutionSummary.mdx, advocacy_docs/partner_docs/SIBVisionsVisionX/04-ConfiguringSIBVisionsVisionX.mdx, advocacy_docs/partner_docs/SIBVisionsVisionX/05-UsingSIBVisionsVisionX.mdx, advocacy_docs/partner_docs/SIBVisionsVisionX/06-CertificationEnvironment.mdx, advocacy_docs/partner_docs/SIBVisionsVisionX/index.mdx
=> edits to sib visions partner doc

advocacy_docs/partner_docs/RepostorDataProtectorforPostgreSQL/02-PartnerInformation.mdx, advocacy_docs/partner_docs/RepostorDataProtectorforPostgreSQL/03-SolutionSummary.mdx, advocacy_docs/partner_docs/RepostorDataProtectorforPostgreSQL/04-ConfiguringRepostorDataProtectorforPostgreSQL.mdx, advocacy_docs/partner_docs/RepostorDataProtectorforPostgreSQL/05-UsingRepostorDataProtectorforPostgreSQL.mdx, advocacy_docs/partner_docs/RepostorDataProtectorforPostgreSQL/06-CertificationEnvironment.mdx, advocacy_docs/partner_docs/RepostorDataProtectorforPostgreSQL/index.mdx
=> Edits to Repostor partner doc

advocacy_docs/partner_docs/QuestToadEdge/02-PartnerInformation.mdx, advocacy_docs/partner_docs/QuestToadEdge/03-SolutionSummary.mdx, advocacy_docs/partner_docs/QuestToadEdge/04-ConfiguringQuestToadEdge.mdx, advocacy_docs/partner_docs/QuestToadEdge/05-UsingQuestToadEdge.mdx, advocacy_docs/partner_docs/QuestToadEdge/06-CertificationEnvironment.mdx, advocacy_docs/partner_docs/QuestToadEdge/index.mdx
=> Edits to Quest Toad Edge partner doc

advocacy_docs/partner_docs/PureStorageFlashArray/02-PartnerInformation.mdx, advocacy_docs/partner_docs/PureStorageFlashArray/03-SolutionSummary.mdx, advocacy_docs/partner_docs/PureStorageFlashArray/04-ConfiguringPureStorageFlashArray.mdx, advocacy_docs/partner_docs/PureStorageFlashArray/05-UsingPureStorageFlashArray.mdx, advocacy_docs/partner_docs/PureStorageFlashArray/06-CertificationEnvironment.mdx, advocacy_docs/partner_docs/PureStorageFlashArray/07-SupportandLoggingDetails.mdx, advocacy_docs/partner_docs/PureStorageFlashArray/index.mdx
=> Pure Storage edits

product_docs/docs/pem/9/upgrading/upgrading_pem_installation/upgrading_pem_installation_linux_rpm.mdx
=> Edits to PR4502

advocacy_docs/partner_docs/NutanixAHV/02-PartnerInformation.mdx, advocacy_docs/partner_docs/NutanixAHV/03-SolutionSummary.mdx, advocacy_docs/partner_docs/NutanixAHV/04-ConfiguringNutanixAHV.mdx, advocacy_docs/partner_docs/NutanixAHV/05-UsingNutanixAHV.mdx, advocacy_docs/partner_docs/NutanixAHV/06-CertificationEnvironment.mdx, advocacy_docs/partner_docs/NutanixAHV/07-Support.mdx, advocacy_docs/partner_docs/NutanixAHV/index.mdx
=> Edits to Nutanix doc

advocacy_docs/partner_docs/ImpervaDataSecurityFabric/02-PartnerInformation.mdx, advocacy_docs/partner_docs/ImpervaDataSecurityFabric/03-SolutionSummary.mdx, advocacy_docs/partner_docs/ImpervaDataSecurityFabric/04-ConfiguringImpervaDataSecurityFabric.mdx, advocacy_docs/partner_docs/ImpervaDataSecurityFabric/05-UsingImpervaDataSecurityFabric.mdx, advocacy_docs/partner_docs/ImpervaDataSecurityFabric/06-CertificationEnvironment.mdx, advocacy_docs/partner_docs/ImpervaDataSecurityFabric/07-Support.mdx, advocacy_docs/partner_docs/ImpervaDataSecurityFabric/index.mdx
=> Edits to Imperva partner doc

advocacy_docs/partner_docs/HashicorpVault/02-PartnerInformation.mdx, advocacy_docs/partner_docs/HashicorpVault/03-SolutionSummary.mdx, advocacy_docs/partner_docs/HashicorpVault/04-ConfiguringHashicorpVault.mdx, advocacy_docs/partner_docs/HashicorpVault/05-UsingHashicorpVault.mdx, advocacy_docs/partner_docs/HashicorpVault/06-CertificationEnvironment.mdx, advocacy_docs/partner_docs/HashicorpVault/07-SupportandLogging.mdx, advocacy_docs/partner_docs/HashicorpVault/index.mdx
=> First edit of Hashicorp/Vault

product_docs/docs/epas/16/reference/oracle_compatibility_reference/epas_compat_bip_guide/03_built-in_packages/20_utl_file.mdx
As per [DB-2308](https://enterprisedb.atlassian.net/browse/DB-2308)
[DB-2308]: https://enterprisedb.atlassian.net/browse/DB-2308?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> New UTL_FILE subprograms as per DB-2308

advocacy_docs/security/advisories/cve2023xxxxx1.mdx, advocacy_docs/security/advisories/cve2023xxxxx2.mdx, advocacy_docs/security/advisories/cve2023xxxxx3.mdx, advocacy_docs/security/advisories/cve2023xxxxx4.mdx, advocacy_docs/security/advisories/cve2023xxxxx5.mdx, advocacy_docs/security/advisories/cve2023xxxxx6.mdx, advocacy_docs/security/advisories/cve2023xxxxx7.mdx, advocacy_docs/security/advisories/cve2023xxxxx8.mdx, advocacy_docs/security/advisories/index.mdx, advocacy_docs/security/index.mdx
version number fixes in security docs
=> Release: 2023-08-21a

advocacy_docs/partner_docs/ThalesCipherTrustManager/02-PartnerInformation.mdx, advocacy_docs/partner_docs/ThalesCipherTrustManager/03-SolutionSummary.mdx, advocacy_docs/partner_docs/ThalesCipherTrustManager/04-ConfiguringThalesCipherTrustManager.mdx, advocacy_docs/partner_docs/ThalesCipherTrustManager/05-UsingThalesCipherTrustManager.mdx, advocacy_docs/partner_docs/ThalesCipherTrustManager/06-CertificationEnvironment.mdx, advocacy_docs/partner_docs/ThalesCipherTrustManager/07-SupportandLogging.mdx, advocacy_docs/partner_docs/ThalesCipherTrustManager/index.mdx
=> Edits to Thales CipherTrust content

product_docs/docs/epas/15/reference/oracle_compatibility_reference/epas_compat_sql/22_create_directory.mdx, product_docs/docs/epas/15/reference/oracle_compatibility_reference/epas_compat_sql/23_create_function.mdx
fixes https://github.com/EnterpriseDB/docs/issues/4653
=> EPAS: front matter error message on bottom of page

advocacy_docs/partner_docs/ChemaxonJChemPostgreSQLCartridge/02-PartnerInformation.mdx, advocacy_docs/partner_docs/ChemaxonJChemPostgreSQLCartridge/03-SolutionSummary.mdx, advocacy_docs/partner_docs/ChemaxonJChemPostgreSQLCartridge/04-Configuration.mdx, advocacy_docs/partner_docs/ChemaxonJChemPostgreSQLCartridge/05-Using.mdx, advocacy_docs/partner_docs/ChemaxonJChemPostgreSQLCartridge/06-CertificationEnvironment.mdx, advocacy_docs/partner_docs/ChemaxonJChemPostgreSQLCartridge/index.mdx
=> First pass at Chemaxon content

product_docs/docs/epas/15/installing/uninstalling/linux_uninstall.mdx, product_docs/docs/epas/15/installing/windows/index.mdx, product_docs/docs/epas/15/installing/windows/managing_an_advanced_server_installation/controlling_server_startup_behavior_on_windows.mdx, product_docs/docs/epas/15/installing/windows/managing_an_advanced_server_installation/index.mdx, product_docs/docs/epas/15/installing/windows/managing_an_advanced_server_installation/starting_and_stopping_epas.mdx, product_docs/docs/epas/15/installing/windows/managing_an_advanced_server_installation/using_pg_ctl_to_control_advanced_server.mdx, product_docs/docs/epas/15/installing/windows/managing_an_advanced_server_installation/using_the_windows_services_applet.mdx
=> Rest of edits to install topics

advocacy_docs/partner_docs/CohesityDataProtectforPostgreSQL/02-PartnerInformation.mdx, advocacy_docs/partner_docs/CohesityDataProtectforPostgreSQL/03-SolutionSummary.mdx, advocacy_docs/partner_docs/CohesityDataProtectforPostgreSQL/04-ConfiguringCohesityDataProtectforPostgreSQL.mdx, advocacy_docs/partner_docs/CohesityDataProtectforPostgreSQL/05-UsingCohesityDataProtectforPostgreSQL.mdx, advocacy_docs/partner_docs/CohesityDataProtectforPostgreSQL/06-CertificationEnvironment.mdx, advocacy_docs/partner_docs/CohesityDataProtectforPostgreSQL/index.mdx
=> Edits to Cohesity doc

advocacy_docs/partner_docs/HPE/02-PartnerInformation.mdx, advocacy_docs/partner_docs/HPE/03-SolutionSummary.mdx, advocacy_docs/partner_docs/HPE/04-ConfiguringHPEGreenlake.mdx, advocacy_docs/partner_docs/HPE/05-UsingHPEGreenlake.mdx, advocacy_docs/partner_docs/HPE/06-CertificationEnvironment.mdx, advocacy_docs/partner_docs/HPE/07-SupportandLogging.mdx, advocacy_docs/partner_docs/HPE/index.mdx
=> Sample edits for HPE

product_docs/docs/pgd/5/parallelapply.mdx, product_docs/docs/pgd/5/reference/autopartition.mdx, product_docs/docs/pgd/5/reference/catalogs-visible.mdx, product_docs/docs/pgd/5/rel_notes/pgd_5.2.0_rel_notes.mdx, product_docs/docs/pgd/5/routing/installing_proxy.mdx, product_docs/docs/pgd/5/routing/proxy.mdx, product_docs/docs/pgd/5/upgrades/upgrade_paths.mdx
=> edits to PGD release PR4560

advocacy_docs/partner_docs/CohesityDataProtectforPostgreSQL/04-ConfiguringCohesityDataProtectforPostgreSQL.mdx
=> Edits to cohesity pr 4607

product_docs/docs/edb_plus/41/02_release_notes/edbplus_41.2_rel_notes.mdx
=> EDB*Plus: fixed rel notes typo

README.md, product_docs/docs/pgd/5/monitoring/otel.mdx, product_docs/docs/pgd/5/monitoring/sql.mdx
Minor improvements  to `README.md`.
Add link to the OpenTelemetry project in the OpenTelemetry chapter.
Fix broken links in the Monitoring through SQL chapter.
Signed-off-by: Lenz Grimmer <lenz.grimmer@enterprisedb.com>
=> Update README.md, add and fix links in PGD docs

product_docs/docs/ocl_connector/15/02_supported_platforms.mdx, product_docs/docs/ocl_connector/15/ocl_rel_notes/15.2.0.4_ocl_release_notes.mdx, product_docs/docs/ocl_connector/15/ocl_rel_notes/index.mdx
=> OCL Connector: 15.2.0.4 release

product_docs/docs/pgd/5/cli/configuring_cli.mdx
Includes changes made in PR4627
=> Edited Configuring PGD CLI topic

product_docs/docs/eprs/7/installing/upgrading_replication_server/index.mdx, product_docs/docs/eprs/7/installing/upgrading_replication_server/upgrading_linux.mdx, product_docs/docs/eprs/7/installing/upgrading_replication_server/upgrading_with_gui_installer.mdx, product_docs/docs/eprs/7/installing/upgrading_replication_server/upgrading_with_xdb_rpm_package.mdx
=> Replication Server: adding driver step to upgrade instructions

src/pages/index.js
=> Homepage: What's new - epas reorg

product_docs/docs/pgd/5/quickstart/index.mdx
=> PGD: fixing link and tweaking language

product_docs/docs/biganimal/release/reference/cli/managing_clusters.mdx
=> Small edits to this biganimal content

product_docs/docs/ocl_connector/15/03_libpq_compatibility.mdx, product_docs/docs/ocl_connector/15/installing/upgrading.mdx, product_docs/docs/ocl_connector/15/ocl_rel_notes/15.2.0.4_ocl_release_notes.mdx
=> OCL Connector: libpq requirement

advocacy_docs/security/advisories/cve20074639.mdx, advocacy_docs/security/advisories/cve201910128.mdx, advocacy_docs/security/advisories/cve202331043.mdx, advocacy_docs/security/advisories/cve202341113.mdx, advocacy_docs/security/advisories/cve202341114.mdx, advocacy_docs/security/advisories/cve202341115.mdx, advocacy_docs/security/advisories/cve202341116.mdx, advocacy_docs/security/advisories/cve202341117.mdx, advocacy_docs/security/advisories/cve202341118.mdx, advocacy_docs/security/advisories/cve202341119.mdx, advocacy_docs/security/advisories/cve202341120.mdx, advocacy_docs/security/advisories/index.mdx, advocacy_docs/security/index.mdx
Final CVEs in
CVE added to page title for clarity
New changes marked with updated date updated
Removed wrong format date for Updated note
Reordered all the indexes to descending CVE
=> Updates with final CVEs

product_docs/docs/eprs/7/installing/upgrading_replication_server/index.mdx, product_docs/docs/eprs/7/installing/upgrading_replication_server/upgrading_linux.mdx, product_docs/docs/eprs/7/installing/upgrading_replication_server/upgrading_with_gui_installer.mdx, product_docs/docs/eprs/7/installing/upgrading_replication_server/upgrading_with_xdb_rpm_package.mdx
=> Replication Server: fixing links

product_docs/docs/epas/15/epas_rel_notes/epas15_4_0_rel_notes.mdx, product_docs/docs/pge/15/release_notes/index.mdx, product_docs/docs/pge/15/release_notes/rel_notes15.4.mdx
Link to the draft PGE release notes: https://deploy-preview-4708--edb-docs-staging.netlify.app/docs/pge/latest/release_notes/rel_notes15.4/
Link to the draft EPAS updates: https://deploy-preview-4708--edb-docs-staging.netlify.app/docs/epas/latest/epas_rel_notes/epas15_4_0_rel_notes/
=> PGE and EPAS: 15.4 rel notes

product_docs/docs/edb_plus/41/02_release_notes/edbplus_41.2_rel_notes.mdx, product_docs/docs/edb_plus/41/04_using_edb_plus.mdx, product_docs/docs/edb_plus/41/06_command_summary.mdx
=> Small changes to pr4517 edbplus

product_docs/docs/biganimal/release/migration/index.mdx, product_docs/docs/edb_plus/41/02_release_notes/edbplus_41.2_rel_notes.mdx, product_docs/docs/edb_plus/41/04_using_edb_plus.mdx, product_docs/docs/edb_plus/41/06_command_summary.mdx, product_docs/docs/epas/15/epas_rel_notes/epas15_4_0_rel_notes.mdx, product_docs/docs/pge/15/release_notes/index.mdx, product_docs/docs/pge/15/release_notes/rel_notes15.4.mdx
- Added PGE 15.4 rel notes and updated the EPAS 15.4 rel notes
- BigAnimal: added link to Migration Handbook
- EPD*Plus copy edits
=> Release: 2023-08-28a

product_docs/docs/pgd/5/upgrades/upgrade_paths.mdx
=> Update guidance for upgrading PGD from 3.7 to 5

product_docs/docs/biganimal/release/overview/02_high_availability.mdx
=> BigAnimal: choosing config

advocacy_docs/security/advisories/cve.mdx.template, advocacy_docs/security/advisories/cve202341113.mdx, advocacy_docs/security/advisories/cve202341114.mdx, advocacy_docs/security/advisories/cve202341115.mdx, advocacy_docs/security/advisories/cve202341116.mdx, advocacy_docs/security/advisories/cve202341117.mdx, advocacy_docs/security/advisories/cve202341118.mdx, advocacy_docs/security/advisories/cve202341119.mdx, advocacy_docs/security/advisories/cve202341120.mdx, advocacy_docs/security/advisories/index.mdx, advocacy_docs/security/index.mdx
Updated as per ticket request DF-370
=> Updated all advisories and indexes

product_docs/docs/eprs/7/installing/upgrading_replication_server/upgrading_with_gui_installer.mdx, product_docs/docs/eprs/7/installing/upgrading_replication_server/upgrading_with_xdb_rpm_package.mdx
Reordered words for clarity and consistency; fixed contraction use in the area.
=> small edits to pr4696 eprs

product_docs/docs/ocl_connector/15/02_supported_platforms.mdx, product_docs/docs/ocl_connector/15/03_libpq_compatibility.mdx, product_docs/docs/ocl_connector/15/04_open_client_library/02_forming_a_connection_string.mdx, product_docs/docs/ocl_connector/15/04_open_client_library/03_compiling_and_linking_a_program.mdx, product_docs/docs/ocl_connector/15/04_open_client_library/04_ref_cursor_support.mdx, product_docs/docs/ocl_connector/15/04_open_client_library/05_ocl_function_reference.mdx, product_docs/docs/ocl_connector/15/04_open_client_library/06_ocl_error_codes_reference.mdx, product_docs/docs/ocl_connector/15/04_open_client_library/08_otl_support.mdx, product_docs/docs/ocl_connector/15/05_generating_the_ocl_trace.mdx, product_docs/docs/ocl_connector/15/06_using_ssl.mdx, product_docs/docs/ocl_connector/15/07_scram_compatibility.mdx, product_docs/docs/ocl_connector/15/installing/windows.mdx
=> some cleanup to the OCL doc

product_docs/docs/epas/15/fundamentals/sql_fundamentals/02_sql_tutorial/01_sample_database/01_sample_database_installation.mdx, product_docs/docs/epas/15/fundamentals/sql_fundamentals/02_sql_tutorial/08_deletions.mdx
Couple of minor corrections for EPAS15
=> Close admonition, correct path

product_docs/docs/biganimal/release/overview/02_high_availability.mdx
=> BigAnimal: spell out SLA for clarity

product_docs/docs/biganimal/release/overview/02_high_availability.mdx
=> Fixed capitalization error

product_docs/docs/biganimal/release/migration/index.mdx
=> Small edit to migration index

product_docs/docs/pgd/3.7/bdr/release-notes.mdx, product_docs/docs/pgd/3.7/pglogical/release-notes.mdx
=> Add BDR 3.7.22 release notes

product_docs/docs/pgd/4/rel_notes/index.mdx, product_docs/docs/pgd/4/rel_notes/pgd_4.3.1-2_rel_notes.mdx, product_docs/docs/pgd/4/rel_notes/pgd_4.3.2_rel_notes.mdx
=> Add PGD 4.3.2 release notes

product_docs/docs/biganimal/release/overview/02_high_availability.mdx
https://enterprisedb.atlassian.net/browse/CNP-3633
=> BigAnimal: switchover

product_docs/docs/pgd/4/rel_notes/pgd_4.3.2_rel_notes.mdx
=> Removed bogus line, added dates as per new spec

product_docs/docs/pgd/4/rel_notes/index.mdx, product_docs/docs/pgd/4/rel_notes/pgd_4.3.0+p1_rel_notes.mdx, product_docs/docs/pgd/4/rel_notes/pgd_4.3.0_rel_notes.mdx, product_docs/docs/pgd/4/rel_notes/pgd_4.3.1+p1_rel_notes.mdx, product_docs/docs/pgd/4/rel_notes/pgd_4.3.1+p2_rel_notes.mdx, product_docs/docs/pgd/4/rel_notes/pgd_4.3.1_rel_notes.mdx, product_docs/docs/pgd/4/rel_notes/pgd_4.3.2_rel_notes.mdx, product_docs/docs/pgd/5/upgrades/upgrade_paths.mdx
Draft of +p for clashing version numbers
=> Switched to +p(packagednumber)

product_docs/docs/tpa/23/INSTALL.mdx, product_docs/docs/tpa/23/architecture-M1.mdx, product_docs/docs/tpa/23/index.mdx, product_docs/docs/tpa/23/reference/2q_and_edb_repositories.mdx, product_docs/docs/tpa/23/reference/INSTALL-repo.mdx, product_docs/docs/tpa/23/reference/patroni.mdx, product_docs/docs/tpa/23/reference/tpaexec-download-packages.mdx, product_docs/docs/tpa/23/reference/tpaexec-info.mdx, product_docs/docs/tpa/23/tpaexec-configure.mdx
Import of TPA 23.21 - Release Notes to come.
=> TPA 23.21 autoimported

advocacy_docs/security/advisories/index.mdx, advocacy_docs/security/index.mdx
Corrected table text in index as per #4757 and updated the other other index. Already have plan to ensure this doesn't happen again.
=> Fix index pages as reported.

product_docs/docs/biganimal/release/overview/updates.mdx
Added new section to Periodic maintenance topic for maintenance for high-availability clusters. Also split content into separate sections.
=> BigAnimal: UPM-23888-Maintenance-for-HA-clusters

product_docs/docs/tpa/23/rel_notes/index.mdx, product_docs/docs/tpa/23/rel_notes/tpa_23.21_rel_notes.mdx, product_docs/docs/tpa/23/rel_notes/tpa_23.22_rel_notes.mdx
=> release notes for TPA 23.22 and correction to .21

product_docs/docs/biganimal/release/overview/updates.mdx, product_docs/docs/tpa/23/rel_notes/index.mdx, product_docs/docs/tpa/23/rel_notes/tpa_23.21_rel_notes.mdx, product_docs/docs/tpa/23/rel_notes/tpa_23.22_rel_notes.mdx
BigAnimal: maintenance for HA clusters
TPA 23.22 release
=> Release: 2023-09-06

product_docs/docs/biganimal/release/reference/cli/managing_clusters.mdx
Captures the intent of https://github.com/EnterpriseDB/docs/pull/3293
=> BigAnimal: listing valid values for properties in config file

product_docs/docs/pgd/4/upgrades/upgrade_paths.mdx, product_docs/docs/pgd/5/upgrades/upgrade_paths.mdx
Final docs as previously agreed in #4738 added.
=> Reloaded from broken PR to deploy sooner.

product_docs/docs/ocl_connector/15/ocl_rel_notes/15.2.0.4_ocl_release_notes.mdx
=> OCL Connector: fixed link

product_docs/docs/biganimal/release/reference/cli/managing_clusters.mdx, product_docs/docs/migration_toolkit/55/07_invoking_mtk/08_mtk_command_options.mdx, product_docs/docs/migration_toolkit/55/mtk_rel_notes/index.mdx, product_docs/docs/migration_toolkit/55/mtk_rel_notes/mtk_5561_rel_notes.mdx, product_docs/docs/ocl_connector/15/ocl_rel_notes/15.2.0.4_ocl_release_notes.mdx, product_docs/docs/pgd/4/harp/06_harp_manager.mdx, product_docs/docs/pgd/4/upgrades/upgrade_paths.mdx, product_docs/docs/pgd/5/upgrades/upgrade_paths.mdx
- Migration Toolkit 55.6.1
- BigAnimal: listing valid values for properties in config file
- OCL Connector: fixed link
=> Release: 2023-09-06a

CODEOWNERS
Made a codeowners file and got validation :)
=> Test a Codeowners addition

product_docs/docs/pgd/5/known_issues.mdx, product_docs/docs/pgd/5/limitations.mdx
Moved items to to limitations, added entry for Group Commit (temporary as future new Durability limitations will include this).
=> Essential fix and relocate of information

product_docs/docs/pgd/5/cli/discover_connections.mdx, product_docs/docs/pgd/5/cli/index.mdx, product_docs/docs/pgd/5/cli/installing_cli.mdx, product_docs/docs/pgd/5/cli/using_cli.mdx
=> edits to PGD CLI content

product_docs/docs/biganimal/release/pricing_and_billing/index.mdx
=> BigAnimal: pricing fix

product_docs/docs/biganimal/release/reference/cli/managing_clusters.mdx
=> small edit to biganimal pr4680

product_docs/docs/efm/4/05_using_efm.mdx
=> Edits to efm PR4788

product_docs/docs/efm/4/13_troubleshooting.mdx, product_docs/docs/efm/4/installing/prerequisites.mdx
=> minor edits to efm pr4520

advocacy_docs/supported-open-source/postgresql/overview.mdx
fixes https://github.com/EnterpriseDB/docs/issues/4793
=> PostgreSQL: fix link to language pack doc

product_docs/docs/postgres_for_kubernetes/1/index.mdx
Housekeeping changes for P4K from #4710, split into a separate PR
=> Updated index to align to CNPG and move things out of Enhanced

product_docs/docs/eprs/7/installing/upgrading_replication_server/index.mdx
https://enterprisedb.atlassian.net/browse/XDB-2125
=> Replication Server: upgrade paths

product_docs/docs/pgd/5/limitations.mdx
=> edits to limitations for BDR pr4752

product_docs/docs/epas/11/epas_compat_spl/15_object_types_and_objects/02_object_type_components/01_object_type_specification_syntax.mdx, product_docs/docs/epas/11/epas_compat_spl/15_object_types_and_objects/02_object_type_components/02_object_type_body_syntax.mdx, product_docs/docs/epas/12/epas_compat_spl/15_object_types_and_objects/02_object_type_components/01_object_type_specification_syntax.mdx, product_docs/docs/epas/12/epas_compat_spl/15_object_types_and_objects/02_object_type_components/02_object_type_body_syntax.mdx, product_docs/docs/epas/13/epas_compat_spl/15_object_types_and_objects/02_object_type_components/01_object_type_specification_syntax.mdx, product_docs/docs/epas/13/epas_compat_spl/15_object_types_and_objects/02_object_type_components/02_object_type_body_syntax.mdx, product_docs/docs/epas/14/epas_compat_spl/15_object_types_and_objects/02_object_type_components/01_object_type_specification_syntax.mdx, product_docs/docs/epas/14/epas_compat_spl/15_object_types_and_objects/02_object_type_components/02_object_type_body_syntax.mdx
https://enterprisedb.atlassian.net/browse/DB-2320
=> EPAS: constructor fix

product_docs/docs/pgd/3.7/bdr/upgrades/index.mdx
Improved document title to be more precise.
BDR-4081
=> Update BDR 3.7 Upgrading chapter

product_docs/docs/biganimal/release/getting_started/creating_a_cluster/index.mdx
https://enterprisedb.atlassian.net/browse/UPM-23829
=> BigAnimal: some cpu/memory is reserved by the system

product_docs/docs/biganimal/release/getting_started/02_connecting_to_your_cloud/index.mdx, product_docs/docs/biganimal/release/getting_started/creating_a_cluster/index.mdx, product_docs/docs/biganimal/release/getting_started/preparing_cloud_account/01_preparing_azure/index.mdx, product_docs/docs/biganimal/release/getting_started/preparing_cloud_account/02_preparing_aws.mdx, product_docs/docs/biganimal/release/getting_started/preparing_cloud_account/index.mdx, product_docs/docs/biganimal/release/getting_started/preparing_cloud_account/preparing_gcp/index.mdx, product_docs/docs/biganimal/release/index.mdx, product_docs/docs/biganimal/release/overview/02_high_availability.mdx, product_docs/docs/biganimal/release/overview/03_security/index.mdx, product_docs/docs/biganimal/release/overview/03a_region_support/index.mdx, product_docs/docs/biganimal/release/planning/choosing_cluster_type.mdx, product_docs/docs/biganimal/release/planning/choosing_postgres_distro.mdx, product_docs/docs/biganimal/release/planning/deployment_options/index.mdx, product_docs/docs/biganimal/release/planning/index.mdx
=> BigAnimal: planning section

product_docs/docs/biganimal/release/planning/choosing_postgres_distro.mdx
=> BigAnimal: Adding PGE distro for BAH

product_docs/docs/biganimal/release/overview/02_high_availability.mdx
=> BigAnimal: commit scopes recommendation

product_docs/docs/biganimal/release/getting_started/02_connecting_to_your_cloud/index.mdx, product_docs/docs/biganimal/release/getting_started/creating_a_cluster/index.mdx, product_docs/docs/biganimal/release/getting_started/preparing_cloud_account/01_preparing_azure/index.mdx, product_docs/docs/biganimal/release/getting_started/preparing_cloud_account/02_preparing_aws.mdx, product_docs/docs/biganimal/release/getting_started/preparing_cloud_account/index.mdx, product_docs/docs/biganimal/release/getting_started/preparing_cloud_account/preparing_gcp/index.mdx, product_docs/docs/biganimal/release/index.mdx, product_docs/docs/biganimal/release/overview/02_high_availability.mdx, product_docs/docs/biganimal/release/overview/03_security/index.mdx, product_docs/docs/biganimal/release/overview/03a_region_support/index.mdx, product_docs/docs/biganimal/release/planning/choosing_cluster_type.mdx, product_docs/docs/biganimal/release/planning/choosing_postgres_distro.mdx, product_docs/docs/biganimal/release/planning/deployment_options/index.mdx, product_docs/docs/biganimal/release/planning/index.mdx
BigAnimal:
- Added planning section 
- Fixed Postgres distros tables
- Added commit scopes recommendation
=> Release: 2023-09-11a

install_template/templates/products/edb-postgres-advanced-server/base.njk, product_docs/docs/epas/15/installing/linux_ppc64le/epas_rhel_7.mdx, product_docs/docs/epas/15/installing/linux_ppc64le/epas_rhel_8.mdx, product_docs/docs/epas/15/installing/linux_ppc64le/epas_rhel_9.mdx, product_docs/docs/epas/15/installing/linux_ppc64le/epas_sles_12.mdx, product_docs/docs/epas/15/installing/linux_ppc64le/epas_sles_15.mdx, product_docs/docs/epas/15/installing/linux_x86_64/epas_centos_7.mdx, product_docs/docs/epas/15/installing/linux_x86_64/epas_other_linux_8.mdx, product_docs/docs/epas/15/installing/linux_x86_64/epas_other_linux_9.mdx, product_docs/docs/epas/15/installing/linux_x86_64/epas_rhel_7.mdx, product_docs/docs/epas/15/installing/linux_x86_64/epas_rhel_8.mdx, product_docs/docs/epas/15/installing/linux_x86_64/epas_rhel_9.mdx, product_docs/docs/epas/15/installing/linux_x86_64/epas_sles_12.mdx, product_docs/docs/epas/15/installing/linux_x86_64/epas_sles_15.mdx
=> EPAS: link in install topics

product_docs/docs/epas/15/reference/sql_reference/01_sql_syntax/01_lexical_structure.mdx, product_docs/docs/epas/15/working_with_oracle_data/02_enhanced_compatibility_features.mdx
=> Light edits to EPAS content

docs/agreements/screenshot_policy.md
Moved screenshot policy into Docs repo from Confluence for greater visibility
=> Agreements: screenshot policy

docs/agreements/screenshot_policy.md, install_template/templates/products/edb-postgres-advanced-server/base.njk, product_docs/docs/biganimal/release/reference/cli/managing_clusters.mdx, product_docs/docs/epas/15/installing/linux_ppc64le/epas_rhel_7.mdx, product_docs/docs/epas/15/installing/linux_ppc64le/epas_rhel_8.mdx, product_docs/docs/epas/15/installing/linux_ppc64le/epas_rhel_9.mdx, product_docs/docs/epas/15/installing/linux_ppc64le/epas_sles_12.mdx, product_docs/docs/epas/15/installing/linux_ppc64le/epas_sles_15.mdx, product_docs/docs/epas/15/installing/linux_x86_64/epas_centos_7.mdx, product_docs/docs/epas/15/installing/linux_x86_64/epas_other_linux_8.mdx, product_docs/docs/epas/15/installing/linux_x86_64/epas_other_linux_9.mdx, product_docs/docs/epas/15/installing/linux_x86_64/epas_rhel_7.mdx, product_docs/docs/epas/15/installing/linux_x86_64/epas_rhel_8.mdx, product_docs/docs/epas/15/installing/linux_x86_64/epas_rhel_9.mdx, product_docs/docs/epas/15/installing/linux_x86_64/epas_sles_12.mdx, product_docs/docs/epas/15/installing/linux_x86_64/epas_sles_15.mdx, product_docs/docs/epas/15/reference/sql_reference/01_sql_syntax/01_lexical_structure.mdx, product_docs/docs/epas/15/working_with_oracle_data/02_enhanced_compatibility_features.mdx, product_docs/docs/pgd/4/upgrades/upgrade_paths.mdx, product_docs/docs/pgd/5/upgrades/upgrade_paths.mdx
- Misc copy edits
- Added Screenshot policy to agreements
- PGD: supported upgrade paths
- BigAnimal: fixed naming of config files
- EPAS 15 link in install tpoics
=> Release: 2023-09-12

advocacy_docs/migrating/oracle/factors_to_consider.mdx
Added some notes on server sizing. This is a question that comes up often in pre-sales. On the migration meeting on 2023-08-17 it was suggested to add this to the migration handbook.
=> Adding Server sizing considerations

product_docs/docs/pgd/5/limitations.mdx
=> Fixed link (was incorrectly going up tree)

product_docs/docs/biganimal/release/using_cluster/06_analyze_with_superset.mdx
Update superset documentation in BA about the connection details for user privileges.
=> docs: Update superset doc for user privileges

product_docs/docs/tpa/23/rel_notes/index.mdx, product_docs/docs/tpa/23/rel_notes/tpa_23.23_rel_notes.mdx
=> TPA 23.23 rel notes

product_docs/docs/epas/11/epas_rel_notes/epas11_21_33_rel_notes.mdx, product_docs/docs/epas/11/epas_rel_notes/index.mdx, product_docs/docs/epas/12/epas_rel_notes/epas12_16_21_rel_notes.mdx, product_docs/docs/epas/12/epas_rel_notes/index.mdx, product_docs/docs/epas/13/epas_rel_notes/epas13_12_18_rel_notes.mdx, product_docs/docs/epas/13/epas_rel_notes/index.mdx, product_docs/docs/epas/14/epas_rel_notes/epas14_9_1_rel_notes.mdx, product_docs/docs/epas/14/epas_rel_notes/index.mdx, product_docs/docs/epas/15/epas_rel_notes/epas15_4_1_rel_notes.mdx, product_docs/docs/epas/15/epas_rel_notes/index.mdx
=> EPAS patch release

product_docs/docs/pem/9/troubleshooting.mdx
=> PEM - Added content as per PEM-4835

product_docs/docs/epas/11/epas_rel_notes/epas11_21_33_rel_notes.mdx, product_docs/docs/epas/11/epas_rel_notes/index.mdx, product_docs/docs/epas/12/epas_rel_notes/epas12_16_21_rel_notes.mdx, product_docs/docs/epas/12/epas_rel_notes/index.mdx, product_docs/docs/epas/13/epas_rel_notes/epas13_12_18_rel_notes.mdx, product_docs/docs/epas/13/epas_rel_notes/index.mdx, product_docs/docs/epas/14/epas_rel_notes/epas14_9_1_rel_notes.mdx, product_docs/docs/epas/14/epas_rel_notes/index.mdx, product_docs/docs/epas/15/epas_rel_notes/epas15_4_1_rel_notes.mdx, product_docs/docs/epas/15/epas_rel_notes/index.mdx, product_docs/docs/pem/9/troubleshooting.mdx
- PEM: Fixed misc/ping in [PEM docs](https://github.com/EnterpriseDB/docs/pull/4835) by @nidhibhammar 
- EPAS: [patch release](https://github.com/EnterpriseDB/docs/pull/4838) by @nidhibhammar
=> Release: 2023-09-25

product_docs/docs/epas/11/epas_rel_notes/index.mdx, product_docs/docs/epas/12/epas_rel_notes/index.mdx, product_docs/docs/epas/13/epas_rel_notes/index.mdx, product_docs/docs/epas/14/epas_rel_notes/index.mdx, product_docs/docs/epas/15/epas_rel_notes/index.mdx
Added the latest version to the table
=> EPAS - Patch release update

product_docs/docs/pem/9/troubleshooting.mdx
=> Fixed typo in PEM content

product_docs/docs/biganimal/release/overview/02_high_availability.mdx
=> Fixed word order in recommendation

product_docs/docs/eprs/7/installing/upgrading_replication_server/index.mdx
=> edits to upgrade topic

advocacy_docs/pg_extensions/advanced_storage_pack/using.mdx
=> small cleanup to new content

product_docs/docs/biganimal/release/using_cluster/06_analyze_with_superset.mdx
=> Fixed a couple of typos

product_docs/docs/pgd/3.7/bdr/release-notes.mdx
Open admonition! FENCE THEM PEOPLE!
Fenced the Admonition.
=> Close open note on admonition

product_docs/docs/pgd/3.7/bdr/nodes.mdx
=> Fix small 3.7 typo

product_docs/docs/pgd/5/terminology.mdx
The Terminology section is almost completely reworked.
=> Replace/Refresh Terminology

advocacy_docs/partner_docs/KastenbyVeeam/02-PartnerInformation.mdx, advocacy_docs/partner_docs/KastenbyVeeam/03-SolutionSummary.mdx, advocacy_docs/partner_docs/KastenbyVeeam/04-ConfiguringVeeamKasten.mdx, advocacy_docs/partner_docs/KastenbyVeeam/05-UsingVeeamKasten.mdx, advocacy_docs/partner_docs/KastenbyVeeam/06-CertificationEnvironment.mdx, advocacy_docs/partner_docs/KastenbyVeeam/07-SupportandLogging.mdx, advocacy_docs/partner_docs/KastenbyVeeam/index.mdx
=> Edits to Kasten by Veeam guide

product_docs/docs/epas/15/installing/linux_install_details/managing_an_advanced_server_installation/modifying_the_data_directory_location.mdx
=> EPAS 15 - Updated, modifying the data directory location as per DB-2501

advocacy_docs/partner_docs/KastenbyVeeam/02-PartnerInformation.mdx, advocacy_docs/partner_docs/KastenbyVeeam/03-SolutionSummary.mdx, advocacy_docs/partner_docs/KastenbyVeeam/04-ConfiguringVeeamKasten.mdx, advocacy_docs/partner_docs/KastenbyVeeam/05-UsingVeeamKasten.mdx, advocacy_docs/partner_docs/KastenbyVeeam/06-CertificationEnvironment.mdx, advocacy_docs/partner_docs/KastenbyVeeam/07-SupportandLogging.mdx, advocacy_docs/partner_docs/KastenbyVeeam/index.mdx, product_docs/docs/biganimal/release/overview/03a_region_support/index.mdx, product_docs/docs/biganimal/release/using_cluster/02_connecting_your_cluster/01_connecting_from_azure/index.mdx, product_docs/docs/biganimal/release/using_cluster/05_monitoring_and_logging/monitoring_from_azure/index.mdx, product_docs/docs/epas/15/installing/linux_install_details/managing_an_advanced_server_installation/modifying_the_data_directory_location.mdx, product_docs/docs/pgd/3.7/bdr/nodes.mdx, product_docs/docs/pgd/5/rel_notes/pgd_5.2.0_rel_notes.mdx, product_docs/docs/pgd/5/terminology.mdx
- Edits to Kasten by Veeam guide by @ebgitelman in #4856  
- BigAnimal: Azure-BAH private networking by @ccestes & @ebgitelman in #4858
- PGD: Fix small 3.7 typo by @djw-m in #4878
- EPAS: Updated, modifying the data directory location as per DB-2501 by @nidhibhammar in #4881
- PGD: Update pgd_5.2.0_rel_notes.mdx by @djw-m in #4883
- PGD: Replace/Refresh Terminology by @djw-m  in #4865
=> Production Release: 2023-10-05

product_docs/docs/pgd/5/terminology.mdx
=> Expanded two phase commit entry.

product_docs/docs/pem/9/tuning_performance/performance_diagnostic.mdx
Triggered by re-org; link directly to extension.
=> Fix link to EDB Wait States

product_docs/docs/pgd/5/upgrades/upgrade_paths.mdx
=> copy edits to new upgrade info

product_docs/docs/biganimal/release/using_cluster/extensions.mdx
=> Edits needed for PostGis addition

product_docs/docs/biganimal/release/reference/cli/index.mdx
Added new section to the Using the BigAnimal CLI topic for "Creating credentials for an alternative organization"
=> BigAnimal-UPM-23034-Create-credentials-for-alternative-organizations

product_docs/docs/biganimal/release/overview/02_high_availability.mdx, product_docs/docs/biganimal/release/reference/cli/index.mdx, product_docs/docs/biganimal/release/using_cluster/extensions.mdx
BigAnimal
- Edits needed for PostGis addition #4889 by @ebgitelman 
- Create-credentials-for-alternative-organizations #4804 by @ebgitelman 
- Reverting the wrong published cross-CSP content #4896 by @nidhibhammar
=> Release: 2023-10-11

product_docs/docs/pgd/4/index.mdx, product_docs/docs/pgd/4/pgdlifecycle.mdx, product_docs/docs/pgd/5/index.mdx, product_docs/docs/pgd/5/pgdlifecycle.mdx
=> BDR-4136 PR - Lifecycle (for PGD 5 first)

product_docs/docs/efm/4/05_using_efm.mdx
missing line break broke formatting for the next line
=> Update 05_using_efm.mdx (Broken formatting)

product_docs/docs/pem/8/pem_rel_notes/864_rel_notes.mdx, product_docs/docs/pem/8/pem_rel_notes/index.mdx, product_docs/docs/pem/9/pem_rel_notes/922_rel_notes.mdx, product_docs/docs/pem/9/pem_rel_notes/931_rel_notes.mdx, product_docs/docs/pem/9/pem_rel_notes/index.mdx
- Added release notes for 9.3.1 and 8.4.3
- Corrected version title for PEM 9.2.2 release notes
=> PEM - 9.3.1 & 8.4.2 patch release

product_docs/docs/efm/4/installing/install_details.mdx, product_docs/docs/efm/4/installing/prerequisites.mdx
=> edits to non-generated install topics

product_docs/docs/eprs/7/installing/installation_details.mdx, product_docs/docs/eprs/7/installing/installing_jdbc_driver.mdx, product_docs/docs/eprs/7/installing/uninstalling.mdx, product_docs/docs/eprs/7/installing/upgrading_replication_server/upgrading_linux.mdx, product_docs/docs/eprs/7/installing/upgrading_replication_server/upgrading_with_gui_installer.mdx, product_docs/docs/eprs/7/installing/upgrading_replication_server/upgrading_with_xdb_rpm_package.mdx, product_docs/docs/eprs/7/installing/windows.mdx
=> edited nongenerated install topics for EPRS

product_docs/docs/jdbc_connector/42.5.4.1/installing/configuring_for_java.mdx, product_docs/docs/jdbc_connector/42.5.4.1/installing/upgrading.mdx, product_docs/docs/jdbc_connector/42.5.4.1/installing/windows.mdx
=> small edits to install

product_docs/docs/efm/4/installing/install_details.mdx, product_docs/docs/efm/4/installing/prerequisites.mdx, product_docs/docs/eprs/7/installing/installation_details.mdx, product_docs/docs/eprs/7/installing/installing_jdbc_driver.mdx, product_docs/docs/eprs/7/installing/uninstalling.mdx, product_docs/docs/eprs/7/installing/upgrading_replication_server/upgrading_linux.mdx, product_docs/docs/eprs/7/installing/upgrading_replication_server/upgrading_with_gui_installer.mdx, product_docs/docs/eprs/7/installing/upgrading_replication_server/upgrading_with_xdb_rpm_package.mdx, product_docs/docs/eprs/7/installing/windows.mdx, product_docs/docs/jdbc_connector/42.5.4.1/installing/configuring_for_java.mdx, product_docs/docs/jdbc_connector/42.5.4.1/installing/upgrading.mdx, product_docs/docs/jdbc_connector/42.5.4.1/installing/windows.mdx, product_docs/docs/pem/8/pem_rel_notes/864_rel_notes.mdx, product_docs/docs/pem/8/pem_rel_notes/index.mdx, product_docs/docs/pem/9/pem_rel_notes/922_rel_notes.mdx, product_docs/docs/pem/9/pem_rel_notes/931_rel_notes.mdx, product_docs/docs/pem/9/pem_rel_notes/index.mdx
- PEM new release #4892 by @nidhibhammar 
- Minor copy edits #4908 #4909 #4910 by @ebgitelman
=> Release: 2023-11-16

product_docs/docs/pgd/3.7/harp/01_release_notes/harp2.3.2_rel_notes.mdx, product_docs/docs/pgd/3.7/harp/01_release_notes/index.mdx, product_docs/docs/pgd/4/rel_notes/index.mdx, product_docs/docs/pgd/4/rel_notes/pgd_4.3.2+p1_rel_notes.mdx
Added release notes for HARP v2.3.2.
**Note:** I'll add the comment to this PR when release is done.
=> BDR-4188 - Add release notes for HARP v2.3.2

product_docs/docs/edb_plus/41/installing/configuring_linux_installation.mdx, product_docs/docs/edb_plus/41/installing/windows.mdx
=> edited non-generated install pages

product_docs/docs/epas/15/upgrading/05_performing_a_minor_version_update_of_an_rpm_installation.mdx
=> Edits to note

product_docs/docs/tpa/23/INSTALL.mdx, product_docs/docs/tpa/23/reference/pem.mdx
Install and PEM content updated
=> TPA 23.24 updates

product_docs/docs/pgbouncer/1/installing/03_uninstallation.mdx
=> Edits to install topics for pgbouncer

product_docs/docs/pgpool/4/installing/uninstalling.mdx, product_docs/docs/pgpool/4/installing/upgrading.mdx, product_docs/docs/pgpool/4/installing_extensions/creating_pgpool_extensions.mdx, product_docs/docs/pgpool/4/installing_extensions/uninstalling_extensions.mdx, product_docs/docs/pgpool/4/installing_extensions/upgrading_extensions.mdx
=> Edits to nongenerated install topics - pgpool

product_docs/docs/postgis/3.2/installing/uninstalling.mdx, product_docs/docs/postgis/3.2/installing/upgrading.mdx, product_docs/docs/postgis/3.2/installing/windows.mdx
=> edits_to_nongenerated_install_postgis

product_docs/docs/pgd/5/terminology.mdx
Removed pre-commit from language
=> Bdr 4160 docs document the 2 phases of two phase commit on terminology page

product_docs/docs/migration_portal/4/01_mp_release_notes/index.mdx, product_docs/docs/migration_portal/4/01_mp_release_notes/mp_4.6.0_rel_notes.mdx, product_docs/docs/migration_portal/4/known_issues_notes.mdx, product_docs/docs/pgd/5/appusage/index.mdx, product_docs/docs/pgd/5/cli/index.mdx
- Migration Portal 4.6.0 release #4891 by @nidhibhammar 
- PGD format fixes in app usage by @djw-m
=> Release: 2023-10-19

product_docs/docs/pgd/5/terminology.mdx
=> small edits to terminology

product_docs/docs/eprs/7/02_overview/02_replication_concepts_and_definitions/13_table_filters.mdx
=> Corrected spelling typo

product_docs/docs/postgres_for_kubernetes/1/addons.mdx
=> Cnp 4265 add kasten to the list of addons

product_docs/docs/pgd/3.6/index.mdx, product_docs/docs/pgd/5/appusage/index.mdx, product_docs/docs/pgd/5/sequences.mdx
Fixed some broken links from PDF link checking
=> Link fixing in PGD docs

product_docs/docs/biganimal/release/pricing_and_billing/index.mdx
Added GCP management costs to BigAnimal Management page
=> Added GCP management costs to BigAnimal Management page

product_docs/docs/biganimal/release/reference/cli/managing_clusters.mdx
Updated BigAnimal PGD CLI commands for version 3.1
=> BigAnimal: CLI updates for 3.1

install_template/templates/products/edb*plus/index.njk, product_docs/docs/edb_plus/41/installing/index.mdx
=> EDB*Plus - Added windows 2022 and 11 support as per ED-278

product_docs/docs/efm/4/04_configuring_efm/05_using_vip_addresses.mdx
- collect all behavioral notes up-front
- link to all cited configuration parameters
- Cleanly delineate documentation of the control script
- Clarify expectations for each step of testing procedure
Goal is to fully summarize the behavior of EFM when configured for use with VIP in the top sections of the topic, without relying on notes elsewhere (testing section, configuration properties reference) to understand the basic behavior.
Builds on work started by @EFM-Bobby in #4957 
Preview: https://deploy-preview-4958--edb-docs-staging.netlify.app/docs/efm/latest/04_configuring_efm/05_using_vip_addresses/
=> Reorganize the EFM virtual IP addresses topic

advocacy_docs/playground/footnotetest.mdx
Added Playground test for mdx bug rendering footnotes in tables out of order.
=> Add test for footnote bug

install_template/config.yaml, product_docs/docs/mysql_data_adapter/2/installing/linux_x86_64/mysql_debian_10.mdx, product_docs/docs/pge/16/deploy_options.mdx, product_docs/docs/pge/16/index.mdx, product_docs/docs/pge/16/installing/index.mdx, product_docs/docs/pge/16/installing/linux_x86_64/index.mdx, product_docs/docs/pge/16/installing/linux_x86_64/pge_centos_7.mdx, product_docs/docs/pge/16/installing/linux_x86_64/pge_debian_10.mdx, product_docs/docs/pge/16/installing/linux_x86_64/pge_debian_11.mdx, product_docs/docs/pge/16/installing/linux_x86_64/pge_other_linux_8.mdx, product_docs/docs/pge/16/installing/linux_x86_64/pge_other_linux_9.mdx, product_docs/docs/pge/16/installing/linux_x86_64/pge_rhel_7.mdx, product_docs/docs/pge/16/installing/linux_x86_64/pge_rhel_8.mdx, product_docs/docs/pge/16/installing/linux_x86_64/pge_rhel_9.mdx, product_docs/docs/pge/16/installing/linux_x86_64/pge_ubuntu_18.mdx, product_docs/docs/pge/16/installing/linux_x86_64/pge_ubuntu_20.mdx, product_docs/docs/pge/16/installing/linux_x86_64/pge_ubuntu_22.mdx, product_docs/docs/pge/16/operation.mdx, product_docs/docs/pge/16/parameters.mdx, product_docs/docs/pge/16/release_notes/index.mdx, product_docs/docs/pge/16/release_notes/rel_notes16.1.mdx, product_docs/docs/pge/16/replication.mdx, product_docs/docs/pge/16/sql_features/index.mdx, product_docs/docs/pge/16/sql_features/jdbctxnrollback.mdx, product_docs/docs/pge/16/sql_features/txnrollback.mdx, product_docs/docs/pge/16/tde.mdx
Added a PGE 16 section with 16.1 release notes.
=> First pass PGE 16.1 docs

product_docs/docs/pgd/3.7/bdr/release-notes.mdx, product_docs/docs/pgd/3.7/pglogical/release-notes.mdx
* Create release notes for PGD 3.7.23 and pglogical 3.7.23 and entry for bdr_pg_upgrade
=> Create release notes for PGD 3.7.23 and pglogical 3.7.23

product_docs/docs/pgd/4/rel_notes/index.mdx, product_docs/docs/pgd/4/rel_notes/pgd_4.3.3_rel_notes.mdx
* Create release notes for PGD v4.3.3 and add entries for CLI and Utilities
=> Create release notes for PGD v4.3.3

product_docs/docs/pgd/3.7/bdr/release-notes.mdx, product_docs/docs/pgd/5/overview/index.mdx, product_docs/docs/pgd/5/upgrades/tpa_overview.mdx
Fixes for various bad links from pdf builder
=> Mop up fixes post test deploy

product_docs/docs/pgd/3.7/pglogical/release-notes.mdx
Added missing notes and upgrades section
=> Added missing 3.7 relnotes

product_docs/docs/tpa/23/INSTALL-repo.mdx, product_docs/docs/tpa/23/INSTALL.mdx, product_docs/docs/tpa/23/ansible-and-sudo.mdx, product_docs/docs/tpa/23/architecture-PGD-Always-ON.mdx, product_docs/docs/tpa/23/firstclusterdeployment.mdx, product_docs/docs/tpa/23/reference/2q_and_edb_repositories.mdx, product_docs/docs/tpa/23/reference/air-gapped.mdx, product_docs/docs/tpa/23/reference/git-credentials.mdx, product_docs/docs/tpa/23/reference/index.mdx, product_docs/docs/tpa/23/reference/local-repo.mdx, product_docs/docs/tpa/23/reference/reconciling-local-changes.mdx, product_docs/docs/tpa/23/tpaexec-upgrade.mdx
Some small changes from the source to fix rendering issues. Otherwise, as per TPA content.
=> TPA 23.25 content imported

product_docs/docs/pem/9/pem_rel_notes/940_rel_notes.mdx, product_docs/docs/pem/9/pem_rel_notes/index.mdx
=> PEM -9.4 fixed release date and added entry to the table

product_docs/docs/pem/9/pem_rel_notes/940_rel_notes.mdx, product_docs/docs/pem/9/pem_rel_notes/index.mdx, product_docs/docs/pgd/5/security/role-management.mdx
PEM 9.4 Release Notes fix #5015 
BDR-4288 Improved PGD Roles Test #5012
=> Release: 2023-11-16c

product_docs/docs/pem/9/pem_rel_notes/940_rel_notes.mdx
=> PEM 9.4 - Added curl and libcurl vulnerabilities note

product_docs/docs/pgd/5/rel_notes/pgd_5.3.0_rel_notes.mdx
=> Edits to PGD PR4962

product_docs/docs/pgd/5/security/role-management.mdx
=> Updates to PGD PR5102

product_docs/docs/pgd/5/quickstart/quick_start_aws.mdx
=> Fix rogue "to" in end links

product_docs/docs/pem/9/pem_rel_notes/940_rel_notes.mdx
small update to remove first person
=> Edits to PEM PR 5021

product_docs/docs/pgd/5/overview/index.mdx, product_docs/docs/pgd/5/upgrades/tpa_overview.mdx
=> Edits to PGD PR5004

src/pages/index.js
The "what's new" was getting a bit stale - update with some recent releases
=> Update what's new section: EPAS 16 & P4K 1.21

product_docs/docs/pem/9/pem_rel_notes/940_rel_notes.mdx, product_docs/docs/pgd/4/bdr/catalogs.mdx, product_docs/docs/pgd/5/durability/index.mdx, product_docs/docs/pgd/5/monitoring/sql.mdx, product_docs/docs/pgd/5/overview/index.mdx, product_docs/docs/pgd/5/quickstart/quick_start_aws.mdx, product_docs/docs/pgd/5/rel_notes/pgd_5.3.0_rel_notes.mdx, product_docs/docs/pgd/5/security/role-management.mdx, product_docs/docs/pgd/5/upgrades/tpa_overview.mdx, product_docs/docs/pge/16/deploy_options.mdx, product_docs/docs/pge/16/index.mdx, product_docs/docs/pge/16/operation.mdx, product_docs/docs/pge/16/parameters.mdx, src/pages/index.js, src/templates/doc.js
- PGD: remove reference to the "bdr-enterprise" extension in 5.x docs, fix typo in 4.x "bdr.stat_subscription" description, role management content copy edits, release notes copy edits, fix rogue "to" in end links
- PEM: remove first person
- PGE: PGE 16 copy edits
- Fix for rendering interference in section index when ToC sidebar is shown
=> Release: 2023-11-21

product_docs/docs/biganimal/release/overview/03a_region_support/index.mdx
=> BigAnimal - Added supported region as per UPM-27095

advocacy_docs/community/contributing/index.mdx, advocacy_docs/community/contributing/releasenotes-styleguide.mdx
Added release notes style guide based on @ebgitelman proposal.
=> Added Release Notes Style Guide

product_docs/docs/pgd/5/quickstart/further_explore_failover.mdx, product_docs/docs/pgd/5/quickstart/quick_start_aws.mdx, product_docs/docs/pgd/5/quickstart/quick_start_docker.mdx, product_docs/docs/pgd/5/quickstart/quick_start_linux.mdx
global switched to local after report in #5041 
Various formattting changes.
=> Fix global/local issue to sync with 23.25

product_docs/docs/pem/8/pem_rel_notes/870_rel_notes.mdx, product_docs/docs/pem/8/pem_rel_notes/index.mdx
=> PEM - 8.7.0 release branch

product_docs/docs/pgd/4/rel_notes/index.mdx, product_docs/docs/pgd/4/rel_notes/pgd_4.0.0_rel_notes.mdx, product_docs/docs/pgd/4/rel_notes/pgd_4.0.1_rel_notes.mdx, product_docs/docs/pgd/4/rel_notes/pgd_4.0.2_rel_notes.mdx, product_docs/docs/pgd/4/rel_notes/pgd_4.0.3_rel_notes.mdx, product_docs/docs/pgd/4/rel_notes/pgd_4.1.0_rel_notes.mdx, product_docs/docs/pgd/4/rel_notes/pgd_4.1.1_rel_notes.mdx, product_docs/docs/pgd/4/rel_notes/pgd_4.2.0_rel_notes.mdx, product_docs/docs/pgd/4/rel_notes/pgd_4.2.1_rel_notes.mdx, product_docs/docs/pgd/4/rel_notes/pgd_4.2.2_rel_notes.mdx, product_docs/docs/pgd/4/rel_notes/pgd_4.3.0+p1_rel_notes.mdx, product_docs/docs/pgd/4/rel_notes/pgd_4.3.0_rel_notes.mdx, product_docs/docs/pgd/4/rel_notes/pgd_4.3.1+p1_rel_notes.mdx, product_docs/docs/pgd/4/rel_notes/pgd_4.3.1+p2_rel_notes.mdx, product_docs/docs/pgd/4/rel_notes/pgd_4.3.1_rel_notes.mdx, product_docs/docs/pgd/4/rel_notes/pgd_4.3.2+p1_rel_notes.mdx, product_docs/docs/pgd/4/rel_notes/pgd_4.3.3_rel_notes.mdx
Added dates from index page
Normalized dates to 3 char month name as per standard.
=>  BDR-4042-Docs-Update-release-notes-with-released-date 

advocacy_docs/supported-open-source/postgresql/uninstalling.mdx
Add note that data is not deleted to address #5037
=> Fix for #5037

product_docs/docs/tpa/23/platform-bare.mdx, product_docs/docs/tpa/23/reference/bdr.mdx, product_docs/docs/tpa/23/reference/reconciling-local-changes.mdx, product_docs/docs/tpa/23/reference/tpaexec-deprovision.mdx, product_docs/docs/tpa/23/tpaexec-configure.mdx
Refresh from repo with some manual fixes
=> TPA 23.26 updates

product_docs/docs/epas/16/index.mdx
=> Replace orace by oracle

product_docs/docs/biganimal/release/overview/02_high_availability/distributed_highavailability.mdx, product_docs/docs/biganimal/release/overview/02_high_availability/primary_standby_highavailability.mdx
=> edits to big animal high availability content PR4885

product_docs/docs/pgd/5/security/pgd-predefined-roles.mdx
Resolve BDR-4128 - "Incorrect statement".
Removed stale statement
=> Fix GRANT ROLE reference

product_docs/docs/biganimal/release/overview/02_high_availability/distributed_highavailability.mdx, product_docs/docs/biganimal/release/overview/02_high_availability/primary_standby_highavailability.mdx, product_docs/docs/epas/16/index.mdx, product_docs/docs/pgd/5/postgres-configuration.mdx, product_docs/docs/pgd/5/security/pgd-predefined-roles.mdx
#5063 Edits to BigAnimal HA content @ebgitelman 
#5068 Fixed reference to Grant Role in PGD @djw-m 
#5065 Typo fix @sergioenterprisedb 
#5071 PGD configuration note for bdr/pgaudit libraries @djw-m
=> Release: 2023-12-06

product_docs/docs/efm/4/04_configuring_efm/04_extending_efm_permissions.mdx
An old reference to efm 4.2 was missed along the way.
=> update old efm version reference

advocacy_docs/supported-open-source/postgresql/overview.mdx, advocacy_docs/supported-open-source/postgresql/uninstalling.mdx
=> Edits to postgresql uninstall topic pr5055

advocacy_docs/supported-open-source/postgresql/installing/linux_x86_64/postgresql_other_linux_8.mdx, advocacy_docs/supported-open-source/postgresql/installing/linux_x86_64/postgresql_other_linux_9.mdx, install_template/templates/products/postgresql/almalinux-8-or-rocky-linux-8.njk, install_template/templates/products/postgresql/almalinux-9-or-rocky-linux-9.njk
https://github.com/EnterpriseDB/docs/pull/5066 specified a PostgreSQL change that required a template change. I didn't have access to the branch mentioned in PR 5066  so I made the changes in this branch/PR.
=> fixes to template specified in PR 5066

product_docs/docs/efm/4/efm_quick_start/index.mdx
=> Update index.mdx with v4.8

product_docs/docs/pgd/5/postgres-configuration.mdx
=> Added missing period for pgd PR5071

product_docs/docs/eprs/7/installing/windows.mdx
Removed "please" and fixed a typo.
=> edits to EPRS PR5082

product_docs/docs/biganimal/release/using_cluster/01_postgres_access/index.mdx
=> BigAnimal - Superuser update as per UPM-24618

product_docs/docs/tpa/23/INSTALL-repo.mdx, product_docs/docs/tpa/23/INSTALL.mdx, product_docs/docs/tpa/23/reference/INSTALL-docker.mdx, product_docs/docs/tpa/23/reference/artifacts.mdx, product_docs/docs/tpa/23/reference/bdr.mdx, product_docs/docs/tpa/23/reference/distributions.mdx, product_docs/docs/tpa/23/reference/reconciling-local-changes.mdx, product_docs/docs/tpa/23/reference/tpaexec-deprovision.mdx, product_docs/docs/tpa/23/reference/tpaexec-download-packages.mdx, product_docs/docs/tpa/23/reference/tpaexec-reconfigure.mdx, product_docs/docs/tpa/23/reference/volumes.mdx, product_docs/docs/tpa/23/reference/yum_repositories.mdx, product_docs/docs/tpa/23/rel_notes/index.mdx, product_docs/docs/tpa/23/rel_notes/tpa_23.27_rel_notes.mdx
Updates to Python 3.9
Added Oracle Linux support notes
=> Imported changes for TPA 23.27

product_docs/docs/pgd/5/reference/commit-scopes.mdx
Add backlink from commit scope ref to durability
=> Add backlink from commit scope ref to durability

product_docs/docs/epas/16/epas_rel_notes/index.mdx
Added 16.1 link, moved existing link to 16.0.
Thanks @tureba
=> Update index.mdx links for releases

product_docs/docs/tpa/23/reference/bdr.mdx
=> TPA Patch for change already made upstream

src/components/advanced-search/filtering.js, src/components/main-content.js, src/components/search-navigation.js, src/components/search/formComps.js, src/components/search/index.js, src/constants/products.js, src/pages/404.js, src/pages/search.js, src/templates/doc.js
- Search only current version (if viewing versioned product) or latest versions of documentation
- Allow excluding specific products from search (pre-release, for now just PG4K PGD) while still allowing them to be searched.
Addresses [DF-380](https://enterprisedb.atlassian.net/browse/DF-380)
[DF-380]: https://enterprisedb.atlassian.net/browse/DF-380?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Search filter tweaks: version restrictions, pre-release product exclusion
