product_docs/docs/biganimal/release/using_cluster/01_postgres_access/index.mdx

Edits to Big Animal PR 5092

---

product_docs/docs/pgbouncer/1/pgbouncer_rel_notes/04_12100_rel_notes.mdx
product_docs/docs/pgbouncer/1/pgbouncer_rel_notes/05_12000_rel_notes.mdx
product_docs/docs/pgbouncer/1/pgbouncer_rel_notes/index.mdx

Added 1.20 and 1.21 release notes

EDB PgBouncer - 1.20 & 1.21 release notes

---

product_docs/docs/biganimal/release/using_cluster/01_postgres_access/index.mdx
product_docs/docs/pem/8/index.mdx
product_docs/docs/pgbouncer/1/pgbouncer_rel_notes/04_12100_rel_notes.mdx
product_docs/docs/pgbouncer/1/pgbouncer_rel_notes/05_12000_rel_notes.mdx
product_docs/docs/pgbouncer/1/pgbouncer_rel_notes/index.mdx

- PEM: correct compatibility table
- PgBouncer: 1.20 & 1.21 release notes
- Big Animal: edits to PR 5092

Release: 2024-01-02

---

product_docs/docs/pgd/3.7/bdr/configuration.mdx

Added note on bogus deprecation message.

BDR 3.7 Documentation fixes

---

product_docs/docs/lasso/4/appendix-a.mdx
product_docs/docs/lasso/4/configuration.mdx
product_docs/docs/lasso/4/describe.mdx
product_docs/docs/lasso/4/index.mdx
product_docs/docs/lasso/4/install.mdx
product_docs/docs/lasso/4/release-notes.mdx
product_docs/docs/lasso/4/report-types.mdx
product_docs/docs/lasso/4/return.mdx
product_docs/docs/lasso/4/security.mdx
product_docs/docs/lasso/4/usage.mdx

Edits to Lasso PR5085

---

product_docs/docs/migration_portal/4/01_mp_release_notes/index.mdx
product_docs/docs/migration_portal/4/01_mp_release_notes/mp_4.7.1_rel_notes.mdx
product_docs/docs/migration_portal/4/known_issues_notes.mdx

Added 4.7.1 release notes as per MIG-4907

Migration Portal - 4.7.1 release branch

---

product_docs/docs/eprs/7/07_common_operations/09_offline_snapshot.mdx

Addresses https://enterprisedb.atlassian.net/browse/XDB-2127

Added note as suggested in XDB-2127

---

product_docs/docs/pgd/5/node_management/logical_standby_nodes.mdx
product_docs/docs/pgd/5/overview/index.mdx
product_docs/docs/pgd/5/reference/nodes.mdx

Edits to PGD PR5137

---

product_docs/docs/epas/16/reference/oracle_compatibility_reference/epas_compat_cat_views/pg_views/index.mdx
product_docs/docs/epas/16/reference/oracle_compatibility_reference/epas_compat_cat_views/pg_views/pg_attribute.mdx
product_docs/docs/epas/16/reference/oracle_compatibility_reference/epas_compat_cat_views/pg_views/pg_authid.mdx
product_docs/docs/epas/16/reference/oracle_compatibility_reference/epas_compat_cat_views/pg_views/pg_class.mdx
product_docs/docs/epas/16/reference/oracle_compatibility_reference/epas_compat_cat_views/pg_views/pg_collation.mdx
product_docs/docs/epas/16/reference/oracle_compatibility_reference/epas_compat_cat_views/pg_views/pg_database.mdx
product_docs/docs/epas/16/reference/oracle_compatibility_reference/epas_compat_cat_views/pg_views/pg_namespace.mdx
product_docs/docs/epas/16/reference/oracle_compatibility_reference/epas_compat_cat_views/pg_views/pg_partitioned_table.mdx
product_docs/docs/epas/16/reference/oracle_compatibility_reference/epas_compat_cat_views/pg_views/pg_proc.mdx
product_docs/docs/epas/16/reference/oracle_compatibility_reference/epas_compat_cat_views/pg_views/pg_subscription.mdx
product_docs/docs/epas/16/reference/oracle_compatibility_reference/epas_compat_cat_views/pg_views/pg_synonym.mdx
product_docs/docs/epas/16/reference/oracle_compatibility_reference/epas_compat_cat_views/pg_views/pg_trigger.mdx
product_docs/docs/epas/16/reference/oracle_compatibility_reference/epas_compat_cat_views/pg_views/pg_type.mdx
product_docs/docs/epas/16/reference/oracle_compatibility_reference/epas_compat_cat_views/pg_views/pg_user.mdx

Edits to EPAS PR5038

---

product_docs/docs/lasso/4/describe.mdx
product_docs/docs/lasso/4/release-notes.mdx

Edits to Lasso PR 5138

---

product_docs/docs/biganimal/release/getting_started/index.mdx
product_docs/docs/biganimal/release/getting_started/managing_cluster.mdx

Added new topic for Managing a cluster
Updated index page

Adding pause and resume clusters for BigAnimal as per UPM-15341

---

advocacy_docs/pg_extensions/wait_states/index.mdx
advocacy_docs/pg_extensions/wait_states/installing.mdx

Modified Installing page to add instructions for PG and PGE
Addresses https://enterprisedb.atlassian.net/browse/DF-377
Also fixes #5067

Adding support for PostgreSQL and PGE to Wait States

---

product_docs/docs/pgd/5/limitations.mdx

First pass - expand the limitations section with a specific prohibition.

Limitations with mixed PGD text.

---

product_docs/docs/pge/15/index.mdx

Tiny fix to menu to follow up on expansion

Update index.mdx - add administration

---

product_docs/docs/pge/15/installing/component_locations.mdx
product_docs/docs/pge/16/installing/component_locations.mdx

New components file added
The * removed from both components files

Created PGE15 components page, removed asterisks from both pages

---

product_docs/docs/pgd/5/ddl.mdx

Extra headings and clarifying paras for DDL and DML locks. 
I can't go further as  changes to app messaging are not done.
Addresses:  https://enterprisedb.atlassian.net/browse/BDR-4195

Added clarifying notes to PGD locking criteria.

---

src/pages/index.js

Rotate PGE and Lasso into the what's new header

Feature PGE and Lasso doc updates

---

product_docs/docs/tpa/23/ansible-and-sudo.mdx
product_docs/docs/tpa/23/architecture-BDR-Always-ON.mdx
product_docs/docs/tpa/23/architecture-M1.mdx
product_docs/docs/tpa/23/architecture-PGD-Always-ON.mdx
product_docs/docs/tpa/23/configure-cluster.mdx
product_docs/docs/tpa/23/images/m1.dot
product_docs/docs/tpa/23/index.mdx
product_docs/docs/tpa/23/platform-aws.mdx
product_docs/docs/tpa/23/reference/2q_and_edb_repositories.mdx
product_docs/docs/tpa/23/reference/air-gapped.mdx
product_docs/docs/tpa/23/reference/apt_repositories.mdx
product_docs/docs/tpa/23/reference/artifacts.mdx
product_docs/docs/tpa/23/reference/barman.mdx
product_docs/docs/tpa/23/reference/bdr.mdx
product_docs/docs/tpa/23/reference/harp.mdx
product_docs/docs/tpa/23/reference/postgresql.conf.mdx
product_docs/docs/tpa/23/rel_notes/index.mdx
product_docs/docs/tpa/23/rel_notes/tpa_23.28_rel_notes.mdx
product_docs/docs/tpa/23/tpaexec-hooks.mdx
scripts/source/process-tpa-docs-auto.sh

TPA docs updated for 23.28
Auto import script updated for new internal repo.

Import 23.28 docs - update import to use tpa-internal.

---

product_docs/docs/migration_portal/4/01_mp_release_notes/mp_4.7.1_rel_notes.mdx
product_docs/docs/migration_portal/4/known_issues_notes.mdx

Edits to Migration Portal PR5155

---

product_docs/docs/eprs/7/07_common_operations/09_offline_snapshot.mdx

Edits to EPRS PR5133

---

product_docs/docs/biganimal/release/getting_started/managing_cluster.mdx

Edits to Big Animal pr 5095

---

advocacy_docs/pg_extensions/wait_states/installing.mdx

Edits to pg_extension PR 5088

---

product_docs/docs/pgd/5/limitations.mdx

Edits to PGD PR5150

---

product_docs/docs/pgd/5/appusage/feature-compatibility.mdx
product_docs/docs/pgd/5/appusage/index.mdx

Page and tables added. 
Linked to app usage section.
Rendered preview: https://deploy-preview-5147--edb-docs-staging.netlify.app/docs/pgd/latest/appusage/feature-compatibility/
Fixes: https://enterprisedb.atlassian.net/browse/BDR-4168

Adding PGD commit scope/feature interop tables

---

product_docs/docs/pgd/5/monitoring/sql.mdx

Edits to PGD PR5132

---

product_docs/docs/epas/16/reference/oracle_compatibility_reference/epas_compat_sql/33_create_schema.mdx

Admonition was malformed and didn't exit exposing code at the end of the page.

Fix overrunning admonition with fencing

---

product_docs/docs/pgd/5/choosing_server.mdx

Two of three addressed - no new docs needed
Third waiting on a separate update with note to add link

Resolving missing links in PGD choosing server page - BDR-3877

---

product_docs/docs/epas/14/upgrading/04_upgrading_an_installation_with_pg_upgrade/03_upgrading_to_advanced_server.mdx
product_docs/docs/epas/15/upgrading/04_upgrading_an_installation_with_pg_upgrade/03_upgrading_to_advanced_server.mdx
product_docs/docs/epas/16/upgrading/04_upgrading_an_installation_with_pg_upgrade/03_upgrading_to_advanced_server.mdx

see [DOCS-66](https://enterprisedb.atlassian.net/browse/DOCS-66)
[DOCS-66]: https://enterprisedb.atlassian.net/browse/DOCS-66?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

EPAS upgrading: correct product name, update version in examples (DOCS66)

---

product_docs/docs/epas/15/epas_security_guide/tde_feature.mdx
product_docs/docs/epas/16/epas_security_guide/tde_feature.mdx
product_docs/docs/tde/15/index.mdx

Correct version coverage for TDE

---

product_docs/docs/biganimal/release/using_cluster/05_monitoring_and_logging/third_party_integrations/datadog.mdx
product_docs/docs/biganimal/release/using_cluster/05_monitoring_and_logging/third_party_integrations/index.mdx
product_docs/docs/biganimal/release/using_cluster/05_monitoring_and_logging/third_party_integrations/newrelic.mdx

Added the topic under Monitoring and logging
[Deployment preview](https://deploy-preview-5154--edb-docs-staging.netlify.app/docs/biganimal/latest/using_cluster/05_monitoring_and_logging/third_party_integrations/)
* [UPM-27644](https://enterprisedb.atlassian.net/browse/UPM-27644)
* [UPM-24655 3rd Party Monitoring](https://enterprisedb.atlassian.net/browse/UPM-24655)
* [UPM-27110](https://enterprisedb.atlassian.net/browse/UPM-27110)
[UPM-27644]: https://enterprisedb.atlassian.net/browse/UPM-27644?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[UPM-27110]: https://enterprisedb.atlassian.net/browse/UPM-27110?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

BigAnimal - Third-party integrations as per UPM-27644

---

product_docs/docs/epas/15/epas_security_guide/04_sslutils.mdx
product_docs/docs/epas/15/managing_performance/02_index_advisor/index.mdx
product_docs/docs/epas/15/managing_performance/02_index_advisor/installing_index_advisor.mdx
product_docs/docs/pem/9/profiling_workloads/index_advisor.mdx

Revised documents for ssutils to include install instructions
Created install instructions for Index Advisor
Indirectly addresses https://enterprisedb.atlassian.net/browse/PEM-4665

Install procedures for sslutils and index advisor in EPAS v 15

---

product_docs/docs/biganimal/release/release_notes/index.mdx
product_docs/docs/biganimal/release/release_notes/jan_2024_rel_notes.mdx
tools/user/import/bareleasenotes/barelease.js
tools/user/import/bareleasenotes/package-lock.json
tools/user/import/bareleasenotes/package.json

New tool - docs in confluence https://enterprisedb.atlassian.net/wiki/spaces/DCBC/pages/3514695702/EDBDocs+tooling#The-tools%2Fuser%2Fimport%2Fbareleasenotes-tool
Updated BA release notes using tool.

Docs-87: Create a release notes harvester for big animal

---

product_docs/docs/pgd/5/index.mdx

Edit to overview removing claim.

---

product_docs/docs/pgd/5/consistency/conflicts.mdx

Edits to PGD PR5192

---

product_docs/docs/postgres_for_kubernetes/1/rel_notes/1_22_0_rel_notes.mdx

Correct release date for Postgres for Kubernetes 1.22.0

---

product_docs/docs/pgd/5/appusage/feature-compatibility.mdx

Edits to PGD PR5157

---

product_docs/docs/biganimal/release/getting_started/managing_cluster.mdx

Edits to Big Animal PR5188

---

product_docs/docs/epas/11/epas_compat_bip_guide/03_built-in_packages/15_dbms_scheduler/03_create_program.mdx
product_docs/docs/epas/11/epas_compat_bip_guide/03_built-in_packages/15_dbms_scheduler/04_create_schedule.mdx
product_docs/docs/epas/12/epas_compat_bip_guide/03_built-in_packages/15_dbms_scheduler/03_create_program.mdx
product_docs/docs/epas/12/epas_compat_bip_guide/03_built-in_packages/15_dbms_scheduler/04_create_schedule.mdx
product_docs/docs/epas/13/epas_compat_bip_guide/03_built-in_packages/15_dbms_scheduler/03_create_program.mdx
product_docs/docs/epas/13/epas_compat_bip_guide/03_built-in_packages/15_dbms_scheduler/04_create_schedule.mdx
product_docs/docs/epas/14/epas_compat_bip_guide/03_built-in_packages/15_dbms_scheduler/03_create_program.mdx
product_docs/docs/epas/14/epas_compat_bip_guide/03_built-in_packages/15_dbms_scheduler/04_create_schedule.mdx
product_docs/docs/epas/15/reference/oracle_compatibility_reference/epas_compat_bip_guide/03_built-in_packages/15_dbms_scheduler/03_create_program.mdx
product_docs/docs/epas/15/reference/oracle_compatibility_reference/epas_compat_bip_guide/03_built-in_packages/15_dbms_scheduler/04_create_schedule.mdx
product_docs/docs/epas/16/reference/oracle_compatibility_reference/epas_compat_bip_guide/03_built-in_packages/15_dbms_scheduler/03_create_program.mdx
product_docs/docs/epas/16/reference/oracle_compatibility_reference/epas_compat_bip_guide/03_built-in_packages/15_dbms_scheduler/04_create_schedule.mdx

typos fixed in all versions of EPAS
Addresses https://enterprisedb.atlassian.net/browse/DB-2610

fix typos in version 11-16

---

product_docs/docs/pgd/5/architectures.mdx

Change in Architectures text as requested.

De-emphasised TPA for deployment for BDR-4389

---

product_docs/docs/biganimal/release/using_cluster/05_monitoring_and_logging/third_party_integrations/datadog.mdx
product_docs/docs/biganimal/release/using_cluster/05_monitoring_and_logging/third_party_integrations/newrelic.mdx

Added a note in both the topics as per suggestion from Craig in Slack: https://edb-starlight.slack.com/archives/C061LSJCJCV/p1706651253584299

BigAnimal - Datadog and NewRelic hotfix

---

product_docs/docs/pgd/5/reference/nodes-management-interfaces.mdx

Edits to pgd pr 5200

---

product_docs/docs/pem/8/monitoring_BDR_nodes.mdx
product_docs/docs/pem/9/monitoring_BDR_nodes.mdx
product_docs/docs/pgd/3.7/index.mdx
product_docs/docs/pgd/4/bdr/index.mdx
product_docs/docs/pgd/4/index.mdx
product_docs/docs/pgd/5/overview/index.mdx

All links in docs now linked to original blog post.

Linking 5x claim wherever it occurs (older PGD, PEM)

---

product_docs/docs/biganimal/release/using_cluster/05_monitoring_and_logging/third_party_integrations/datadog.mdx
product_docs/docs/biganimal/release/using_cluster/05_monitoring_and_logging/third_party_integrations/index.mdx
product_docs/docs/biganimal/release/using_cluster/05_monitoring_and_logging/third_party_integrations/newrelic.mdx

Edits to Big Animal PR5154

---

product_docs/docs/pgd/5/routing/index.mdx

Downcase incorrectly cased The

---

product_docs/docs/pgd/5/terminology.mdx

Fix headings

---

product_docs/docs/pgd/5/reference/nodes-management-interfaces.mdx

Edits to PGD pr5209

---

product_docs/docs/tpa/23/rel_notes/index.mdx
product_docs/docs/tpa/23/rel_notes/tpa_23.28_rel_notes.mdx

Correct release year to 2024

---

product_docs/docs/epas/16/reference/oracle_compatibility_reference/04_partitioning_commands_compatible_with_oracle_databases/limitations.mdx

Edits to EPAS PR5198

---

product_docs/docs/biganimal/release/using_cluster/05_monitoring_and_logging/monitoring_using_pemx/index.mdx

Update index.mdx with spelling correction

---

product_docs/docs/pem/9/considerations/pem_security_best_practices/apache_httpd_security_configuration.mdx

Typo (I think) pme.conf -> pem.conf

---

product_docs/docs/lasso/4/describe.mdx
product_docs/docs/lasso/4/release-notes.mdx
product_docs/docs/lasso/4/report-types.mdx
product_docs/docs/lasso/4/usage.mdx

Lasso 4.13.0 release

---

advocacy_docs/community/contributing/styleguide.mdx

I was going through the style guide, noticed two broken links, and fixed them.

Correcting broken links

---

product_docs/docs/pgd/5/reference/nodes-management-interfaces.mdx

Edits to PGD pr5199

---

product_docs/docs/epas/12/epas_rel_notes/index.mdx
product_docs/docs/epas/13/epas_rel_notes/index.mdx

Fix side bar order of EPAS release notes

---

product_docs/docs/biganimal/release/using_cluster/05_monitoring_and_logging/third_party_integrations/datadog.mdx

Clarify distinction between node and container
Reduce repetition
Minor structure changes

Make wording around DD costs more concise

---

product_docs/docs/postgres_for_kubernetes/1/rel_notes/1_15_rel_notes.mdx

Fix incorrect version in a couple of places; correct link.

DF-398: fix typo in PG4K 1.15 release notes

---

advocacy_docs/pg_extensions/query_advisor/using.mdx

change view name from query_advisor_qualstat to query_advisor_qualstats

change view name from query_advisor_qualstat to query_advisor_qualstats

---

product_docs/docs/lasso/4/describe.mdx
product_docs/docs/lasso/4/release-notes.mdx
product_docs/docs/lasso/4/report-types.mdx

Edits to Lasso PR5245

---

product_docs/docs/pgd/5/node_management/index.mdx
product_docs/docs/pgd/5/node_management/maintainance_with_proxies.mdx

Edits to PGD PR5172

---

advocacy_docs/pg_extensions/pg_failover_slots/configuring.mdx

Modified Configuring topic to add prerequisites
Addresses https://github.com/EnterpriseDB/docs/issues/5277

Added missing prerequisites to PG Failover Slots

---

product_docs/docs/pwr/1/configuring.mdx
product_docs/docs/pwr/1/index.mdx
product_docs/docs/pwr/1/installing.mdx
product_docs/docs/pwr/1/rel_notes/index.mdx
product_docs/docs/pwr/1/using.mdx

Create simple index cards 
Repositioned release notes so they appear first

Index cards for Postgres Workload Report

---

product_docs/docs/pgd/5/upgrades/upgrade_paths.mdx

Update docs on upgrade path, 3.7 to 5 is now supported

---

advocacy_docs/security/assessments/cve-2024-0985.mdx
advocacy_docs/security/assessments/cve-2024-1597.mdx
advocacy_docs/security/assessments/index.mdx
advocacy_docs/security/index.mdx
advocacy_docs/security/templates/assessmentsindex.njs
advocacy_docs/security/templates/securityindex.njs
tools/automation/generators/advisoryindex/advisoryindex.js

Added Assessments
Added two assements
Updated scripts and templates

Rework security to support assessment, added 0985 or 1597 (DOCS-124)

---

product_docs/docs/biganimal/release/overview/03a_region_support/index.mdx
product_docs/docs/biganimal/release/reference/cli/managing_clusters.mdx
product_docs/docs/biganimal/release/release_notes/feb_2024_rel_notes.mdx
product_docs/docs/biganimal/release/release_notes/index.mdx

Added region support and release notes for Feb 2024

BigAnimal - Region support and release notes

---

product_docs/docs/pgd/5/upgrades/upgrade_paths.mdx

Edits to PGD PR5306

---

product_docs/docs/efm/4/07_using_efm_utility.mdx
product_docs/docs/efm/4/upgrading.mdx

For style guide adherence and general edit.

Copy edits to EFM PR5256

---

product_docs/docs/epas/16/upgrading/03_limitations.mdx

Removed some text from Upgrading > Upgrading considerations
Addresses https://enterprisedb.atlassian.net/browse/DB-2613

Removed two limitations from EPAS upgrade

---

product_docs/docs/hadoop_data_adapter/2/02_requirements_overview.mdx
product_docs/docs/mongo_data_adapter/5/02_requirements_overview.mdx
product_docs/docs/mysql_data_adapter/2/02_requirements_overview.mdx

Removed EPAS 11 from all 3 FDWs

FDWS - Remove EPAS 11

---

product_docs/docs/pem/8/pem_rel_notes/871_rel_notes.mdx
product_docs/docs/pem/8/pem_rel_notes/index.mdx
product_docs/docs/pem/9/pem_rel_notes/951_rel_notes.mdx
product_docs/docs/pem/9/pem_rel_notes/index.mdx

Added release notes for PEM 9.5.1 and PEM 8.7.1 as per [DOCS-151](https://enterprisedb.atlassian.net/browse/DOCS-151)
[DOCS-151]: https://enterprisedb.atlassian.net/browse/DOCS-151?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

PEM - 9.5.1 & 8.7.1 release

---

product_docs/docs/pgd/5/rel_notes/pgd_5.4.0_rel_notes.mdx

Modify release notes to match customer mail

---

product_docs/docs/pgd/5/durability/commit-scopes.mdx

One missed page from BDR-4575.

ALL with GROUP COMMIT must use Raft

---

.github/workflows/deploy-develop.yml
.github/workflows/deploy-draft.yml
.github/workflows/deploy-main.yml
.github/workflows/sync-and-process-files.yml
.github/workflows/sync-issues.yml

Chore: update action versions (kill GitHub warnings)

---

product_docs/docs/lasso/4/describe.mdx
product_docs/docs/lasso/4/install.mdx
product_docs/docs/lasso/4/release-notes.mdx
product_docs/docs/lasso/4/report-types.mdx

Lasso release 4.14.0

---

product_docs/docs/biganimal/release/using_cluster/05_monitoring_and_logging/monitoring_using_biganimal_observability/index.mdx

Renamed multi-line charts to line charts

BigAnimal - pemx typo fix

---

product_docs/docs/tde/15/enabling_tde.mdx

Typo in enabling_tde.mdx

---

advocacy_docs/security/assessments/index.mdx
advocacy_docs/security/index.mdx

Update to indexes for fix to cve-2024-1597

---

product_docs/docs/pgd/5/cli/installing_cli.mdx

Edits to PGD PR5317

---

product_docs/docs/pgd/5/durability/commit-scopes.mdx

Added details on clearing commit scopes

Add details on clearing commit scopes

---

product_docs/docs/biganimal/release/using_cluster/05_monitoring_and_logging/monitoring_using_biganimal_observability/index.mdx

Edits to BigAnimal PR5319

---

product_docs/docs/pgbouncer/1/pgbouncer_rel_notes/03_12200_rel_notes.mdx
product_docs/docs/pgbouncer/1/pgbouncer_rel_notes/index.mdx

Added release notes as per [RL-50](https://enterprisedb.atlassian.net/browse/RL-50)
[RL-50]: https://enterprisedb.atlassian.net/browse/RL-50?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Pgbouncer - 1.22.0.0 release branch

---

product_docs/docs/postgres_for_kubernetes/1/samples/cluster-example-tde.yaml

Missing cluster-example-tde.yaml file.

DOCS-208 - Re-add the missing example tde file.

---

product_docs/docs/biganimal/release/reference/access_key/index.mdx

Updated Access key creation steps as per UPM-31502

BigAnimal - Access key update

---

product_docs/docs/pgd/5/upgrades/upgrade_paths.mdx

Fix broken link upgrade_paths.mdx

Fix broken link upgrade_paths.mdx

---

product_docs/docs/biganimal/release/index.mdx
product_docs/docs/biganimal/release/known_issues/index.mdx
product_docs/docs/biganimal/release/known_issues/known_issues_dha.mdx

New Known Issues section with sub-page for known issues for DHA/PGD

First draft of known issues section

---

product_docs/docs/tpa/23/rel_notes/index.mdx
product_docs/docs/tpa/23/rel_notes/tpa_23.31_rel_notes.mdx

Release notes for emergency 23.31 release

---

product_docs/docs/biganimal/release/migration/dha_bulk_migration.mdx
product_docs/docs/biganimal/release/migration/index.mdx

Drafting of bulk loading guide
For revision. 
(PR as draft)

Bulk loading guide

---

product_docs/docs/biganimal/release/getting_started/creating_a_cluster/index.mdx
product_docs/docs/biganimal/release/migration/dha_bulk_migration.mdx
product_docs/docs/biganimal/release/migration/index.mdx
product_docs/docs/pwr/1/configuring.mdx

#5407 BigAnimal DHA bulk loading guide
#5406 PWR: Yaml clarification
#5390 BigAnimal Google IOPS removal

Release 2024-03-20b

---

product_docs/docs/pgd/3.7/harp/01_release_notes/harp2.4.0_rel_notes.mdx
product_docs/docs/pgd/3.7/harp/01_release_notes/index.mdx

Create release notes for harp 2.4.0. for PGD 3.7

Create release notes for harp 2.4.0. for PGD 3.7

---

product_docs/docs/biganimal/release/getting_started/creating_a_cluster/index.mdx

Reverts EnterpriseDB/docs#5410

Revert "Update index.mdx"

---

product_docs/docs/biganimal/release/migration/dha_bulk_migration.mdx
product_docs/docs/biganimal/release/migration/index.mdx

Edits to BigAnimal PR5407

---

product_docs/docs/biganimal/release/getting_started/creating_a_cluster/index.mdx
product_docs/docs/biganimal/release/migration/dha_bulk_migration.mdx
product_docs/docs/biganimal/release/migration/index.mdx
product_docs/docs/biganimal/release/using_cluster/fault_injection_testing/images/biganimal_faultinjectiontest_1.png
product_docs/docs/biganimal/release/using_cluster/fault_injection_testing/images/biganimal_faultinjectiontest_2.png
product_docs/docs/biganimal/release/using_cluster/fault_injection_testing/images/biganimal_faultinjectiontest_3.png
product_docs/docs/biganimal/release/using_cluster/fault_injection_testing/images/biganimal_faultinjectiontest_4.png
product_docs/docs/biganimal/release/using_cluster/fault_injection_testing/index.mdx
product_docs/docs/biganimal/release/using_cluster/index.mdx
product_docs/docs/pgd/3.7/harp/01_release_notes/harp2.4.0_rel_notes.mdx
product_docs/docs/pgd/3.7/harp/01_release_notes/index.mdx

#5422 Initial PGD Fault injection testing
#5417 Harp 2.4.0 release notes for PGD 3.7

Release 2024-03-20 (c)

---

product_docs/docs/biganimal/release/reference/access_key/index.mdx

Edits to BigAnimal PR5373

---

product_docs/docs/tpa/23/tower.mdx
src/pages/index.js

Feature latest releases for PGD & TPA.
Also bring in @ebgitelman's fixes for TPA's Tower topic, since linking to it in its current state is not great

update featured topics

---

product_docs/docs/biganimal/release/known_issues/index.mdx
product_docs/docs/biganimal/release/known_issues/known_issues_dha.mdx

Edits to BigAnimal PR5405

---

product_docs/docs/biganimal/release/using_cluster/02_connecting_your_cluster/01_connecting_from_azure/index.mdx

Here is the latest Azure CLI response 
"ipConfigurations": [
{
"etag": "W/\"a064b28b-97df-4332-b884-6f50683629c3\"",
"id": "/subscriptions/c80801ad-55a3-41b1-8ace-6dfc1941b712/resourceGroups/basupport/providers/Microsoft.Network/networkInterfaces/shan-end-nic/ipConfigurations/privateEndpointIpConfig.7446ff66-dcdf-4384-b47b-88487dae86f8",
"name": "privateEndpointIpConfig.7446ff66-dcdf-4384-b47b-88487dae86f8",
"primary": true,
"privateIPAddress": "10.6.0.6",
"privateIPAddressVersion": "IPv4",
"privateIPAllocationMethod": "Dynamic",
"privateLinkConnectionProperties": {
"fqdns": [],
"groupId": "",
"requiredMemberName": ""
},
"provisioningState": "Succeeded",
"resourceGroup": "basupport",
"subnet": {
"id": "/subscriptions/c80801ad-55a3-41b1-8ace-6dfc1941b712/resourceGroups/basupport/providers/M …

Azure CLI Command Updated

---

product_docs/docs/pgd/5/admin-tpa/installing.mdx

Added a redirect to tpa installing

Fix redirect for software downloads

---

product_docs/docs/biganimal/release/known_issues/index.mdx
product_docs/docs/biganimal/release/known_issues/known_issues_dha.mdx
product_docs/docs/biganimal/release/migration/dha_bulk_migration.mdx
product_docs/docs/biganimal/release/using_cluster/02_connecting_your_cluster/01_connecting_from_azure/index.mdx
product_docs/docs/efm/4/05_using_efm.mdx
product_docs/docs/efm/4/13_troubleshooting.mdx
product_docs/docs/pgd/5/admin-tpa/installing.mdx

#5421 Copyedits to BigAnimal PGD
#5419 Biganimal Bulk loading - remove DHA acronym
#5435 Updated Azure CLI Command
#5437 Add EFM information on startup log
#5440 Fix TPA redirection

Release 25 03 2024a

---

product_docs/docs/pgd/4/bdr/catalogs.mdx

Added in missing fields as per #5414 for 5.0

Follow up backport: conflict_history missing fields

---

product_docs/docs/pgd/5/quickstart/further_explore_conflicts.mdx
product_docs/docs/pgd/5/quickstart/further_explore_failover.mdx

Just added a note to prefix both xpanes installation sections.

DOCS-190: Add note on xpanes explaining not mandatory

---

product_docs/docs/pgd/5/quickstart/further_explore_failover.mdx

DOCS-203 - Added a note on the barman usage and offer recommended practice

---

product_docs/docs/biganimal/release/getting_started/creating_a_cluster/index.mdx

Reverts EnterpriseDB/docs#5424 - PGE updates for documentation

Revert "Revert "Update index.mdx""

---

product_docs/docs/biganimal/release/getting_started/creating_a_cluster/index.mdx

Added two notes to Creating a cluster topic.
Addresses https://enterprisedb.atlassian.net/browse/UPM-30030.

Notes about storage and memory requirements in BigAnimal

---

product_docs/docs/pgd/5/rel_notes/index.mdx
product_docs/docs/pgd/5/rel_notes/pgd_5.4.1_rel_notes.mdx

Release notes for PGD 5.4.1

---

advocacy_docs/pg_extensions/ldap_sync/configuring.mdx
advocacy_docs/pg_extensions/ldap_sync/installing.mdx

Update docs to use pg_cron instead of pgagent.

Update ldap_sync docs to use pg_cron instead of pgagent

---

product_docs/docs/pgd/5/quickstart/quick_start_aws.mdx

Reworked the AWS section for quick start AWS. 
Removed the AWS CLI dependency mention.

AWS Easier onboard

---

README.md

DOCS-195:  Readme - update versions node, npm

---

advocacy_docs/pg_extensions/pg_squeeze/using.mdx
product_docs/docs/pgd/5/rel_notes/index.mdx
product_docs/docs/pgd/5/rel_notes/pgd_5.4.1_rel_notes.mdx

#5464 Added information about lock levels to pq_squeeze
#5461 PGD 5.4.1 Release Notes

Release: 2024-04-03b

---

product_docs/docs/biganimal/release/known_issues/known_issues_dha.mdx

Docs-281 - Added 2 known issues (default db name and extension replication)

---

product_docs/docs/biganimal/release/known_issues/known_issues_dha.mdx
product_docs/docs/biganimal/release/known_issues/known_issues_pgd.mdx

Added a replication role name as requested

Added  replication role name, single-lined some entries for easier management

---

product_docs/docs/pgd/5/reference/functions.mdx

Added option, tidied up some other SQL functions in the process, pre-wrapped the SQL function, added a description.

DOCS-233: Complete options for bdr.raft_leadership_transfer

---

product_docs/docs/pgd/5/admin-manual/installing/01-provisioning-hosts.mdx
product_docs/docs/pgd/5/admin-manual/installing/02-install-postgres.mdx
product_docs/docs/pgd/5/admin-manual/installing/03-configuring-repositories.mdx
product_docs/docs/pgd/5/admin-manual/installing/04-installing-software.mdx
product_docs/docs/pgd/5/admin-manual/installing/05-creating-cluster.mdx
product_docs/docs/pgd/5/admin-manual/installing/06-check-cluster.mdx
product_docs/docs/pgd/5/admin-manual/installing/07-configure-proxies.mdx
product_docs/docs/pgd/5/admin-manual/installing/08-using-pgd-cli.mdx
product_docs/docs/pgd/5/admin-manual/installing/index.mdx

Combines edits of 5104 with changes from 5377 to proxy and resolves all the conflicts the Github generated.
@ebgitelman , can you check I've preserved all your edits.
@smaher-edb , can you confirm that the pgd proxy section has all your changes.

Edits to PGD PR5104 - with 5377 changes

---

product_docs/docs/biganimal/release/administering_cluster/notifications.mdx

Added Notifications topic as per [UPM-31169](https://enterprisedb.atlassian.net/browse/UPM-31169)/ [DOCS-210](https://enterprisedb.atlassian.net/browse/DOCS-210)
[UPM-31169]: https://enterprisedb.atlassian.net/browse/UPM-31169?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DOCS-210]: https://enterprisedb.atlassian.net/browse/DOCS-210?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

BigAnimal - in-app notifications

---

product_docs/docs/postgis/3.2/01_release_notes/index.mdx
product_docs/docs/postgis/3.2/01_release_notes/rel_notes342.mdx

Added release notes as per [RL-51](https://enterprisedb.atlassian.net/browse/RL-51)
[RL-51]: https://enterprisedb.atlassian.net/browse/RL-51?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

PostGIS - 3.4.2 release branch

---

product_docs/docs/biganimal/release/release_notes/index.mdx
product_docs/docs/biganimal/release/release_notes/mar_2024_rel_notes.mdx

Updated BA release notes for March 2024

---

product_docs/docs/biganimal/release/known_issues/known_issues_pgd.mdx

Reworked leadership KI to be straight on reconnection needs
Removed the requested issue

DOCS-278 and DOCS-262 

---

product_docs/docs/biganimal/release/known_issues/index.mdx
product_docs/docs/biganimal/release/known_issues/known_issues_pgd.mdx

Fix mistimed merge 
Add PGD known issues link to BA known issues
Fix index redirect

Fix mistimed merge and add PGD known issues link to BA known issues

---

product_docs/docs/biganimal/release/administering_cluster/notifications.mdx

Edits to BigAnimal PR5411

---

product_docs/docs/biganimal/release/administering_cluster/projects.mdx
product_docs/docs/biganimal/release/getting_started/creating_a_cluster/index.mdx
product_docs/docs/biganimal/release/using_cluster/tagging/create_and_manage_tags.mdx
product_docs/docs/biganimal/release/using_cluster/tagging/index.mdx

Added basic structure and introduction to tags as per UPM-31277 and DOCS-188

BigAnimal - Tags documentation

---

product_docs/docs/migration_portal/4/01_mp_release_notes/index.mdx
product_docs/docs/migration_portal/4/01_mp_release_notes/mp_4.8.0_rel_notes.mdx

https://enterprisedb.atlassian.net/browse/MIG-5029
(https://enterprisedb.atlassian.net/browse/DOCS-236)

Migration Portal 4.8 release notes

---

product_docs/docs/pgbouncer/1/pgbouncer_rel_notes/02_12210_rel_notes.mdx
product_docs/docs/pgbouncer/1/pgbouncer_rel_notes/index.mdx

Added pgbouncer 1.22.1.0 release notes as per [RL-138](https://enterprisedb.atlassian.net/browse/RL-138)
[RL-138]: https://enterprisedb.atlassian.net/browse/RL-138?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

PgBouncer 1.22.1.0 Release branch

---

product_docs/docs/biganimal/release/getting_started/managing_cluster.mdx
product_docs/docs/biganimal/release/reference/cli/managing_clusters.mdx

Addresses [UPM-31839](https://enterprisedb.atlassian.net/browse/UPM-31839)/[DOCS-298](https://enterprisedb.atlassian.net/browse/DOCS-298).
[UPM-31839]: https://enterprisedb.atlassian.net/browse/UPM-31839?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DOCS-298]: https://enterprisedb.atlassian.net/browse/DOCS-298?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

BigAnimal - Add CLI 3.7.0

---

product_docs/docs/biganimal/release/administering_cluster/projects.mdx
product_docs/docs/biganimal/release/using_cluster/tagging/create_and_manage_tags.mdx
product_docs/docs/pgd/5/admin-manual/installing/03-configuring-repositories.mdx
product_docs/docs/pgd/5/admin-manual/installing/04-installing-software.mdx
product_docs/docs/pgd/5/admin-manual/installing/index.mdx
product_docs/docs/pgd/5/admin-tpa/upgrading_major_rolling.mdx
product_docs/docs/pgd/5/reference/functions.mdx
product_docs/docs/pgd/5/upgrades/manual_overview.mdx
product_docs/docs/postgres_for_kubernetes/1/kubectl-plugin.mdx

Various link fixes (identified via PDF builder logs).

Link fixes: 2024-04-16

---

product_docs/docs/biganimal/release/overview/05_database_version_policy.mdx

Edits to BigAnimal PR5473

---

product_docs/docs/eprs/7/06_mmr_operation/03_creating_primary_nodes.mdx

Changed start of sentence in 2nd paragraph from "You co this" to "You do this"

Corrected spelling

---

product_docs/docs/postgres_distributed_for_kubernetes/1/rel_notes/1_0_rel_notes.mdx
product_docs/docs/postgres_distributed_for_kubernetes/1/rel_notes/index.mdx

Adapting dev's release notes to our public-facing release notes template.
https://enterprisedb.atlassian.net/browse/DOCS-432

initial draft of PG4K-PGD release notes with doc team's style guide

---

product_docs/docs/postgres_distributed_for_kubernetes/1/architecture.mdx
product_docs/docs/postgres_distributed_for_kubernetes/1/connectivity.mdx
product_docs/docs/postgres_distributed_for_kubernetes/1/quickstart.mdx

https://enterprisedb.atlassian.net/browse/DOCS-186

Submariner for environments with multiple AZ

---

product_docs/docs/pgd/5/cli/installing_cli.mdx

More extensive bulletproofed installation process

DOCS-350 - Improving PGD CLI install instructions

---

CODEOWNERS
product_docs/docs/biganimal/release/overview/05_database_version_policy.mdx
product_docs/docs/biganimal/release/using_cluster/05_monitoring_and_logging/third_party_integrations/index.mdx
product_docs/docs/eprs/7/06_mmr_operation/03_creating_primary_nodes.mdx
product_docs/docs/livecompare/2/supported_technologies.mdx
product_docs/docs/pgd/5/cli/installing_cli.mdx

- Codeowners based on content team allocation
- Big Animal: Third-party integration metrics, edits for style guide compliance
- PGD: Improvement to PGD CLI instructions
- LiveCompare: Updates to supported Postgres table

Release: 2024-04-23a

---

product_docs/docs/pgd/5/cli/installing_cli.mdx

Edits to PGD PR5495

---

product_docs/docs/biganimal/release/using_cluster/pgd_defaults_ba.mdx

Adding default PGD commit_scopes for BigAnimal 

---

product_docs/docs/lasso/4/describe.mdx
product_docs/docs/lasso/4/release-notes.mdx

Lasso release 4.15.0

---

src/pages/index.js

New featured topics: PG4K-PGD, EPAS AMI instructions

---

product_docs/docs/postgres_distributed_for_kubernetes/1/rel_notes/1_0_rel_notes.mdx

Edits to pgd4k PR5524

---

product_docs/docs/biganimal/release/using_cluster/pgd_cli_ba.mdx

Added a page in BA docs showing how to use the PGD CLI to connect to your BA DHA cluster.

PGD CLI in BA docs

---

product_docs/docs/pgd/5/admin-tpa/installing.mdx
product_docs/docs/pgd/5/quickstart/connecting_applications.mdx
product_docs/docs/pgd/5/quickstart/further_explore_failover.mdx
product_docs/docs/pgd/5/quickstart/quick_start_aws.mdx
product_docs/docs/pgd/5/quickstart/quick_start_docker.mdx
product_docs/docs/pgd/5/quickstart/quick_start_linux.mdx
product_docs/docs/pgd/5/rel_notes/pgd_5.0.0_rel_notes.mdx
product_docs/docs/pgd/5/routing/raft/01_raft_subgroups_and_tpa.mdx

https://enterprisedb.atlassian.net/browse/DOCS-154
https://enterprisedb.atlassian.net/browse/DOCS-331

PGD docs: Replacing epas 15 mentions with epas 16

---

product_docs/docs/biganimal/release/using_cluster/05_monitoring_and_logging/third_party_integrations/index.mdx

Edits to BigAnimal PR5510

---

product_docs/docs/pgd/5/deployments.mdx

PGD deployments table normalized

DOCS-461 Synchronise table styles

---

product_docs/docs/postgres_distributed_for_kubernetes/1/identify_images/assemble_command.mdx
product_docs/docs/postgres_distributed_for_kubernetes/1/identify_images/identify_image_name.mdx
product_docs/docs/postgres_distributed_for_kubernetes/1/identify_images/index.mdx
product_docs/docs/postgres_distributed_for_kubernetes/1/index.mdx
product_docs/docs/postgres_distributed_for_kubernetes/1/installation_upgrade.mdx
product_docs/docs/postgres_distributed_for_kubernetes/1/private_registries.mdx

https://enterprisedb.atlassian.net/browse/DOCS-198 
- How to select specific operand and proxy images for deployment.
- Reorganized installation topic to add more visual cues for steps.
- Cross-linked for more visibility among topics.

More information around operand and proxy images

---

product_docs/docs/biganimal/release/using_cluster/01_postgres_access/index.mdx

Edits to BigAnimal PR5395

---

product_docs/docs/biganimal/release/using_cluster/pgd_cli_ba.mdx

Edits to BigAnimal PR5620

---

product_docs/docs/biganimal/release/getting_started/preparing_cloud_account/01_preparing_azure/01_understanding_qotas_in_azure.mdx

Added activation resource and access requirements as per [DOC-437](https://enterprisedb.atlassian.net/browse/DOCS-437)

BigAnimal - Azure policies

---

product_docs/docs/lasso/4/release-notes.mdx

Edits to Lasso PR5633

---

product_docs/docs/pgd/5/index.mdx

Fix compat matrix link

---

product_docs/docs/pgd/4/rel_notes/pgd_4.3.5_rel_notes.mdx
product_docs/docs/pgd/5/rel_notes/pgd_5.5.0_rel_notes.mdx

BDR4.3.5 relnotes + some on 5.5.0

---

install_template/templates/products/replication-server/index.njk
product_docs/docs/eprs/7/installing/index.mdx
product_docs/docs/eprs/7/installing/upgrading_replication_server/index.mdx

Added a global warning for install and another for upgrade.
Addresses https://enterprisedb.atlassian.net/browse/DOCS-630.

Add warning recommending strict adherence to EPRS install steps

---

product_docs/docs/pgd/5/index.mdx

Edit to pgd pr5585

---

product_docs/docs/pwr/1/configuring.mdx
product_docs/docs/pwr/1/rel_notes/110_rel_notes.mdx
product_docs/docs/pwr/1/rel_notes/index.mdx
product_docs/docs/pwr/1/using.mdx

Add documentation changes for the release of PWR 1.1.0

PWR release 1.1.0

---

product_docs/docs/efm/4/installing/linux_ppc64le/efm_rhel_8.mdx
product_docs/docs/efm/4/installing/linux_ppc64le/efm_rhel_9.mdx
product_docs/docs/efm/4/installing/linux_ppc64le/efm_sles_12.mdx
product_docs/docs/efm/4/installing/linux_ppc64le/efm_sles_15.mdx
product_docs/docs/efm/4/installing/linux_x86_64/efm_centos_7.mdx
product_docs/docs/efm/4/installing/linux_x86_64/efm_debian_10.mdx
product_docs/docs/efm/4/installing/linux_x86_64/efm_debian_11.mdx
product_docs/docs/efm/4/installing/linux_x86_64/efm_other_linux_8.mdx
product_docs/docs/efm/4/installing/linux_x86_64/efm_other_linux_9.mdx
product_docs/docs/efm/4/installing/linux_x86_64/efm_rhel_7.mdx
product_docs/docs/efm/4/installing/linux_x86_64/efm_rhel_8.mdx
product_docs/docs/efm/4/installing/linux_x86_64/efm_rhel_9.mdx
product_docs/docs/efm/4/installing/linux_x86_64/efm_sles_12.mdx
product_docs/docs/efm/4/installing/linux_x86_64/efm_sles_15.mdx
product_docs/docs/efm/4/installing/linux_x86_64/efm_ubuntu_20.mdx
product_docs/docs/efm/4/installing/linux_x86_64/efm_ubuntu_22.mdx

New template generated files for EFM 4.9

New install files for EFM 4.9

---

advocacy_docs/pg_extensions/wait_states/rel_notes/index.mdx
advocacy_docs/pg_extensions/wait_states/rel_notes/wait_states_1.3_rel_notes.mdx
product_docs/docs/pem/9/pem_rel_notes/index.mdx

Updated the release date in edb_wait_states docs
Added PEM 9.6 to the index page

Quick fixes

---

product_docs/docs/biganimal/release/getting_started/creating_a_cluster/creating_a_dha_cluster.mdx

Removed a link which looped back around to the page as was.

Update creating_a_dha_cluster.mdx corrected old link

---

product_docs/docs/epas/17/reference/oracle_compatibility_reference/epas_compat_bip_guide/03_built-in_packages/20_utl_file.mdx
product_docs/docs/epas/17/reference/oracle_compatibility_reference/epas_compat_sql/22_create_directory.mdx
product_docs/docs/epas/17/reference/oracle_compatibility_reference/epas_compat_sql/46_drop_directory.mdx

Wording for CREATE DIRECTORY and MERGE DIRECTORY

---

product_docs/docs/livecompare/2/oracle_support.mdx
product_docs/docs/livecompare/2/rel_notes/2.5.1_rel_notes.mdx
product_docs/docs/livecompare/2/rel_notes/index.mdx
product_docs/docs/livecompare/2/settings.mdx
product_docs/docs/livecompare/2/supported_technologies.mdx
product_docs/docs/migration_toolkit/55/04_functionality_overview.mdx
product_docs/docs/migration_toolkit/55/07_invoking_mtk/08_mtk_command_options.mdx
product_docs/docs/migration_toolkit/55/10_error_codes.mdx
product_docs/docs/migration_toolkit/55/11_questions.mdx
product_docs/docs/migration_toolkit/55/mtk_rel_notes/index.mdx
product_docs/docs/migration_toolkit/55/mtk_rel_notes/mtk_5580_rel_notes.mdx

- Migration toolkit 5.5.8.0
- LiveCompare 2.5.1

Release: 2024-05-16b

---

product_docs/docs/pgd/5/cli/installing/linux.mdx
product_docs/docs/pgd/5/deploy-config/deploy-biganimal/index.mdx
product_docs/docs/pgd/5/deploy-config/deploy-kubernetes/index.mdx
product_docs/docs/pgd/5/deploy-config/deploy-manual/deploying/01-provisioning-hosts.mdx
product_docs/docs/pgd/5/deploy-config/deploy-manual/deploying/02-install-postgres.mdx
product_docs/docs/pgd/5/deploy-config/deploy-manual/deploying/03-configuring-repositories.mdx
product_docs/docs/pgd/5/deploy-config/deploy-manual/deploying/04-installing-software.mdx
product_docs/docs/pgd/5/deploy-config/deploy-manual/deploying/05-creating-cluster.mdx
product_docs/docs/pgd/5/deploy-config/deploy-manual/deploying/06-check-cluster.mdx
product_docs/docs/pgd/5/deploy-config/deploy-manual/deploying/07-configure-proxies.mdx
product_docs/docs/pgd/5/deploy-config/deploy-manual/deploying/08-using-pgd-cli.mdx
product_docs/docs/pgd/5/deploy-config/deploy-manual/deploying/index.mdx
product_docs/docs/pgd/5/deploy-config/deploy-tpa/deploying/01-configuring.mdx
product_docs/docs/pgd/5/deploy-config/deploy-tpa/deploying/02-deploying.mdx
product_docs/docs/pgd/5/deploy-config/deploy-tpa/deploying/index.mdx
product_docs/docs/pgd/5/deploy-config/deploy-tpa/index.mdx
product_docs/docs/pgd/5/upgrades/upgrading_major_rolling.mdx
tools/user/reorg/redirects/renames-to-redirects.js

Add a few missing redirects to support the PGD 5 reorg

---

src/constants/updates.js
src/pages/index.js

Also moved the content for these to a datafile for ease of updating

Update "what's new" topics

---

product_docs/docs/pgd/5/deploy-config/deploy-tpa/deploying/01-configuring.mdx

Invisible anchor added to tpa configure page

Fix link in tpa page

---

product_docs/docs/pge/15/release_notes/rel_notes15.7.mdx
product_docs/docs/pge/16/release_notes/rel_notes16.3.mdx

Added missing release note to PGE releases

Added missing release note to PGE releases

---

src/constants/updates.js

URLs in the new shiny constants/updates.js

Fix front page URLs

---

product_docs/docs/pgd/5/cli/installing/linux.mdx

Removed dupe redirect from linux.mdx

---

product_docs/docs/postgres_distributed_for_kubernetes/1/index.mdx

Files had moved into the planning directory on the reorg.

Fix bad links into PGD

---

product_docs/docs/pgd/4/deployments/manually/07-using-pgd-cli.mdx

Fix inpage numbering on 07-using-pgd-cli.mdx

---

product_docs/docs/pwr/1/configuring.mdx
product_docs/docs/pwr/1/rel_notes/110_rel_notes.mdx
product_docs/docs/pwr/1/using.mdx

Edits to PWR PR5609

---

product_docs/docs/biganimal/release/administering_cluster/aws_secrets_manager_integration.mdx

Addresses [DOC-196](https://enterprisedb.atlassian.net/browse/DOCS-196)

BigAnimal - AWS Secrets Manager Integration

---

product_docs/docs/eprs/7/02_overview/04_design_replication_system/03_restrictions_on_replicated_database_objects.mdx
product_docs/docs/eprs/7/10_appendix/03_miscellaneous_xdb_processing_topics/01_publications_and_subscriptions_server_conf_options/single_quote_unescape.mdx
product_docs/docs/eprs/7/10_appendix/03_miscellaneous_xdb_processing_topics/01_publications_and_subscriptions_server_conf_options/skip_default_column.mdx
product_docs/docs/eprs/7/10_appendix/03_miscellaneous_xdb_processing_topics/01_publications_and_subscriptions_server_conf_options/snapshot_connection_retry.mdx
product_docs/docs/eprs/7/eprs_rel_notes/eprs_rel_notes_7.8.0.mdx

Edits to EPRS PR5607

---

product_docs/docs/biganimal/release/using_cluster/05_monitoring_and_logging/health_status.mdx

Added first draft of Health Status doc as per [DOCS-469](https://enterprisedb.atlassian.net/browse/DOCS-469) & [DOCS-470](https://enterprisedb.atlassian.net/browse/DOCS-470)
[DOCS-469]: https://enterprisedb.atlassian.net/browse/DOCS-469?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DOCS-470]: https://enterprisedb.atlassian.net/browse/DOCS-470?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

BigAnimal - Health Status doc

---

static/images/favicon.png
static/images/social.jpg

Temporary Replacement Graphics

---

advocacy_docs/edb-postgres-ai/console/agent/agent-as-a-service.mdx
advocacy_docs/edb-postgres-ai/console/agent/beacon-agent-ref.mdx
advocacy_docs/edb-postgres-ai/console/agent/index.mdx
advocacy_docs/edb-postgres-ai/console/reference/index.mdx
advocacy_docs/edb-postgres-ai/overview/concepts.mdx
advocacy_docs/edb-postgres-ai/overview/releasenotes.mdx

- Moved beacon-agent reference into the agent content.
- Removed unnecessary colons from headings in overview/concepts.mdx 
- Fixed indentation and numbering of steps in /docs/edb-postgres-ai/console/agent/agent-as-a-service/

Minor post-release fixes for EDB Postgres AI

---

advocacy_docs/edb-postgres-ai/console/agent/agent-as-a-service.mdx
advocacy_docs/edb-postgres-ai/console/agent/beacon-agent-ref.mdx
advocacy_docs/edb-postgres-ai/console/agent/index.mdx
advocacy_docs/edb-postgres-ai/console/reference/index.mdx
advocacy_docs/edb-postgres-ai/overview/concepts.mdx
advocacy_docs/edb-postgres-ai/overview/releasenotes.mdx
static/images/favicon.png
static/images/social.jpg

- New branding for favicon / social images
- Link, styling and trademark cleanup

Release: 2024-05-23b

---

product_docs/docs/jdbc_connector/42.5.4.2/02_requirements_overview.mdx

Supported Platforms fix as per [EC-3097](https://enterprisedb.atlassian.net/browse/EC-3097)
[EC-3097]: https://enterprisedb.atlassian.net/browse/EC-3097?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

JDBC Connector - Supported platforms fix

---

product_docs/docs/pgd/5/rel_notes/pgd_5.5.0_rel_notes.mdx

Fix word trash in notes

---

tools/user/import/bareleasenotes/barelease.js

Fixes output text (embedded in code as so little text, a template seemed overkill)

Fix text to match recent edits

---

advocacy_docs/edb-postgres-ai/console/getstarted.mdx

Link in Console - Getting Started

Fix link for console (to one that works)

---

product_docs/docs/postgres_distributed_for_kubernetes/1/security.mdx

DOCS-688 - Fix link in security.mdx

---

advocacy_docs/edb-postgres-ai/console/agent/install-agent.mdx

1. Some typos.
2. Broke up a command.
3. Added some commands to set up env variables for subscription token and subscription type.

Some improvements to install-agent.mdx

---

advocacy_docs/community/contributing/styleguide.mdx

Added recommendations for the usage of the term "cluster". 
Added recommendations for usage of "Postgres flavour/distribution". 
Added section on trademark symbol recommendation.
https://enterprisedb.atlassian.net/browse/DOCS-167

Added style guide information for three new topics

---

advocacy_docs/community/contributing/styleguide.mdx
advocacy_docs/edb-postgres-ai/console/agent/install-agent.mdx
advocacy_docs/supported-open-source/patroni/index.mdx
advocacy_docs/supported-open-source/patroni/installing_patroni.mdx
advocacy_docs/supported-open-source/patroni/installing_with_TPA.mdx
product_docs/docs/eprs/7/installing/uninstalling.mdx
product_docs/docs/eprs/7/installing/upgrading_replication_server/upgrading_with_gui_installer.mdx
product_docs/docs/eprs/7/installing/windows.mdx
product_docs/docs/pgd/4/bdr/scaling.mdx
product_docs/docs/pgd/5/reference/index.json
product_docs/docs/pgd/5/reference/index.mdx
product_docs/docs/pgd/5/reference/pgd-settings.mdx
product_docs/docs/pgd/5/rel_notes/index.mdx
product_docs/docs/pgd/5/rel_notes/pgd_5.4.1_rel_notes.mdx
product_docs/docs/pgd/5/rel_notes/pgd_5.5.1_rel_notes.mdx
product_docs/docs/pgd/5/scaling.mdx
product_docs/docs/postgres_distributed_for_kubernetes/1/identify_images/assemble_command.mdx
product_docs/docs/postgres_distributed_for_kubernetes/1/identify_images/identify_image_name.mdx
product_docs/docs/postgres_distributed_for_kubernetes/1/identify_images/index.mdx
product_docs/docs/postgres_distributed_for_kubernetes/1/identify_images/private_registries.mdx
product_docs/docs/postgres_distributed_for_kubernetes/1/installation_upgrade.mdx

#5715 PGD 5.5.1 release
#5714 Docs changes for PGD Autopartition
#5686 Removed Stackbuilder references from EPRS docs
#5702 Improvements to install agent docs
#5656 Updated installation instructions for Patroni to use edb-patroni
#5697 Improvements of pgd4k documentation
#5690 Updates to style guide

Release 23-05-31(a)

---

advocacy_docs/supported-open-source/patroni/installing_patroni.mdx
advocacy_docs/supported-open-source/patroni/installing_with_TPA.mdx

Edits to Patroni PR5656

---

product_docs/docs/postgres_distributed_for_kubernetes/1/identify_images/assemble_command.mdx
product_docs/docs/postgres_distributed_for_kubernetes/1/identify_images/identify_image_name.mdx
product_docs/docs/postgres_distributed_for_kubernetes/1/identify_images/index.mdx

Edits to PGD4K PR5697

---

product_docs/docs/migration_toolkit/55/09_mtk_errors.mdx

Edits to Migration Toolkit PR5658

---

product_docs/docs/pgd/5/rel_notes/index.mdx

Tiny date fix

---

product_docs/docs/pgd/5/reference/functions.mdx

Edits to PGD PR5436

---

product_docs/docs/biganimal/release/using_cluster/05_monitoring_and_logging/third_party_integrations/datadog.mdx

Edits to datadog PR5238

---

product_docs/docs/biganimal/release/using_cluster/fault_injection_testing/index.mdx

Edits to BigAnimal PR5422

---

product_docs/docs/biganimal/release/getting_started/managing_cluster.mdx
product_docs/docs/biganimal/release/reference/cli/managing_clusters.mdx

Edits to BigAnimal PR5479

---

product_docs/docs/biganimal/release/using_cluster/05_monitoring_and_logging/health_status.mdx

Edits to BigAnimal PR5660 (health status

---

product_docs/docs/epas/15/planning/deployment_options/aws_epas.mdx

Edits to epas15 pr3884

---

product_docs/docs/biganimal/release/migration/dha_bulk_migration.mdx

Edits to BigAnimal PR5462

---

product_docs/docs/biganimal/release/using_cluster/05c_upgrading_log_rep.mdx

Edits to BigAnimal PR5372

---

product_docs/docs/biganimal/release/administering_cluster/notifications.mdx
product_docs/docs/biganimal/release/overview/updates.mdx
product_docs/docs/biganimal/release/reference/access_key/index.mdx
product_docs/docs/biganimal/release/using_cluster/05_monitoring_and_logging/third_party_integrations/index.mdx

Edits to BigAnimal PR5621

---

product_docs/docs/biganimal/release/getting_started/identity_provider/index.mdx

Edits to BigAnimal PR5376

---

advocacy_docs/pg_extensions/edb_job_scheduler/index.mdx

Removed a wrong statement and fixed the catalog name

EDB_JOB_SCHEDULER - minor fixes

---

product_docs/docs/pgd/4/bdr/catalogs.mdx
product_docs/docs/pgd/4/bdr/configuration.mdx
product_docs/docs/pgd/5/reference/catalogs-visible.mdx
product_docs/docs/pgd/5/reference/functions.mdx
product_docs/docs/pgd/5/reference/nodes-management-interfaces.mdx
product_docs/docs/pgd/5/reference/pgd-settings.mdx

Edits to PGD PR5651

---

product_docs/docs/pgd/5/security/pgd-predefined-roles.mdx
product_docs/docs/pgd/5/security/roles.mdx

Descriptions on the predefined roles page
Links to the predefined roles from the general Roles page

Tidy up roles pages

---

product_docs/docs/biganimal/release/reference/cli/managing_clusters.mdx

Two new examples
Addresses https://enterprisedb.atlassian.net/browse/DOCS-165

Added examples for creating distributed clusters in BigAnimal for AWS and GCP

---

src/templates/learn-doc.js

Adds deepToC support to advocacy docs via the learn-doc.

Adds deepToC support to the learn-doc templates and advocacy docs

---

.github/workflows/deploy-develop.yml
.github/workflows/deploy-draft.yml
.github/workflows/deploy-main.yml
gatsby-node.js
product_docs/docs/biganimal/release/reference/cli/managing_clusters.mdx
product_docs/docs/pgd/5/security/pgd-predefined-roles.mdx
product_docs/docs/pgd/5/security/roles.mdx
src/components/card-decks.js
src/components/index.js
src/components/prev-next.js
src/components/tiles.js
src/constants/gatsby-utils.js
src/templates/doc.js
src/templates/learn-doc.js

- Maintenance: deepToC support in unversioned docs, full nav cards in versioned docs, nav bugfixes
- BigAnimal: examples for creating distributed clusters in BigAnimal for AWS and GCP
- PGD: Tidy up roles pages

Release: 2024-06-05b

---

product_docs/docs/lasso/4/describe.mdx

Edits to Lasso release 4.16.0 #5733

---

product_docs/docs/pgd/5/quickstart/further_explore_replication.mdx
product_docs/docs/pgd/5/quickstart/index.mdx
product_docs/docs/pgd/5/quickstart/quick_start_aws.mdx
product_docs/docs/pgd/5/quickstart/quick_start_docker.mdx
product_docs/docs/pgd/5/quickstart/quick_start_linux.mdx

Added and linked a new explore replication section based on the manual install test replication guide.
To-do: port changes in the guide back to manual installation.

Docs-627 - New explore replication section

---

product_docs/docs/pgd/5/security/pgd-predefined-roles.mdx
product_docs/docs/pgd/5/security/roles.mdx

Edits to Tidy up roles pages #5657

---

advocacy_docs/supported-open-source/pgbackrest/04-recommended_settings.mdx
advocacy_docs/supported-open-source/pgbackrest/10-non-superuser.mdx

Created non-superuser section for tech review
Fixed links and glossary in settings as two were not resolving

DOCS-668-the-customer-wants-the-documentation-enhancement-f

---

product_docs/docs/pem/9/monitoring_performance/notifications.mdx

Added a section about Using webhooks to the Notifications topic in PEM.
Addresses https://enterprisedb.atlassian.net/browse/PEM-4330.

Add Using Webhooks to PEM documentation

---

advocacy_docs/edb-postgres-ai/analytics/how_to_lakehouse_sync.mdx
advocacy_docs/edb-postgres-ai/analytics/images/msl_list.png

This adds a how-to guide for the happy path of Lakehouse sync.

Add how-to of happy path for Lakehouse sync DOCS-604

---

product_docs/docs/pgd/5/overview/index.mdx

Small fixes to PGD overview page.

---

product_docs/docs/efm/4/efm_rel_notes/index.mdx

EFM doesn't have "minor" releases or patches. Every release is separate from the others, even if it's just the "minor" number that changed in the version.

Remove confusing text about minor releases and patches

---

product_docs/docs/pem/9/monitoring_performance/notifications.mdx

Edits to PEM Add Using Webhooks to PEM documentation #5258

---

product_docs/docs/pgd/5/routing/readonly.mdx

Typos in PGD read-only proxy topic.mdx

---

product_docs/docs/pgd/5/appusage/behavior.mdx
product_docs/docs/pgd/5/appusage/index.mdx
product_docs/docs/pgd/5/cli/discover_connections.mdx
product_docs/docs/pgd/5/ddl/ddl-locking.mdx
product_docs/docs/pgd/5/ddl/ddl-managing-with-pgd-replication.mdx
product_docs/docs/pgd/5/ddl/ddl-overview.mdx

Re-edit of PGD content per request

Re-edit of PGD - part 1

---

advocacy_docs/edb-postgres-ai/analytics/how_to_lakehouse_sync.mdx

Fix a couple typos in Lakehouse sync.

---

product_docs/docs/pgd/5/compatibility.mdx
product_docs/docs/pgd/5/index.mdx

DOCS-762 - Compatibility page and link

---

gatsby-config.js
install_template/templates/products/postgis/arm64_index.njk
install_template/templates/products/replication-server/index.njk
product_docs/docs/postgis/3/installing/linux_arm64/index.mdx
src/components/left-nav.js
src/pages/index.js
src/plugins/preserve-image-style/index.js
src/plugins/preserve-image-style/package.json
src/styles/_helpers.scss
src/templates/learn-doc.js

- Fixes: clicking too fast crashes local nav (white screen), console filled with log messages while navigating, unintended fill for icons
- Enhancement: style attribute preserved for HTML images

Release: 2024-06-25b

---

product_docs/docs/biganimal/release/getting_started/02_connecting_to_your_cloud/connecting_aws.mdx
product_docs/docs/biganimal/release/getting_started/02_connecting_to_your_cloud/connecting_azure.mdx
product_docs/docs/biganimal/release/getting_started/02_connecting_to_your_cloud/connecting_gcp.mdx
product_docs/docs/biganimal/release/getting_started/creating_a_cluster/index.mdx
product_docs/docs/biganimal/release/getting_started/overview.mdx
product_docs/docs/biganimal/release/overview/support/index.mdx

Edits to Integrate CS and Sales articles into technical documentation PR5350

---

product_docs/docs/pgd/5/ddl/ddl-pgd-functions-like-ddl.mdx
product_docs/docs/pgd/5/ddl/ddl-replication-options.mdx
product_docs/docs/pgd/5/ddl/ddl-role-manipulation.mdx
product_docs/docs/pgd/5/ddl/ddl-workarounds.mdx
product_docs/docs/pgd/5/ddl/index.mdx

Second set of edits to PGD doc

---

product_docs/docs/biganimal/release/administering_cluster/projects.mdx
product_docs/docs/biganimal/release/getting_started/creating_a_cluster/index.mdx
product_docs/docs/biganimal/release/overview/03_security/index.mdx
product_docs/docs/biganimal/release/using_cluster/05a_deleting_your_cluster.mdx
product_docs/docs/biganimal/release/using_cluster/managing_replicas.mdx

https://enterprisedb.atlassian.net/browse/DOCS-724 
Final UI changes are being made as we speak.

TDE on BigAnimal with Customer Managed Keys

---

product_docs/docs/biganimal/release/using_cluster/05_monitoring_and_logging/monitoring_using_biganimal_observability/index.mdx

Added Session wait states as per [UPM-35116](https://enterprisedb.atlassian.net/browse/UPM-35116)
[UPM-35116]: https://enterprisedb.atlassian.net/browse/UPM-35116?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

BigAnimal's Observability feature update

---

product_docs/docs/biganimal/release/getting_started/creating_a_cluster/creating_a_dha_cluster.mdx
product_docs/docs/biganimal/release/getting_started/creating_a_cluster/index.mdx
product_docs/docs/biganimal/release/overview/04_responsibility_model.mdx
product_docs/docs/biganimal/release/planning/choosing_postgres_distro.mdx
product_docs/docs/biganimal/release/using_cluster/04_backup_and_restore.mdx

Added initial draft of snapshot backups as per [DOCS-413](https://enterprisedb.atlassian.net/browse/DOCS-413)
[DOCS-413]: https://enterprisedb.atlassian.net/browse/DOCS-413?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

BigAnimal - Snapshot backups

---

product_docs/docs/migration_portal/4/01_mp_release_notes/index.mdx
product_docs/docs/migration_portal/4/01_mp_release_notes/mp_4.10.0_rel_notes.mdx
product_docs/docs/migration_portal/4/03_mp_using_portal/01_mp_overview_home.mdx
product_docs/docs/migration_portal/4/03_mp_using_portal/02_mp_overview_project.mdx
product_docs/docs/migration_portal/4/04_mp_migrating_database/02_mp_schema_assessment.mdx
product_docs/docs/migration_portal/4/images/mp_overview_home_1.png
product_docs/docs/migration_portal/4/images/mp_overview_home_1_edbai.png
product_docs/docs/migration_portal/4/images/mp_overview_home_2.png
product_docs/docs/migration_portal/4/images/mp_overview_home_2_edbai.png
product_docs/docs/migration_portal/4/images/mp_schema_assessment_copilot.png
product_docs/docs/migration_portal/4/images/mp_schema_assessment_copilot_edbai.png
product_docs/docs/migration_portal/4/images/mp_schema_assessment_errors.png
product_docs/docs/migration_portal/4/images/mp_schema_assessment_errors_edbai.png
product_docs/docs/migration_portal/4/images/mp_schema_assessment_incompatible.png
product_docs/docs/migration_portal/4/images/mp_schema_assessment_incompatible_edbai.png
product_docs/docs/migration_portal/4/images/mp_schema_assessment_workaround.png
product_docs/docs/migration_portal/4/images/mp_schema_assessment_workaround_edbai.png

Migration Portal: 4.10 release and screenshot updates post re-branding.

Release: 2024-06-27a

---

product_docs/docs/postgres_for_kubernetes/1/security.mdx

Early cherry-pick of https://github.com/cloudnative-pg/cloudnative-pg/pull/4834

Bring in upstream docs changes for Cluster-Wide Permissions and Operator Deployment

---

package-lock.json
src/components/advanced-search/filtering.js
src/components/advanced-search/form.js
src/components/search/index.js
src/pages/404.js
src/pages/search.js

Root cause of this was passing a string to `<Configure>` where it expected a number. The irritating bit about that was that it *worked*, it just kept re-rendering as the internal state was never an exact match with what was passed. 
Took this opportunity to clean up a few other places that were triggering unnecessary re-rendering; page should be noticeably faster now.
Finally, re-enable analytics (which I'd disabled the other dayas a temporary mitigation; didn't fix the root issue, but did stop it from quickly crashing a browser by filling logs with errors)

Fix render loop on advanced search

---

product_docs/docs/tde/15/affected_commands.mdx
product_docs/docs/tde/15/pg_upgrade_arguments.mdx
product_docs/docs/tde/15/upgrade_overview.mdx

https://enterprisedb.atlassian.net/browse/DOCS-807
Fixing a few broken links.

TDE: link fixes

---

package-lock.json
product_docs/docs/pgd/5/ddl/ddl-locking.mdx
product_docs/docs/postgres_for_kubernetes/1/security.mdx
product_docs/docs/tde/15/affected_commands.mdx
product_docs/docs/tde/15/pg_upgrade_arguments.mdx
product_docs/docs/tde/15/upgrade_overview.mdx
src/components/advanced-search/filtering.js
src/components/advanced-search/form.js
src/components/search/index.js
src/pages/404.js
src/pages/search.js

[#5830 Fix render loop on advanced search](https://github.com/EnterpriseDB/docs/pull/5830)
[#5831 TDE: link fixes](https://github.com/EnterpriseDB/docs/pull/5831)
[#5829 Notes to nodes...](https://github.com/EnterpriseDB/docs/pull/5829)

Release 2024-07-03a

---

product_docs/docs/pgd/5/durability/durabilityterminology.mdx
product_docs/docs/pgd/5/durability/group-commit.mdx
product_docs/docs/pgd/5/durability/index.mdx
product_docs/docs/pgd/5/durability/lag-control.mdx

PGD reedit -- fourth group of edits

---

src/constants/updates.js

Updated updates

---

product_docs/docs/pgd/5/durability/durabilityterminology.mdx
product_docs/docs/pgd/5/durability/group-commit.mdx
product_docs/docs/pgd/5/durability/index.mdx
product_docs/docs/pgd/5/durability/lag-control.mdx
product_docs/docs/pgd/5/durability/legacy-sync.mdx
product_docs/docs/pgd/5/durability/limitations.mdx
product_docs/docs/pgd/5/durability/overview.mdx
product_docs/docs/pgd/5/monitoring/index.mdx
product_docs/docs/pgd/5/monitoring/otel.mdx
product_docs/docs/pgd/5/node_management/heterogeneous_clusters.mdx
product_docs/docs/pgd/5/node_management/index.mdx
product_docs/docs/pgd/5/node_management/node_recovery.mdx
product_docs/docs/pgd/5/repsets.mdx
src/constants/updates.js

[#5838 Updated updates](https://github.com/EnterpriseDB/docs/pull/5838)
[#5806 PGD re-edit](https://github.com/EnterpriseDB/docs/pull/5806)
[#5835 DOCS-804 Broken architecture image in rep sets docs](https://github.com/EnterpriseDB/docs/pull/5835)
[#5786 PGD reedit](https://github.com/EnterpriseDB/docs/pull/5786)

Release 2024-07-04a

---

install_template/templates/products/edb-jdbc-connector/index.njk
product_docs/docs/jdbc_connector/42.5.4.2/installing/index.mdx
product_docs/docs/jdbc_connector/42.5.4.2/installing/using_maven.mdx

Added instructions on how to install JDBC using Maven. 
https://enterprisedb.atlassian.net/browse/EC-3084

JDBC: Maven installation

---

product_docs/docs/pgd/5/quickstart/connecting_applications.mdx
product_docs/docs/pgd/5/quickstart/further_explore_conflicts.mdx
product_docs/docs/pgd/5/quickstart/further_explore_failover.mdx
product_docs/docs/pgd/5/quickstart/further_explore_replication.mdx
product_docs/docs/pgd/5/quickstart/index.mdx
product_docs/docs/pgd/5/quickstart/next_steps.mdx
product_docs/docs/pgd/5/quickstart/quick_start_aws.mdx
product_docs/docs/pgd/5/quickstart/quick_start_cloud.mdx
product_docs/docs/pgd/5/quickstart/quick_start_docker.mdx
product_docs/docs/pgd/5/quickstart/quick_start_linux.mdx

Edits to quick start - PGD reedit group 7

---

product_docs/docs/migration_toolkit/55/07_invoking_mtk/08_mtk_command_options.mdx

Edits to PR5820: MTK: schema-qualified command-line options

---

product_docs/docs/biganimal/release/release_notes/2024_06_jun_rel_notes.mdx

Edits to BigAnimal PR5842 June release notes

---

product_docs/docs/epas/16/working_with_oracle_data/02_enhanced_compatibility_features.mdx

Added note about DBLink compatibility.
Addresses https://enterprisedb.atlassian.net/browse/DB-2580

Added compatibility note

---

product_docs/docs/pem/9/monitoring_performance/alerts.mdx

Removed SQL code from the statement as it was not supported.

PEM: Update alerts.mdx

---

product_docs/docs/pem/9/monitoring_performance/notifications.mdx

Updated the note that snmp v3 can not work with non root agents.

PEM: Update notifications.mdx

---

product_docs/docs/hadoop_data_adapter/2/10d_example_limit_offset_pushdown.mdx

https://enterprisedb.atlassian.net/browse/FDW-690

Hadoop FDW: per-session GUC was added for enable_limit_pushdown

---

advocacy_docs/repos/getting_started/index.mdx
advocacy_docs/repos/getting_started/troubleshooting.mdx
advocacy_docs/repos/getting_started/with_cli/adding_edb_repositories.mdx
advocacy_docs/repos/getting_started/with_cli/get_your_token.mdx
advocacy_docs/repos/getting_started/with_cli/index.mdx
advocacy_docs/repos/getting_started/with_cli/install_named_package.mdx
advocacy_docs/repos/getting_started/with_web/add_your_repository.mdx
advocacy_docs/repos/getting_started/with_web/get_your_token.mdx
advocacy_docs/repos/getting_started/with_web/index.mdx
advocacy_docs/repos/getting_started/with_web/install_package.mdx
advocacy_docs/repos/index.mdx
advocacy_docs/repos/migration/index.mdx
advocacy_docs/repos/reference/index.mdx
advocacy_docs/repos/reference/package_names.mdx
advocacy_docs/repos/reference/repositories_by_name.mdx
advocacy_docs/repos/working_with_repos/building_local_mirrors.mdx
advocacy_docs/repos/working_with_repos/directly.mdx
advocacy_docs/repos/working_with_repos/index.mdx
advocacy_docs/repos/working_with_repos/installing_airgapped.mdx

Edits to DOCS-726 - Repos section for docs

---

advocacy_docs/edb-postgres-ai/overview/index.mdx

In page links were out of sync with names - now fixed

Fix inpage links

---

product_docs/docs/pgd/5/reference/pgd-settings.mdx

Added warning to reference entry

DOCS-911 - Added warning to reference entry for bdr.default_replica_identity

---

product_docs/docs/pgd/5/terminology.mdx

Modified quorum in terminology to be more general and include reference to locking

Update terminology.mdx quorum

---

product_docs/docs/pge/15/deploy_options.mdx
product_docs/docs/pge/16/deploy_options.mdx

Update deploy_options.mdx fix broken link

---

product_docs/docs/biganimal/release/reference/cli/managing_clusters.mdx

Updated the command for listing all deleted clusters as show --deleted as per [DOCS-913](https://enterprisedb.atlassian.net/browse/DOCS-913)
[DOCS-913]: https://enterprisedb.atlassian.net/browse/DOCS-913?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

BigAnimal - Fixed the CLI command

---

product_docs/docs/hadoop_data_adapter/2/hadoop_rel_notes/hadoop_rel_notes_2.3.2.mdx
product_docs/docs/mysql_data_adapter/2/06_features_of_mysql_fdw.mdx
product_docs/docs/mysql_data_adapter/2/mysql_rel_notes/mysql2.9.2_rel_notes.mdx

Edits to MySQL FDW - read default file for connections #5834

---

src/pages/index.js

Adjusted columns for smoother degradation on width.

Modify resize to handle smaller screens more gradually

---

product_docs/docs/biganimal/release/release_notes/2024_07_jul_rel_notes.mdx
product_docs/docs/biganimal/release/release_notes/index.mdx

No new updates for EDB Cloud Service/BA in July, however, adding release notes page for completeness.

EDB Cloud Service RN for July

---

product_docs/docs/pgd/5/reference/functions-internal.mdx

Added deeptoc to make page browsable.

Activate deeptoc on this page

---

advocacy_docs/security/advisories/cve20244545.mdx
product_docs/docs/epas/16/upgrading/minor_upgrade/index.mdx

Fixup on epas upgrade and security pages to fix earlier merge

---

product_docs/docs/pgd/5/reference/pgd-settings.mdx

Edits to pgd-settings file for re-edit project - group 10

---

product_docs/docs/biganimal/release/using_cluster/index.mdx
product_docs/docs/biganimal/release/using_cluster/managing_cloud_account/csp_tagging.mdx
product_docs/docs/biganimal/release/using_cluster/managing_cloud_account/index.mdx
product_docs/docs/pgd/5/reference/pgd-settings.mdx

Cloud Service (formerly BigAnimal) - _CSP tagging_ feature.
PGD - Editorial review of _PGD settings_ topic.

Release: 2024-08-05a

---

product_docs/docs/pgd/5/reference/catalogs-internal.mdx
product_docs/docs/pgd/5/reference/catalogs-visible.mdx
product_docs/docs/pgd/5/reference/conflict_functions.mdx
product_docs/docs/pgd/5/reference/conflicts.mdx
product_docs/docs/pgd/5/reference/index.json
product_docs/docs/pgd/5/reference/index.mdx
product_docs/docs/pgd/5/reference/index.mdx.src
product_docs/docs/pgd/5/reference/streamtriggers/rowfunctions.mdx
product_docs/docs/pgd/5/reference/streamtriggers/rowvariables.mdx

PGD re-edit batch 8 - reference

---

product_docs/docs/pgd/5/reference/conflicts.mdx
product_docs/docs/pgd/5/reference/functions-internal.mdx
product_docs/docs/pgd/5/reference/functions.mdx
product_docs/docs/pgd/5/reference/index.json
product_docs/docs/pgd/5/reference/index.mdx
product_docs/docs/pgd/5/reference/index.mdx.src
product_docs/docs/pgd/5/reference/nodes-management-interfaces.mdx
product_docs/docs/pgd/5/reference/nodes.mdx

PGD re-edit - group 9

---

tools/automation/actions/link-check/index.js

I'd messed up paths at some point, breaking annotations by including a "content/" prefix. 
At @djw-m's request, also include path context in the logs.

Link checker: fix paths, provide better context for logs

---

product_docs/docs/biganimal/release/using_cluster/fault_injection_testing/index.mdx
product_docs/docs/pgd/5/reference/conflict_functions.mdx

Mostly testing link-checker corrections

Minor link fixes: 2024-08-6

---

product_docs/docs/migration_toolkit/55/installing/macos.mdx
product_docs/docs/migration_toolkit/55/installing/windows.mdx

https://enterprisedb.atlassian.net/browse/DOCS-928

MTK: Removing Adoptium reference + specifying supported JDKs

---

advocacy_docs/tools/alteruser_utility/index.mdx
advocacy_docs/tools/index.mdx
src/constants/products.js
src/pages/index.js

Added initial draft of ALTERUSER utility under tools as per [DOCS-698](https://enterprisedb.atlassian.net/browse/DOCS-698)
[DOCS-698]: https://enterprisedb.atlassian.net/browse/DOCS-698?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ALTERUSER - new utility added under tools

---

product_docs/docs/pgd/5/routing/readonly.mdx

Fix typos in readonly.mdx

---

product_docs/docs/epas/17/reference/oracle_compatibility_reference/epas_compat_bip_guide/03_built-in_packages/20_utl_file.mdx
product_docs/docs/epas/17/reference/oracle_compatibility_reference/epas_compat_sql/22_create_directory.mdx
product_docs/docs/epas/17/reference/oracle_compatibility_reference/epas_compat_sql/46_drop_directory.mdx
product_docs/docs/epas/17/reference/oracle_compatibility_reference/epas_compat_sql/64_grant.mdx
product_docs/docs/epas/17/reference/oracle_compatibility_reference/epas_compat_sql/67_revoke.mdx

Update description now that users can be granted privileges on directories.
Addresses https://enterprisedb.atlassian.net/browse/DOCS-782

Update description of user privileges on UTL_FILE

---

advocacy_docs/pg_extensions/spl_check/using/index.mdx

Added verbiage to Using section of SPL Check
Addresses https://enterprisedb.atlassian.net/browse/DOCS-763.

Document deep spl_check enhancement

---

product_docs/docs/pem/9/monitoring_performance/probes.mdx

Copied the initial draft from #5903

PEM 9 - Target types update for Probes

---

install_template/config.yaml
product_docs/docs/edb_plus/41/installing/index.mdx
product_docs/docs/edb_plus/41/installing/linux_arm64/edbplus_debian_12.mdx
product_docs/docs/edb_plus/41/installing/linux_arm64/index.mdx
product_docs/docs/edb_plus/41/installing/linux_x86_64/edbplus_debian_12.mdx
product_docs/docs/edb_plus/41/installing/linux_x86_64/index.mdx
product_docs/docs/eprs/7/installing/index.mdx
product_docs/docs/eprs/7/installing/linux_arm64/eprs_debian_12.mdx
product_docs/docs/eprs/7/installing/linux_arm64/index.mdx
product_docs/docs/eprs/7/installing/linux_x86_64/eprs_debian_12.mdx
product_docs/docs/eprs/7/installing/linux_x86_64/index.mdx
product_docs/docs/migration_toolkit/55/installing/index.mdx
product_docs/docs/migration_toolkit/55/installing/linux_arm64/index.mdx
product_docs/docs/migration_toolkit/55/installing/linux_arm64/mtk_debian_12.mdx
product_docs/docs/migration_toolkit/55/installing/linux_x86_64/index.mdx
product_docs/docs/migration_toolkit/55/installing/linux_x86_64/mtk_debian_12.mdx
product_docs/docs/pem/9/pem_rel_notes/970_rel_notes.mdx
product_docs/docs/pem/9/registering_agent.mdx

PEM: Removed multi-host documentation.
EDB*Plus, MTK, Replication Server: added Debian 12 installation topics.

Release: 2024-08-14a

---

src/constants/updates.js

See draft deploy to check homepage rendering.

Add update for PEM 9.7

---

product_docs/docs/transporter/ba_preview/getting_started/apply_constraints.mdx
product_docs/docs/transporter/ba_preview/getting_started/prepare_schema.mdx

WIP
Kyle and I attempted to provide more context around schema import in the following PRs: 
https://github.com/EnterpriseDB/docs/pull/5908
https://github.com/EnterpriseDB/docs/pull/5883
After discussing what we want to recommend to customers, this PR replaces both other PRs and provides a path to follow.  
https://enterprisedb.atlassian.net/browse/DOCS-930
https://enterprisedb.atlassian.net/browse/DOCS-897

Improvements for schema migration

---

product_docs/docs/pge/13/release_notes/index.mdx

Fix remove HTML comments

---

advocacy_docs/security/assessments/cve-2024-7348.mdx
advocacy_docs/security/assessments/index.mdx
advocacy_docs/security/index.mdx

Security update added assesment for CVE-2024-7348

Security update added assesment for CVE-2024-7348

---

advocacy_docs/edb-postgres-ai/console/using/estate/cloud-hosted-databases.mdx
advocacy_docs/edb-postgres-ai/console/using/estate/edb-postgres-ai-clusters.mdx
advocacy_docs/edb-postgres-ai/console/using/estate/images/estateview.png
advocacy_docs/edb-postgres-ai/console/using/estate/images/managedstoragelocations.png
advocacy_docs/edb-postgres-ai/console/using/estate/index.mdx
advocacy_docs/edb-postgres-ai/console/using/estate/self-managed-postgres.mdx
advocacy_docs/edb-postgres-ai/console/using/estate/storage-locations.mdx
advocacy_docs/edb-postgres-ai/console/using/projects/clusters.mdx
advocacy_docs/edb-postgres-ai/console/using/projects/project_overview.mdx

Rework and fill out using/estate

Repair missing content in console using estate

---

product_docs/docs/pgd/5/ddl/ddl-replication-options.mdx

Typo fix from a past bulk change.

Fix bdr.ddl_replication default

---

product_docs/docs/migration_portal/4/04_mp_migrating_database/02_mp_schema_assessment.mdx
product_docs/docs/migration_portal/4/known_issues_notes.mdx

https://enterprisedb.atlassian.net/browse/MIG-5166 
https://enterprisedb.atlassian.net/browse/DOCS-936

Migration Portal: added unsupported objects to known issues

---

product_docs/docs/migration_portal/4/01_mp_release_notes/index.mdx
product_docs/docs/migration_portal/4/01_mp_release_notes/mp_4.11.0_rel_notes.mdx

https://enterprisedb.atlassian.net/browse/DOCS-908
https://enterprisedb.atlassian.net/browse/MIG-5173

Added release notes for MP 4.11.0

---

product_docs/docs/eprs/7/supported_platforms.mdx

https://enterprisedb.atlassian.net/browse/DOCS-921

EPRS: Removing EOL operating systems from java support page

---

product_docs/docs/pem/9/considerations/setup_ha_using_efm.mdx
product_docs/docs/pem/9/upgrading/upgrading_pem_installation/high_availability_upgrade.mdx

Edits to upgrade topic for PEM on high-availability mode #5923

---

product_docs/docs/pgd/5/data_migration/edbloader.mdx
product_docs/docs/pgd/5/data_migration/index.mdx
product_docs/docs/pgd/5/index.mdx

Added data migration section
Added EDB*Loader as first entry in it.

DOCS-798 support edbloader in pgd compatibility

---

product_docs/docs/migration_toolkit/55/10_error_codes.mdx

https://enterprisedb.atlassian.net/browse/DOCS-923 
https://enterprisedb.atlassian.net/browse/MTK-1370?focusedCommentId=623436 
Improving the consistency of formatting has been pointed out and will be handled for the next release.

MTK: error codes

---

product_docs/docs/migration_toolkit/55/mtk_rel_notes/index.mdx
product_docs/docs/migration_toolkit/55/mtk_rel_notes/mtk_5590_rel_notes.mdx

Migration Toolkit release notes for 55.9.0.

MTK: release notes for 55.9.0 

---

product_docs/docs/pgbouncer/1/pgbouncer_rel_notes/12310_rel_notes.mdx
product_docs/docs/pgbouncer/1/pgbouncer_rel_notes/index.mdx

PgBouncer - 1.23.1.0 release

---

product_docs/docs/efm/4/04_configuring_efm/01_cluster_properties.mdx

Updated the content as per [DOCS-125](https://enterprisedb.atlassian.net/browse/DOCS-125)
[DOCS-125]: https://enterprisedb.atlassian.net/browse/DOCS-125?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

EFM - cluster properties update

---

product_docs/docs/pgd/5/backup.mdx
product_docs/docs/pgd/5/compatibility.mdx
product_docs/docs/pgd/5/index.mdx
product_docs/docs/pgd/5/known_issues.mdx
product_docs/docs/pgd/5/parallelapply.mdx

Re-edit of PGD group 15

---

product_docs/docs/pgd/5/upgrades/upgrading_major_rolling.mdx

Reedit of PGD major rolling upgrades topic

---

product_docs/docs/pgd/5/durability/commit-scope-rules.mdx

just a typo, there was a duplicate word 'commit'

Found typo while reading PGD commit scope docs.

---

product_docs/docs/pgd/5/data_migration/edbloader.mdx
product_docs/docs/pgd/5/data_migration/index.mdx

Edits to DOCS-798 support edbloader in pgd compatibility PR5941

---

product_docs/docs/pge/13/release_notes/index.mdx
product_docs/docs/pge/14/release_notes/index.mdx
product_docs/docs/pge/15/release_notes/index.mdx
product_docs/docs/pge/15/release_notes/rel_notes15.8.1.mdx
product_docs/docs/pge/16/release_notes/index.mdx
product_docs/docs/pge/16/release_notes/rel_notes16.4.1.mdx

Release notes for minor release update

PGE .1 22 Aug 24

---

product_docs/docs/epas/14/epas_rel_notes/epas14_13_1_rel_notes.mdx
product_docs/docs/epas/14/epas_rel_notes/index.mdx
product_docs/docs/epas/16/epas_rel_notes/epas16_4_1_rel_notes.mdx
product_docs/docs/epas/16/epas_rel_notes/index.mdx
product_docs/docs/epas/16/epas_security_guide/05_edb_audit_logging/07_redacting_passwords_from_audit_logs.mdx

EPAS .1 updates Aug 16

---

product_docs/docs/pem/9/monitoring_performance/probes.mdx

Edits to PEM 9 - Target types update for Probes #5914

---

product_docs/docs/eprs/7/eprs_rel_notes/eprs_rel_notes_7.9.0.mdx

Edits to EPRS: release notes for 7.9.0 PR5968

---

product_docs/docs/pgd/5/monitoring/sql.mdx
product_docs/docs/pgd/5/node_management/heterogeneous_clusters.mdx
product_docs/docs/pgd/5/testingandtuning.mdx
product_docs/docs/pgd/5/transaction-streaming.mdx
product_docs/docs/pgd/5/twophase.mdx

Reedit of PGD - final group

---

product_docs/docs/eprs/7/05_smr_operation/08_optimizing_performance/02_optimize_sync_replication/using_bacth_lob.mdx

Edits to EPRS: batch LOB synchronization PR5936

---

product_docs/docs/efm/4/04_configuring_efm/01_cluster_properties.mdx

Edits to EFM - cluster properties update #5976

---

product_docs/docs/efm/4/efm_rel_notes/01_efm_410_rel_notes.mdx

Edits to EFM 4.10 Changes PR5932

---

product_docs/docs/pgd/5/reference/index.mdx

Index change checked in without updated index file

---

product_docs/docs/pgd/5/index.mdx
product_docs/docs/pgd/5/overview/index.mdx

DOCS-955 POC for new flow

---

product_docs/docs/pgd/5/reference/index.json
product_docs/docs/pgd/5/reference/index.mdx
product_docs/docs/pgd/5/reference/nodes-management-interfaces.mdx

Added basic doc for bdr.drop_node_group

Add basic bdr.drop_node_group reference

---

product_docs/docs/migration_toolkit/55/07_invoking_mtk/08_mtk_command_options.mdx
product_docs/docs/migration_toolkit/55/07_invoking_mtk/mtk_command_options_in_file/creating_txt_file.mdx
product_docs/docs/migration_toolkit/55/07_invoking_mtk/mtk_command_options_in_file/executing_migration_with_txt.mdx
product_docs/docs/migration_toolkit/55/07_invoking_mtk/mtk_command_options_in_file/index.mdx

Edits to Added new pages for MTK options file feature #5959

---

product_docs/docs/tde/15/enabling_tde.mdx

Fixed INPUT and OUTPUT code and made command executable

TDE: Fixed INPUT and OUTPUT code and made command executable

---

product_docs/docs/tpa/23/rel_notes/index.mdx

TPA patch for 23.34.1

---

product_docs/docs/tpa/23/rel_notes/index.mdx

Release: 2024-09-10a

---

product_docs/docs/pgd/5.6/reference/index.json
product_docs/docs/pgd/5.6/reference/index.mdx
product_docs/docs/pgd/5.6/reference/pgd-settings.mdx

Fix applied to PGD 5.6 branch

---

advocacy_docs/pg_extensions/query_advisor/index.mdx
advocacy_docs/pg_extensions/query_advisor/rel_notes/index.mdx
advocacy_docs/pg_extensions/query_advisor/rel_notes/query_advisor_1.1.1_rel_notes.mdx
advocacy_docs/pg_extensions/query_advisor/using.mdx

add stats recommendations function

---

advocacy_docs/edb-postgres-ai/analytics/quick_start.mdx
advocacy_docs/pg_extensions/query_advisor/index.mdx
advocacy_docs/pg_extensions/query_advisor/rel_notes/index.mdx
advocacy_docs/pg_extensions/query_advisor/rel_notes/query_advisor_1.1.1_rel_notes.mdx
advocacy_docs/pg_extensions/query_advisor/using.mdx
advocacy_docs/supported-open-source/postgresql/installing/windows.mdx
product_docs/docs/pgd/5/data_migration/edbloader.mdx
product_docs/docs/pgd/5/monitoring/sql.mdx
product_docs/docs/pgd/5/reference/functions.mdx
product_docs/docs/pgd/5/reference/index.json
product_docs/docs/pgd/5/reference/index.mdx
product_docs/docs/pgd/5/reference/pgd-settings.mdx
product_docs/docs/tde/15/index.mdx

TDE - Added OpenSSL as encryption software.
PGD - Updated bdr.raft_group_election_timeout and transaction_id references. Edits to EDBLoader.
PostgreSQL - Added limitation to ASCII characters for Windows installation.
EDB Query Advisor - 1.1.1 release.

Release: 2024-09-12a

---

advocacy_docs/dev-guides/deploy/docker.mdx
advocacy_docs/dev-guides/developing/developing-postgres-applications-with-python.mdx
advocacy_docs/dev-guides/developing/index.mdx
advocacy_docs/dev-guides/index.mdx

Frontpage cleanup work

---

product_docs/docs/lasso/4/configuration.mdx
product_docs/docs/lasso/4/describe.mdx
product_docs/docs/lasso/4/install.mdx
product_docs/docs/lasso/4/release-notes.mdx
product_docs/docs/lasso/4/report-types.mdx
product_docs/docs/lasso/4/usage.mdx

Lasso Release 4.17.0

---

advocacy_docs/edb-postgres-ai/overview/index.mdx
src/components/left-nav.js
src/components/search-navigation.js
src/components/side-navigation.js

Fixes to infobox to make it all clickable for all pages.
Fixes to EDB/docs title to correct formatting and remove double underlining.

Misc fixes to infobox and EDB/docs header

---

src/pages/index.js

Tweaked boxing, revealed accidentally hidden migration handbook

tweak boxing

---

product_docs/docs/epas/11/epas_compat_sql/21_create_public_database_link.mdx

Fix version for OCI in 21_create_public_database_link.mdx

---

product_docs/docs/epas/11/epas_compat_sql/21_create_public_database_link.mdx
product_docs/docs/epas/12/epas_compat_sql/21_create_public_database_link.mdx
product_docs/docs/epas/13/epas_compat_sql/21_create_public_database_link.mdx
product_docs/docs/epas/14/epas_compat_sql/21_create_public_database_link.mdx
product_docs/docs/epas/16/reference/oracle_compatibility_reference/epas_compat_sql/21_create_public_database_link.mdx

#6058 EPAS - Added oracle 19c support to Database link
#6071 Tweak boxing on front page and restore accidental ommmission

Release 2024-09-19a

---

product_docs/docs/pgd/5/reference/index.json
product_docs/docs/pgd/5/reference/index.mdx
product_docs/docs/pgd/5/reference/pgd-settings.mdx

Added reference bdr.lock_table_locking 
Converted to tables for values
Added defaults for bdr.ddl_locking

Added reference, converted to tables, added defaults

---

product_docs/docs/pgd/5/reference/functions-internal.mdx

Reworked the bdr.drop_node warning/advice. /pgd/latest/reference/functions-internal#bdrdrop_node

Rework bdr.drop_node

---

src/components/footer.js

Adds Trust Center to the footer menu

Trust Center in footer menu

---

product_docs/docs/pem/9/considerations/pem_pgbouncer/configuring_pgBouncer.mdx
product_docs/docs/pem/9/considerations/pem_pgbouncer/configuring_the_pem_agent.mdx
product_docs/docs/pem/9/considerations/pem_pgbouncer/index.mdx
product_docs/docs/pem/9/considerations/pem_pgbouncer/pem_server_pem_agent_connection_management_mechanism.mdx
product_docs/docs/pem/9/considerations/pem_pgbouncer/preparing_the_pem_database_server.mdx

Edits to PEM with PgBouncer-customer issue PR5950

---

src/components/index-sub-nav.js
src/components/side-navigation.js

Updated links in sidebar for Knowledge Base

DOCS-1039: Sidebar KB entries updated

---

product_docs/docs/lasso/4/describe.mdx

Made descriptions of the new functions consistent with other descriptions (imperative followed by period).

Edits to Lasso Release 4.17.0 PR6052

---

product_docs/docs/pgd/5/reference/functions.mdx

Edits to PGD: improve description of "transaction_id" pseudo-GUC PR6048

---

product_docs/docs/tde/15/enabling_tde_epas.mdx
product_docs/docs/tde/15/index.mdx
product_docs/docs/tde/15/pg_upgrade_arguments.mdx
product_docs/docs/tde/15/upgrade_use_cases/index.mdx
product_docs/docs/tde/15/upgrade_use_cases/postgres_to_extended.mdx

https://enterprisedb.atlassian.net/browse/DOCS-97 
A bug that was blocking us from adding this tutorial was fixed, and included in the latest versions of PGE.

TDE: pg to pge tutorial while enabling TDE

---

product_docs/docs/epas/12/epas_compat_sql/21_create_public_database_link.mdx
product_docs/docs/epas/13/epas_compat_sql/21_create_public_database_link.mdx
product_docs/docs/epas/14/epas_compat_sql/21_create_public_database_link.mdx
product_docs/docs/epas/15/reference/oracle_compatibility_reference/epas_compat_sql/21_create_public_database_link.mdx
product_docs/docs/epas/16/reference/oracle_compatibility_reference/epas_compat_sql/21_create_public_database_link.mdx

Added Oracle 21c in a note for database link

EPAS - Added oracle 21c

---

advocacy_docs/edb-postgres-ai/migration-etl/data-migration-service/index.mdx
advocacy_docs/edb-postgres-ai/migration-etl/data-migration-service/known_issues.mdx
advocacy_docs/edb-postgres-ai/migration-etl/data-migration-service/limitations.mdx

We already have a "Limitations" page where we have listed all known issues, limitations and notes for the EDB DMS. 
This PR removes the duplicate page, and changes the name of the Limitations page to be more in line with what it contains.

Removed "Known Issues" section and altered "Limitations" page title

---

advocacy_docs/dev-guides/deploy/images/pgadmin-connected.png
advocacy_docs/dev-guides/deploy/images/pgadmin-default.png
advocacy_docs/dev-guides/deploy/images/pgadmin-register-server.png
advocacy_docs/dev-guides/deploy/windows.mdx

Quick & basic rundown of steps to get PostgreSQL installed on a dev machine

PostgreSQL on Windows dev env topic

---

product_docs/docs/eprs/7/07_common_operations/09_offline_snapshot.mdx

Edits to EPRS: fix to offline snapshot steps PR5985

---

tools/user/mergeq/.gitignore
tools/user/mergeq/README.md
tools/user/mergeq/mergeq.js
tools/user/mergeq/package-lock.json
tools/user/mergeq/package.json

New tool, works out whats been merged but not published yet.

Adding mergeq tool

---

advocacy_docs/edb-postgres-ai/migration-etl/data-migration-service/getting_started/installing/index.mdx
advocacy_docs/edb-postgres-ai/migration-etl/data-migration-service/getting_started/installing/linux_x86_64/index.mdx
install_template/templates/products/edb-data-migration-service-reader/index.njk
install_template/templates/products/edb-data-migration-service-reader/x86_64_index.njk

Removed the extra index cards from the index pages of DMS installation topics
https://enterprisedb.atlassian.net/browse/DOCS-1040

DMS - Index page fix

---

product_docs/docs/pgd/5/reference/pgd-settings.mdx

Made consistent with the other options in this topic.

Edits to Added reference, converted to tables, added defaults pgd pr6081

---

product_docs/docs/tde/15/enabling_tde_epas.mdx
product_docs/docs/tde/15/upgrade_use_cases/postgres_to_extended.mdx

Edits to TDE: pg to pge tutorial while enabling TDE #6029

---

product_docs/docs/tde/15/key_stores.mdx

https://enterprisedb.atlassian.net/browse/DOCS-1038

TDE: Added Fortanix as available TDE key store

---

src/constants/updates.js

Fix bad link less junk

---

advocacy_docs/supported-open-source/barman/single-server-streaming/step02-backup-setup.mdx
product_docs/docs/tde/15/key_stores.mdx
src/constants/updates.js

#6127 : Fix bad link less junk
#4938 : Update step02-backup-setup.mdx
#6108 : TDE: Added Fortanix as available TDE key store

Release 2024-10-04a

---

advocacy_docs/dev-guides/index.mdx

Dev Guides: added new topic to index

---

advocacy_docs/dev-guides/deploy/windows.mdx

Fix navTitle on Windows

---

product_docs/docs/pgd/5/node_management/creating_and_joining.mdx
product_docs/docs/pgd/5/security/role-management.mdx

Edits to pgd: clarify joining nodes with non-default extensions #6099

---

product_docs/docs/pgd/5.6/node_management/decoding_worker.mdx

DOCS-1001-Repicked

---

advocacy_docs/partner_docs/ThalesCipherTrustManager/04-ConfiguringThalesCipherTrustManager.mdx

Typo in Thales Manager doc

---

product_docs/docs/pgd/5.6/nodes/subscriber_only/index.mdx
product_docs/docs/pgd/5.6/nodes/subscriber_only/joining-so.mdx
product_docs/docs/pgd/5.6/nodes/subscriber_only/optimizing-so.mdx

Fixes and improvements on the SO docs

---

product_docs/docs/pgd/4/rel_notes/index.mdx
product_docs/docs/pgd/4/rel_notes/pgd_4.3.6_rel_notes.mdx
product_docs/docs/pgd/4/rel_notes/src/relnote_4.3.6.yml
product_docs/docs/pgd/5.6/rel_notes/index.mdx
product_docs/docs/pgd/5.6/rel_notes/pgd_5.6.0_rel_notes.mdx
product_docs/docs/pgd/5.6/rel_notes/src/relnote_5.6.0.yml
tools/automation/generators/relnoted/package-lock.json
tools/automation/generators/relnoted/package.json
tools/automation/generators/relnoted/relnoted.js
tools/automation/generators/relnoted/relnotetester.yml

DOCS-1059 Release Notes (4.3.6 and 5.6)

---

product_docs/docs/pgd/5.6/nodes/subscriber_only/index.mdx
product_docs/docs/pgd/5.6/nodes/subscriber_only/overview.mdx

Review required overview rework

Fixes and rework

---

advocacy_docs/edb-postgres-ai/analytics/concepts.mdx

Remove splitgraph ref

---

advocacy_docs/edb-postgres-ai/cloud-service/getting_started/creating_cluster/creating_a_cluster.mdx

Fixed link for adding key to point into console using projects settings security with an absolute link as it was climbing up 3 directory levels and missing.

Fix link with readable absolute link

---

advocacy_docs/edb-postgres-ai/migration-etl/index.mdx
advocacy_docs/pg_extensions/query_advisor/index.mdx

Drafting something up where we can hopefully outline the differences among the migration tools EDB offers.

EDB Postgres AI Migrations page

---

product_docs/docs/migration_portal/4/known_issues_notes.mdx

Edits to Migration Portal: workaround for snapshot too old error PR6124

---

advocacy_docs/pg_extensions/query_advisor/index.mdx
advocacy_docs/pg_extensions/query_advisor/using.mdx

Edits to add stats recommendations function pgextensions pr6035

---

product_docs/docs/pgd/5.6/reference/catalogs-internal.mdx
product_docs/docs/pgd/5/reference/catalogs-internal.mdx

Added bdr.node_config_summary to 5 and 5.6 PGD reference docs.

Docs 1030 - Add bdr.node_config_summary to 5 and 5.6 PGD reference docs

---

product_docs/docs/pgd/5.6/reference/index.json
product_docs/docs/pgd/5.6/reference/index.mdx
product_docs/docs/pgd/5/reference/index.json
product_docs/docs/pgd/5/reference/index.mdx
tools/automation/generators/refbuilder/refbuilder.js

This should fix up the reference generator to remove latest generation and handle versions more statically.

Fixed up indexes, removed latest reversioning from indexes.

---

product_docs/docs/eprs/7/06_mmr_operation/06_conflict_resolution/07_auto_conflict_resolution_eg.mdx

EPRS: typo

---

product_docs/docs/eprs/7/06_mmr_operation/index.mdx

Missing verb, altered sentence a bit.

EPRS: missing verb on MMR page

---

product_docs/docs/pgd/5.6/rel_notes/pgd_5.6.0_rel_notes.mdx
product_docs/docs/pgd/5.6/rel_notes/src/relnote_5.6.0.yml

Some older release notes were included by accident. They have been eliminated.

Post release fixup release notes

---

product_docs/docs/pgd/5.6/known_issues.mdx

Known issues as of 30Oct update

---

advocacy_docs/edb-postgres-ai/console/using/notifications.mdx

Addresses [DOCS-740](https://enterprisedb.atlassian.net/browse/DOCS-740)
[DOCS-740]: https://enterprisedb.atlassian.net/browse/DOCS-740?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Cloud Service - Expanding notifications

---

advocacy_docs/edb-postgres-ai/console/using/notifications.mdx

Released today:
#6143 : Cloud Service - Expanding notifications

Release: 2024-11-05a

---

advocacy_docs/repos/migration/index.mdx

Remove October from the sunset date for Repos 1.0

Remove October

---

product_docs/docs/pgd/5.6/reference/index.json
product_docs/docs/pgd/5.6/reference/index.mdx
product_docs/docs/pgd/5.6/reference/nodes.mdx

bdr_config in node docs, and refreshed listing to a table.

DOCS-1077 - Added bdr_config - reformatted node state table.

---

product_docs/docs/postgres_for_kubernetes/1/evaluation.mdx

PG4K - Shorter version of eval page (migrated over)

---

product_docs/docs/postgres_distributed_for_kubernetes/1/architecture.mdx
product_docs/docs/postgres_distributed_for_kubernetes/1/backup.mdx
product_docs/docs/postgres_distributed_for_kubernetes/1/connectivity.mdx
product_docs/docs/postgres_distributed_for_kubernetes/1/labels_annotations.mdx
product_docs/docs/postgres_distributed_for_kubernetes/1/ldap.mdx
product_docs/docs/postgres_distributed_for_kubernetes/1/managed.mdx
product_docs/docs/postgres_distributed_for_kubernetes/1/mutations.mdx
product_docs/docs/postgres_distributed_for_kubernetes/1/pg4k-pgd.v1beta1.mdx
product_docs/docs/postgres_distributed_for_kubernetes/1/recovery.mdx

Edits to  Postgres Distributed for Kubernetes v1.0.1 #6152

---

product_docs/docs/pgd/3.7/pglogical/subscriptions/index.mdx

Added small note on slot name generator.

Add gen_slot_name note

---

advocacy_docs/edb-postgres-ai/cloud-service/release_notes/2023/2023_01_jan_rel_notes.mdx
advocacy_docs/edb-postgres-ai/cloud-service/release_notes/2023/2023_02_feb_rel_notes.mdx
advocacy_docs/edb-postgres-ai/cloud-service/release_notes/2023/2023_03_mar_rel_notes.mdx
advocacy_docs/edb-postgres-ai/cloud-service/release_notes/2023/2023_04_apr_rel_notes.mdx
advocacy_docs/edb-postgres-ai/cloud-service/release_notes/2023/2023_05_may_rel_notes.mdx
advocacy_docs/edb-postgres-ai/cloud-service/release_notes/2023/2023_06_jun_rel_notes.mdx
advocacy_docs/edb-postgres-ai/cloud-service/release_notes/2023/2023_07_jul_rel_notes.mdx
advocacy_docs/edb-postgres-ai/cloud-service/release_notes/2023/2023_08_aug_rel_notes.mdx
advocacy_docs/edb-postgres-ai/cloud-service/release_notes/2023/2023_09_sep_rel_notes.mdx
advocacy_docs/edb-postgres-ai/cloud-service/release_notes/2023/2023_10_oct_rel_notes.mdx
advocacy_docs/edb-postgres-ai/cloud-service/release_notes/2023/2023_11_nov_rel_notes.mdx
advocacy_docs/edb-postgres-ai/cloud-service/release_notes/2023/2023_12_dec_rel_notes.mdx
advocacy_docs/edb-postgres-ai/cloud-service/release_notes/2023/index.mdx
advocacy_docs/edb-postgres-ai/cloud-service/release_notes/2024_01_jan_rel_notes.mdx
advocacy_docs/edb-postgres-ai/cloud-service/release_notes/2024_02_feb_rel_notes.mdx
advocacy_docs/edb-postgres-ai/cloud-service/release_notes/2024_03_mar_rel_notes.mdx
advocacy_docs/edb-postgres-ai/cloud-service/release_notes/2024_04_apr_rel_notes.mdx
advocacy_docs/edb-postgres-ai/cloud-service/release_notes/2024_05_may_rel_notes.mdx
advocacy_docs/edb-postgres-ai/cloud-service/release_notes/2024_06_jun_rel_notes.mdx
advocacy_docs/edb-postgres-ai/cloud-service/release_notes/2024_07_jul_rel_notes.mdx
advocacy_docs/edb-postgres-ai/cloud-service/release_notes/2024_08_aug_rel_notes.mdx
advocacy_docs/edb-postgres-ai/cloud-service/release_notes/2024_09_sep_rel_notes.mdx
advocacy_docs/edb-postgres-ai/cloud-service/release_notes/2024_10_oct_rel_notes.mdx
advocacy_docs/edb-postgres-ai/cloud-service/release_notes/index.mdx
tools/user/import/bareleasenotes/barelease.js

New layout for release page to
allow for folded years 
(Folding and new item indexing still manual)
Redirections autogenerated to ensure all notes will always be found even when folded into a directory.

Redesigned layout, updated barelease for robustness

---

advocacy_docs/edb-postgres-ai/cloud-service/index.mdx

Target page needs significant updates as well; this PR is a reminder to update inbound link context.

Reconcile aidb descriptions and link context on CS page

---

product_docs/docs/pge/13/release_notes/index.mdx
product_docs/docs/pge/14/release_notes/index.mdx
product_docs/docs/pge/15/release_notes/index.mdx
product_docs/docs/pge/15/release_notes/rel_notes15.9.mdx
product_docs/docs/pge/16/release_notes/index.mdx
product_docs/docs/pge/16/release_notes/rel_notes16.5.mdx

Added RN for 16.5.0, 15.9.0, 14.14.0, and 13.17. 
We have no 12 branch of documentation for PGE, hence not including release notes for 12.21 here.
https://enterprisedb.atlassian.net/browse/DOCS-1114

PGE: added release notes for nov's minor release

---

product_docs/docs/epas/12/epas_rel_notes/epas12_21_26_rel_notes.mdx
product_docs/docs/epas/12/epas_rel_notes/index.mdx
product_docs/docs/epas/13/epas_rel_notes/epas13_17_23_rel_notes.mdx
product_docs/docs/epas/13/epas_rel_notes/index.mdx
product_docs/docs/epas/14/epas_rel_notes/epas14_14_0_rel_notes.mdx
product_docs/docs/epas/14/epas_rel_notes/index.mdx
product_docs/docs/epas/15/epas_rel_notes/epas15_9_0_rel_notes.mdx
product_docs/docs/epas/15/epas_rel_notes/index.mdx
product_docs/docs/epas/16/epas_rel_notes/epas16_5_0_rel_notes.mdx
product_docs/docs/epas/16/epas_rel_notes/index.mdx
product_docs/docs/pge/13/release_notes/index.mdx
product_docs/docs/pge/14/release_notes/index.mdx
product_docs/docs/pge/15/release_notes/index.mdx
product_docs/docs/pge/15/release_notes/rel_notes15.9.mdx
product_docs/docs/pge/16/release_notes/index.mdx
product_docs/docs/pge/16/release_notes/rel_notes16.5.mdx

#6233 : EPAS minor release - release notes
#6237 : PGE: added release notes for nov's minor release

Release: 2024-11-14b

---

advocacy_docs/security/assessments/cve-2020-10531.mdx
advocacy_docs/security/assessments/index.mdx
advocacy_docs/security/index.mdx
tools/automation/generators/advisoryindex/advisoryindex.js

Security update (post rollback of feature changes)

Release 2024-11-14c

---

product_docs/docs/pgd/5.6/reference/catalogs-internal.mdx
product_docs/docs/pgd/5.6/reference/catalogs-visible.mdx

PGD #6221
Teeny edits for consistency in using periods for items in a table. (If one takes a period, all take a period.)

Edits to Docs 1104 Document missing optimized topology changes to tables

---

product_docs/docs/tde/15/secure_key/key_store.mdx

Adding Entrust to the list of supported KMS.
https://enterprisedb.atlassian.net/browse/DOCS-540

TDE: added Entrust to the list of supported key management systems

---

product_docs/docs/migration_toolkit/55/02_supported_operating_systems_and_database_versions.mdx

Short PR to ad PG and EPAS 17 as supported versions.
https://enterprisedb.atlassian.net/browse/DOCS-974
https://enterprisedb.atlassian.net/browse/DOCS-768
Once approved, this can be merged to the release branch DOCS-1088-Tracking-55.10-work.

MTK 55.10: Updated support page

---

advocacy_docs/edb-postgres-ai/migration-etl/data-migration-service/getting_started/config_reader.mdx

The comments in this script have been updated for better documentation and to reflect new supported capabilities for the PG AI platform.

fix(UPM-42248): Updates the run-cdcreader.sh script example

---

product_docs/docs/net_connector/8.0.5.1/01_release_notes.mdx
product_docs/docs/net_connector/8.0.5.1/03_the_advanced_server_net_connector_overview.mdx

https://enterprisedb.atlassian.net/browse/DOCS-1122

.NET: release notes for 8.0.5.1

---

product_docs/docs/pgd/5.6/commit-scopes/group-commit.mdx

Added warning about group commit

Mark group commit preview

---

product_docs/docs/pgd/5.6/rel_notes/index.mdx
product_docs/docs/pgd/5.6/rel_notes/pgd_5.6.1_rel_notes.mdx
product_docs/docs/pgd/5.6/rel_notes/src/relnote_5.6.1.yml

PGD 5.6.1 release notes

---

product_docs/docs/livecompare/3/oracle_support.mdx
product_docs/docs/livecompare/3/rel_notes/3.0.2_rel_notes.mdx
product_docs/docs/livecompare/3/rel_notes/index.mdx

3.0.2 release update

---

product_docs/docs/migration_toolkit/55/02_supported_operating_systems_and_database_versions.mdx
product_docs/docs/migration_toolkit/55/07_invoking_mtk/08_mtk_command_options.mdx
product_docs/docs/migration_toolkit/55/mtk_rel_notes/index.mdx
product_docs/docs/migration_toolkit/55/mtk_rel_notes/mtk_55100_rel_notes.mdx

This branch tracks all changes, updates, and new features that will go into MTK version 55.10.0. 
https://enterprisedb.atlassian.net/browse/DOCS-1088
Covers: 
https://enterprisedb.atlassian.net/browse/DOCS-1019 approved
https://enterprisedb.atlassian.net/browse/DOCS-974 approved
https://enterprisedb.atlassian.net/browse/DOCS-768 approved
https://enterprisedb.atlassian.net/browse/MTK-1423 approved
Tentatively going out on the 21th.

MTK 55.10 release branch 

---

product_docs/docs/migration_portal/4/04_mp_migrating_database/01_mp_schema_extraction/01_data_pump_utility.mdx
product_docs/docs/migration_portal/4/04_mp_migrating_database/01_mp_schema_extraction/edb_ddl_extractor.mdx
product_docs/docs/migration_portal/4/04_mp_migrating_database/01_mp_schema_extraction/index.mdx
product_docs/docs/migration_portal/4/04_mp_migrating_database/index.mdx

https://enterprisedb.atlassian.net/browse/DOCS-1112 
- Added warning to advise customer to use the supported methods for extractions. 
- Rephrased the first intro section.
- Took the "Using EDB DDL Extractor" and put it on its own dedicated page for better order of information.

Mig Portal: DDL Extractor note and reorg of extraction section

---

product_docs/docs/net_connector/8.0.5.1/01_release_notes.mdx

Updated NET release date

---

product_docs/docs/pgd/5.6/reference/autopartition.mdx

Reflects following changes made in 5.6.0:
- default value for "managed_locally" set to TRUE (commit 1348c853)
- parameter "analytics_offload_period" added (commit 52da8023)
DOCS-1129.

PGD: update bdr.autopartition() function description for changes in 5.6

---

product_docs/docs/migration_portal/4/01_mp_release_notes/index.mdx
product_docs/docs/migration_portal/4/01_mp_release_notes/mp_4.12.0_rel_notes.mdx
product_docs/docs/migration_portal/4/02_supported_platforms.mdx

#6265 : Migration Portal: 4.12.0 release

Production Release: 2024-11-25b

---

product_docs/docs/tpa/23/rel_notes/index.mdx
product_docs/docs/tpa/23/rel_notes/src/tpa_23.35.0_rel_notes.yml
product_docs/docs/tpa/23/rel_notes/tpa_23.35.0_rel_notes.mdx

Added three part version numbers and rebuild release notes.

3 part version number added

---

product_docs/docs/pgd/5.6/compatibility.mdx

Fix PGD compat table (remove 24.04 typo)

Fix compat listings

---

product_docs/docs/pgd/5.6/planning/choosing_server.mdx

Fix typo in choosing_server.mdx

---

advocacy_docs/edb-postgres-ai/cloud-service/using_cluster/cli/managing_clusters.mdx
advocacy_docs/edb-postgres-ai/cloud-service/using_cluster/cli/using_features.mdx

Added new feature 'Tags' in CLI

CLI 3.10 - Release

---

advocacy_docs/edb-postgres-ai/cloud-service/using_cluster/cli/managing_clusters.mdx
advocacy_docs/edb-postgres-ai/cloud-service/using_cluster/cli/using_features.mdx
product_docs/docs/pgd/5.6/planning/choosing_server.mdx

#6313 : CLI 3.10 - Release
#6312 : Fix typo in choosing_server.mdx

Release: 2024-11-28a

---

product_docs/docs/livecompare/3/oracle_support.mdx
product_docs/docs/livecompare/3/rel_notes/3.0.2_rel_notes.mdx

Edits to 3.0.2 release update #6225

---

advocacy_docs/edb-postgres-ai/console/estate/agent/install-agent.mdx

Typos in Install Beacon agent doc

---

advocacy_docs/pg_extensions/wait_states/configuring.mdx

Teeny edit...thought I had more when I created the branch.

Edits to add configuring section #6177

---

advocacy_docs/edb-postgres-ai/cloud-service/index.mdx
advocacy_docs/edb-postgres-ai/index.mdx

Notice for Cloud Service explicitly states Your Cloud Account is still in operation.

Updated for DOCS-1145

---

product_docs/docs/pgd/5/node_management/subscriber_only.mdx

Added text for clarity of purpose.

DOCS-733 - Added clarity to subscriber-only node purpose.

---

advocacy_docs/pg_extensions/pgvector/index.mdx
advocacy_docs/pg_extensions/pgvector/installing.mdx
advocacy_docs/pg_extensions/pgvector/rel_notes/index.mdx
advocacy_docs/pg_extensions/pgvector/using.mdx

Edits to Add pem-port to options table #6229

---

advocacy_docs/edb-postgres-ai/overview/latest-release-news/2024q4release.mdx
src/pages/index.js

Q42024 Updates

---

src/constants/updates.js

Updated news boxes

---

product_docs/docs/tde/15/enabling/enabling_tde.mdx
product_docs/docs/tde/15/enabling/enabling_tde_epas.mdx
product_docs/docs/tde/15/enabling/postgres_to_extended.mdx
product_docs/docs/tde/15/encrypted_files/wal_files.mdx
product_docs/docs/tde/15/initdb_tde_options.mdx
product_docs/docs/tde/15/secure_key/disabling_key.mdx
product_docs/docs/tde/15/secure_key/index.mdx
product_docs/docs/tde/15/secure_key/key_store.mdx
product_docs/docs/tde/15/secure_key/passphrase.mdx

Some High priority fixes and iprovements for https://enterprisedb.atlassian.net/browse/DOCS-1147

TDE: improvements and fixes for DOCS-1147

---

.github/workflows/generate-release-notes.yml
.github/workflows/sync-and-process-files.yml
advocacy_docs/edb-postgres-ai/overview/latest-release-news/2024q4release.mdx
product_docs/docs/pgd/5.6/terminology.mdx
product_docs/docs/pge/13/release_notes/index.mdx
product_docs/docs/postgres_distributed_for_kubernetes/1/index.mdx
product_docs/docs/postgres_for_kubernetes/1/index.mdx
product_docs/docs/tde/15/enabling/enabling_tde.mdx
product_docs/docs/tde/15/enabling/enabling_tde_epas.mdx
product_docs/docs/tde/15/enabling/postgres_to_extended.mdx
product_docs/docs/tde/15/encrypted_files/wal_files.mdx
product_docs/docs/tde/15/initdb_tde_options.mdx
product_docs/docs/tde/15/secure_key/disabling_key.mdx
product_docs/docs/tde/15/secure_key/index.mdx
product_docs/docs/tde/15/secure_key/key_store.mdx
product_docs/docs/tde/15/secure_key/passphrase.mdx
scripts/fileProcessor/package-lock.json
scripts/fileProcessor/processors/cnp/add-frontmatters.mjs
scripts/fileProcessor/processors/cnp/update-yaml-links.mjs
scripts/source/dispatch_product.py
scripts/source/process-cnp-docs.sh
src/constants/updates.js
src/pages/index.js

#6342 : TDE: improvements and fixes for DOCS-1147
#6348 : Updated news boxes
#6347 : Q42024 Updates
#6341 : PGE 13.x: corrected semantic versioning
#6308 : PG4K - fix for pages and feedback
#6344 : Update cluster definition in  terminology.mdx

Release: 2024-12-12a

---

product_docs/docs/pgd/5.6/upgrades/upgrade_paths.mdx

Update upgrade_paths.mdx with semantic versioning note

---

product_docs/docs/pgd/5.6/upgrades/upgrade_paths.mdx
product_docs/docs/tde/15/enabling/enabling_key_wrapper.mdx
product_docs/docs/tde/15/enabling/index.mdx
product_docs/docs/tde/15/secure_key/disabling_key.mdx
product_docs/docs/tde/15/secure_key/passphrase.mdx

#6352 : Update upgrade_paths.mdx with semantic versioning note
#6351 : TDE: tutorials to enable data wrapper and provide passphrase in file

Release: 2024-12-17a

---

product_docs/docs/postgres_for_kubernetes/1/index.mdx

Updated front page to match licensing for review.
Same change is upstream by 1 and if approved will be upstreamed to maint.

Updated front page

---

product_docs/docs/postgres_distributed_for_kubernetes/1/installation_upgrade.mdx

Update installation_upgrade.mdx fix typo

---

advocacy_docs/edb-postgres-ai/analytics/index.mdx

Small fix to lakehouse nav as it was out of order

Fix lakehouse nav being out of order

---

product_docs/docs/postgres_for_kubernetes/1/openshift.mdx

Replicates upstream PR correcting docs.

Update openshift.mdx to 1.25 ahead of next merge

---

product_docs/docs/postgres_distributed_for_kubernetes/1/architecture.mdx
product_docs/docs/postgres_distributed_for_kubernetes/1/installation_upgrade.mdx
product_docs/docs/postgres_distributed_for_kubernetes/1/pg4k-pgd.v1beta1.mdx
product_docs/docs/postgres_distributed_for_kubernetes/1/private_edb_registries.mdx
product_docs/docs/postgres_distributed_for_kubernetes/1/supported_versions.mdx

- Correct version support for OpenShift
- A few other minor corrections & updates

Bring in corrections to pgd4k 1.1 docs

---

advocacy_docs/pg_extensions/pg_tuner/using.mdx
product_docs/docs/pgd/5.6/overview/architecture-and-performance.mdx
product_docs/docs/pgd/5.6/overview/basic-architecture.mdx
product_docs/docs/pgd/5.6/overview/compared.mdx
product_docs/docs/pgd/5.6/overview/index.mdx

Added comparison matrix to overview section, reorganised overview section.

Docs 291 - Add PGD comparison matrix

---

product_docs/docs/pgd/5.6/overview/architecture-and-performance.mdx
product_docs/docs/pgd/5.6/overview/basic-architecture.mdx
product_docs/docs/pgd/5.6/overview/compared.mdx

Mostly edited to add the period to descriptions. Had one query.

Edits to Docs 291 - Add PGD comparison matrix #6394

---

product_docs/docs/pgd/3.7/bdr/release-notes.mdx
product_docs/docs/pgd/3.7/pglogical/release-notes.mdx
product_docs/docs/pgd/4/upgrades/upgrade_paths.mdx

Add missing release notes for PGD 3.7

---

.github/workflows/build-pages.yml
.github/workflows/deploy-to-netlify.yml
advocacy_docs/edb-postgres-ai/cloud-service/index.mdx
product_docs/docs/net_connector/4.0.10.1/index.mdx
product_docs/docs/net_connector/4.0.6.1/index.mdx
product_docs/docs/net_connector/4.1.3.1/index.mdx
product_docs/docs/net_connector/4.1.5.1/index.mdx
product_docs/docs/pgd/3.7/bdr/release-notes.mdx
product_docs/docs/pgd/3.7/pglogical/release-notes.mdx
product_docs/docs/pgd/4/upgrades/upgrade_paths.mdx
product_docs/docs/pgd/5.6/overview/architecture-and-performance.mdx
product_docs/docs/pgd/5.6/overview/basic-architecture.mdx
product_docs/docs/pgd/5.6/overview/compared.mdx
scripts/pdf/generate_pdf.py

- Docs 291 - Add PGD comparison matrix
- Edits to Docs 291 - Add PGD comparison matrix
- Add missing release notes for PGD 3.7
- Misc corrections for parallel PDF build changes

Release: 2025-01-14a

---

product_docs/docs/pgd/5.6/appusage/extensions.mdx

Changed link to subdocument of new overview

---

advocacy_docs/migrating/oracle/oracle_epas_comparison/app_devel_capabilities.mdx
advocacy_docs/migrating/oracle/oracle_epas_comparison/non_relational_data.mdx
advocacy_docs/migrating/oracle/oracle_epas_comparison/notable_differences.mdx

https://enterprisedb.atlassian.net/browse/DOCS-1151 
Added some EPAS 17 updated to the Migration Handbook.

Migration Handbook: EPAS 17 updates

---

advocacy_docs/pg_extensions/wait_states/installing.mdx
advocacy_docs/supported-open-source/postgresql/uninstalling.mdx
product_docs/docs/language_pack/4/installing/windows.mdx

Addresses [DOCS-939](https://enterprisedb.atlassian.net/browse/DOCS-939), [DOCS-1096](https://enterprisedb.atlassian.net/browse/DOCS-1096), [DOCS-962](https://enterprisedb.atlassian.net/browse/DOCS-962)
[DOCS-939]: https://enterprisedb.atlassian.net/browse/DOCS-939?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DOCS-1096]: https://enterprisedb.atlassian.net/browse/DOCS-1096?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DOCS-962]: https://enterprisedb.atlassian.net/browse/DOCS-962?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Backlogs - Wait States, PostgreSQL, Language Pack

---

product_docs/docs/postgres_for_kubernetes/1/bootstrap.mdx

Fixes for naming and license reference

---

advocacy_docs/edb-postgres-ai/ai-accelerator/compatibility.mdx

Update platform availability

---

product_docs/docs/pgd/5/reference/functions.mdx

docs/fixing loose comma.

---

product_docs/docs/lasso/4/configuration.mdx
product_docs/docs/lasso/4/describe.mdx
product_docs/docs/lasso/4/install.mdx
product_docs/docs/lasso/4/release-notes.mdx
product_docs/docs/lasso/4/usage.mdx

Lasso release 4.18.0

---

advocacy_docs/dev-guides/deploy/docker.mdx
advocacy_docs/dev-guides/deploy/windows.mdx
advocacy_docs/dev-guides/index.mdx
advocacy_docs/dev-guides/working/psql-for-busy-developers.mdx

Edited all this doc while I was i there.

Edits to PostgreSQL on Windows dev env topic #6063

---

advocacy_docs/migrating/oracle/oracle_epas_comparison/app_devel_capabilities.mdx
advocacy_docs/migrating/oracle/oracle_epas_comparison/non_relational_data.mdx
advocacy_docs/migrating/oracle/oracle_epas_comparison/notable_differences.mdx

Addressed some consistency issues I missed in earlier edits.

Edits to Migration Handbook: EPAS 17 updates #6402

---

product_docs/docs/pem/9/monitoring_performance/probes.mdx

Edits to Update probes.mdx #6323

---

product_docs/docs/migration_portal/4/known_issues_notes.mdx

https://enterprisedb.atlassian.net/browse/MIG-5001 
https://enterprisedb.atlassian.net/browse/DOCS-1178

MP: terminated DDL assessment due to EPAS-reserved words

---

advocacy_docs/edb-postgres-ai/ai-accelerator/models/using-models.mdx

Fix close paretheses (not curly)

Update using-models.mdx - typo fix

---

product_docs/docs/net_connector/8.0.5.1/02_requirements_overview.mdx

https://enterprisedb.atlassian.net/browse/DOCS-1180

NET: compatibility page

---

product_docs/docs/pgd/5/conflict-management/conflicts/02_types_of_conflict.mdx

Missing closing ` on highlighted text and other minor typos.

PGD bug fix

---

product_docs/docs/epas/17/database_administration/index.mdx
product_docs/docs/epas/17/database_administration/roles.mdx
product_docs/docs/epas/17/reference/oracle_compatibility_reference/epas_compat_cat_views/index.mdx

Addresses [DOCS-1159](https://enterprisedb.atlassian.net/browse/DOCS-1159) and [DOCS-1158](https://enterprisedb.atlassian.net/browse/DOCS-1158)
[DOCS-1159]: https://enterprisedb.atlassian.net/browse/DOCS-1159?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DOCS-1158]: https://enterprisedb.atlassian.net/browse/DOCS-1158?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

EPAS - Adding predefined roles

---

advocacy_docs/edb-postgres-ai/migration-etl/data-migration-service/index.mdx

Fixing the closing end of an admonition that is being displayed incorrectly.

Admonition closure fix

---

advocacy_docs/security/advisories/cve202331043.mdx
advocacy_docs/security/advisories/cve202341113.mdx
advocacy_docs/security/advisories/cve202341114.mdx
advocacy_docs/security/advisories/cve202341115.mdx
advocacy_docs/security/advisories/cve202341116.mdx
advocacy_docs/security/advisories/cve202341117.mdx
advocacy_docs/security/advisories/cve202341118.mdx
advocacy_docs/security/advisories/cve202341119.mdx
advocacy_docs/security/advisories/cve202341120.mdx
advocacy_docs/security/advisories/index.mdx
advocacy_docs/security/assessments/cve-2024-0985.mdx
advocacy_docs/security/assessments/index.mdx
advocacy_docs/security/index.mdx

Removed links to EOL EPAS 11/12
Added updated notes

Removed 11/12 Epas

---

product_docs/docs/epas/13/epas_guide/14_edb_clone_schema.mdx
product_docs/docs/epas/14/epas_guide/14_edb_clone_schema.mdx
product_docs/docs/epas/15/database_administration/14_edb_clone_schema/cloning_with_a_non_super_user.mdx
product_docs/docs/epas/15/database_administration/14_edb_clone_schema/edb_clone_schema_overview.mdx
product_docs/docs/epas/15/database_administration/14_edb_clone_schema/setting_up_edb_clone_schema.mdx
product_docs/docs/epas/16/database_administration/14_edb_clone_schema/cloning_with_a_non_super_user.mdx
product_docs/docs/epas/16/database_administration/14_edb_clone_schema/edb_clone_schema_overview.mdx
product_docs/docs/epas/16/database_administration/14_edb_clone_schema/setting_up_edb_clone_schema.mdx
product_docs/docs/epas/17/database_administration/14_edb_clone_schema/cloning_with_non_super_user.mdx
product_docs/docs/epas/17/database_administration/14_edb_clone_schema/setting_up_edb_clone_schema.mdx

Made the edits to all the versions as has been done with EPAS historically.

Edits to EPAS 13 - update clone schema setup steps #6336

---

product_docs/docs/lasso/4/configuration.mdx
product_docs/docs/lasso/4/describe.mdx
product_docs/docs/lasso/4/install.mdx

Edits to Lasso release 4.18.0 PR6427

---

product_docs/docs/epas/17/database_administration/roles.mdx

Edits to EPAS - Adding predefined roles #6423

---

product_docs/docs/pem/9/profiling_workloads/installing_sql_profiler.mdx

Fixed SQL Profiler package name for EDB Postgres Extended

PEM - SQL Profiler package name correction

---

product_docs/docs/net_connector/8.0.5.1/18_api_reference.mdx

https://enterprisedb.atlassian.net/browse/DOCS-1177
Just a short note on Npgsql reference documentation in relation to .NET version.

NET: Npgsql API version note

---

product_docs/docs/net_connector/8.0.5.1/18_api_reference.mdx

Edits to NET: Npgsql API version note #6464

---

advocacy_docs/community/contributing/styleguide.mdx

While this has been house style for several years, it hadn't made it into the style guide.

Update to style regarding versions

---

advocacy_docs/edb-postgres-ai/ai-accelerator/pgfs/functions.mdx

grammar fix

---

product_docs/docs/postgres_for_kubernetes/1/index.mdx

Operator support Postgres 17 version

Support Postgres 17 version

---

product_docs/docs/postgis/3/01_release_notes/index.mdx
product_docs/docs/postgis/3/01_release_notes/rel_notes352.mdx

PostGIS - Feb Minor release

---

advocacy_docs/pg_extensions/pg_squeeze/rel_notes/index.mdx
advocacy_docs/pg_extensions/pg_squeeze/rel_notes/pg_squeeze_1.7.0_rel_notes.mdx
advocacy_docs/pg_extensions/pg_squeeze/rel_notes/pg_squeeze_1.8.0_rel_notes.mdx

https://enterprisedb.atlassian.net/browse/DOCS-1211

pg_squeeze: release notes for 1.7 and 1.8

---

product_docs/docs/epas/17/epas_rel_notes/index.mdx

EPAS: release notes navigation fix

---

product_docs/docs/eprs/7/05_smr_operation/04_on_demand_replication/02_perform_sync_replication.mdx

Update 02_perform_sync_replication.mdx for typo

---

scripts/pdf/cleanup_combined_markdown.mjs
scripts/pdf/generate_pdf.py
scripts/pdf/package-lock.json
scripts/pdf/package.json
scripts/pdf/pdf-styles.css

- Embed SVGs (will not render in wkhtmltopdf otherwise). Also reference other images directly instead of embedding.
- Discourage page breaks between code block and output block
- Get rid of stray padding on the first line of code blocks
- Get rid of excess whitespace after headings

PDF rendering misc bugs

---

advocacy_docs/security/advisories/index.mdx
advocacy_docs/security/assessments/cve-2025-1094.mdx
advocacy_docs/security/assessments/index.mdx
advocacy_docs/security/index.mdx
advocacy_docs/security/templates/advisoriesindex.njs
advocacy_docs/security/templates/assessmentsindex.njs
tools/automation/generators/advisoryindex/advisoryindex.js

Updated scripts for clearer release date order
Added alex700's CVE assesment.

Security - updated presentations and added CVE assessment

---

advocacy_docs/security/advisories/index.mdx
advocacy_docs/security/assessments/cve-2025-1094.mdx
advocacy_docs/security/assessments/index.mdx
advocacy_docs/security/index.mdx
advocacy_docs/security/templates/advisoriesindex.njs
advocacy_docs/security/templates/assessmentsindex.njs
product_docs/docs/epas/17/epas_rel_notes/index.mdx
product_docs/docs/eprs/7/05_smr_operation/04_on_demand_replication/02_perform_sync_replication.mdx
scripts/pdf/cleanup_combined_markdown.mjs
scripts/pdf/generate_pdf.py
scripts/pdf/package-lock.json
scripts/pdf/package.json
scripts/pdf/pdf-styles.css
tools/automation/generators/advisoryindex/advisoryindex.js

#6501 : Security - updated presentations and added CVE assessment
#6483 : PDF rendering misc bugs
#6494 : Update 02_perform_sync_replication.mdx for typo
#6493 : EPAS: release notes navigation fix

Release 2025/02/15a

---

advocacy_docs/supported-open-source/postgresql/installing/windows.mdx

Cleaned up the instruction a little and moved the background text out of the step so it's easier for the user to follow the step.

Edits to PostgreSQL - Locale update #6486

---

product_docs/docs/pem/9/certificates/index.mdx

Edits to PEM 9 - Added agent_ssl_passphrase_script parameter #6467

---

advocacy_docs/edb-postgres-ai/cloud-service/getting_started/your_cloud_account/preparing_cloud_account/preparing_azure/01_understanding_qotas_in_azure.mdx

Updated the network access from public to private and also updated BigAnimal references to Cloud Service

Cloud Service - Update Network access

---

product_docs/docs/pgd/5/rel_notes/src/relnote_5.7.0.yml

Edits to bdr release notes

---

product_docs/docs/pge/13/release_notes/index.mdx
product_docs/docs/pge/14/release_notes/index.mdx
product_docs/docs/pge/15/release_notes/index.mdx
product_docs/docs/pge/15/release_notes/rel_notes15.12.mdx
product_docs/docs/pge/16/release_notes/index.mdx
product_docs/docs/pge/16/release_notes/rel_notes16.8.mdx
product_docs/docs/pge/17/release_notes/index.mdx
product_docs/docs/pge/17/release_notes/rel_notes17.4.mdx

Added release notes with upstream merge details

PGE - Minor release

---

src/constants/updates.js

Updated Updates/WhatsNew Bar

---

product_docs/docs/eprs/7/supported_platforms.mdx

https://enterprisedb.atlassian.net/browse/DOCS-1215 
https://enterprisedb.atlassian.net/browse/XDB-2358

EPRS 7.11: supported JDK updates

---

product_docs/docs/pgd/5/cli/command_ref/cluster/show.mdx
product_docs/docs/pgd/5/cli/command_ref/cluster/verify.mdx
product_docs/docs/pgd/5/cli/command_ref/commit-scope/create.mdx
product_docs/docs/pgd/5/cli/command_ref/events/show.mdx
product_docs/docs/pgd/5/cli/command_ref/group/get-option.mdx
product_docs/docs/pgd/5/cli/command_ref/group/set-leader.mdx
product_docs/docs/pgd/5/cli/command_ref/group/set-option.mdx
product_docs/docs/pgd/5/cli/command_ref/group/show.mdx
product_docs/docs/pgd/5/cli/command_ref/groups/list.mdx
product_docs/docs/pgd/5/cli/command_ref/node/get-option.mdx
product_docs/docs/pgd/5/cli/command_ref/node/set-option.mdx
product_docs/docs/pgd/5/cli/command_ref/node/show.mdx
product_docs/docs/pgd/5/cli/command_ref/node/upgrade.mdx
product_docs/docs/pgd/5/cli/command_ref/nodes/list.mdx
product_docs/docs/pgd/5/cli/command_ref/raft/show.mdx
product_docs/docs/pgd/5/cli/command_ref/replication/show.mdx
product_docs/docs/pgd/5/cli/index.mdx
product_docs/docs/pgd/5/cli/using_cli.mdx

Some changes to the new cli commands and outputs needed updating.

Pgd 5.7 final edits

---

advocacy_docs/edb-postgres-ai/ai-accelerator/models/openai-api-compatibility.mdx
advocacy_docs/edb-postgres-ai/ai-accelerator/models/supported-models/completions.mdx
advocacy_docs/edb-postgres-ai/ai-accelerator/models/supported-models/embeddings.mdx
advocacy_docs/edb-postgres-ai/ai-accelerator/models/using-models.mdx
advocacy_docs/edb-postgres-ai/ai-accelerator/reference/models.mdx
advocacy_docs/edb-postgres-ai/ai-accelerator/rel_notes/ai-accelerator_2.1.2_rel_notes.mdx
advocacy_docs/edb-postgres-ai/ai-accelerator/rel_notes/index.mdx
advocacy_docs/edb-postgres-ai/ai-accelerator/rel_notes/src/rel_notes_2.1.2.yml

Adds new release notes for an upcoming AIDB 2.1.2 maintenance release
See https://github.com/EnterpriseDB/aidb/releases/tag/v2.1.2 and https://lantern.edb.dev/release/foundation/release-scheduling?pid_f=23537&r=426

DOCS-1214 - Updates for AIDB release 2.1.2

---

advocacy_docs/edb-postgres-ai/ai-accelerator/rel_notes/ai-accelerator_2.1.2_rel_notes.mdx
advocacy_docs/edb-postgres-ai/ai-accelerator/rel_notes/index.mdx
advocacy_docs/edb-postgres-ai/ai-accelerator/rel_notes/src/rel_notes_2.1.2.yml

Reverts EnterpriseDB/docs#6536
Wasn't approved.

Revert "Update rel_notes_2.1.2.yml"

---

advocacy_docs/edb-postgres-ai/cloud-service/references/distributed_high_availability/pgd_cli_ba.mdx
product_docs/docs/pgd/5/cli/command_ref/replication/index.mdx
product_docs/docs/tpa/23/reference/reconciling-local-changes.mdx

Fix for dha-cs-pgd-cli docs typo.

Fix quoting

---

product_docs/docs/pgd/5.6/index.mdx

Make link absolute as banner links are not fixed up for publication

Make link absolute as banner links are not fixed up for publication

---

product_docs/docs/pgd/5.6/index.mdx
product_docs/docs/pgd/5.7/rel_notes/pgd_5.7.0_rel_notes.mdx
product_docs/docs/pgd/5.7/rel_notes/src/relnote_5.7.0.yml

#6554 : Make link absolute as banner links are not fixed up for publication
#6555 : Docs 1229 update PGD 5.7.0 release notes

release 2025-02-27a

---

advocacy_docs/pg_extensions/pgrouting/configuring.mdx
advocacy_docs/pg_extensions/pgrouting/index.mdx
advocacy_docs/pg_extensions/pgrouting/installing.mdx
advocacy_docs/pg_extensions/pgrouting/using.mdx

Edits to Extensions docs 810 pgrouting #6513

---

product_docs/docs/migration_toolkit/55/07_invoking_mtk/08_mtk_command_options.mdx

Just added serial comma in a couple of spots.

Edits to MTK 55.11: -allDomains and -domains description updates #6510

---

product_docs/docs/tde/15/secure_key/passphrase.mdx

https://enterprisedb.atlassian.net/browse/DOCS-1216 
(Examples provided in https://enterprisedb.atlassian.net/browse/DB-2866)

TDE: passphrase on WINDOWS examples

---

advocacy_docs/pg_extensions/query_advisor/installing.mdx
advocacy_docs/pg_extensions/query_advisor/rel_notes/index.mdx
advocacy_docs/pg_extensions/query_advisor/rel_notes/query_advisor_1.2.0_rel_notes.mdx
advocacy_docs/pg_extensions/query_advisor/using.mdx

Added release notes and updated content as per [DOCs-1206](https://enterprisedb.atlassian.net/browse/DOCS-1206)

Query Advisor - 1.2.0 release

---

advocacy_docs/edb-postgres-ai/ai-accelerator/installing/complete.mdx
advocacy_docs/edb-postgres-ai/ai-accelerator/models/using-models.mdx

Updates over proxies and model first use

DOCS-1230 updates for aidb

---

product_docs/docs/pgd/5.6/backup.mdx
product_docs/docs/pgd/5.6/cli/index.mdx
product_docs/docs/pgd/5.6/decoding_worker.mdx

Fixed up redirects in PGD docs

Remove redirects in 5.6 branch that clash with 5.x(7) branch

---

advocacy_docs/pg_extensions/pg_failover_slots/rel_notes/index.mdx
advocacy_docs/pg_extensions/pg_failover_slots/rel_notes/pg_failover_slots_1.0.1_rel_notes.mdx

add rel notes 1.0.1

---

advocacy_docs/pg_extensions/wait_states/index.mdx

add index for sections

---

advocacy_docs/pg_extensions/ldap_sync/installing.mdx

add plpython3u note

---

product_docs/docs/postgres_distributed_for_kubernetes/1/known_issues.mdx

#6571 : PGD4K adhoc - Data Migration update

Production build 2 for 2025-02-28b

---

product_docs/docs/eprs/7/02_overview/02_replication_concepts_and_definitions/10_sync_replication_log_based/02_logical_replication_slots.mdx
product_docs/docs/eprs/7/10_appendix/02_resolving_problems/04_troubleshooting_areas.mdx

Edits to EPRS 7.11: logical replication slots for HA and failover #6504

---

advocacy_docs/edb-postgres-ai/ai-accelerator/pgfs/functions.mdx
advocacy_docs/edb-postgres-ai/ai-accelerator/pgfs/index.mdx
advocacy_docs/edb-postgres-ai/ai-accelerator/pgfs/sql/index.mdx
advocacy_docs/edb-postgres-ai/ai-accelerator/pgfs/sql/local.mdx
advocacy_docs/edb-postgres-ai/ai-accelerator/pgfs/sql/s3.mdx

Edits to PGFS section of Pipelines doc

---

advocacy_docs/edb-postgres-ai/ai-accelerator/gettingstarted/index.mdx
advocacy_docs/edb-postgres-ai/ai-accelerator/pgvector/index.mdx
advocacy_docs/edb-postgres-ai/ai-accelerator/reference/index.mdx
advocacy_docs/edb-postgres-ai/ai-accelerator/reference/models.mdx
advocacy_docs/edb-postgres-ai/ai-accelerator/reference/pgfs.mdx
advocacy_docs/edb-postgres-ai/ai-accelerator/reference/retrievers.mdx

Edits to rest of pipelines doc

---

product_docs/docs/pgd/5.7/upgrades/index.mdx
product_docs/docs/pgd/5.7/upgrades/inplace_upgrade.mdx
product_docs/docs/pgd/5.7/upgrades/manual_overview.mdx
product_docs/docs/pgd/5.7/upgrades/upgrading_major_rolling.mdx

Edits to Docs 769-b #6505

---

product_docs/docs/pem/9/monitoring_performance/notifications.mdx

Port some lost content from online help to the docs on SNMP

---

product_docs/docs/postgres_for_kubernetes/1/installation_upgrade.mdx

#6584 : [PG4k] Fix version number

Release 2025-03-05a

---

product_docs/docs/epas/13/epas_guide/14_edb_clone_schema.mdx
product_docs/docs/epas/14/epas_guide/14_edb_clone_schema.mdx
product_docs/docs/epas/15/database_administration/14_edb_clone_schema/edb_clone_schema_overview.mdx
product_docs/docs/epas/15/database_administration/14_edb_clone_schema/setting_up_edb_clone_schema.mdx
product_docs/docs/epas/16/database_administration/14_edb_clone_schema/cloning_with_a_non_super_user.mdx
product_docs/docs/epas/16/database_administration/14_edb_clone_schema/edb_clone_schema_overview.mdx
product_docs/docs/epas/16/database_administration/14_edb_clone_schema/setting_up_edb_clone_schema.mdx
product_docs/docs/epas/17/database_administration/14_edb_clone_schema/edb_clone_schema_overview.mdx
product_docs/docs/epas/17/database_administration/14_edb_clone_schema/setting_up_edb_clone_schema.mdx

EDB Clone schema updates required for a customer.

Release: 2025-03-05b

---

product_docs/docs/epas/13/upgrading/04_upgrading_an_installation_with_pg_upgrade/03_upgrading_to_advanced_server.mdx
product_docs/docs/epas/14/upgrading/04_upgrading_an_installation_with_pg_upgrade/03_upgrading_to_advanced_server.mdx
product_docs/docs/epas/15/upgrading/04_upgrading_an_installation_with_pg_upgrade/03_upgrading_to_advanced_server.mdx
product_docs/docs/epas/16/upgrading/major_upgrade/03_upgrading_to_advanced_server.mdx
product_docs/docs/epas/17/upgrading/major_upgrade/03_upgrading_to_advanced_server.mdx

Added a note to the upgrade section as per [DOCS-1123](https://enterprisedb.atlassian.net/browse/DOCS-1123)
[DOCS-1123]: https://enterprisedb.atlassian.net/browse/DOCS-1123?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

EPAS - Adding a note to upgrade

---

product_docs/docs/epas/17/reference/database_administrator_reference/01_audit_logging_configuration_parameters.mdx

Added JSON format to edb_audit parameter as per discussion on https://edb.slack.com/archives/CDTA6PCJV/p1741232419768419

EPAS - Added JSON format to edb_audit parameter

---

product_docs/docs/pgbouncer/1/pgbouncer_rel_notes/12400_rel_notes.mdx
product_docs/docs/pgbouncer/1/pgbouncer_rel_notes/index.mdx

Added pgbouncer 1.24.0.0 release notes
https://enterprisedb.atlassian.net/browse/DOCS-1266

pgbouncer - release notes

---

advocacy_docs/edb-postgres-ai/ai-accelerator/models/supported-models/nim_clip.mdx

Add closing curly brace in the create NIM model code sample

Update nim_clip.mdx adding closing curly brace

---

advocacy_docs/pg_extensions/edb_job_scheduler/configuring.mdx

Added GUC parameters as per [DOCS-1202](https://enterprisedb.atlassian.net/browse/DOCS-1202)
[DOCS-1202]: https://enterprisedb.atlassian.net/browse/DOCS-1202?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

edb_job_scheduler - Added GUC parameters

---

product_docs/docs/pem/9/monitoring_xdb_replication_cluster.mdx

Addresses: https://github.com/EnterpriseDB/docs/issues/6610

PEM - update xDB to EPRS

---

advocacy_docs/edb-postgres-ai/databases/advanced_sql.mdx

DBS: Minor fix for advanced SQL

---

advocacy_docs/edb-postgres-ai/ai-accelerator/models/primitives.mdx
src/constants/updates.js

#6632 : Update updates.js
#6629 : Update primitives.mdx

Release 2025-03-21a

---

advocacy_docs/pg_extensions/edb_job_scheduler/configuring.mdx

Edits to edb_job_scheduler - Added GUC parameters #6596

---

advocacy_docs/pg_extensions/pgaudit/index.mdx
advocacy_docs/pg_extensions/pgaudit/installing.mdx
advocacy_docs/pg_extensions/pgaudit/using.mdx

Mostly consistent tagging (or not) of pgaudit.

edits to add extension pgaudit #6232

---

advocacy_docs/pg_extensions/query_advisor/using.mdx

Edits to Query Advisor PR6540

---

advocacy_docs/pg_extensions/pgtt/configuring.mdx
advocacy_docs/pg_extensions/pgtt/index.mdx
advocacy_docs/pg_extensions/pgtt/installing.mdx
advocacy_docs/pg_extensions/pgtt/using.mdx

Mostly consistency of tagging extension name (no tagging needed)

Edits to pgtt PR 6563

---

product_docs/docs/postgres_distributed_for_kubernetes/1/image_catalog.mdx
product_docs/docs/postgres_distributed_for_kubernetes/1/index.mdx
product_docs/docs/postgres_distributed_for_kubernetes/1/known_issues.mdx
product_docs/docs/postgres_distributed_for_kubernetes/1/node_joins.mdx
product_docs/docs/postgres_distributed_for_kubernetes/1/openshift.mdx
product_docs/docs/postgres_distributed_for_kubernetes/1/rel_notes/1_1_1_rel_notes.mdx
product_docs/docs/postgres_distributed_for_kubernetes/1/samples.mdx

Please see a couple of queries

Edits to PGD4k PR6628

---

src/constants/updates.js

Updates.js typo fixo

---

advocacy_docs/edb-postgres-ai/ai-accelerator/capabilities.mdx
advocacy_docs/edb-postgres-ai/ai-accelerator/gettingstarted/index.mdx
advocacy_docs/edb-postgres-ai/ai-accelerator/limitations.mdx
advocacy_docs/edb-postgres-ai/ai-accelerator/models/index.mdx
advocacy_docs/edb-postgres-ai/ai-accelerator/models/supported-models/completions.mdx
advocacy_docs/edb-postgres-ai/ai-accelerator/models/using-models.mdx
advocacy_docs/edb-postgres-ai/ai-accelerator/models/using-with/index.mdx
advocacy_docs/edb-postgres-ai/ai-accelerator/models/using-with/openai-api-compatibility.mdx
advocacy_docs/edb-postgres-ai/ai-accelerator/models/using-with/using-nvidia-nim/index.mdx
advocacy_docs/edb-postgres-ai/ai-accelerator/models/using-with/using-nvidia-nim/using-nim-in-nvidia-cloud.mdx
advocacy_docs/edb-postgres-ai/ai-accelerator/models/using-with/using-nvidia-nim/using-nim-in-your-environment.mdx
advocacy_docs/edb-postgres-ai/ai-accelerator/overview.mdx
advocacy_docs/edb-postgres-ai/ai-accelerator/pipelines-overview.mdx
advocacy_docs/edb-postgres-ai/ai-accelerator/preparers/concepts.mdx
advocacy_docs/edb-postgres-ai/ai-accelerator/preparers/examples/chunk_text.mdx
advocacy_docs/edb-postgres-ai/ai-accelerator/preparers/examples/index.mdx
advocacy_docs/edb-postgres-ai/ai-accelerator/preparers/examples/parse_html.mdx
advocacy_docs/edb-postgres-ai/ai-accelerator/preparers/examples/parse_pdf.mdx
advocacy_docs/edb-postgres-ai/ai-accelerator/preparers/examples/summarize_text.mdx
advocacy_docs/edb-postgres-ai/ai-accelerator/preparers/index.mdx
advocacy_docs/edb-postgres-ai/ai-accelerator/preparers/primitives.mdx
advocacy_docs/edb-postgres-ai/ai-accelerator/preparers/usage.mdx
advocacy_docs/edb-postgres-ai/ai-accelerator/reference/index.mdx
advocacy_docs/edb-postgres-ai/ai-accelerator/reference/models.mdx
advocacy_docs/edb-postgres-ai/ai-accelerator/reference/preparers.mdx

Edits to DOCS-1265 PGAIDB 2.2.1 #6592

---

product_docs/docs/pgd/5.7/reference/nodes-management-interfaces.mdx

Note added to pgd's part_node reference.

Changes made to part_node

---

src/pages/index.js

Reordered grid for better topicality vs availability

Reordered and reshaped grid

---

advocacy_docs/edb-postgres-ai/overview/latest-release-news/2025q1release.mdx
advocacy_docs/edb-postgres-ai/overview/latest-release-news/images/2025q1-PEM10.png
advocacy_docs/edb-postgres-ai/overview/latest-release-news/images/2025q1-rubrik.png
src/pages/index.js

Docs 1362 create a q1 news section

---

advocacy_docs/pg_extensions/otel/configuring.mdx
advocacy_docs/pg_extensions/otel/index.mdx
advocacy_docs/pg_extensions/otel/installing.mdx
advocacy_docs/pg_extensions/otel/rel_notes/index.mdx
advocacy_docs/pg_extensions/otel/uninstalling.mdx
advocacy_docs/pg_extensions/otel/upgrading.mdx
advocacy_docs/pg_extensions/otel/using.mdx

Edits to otel extension initial draft #6614

---

advocacy_docs/pg_extensions/advanced_storage_pack/rel_notes/asp_1.3.0_rel_notes.mdx
advocacy_docs/pg_extensions/advanced_storage_pack/rel_notes/index.mdx
advocacy_docs/pg_extensions/advanced_storage_pack/rel_notes/src/meta.yml
advocacy_docs/pg_extensions/advanced_storage_pack/rel_notes/src/relnote_1.3.0.yml

New 1.3.0 notes 
Generated Release Notes YML installed

DOCS-1366 ASP 1.3.0 Notes and switched to generated release notes

---

product_docs/docs/pem/9/monitoring_xdb_replication_cluster.mdx

Fixed typo (where it was introducing product name, it seemed important)

Edit to PEM - update xDB to EPRS #6611

---

product_docs/docs/tde/15/secure_key/passphrase.mdx

Edits to TDE PR6551

---

advocacy_docs/edb-postgres-ai/ai-accelerator/installing/complete.mdx
advocacy_docs/edb-postgres-ai/ai-accelerator/models/using-models.mdx

Edits to ai accelerator pipelines pr6568

---

advocacy_docs/pg_extensions/pg_failover_slots/rel_notes/pg_failover_slots_1.0.1_rel_notes.mdx

Edits to pg_failover PR6565

---

product_docs/docs/pgd/5.7/reference/nodes-management-interfaces.mdx

Edits to Changes made to part_node #6654

---

product_docs/docs/pem/9/monitoring_performance/notifications.mdx

Fixed passive voice and changed "may" to "can" to improve clarity.

Edits to Port some lost content from online help to the docs on SNMP pr6573

---

product_docs/docs/efm/5/index.mdx

Hid the version as EFM is single version docs

Hiding version for EFM

---

advocacy_docs/pg_extensions/pg_tuner/index.mdx

add index cards

---

product_docs/docs/lasso/4/release-notes.mdx

Include the release notes for Lasso 4.19.0

Add Lasso 4.19.0 release notes

---

product_docs/docs/eprs/7/supported_platforms.mdx

Added ubuntu 24 to Java compact page: 
https://enterprisedb.atlassian.net/browse/XDB-2371

EPRS: add Ubuntu 24 compat

---

product_docs/docs/tpa/23/platform-aws.mdx

Fix typo ahead of next import

---

product_docs/docs/epas/14/epas_guide/14_edb_clone_schema.mdx
product_docs/docs/epas/15/database_administration/14_edb_clone_schema/checking_the_status.mdx
product_docs/docs/epas/15/database_administration/14_edb_clone_schema/cloning_with_a_non_super_user.mdx
product_docs/docs/epas/15/database_administration/14_edb_clone_schema/setting_up_edb_clone_schema.mdx
product_docs/docs/epas/16/database_administration/14_edb_clone_schema/checking_the_status.mdx
product_docs/docs/epas/16/database_administration/14_edb_clone_schema/cloning_with_a_non_super_user.mdx
product_docs/docs/epas/16/database_administration/14_edb_clone_schema/copying_a_remote_schema.mdx
product_docs/docs/epas/16/database_administration/14_edb_clone_schema/copying_a_schema.mdx
product_docs/docs/epas/16/database_administration/14_edb_clone_schema/edb_clone_schema_overview.mdx
product_docs/docs/epas/16/database_administration/14_edb_clone_schema/setting_up_edb_clone_schema.mdx
product_docs/docs/epas/17/database_administration/14_edb_clone_schema/checking_the_status.mdx
product_docs/docs/epas/17/database_administration/14_edb_clone_schema/edb_clone_schema_overview.mdx

https://enterprisedb.atlassian.net/browse/DI-1292
https://enterprisedb.atlassian.net/browse/DOCS-1387

CloneSchema: docs updates

---

product_docs/docs/postgres_for_kubernetes/1/openshift.mdx

Channels patch for going forward to 1.26.0

Update openshift.mdx with new channels text

---

product_docs/docs/postgres_for_kubernetes/1/preview_version.mdx

Update preview_version.mdx for 1.26rc1

---

advocacy_docs/edb-postgres-ai/ai-accelerator/compatibility.mdx

Add ARM support that will be landing in PGFS 2.0.1 (now that PGAA supports it)

Add ARM support for PGFS

---

product_docs/docs/postgres_for_kubernetes/1/preview_version.mdx

Update preview_version.mdx for rc2

---

advocacy_docs/edb-postgres-ai/ai-accelerator/compatibility.mdx
product_docs/docs/epas/17/upgrading/major_upgrade/how_pg_upgrade_works.mdx
product_docs/docs/postgres_for_kubernetes/1/preview_version.mdx

- https://github.com/EnterpriseDB/docs/pull/6691
- https://github.com/EnterpriseDB/docs/pull/6707
- https://github.com/EnterpriseDB/docs/pull/6709

Release: 2025-04-17a

---

product_docs/docs/epas/13/epas_compat_sql/16_alter_user_role_profile_management_clauses.mdx
product_docs/docs/epas/14/epas_compat_sql/16_alter_user_role_profile_management_clauses.mdx
product_docs/docs/epas/15/reference/oracle_compatibility_reference/epas_compat_sql/16_alter_user_role_profile_management_clauses.mdx
product_docs/docs/epas/16/reference/oracle_compatibility_reference/epas_compat_sql/16_alter_user_role_profile_management_clauses.mdx
product_docs/docs/epas/17/reference/oracle_compatibility_reference/epas_compat_sql/16_alter_user_role_profile_management_clauses.mdx
product_docs/docs/pem/10/debugger.mdx
product_docs/docs/pem/10/installing/windows/pem_server_and_httpd_on_diff_host.mdx

Also edited the PEM debugging content as it was never edited and needed to adhere to style guide.

EPAS - Update password set at timestamp clause details #6693

---

product_docs/docs/ocl_connector/17/04_open_client_library/03_compiling_and_linking_a_program.mdx

Edits to Adding Windows example to OCL compiling and linking #6678

---

advocacy_docs/pg_extensions/sqlprofiler/configuring.mdx
advocacy_docs/pg_extensions/sqlprofiler/index.mdx
advocacy_docs/pg_extensions/sqlprofiler/uninstalling.mdx
advocacy_docs/pg_extensions/sqlprofiler/using.mdx

Edits to sqlprofiler extension docs add #6556

---

product_docs/docs/pgd/5.7/cdc-failover.mdx

Edits to DOCS-1195 Failover slots #6480

---

advocacy_docs/edb-postgres-ai/cloud-service/support_services/index.mdx

Highlight support portal is the recommended option.
For best practices: 
Mentioned, the user can contact their own edb admin to manage the access.

Update Support Service.mdx

---

product_docs/docs/pgd/5.7/cdc-failover.mdx

Update cdc-failover.mdx fix quoted links

---

advocacy_docs/security/assessments/cve-2025-2291.mdx
advocacy_docs/security/assessments/index.mdx
advocacy_docs/security/index.mdx
product_docs/docs/pgbouncer/1/pgbouncer_rel_notes/12400_rel_notes.mdx
product_docs/docs/pgbouncer/1/pgbouncer_rel_notes/12410_rel_notes.mdx
product_docs/docs/pgbouncer/1/pgbouncer_rel_notes/index.mdx

Prepare for general release tomorrow

CVE-2025-2291 Assessment

---

advocacy_docs/community/contributing/styleguide.mdx
advocacy_docs/edb-postgres-ai/cloud-service/support_services/index.mdx
advocacy_docs/security/assessments/cve-2025-2291.mdx
advocacy_docs/security/assessments/index.mdx
advocacy_docs/security/index.mdx
product_docs/docs/efm/5/04_configuring_efm/01_cluster_properties.mdx
product_docs/docs/efm/5/04_configuring_efm/04_extending_efm_permissions.mdx
product_docs/docs/epas/17/installing/linux_install_details/updating_an_rpm_installation.mdx
product_docs/docs/pgbouncer/1/pgbouncer_rel_notes/12410_rel_notes.mdx
product_docs/docs/pgbouncer/1/pgbouncer_rel_notes/index.mdx
product_docs/docs/pgd/5.7/cdc-failover.mdx
product_docs/docs/pgd/5.7/reference/functions-internal.mdx
src/styles/_docs.scss

- #6733 
- #6719 
- #6723 
- #6738 
- #6731 
- #6736 
- #6729 
- #6724

Release: 2025-04-30a

---

advocacy_docs/community/contributing/styleguide.mdx
src/styles/_overrides.scss

For @sonotley , who likes consistent spacing.
(this is a work around for this Bootstrap issue: https://github.com/twbs/bootstrap/issues/32265)

Preserve nested list margins when combined with other paragraphs

---

product_docs/docs/pgd/4/upgrades/index.mdx
product_docs/docs/pgd/5.6/planning/limitations.mdx
product_docs/docs/pgd/5.6/upgrades/manual_overview.mdx
product_docs/docs/pgd/5.7/planning/limitations.mdx
product_docs/docs/pgd/5.7/upgrades/manual_overview.mdx

Language around mixed versions, explaining reason why mixed versions are a bad idea outside upgrade windows.
Applied to the 5.6 and 5.7 branches.

Changes with expanded language

---

product_docs/docs/eprs/7/10_appendix/02_resolving_problems/01_error_messages.mdx

https://enterprisedb.atlassian.net/browse/XDB-2367
https://enterprisedb.atlassian.net/browse/DOCS-1274

EPRS: 7.12 workaround for JA16SJIS enconding issue

---

product_docs/docs/pgd/6/reference/twophase.mdx

Smal change finishing out the big sweep previously.

DOCS-1426 remove obsolete GUCs

---

advocacy_docs/edb-postgres-ai/ai-accelerator/reference/index.mdx
advocacy_docs/edb-postgres-ai/ai-accelerator/reference/models.mdx

- Add HCP methods to AIDB documentation
- Clean up formatting of AIDB model docs

Add HCP model functions

---

product_docs/docs/pgd/6/reference/tables-views-functions/nodes-management-interfaces.mdx

Corrected text to sync with ticket

---

advocacy_docs/edb-postgres-ai/ai-accelerator/reference/index.mdx
advocacy_docs/edb-postgres-ai/ai-accelerator/reference/models.mdx
advocacy_docs/edb-postgres-ai/ai-accelerator/rel_notes/ai-accelerator_4.0.1_rel_notes.mdx
advocacy_docs/edb-postgres-ai/ai-accelerator/rel_notes/index.mdx
advocacy_docs/edb-postgres-ai/ai-accelerator/rel_notes/src/rel_notes_4.0.1.yml

Docs-1523 AIDB update for 4.0.1

---

product_docs/docs/pgd/6/reference/ddl/ddl-command-handling.mdx

Updated command handling

---

product_docs/docs/pgd/6/rel_notes/pgd_6.0.0_rel_notes.mdx
product_docs/docs/pgd/6/rel_notes/src/relnote_6.0.0.yml

Add BDR-5401

---

advocacy_docs/edb-postgres-ai/ai-accelerator/reference/index.mdx
advocacy_docs/edb-postgres-ai/ai-accelerator/reference/models.mdx
advocacy_docs/edb-postgres-ai/ai-accelerator/rel_notes/ai-accelerator_4.0.1_rel_notes.mdx
advocacy_docs/edb-postgres-ai/ai-accelerator/rel_notes/index.mdx
advocacy_docs/edb-postgres-ai/ai-accelerator/rel_notes/src/rel_notes_4.0.1.yml

#6764 : Docs-1523 AIDB update for 4.0.1

Release 2025-05-12a

---

product_docs/docs/pgd/6/reference/tables-views-functions/catalogs-visible.mdx
product_docs/docs/pgd/6/reference/tables-views-functions/index.json
product_docs/docs/pgd/6/reference/tables-views-functions/index.mdx
product_docs/docs/pgd/6/reference/tables-views-functions/nodes-management-interfaces.mdx
product_docs/docs/pgd/6/reference/tables-views-functions/nodes.mdx

Added content, rebuilt indexes.

DOCS-1541 pgd part node updates

---

product_docs/docs/migration_toolkit/55/mtk_rel_notes/mtk_55112_rel_notes.mdx

https://enterprisedb.atlassian.net/browse/MTK-1470

[MTK] 55.11.2 release notes 

---

product_docs/docs/migration_toolkit/55/09_mtk_errors.mdx
product_docs/docs/migration_toolkit/55/mtk_rel_notes/index.mdx
product_docs/docs/migration_toolkit/55/mtk_rel_notes/mtk_55112_rel_notes.mdx

Release: 2025-05-13a

---

product_docs/docs/eprs/7/08_xdb_cli/03_xdb_cli_commands/04_encrypt_password.mdx

https://enterprisedb.atlassian.net/browse/XDB-2390

EPRS 7.12: Added section for modifying encryption on existing EPRS

---

product_docs/docs/migration_toolkit/55/09_mtk_errors.mdx

Corrections for:
https://enterprisedb.atlassian.net/browse/MTK-1465

MTK 55.11.2 corrections

---

product_docs/docs/eprs/7/08_xdb_cli/03_xdb_cli_commands/04_encrypt_password.mdx
product_docs/docs/eprs/7/10_appendix/02_resolving_problems/01_error_messages.mdx
product_docs/docs/eprs/7/eprs_rel_notes/eprs_rel_notes_7.12.0.mdx
product_docs/docs/eprs/7/eprs_rel_notes/index.mdx
product_docs/docs/migration_toolkit/55/09_mtk_errors.mdx

#6752 : EPRS 7.12 branch
#6802 : MTK 55.11.2 corrections

Production release: 2025-05-14a

---

product_docs/docs/postgres_for_kubernetes/1/preview_version.mdx

- PG4K preview notes updated to reflect v1.26.0-rc3

Release: 2025-05-14b

---

product_docs/docs/pem/10/pem_rel_notes/index.mdx
product_docs/docs/pem/10/pem_rel_notes/pem_10.1.0_rel_notes.mdx
product_docs/docs/pem/10/pem_rel_notes/src/meta.yml
product_docs/docs/pem/10/pem_rel_notes/src/pem_10.1.0_rel_notes.yml

PEM 10.1 rel notes

---

advocacy_docs/pg_extensions/query_advisor/rel_notes/index.mdx
advocacy_docs/pg_extensions/query_advisor/rel_notes/query_advisor_1.2.1_rel_notes.mdx
advocacy_docs/pg_extensions/wait_states/rel_notes/index.mdx
advocacy_docs/pg_extensions/wait_states/rel_notes/wait_states_1.5.1_rel_notes.mdx

Added Query Advisor and Wait States release notes

Extensions - May release

---

install_template/templates/products/postgres-enterprise-manager-server/base.njk
product_docs/docs/epas/13/epas_guide/03_database_administration/02_index_advisor/index.mdx
product_docs/docs/epas/14/epas_guide/03_database_administration/02_index_advisor/index.mdx
product_docs/docs/epas/15/managing_performance/02_index_advisor/index_advisor_overview.mdx
product_docs/docs/pem/10/certificates/index.mdx

Edits to PEM 10 - first set

---

product_docs/docs/pgd/5.8/rel_notes/pgd_5.8.0_rel_notes.mdx
product_docs/docs/pgd/5.8/rel_notes/src/relnote_5.8.0.yml

Add two missing items found in the BDR source.
DOCS-1553.

PGD 5.8: update release notes

---

product_docs/docs/pem/10/installing/ha/efm_s1.mdx
product_docs/docs/pem/10/installing/ha/setup_ha_using_efm.mdx

Remove star from SQL statement that shouldn't have been there

---

product_docs/docs/pgd/6/reference/cli/command_ref/node/setup.mdx

User and roles text added (draft).
Tracking in BDR-6300

Node setup command fixups

---

product_docs/docs/pgd/6/reference/nodes/subscriber_only/overview.mdx
product_docs/docs/pgd/6/rel_notes/pgd_6.0.0_rel_notes.mdx
product_docs/docs/pgd/6/rel_notes/src/relnote_6.0.0.yml

DOCS-1554 - DDL for 6.0 on SO update

---

src/constants/products.js

Fix icons for defined products

---

product_docs/docs/pgd/3.7/index.mdx
product_docs/docs/pgd/4/index.mdx

Versioning fix

---

product_docs/docs/pem/10/pem_rel_notes/index.mdx
product_docs/docs/postgres_for_kubernetes/1/rel_notes/1_22_10_rel_notes.mdx
product_docs/docs/postgres_for_kubernetes/1/rel_notes/1_24_4_rel_notes.mdx
product_docs/docs/postgres_for_kubernetes/1/rel_notes/1_25_2_rel_notes.mdx
product_docs/docs/postgres_for_kubernetes/1/rel_notes/1_26_0_rel_notes.mdx
product_docs/docs/postgres_for_kubernetes/1/rel_notes/index.mdx
product_docs/docs/postgres_for_kubernetes/1/rel_notes/src/1.22.10_rel_notes.yml
product_docs/docs/postgres_for_kubernetes/1/rel_notes/src/1.24.4_rel_notes.yml
product_docs/docs/postgres_for_kubernetes/1/rel_notes/src/1.25.2_rel_notes.yml
product_docs/docs/postgres_for_kubernetes/1/rel_notes/src/1.26.0_rel_notes.yml
product_docs/docs/postgres_for_kubernetes/1/rel_notes/src/meta.yml
tools/automation/generators/relgen/meta-schema.json
tools/automation/generators/relgen/package-lock.json
tools/automation/generators/relgen/package.json
tools/automation/generators/relgen/relgen.js
tools/automation/generators/relgen/relnote-schema.json

...this requires some modifications to the tool:
- merging of release notes and precursor metadata
- sorting by semver
- frontmatter and outro options

Set up relgen for PG4K.

---

product_docs/docs/pem/10/considerations/pem_security_best_practices/apache_httpd_security_configuration.mdx
product_docs/docs/pem/10/index.mdx
scripts/pdf/cleanup_combined_markdown.mjs

PEM - Update link in apache_httpd_security_configuration.mdx

---

product_docs/docs/pem/10/considerations/ha_pem.mdx

Add a link from the high-level HA PEM Patterns page to the detailed instructions

Add a link from the high-level HA PEM Patterns 

---

product_docs/docs/pgd/6/rel_notes/pgd_6.0.1_rel_notes.mdx
product_docs/docs/pgd/6/rel_notes/src/relnote_6.0.1.yml

PGD: Release note was not correctly described. New description and link in place.

PGD: Fix for release notes

---

product_docs/docs/pgd/6/get-started/first-steps/loading-data.mdx

Only need one select... silly author

---

product_docs/docs/pgd/5.7/index.mdx
product_docs/docs/pgd/5.8/index.mdx

Removed categories from pgd 5.7 and 5.8

Fix multiple listing in High Availability

---

advocacy_docs/pg_extensions/otel/installing.mdx

modify Otel supported versions

add supported versions table

---

product_docs/docs/pgd/5.8/node_management/maintainance_with_proxies.mdx

Drafted up looser guidance to inform reader about scenarios and impacts. Removed the never.

BDR-6308-docs-relax-new-pgd-documentation-to-not-contain-w

---

advocacy_docs/repos/getting_started/with_cli/adding_edb_repositories.mdx
advocacy_docs/repos/getting_started/with_cli/index.mdx
advocacy_docs/repos/getting_started/with_web/get_your_token.mdx

Fix for issues re downloads/repositories

Attempt to clarify where repos/subscriptions come from

---

advocacy_docs/edb-postgres-ai/migration-etl/index.mdx

Migration Toolkit is a single tool, not a set of tools

Updated Migration Toolkit description

---

advocacy_docs/edb-postgres-ai/ai-factory/pipeline/installing/complete.mdx

Minor typo in code

---

advocacy_docs/edb-postgres-ai/hybrid-manager/using_hybrid_manager/migration/migration_guides/snippet_sources/100_agent_snippets/preparing_oracle_database.mdx

MIG-6348: update privilege description

---

product_docs/docs/pgd/4.4/rel_notes/pgd_4.4.0_rel_notes.mdx
product_docs/docs/pgd/4.4/rel_notes/src/relnote_4.4.0.yml

Add missing release note for pgd 4.4.0
