EnterpriseDB/docs

- package.json
- scripts/sync_repos.py
Run `yarn sync` to sync repos. Both repo folders must be in the same parent folder.
> Syncing for repos

- .github/ISSUE_TEMPLATE/problem-with-topic.md
- .github/ISSUE_TEMPLATE/propose-new-topic.md
Instead of putting these in contribute, include them in the GH UI. 
TODO: link to these *from* contribute
> basic issue templates for problems & requests

- src/advocacy_components/katacoda.js
- src/styles/_docs.scss
Katacoda does not, by default, play well with the React model - that leads to things like #77, where in-page navigation resets styles and event-handlers that Katacoda has applied to other elements on the page.
But with judicious application of Effect / LayoutEffect hooks, it's possible to mitigate this by ensuring that DOM modifications happen within React's lifecycle. Hence this PR:
- events are attached / detached and CSS classname applied / removed to `pre` elements matching the languages specified by the `codelanguages` property as the Katacoda panel is shown / hidden. This fixes #77. New CSS class, `katacoda-exec` is used to apply pointer styling; we may wish to use this to apply a more visible indication of interactivity in the future. cc @cero-miedo 
- New CSS class …
> Katacoda panel component cleanup: hooks, CSS styling, bug fixes

- .github/workflows/trigger-docs-deploy.yml
See title. Uses a GH workflow to send events to the docs repo when code gets merged into master
> Trigger docs deploys on pushes to master

- advocacy_docs/building/sql/views.mdx
- advocacy_docs/community/contribute/planning/demo.mdx
- advocacy_docs/community/contribute/style/index.mdx
- advocacy_docs/getting-started/connecting_to_postgres/java/01_hibernate.mdx
- advocacy_docs/getting-started/connecting_to_postgres/java/02_JDBC.mdx
- advocacy_docs/getting-started/connecting_to_postgres/java/03_springdata.mdx
- advocacy_docs/getting-started/connecting_to_postgres/python/02_django.mdx
- advocacy_docs/getting-started/installing_postgres/docker.mdx
- advocacy_docs/getting-started/installing_postgres/linux.mdx
Only doing a PR here to give me a place to make notes. Key changes:
- Document usage of `KatacodaPanel` and `KatacodaPageLink` + new Frontmatter list
- two places for this: briefly in contrib->style and more extensively in contrib->planning->demo
- Update all panel usage to `KatacodaPanel` component
- Update all embeds to `KatacodaPageLink`+Frontmatter list
- Remove all instances where the intro section for the embed was duplicated in the article (this only made sense when it wasn't a separate page)
- Remove all imports (both Katacoda components are default available now)
> update Katacoda usage and docs to match Evan's new components

- .devcontainer/Dockerfile
- .devcontainer/devcontainer.json
- README.md
- README_DOCKER_VSCODE.md
Along with some overdue updates to the dockerfile, and some other notes on prerequesites in the README. 
Could use a sanity-check on this - I've been using VSCode + containers pretty much exclusively for months, so good to know if these instructions make sense.
> Docs for using VSCode's remote containers plugin to run this repo

- README.md
- Remove `nvm`, instead manually install node 14 LTS
- Clear up python installation
- Recommend VS Code Docker for windows users
> README installation update

- src/components/pdf-download.js
`relativeDirectory` changed when we switch to individual product sourcing
> Fix PDF Download link component, path was being determined incorrectly

- gatsby-node.js
- src/templates/doc.js
- src/templates/gh-doc.js
- src/templates/katacoda-page.js
- src/templates/learn-doc.js
Use pagePath in context instead of path, which gatsby rehydrates client side. This solution works with js disabled
> Fix for pagePath missing without JS on

- .github/workflows/update-pdfs-on-develop.yml
Right now if someone pushes a commit to develop while the pdf update action is running, it won't be able to commit the new pdfs. This should 🤞 fix that!
> PDF Action Update - pull before commiting

- src/components/link.js
- make protocol relative urls use `<a>` tags
- force trailing backslash outside of `URL` to avoid browser specific issues
> <Link> improvements

- product_docs/docs/efm/4.1/efm_pgpool_ha_guide/03_components_ha_pgpool.mdx
- product_docs/docs/epas/13/epas_compat_spl/03_variable_declarations/index.mdx
- product_docs/docs/pem/8.0/pem_online_help/04_toc_pem_features/07_pem_postgres_expert/03_pe_configuration_expert_recommendations.mdx
- product_docs/docs/pem/8.0/pem_online_help/12_release_notes/04_pem_release_notes_7_14.mdx
@epbarger  noticed this; appears to be an artifact of how RSTs were converted - the syntax `word_` can indicate a link in RST, if there is an associated `_word` target for the link. Pandoc appears to have just... Converted them to links with no target.
> fix things that weren't really RST links

- src/components/layout.js
- src/templates/doc.js
Addresses #777 
- Add 'EDB Docs - ' prefix to titles using Layout
- add version to end of doc.js titles
Every page should have `EDB Docs - ` prefixes in front of the title, except for the index page. Versioned product docs will add the version at the end
*pgBackrest stub page*
*Epas 13*
> Smarter titles

- src/components/link.js
- Replace lookbehind regex in Link with simple string concat - Safari doesn't support lookbehind
> Fix Safari JS issues

- product_docs/docs/epas/13/epas_compat_tools_guide/02_edb_loader.mdx
- product_docs/docs/epas/13/epas_compat_tools_guide/03_edb_wrap.mdx
- product_docs/docs/jdbc_connector/42.2.12.3/09_security_and_encryption/01_using_ssl/01_configuring_the_server.mdx
- product_docs/docs/pem/8.0/pem_upgrade/01_upgrading_pem_installation/04_upgrading_pem_installation_linux_graphical.mdx
Some of these were manually converted in ways that lost the encapsulation, making them kinda incongruous
> Manually fix multiline notes that were lost

- product_docs/docs/epas/13/epas_compat_tools_guide/02_edb_loader.mdx
- product_docs/docs/epas/13/epas_guide/03_database_administration/01_configuration_parameters/03_configuration_parameters_by_functionality/01_top_performance_related_parameters/05_checkpoint_segments.mdx
- product_docs/docs/epas/13/epas_upgrade_guide/04_upgrading_an_installation_with_pg_upgrade/01_performing_an_upgrade/index.mdx
- product_docs/docs/epas/13/epas_upgrade_guide/04_upgrading_an_installation_with_pg_upgrade/03_upgrading_to_advanced_server.mdx
- product_docs/docs/epas/13/epas_upgrade_guide/07_migration.mdx
DF-212: Removed the 9.5 reference from v13 guides as 9.5 support ended in Jan 2021. Pls merge these changes, will verify it on staging
> DF-212 Removed 9.5 reference from v13 guides

- gatsby-node.js
- src/components/card-decks.js
- src/templates/learn-doc.js
There are two rendering modes for the "card deck" index generated for pages in the advo section: simple and full, with the latter being used ONLY when exactly 4 directories deep. Three if you count not rendering one at all if less than 4 levels deep in the directory hierarchy. This is... A pain to remember. 
Also, the card decks ignore the sort order used in the sidebar.
Both of these keep tripping me up, so this PR attempts to fix them both.
1. Add an optional `indexMode` key to frontmatter, with 3 possible values: "none", "simple", "full". If omitted, current "guess based on depth" behavior remains; if specified, then:
- none == no card deck
- simple == card deck without icons or children
- full == card deck with icons and children (if any)
2. Sort the things!
Combined, these provide a …
> Card deck enhancements: Frontmatter-configurable rendering, sort order

- advocacy_docs/supported-open-source/pgbackrest/index.mdx
- Removed italics around mentions of pgBackRest (we don't italicize product names anywhere else)
- switched from "Postgres" to "PostgreSQL"
- put the link to the .org in a Markdown admonition (!!! Note...), per the new standard
- removed language in the intro about pgBackRest being "as easy as could be" as this is for users and not marketing per se
> slight copy adjustments on the index

- src/components/card-decks.js
Eh, @cero-miedo mind weighing in on this? I'd just copied the existing breaks in #935 but... Didn't bother to check if they made sense. When I did, I noticed stuff like this:
That's at a 1024px window size (Chrome, Windows 10) - kiiinda sketchy. Even at 1278 (half my larger screen) 3 columns is pushing it for longer words like "Recommended", but at least most of the text is readable. 
This PR specifies a couple of breaks for both simple and full cards to try & keep 'em readable as long as possible.
> aim for saner breaks on card decks

- src/components/link.js
- src/components/version-dropdown.js
Fixes https://github.com/EnterpriseDB/docs/issues/940
Also fixes a bug where paths ending in a version number with a decimal (`/epas/9.6` for example) would be built as `a` instead of `Link`, because `.6` would be detected as a file extension
> Change VersionDropdown to use Link instead of bootstrap Dropdown.Item

- advocacy_docs/supported-open-source/barman/single-server-streaming/index.mdx
- advocacy_docs/supported-open-source/barman/single-server-streaming/step01-db-setup.mdx
- advocacy_docs/supported-open-source/barman/single-server-streaming/step02-backup-setup.mdx
- advocacy_docs/supported-open-source/barman/single-server-streaming/step03-backup.mdx
- advocacy_docs/supported-open-source/barman/single-server-streaming/step04-restore.mdx
- gatsby-node.js
- src/components/code-block.js
- src/components/katacoda-panel.js
- src/styles/_docs.scss
Revised #975 in response to feedback, this version breaks the steps up into 4 sections, and builds on docker compose environments running within Katacoda vs. Katacoda directly.
Lots of small changes, but of particular note:
- backup and pg are logically different machines
- reverted to using a superuser for barman access vs. replication user + assigned roles and permissions
- demonstrates remote restore
- overall hews a bit closer to the approaches demonstrated in the Barman manual
Future work:
- demonstrating partial WAL recovery (had this nearly working, but will need to rebuild the pg on a different base)
- link to git repo used to build images as an option for experimentation
- slim down images a bit somehow
Some potential issues:
- Even broken up, this is still pretty heavy, and may …
> Multi-page Barman tutorial (Single server, streaming)

- package.json
- product_docs/docs/pem/8.0.1/pem_online_help/03_toc_pem_client/01_pem_browser_window.mdx
- product_docs/docs/pem/8.0.1/pem_online_help/03_toc_pem_client/02_pem_toolbar.mdx
- product_docs/docs/pem/8.0.1/pem_online_help/03_toc_pem_client/03_pem_menu_bar.mdx
- product_docs/docs/pem/8.0/pem_online_help/03_toc_pem_client/01_pem_browser_window.mdx
- product_docs/docs/pem/8.0/pem_online_help/03_toc_pem_client/02_pem_toolbar.mdx
- product_docs/docs/pem/8.0/pem_online_help/03_toc_pem_client/03_pem_menu_bar.mdx
- scripts/pdf/generate_pdf.py
- Change `yarn build-all-pdfs` to fail as soon as a PDF fails to build (which should fail the github action)
- Fix some images paths in PEM 8.0 and 8.0.1 online help. The images were displaying in the browser (and still do), but pandoc wasn't happy about them when trying to generate the html for the pdf generator.
- Wrap titles with `"` instead of `'` so that title frontmatter without quotes (but possibly with a `'`) doesn't cause a problem when passing the title into system commands
- Add a bit more logging to the output of the generation script
> PDF generator fixes

- gatsby-config.js
- package.json
- src/constants/algolia-indexing.js
- yarn.lock
- Move algolia related functions into new `algolia-indexing` file to cleanup `gatsby-config` a bit
- Upgrade `gatsby-plugin-algolia` so that we can use the `skipIndexing` option and simplify the setup there
- Change the way the `noindex` header is being set - I think the previous method was busting the cache each time
> Cleanup gatsby-config, upgrade algolia

- src/components/code-block.js
- src/components/layout.js
Thanks to @gsong for helping figure out what was going on here!
The components passed into `MDXProvider` were changing somehow on link hover - memoizing the components object seems to fix the issue.
> Fix Katacoda closing on link hover in development

- gatsby-node.js
- package.json
- scripts/post-build.sh
- src/constants/gatsby-node-utils.js
also move post-build.sh into `onPostBuild` gatsby hook
> strip nginx legacy redirects from netlify _redirects

- advocacy_docs/supported-open-source/barman/index.mdx
- advocacy_docs/supported-open-source/barman/single-server-streaming/index.mdx
- advocacy_docs/supported-open-source/barman/single-server-streaming/step02-backup-setup.mdx
- advocacy_docs/supported-open-source/barman/single-server-streaming/step03-backup.mdx
- advocacy_docs/supported-open-source/barman/single-server-streaming/step04-restore.mdx
- advocacy_docs/supported-open-source/pgadmin/index.mdx
- advocacy_docs/supported-open-source/pgbackrest/02-installation.mdx
- advocacy_docs/supported-open-source/pgbackrest/03-quick_start.mdx
- advocacy_docs/supported-open-source/pgbackrest/04-recommended_settings.mdx
- advocacy_docs/supported-open-source/pgbackrest/05-retention_policy.mdx
- advocacy_docs/supported-open-source/pgbackrest/06-use_case_1.mdx
- advocacy_docs/supported-open-source/pgbackrest/07-use_case_2.mdx
- advocacy_docs/supported-open-source/pgbackrest/98-appendix.mdx
- advocacy_docs/supported-open-source/pgbackrest/99-faq.mdx
- advocacy_docs/supported-open-source/pgbackrest/index.mdx
- advocacy_docs/supported-open-source/postgresql/index.mdx
- advocacy_docs/supported-open-source/postgresql/installer/01_requirements_overview.mdx
- advocacy_docs/supported-open-source/postgresql/installer/02_installing_postgresql_with_the_graphical_installation_wizard/01_invoking_the_graphical_installer.mdx
- advocacy_docs/supported-open-source/postgresql/installer/02_installing_postgresql_with_the_graphical_installation_wizard/index.mdx
- advocacy_docs/supported-open-source/postgresql/installer/03_using_stackbuilder.mdx
- advocacy_docs/supported-open-source/postgresql/installer/04_installation_troubleshooting.mdx
- advocacy_docs/supported-open-source/postgresql/installer/05_uninstalling_postgresql.mdx
- advocacy_docs/supported-open-source/postgresql/installer/index.mdx
- gatsby-config.js
- gatsby-node.js
- src/constants/algolia-indexing.js
Changed the algolia indexing code to build up a content tree (the same way gatsby-node does) in order to compute the frontmatter for each doc. This lets us use `directoryDefaults` in the search indexing. I converted all of the docs in `supported-open-source` to use `directoryDefaults` for `product` and `platform` as a test. I also did a little more cleanup of the search indexing code, though I think there is a little more work to be done.
Going to test this more to ensure the indexing didn't change, but looking good so far.
**Content**
> directoryDefault aware algolia indexing

- scripts/pdf/pdf-styles.css
- Fixed coding font spec in Pandoc CSS. I assume we want to use the specified font of `Source Code Pro` for both `pre` and `code`, right?
> fix: adjust Pandoc CSS to use specified coding font

- .devcontainer/Dockerfile
- .devcontainer/devcontainer.json
- .devcontainer/library-scripts/docker-in-docker-debian.sh
Now that @gsong has demonstrated the use of containers to reduce tangential dependencies with #1047, I need my preferred environment to support this. Unfortunately, my preferred environment was already running everything in a container. 
This change adjusts the VSCode container definition to allow the use of Docker commands ("Docker in Docker"). Could have also gone with a lighter-weight [Docker-from-Docker](https://github.com/microsoft/vscode-dev-containers/blob/master/script-library/docs/docker.md) approach, but would've required special handling for VSCode's "Clone Repository in Container Volume" option, which is a handy option but not really worth special-casing; this should behave more or less the same to just running stuff locally.
> allow using docker from within docker-hosted dev env

- product_docs/docs/pem/8.0.1/pem_upgrade/02_upgrading_backend_database.mdx
- product_docs/docs/pem/8.0.1/pem_upgrade/03_moving_pem_server.mdx
- product_docs/docs/pem/8.0/pem_upgrade/02_upgrading_backend_database.mdx
- product_docs/docs/pem/8.0/pem_upgrade/03_moving_pem_server.mdx
Formatting for a note is fixed in PEM Upgrade guide
**Examples**
**Content**
> Formatting for a note is fixed in PEM Upgrade guide

- .github/workflows/deploy-develop.yml
- .github/workflows/deploy-main.yml
- gatsby-config.js
- gatsby-node.js
- add workaround to fix stale cache issue with page deletion
- re-enable gatsby cache for github builds
**Content**
> Re-enable cache on github builds

- package.json
- yarn.lock
This was used by scripts/normalize/lib/relativelinks.js to do product comparisons, but... Apparently I never actually added it as a dev dependency? 
Figures; I don't run these for a bit and they just rot.
**Content**
> link-rewrite uses semver-compare

- src/components/katacoda-panel.js
Finally figured this out with @matt-edb's help: Katacoda is supposed to delay load (that is, the script doesn't try to initialize until we've actually displayed the panel) - if it loads too early and the panel is hidden, then it sets up some constants wrong and never fully loads. 
This is supposed to be triggered by a `data-katacoda-ondemand` attribute on the panel wrapper div. But, sometimes the script would load before the panel was in place. 
This was frustrating because it wouldn't break *every* time - heavily dependent on script load time, when Gatsby decided to refresh the pre-rendered content, and how quickly you click the "Start Now" button after the page loads.
So, gonna cheat just slightly here & put the attribute on the script tag itself: should be then that if the script is …
> ensure that Katacoda won't try to load before the page content

- src/components/katacoda-panel.js
Reverts EnterpriseDB/docs#1090
Not sure why, but build is failing since this was merged. Seems unrelated, but ... !
> Revert "ensure that Katacoda won't try to load before the page content"

- product_docs/docs/pem/8.0/pem_inst_guide_linux/02_pem_hardware_software_requirements.mdx
Fix bug whereby admonition body wasn't indented, and thus interpreted as a "fenced" admonition with no closing, causing it to eat the rest of the page (including some frontmatter!)
Also use real headers instead of bold text, which would've avoided *some* of the issue if it'd been done originally.
Fixes #1089
**Content**
> Indent body of admonition

- src/components/katacoda-panel.js
Reverts EnterpriseDB/docs#1093
Wasn't causing the issue, so want this back!
> Revert "Revert "ensure that Katacoda won't try to load before the page content""

- src/components/advanced-search/filtering.js
- src/constants/gatsby-node-utils.js
- Sort versions correctly in AS filtering
- Replace `sortVersionArray` in `gatsby-node-utils` with a cleaner implementation
**Content**
> Sort versions correctly in Advanced Search filtering

- product_docs/docs/epas/13/epas_compat_table_partitioning/02_selecting_a_partition_type/index.mdx
Doc is updated with DB-733 i.e default_with_rowids not supported with partitioned table.
**Examples**
**Content**
- [x ] This PR adds new content
> DB-733 default_with_rowids not supported with partitioned table, reviewed by Suraj

- advocacy_docs/supported-open-source/barman/single-server-streaming/step01-db-setup.mdx
- advocacy_docs/supported-open-source/barman/single-server-streaming/step02-backup-setup.mdx
- advocacy_docs/supported-open-source/barman/single-server-streaming/step03-backup.mdx
- advocacy_docs/supported-open-source/barman/single-server-streaming/step04-restore.mdx
Critical areas for review:
- Step 1: installing barman-cli (pretty trivial)
- Step 3: triggering an update without a WAL rotation
- Step 4: doing a restore both *without* and then *with* WAL recovery to demonstrate the difference
- Addresses #1062
- Adds more links to documentation, sample output, and explanations for output that may seem incongruous
- Backed by copious stability updates to the underlying containers
**Content**
> Add partial WAL recovery to Barman demo

- product_docs/docs/epas/13/epas_inst_linux/03_using_a_package_manager_to_install_advanced_server.mdx
- product_docs/docs/epas/13/epas_inst_linux/05_managing_an_advanced_server_installation.mdx
Feature enhancement: Enabling Core Dumps for RHEL/CentOS and Debian/Ubuntu host documented.
**Content**
- [ x] This PR adds new content
> DB-1088 Enable core dumps, reviewed by Rohit

- advocacy_docs/kubernetes/cloud_native_postgresql/index.mdx
- advocacy_docs/kubernetes/cloud_native_postgresql/interactive_demo.mdx
- advocacy_docs/kubernetes/cloud_native_postgresql/quickstart.mdx
- src/components/tree-node.js
- src/pages/index.js
Per team discussion on April 14, moving CNP installation demo to be on the same hierarchical level as other content. Added back in the Demo badge for sidebar links.
**Content**
> Tweaks to CNP demo location

- scripts/normalize/lib/relativelinks.js
Some docs used URL-encoded link targets, some did not. Of course.
Assume they did, but handle the case where there are spurious % in the fragment without crashing.
> handle badly-encoded relative links / link-targets

- advocacy_docs/kubernetes/cloud_native_postgresql/api_reference.mdx
Move anchor links *above* titles; the ToC plugin does not care for HTML *in* titles. Arguably a bug in that plugin, since it really should know better - but... HTML *in* Markdown titles is a bit unusual, and parsing that properly is not a small thing.
Strictly-speaking, we don't need these anchor links at all *for this repo* - the ToC plugin generates its own (via remark-autolink-headers). But they're presumably useful for other targets, they might be useful for cross-linking, and it's nice to be consistent.
There's a fix for this in https://github.com/EnterpriseDB/cloud-native-postgresql/pull/298 - I should've verified the status of that first, since got bit by this for the 1.3.0 release as well.
**Content**
> Fix HTML in titles (hopefully for the last time)

- advocacy_docs/kubernetes/cloud_native_postgresql/monitoring.mdx
- scripts/source/source_cloud_native_operator.py
Conversion script was not handling markdown files where whitespace preceded the first heading. This is not a problem for Markdown, but MDX needs to lead with the frontmatter - no whitespace!
This case is handled now. However, there remains a possibility for a file that has *non-whitespace* preceding the first header; this can be handled with additional effort, but for now I've just added a warning to the script to call this out if it is detected.
A more robust approach would be needed anyway for #1224, so unless this potential problem shows up in the wild a fix can wait until that issue is processed.
**Content**
> Fix conversion error on md file with leading whitespace

- product_docs/docs/pem/8.0/pem_online_help/04_toc_pem_features/12_pem_manage_probes/01_pem_custom_probes.mdx
- product_docs/docs/pem/8.0/pem_online_help/04_toc_pem_features/12_pem_manage_probes/03_pem_probe_config/index.mdx
- product_docs/docs/pem/8.0/pem_online_help/04_toc_pem_features/12_pem_manage_probes/index.mdx
- product_docs/docs/pem/8.0/pem_online_help/05_toc_pem_management_basics/01_grant_wizard.mdx
- product_docs/docs/pem/8.0/pem_online_help/05_toc_pem_management_basics/03_import_export_data.mdx
- product_docs/docs/pem/8.0/pem_online_help/05_toc_pem_management_basics/04_maintenance/01_maintenance_dialog.mdx
- product_docs/docs/pem/8.0/pem_online_help/05_toc_pem_management_basics/04_maintenance/index.mdx
- product_docs/docs/pem/8.0/pem_online_help/05_toc_pem_management_basics/05_storage_manager.mdx
- product_docs/docs/pem/8.0/pem_online_help/05_toc_pem_management_basics/06_backup_dialog.mdx
- product_docs/docs/pem/8.0/pem_online_help/05_toc_pem_management_basics/07_backup_globals_dialog.mdx
- product_docs/docs/pem/8.0/pem_online_help/05_toc_pem_management_basics/08_backup_server_dialog.mdx
- product_docs/docs/pem/8.0/pem_online_help/05_toc_pem_management_basics/09_restore_dialog.mdx
- product_docs/docs/pem/8.0/pem_online_help/05_toc_pem_management_basics/10_managing_cluster_objects/index.mdx
- product_docs/docs/pem/8.0/pem_online_help/05_toc_pem_management_basics/11_managing_database_objects/02_collation_dialog.mdx
- product_docs/docs/pem/8.0/pem_online_help/05_toc_pem_management_basics/11_managing_database_objects/14_function_dialog.mdx
- product_docs/docs/pem/8.0/pem_online_help/05_toc_pem_management_basics/11_managing_database_objects/18_procedure_dialog.mdx
- product_docs/docs/pem/8.0/pem_online_help/05_toc_pem_management_basics/11_managing_database_objects/22_trigger_function_dialog.mdx
- product_docs/docs/pem/8.0/pem_online_help/05_toc_pem_management_basics/11_managing_database_objects/23_type_dialog.mdx
- product_docs/docs/pem/8.0/pem_online_help/05_toc_pem_management_basics/11_managing_database_objects/index.mdx
- product_docs/docs/pem/8.0/pem_online_help/05_toc_pem_management_basics/12_modifying_tables/index.mdx
- product_docs/docs/pem/8.0/pem_online_help/05_toc_pem_management_basics/index.mdx
Toctree and formatting issues fixed for the PEM Management Basics section of PEM 8.0 Online Help. Also, the review comments of the previous PR are fixed.
**Content**
> Toctree and formtting issues fixed for PEM Mangement Basics section

- advocacy_docs/supported-open-source/pgbackrest/08-multiple-repositories.mdx
The multi-repo feature was added with pgBackRest 2.33.
This new section demonstrate, using EPAS 13 on CentOS 7, the behavior of each command using multiple repositories.
**Content**
**Remark:** the development team has written a small [blog post](https://blog.crunchydata.com/blog/introducing-pgbackrest-multiple-repository-support) about this feature but this new content goes deeper than that.
> pgBackRest multi-repo feature

- product_docs/docs/epas/13/epas_compat_table_partitioning/04_partitioning_commands_compatible_with_oracle_databases/11_alter_table_set_subpartition_template/01_example_setting_a_subpartition_template.mdx
- Fixed the typo for (hash) in the subpartition template section.
**Content**
> Typo fixed for Subpartition tempate

- product_docs/docs/epas/12/epas_compat_tools_guide/02_edb_loader.mdx
- product_docs/docs/epas/13/epas_compat_tools_guide/02_edb_loader.mdx
The edb*loader version compatibility content moved under the NOTE section, as discussed with Dee Dee.
**Content**
> Formatting of the note for edb loader fixed in v12 and v13

- product_docs/docs/epas/12/epas_compat_sql/21_create_public_database_link.mdx
- product_docs/docs/epas/13/epas_compat_sql/21_create_public_database_link.mdx
DB-1115: Updated the doc and included the Oracle memory usage info with dblink_oci in SQL guide. 
**Content**
> DB-1115 Improve Oracle Memory usage with dblink_oci

- .github/workflows/deploy-draft.yml
- product_docs/docs/edbcloud/beta/index.mdx
- src/templates/doc.js
The current EDBCloud branch is taking a hybrid format: something between current product docs (e.g. EPAS) and open source docs (e.g. pgBackRest). That means we're probably going to have to adjust navigation to allow for this sort of format. Specifically:
- Hierarchical side-nav
- "Card"-style index pages
- ...possibly different directory structure that eschews versioning (see: https://docs.google.com/document/d/1-jKMMldDDKHAksdttrC-UK6Bo3ctiXUUVtkAla098Ak/edit)
This PR aims to do the simplest thing that could work for now: enable card decks on index pages for product docs, if indicated in frontmatter via `indexCards: simple`
I've also added a workflow that'll produce draft builds for a PR if the `deploy` label is added. This addresses …
> Allow advo-style card nav for products

- product_docs/docs/efm/4.1/efm_user/07_using_efm_utility.mdx
- product_docs/docs/efm/4.2/efm_user/07_using_efm_utility.mdx
Removed agent column from output of efm node-status-json command for EFM 4.1 and 4.2 versions.
**Content**
> Additional updates for EFM-1458

- src/styles/_admonitions.scss
A particular rule in the styling for admonitions removed the bottom margin of any child. This change alters that to only remove the bottom margin of the *last* child, thus allowing paragraphs within the admonition to render normally.
Before:
After:
> Allow paragraph margins within admonitions; only omit the ending margin

- product_docs/docs/epas/12/ecpgplus_guide/02_overview.mdx
- product_docs/docs/epas/12/ecpgplus_guide/07_reference.mdx
- product_docs/docs/epas/12/edb_plus/03_installing_edb_plus.mdx/02_rpm_installation.mdx
- product_docs/docs/epas/12/edb_plus/06_command_summary.mdx
- product_docs/docs/epas/12/epas_compat_bip_guide/03_built-in_packages/03_dbms_aqadm/07_purge_queue_table.mdx
- product_docs/docs/epas/13/ecpgplus_guide/02_overview.mdx
- product_docs/docs/epas/13/ecpgplus_guide/07_reference.mdx
- product_docs/docs/epas/13/edb_plus/06_command_summary.mdx
- product_docs/docs/epas/13/epas_compat_bip_guide/03_built-in_packages/03_dbms_aqadm/07_purge_queue_table.mdx
Found bugs while reviewing the v11 migration guides (ecpgplus and edb*plus guides), fixed:
- Missing tags & Syntax
**Content**
> Minor tweaks to EPAS guides

- product_docs/docs/epas/12/epas_compat_table_partitioning/04_partitioning_commands_compatible_with_oracle_databases/01_create_table_partition_by/index.mdx
- product_docs/docs/epas/12/epas_compat_table_partitioning/04_partitioning_commands_compatible_with_oracle_databases/02_alter_table_add_partition/index.mdx
- product_docs/docs/epas/12/epas_compat_table_partitioning/04_partitioning_commands_compatible_with_oracle_databases/05_alter_table_split_subpartition/02_example_splitting_a_range_subpartition.mdx
- product_docs/docs/epas/12/epas_compat_table_partitioning/04_partitioning_commands_compatible_with_oracle_databases/06_alter_table_exchange_partition/index.mdx
- product_docs/docs/epas/13/epas_compat_table_partitioning/04_partitioning_commands_compatible_with_oracle_databases/01_create_table_partition_by/index.mdx
- product_docs/docs/epas/13/epas_compat_table_partitioning/04_partitioning_commands_compatible_with_oracle_databases/02_alter_table_add_partition/index.mdx
- product_docs/docs/epas/13/epas_compat_table_partitioning/04_partitioning_commands_compatible_with_oracle_databases/05_alter_table_split_subpartition/02_example_splitting_a_range_subpartition.mdx
- product_docs/docs/epas/13/epas_compat_table_partitioning/04_partitioning_commands_compatible_with_oracle_databases/06_alter_table_exchange_partition/index.mdx
While reviewing the Table Partitioning Guide for v11 migration, found syntax related bugs. Fixed the same.
**Content**
> Table Partitioning Guides Fixes

- product_docs/docs/epas/12/epas_compat_ora_dev_guide/06_dblink_ora/02_calling_dblink_ora_functions.mdx
- product_docs/docs/epas/12/epas_compat_spl/02_spl_programs/07_subprograms_subprocedures_and_subfunctions/04_invoking_subprograms.mdx
- product_docs/docs/epas/12/epas_compat_spl/02_spl_programs/07_subprograms_subprocedures_and_subfunctions/07_accessing_subprogram_variables.mdx
- product_docs/docs/epas/12/epas_compat_spl/03_variable_declarations/02_using__type_in_variable_declarations.mdx
- product_docs/docs/epas/12/epas_compat_spl/03_variable_declarations/03_using__row_type_in_record_declarations.mdx
- product_docs/docs/epas/12/epas_compat_spl/08_static_cursors/07_cursor_for_loop.mdx
- product_docs/docs/epas/12/epas_compat_spl/10_collections/01_associative_arrays.mdx
- product_docs/docs/epas/12/epas_compat_spl/10_collections/02_nested_tables.mdx
- product_docs/docs/epas/12/epas_compat_spl/10_collections/03_varrays.mdx
- product_docs/docs/epas/12/epas_compat_spl/13_triggers/03_creating_triggers.mdx
- product_docs/docs/epas/12/epas_compat_spl/15_object_types_and_objects/02_object_type_components/02_object_type_body_syntax.mdx
- product_docs/docs/epas/12/epas_compat_spl/15_object_types_and_objects/04_creating_object_instances.mdx
- product_docs/docs/epas/12/epas_compat_spl/15_object_types_and_objects/05_referencing_an_object.mdx
- product_docs/docs/epas/13/epas_compat_ora_dev_guide/06_dblink_ora/02_calling_dblink_ora_functions.mdx
- product_docs/docs/epas/13/epas_compat_spl/02_spl_programs/07_subprograms_subprocedures_and_subfunctions/04_invoking_subprograms.mdx
- product_docs/docs/epas/13/epas_compat_spl/02_spl_programs/07_subprograms_subprocedures_and_subfunctions/07_accessing_subprogram_variables.mdx
- product_docs/docs/epas/13/epas_compat_spl/03_variable_declarations/02_using__type_in_variable_declarations.mdx
- product_docs/docs/epas/13/epas_compat_spl/03_variable_declarations/03_using__row_type_in_record_declarations.mdx
- product_docs/docs/epas/13/epas_compat_spl/08_static_cursors/07_cursor_for_loop.mdx
- product_docs/docs/epas/13/epas_compat_spl/10_collections/01_associative_arrays.mdx
- product_docs/docs/epas/13/epas_compat_spl/10_collections/02_nested_tables.mdx
- product_docs/docs/epas/13/epas_compat_spl/10_collections/03_varrays.mdx
- product_docs/docs/epas/13/epas_compat_spl/13_triggers/03_creating_triggers.mdx
- product_docs/docs/epas/13/epas_compat_spl/15_object_types_and_objects/02_object_type_components/02_object_type_body_syntax.mdx
- product_docs/docs/epas/13/epas_compat_spl/15_object_types_and_objects/04_creating_object_instances.mdx
- product_docs/docs/epas/13/epas_compat_spl/15_object_types_and_objects/05_referencing_an_object.mdx
During reviewing the SPL guide for v11 migration, came across syntax-related bugs. Fixed the same.
**Content**
> SPL Guide syntax fixes

- README.md
Suggested changes to #1542.
@drothery-edb I've made these markdown formatting changes:
1. In general, avoid using the trailing double space trick if possible. If you're in a bulleted block, just use blank line and indentation to keep everything as a block.
2. Prefer code fence blocks.
> style: better MD formatting

- src/components/archive.js
Apparently `GATSBY_ENVIRONMENT_BRANCH` is undefined (at least in local and staging builds). Re-use the APP_ENV approach already used elsewhere to determine which archive branch to link to.
**Content**
> Fix "undefined" in archive paths

- src/components/layout.js
We'd originally planned this for the inaugural release, but wanted to wait so as to gauge the effect in isolation (refs: #163, #166). 
...5 months is probably long enough.
Tl;dr: this tries to ensure that search engines see only ONE version of each topic, with each distinct version considered just a trivial variation. Vs. the status quo, which has them trying to index and distinguish between myriad versions, generally ranking out-of-date versions above current and penalizing us for duplicating content along the way.
Full details on this can be found in https://github.com/EnterpriseDB/docs-products/issues/139 - copying the relevant portions here:
> The purpose is to tell the search indexer that a given page corresponds to a given URL *even if it isn't being accessed via that URL*.
> 
> So …
> re-enable rel:canonical header

- product_docs/docs/efm/4.2/efm_pgpool_ha_guide/03_efm_vip.mdx
- product_docs/docs/efm/4.2/efm_pgpool_ha_guide/04_efm_client_connect_failover.mdx
- product_docs/docs/efm/4.2/efm_pgpool_ha_guide/05_efm_pgbouncer.mdx
- product_docs/docs/efm/4.2/efm_pgpool_ha_guide/06_efm_pgpool.mdx
PDF builds were failing due to bad image paths in the latest EFM content. In some cases, these also appeared to be pointing to the wrong images. I've corrected both.
Related: #1578
**Content**
> fix image paths (and names in some cases)

- product_docs/docs/epas/12/epas_guide/10_edb_resource_manager.mdx
- product_docs/docs/epas/13/epas_guide/10_edb_resource_manager.mdx
Fixed some examples of using `!` instead of `factorial()`. I used:
```
find product_docs/ -name \*.mdx | xargs grep '[0-9]!'
```
to find them. Note that two more files (`product_docs/docs/epas/1[23]/epas_compat_spl/02_spl_programs/07_subprogra
ms_subprocedures_and_subfunctions/02_creating_a_subfunction.mdx`) have that pattern, but they are merely printing out the results of `factorial()` in a human-readable way. So those are safe.
**Content**
> Fix for #1602

- static/_redirects
There was briefly a PEM 8.0 release - just long enough to pick up a bad redirect. Handle it sanely.
This fixes #1639
> Add PEM 8.0 redirect

- gatsby-node.js
1. Avoid pointing folks to an editor on the `main` branch: this will not have the most recent changes (if changes are pending a production build), and will tend to encourage PRs against main (which should be avoided except in emergency / hotfix situations). 
2. Reliably detect the current branch name, both for local builds and builds made against PRs via Github Actions. Use this for edit links except when on production (as noted above). Don't shell out for this info unless necessary (non-GHA builds).
3. Use the same branch name / head sha for the /docs/build-info page (which I had forgotten existed until just now, but which should probably be consistent here!)
> Reliably detect branch name & use 'develop' for edit links on production

- product_docs/docs/edbcloud/beta/overview/index.mdx
moved  "with Oracle compatibility" to normal text outside of the link label in the Overview of Service index page
> updated link label

- gatsby-node.js
- product_docs/docs/edbcloud/beta/index.mdx
- src/components/left-nav.js
- src/constants/gatsby-utils.js
- src/templates/doc.js
* Added 2 new keys to the frontmatter of the MDX pages: `hideVersion` and `showBanner`.
* `hideVersion` is expected to be `true` or `false`.
* `showBanner` accepts a `string` ('edbcloud' for this case). The idea is that in the future, we can show banners with different content if needed.
* The 2 new keys are available in the `navTree` so that we only need to define their value on the top-level page.
> Hide product version and show banner for EDB Cloud pages

- product_docs/docs/epas/11/epas_guide/10_edb_resource_manager.mdx
- product_docs/docs/epas/12/epas_guide/10_edb_resource_manager.mdx
- product_docs/docs/epas/13/epas_guide/10_edb_resource_manager.mdx
Added this sentence to EDB Resource Manager topic in epas guide v11, 12, 13
On multicore systems, you can apply the `cpu_rate_limit` to more than one CPU core by setting it to greater than 1. For example, if `cpu_rate_limit` is set to 2.0, you use 100% of two CPUs.
> Incorporated feedback from PR#1733

- src/templates/doc.js
Added card deck functionality for EDBCloud in 8f45da165b8a31c5032f19c5bdbfcc06cc4b5c98 - but left the path-based behavior. That's undesirable for the product template, as it has its own style of index nav (for MOST products). Remove that default - getting this style requires explicit request via `indexCards` frontmatter key.
**Content**
> Remove path-based defaults for card deck nav style

- src/components/link.js
Address an issue that cropped up in the CNP import: URLs that point to .md files along with a fragment (e.g., that point to a header).
**Content**
> Handle URLs to .md or .mdx with fragment or query

- gatsby-node.js
This builds on #1721 by making the new frontmatter options optional: with types defined, Gatsby won't try to infer types and will therefore be content if the options are not used anywhere in the codebase. 
My immediate need for this involves being weary of Heroku builds failing, but I do foresee a time when the banner won't be needed anywhere and thus removing it entirely might be useful.
**Content**
> Give new frontmatter options a type so that they can be completely optional

- product_docs/docs/eprs/6.2/02_overview/04_design_replication_system/03_restrictions_on_replicated_database_objects.mdx
Updated the Replication Serve User's guide v6.2 to include the restrictions on the PG database objects.
**Content**
> Updated the restrictions on data types

- product_docs/docs/epas/11/epas_compat_sql/36_create_table.mdx
- product_docs/docs/epas/12/epas_compat_sql/36_create_table.mdx
- product_docs/docs/epas/13/epas_compat_sql/36_create_table.mdx
DF-263 Added UNLOGGED parameter to CREATE TABLE syntax
**Content**
> DF-263 UNLOGGED Parameter added

- README.md
- docs/how-tos/avoid-breaking-links.md
- gatsby-node.js
- product_docs/docs/epas/13/edb_plus/03_installing_edb_plus.mdx
- src/constants/gatsby-utils.js
- static/_redirects
This started as a quick fix for a few files that were consolidated in the EPAS 13 docs, and turned into a tweak to Frontmatter redirect functionality, a review of existing Netlify redirects, and an expansion of the guidance available for using redirects.
When you get a chance,
- @jericson would you mind reviewing the changes / additions to README.md, docs/how-tos/avoid-breaking-links.md, and _redirects for accuracy and narrative flow?
- @drothery-edb and @nidhibhammar could you review the same for applicability to your work and unanswered questions?
- @frago12 would you mind doing a quick sanity-check of my changes to gatsby-node.js and gatsby-util.js?
> Clean up Netlify redirects, write guidance for usage

- product_docs/docs/migration_toolkit/54/mtk_rel_notes/08_mkt_5401_rel_notes.mdx
- product_docs/docs/migration_toolkit/54/mtk_rel_notes/09_mkt_54_rel_notes.mdx
- product_docs/docs/migration_toolkit/54/mtk_rel_notes/index.mdx
- product_docs/docs/migration_toolkit/55/mtk_rel_notes/08_mkt_551_rel_notes.mdx
- product_docs/docs/migration_toolkit/55/mtk_rel_notes/09_mkt_55_rel_notes.mdx
- product_docs/docs/migration_toolkit/55/mtk_rel_notes/index.mdx
- static/_redirects
- Add redirects from old versioning scheme (xx.x.x -> xx) in _redirects
- Add specific redirects for release notes
- Correct several references to v55 in the v54 docs
**Content**
> Redirects & version corrections for Migration Toolkit 

- src/constants/gatsby-utils.js
In #1852 I added support for stable redirects to the latest version and relative redirects, both as a belt-and-suspenders approach to avoiding broken redirects as versions are forked and superseded. However... Both of these provide a path to inadvertently creating infinite redirects via a page that redirects to itself. 
We shouldn't allow that. Even explicitly. While preventing redirect loops (page redirects to redirect to itself via some out-of-band method) is somewhat more complex, avoiding the obvious mistake of creating an explicit redirect to the URL being requested is trivial - this PR adds a check for that. 
I observed this behavior in https://www.enterprisedb.com/docs/migration_portal/latest/ - it works via navigation from the main page (handled by Gatsby's router) but redirects …
> Avoid inadvertently redirecting page to itself

- product_docs/docs/pglogical/3.7/subscriptions/index.mdx
- product_docs/docs/pglogical/3.7/subscriptions/pglogical-writer.mdx
- scripts/source/pglogical.js
I had to make some modifications to paths for pages where the original structure applied a navigation heirarchy in the sidebar but not in the path structure; intended to have redirects to avoid breaking links, but got relative links wrong - probably a sign that my relative redirects logic is... confusing. Not a great sign!
Regardless, that left a link broken for pglogical; this fixes that.
**Content**
> Fix auto-gen redirects for pglogical to allow existing links to work

- product_docs/docs/edbcloud/beta/administering_cluster/01_portal_access.mdx
- product_docs/docs/edbcloud/beta/administering_cluster/03_account_activity.mdx
This PR changes 
- the EDB Cloud product documentation to use the correct term mentioned from https://enterprisedb.atlassian.net/browse/UPM-1752 which is defined by the offering manager to 
- use "cluster" to replace the original "database" term to stand for one customer's EDB Cloud PG cluster. 
The corresponding changes of the product will be released today. 
**Content**
> update EDB cloud administration permission names from database to cluster

- src/pages/index.js
Updated location of LiveCompare link on the home page per https://github.com/EnterpriseDB/docs/issues/1923
> updated location of home page link

- gatsby-config.js
This arose via an observation from Christina Wong in [EW-7470](https://enterprisedb.atlassian.net/browse/EW-7470): 
> 
The URL linked is https://www.enterprisedb.com/docs/static/4cb04e2e1f87ba158b607373b3476147/edbcloud_vbeta_documentation.pdf
([Try this search](https://www.google.com/search?q=edb+cloud+preview) in "incognito" mode - link was still listed at the time I wrote this PR)
The hash in that path is going to change every time the PDF changes; that's fairly often, so even if Google re-indexes pretty quickly there's a good chance we'll be seeing broken links.
And... There's no content in that PDF that isn't in the Docs pages themselves. So to avoid issues, I'd like to noindex them.
**Content**
> noindex generated PDFs

- gatsby-config.js
- src/components/index-sub-nav.js
- src/components/side-navigation.js
Use www.enterprisedb.com for docs links. Not sure off-hand if this was always wrong or if there's some recent change here, but... Ton of unnecessary 301 redirects and inaccurate rel=canonical URLs due to Gatsby writing out www-less URLs.
**Content**
> Use www. prefix to minimize 301 redirects

- scripts/fileProcessor/processors/cnp/update-yaml-links.mjs
My last change to this file made it asynchronous; that worked fine locally, but appears to hit a race condition when triggered from a workflow on GH. Side-step the issue for now by just processing these synchronously.
> Use synchronous processing to avoid race condition with rename plugin

- product_docs/docs/biganimal/release/getting_started/01_check_resource_limits.mdx
updated quota requirements per Ben
> UPM-3179-quota-req-changes

- advocacy_docs/kubernetes/cloud_native_postgresql/api_reference.mdx
- advocacy_docs/kubernetes/cloud_native_postgresql/architecture.mdx
- advocacy_docs/kubernetes/cloud_native_postgresql/backup_recovery.mdx
- advocacy_docs/kubernetes/cloud_native_postgresql/bootstrap.mdx
- advocacy_docs/kubernetes/cloud_native_postgresql/cnp-plugin.mdx
- advocacy_docs/kubernetes/cloud_native_postgresql/connection_pooling.mdx
- advocacy_docs/kubernetes/cloud_native_postgresql/credits.mdx
- advocacy_docs/kubernetes/cloud_native_postgresql/images/pgbouncer-architecture-rw.png
- advocacy_docs/kubernetes/cloud_native_postgresql/index.mdx
- advocacy_docs/kubernetes/cloud_native_postgresql/installation_upgrade.mdx
- advocacy_docs/kubernetes/cloud_native_postgresql/logging.mdx
- advocacy_docs/kubernetes/cloud_native_postgresql/monitoring.mdx
- advocacy_docs/kubernetes/cloud_native_postgresql/operator_capability_levels.mdx
- advocacy_docs/kubernetes/cloud_native_postgresql/operator_conf.mdx
- advocacy_docs/kubernetes/cloud_native_postgresql/postgresql_conf.mdx
- advocacy_docs/kubernetes/cloud_native_postgresql/release_notes.mdx
- advocacy_docs/kubernetes/cloud_native_postgresql/rolling_update.mdx
- advocacy_docs/kubernetes/cloud_native_postgresql/samples/cluster-backup-retention-30d.yaml
- advocacy_docs/kubernetes/cloud_native_postgresql/samples/cluster-example-full.yaml
- advocacy_docs/kubernetes/cloud_native_postgresql/samples/cluster-example-initdb.yaml
- advocacy_docs/kubernetes/cloud_native_postgresql/samples/cluster-example-monitoring.yaml
- advocacy_docs/kubernetes/cloud_native_postgresql/samples/cnp-basic-monitoring.yaml
- advocacy_docs/kubernetes/cloud_native_postgresql/samples/pooler-basic-auth.yaml
- advocacy_docs/kubernetes/cloud_native_postgresql/samples/pooler-tls.yaml
- advocacy_docs/kubernetes/cloud_native_postgresql/scheduling.mdx
- advocacy_docs/kubernetes/cloud_native_postgresql/security.mdx
- advocacy_docs/kubernetes/cloud_native_postgresql/ssl_connections.mdx
- advocacy_docs/kubernetes/cloud_native_postgresql/troubleshooting.mdx
- product_docs/docs/biganimal/release/getting_started/01_check_resource_limits.mdx
- scripts/fileProcessor/package-lock.json
> Release: 2021-11-11

- product_docs/docs/biganimal/release/getting_started/creating_a_cluster/01_cluster_networking.mdx
Fixes typo on BigAnimal Cluster networking architecture page
> addressing typo

- advocacy_docs/kubernetes/cloud_native_postgresql/interactive_demo.mdx
- merge_sources/kubernetes/cloud_native_postgresql/interactive_demo.mdx
- Switch to k3d for updated Kubernetes version
- Update output to match CNP 1.10
**Content**
> CNP demo: update kubernetes & cnp

- product_docs/docs/efm/4/efm_user/05_using_efm.mdx
The virtual.ip.interface property shouldn't be in the list of props that have to be unique if using more than one agent on a node. Something similar used to be a requirement, which is probably how this got here. Will take a look at the v3 docs also.
**Content**
> virtual.ip.interface not a unique propertie

- product_docs/docs/efm/3/efm_user/05_using_efm.mdx
This can be removed from the list of unique properties. In older versions of EFM a sub-interface was required and this had to be unique. We got rid of the subinterface but not the documentation that went with it. Have filed a PR already for the v4 version of this page.
**Content**
> virtual.ip.interface not a unique property

- product_docs/docs/bart/2.6/bart_inst/index.mdx
- product_docs/docs/slony/2.2.10/01_installation/index.mdx
- src/pages/index.js
Changed order of short and long names for Replication Server on the home page
Added notes about epas v14 not supporting Slony or BART
> updated shortname reference on home page and v14 support notes

- gatsby-config.js
Several of the BDR ecosystem products have consistently used `postgresql` as a language tag for code blocks. We may wish to standardize on `sql` for these, but for now it'd be nice if they highlighted properly - so add `postgresql` as an alias for `sql`. This may even be desirable for sematic reasons, though I kind of doubt it.
**Content**
> syntax highlight "postgresql" code blocks using sql rules (BDR family)

- product_docs/docs/biganimal/release/getting_started/creating_a_cluster/01_cluster_networking.mdx
Broken link due to addition of numeric prefix in c36b699eba62eb01b95b6565b4152f74d3d47b1f - there was a redirect added to try to avoid this, but it didn't take because directory renames must use a parent path prefix (../) when intending to redirect index.mdx
**Content**
> Fix link to "connecting..."

- .github/workflows/deploy-develop.yml
- .github/workflows/deploy-draft.yml
- .github/workflows/sync-and-process-files.yml
...since netlify-cli is now suddenly failing to install on the runner (see: [1](https://github.com/EnterpriseDB/docs/runs/4537965585?check_suite_focus=true), [2](https://github.com/EnterpriseDB/docs/runs/4540134421?check_suite_focus=true))
Been using this action for draft deploys for a while now, seems stable. Also added caching for npm and the option to kill concurrent staging builds, since why not speed this up a bit.
**Content**
> Use netlify deploy action instead of netlify-cli

- product_docs/docs/efm/4/efm_user/13_troubleshooting.mdx
Unencoded <...> is interpreted as a JSX tag by MDX - since we want this message to render verbatim, I avoid the error by encoding these characters as HTML entities.
**Content**
> Encode <> to avoid breaking MDX compilation

- product_docs/docs/efm/4/efm_user/04_configuring_efm/01_cluster_properties/index.mdx
Added information that timeouts do not apply to this case when the agent exits and that it's treated like agent failures.
**Content**
> Update primary.shutdown.as.failure information

- product_docs/docs/eprs/6.2/eprs_rel_notes/13_eprs_rel_notes_6.2.16.mdx
Added missing support ticket ID. Addresses https://github.com/EnterpriseDB/docs/issues/2206.
> Replication Server 6.2.16: Missing rel note

- product_docs/docs/efm/4/03_installing_efm.mdx
- product_docs/docs/efm/4/05_using_efm.mdx
- product_docs/docs/efm/4/12_upgrading_existing_cluster.mdx
- product_docs/docs/efm/4/efm_user/15_configuring_ssl_authentication.mdx
- Relative links that no longer referenced sibling pages
- Postgresql.org links that referenced version 10 vs. current
**Content**
> Fix some broken & obsolete links in the EFM 4 docs

- product_docs/docs/biganimal/release/getting_started/01_preparing_azure/index.mdx
Remove double-dash before subscription ID in preflight script examples.
**Content**
> Remove double-dash before subscription ID in preflight script examples

- product_docs/docs/bdr/4.0/functions.mdx
- product_docs/docs/bdr/4.0/nodes.mdx
- product_docs/docs/bdr/4.0/striggers.mdx
Fix link and admonitions in BDR import. 
This is the 2nd time around for this; the CAMO.md link needs to be fixed in the BDR branch, and I need to fix the admonition component's support for tabs.
> Fix admonition corruption in BDR import

- product_docs/docs/biganimal/release/overview/02_high_availability.mdx
Removed the line item about connecting to the standby replicas (not yet supported).
Removed the line item about connecting to the standby replicas (not yet supported).
**Content**
> BigAnimal: updated definition of replicas

- product_docs/docs/biganimal/release/getting_started/01_preparing_azure/index.mdx
- Update the BigAnimal getting_started documentation to pickup latest changes (bug fix) of the biganimal-preflight-check script
- adjust slightly the terms used in the documentation to say:
* SKU restriction: because the SKU limitation is what Azure put to indicate is this specific type of VM available in our data-center/POD? rather than the vCPU cores, which is a Azure customer's subscription quota limitation.
**Content**
> Update BigAnimal getting_started doc to reflect latest output of preflight check script

- gatsby-node.js
- static/_redirects
Builds on #2250 - turns out with Netlify rewriting (vs redirecting) /edb-docs paths, 404s on Docs don't... Work. Gatsby does something stupid and you end up with a blank page. 
So, need catch-alls for every path under /edb-docs (at least get you to the right *product* if a specific page didn't get remapped) and /edb-docs itself. 
Had some of this already, but to use wildcards needs to be written to the end of the file so as to avoid interfering with more specific redirects.
> Catch EVERYTHING going to /edb-docs, send it somewhere sane

- gatsby-node.js
I copied a value to two lines in the redirect, breaking the JDBC fallback. Thanks for the catch, @jericson !
> fix copy-paste error with redirects

- product_docs/docs/biganimal/release/using_cluster/06_demonstration_oracle_compatibility.mdx
Adding some instructions for importing to your own cluster to the Oracle syntax demo - primarily of value to give Trial users something to do right off the bat.
@jericson would you mind running through these to verify that... I got them right?
@drothery-edb could you sanity check this for style and flow?
**Content**
> Add import instructions to BA Oracle compat demo

- product_docs/docs/biganimal/release/getting_started/02_connect_cloud_account.mdx
- Fixed typo in the syntax of the create-spn guidance.
- Original: "The syntax of the command is:
curl -sL https://raw.githubusercontent.com/EnterpriseDB/cloud-utilities/main/azure/create-spn.sh | bash -s \
-- --display-name <display-name> \
----subscription <subscription> \
-- -years <years>"
- Corrected: "The syntax of the command is:
curl -sL https://raw.githubusercontent.com/EnterpriseDB/cloud-utilities/main/azure/create-spn.sh | bash -s \
-- -display-name <display-name> \
-- -subscription <subscription> \
-- -years <years>"
**Content**
> BigAnimal Connecting your account topic: fixing hyphens in create-spn.sh curl command

- gatsby-node.js
Netlify deploys take too long. A big part of this is that 6K+ files are hashing differently from build to build.
Turns out, a big part of this is the list of client-side redirects stored in app-<hash>.js. If the order changes (and it does) then the hash on that file changes, which in turn is propagated to every HTML file - and now those also hash differently.
There are a few possible solutions to this:
- ensure pages are added in the same order every time
- don't do client-side redirects
- sort the list of pages
Starting off with the last one, because it is easy. Reduces the no-change diff between builds from 6K+ to about 10 files. Which is still... 9 more than it should be (1 will always change as it contains the build timestamp). But, an improvement!
> Netlify deploy optimization

- product_docs/docs/biganimal/release/reference/cli.mdx
biganimal CLI binary checksum verification guide has some inaccurate description and wrong sample commands. This PR is to correct these bugs, and add more sample command for different platforms.
**Examples**
**Content**
> fix(UPM-4584): fix sha256 verification guide bugs

- product_docs/docs/pem/8/pem_inst_guide_linux/04_installing_postgres_enterprise_manager/07_configuring_the_pem_server_to_use_windows_kerberos_server.mdx
When customer uses the same SPN (Domain User) for generating the keytab files, it ends up updating 'kvno' on every newly generated keytab files, and he won't be able to login to PEM Server ever.
> Use '-kvno 0' while generating the keytab files.

- scripts/source/bdr.js
I was wrong. We really do need to use docs2 that only shows up in release branches.
> Really did need to use docs2

- product_docs/docs/efm/4/05_using_efm.mdx
change "orimary" to "primary". EFM-1508
**Content**
> typo in word "primary"

- src/styles/_dark.scss
- src/styles/_theme.scss
* fixed some dark mode overrides were not previously being applied due to a small css bug
* Updated the link colors & hover states to pass accessibility AAA contrast
* bumped the `font-weight` overall from 300 to 350 for better rendering on both dark and light mode
**Content**
> Accessibility updates

- product_docs/docs/migration_portal/3.5.0/01_mp_release_notes/index.mdx
Clarified in the rel notes that Migration Portal 3.5.0 no longer supports the assessment of files generated by the previously provided EDB DDL extractor
> Updated MP 3.5 rel notes

- product_docs/docs/epas/10/language_pack/01_supported_database_server_versions.mdx
- product_docs/docs/epas/10/language_pack/03_using_the_procedural_languages.mdx
- product_docs/docs/epas/10/language_pack/index.mdx
- product_docs/docs/epas/11/language_pack/01_supported_database_server_versions.mdx
- product_docs/docs/epas/11/language_pack/03_using_the_procedural_languages.mdx
- product_docs/docs/epas/11/language_pack/index.mdx
- product_docs/docs/epas/12/language_pack/01_supported_database_server_versions.mdx
- product_docs/docs/epas/12/language_pack/03_using_the_procedural_languages.mdx
- product_docs/docs/epas/12/language_pack/index.mdx
- product_docs/docs/epas/13/language_pack/01_supported_database_server_versions.mdx
- product_docs/docs/epas/13/language_pack/03_using_the_procedural_languages.mdx
- product_docs/docs/epas/13/language_pack/index.mdx
- product_docs/docs/epas/14/language_pack/01_supported_database_server_versions.mdx
- product_docs/docs/epas/14/language_pack/03_using_the_procedural_languages.mdx
- product_docs/docs/epas/14/language_pack/index.mdx
- Removed circular links 
- Clarified Language pack/ EPAS version mapping
- Removed Java reference
- Standardized Tcl capitalization
> EPAS:  cleaning up Language Pack content

- gatsby-node.js
- src/templates/file.js
Apparently later Gatsby 4 releases don't reliably hold onto file content in the graphql database just because it was once retrieved. See: https://github.com/gatsbyjs/gatsby/issues/34605
So... Instead of just retrieving the content and doing nothing with it, explicitly store it in a field and then use that field.
> Correctly pass sample code to yaml file module

- product_docs/docs/biganimal/release/using_cluster/02_connecting_your_cluster/01_connecting_from_azure/01_private_endpoint.mdx
Fixed typo "exammple" to "example"
> Fixed typo "exammple" to "example"

- package.json
This finishes 87e6324a3cc73e61ac1a3559d8e2d9c1ace80242 by moving the --force option to the npm script. I ... just forgot to commit the file.
> Force mtimes script to run 

- product_docs/docs/biganimal/release/using_cluster/05_monitoring_and_logging/06_metrics.mdx
- Update BigAnimal metrics page to incorporate changes in the way metrics are gathered. These metrics will now be stored in the DpMetrics_CL table going forward. Old InsightMetrics gathered data is still being collected but will be switched off.
**Content**
> docs(UPM-5493): update BigAnimal metrics documentaion for telegraf-fluentbit changes

- product_docs/docs/eprs/7.0/02_overview/04_design_replication_system/03_restrictions_on_replicated_database_objects.mdx
- product_docs/docs/eprs/7.0/08_xdb_cli/03_xdb_cli_commands/41_taking_mmr_snapshot.mdx
- product_docs/docs/eprs/7.0/08_xdb_cli/03_xdb_cli_commands/49_clean_shadow_table_history.mdx
Addressed typo mentioned on [XDB-1093](https://enterprisedb.atlassian.net/browse/XDB-1093) (replicate misspelled on (https://www.enterprisedb.com/docs/eprs/latest/02_overview/04_design_replication_system/03_restrictions_on_replicated_database_objects/)
Addressed https://enterprisedb.atlassian.net/browse/XDB-1092 (changed case of MMW in Take a Multi-Master Snapshot (dommrsnapshot)  and Cleaning Up Shadow Table History
(cleanshadowhistforpub) CLI commands
> EPRS 7.0: doc bug fixes

- scripts/source/bdr.js
- scripts/source/dispatch_product.py
- scripts/source/livecompare.js
- scripts/source/pglogical.js
- scripts/source/test/sync-bdr.json
BDR, Harp, LiveCompare, pgLogical all need to behave in the same way: newly-added files get brought in, deleted files get removed. 
This was not happening consistently, mostly because these conversion scripts were written to be run manually and sorta expected to be dumping their output in a scratch directory. 
I've altered them to process files in place, and then copy over only select files (mdx, jpg, jpeg, png, svg) - deleting any files of these types that aren't found in the destination subtree. 
(for Harp, only this last sync step is performed)
One small hitch is the images for BDR, which 
1. live in the parent directory from the rest of the content, and
2. don't seem to exist at all in the last sync ref
...so I'm ignoring those for now (using the old sync logic) to avoid deleting them …
> Alter BDR, etc. source scripts to sync w/ deletion

- product_docs/docs/biganimal/release/using_cluster/03_modifying_your_cluster/05_db_configuration_parameters.mdx
Removed note saying you can't decrease the values of some parameters
> BigAnimal: removing note re parameters

- advocacy_docs/supported-open-source/barman/pg-backup-api/01-installation.mdx
- advocacy_docs/supported-open-source/barman/pg-backup-api/02-securing-pg-backup-api.mdx
- advocacy_docs/supported-open-source/barman/pg-backup-api/index.mdx
Adds documentation for Postgres backup API (pg-backup-api) to the Barman
documentation.
- Added page for Postgres backup API
- Added Installation page for Postgres backup API
- Added Securing Postgres backup API page
**Content**
> Add documentation for Postgres backup API

- advocacy_docs/migrating/oracle/oracle_epas_comparison/app_devel_capabilities.mdx
Updated the link location for the list of supported PL/SQL packages.  The references had underscores in the location.  Changed to dashes.
> Updated link in table to list of supported PL/SQL packages

- product_docs/docs/bdr/4.0/conflicts.mdx
Fixed typo in the parameter name `track_commit_timestamp`.
**Content**
> Typo in parameter name

- product_docs/docs/biganimal/release/overview/03a_region_support.mdx
replaced AWS free trial regions (not needed because they are documented in the free trial topic) with the AWS regions
> BigAnimal: AWS regions

- product_docs/docs/migration_toolkit/55/02_supported_operating_systems_and_database_versions.mdx
Removed the release specific information after each listed supported Oracle version on the 02_supported_operating_systems_and_database_versions page.  For example, instead of stating Oracle 12c Release 1, it now simply states Oracle 12c.
> Updated supported Oracle versions

- advocacy_docs/supported-open-source/barman/pg-backup-api/01-installation.mdx
- advocacy_docs/supported-open-source/barman/pg-backup-api/02-securing-pg-backup-api.mdx
Updates the instructions for installing and configuring pg-backup-api for the barman product in the supported-open-source section. These are minor fixes which relate to released versions of the products.
- Restart httpd when securing pg-backup-api on RHEL8
- Fix chmod when securing pg-backup-api
- Change location of keys and certs for pg-backup-api
- Add SELinux commands for securing pg-backup-api
- Enable pg-backup-api and httpd services
**Content**
> Pgbapi fix for selinux

- product_docs/docs/pgd/4/upgrades/index.mdx
During major version upgrade, WAL senders on higher BDR version nodes
are not expected to use LCRs due to proto_version mismatch. Update the
upgrade documentation with the details.
BDR-2195
> Add documentation for LCR usage during upgrade

- advocacy_docs/supported-open-source/cloud_native_pg/index.mdx
Signed-off-by: Gabriele Bartolini <gabriele.bartolini@enterprisedb.com>
Set the URL to the CNPG docs rather than homepage
**Content**
> fix: link to CNPG docs rather than home page

- product_docs/docs/efm/4/05_using_efm.mdx
Each agent has to use a unique service name for the database, or else one cluster might shut down the db being used by another cluster.
**Content**
> add property to unique list for >1 agent/node

- product_docs/docs/postgres_for_kubernetes/1/openshift.mdx
Change a few links to reference content in the open source operator docs
**Content**
> Fix a couple of links in the openshift doc that referenced docs in the opensource docs

- advocacy_docs/supported-open-source/cloud_native_pg/index.mdx
Sending users directly to the 1.15 doc. We'll need to figure out how to set up links to "lastest" later
> CloudNativePG doc link

- product_docs/docs/bdr/4/functions.mdx
- product_docs/docs/bdr/4/group-commit.mdx
- product_docs/docs/bdr/4/lag-control.mdx
- BDR - explain limits of Group Commit and Lag Control
- Also add documentation for the bdr.lag_control function by Charlie
**Content**
> Explain limitations of Group Commit and Lag control.

- product_docs/docs/efm/4/12_upgrading_existing_cluster.mdx
This adds a note for any customers that are calling efm scripts from their own custom script. They need to update their scripts before uninstalling a version of EFM to avoid breaking them.
https://enterprisedb.atlassian.net/browse/EFM-1514
**Content**
> note to the uninstall section

- product_docs/docs/efm/4/01_prerequisites.mdx
The text made it sound like the user checks to see if files exist, rather than describing that the efm agent does it. Also removed a redundant sentence that I think isn't needed.
**Content**
> update to autostart instructions

- src/styles/_docs.scss
Fixes #2612
Per @drothery-edb 's request, this alters the styling used for nested ordered lists to make distinguishing the nesting level a bit easier.
There are only about 17 nested ordered lists in the current docs. The only one that looked a bit odd to me can be found here: https://www.enterprisedb.com/docs/biganimal/latest/getting_started/identity_provider/okta/#:~:text=On%20the%20Assignments%20tab - that's an ordered list within an ordered list within an ordered list. An unusual occurrence... But I added a case for that just to be on the safe side - at 3 levels deep it'll switch to roman numerals. Any deeper than that, it'll switch back to digits.
Here are some pages to check:
- product_docs/docs/biganimal/release/migration/cold_migration.mdx:12:5 …
> Use different list markers for nested ordered lists

- product_docs/docs/bdr/4/group-commit.mdx
- Fixed typo in BDR4 group commit section
- Fix output in the code blocks to be viewed entirely in BDR4 group commit section
**Content**
> BDR/Group Commit cosmetics and typos

- product_docs/docs/harp/2/07_harp_proxy.mdx
- Removed un-needed information about how to manually set up authentication
**Content**
> Remove un-needed information around pgbouncer HNG-607

- product_docs/docs/eprs/7/03_installation/03_installing_rpm_package/ibm_power_ppc64le/11_eprs_sles15_ppcle.mdx
- product_docs/docs/eprs/7/03_installation/03_installing_rpm_package/x86_amd64/05_eprs_sles15_x86.mdx
Two topics had the package manager command as dnf. I assume that's supposed to be zypper. 
If you approve, you can merge
> changed dnf to zypper for SLES 15 topics for Replication Server

- product_docs/docs/bdr/3.6/index.mdx
- product_docs/docs/bdr/3.7/backup.mdx
- product_docs/docs/bdr/3.7/camo.mdx
- product_docs/docs/bdr/3.7/camo_clients.mdx
- product_docs/docs/bdr/3.7/configuration.mdx
- product_docs/docs/bdr/3.7/eager.mdx
- product_docs/docs/bdr/3.7/index.mdx
- product_docs/docs/bdr/3.7/isolation_details.mdx
- product_docs/docs/bdr/3.7/monitoring.mdx
- product_docs/docs/bdr/3.7/overview.mdx
- product_docs/docs/harp/2/03_installation.mdx
- product_docs/docs/pgd/4/backup.mdx
- product_docs/docs/pgd/4/monitoring.mdx
Documentation for BDR4 and BDR3.7 in the `Monitoring`  section
- Adjusted information related to `bdr.worker_errors` and the persistency of the data.
- Adjusted links and references to 2ndQuadrant -> EDB
**Content**
> Clarify documentation for bdr.worker_errors

- product_docs/docs/epas/14/epas_rel_notes/epas14_4_0_rel_notes.mdx
Support ticket 83263 was depending on the fix of DB-1777, but was missing from the metadata
This adds the support ticket number that is related to DB-1777
**Content**
> Add ticket number to EPAS 14.4.0 bug fix

- advocacy_docs/supported-open-source/pgbackrest/02-installation.mdx
In a support ticket (83285), a customer followed these directions and installed `postgresql-libs` manually before pgbackrest. Later on, that package conflicted with other dependencies of other packages, in the typical collision on `/usr/lib64/libpq.so`.
In RHEL 7, `postgresql-libs` brings libpq 9.2 of Red Hat, which is not a supported version and is also not tested against any of our packages. In RHEL 8, that package does not exist; instead, RHEL 8 provides `libpq` in the appstream repository.
In both cases, the package provided by PGDG is called `libpq5`, which is the right expectation to set when installing `pgbackrest` also from PGDG.
Additionally, if other packages have been installed before and already pulled these dependencies, then maybe these libraries won't be pulled in when …
> Adjust dependencies of pgBackRest in RHEL 7

- product_docs/docs/pgd/4/upgrades/index.mdx
Changed "upgrade" to "downtime" as per [DF-298](https://enterprisedb.atlassian.net/browse/DF-298)
> PGD: upgrades typo fix

- product_docs/docs/postgres_for_kubernetes/1/index.mdx
After discussing with @josh-heyer, we figured out why the tiles on the opening page were missing and how to add those.
This PR is to fix that.
> chore: adding chapter formatting to the opening page for EDB Postgres for Kubernetes

- product_docs/docs/bdr/3.6/index.mdx
- product_docs/docs/bdr/3.7/backup.mdx
- product_docs/docs/bdr/3.7/camo.mdx
- product_docs/docs/bdr/3.7/camo_clients.mdx
- product_docs/docs/bdr/3.7/configuration.mdx
- product_docs/docs/bdr/3.7/eager.mdx
- product_docs/docs/bdr/3.7/index.mdx
- product_docs/docs/bdr/3.7/isolation_details.mdx
- product_docs/docs/bdr/3.7/monitoring.mdx
- product_docs/docs/bdr/3.7/overview.mdx
- product_docs/docs/bdr/4/camo.mdx
- product_docs/docs/bdr/4/configuration.mdx
- product_docs/docs/bdr/4/eager.mdx
- product_docs/docs/bdr/4/functions.mdx
- product_docs/docs/bdr/4/group-commit.mdx
- product_docs/docs/bdr/4/release_notes/bdr4.1.1_rel_notes.mdx
- product_docs/docs/harp/2/01_release_notes/harp2.1.1_rel_notes.mdx
- product_docs/docs/harp/2/01_release_notes/index.mdx
- product_docs/docs/harp/2/03_installation.mdx
- product_docs/docs/pgd/4/backup.mdx
- product_docs/docs/pgd/4/monitoring.mdx
- product_docs/docs/pgd/4/rel_notes/epd_4_1_1_rel_notes.mdx
- product_docs/docs/pgd/4/rel_notes/epd_4_rel_notes.mdx
- product_docs/docs/pgd/4/rel_notes/index.mdx
- Add initial release notes for BDR 4.1.1
- add documentation related to functions bdr.is_node_ready() and bdr.is_node_connected
**Content**
> Documentation for BDR 4.1.1

- product_docs/docs/efm/4/05_using_efm.mdx
The original text here says that the user may reset the value, which isn't something we should direct the user to do (or even explain how they *could* do it). The text is supposed to say that it's something that can happen. The original text in the workspace didn't say that the user could do it, so this was messed up somewhere later.
**Content**
> change to efm standby priority description

- src/constants/products.js
This is motivated by #2798 - need to get product names in some semblance of order for contextual search to work properly. 
- Removes "ark" definition - this product isn't built anymore (and hasn't been in a good while)
- Adds definitions for LiveCompare, pglogical, edb_plus
> Add livecompare, pglogical, edbplus; remove ark; alphabetize

- product_docs/docs/biganimal/release/getting_started/creating_a_cluster/index.mdx
- product_docs/docs/biganimal/release/pricing_and_billing/index.mdx
AWS and Azure calculator links were switched
Links to cluster types from creating a cluster were broken
> BigAnimal: fixing pricing calculater links and links to cluster types

- product_docs/docs/pgd/4/cli/command_ref/pgd_check-health.mdx
- product_docs/docs/pgd/4/cli/command_ref/pgd_show-clockskew.mdx
Added a note about inaccurate results for clock skew estimation with current implementation
when cluster is under high load or has large number of nodes in it.
We are working to improve the accuracy as part of [BDR-2157](https://enterprisedb.atlassian.net/browse/BDR-2157). 
This note would go away once the algorithm is updated.
**Content**
> BDR-2351 - Add a note about clock skew estimation with current implementation

- product_docs/docs/biganimal/release/using_cluster/06_demonstration_oracle_compatibility.mdx
Old BA cluster is being shut down, so need a new one - using a (long-lived) demo instance for convenience.
(also fixed paths in backup/restore section so they actually work)
**Content**
> Update host to point to demo BA instance, fix path in restore

- product_docs/docs/biganimal/release/reference/cli.mdx
- The `create-cluster` subcommand interactive mode sample. 
- The `create-cluster` configuration file sample.
**Examples**
**Content**
> chore(UPM-8458): Document update to reflect CLI 1.6.0 changes.

- product_docs/docs/bdr/4/configuration.mdx
The hint for a 4 node BDR cluster mentions some vague values for `max_replication_slots` and `max_worker_processes`. These values don't seem to be rational and hence dropping the hint.
**Content**
- [ x] This PR removes existing content
> Remove the vague hint for props value

- product_docs/docs/epas/14/epas_guide/03_database_administration/05_edb_audit_logging/09_object_auditing.mdx
- updated syntax from { select | update | delete | insert }@groupname to { select | update | delete | insert }{@ | -}groupname in v14
> EPAS: updated edb_audit_statement syntax as per DB-1689

- static/_redirects
Fixed redirects for releases in https://github.com/EnterpriseDB/docs/pull/3006
> PostGIS PgBouncer redirects

- install_template/templates/products/edb-jdbc-connector/ubuntu-18.04.njk
- install_template/templates/products/edb-jdbc-connector/ubuntu-20.04.njk
This maybe doesn't affect Macs, but Linux systems do care if the case doesn't match the filename - JDBC install templates were failing to build as a result.
> Fix case so JDBC install templates build on Linux

- src/components/left-nav.js
Early in the development of EDB Docs 2.0, navigating deep into a set of nested topics might leave you with a limited set of options in the navigation sidebar with no way to get back "up" to the parent topic. A "<- Back" link was added to let folks navigate "up". 
Docs was changed a long time ago to show the full heirarchy in the sidebar. The "Back" button was also changed to always go back to the docs homepage. Which is also what clicking the "docs" part of "EDB / docs" does. 
This leaves the "<-- Back" link sorta redundant at best and confusing at worst. Let's get rid of it!
> Remove superfluous back button

- product_docs/docs/biganimal/release/getting_started/preparing_cloud_account/01_preparing_azure/index.mdx
- product_docs/docs/biganimal/release/reference/api.mdx
- product_docs/docs/biganimal/release/reference/cli.mdx
- product_docs/docs/biganimal/release/using_cluster/02_connecting_your_cluster/01_connecting_from_azure/01_private_endpoint.mdx
- product_docs/docs/biganimal/release/using_cluster/02_connecting_your_cluster/01_connecting_from_azure/02_virtual_network_peering.mdx
- product_docs/docs/biganimal/release/using_cluster/02_connecting_your_cluster/01_connecting_from_azure/03_vnet_vnet.mdx
- product_docs/docs/biganimal/release/using_cluster/02_connecting_your_cluster/02_connecting_from_aws/01_vpc_endpoint.mdx
- product_docs/docs/biganimal/release/using_cluster/02_connecting_your_cluster/02_connecting_from_aws/02_vpc_peering.mdx
- src/styles/_docs.scss
Addresses issue #3022 - inability to copy certain commands in shell listings due to the presence of output listings.
Three conventions should be used in these docs for shell code blocks:
1. Do not lead with a "prompt" (such as `$` or `#`) - if copy-pasted, these will lead to either "command not found" or a no-op, both which are confusing.
2. Separate command output from the command(s) themselves by a line containing only the text `__OUTPUT__`. When built, this will result in a separate (but visually-connected) listing that will not be copied.
3. Break long lines in a consistent and visually-appealing fashion to aid in reading long commands. 70 characters give or take is a good rule of thumb - if more than two lines, might as well go with one parameter per line.
Please check all boxes that …
> Separate shell commands from output listings in BigAnimal docs

- product_docs/docs/postgres_for_kubernetes/1/rel_notes/1_16_rel_notes.mdx
Added instructions for how to upgrade to versions 1.16.x of EDB Postgres for Kubernetes on Openshift.
**Content**
> Adding instructions for Openshift upgrade to 1.16.x

- product_docs/docs/biganimal/release/overview/04_responsibility_model.mdx
Sandeep Arora pointed out the following: 
The High Availability section mentions two standby replicas whereas we have now an option to have either one or two. Only the wording needs to be updated to ensure one does not think we only deploy two standby replicas.
This PR addresses the issue.
> BigAnimal: HA section of Shared responsibilities

- product_docs/docs/biganimal/release/getting_started/02_connecting_to_your_cloud/index.mdx
Updated the examples in the CLI examples that used deprecated --high-availability option
https://enterprisedb.atlassian.net/browse/UPM-8984
> BigAnimal: fixed --high-availability examples

- product_docs/docs/pgd/4/overview/bdr/catalogs.mdx
-  Add missing column in `bdr.ddl_epoch`
-  Fixed a typo in the description of `bdr.conflict_history.local_lsn`.
**Content**
> Add missing column in bdr.ddl_epoch

- product_docs/docs/eprs/6.2/07_common_operations/08_replicating_ddl_changes/01_ddl_change_replication.mdx
- product_docs/docs/eprs/7/07_common_operations/08_replicating_ddl_changes/01_ddl_change_replication.mdx
- added note as per [XDB-1595](https://enterprisedb.atlassian.net/browse/XDB-1595)
- removed sentence at the bottom of /6.2/07_common_operations/08_replicating_ddl_changes/01_ddl_change_replication/ that referred to a nonexistent section and referred to Replication Server as xDB
> EPRS: alterDDL command limitation note

- scripts/source/pglogical2.js
- src/pages/index.js
Should be "pglogical" not "pgLogical" (or "PGlogical" or "PgLogical" or "pGlOgIcAl")
Also restored a few omissions to the import script
**Content**
> Fix capitalization of pglogical on homepage

- advocacy_docs/supported-open-source/cloud_native_pg/index.mdx
Changed link to point to doc landing page instead of v1.15 page
> CloudNativePG: fixed doc link

- product_docs/docs/ocl_connector/14.1.0.1/02_supported_platforms.mdx
Using the approach we are using for most other products of linking to https://www.enterprisedb.com/resources/platform-compatibility instead of maintaining a list of supported platforms in the doc - using a single source of truth.
https://enterprisedb.atlassian.net/browse/EC-2315
> OCL: updated platform support topic to link to web site

- install_template/templates/products/postgres-enterprise-manager-server/base.njk
- product_docs/docs/pem/8/installing_pem_server/pem_server_inst_linux/installing_pem_server_using_edb_repository/ibm_power_ppc64le/pem_server_rhel8_ppcle.mdx
- product_docs/docs/pem/8/installing_pem_server/pem_server_inst_linux/installing_pem_server_using_edb_repository/ibm_power_ppc64le/pem_server_sles12_ppcle.mdx
- product_docs/docs/pem/8/installing_pem_server/pem_server_inst_linux/installing_pem_server_using_edb_repository/ibm_power_ppc64le/pem_server_sles15_ppcle.mdx
- product_docs/docs/pem/8/installing_pem_server/pem_server_inst_linux/installing_pem_server_using_edb_repository/x86_amd64/pem_server_centos7_x86.mdx
- product_docs/docs/pem/8/installing_pem_server/pem_server_inst_linux/installing_pem_server_using_edb_repository/x86_amd64/pem_server_deb10_x86.mdx
- product_docs/docs/pem/8/installing_pem_server/pem_server_inst_linux/installing_pem_server_using_edb_repository/x86_amd64/pem_server_other_linux8_x86.mdx
- product_docs/docs/pem/8/installing_pem_server/pem_server_inst_linux/installing_pem_server_using_edb_repository/x86_amd64/pem_server_rhel7_x86.mdx
- product_docs/docs/pem/8/installing_pem_server/pem_server_inst_linux/installing_pem_server_using_edb_repository/x86_amd64/pem_server_rhel8_x86.mdx
- product_docs/docs/pem/8/installing_pem_server/pem_server_inst_linux/installing_pem_server_using_edb_repository/x86_amd64/pem_server_sles12_x86.mdx
- product_docs/docs/pem/8/installing_pem_server/pem_server_inst_linux/installing_pem_server_using_edb_repository/x86_amd64/pem_server_sles15_x86.mdx
- product_docs/docs/pem/8/installing_pem_server/pem_server_inst_linux/installing_pem_server_using_edb_repository/x86_amd64/pem_server_ubuntu18_x86.mdx
- product_docs/docs/pem/8/installing_pem_server/pem_server_inst_linux/installing_pem_server_using_edb_repository/x86_amd64/pem_server_ubuntu20_x86.mdx
Fixed broken link and the capitalization in the label in the install topics 
Updated the template files and regenerated and deployed install topics with corrections
> PEM: fixed broken link to init config topic in install topics

- product_docs/docs/pgd/3.7/pglogical/subscriptions/index.mdx
Removed the second instance of the `apply_delay` parameter of the pglogical.create_subscription function
> pglogical3: duplicate info issue

- product_docs/docs/biganimal/release/overview/02_high_availability.mdx
Updated the description in the Synchronous replication section to mention that you can change the default behavior of 2-node clusters
> BigAnimal: two-node cluster clarification

- product_docs/docs/biganimal/release/using_cluster/01_postgres_access.mdx
removed extra 'a' and misspelling of 'privileges' as 'priviledges'
**Examples**
**Content**
> small-mispelling-update-natalia

- .github/workflows/deploy-draft.yml
- docker/docker-compose.build-pdf.yaml
- docker/images/Dockerfile.pdf-builder
- scripts/pdf/cleanup_combined_markdown.mjs
- scripts/pdf/generate_pdf.py
- scripts/pdf/lib/mdast-embedded-hast.mjs
- scripts/pdf/package-lock.json
- scripts/pdf/package.json
- scripts/pdf/pdf-styles.css
Adds a preprocessing step to PDF generation, after the individual topics are combined but before the Markdown is rendered to HTML. Within this step,
1. All links are rewritten as follows:
- All headings have unique (within the PDF) IDs generated for them and link targets added 
- All other IDs (ex: `<div id='blah'>`) are rewritten to be unique within the entire PDF (ex: `<div id='blah'></div><div id='blah2'></div>...`)
- Links that resolve to content that will be included within the PDF (other pages within the same product, sections within the same page, HTML IDs) are rewritten to point to the PDF-specific IDs. This includes both Markdown links and HTML links (`<a href=...`)
- Links that resolve to content that will *not* be included within the PDF (other products, other pages on EDB's …
> Rewrite URLs in combined MDX before generating PDF

- product_docs/docs/biganimal/release/using_cluster/05_monitoring_and_logging/metrics/index.mdx
- product_docs/docs/biganimal/release/using_cluster/05_monitoring_and_logging/monitoring_from_azure/index.mdx
Update made based in this Slack conversation with Sandeep Arora:
On this docs page - https://www.enterprisedb.com/docs/biganimal/latest/using_cluster/05_monitoring_and_logging/monitoring_from_azure/
Step 4 - we don't have "Log Analytics Workspace" with the suffix -customer , this needs to corrected.
It is a random suffix, however there is a fixed prefix - [log-workspace-]
> BigAnimal: update to Monitoring Azure topic

- install_template/templates/products/mysql-foreign-data-wrapper/centos-7.njk
- install_template/templates/products/mysql-foreign-data-wrapper/debian-10.njk
- install_template/templates/products/mysql-foreign-data-wrapper/debian-11.njk
- install_template/templates/products/mysql-foreign-data-wrapper/ubuntu-18.04.njk
- product_docs/docs/mysql_data_adapter/2/02_requirements_overview.mdx
- product_docs/docs/mysql_data_adapter/2/04_installing_the_mysql_data_adapter/x86_amd64/mysql_centos7_x86.mdx
- product_docs/docs/mysql_data_adapter/2/04_installing_the_mysql_data_adapter/x86_amd64/mysql_deb10_x86.mdx
- product_docs/docs/mysql_data_adapter/2/04_installing_the_mysql_data_adapter/x86_amd64/mysql_deb11_x86.mdx
- product_docs/docs/mysql_data_adapter/2/04_installing_the_mysql_data_adapter/x86_amd64/mysql_ubuntu18_x86.mdx
- product_docs/docs/pem/8/installing_pem_server/pem_server_inst_linux/installing_pem_server_using_edb_repository/x86_amd64/pem_server_deb11_x86.mdx
buster > bullseye in url for Debian 11
buster > bionic for Ubuntu 18
removed MySQL 5 command
> MySQL: updated MySQL prerequisite for Debian 11

- advocacy_docs/supported-open-source/cloud_native_pg/index.mdx
- product_docs/docs/postgres_for_kubernetes/1/rel_notes/index.mdx
Redirect relative paths pointing at ./release_notes to ./rel_notes
Avoids unnecessary trip through stub page. The original path is release_notes, which we don't include (referring instead to the open source docs from our internal release notes which live at rel_notes). 
**Content**
> Redirect from import path to internal path for release notes

- product_docs/docs/migration_toolkit/55/05_installing_mtk/install_on_linux/ibm_power_ppc64le/index.mdx
- product_docs/docs/migration_toolkit/55/05_installing_mtk/install_on_linux/x86_amd64/index.mdx
- product_docs/docs/migration_toolkit/55/05_installing_mtk/install_on_linux/x86_amd64/mtk55_deb11_x86.mdx
Missed updating the link and label on these blurbs in the sub-landing pages for install. Decided to remove them as those instructions are provided on the parent topic and all the child install topics and are deemed unnecessary
Fixed same info on Debian 11 topic
> MTK: updates to sections that had referred to third-party drivers

- product_docs/docs/biganimal/release/using_cluster/06_analyze_with_superset.mdx
Removing the SSO auth mechanism note between BigAnimal and Superset as it is no longer valid after the new PKCE flow implementation. 
**Content**
> docs(UPM-9010): Remove the SSO note for superset

- product_docs/docs/biganimal/release/getting_started/index.mdx
Added the Connecting your cluster back in to the nav order. Removed it erroneously.
> BigAnimal: fixed nav order in Getting started

- product_docs/docs/pgd/5/known_issues.mdx
- Non-default replications sets are supported now with bdr-1775 changes. So removed the known issues related to it. 
**Content**
> Fix known issues for decoding worker and replications sets

- product_docs/docs/biganimal/release/using_cluster/02_connecting_your_cluster/index.mdx
Removed extraneous "to" in the "Connecting your cluster to EDB's migration tools" section of the "Connecting your cluster" topic.
> BA: removed extraneous "to" in Connecting topic

- product_docs/docs/pgd/4/deployments/tpaexec/quick_start.mdx
The --layout parameter is case sensitive, and only accepts lower case values. So the "Silver" in the example causes it to fail, issuing a message to the user. 
This change does s/Silver/silver/, which allows the example to be used as is intended.
**Content**
> Adjust the example layout

- product_docs/docs/biganimal/release/using_cluster/02_connecting_your_cluster/index.mdx
- product_docs/docs/efm/4/12_upgrading_existing_cluster.mdx
- product_docs/docs/epas/14/language_pack/02_installing_language_pack.mdx
- product_docs/docs/eprs/6.2/07_common_operations/08_replicating_ddl_changes/01_ddl_change_replication.mdx
- product_docs/docs/eprs/7/07_common_operations/08_replicating_ddl_changes/01_ddl_change_replication.mdx
- product_docs/docs/migration_toolkit/55/06_building_toolkit.properties_file.mdx
- product_docs/docs/pgd/4/deployments/tpaexec/quick_start.mdx
- EPAS: fixed version number in Language Pack doc
- MTK: added location for toolkit file in Mac OS
- EPRS: added DDL change replication process note
- EFM: clarified cluster upgrade process
- PGD: fixed case of Silver in TPAexec example
- BigAnimal: removed extraneous "to" in Connecting topic
> Release: 2022-10-17

- product_docs/docs/biganimal/release/using_cluster/06_analyze_with_superset.mdx
Added the docs for import dashboard template in Apache Superset in `Using Superset dashboards` section.
**Examples**
- We have added a capability to export the ready-to-import PGD dashboard in any Superset instance. We need to specify the steps and  export the JSON file.
**Content**
> docs(UPM-10326): Docs for PGD dashboard import in superset

- product_docs/docs/epas/13/epas_inst_linux/05_managing_an_advanced_server_installation.mdx
- product_docs/docs/epas/13/epas_inst_windows/06_configuring_advanced_server/02_connecting_to_advanced_server_with_psql.mdx
- product_docs/docs/epas/14/epas_inst_linux/managing_an_advanced_server_installation.mdx
- product_docs/docs/epas/14/epas_inst_windows/managing_an_advanced_server_installation/configuring_epas.mdx
Changed the following language
Before: 
`edb-psql is a symbolic link to PostgreSQL community psql. For more information about using the command line client, see the PostgreSQL Core Documentation at:
`
After: 
`edb-psql is a symbolic link to a binary called `psql`, a modified version of the PostgreSQL community `psql`, with added support for Advanced Server features. For more information about using the command line client, see the PostgreSQL Core Documentation at:`
**Reasoning**
it’s true the edb-psql is a symlink to a binary called psql, but it’s an EDB-modified version of psql, not the community version
**Content**
> Update edb-psql description for accuracy (EDB modified not community) 

- product_docs/docs/biganimal/release/using_cluster/01_postgres_access.mdx
Add the statement about not storing data in postgres database
Avoid storing data in the `postgres` database, which is used as an access point to configure the cluster.
**Content**
> we don't recommend the user to store data in postgres database

- install_template/deploy.mjs
- install_template/templates/products/edb-odbc-connector/base.njk
- install_template/templates/products/edb-odbc-connector/debian.njk
- install_template/templates/products/edb-odbc-connector/sles-12.njk
- install_template/templates/products/edb-odbc-connector/sles-15.njk
- install_template/templates/products/edb-odbc-connector/ubuntu.njk
- product_docs/docs/eprs/7/03_installation/03_installing_rpm_package/x86_amd64/eprs_centos7_x86.mdx
- product_docs/docs/jdbc_connector/42.5.0.1/images/selecting_the_connectors_installer.png
- product_docs/docs/ocl_connector/12.1.2.1/images/selecting_the_connectors_installer.png
- product_docs/docs/ocl_connector/13.1.4.2/images/selecting_the_connectors_installer.png
- product_docs/docs/ocl_connector/14.1.0.1/images/selecting_the_connectors_installer.png
- product_docs/docs/odbc_connector/12/images/selecting_the_connectors_installer.png
- product_docs/docs/odbc_connector/13/01_odbc_rel_notes/index.mdx
- product_docs/docs/odbc_connector/13/03_installing_edb_odbc/01_installing_linux/ibm_power_ppc64le/odbc13_rhel8_ppcle.mdx
- product_docs/docs/odbc_connector/13/03_installing_edb_odbc/01_installing_linux/ibm_power_ppc64le/odbc13_sles12_ppcle.mdx
- product_docs/docs/odbc_connector/13/03_installing_edb_odbc/01_installing_linux/ibm_power_ppc64le/odbc13_sles15_ppcle.mdx
- product_docs/docs/odbc_connector/13/03_installing_edb_odbc/01_installing_linux/x86_amd64/odbc13_centos7_x86.mdx
- product_docs/docs/odbc_connector/13/03_installing_edb_odbc/01_installing_linux/x86_amd64/odbc13_deb10_x86.mdx
- product_docs/docs/odbc_connector/13/03_installing_edb_odbc/01_installing_linux/x86_amd64/odbc13_deb11_x86.mdx
- product_docs/docs/odbc_connector/13/03_installing_edb_odbc/01_installing_linux/x86_amd64/odbc13_other_linux8_x86.mdx
- product_docs/docs/odbc_connector/13/03_installing_edb_odbc/01_installing_linux/x86_amd64/odbc13_rhel7_x86.mdx
- product_docs/docs/odbc_connector/13/03_installing_edb_odbc/01_installing_linux/x86_amd64/odbc13_rhel8_x86.mdx
- product_docs/docs/odbc_connector/13/03_installing_edb_odbc/01_installing_linux/x86_amd64/odbc13_sles12_x86.mdx
- product_docs/docs/odbc_connector/13/03_installing_edb_odbc/01_installing_linux/x86_amd64/odbc13_sles15_x86.mdx
- product_docs/docs/odbc_connector/13/03_installing_edb_odbc/01_installing_linux/x86_amd64/odbc13_ubuntu18_x86.mdx
- product_docs/docs/odbc_connector/13/03_installing_edb_odbc/01_installing_linux/x86_amd64/odbc13_ubuntu20_x86.mdx
- product_docs/docs/odbc_connector/13/images/selecting_the_connectors_installer.png
- Address  [EC-2395](https://enterprisedb.atlassian.net/browse/EC-2394) - ODBC Docs: Correct the description on Release Notes landing page
- Address [EC-2394](https://enterprisedb.atlassian.net/browse/EC-2395) - Update JDBC, OCI, ODBC docs to remove connector version numbers from Stackbuilder Plus screenshots
- Address [EC-2393](https://enterprisedb.atlassian.net/browse/EC-2393) - ODBC Docs: Add edb-odbc-devel install command to Rhel, CentOS, Rocky and SLES platforms installation pages
> Connectors: misc fixes 

- product_docs/docs/efm/4/04_configuring_efm/01_cluster_properties.mdx
The description for remote.timeout was misleading in that someone could infer that agents generally monitor remote databases. Agents only do this (communicate in general, that is) when there's some reason to, e.g. during a potential failover. They also send messages like "shutdown for switchover" to the primary, "reconfigure to follow the new primary" to standbys, "prepare to shutdown," etc. We could put in more examples if anyone thinks that would be more helpful in this section.
I'm suggesting we change the node.timeout one because an agent waiting "for a response" implies the agent sent a request to another. While "response" isn't technically NOT true, the real thing an agent is waiting on is a heartbeat message or any kind of communication from another agent before deciding "ok, it's …
> two efm timeout descriptions

- product_docs/docs/postgres_for_kubernetes/1/openshift.mdx
Currently, that section shows up literally as `!!! Important Alternatively, you can list namespaces using a label selector, as explained in` in the documentation. I believe that might be caused by the block being 1 space further in, when compared to the rest of the 3. section, so this change tries to handle that.
The indentation of the `!!! Important` section went from 4 spaces to 3 spaces, to match the rest of the contents of the 3. section
> Adjust indentation of a "!!! Important" section

- product_docs/docs/pgd/4/bdr/functions.mdx
`bdr.conflict_type_to_string()` and `bdr.conflict_resolution_to_string()` were required on 3.6 when we used the old `bdr.apply_log` table. Since 3.7, with the `bdr.conflict_history` table, those 2 functions no longer exist.
> Conflict to string functions no longer exist

- product_docs/docs/biganimal/release/free_trial/index.mdx
- product_docs/docs/biganimal/release/overview/02_high_availability.mdx
- product_docs/docs/biganimal/release/overview/05_database_version_policy.mdx
This reverts commit 16fb4340f6af42c053fac7d7caff63141f166e04.
> BigAnimal: remove beta from PostgreSQL references

- product_docs/docs/pgd/4/upgrades/upgrade_paths.mdx
Fix typo in URL to the 3.7 version, from updrades to upgrades
> Fix typo in URL to the 3.7 version

- product_docs/docs/pgd/4/harp/09_consensus-layer.mdx
Documentation only mentions Logical Standby nodes, but we also need to mention Subscriber-Only nodes.
> Subscriber-Only nodes are not considered in quorum

- product_docs/docs/biganimal/release/administering_cluster/01a_superset_access.mdx
The BigAnimal Superset role mapping page on docs needed a fix, as it was telling about users can manage the superset roles from the BA portal, which is incorrect. The admin doesn't assign the superset permissions, but just assigns the BA role, which is then mapped with the superset roles. 
Also, added a note about to SQL lab where the admin needs to assign the SQL lab permission on a per-database basis.
> docs(UPM-13774): Fix the superset role docs

- product_docs/docs/biganimal/release/getting_started/creating_a_cluster/index.mdx
- product_docs/docs/biganimal/release/using_cluster/01_postgres_access.mdx
Fixing these links: 
⚠️   https://github.com/EnterpriseDB/docs/blob/refs/heads/develop/product_docs/docs/biganimal/release/getting_started/creating_a_cluster/index.mdx?plain=1#L154
cannot find slug for iam_authentication_for_postgres in /biganimal/release/using_cluster/01_postgres_access/
⚠️⚠️  https://github.com/EnterpriseDB/docs/blob/refs/heads/develop/product_docs/docs/biganimal/release/using_cluster/01_postgres_access.mdx?plain=1#L91
cannot find topic for path: /biganimal/release/using_cluster/biganimal/latest/reference/cli/
> BigAnimal: fixing links

- product_docs/docs/pgd/4/bdr/camo.mdx
- product_docs/docs/pgd/4/bdr/group-commit.mdx
Correct grammatical errors
Correct when SET LOCAL bdr.commit_scope and be assigned.
Use boolean type spelling. Seems most consistent with BDR function signatures for Node Management and System Functions
Emphasize that Group Commit must be set before transaction has written data.
BDR-2805
> Minor corrections for CAMO and Group Commit chapters

- product_docs/docs/migration_toolkit/55/installing/index.mdx
- product_docs/docs/migration_toolkit/55/installing/install_on_mac.mdx
- product_docs/docs/migration_toolkit/55/installing/install_on_windows.mdx
- product_docs/docs/migration_toolkit/55/installing/installing_jdbc_driver.mdx
- product_docs/docs/migration_toolkit/55/installing/linux_ppc64le/index.mdx
- product_docs/docs/migration_toolkit/55/installing/linux_x86_64/index.mdx
Looks like a few paths in redirects were updated as part of #3359 - this caused redirect loops when attempting to navigate to these pages.
Fixes #3473
> Correct errantly corrected redirects in MTK install docs

- product_docs/docs/postgres_for_kubernetes/1/rel_notes/index.mdx
Forgot to add link to release notes index page; address this.
> Hotfix: Add index link to Postgres for Kubernetes 1.8.1 release notes

- product_docs/docs/edb_plus/40/02a_supported_platforms.mdx
- product_docs/docs/hadoop_data_adapter/2/02_requirements_overview.mdx
- product_docs/docs/mongo_data_adapter/5/02_requirements_overview.mdx
- product_docs/docs/mysql_data_adapter/2/02_requirements_overview.mdx
- product_docs/docs/ocl_connector/14.1.0.1/02_supported_platforms.mdx
- product_docs/docs/odbc_connector/13/02_requirements_overview.mdx
- product_docs/docs/pgbouncer/1.17/supported_platforms.mdx
- product_docs/docs/pgpool/4.3/supported_platforms.mdx
Removed EPAS 10 column from the products that have the EPAS compatibility table:
- EDB*Plus
- OCL Connector (didn't have the table but fixed the sentence that referenced v10
- ODBC Connector
- PgBouncer
- pgPool
- FDWs
> Removing EPAS 10 column from products that have an EPAS compatibility table

- product_docs/docs/eprs/6.2/03_installation/02_installing_from_cli.mdx
- product_docs/docs/eprs/6.2/03_installation/03_installing_rpm_package.mdx
- product_docs/docs/eprs/6.2/07_common_operations/10_replicating_postgres_partitioned_tables.mdx
- product_docs/docs/eprs/6.2/10_appendix/01_permitted_conf_and_permutations.mdx
- product_docs/docs/eprs/6.2/10_appendix/02_upgrading_to_xdb6_2/index.mdx
This path ([/resources/product-documentation](https://www.enterprisedb.com/resources/product-documentation)) hasn't been useful in ages and should probably be dropped at some point; if nothing else, it indicates docs that haven't been updated in a very long time.
Was reminded of its existence (and remaining references in the xDB docs) due to work currently ongoing to migrate redirects on the main website. Taking this opportunity to expunge them from docs, though references to this path may yet exist elsewhere.
Of particular note in this set of changes: there was a note in the upgrade index discussing upgrades from 5.x to 6.0, which referenced a topic that... Hasn't been accessible on the web for a good while. Removed that entire section, as I cannot think of a good alternative.
> update ancient links to /resources/product-documentation

- product_docs/docs/biganimal/release/free_trial/detail/create_a_cluster/create_cluster_cli.mdx
Probably fine that the reference CLI doc handwaves putting the executable on your path, but the goal with the free trial docs is to do a bit more handholding / require a bit less thinking on the part of the trial user. @VinnieGrack suggested including an example that would walk through putting the biganimal executable on the path,.
Resolves #3055
> Include complete example of biganimal CLI installation

- product_docs/docs/biganimal/release/free_trial/detail/create_a_cluster/create_cluster_cli.mdx
- product_docs/docs/biganimal/release/free_trial/detail/experiment/backup_and_restore.mdx
Use unprefixed calls (assumes `biganimal` is on the path) everywhere for consistency. Also avoid old, camelCase flags.
Fixes #3054
> Minor consistency for calls to the biganimal CLI in free trial docs

- product_docs/docs/biganimal/release/getting_started/02_connecting_to_your_cloud/connecting_aws.mdx
- product_docs/docs/biganimal/release/getting_started/02_connecting_to_your_cloud/connecting_azure.mdx
- product_docs/docs/biganimal/release/getting_started/02_connecting_to_your_cloud/index.mdx
- product_docs/docs/biganimal/release/reference/cli.mdx
- Reformatted the install instructions into a procedure to emphasize step for moving the executable into your executable search path.
- Since the install instructions now make this more obvious, removed the (./) command prefix in the Connecting your cloud topics. This makes the command usage consistent between the CLI topic and those topics and the topics in the Free Trial section.
> BigAnimal: making CLI commands consistent

- advocacy_docs/supported-open-source/postgresql/installer/05_uninstalling_postgresql.mdx
Added note about using a standard Mac uninstall process for users that didn't use our installer to install PG.
Fixes https://github.com/EnterpriseDB/docs/issues/2484
> PG: Mac uninstall

- product_docs/docs/biganimal/release/reference/api.mdx
Updated deprecation note including the link to the change log (this needs to be verified)
Changed v2 to v3 in paths
Changed the example in the Call the API section
[UPM-13711]: https://enterprisedb.atlassian.net/browse/UPM-13711?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> BigAnimal: API v3 updates

- product_docs/docs/biganimal/release/pricing_and_billing/index.mdx
As per discussion with Ben Anderson, management costs are _per region_ and not _per cluster_. Editing for accuracy.
"cluster" -> "region"
> Updating "cluster" to "region"

- product_docs/docs/eprs/6.2/03_installation/01_installing_with_stackbuilder.mdx
- product_docs/docs/eprs/6.2/03_installation/02_installing_from_cli.mdx
- product_docs/docs/eprs/6.2/03_installation/03_installing_rpm_package.mdx
- product_docs/docs/eprs/6.2/08_xdb_cli/03_xdb_cli_commands/02_print_version.mdx
- product_docs/docs/eprs/6.2/08_xdb_cli/03_xdb_cli_commands/03_print_xdb_server_version.mdx
Removed mentions of v6.1 and 6.0 from documentation. Left upgrading content about updating from these versions.
> Replication Server: removing mentions of v6.1 and 6.0 

- product_docs/docs/biganimal/release/overview/03a_region_support.mdx
- product_docs/docs/biganimal/release/overview/replication.mdx
Updated overview topics for regions and faraway replicas with the limitation for the South East Asia region.
Addressed https://enterprisedb.atlassian.net/browse/UPM-15019.
> BigAnimal: region limitations for faraway clusters

- product_docs/docs/biganimal/release/using_cluster/managing_replicas.mdx
As per new workflow, the password is not required to be entered during the Faraway Replica creation, I modified the statement however please get it reviewed for sanity check and change the verbiage so it is more appropriate. Same thing applies to Modify replica section, that should not let users modify the password. password change should be done on the primary.
> Update Password statement for replica creation & Modification

- product_docs/docs/pgd/4/bdr/ddl.mdx
As per discussion in BDR-2761 (https://enterprisedb.atlassian.net/browse/BDR-2761), we should document the restrictions on PASSWORD_PROFILE_FUNCTION.
> A note on PASSWORD_PROFILE_FUNCTION

- install_template/templates/products/edb-pgpool-ii-extensions/base.njk
- product_docs/docs/eprs/7/installing/linux_ppc64le/eprs_rhel_8.mdx
- product_docs/docs/eprs/7/installing/linux_x86_64/eprs_rhel_8.mdx
- product_docs/docs/pgpool/4.3/installing_extensions/linux_ppc64le/pgpoolext_rhel_8.mdx
- product_docs/docs/pgpool/4.3/installing_extensions/linux_ppc64le/pgpoolext_sles_12.mdx
- product_docs/docs/pgpool/4.3/installing_extensions/linux_ppc64le/pgpoolext_sles_15.mdx
- product_docs/docs/pgpool/4.3/installing_extensions/linux_x86_64/pgpoolext_centos_7.mdx
- product_docs/docs/pgpool/4.3/installing_extensions/linux_x86_64/pgpoolext_debian_10.mdx
- product_docs/docs/pgpool/4.3/installing_extensions/linux_x86_64/pgpoolext_debian_11.mdx
- product_docs/docs/pgpool/4.3/installing_extensions/linux_x86_64/pgpoolext_other_linux_8.mdx
- product_docs/docs/pgpool/4.3/installing_extensions/linux_x86_64/pgpoolext_rhel_7.mdx
- product_docs/docs/pgpool/4.3/installing_extensions/linux_x86_64/pgpoolext_rhel_8.mdx
- product_docs/docs/pgpool/4.3/installing_extensions/linux_x86_64/pgpoolext_sles_12.mdx
- product_docs/docs/pgpool/4.3/installing_extensions/linux_x86_64/pgpoolext_sles_15.mdx
- product_docs/docs/pgpool/4.3/installing_extensions/linux_x86_64/pgpoolext_ubuntu_18.mdx
- product_docs/docs/pgpool/4.3/installing_extensions/linux_x86_64/pgpoolext_ubuntu_20.mdx
- Removed codeready-builder instructions for EPRS - updating the instructions for codeready-builder was done in another PR (https://github.com/EnterpriseDB/docs/pull/3499), but the EPRS changes didn't get in at that time - adding them now
- Fixed package names for pgPool extensions - there is no hyphen between "as" and the as version number in the package names (see https://edb.slack.com/archives/CU5QEU5L7/p1673878714011569). Note that I verified that the change applies to all the OSs by checking Repos 2.0. I found that the pgPool Debian 11 packages weren't in the repo. I notified Hayee about that.
> Install instructions: fixed for EPRS and pgPool

- product_docs/docs/epas/14/epas_compat_sql/21_create_public_database_link.mdx
- Updated the path to a link that the PDF link checker indicated was broken, but I think we should either remove the paragraph that contains the link or change the destination to a topic that actually contains the information about service script (if there is one).
- Removed reference to Linux interactive installer.
> EPAS: link issue

- product_docs/docs/biganimal/release/using_cluster/06_analyze_with_superset.mdx
Changing the command to execute the database name change script as we added a shebang line in the script to execute the script without using `python3 <script.py>`. We just need to give the executable permissions to the script and need to call the script using `./`.
This PR is to make these changes on docs as the same has been updated in the cloud-utilities repo.
> chore(UPM-12468): Docs changes for superset PGD dashboard

- product_docs/docs/biganimal/release/reference/cli/using_features.mdx
- product_docs/docs/biganimal/release/using_cluster/01_postgres_access.mdx
- product_docs/docs/biganimal/release/using_cluster/managing_replicas.mdx
Instead of hiding CLI links under See also sections, created CLI headings in feature topics
Included CLI in the headings on the CLI use case topics so the link labels make more sense
> BigAnimal: improving CLI links and headings

- product_docs/docs/biganimal/release/pricing_and_billing/index.mdx
A note: The "Contact Sales for additional information regarding pricing." line may not be necessary if pricing is literally as simple as: "multiply the number of vCPUs per instance by the number of replicas configured".
Pricing should accommodate both High Availability and Extreme High Availability use cases.
> Make language inclusive of EHA

- product_docs/docs/epas/14/epas_compat_bip_guide/03_built-in_packages/04_dbms_crypto/index.mdx
Removed single variant HASH function from the docs as per the comment on DF-313
> EPAS 14 - DBMS_CRYPTO correction as per DF-313

- product_docs/docs/pem/9/pem_upgrade/upgrading_pem_installation/upgrading_pem_installation_linux_rpm.mdx
The previous link got the reader to the root of the PEM docs, not to the intended destination, which is https://www.enterprisedb.com/docs/pem/latest/installing_pem_server/pem_server_inst_linux/configuring_the_pem_server_on_linux/
Link changed from ../.. to https://www.enterprisedb.com/docs/pem/latest/installing_pem_server/pem_server_inst_linux/configuring_the_pem_server_on_linux/, in a location that had the text "Configuring the PEM server on Linux platforms"
Note: I don't know why the last line is shown as edited. I edited one line of the link in the Github web interface, now the diff contains two changes, but I didn't intend for the last one and I don't know how to prevent it in this PR.
> Fix link that points to the configuration page

- product_docs/docs/migration_portal/4/01_mp_release_notes/mp_4.3_rel_notes.mdx
- product_docs/docs/migration_portal/4/01_mp_release_notes/mp_4.4_rel_notes.mdx
Added a section to notify users that Migration Portal support for EPAS 11 as a target database is planned to be removed in May;
> Added End of support notice for EPAS 11

- product_docs/docs/biganimal/release/using_cluster/01_postgres_access.mdx
Alert user for not using ALTER SYSTEM` query to change the configuration of the PostgreSQL instances in an imperative way.
> To add the warning for User

- product_docs/docs/tpa/23/INSTALL.mdx
- product_docs/docs/tpa/23/reference/barman.mdx
This can probably be removed in a couple of months, but for now there's a chance that someone with a trial token will be unable to access the postgres_distributed repo if the token was generated prior to (some time in the last week).
> Add warning to TPA install for folks with old tokens

- product_docs/docs/eprs/7/installing/installation_details.mdx
- product_docs/docs/eprs/7/installing/windows.mdx
I edited the EPRS Windows install page so it could potentially be used as a model for other Windows installation instructions.
The install instructions reference a Details page. I made some modest edits to the Details page because it did not seem to present information in any logical way. (That page could still be improved.)
> Edits to EPRS Windows installation and details page

- product_docs/docs/biganimal/release/getting_started/02_azure_market_setup.mdx
- product_docs/docs/biganimal/release/getting_started/identity_provider/index.mdx
1. BigAnimal Azure Marketplace onboarding documention deletes the text of user must be Global Administrator or Privileged Role Administrator. The latest feature in production system does not require the user own these role anymore. 
2. `Add a tile` in *Setup Identity Provider* is one independent topic, it does not belong to *## Manage roles for added users* . So I adjust the `### Add a tile` to `## Add a tile`
> update setup azure marketplace process doc

- product_docs/docs/pgd/5/quick_start_docker.mdx
Perhaps it's better not to use an AWS region name for a location in a Docker deployment
This might cause confusion. 
Changed the TPA deployment location from "eu-west-1" (AWS region name) to a neutral "dc1" (for data centre 1).
Also fixed a typo.
> Fixed confusing location name

- advocacy_docs/pg_extensions/advanced_storage_pack/index.mdx
We use Postgres when referring to our set of Postgres distributions: PG, EPAS, and PGE
> Advanced Storage pack: changing to generic Postgres terminology

- src/components/index.js
- src/components/main-content.js
- src/components/timed-banner.js
Add a banner to docs pages (above the search bar) with a CTA and registration link for PG Vision. Will disappear after May 2nd, 2023.
Fixes #3763
> Add pgvision banner to Docs

- product_docs/docs/tpa/23/INSTALL.mdx
Rewrite the (still temporary) note in TPA Installation topic to stand a chance of being useful.
Big problem: the curl command as-written will never produce an explicit error (we tell it to squelch errors!). A token with insufficient access or a mistyped token will fail silently. ...However, a good token will *succeed* noisily!
Other problem: old tokens are not the only issue here. Depending on subscription level, current customers may also encounter (silent) failures. 
Changes attempt to address both of these issues and provide some direction for those encountering them.
> Update note on troubleshooting repo access to reflect reality

- product_docs/docs/eprs/6.2/07_common_operations/11_using_ssl_connections.mdx
Added note about default paths when using Linux interactive installer to 6.2 doc
> EPRS: 6.2 SSL default path note

- product_docs/docs/pgd/4/harp/03_installation.mdx
- product_docs/docs/pgd/4/harp/04_configuration.mdx
On what information we have, have moved builtin proxy to default, removed experimental warnings, removed requirement for pgbouncer binaries from docs.
BUT: Have kept references to pgbouncer as it does appear this is only a default change, so this will need PM/Tech review for correctness.
> Moved pgbouncer refs assuming builtin is default

- product_docs/docs/epas/15/epas_compat_ora_dev_guide/02_about_the_examples_used_in_this_guide.mdx
Brought paras together and used end of line double space to introduce line breaks in right place.
> Remove sql backticks leaking into code blocks

- product_docs/docs/pgd/4/rel_notes/pgd_4.3.0_rel_notes.mdx
- product_docs/docs/pgd/5/rel_notes/index.mdx
- product_docs/docs/pgd/5/rel_notes/pgd_5.1.0_rel_notes.mdx
- Prepare BDR 5.1.0 release file
- Add BDR-2534 to BDR 5.1.0 release notes
- Add BDR-2534 to BDR 4.3.0 release notes
Related BDR PRs:
https://github.com/EnterpriseDB/bdr/pull/1842
https://github.com/EnterpriseDB/bdr/pull/1841
https://github.com/EnterpriseDB/bdr/pull/1840
> Prepare BDR 5.1.0 release and add BDR-2534

- src/styles/_dark.scss
We were missing a couple of admonition types in dark mode, causing severe retina burns.
Also, we should allow our diversity of icons to... shine through
> Support admonition icons, all types in dark mode

- product_docs/docs/pem/9/registering_agent.mdx
- product_docs/docs/pem/9/troubleshooting.mdx
- product_docs/docs/pem/9/troubleshooting_agent.mdx
Added the following sub-heading in the "Registering a PEM agent"- "Modifying the pemagent service file to update agent configuration file path" for steps to update the service file
> PEM-3896-Added content for changing agent.cfg file path in pemagent service file

- install_template/templates/products/migration-toolkit/base.njk
- install_template/templates/products/replication-server/base.njk
- product_docs/docs/eprs/7/10_appendix/02_resolving_problems/04_troubleshooting_areas.mdx
- product_docs/docs/eprs/7/installing/linux_ppc64le/eprs_rhel_8.mdx
- product_docs/docs/eprs/7/installing/linux_ppc64le/eprs_sles_12.mdx
- product_docs/docs/eprs/7/installing/linux_ppc64le/eprs_sles_15.mdx
- product_docs/docs/eprs/7/installing/linux_x86_64/eprs_centos_7.mdx
- product_docs/docs/eprs/7/installing/linux_x86_64/eprs_debian_10.mdx
- product_docs/docs/eprs/7/installing/linux_x86_64/eprs_debian_11.mdx
- product_docs/docs/eprs/7/installing/linux_x86_64/eprs_other_linux_8.mdx
- product_docs/docs/eprs/7/installing/linux_x86_64/eprs_rhel_7.mdx
- product_docs/docs/eprs/7/installing/linux_x86_64/eprs_rhel_8.mdx
- product_docs/docs/eprs/7/installing/linux_x86_64/eprs_sles_12.mdx
- product_docs/docs/eprs/7/installing/linux_x86_64/eprs_sles_15.mdx
- product_docs/docs/eprs/7/installing/linux_x86_64/eprs_ubuntu_18.mdx
- product_docs/docs/eprs/7/installing/linux_x86_64/eprs_ubuntu_20.mdx
- product_docs/docs/migration_toolkit/55/installing/linux_ppc64le/mtk_rhel_8.mdx
- product_docs/docs/migration_toolkit/55/installing/linux_ppc64le/mtk_sles_12.mdx
- product_docs/docs/migration_toolkit/55/installing/linux_ppc64le/mtk_sles_15.mdx
- product_docs/docs/migration_toolkit/55/installing/linux_x86_64/mtk_centos_7.mdx
- product_docs/docs/migration_toolkit/55/installing/linux_x86_64/mtk_debian_10.mdx
- product_docs/docs/migration_toolkit/55/installing/linux_x86_64/mtk_debian_11.mdx
- product_docs/docs/migration_toolkit/55/installing/linux_x86_64/mtk_other_linux_8.mdx
- product_docs/docs/migration_toolkit/55/installing/linux_x86_64/mtk_rhel_7.mdx
- product_docs/docs/migration_toolkit/55/installing/linux_x86_64/mtk_rhel_8.mdx
- product_docs/docs/migration_toolkit/55/installing/linux_x86_64/mtk_sles_12.mdx
- product_docs/docs/migration_toolkit/55/installing/linux_x86_64/mtk_sles_15.mdx
- product_docs/docs/migration_toolkit/55/installing/linux_x86_64/mtk_ubuntu_18.mdx
- product_docs/docs/migration_toolkit/55/installing/linux_x86_64/mtk_ubuntu_20.mdx
In addition to removing the Java prereq bullet, I moved the note about uninstalling Java in EPRS to the troubleshooting topic.
> Removed Java requirement from install instructions 

- product_docs/docs/biganimal/release/using_cluster/05_monitoring_and_logging/metrics/index.mdx
Now we only have cnp_backends_total but not cnp_backends_n_backend
> correct name of cnp_backends_total

- advocacy_docs/pg_extensions/index.mdx
- product_docs/docs/pem/8/installing_pem_agent/installing_on_linux/x86_amd64/index.mdx
Oracle compatible (EPAS) clusters now support autocluster, refdata, and edb-pg-tuner EDB extensions.
See https://docs.google.com/spreadsheets/d/1GXzzVYT6CULGgGcyp0VtBfOtbxuWxkOU2pRYW42W4pM/edit#gid=1884264748
> Extensions topic update for Q1 BigAnimal extensions support

- install_template/templates/products/edb-postgres-extended-server/base.njk
- product_docs/docs/pge/15/installing/linux_x86_64/pge_centos_7.mdx
- product_docs/docs/pge/15/installing/linux_x86_64/pge_other_linux_8.mdx
- product_docs/docs/pge/15/installing/linux_x86_64/pge_rhel_7.mdx
- product_docs/docs/pge/15/installing/linux_x86_64/pge_rhel_8.mdx
- product_docs/docs/pge/15/installing/linux_x86_64/pge_ubuntu_18.mdx
- product_docs/docs/pge/15/installing/linux_x86_64/pge_ubuntu_20.mdx
- product_docs/docs/pge/15/installing/linux_x86_64/pge_ubuntu_22.mdx
Using syntax from Josh, I made this elegant fix to the problem of example text that explains the deploy command varying between platforms.
> Fix for example deploy text for EPES (PGE)

- product_docs/docs/pgd/5/upgrades/index.mdx
BDR-3002
Provide more detailed instructions on how to upgrade a CAMO enabled cluster from BDR 3.7 or 4.x to BDR 5.0.
> Provide more details on how to upgrade a CAMO enabled cluster.

- product_docs/docs/pgd/3.7/harp/01_release_notes/harp2.2.2_rel_notes.mdx
- product_docs/docs/pgd/3.7/harp/01_release_notes/index.mdx
- product_docs/docs/pgd/4/rel_notes/index.mdx
- product_docs/docs/pgd/4/rel_notes/pgd_4.3.0_rel_notes.mdx
- product_docs/docs/pgd/5/rel_notes/pgd_5.0.1_rel_notes.mdx
* Add entry for HARP 2.2.2 release notes for PGD 3.7
* Add the release version HARP 2.2.2 to index page for PGD 4 along with a footnote to upgrade to this version for all installations using HARP 2.2.1
TBH the entry for PGD 4 still looks odd to me. We are mentioning HARP 2.2.2 to be released as part of PGD 4.3.0 which in fact is not the case. Ideally I would have preferred to have any entry for this under PGD 4.3.1 with release date as `30 March 2023` and then the footnote would have made more sense. The detailed rel_notes for PGD 4.3.1 would contain entry only for HARP 2.2.2.
The upcoming release for PGD in May 2023 would then become 4.3.2. I am not sure about the challenges involved with this change in PGD release schedule so my suggestion may not be a viable option here.
> BDR-3342 - Add release note entry for HARP dependencies upgrade

- product_docs/docs/pgd/5/backup.mdx
Small changes to statement of only Postges Extended having feature, and separated from statement that barman does not automatically create a recovery file.
> Fixed the note to be precise on availability

- product_docs/docs/epas/12/epas_rel_notes/19_epas12.1.2_rel_notes.mdx
Pipes were used inline with backquotes. 
Now escaped.
> Fix Markdown in table

- advocacy_docs/pg_extensions/pg_failover_slots/installing.mdx
- Format for package name had underscore instead of dash
- Example for RHEL was missing major verison
See: https://edb.slack.com/archives/CU5QEU5L7/p1681834353252679
> Fix package name and example for failover slots extension

- product_docs/docs/efm/4/04_configuring_efm/05_using_vip_addresses.mdx
Adding a note that the important part about pinging the VIP is the exit code of the ping command. This comes from a customer replacing /bin/ping with something else that always exited with zero even though the human-readable output. In that case EFM always thought the address being pinged was reachable, breaking failover when using a VIP.
> Add information about how efm interprets ping

- product_docs/docs/biganimal/release/using_cluster/04_backup_and_restore.mdx
Fixed link and typo in https://www.enterprisedb.com/docs/biganimal/latest/using_cluster/04_backup_and_restore/#perform-an-extreme-high-availability-cluster-restore
> BigAnimal: Fixed link and typo in Restoring an EHA cluster

- install_template/templates/products/failover-manager/base.njk
- product_docs/docs/efm/4/installing/linux_ppc64le/efm_rhel_8.mdx
- product_docs/docs/efm/4/installing/linux_ppc64le/efm_sles_12.mdx
- product_docs/docs/efm/4/installing/linux_ppc64le/efm_sles_15.mdx
- product_docs/docs/efm/4/installing/linux_x86_64/efm_centos_7.mdx
- product_docs/docs/efm/4/installing/linux_x86_64/efm_debian_10.mdx
- product_docs/docs/efm/4/installing/linux_x86_64/efm_debian_11.mdx
- product_docs/docs/efm/4/installing/linux_x86_64/efm_other_linux_8.mdx
- product_docs/docs/efm/4/installing/linux_x86_64/efm_rhel_7.mdx
- product_docs/docs/efm/4/installing/linux_x86_64/efm_rhel_8.mdx
- product_docs/docs/efm/4/installing/linux_x86_64/efm_sles_12.mdx
- product_docs/docs/efm/4/installing/linux_x86_64/efm_sles_15.mdx
- product_docs/docs/efm/4/installing/linux_x86_64/efm_ubuntu_18.mdx
- product_docs/docs/efm/4/installing/linux_x86_64/efm_ubuntu_20.mdx
- product_docs/docs/efm/4/installing/linux_x86_64/efm_ubuntu_22.mdx
Clarified that both PG and EPAS are supported and that you don't need to install the db for witness nodes
See related discussion https://edb.slack.com/archives/C016SDV9HLL/p1682341493767469
> Failover Manager: install template changes

- product_docs/docs/pem/9/in_app_help.mdx
- product_docs/docs/pem/9/registering_agent.mdx
Refer: https://github.com/EnterpriseDB/docs/pull/3733
> PEM - Added user specific examples

- product_docs/docs/pgd/5/tpa.mdx
Removing --subnet-patterns from doc as it apparently no longer exists.
> Removing --subnet-patterns from doc

- product_docs/docs/pgd/5/overview/index.mdx
- product_docs/docs/pgd/5/terminology.mdx
Added write leader to terminology (mention shadow nodes but only in context of there being a write leader), added links to overview and mention write leader term in body of overview on connection management.
> Changes to introduce write leader

- product_docs/docs/mysql_data_adapter/2/02_requirements_overview.mdx
Added "Linux" qualifier - MySQL FDW isn't supported on Windows or MacOS
> MySQL FDW: correction to supported platforms

- product_docs/docs/tde/15/key_stores.mdx
Neglected to convert the ascii codes in code blocks when moving content over from the DocBook source
> TDE: replacing ascii code with the correct characters

- gatsby-browser.js
- gatsby-config.js
- product_docs/docs/pgd/5/cli/command_ref/index.mdx
- product_docs/docs/pgd/5/cli/index.mdx
- product_docs/docs/pgd/5/consistency/index.mdx
- product_docs/docs/pgd/5/durability/index.mdx
- product_docs/docs/pgd/5/monitoring/index.mdx
- product_docs/docs/pgd/5/quickstart/index.mdx
- product_docs/docs/pgd/5/rel_notes/index.mdx
- product_docs/docs/pgd/5/routing/index.mdx
- product_docs/docs/pgd/5/upgrades/index.mdx
- src/components/side-navigation.js
- src/components/table-of-contents.js
- src/components/tree-node.js
- src/constants/gatsby-utils.js
- src/styles/_docs.scss
- src/styles/_overrides.scss
Build #4024 into the system as follows:
- record number of children when building nav tree
- apply CSS class to nav links where childCount > 0
- CSS class renders arrow using Bootstrap's weird-ass border technique
Result: arrows next to expandable items in list.
TODO: figure out if accessibility can be improved here (ARIA role?)
Partially address https://github.com/EnterpriseDB/docs/issues/4120 as follows:
- fix height of right nav bar, enable scrollbar when content exceeds
- indicate currently-selected section via CSS class
- on navigation, ensure currently selected items in both left and right nav
are scrolled into view if not currently visible
- using gatsby hook, record current scroll state for left/right navs,
restore this state when navigating back
> Nav bar usability enhancements

- static/_redirects
Ensure that EOL'd version paths redirect to the root of latest, not a 404 or matching path
> Update _redirects for EFM EOL'd versions

- advocacy_docs/supported-open-source/pgbackrest/06-use_case_1.mdx
- advocacy_docs/supported-open-source/pgbackrest/07-use_case_2.mdx
- advocacy_docs/supported-open-source/pgbackrest/99-faq.mdx
- advocacy_docs/supported-open-source/pgbackrest/index.mdx
pgBackRest 2.46 was released (and the community packages provided).
SFTP support for repository storage has also been introduced in this release.
> pgBackRest 2.46

- product_docs/docs/pgd/3.7/harp/08_harpctl.mdx
- product_docs/docs/pgd/4/harp/08_harpctl.mdx
Remove the --dcs flag for harpctl from docs. 
The flag support has been removed as part of HNG-388
The actual change is on line#35. Please ignore the whitespace changes that my IDE added automatically. This isn't visible when I see the diff in my IDE
> Remove the --dcs flag for harpctl. The flag support has been removed as part of HNG-388

- advocacy_docs/pg_extensions/advanced_storage_pack/index.mdx
- advocacy_docs/pg_extensions/ldap_sync/index.mdx
- advocacy_docs/pg_extensions/pg_failover_slots/index.mdx
- advocacy_docs/pg_extensions/pg_tuner/index.mdx
- src/constants/products.js
To fully enable search for these, we need two things:
1. Set a product name in directory defaults for each extension (this associates each extension's content with the product name and enables the facet in advanced search)
2. Add these names to products.js (this enables selecting the name from the search dropdown)
> Set products for search within extensions

- product_docs/docs/epas/15/epas_guide/03_database_administration/05_edb_audit_logging/01_audit_logging_configuration_parameters.mdx
01_audit_logging_configuration_parameters.mdx
Unnecessary indentation of the bulleted lists messes up inline formatting.
Bulleted lists for the `edb_audit_archiver_compress_time_limit` and `edb_audit_archiver_compress_size_limit` values were incorrectly formatted.
> Fix formatting of lists

- product_docs/docs/pem/9/monitoring_failover_manager.mdx
Add workaround for case where the cluster properties file is not in the home directory of the efm user.
> Add workaround for EFM monitoring

- product_docs/docs/pgd/5/quickstart/index.mdx
@djw-m even though the short name suggests otherwise, EDB is part of the product name we should be using in the docs
@ebgitelman can you look for instances of the product name missing EDB in your copyediting passes? Also, CLI should be uppercase. We need to search the docs for Cli and cli and fix the case.
> PGD: including "EDB" in product name

- product_docs/docs/pgd/5/rel_notes/pgd_5.1.0_rel_notes.mdx
Smol fix to 5.0 relnote admonitions in anticipation of fixing the CSP issue.
> Fix admonitions

- product_docs/docs/biganimal/release/pricing_and_billing/index.mdx
Per Slack message, Natalia says we don't need the 2nd PostgreSQL line in the pricing table
> BigAnimal: fix to pricing

- product_docs/docs/tpa/23/tpaexec-configure.mdx
Fix the broken PDF links in the TPA docs.
Flipped the heading back. 
This will fix the two pages that link here.
There may have been contemporaneous edits on this downstream build so will need to validate later on.
This should resolve #4295
> Fix the Flavour

- advocacy_docs/pg_extensions/advanced_storage_pack/installing.mdx
- ASP packages are only available in version 12 onwards. Version 11 was never a possibility for ASP.
- EL 9 is now released, so added to the distro list
- Ubuntu is the only Debian derivative that we support, so mention it instead of letting customers think any other derivative is included
- The 1 and -1 were dropped from the package names a while back, and the packages have been released without them, with appropriate upgrade paths
- Newer versions than 1.0.0 have been out as well, so the installation instructions are not helping anyone by mentioning that past version explicitly
- Also fixing the last example that intends to install for EPAS, but shows the instruction for PostgreSQL
> Update installation instructions for ASP

- product_docs/docs/pgd/3.7/harp/01_release_notes/harp2.3.0_rel_notes.mdx
- product_docs/docs/pgd/3.7/harp/01_release_notes/index.mdx
- product_docs/docs/pgd/4/rel_notes/index.mdx
- product_docs/docs/pgd/4/rel_notes/pgd_4.3.1_rel_notes.mdx
Add release notes for HARP 2.3.0.
The notes have been added for BDR 3.7 as well as BDR 4.x.
More details about the fixes in this release are mentioned in [BDR-3735](https://enterprisedb.atlassian.net/browse/BDR-3735)
Please do not merge this before the actual release.
[BDR-3735]: https://enterprisedb.atlassian.net/browse/BDR-3735?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> BDR-3735 - Add release notes for HARP 2.3.0

- product_docs/docs/tpa/23/rel_notes/index.mdx
- product_docs/docs/tpa/23/rel_notes/tpa_23.17_rel_notes.mdx
- product_docs/docs/tpa/23/rel_notes/tpa_23.18_rel_notes.mdx
- product_docs/docs/tpa/23/rel_notes/tpa_23.19_rel_notes.mdx
Add release notes for TPA 23.19
Correct version numbers in previous RNs
A summarized version of detailed 23.19 release notes for the EnterpriseDB docs site.
> Add release notes for TPA 23.19

- product_docs/docs/biganimal/release/getting_started/02_connecting_to_your_cloud/connecting_aws.mdx
Missed updating the CLI commands in the Connecting to your AWS Cloud.
Kyle pointed out the miss in Slack: https://edb.slack.com/archives/CU5QEU5L7/p1689358429868599
> BigAnimal: update CLI commands for connecting to AWS

- product_docs/docs/pgd/4/bdr/sequences.mdx
- product_docs/docs/pgd/5/sequences.mdx
Just some definitions from absolute 19 digits to up to 19 digits.
> fix definition of max digits of a snowflake id

- src/pages/index.js
After the recent addition of new partner docs, the Migration block got pushed to the bottom of the second column. Did some rearranging to get it back to the top right position.
> Home page: moved Migration block back to the top

- product_docs/docs/epas/13/epas_rel_notes/epas13_11_15_rel_notes.mdx
Just a version number and a link
> Fix EPAS 13.11 for release merged version and relnote link

- product_docs/docs/pgd/4/rel_notes/index.mdx
Tidied up the links and did some archeology to identify what the correct version numbers were at the bottom end of the list.
Removed the links on the 22.x series for now.
> Internalised links - fixed old TPA version numbers

- product_docs/docs/eprs/7/05_smr_operation/01_prerequisites/05_preparing_sub_database.mdx
super user permissions not required for a Subscription database user
https://enterprisedb.atlassian.net/browse/XDB-1753
Fixes https://github.com/EnterpriseDB/docs/issues/2702
> Replication Server: super user permissions not required 

- README.md
Found I had been skipping a step because the instructions gave a non-existent command. Looked into it and found you can lose a step because the setup script also installs all the packages. This update reflects that.
> Update README.md - fix develop instructions

- product_docs/docs/pgd/5/monitoring/otel.mdx
Added link in OTEL for Consensus metrics directing reader to SQL monitoring info on same metrics.
At suggestion of @irionr
> Added link in OTEL to SQL info

- product_docs/docs/pgd/5/routing/installing_proxy.mdx
Links inside routing pointed at index, but a reference to [index#configuration] is misread and comes out as index/#configuration which fails to resolve. Only two links in the codebase like this, so changed here to [../routing#configuration] which does resolve to the index page.
May need to raise issue as bug or as wider discussion of why don't we have a more classical folder/files hierarchy. 
Should close #4596.
> dirty links change to make link to index work

- product_docs/docs/biganimal/release/using_cluster/05_monitoring_and_logging/metrics/index.mdx
The `bdr_raft_mon` metric is being retired for performance and stability reasons. Update the documentation accordingly.
Includes a few other minor docs fixes for metrics docs.
> docs(UPM-23204): Remove bdr_raft_mon metrics

- advocacy_docs/security/advisories/cve2023xxxxx1.mdx
- advocacy_docs/security/advisories/cve2023xxxxx2.mdx
- advocacy_docs/security/advisories/cve2023xxxxx3.mdx
- advocacy_docs/security/advisories/cve2023xxxxx4.mdx
- advocacy_docs/security/advisories/cve2023xxxxx5.mdx
- advocacy_docs/security/advisories/cve2023xxxxx6.mdx
- advocacy_docs/security/advisories/cve2023xxxxx7.mdx
- advocacy_docs/security/advisories/cve2023xxxxx8.mdx
- advocacy_docs/security/advisories/index.mdx
- advocacy_docs/security/index.mdx
Fix up on all the version numbers to refer to 13.12.17 not 16 *AND* fixed in all indexes and removed the place holder values in the summary for cve2023xxxxx6
> Security version number fixes

- product_docs/docs/epas/15/application_programming/12_debugger/configuring_debugger.mdx
- product_docs/docs/epas/15/application_programming/ecpgplus_guide/installing_ecpgplus.mdx
- product_docs/docs/epas/15/database_administration/14_edb_clone_schema/setting_up_edb_clone_schema.mdx
- product_docs/docs/epas/15/epas_security_guide/02_protecting_against_sql_injection_attacks/02_configuring_sql_protect.mdx
- product_docs/docs/epas/15/epas_security_guide/04_sslutils.mdx
- product_docs/docs/epas/15/epas_security_guide/tde_feature.mdx
- product_docs/docs/epas/15/fundamentals/sql_fundamentals/02_conventions.mdx
- product_docs/docs/epas/15/fundamentals/sql_fundamentals/03_examples_used.mdx
- product_docs/docs/epas/15/installing/uninstalling/linux_uninstall.mdx
- product_docs/docs/epas/15/installing/uninstalling/windows_uninstall.mdx
- product_docs/docs/epas/15/installing/windows/installing_advanced_server_with_the_interactive_installer/index.mdx
- product_docs/docs/epas/15/installing/windows/installing_advanced_server_with_the_interactive_installer/invoking_the_graphical_installer_from_the_command_line/index.mdx
- product_docs/docs/epas/15/installing/windows/installing_advanced_server_with_the_interactive_installer/invoking_the_graphical_installer_from_the_command_line/performing_an_installation_with_limited_privileges.mdx
- product_docs/docs/epas/15/installing/windows/installing_advanced_server_with_the_interactive_installer/invoking_the_graphical_installer_from_the_command_line/performing_an_unattended_installation.mdx
- product_docs/docs/epas/15/installing/windows/installing_advanced_server_with_the_interactive_installer/invoking_the_graphical_installer_from_the_command_line/reference_command_line_options.mdx
- product_docs/docs/epas/15/installing/windows/installing_advanced_server_with_the_interactive_installer/performing_a_graphical_installation_on_windows.mdx
- product_docs/docs/epas/15/installing/windows/installing_advanced_server_with_the_interactive_installer/using_stackbuilder_plus.mdx
- product_docs/docs/epas/15/installing/windows/managing_an_advanced_server_installation/configuring_epas.mdx
- product_docs/docs/epas/15/managing_performance/02_index_advisor/02_index_advisor_configuration.mdx
- product_docs/docs/epas/15/reference/database_administrator_reference/01_index_advisor_components.mdx
Part I of install topics transferred from outdated branch.
Also made xx nomenclature consistent throughout the doc, as it was using three different styles of wording.
> Edits to installs and consistent nomenclature for versions

- product_docs/docs/pgd/5/reference/nodes-management-interfaces.mdx
Removed loose indents in bdr.alter_node_group_config originally reported in BDR4 #3016 
This completes the tab tidy up
> Fixed indents carried over from bdr4 docs

- .github/workflows/deploy-develop.yml
- .github/workflows/deploy-draft.yml
- .github/workflows/deploy-main.yml
- src/constants/gatsby-utils.js
Aim to speed up deployment via two angles:
1. Use faster build environments: 16 cores is better than 2
2. Allow fewer file changes on builds by eliminating client-side redirects (and the huge array shared by every single page that changed every time a new file was added / redirect was changed)
> Faster builds: bigger machines, smaller tables

- docs/agreements/product-version-fork.md
Wrote up a short process for doing long-lived "next product version docs" branches without quite so many headaches: https://github.com/EnterpriseDB/docs/blob/process/josh/product-fork-process-proposal/docs/agreements/product-version-fork.md
Would appreciate your review, @drothery-edb and @nidhibhammar - with your approval, I'd like to try this first with the EPAS 15 branch (work on which is already underway) and also the PGD 5 branch (yet to be created).
> Outline strategy for forking product docs without losing history

- product_docs/docs/epas/11/installing/linux_install_details/component_locations.mdx
- product_docs/docs/epas/12/installing/linux_install_details/component_locations.mdx
- product_docs/docs/epas/13/installing/linux_install_details/component_locations.mdx
- product_docs/docs/epas/14/installing/linux_install_details/component_locations.mdx
- product_docs/docs/epas/15/installing/linux_install_details/component_locations.mdx
Removed Log rotation file and Sudo configuration file and updated Logs and Lock files as per [DB-2428](https://enterprisedb.atlassian.net/browse/DB-2428)
[DB-2428]: https://enterprisedb.atlassian.net/browse/DB-2428?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> EPAS 15 - Log file fix as per DB-2428

- gatsby-node.js
- src/components/feedback-dropdown.js
- src/components/footer.js
- src/components/layout.js
- src/components/left-nav.js
- src/components/link.js
- src/components/prev-next.js
- src/constants/gatsby-utils.js
- src/constants/utils.js
- src/templates/doc.js
- src/templates/learn-doc.js
Key to accomplishing this is reducing the number of files changed from build-to-build to as close as possible to those corresponding to the set of pages actually *changed*. To this end, 
- Eliminates most client-side redirects by actually rewriting current version links to /latest/ instead of depending on a redirect to handle this (a server-side redirect is still created so that versioned URLs will work in production, but there shouldn't be any links *within* docs that use a versioned path to a latest-version page). The goal here is to eliminate the client-side redirects table, which is carried along with every page's data and will tend to change every time a file is added / removed / renamed - thus adding a single file could result in *every* page being re-deployed.
- Stop using the last …
> Speed up Netlify deploys

- product_docs/docs/pgd/4/rel_notes/index.mdx
Some dates were missed on the grand update because for some reason June and July didn't need to be 3 characters like every other month.
> Clean up last bad dates (four letter months!)

- product_docs/docs/postgres_for_kubernetes/1/kubectl-plugin.mdx
Update docs so it is clear users need to call the `kubectl cnp psql` command explicitly with a user on OpenShift due to the fact that OpenShift randomly assigns UID to users in containers.
Added a Note to clarify the above under the block of text about the `kubectl cnp psql` command.
> Explicitly call out psql -U for OpenShift

- product_docs/docs/postgres_for_kubernetes/1/kubectl-plugin.mdx
Don't know if this is easy to do, as this would make these docs diverge from the upstream ones, but referencing Debian here (`psql` output showing the Postgres cluster is running on Debian images), is quite confusing, and should probably be avoided.
> Removing references to clusters running on Debian.

- product_docs/docs/eprs/7/01_introduction/04_permitted_conf_and_permutations.mdx
Changed occurrence of "Microsoft SQL service" to "Microsoft SQL Server"
> Correct SQL Server related typo

- product_docs/docs/biganimal/release/getting_started/creating_a_cluster/index.mdx
- product_docs/docs/biganimal/release/knowledge_base.mdx
- product_docs/docs/biganimal/release/overview/extensions_tools.mdx
- product_docs/docs/biganimal/release/overview/poolers.mdx
moving away from "self-hosted" terminology for poolers deployed and managed separate from BigAnimal
> BigAnimal: pooler language updates

- product_docs/docs/pem/8/considerations/pem_pgbouncer/configuring_pgBouncer.mdx
- product_docs/docs/pem/9/considerations/pem_pgbouncer/configuring_pgBouncer.mdx
- product_docs/docs/pem/9/considerations/pem_pgbouncer/configuring_the_pem_agent.mdx
- product_docs/docs/pem/9/considerations/pem_pgbouncer/index.mdx
- product_docs/docs/pem/9/considerations/pem_pgbouncer/pem_server_pem_agent_connection_management_mechanism.mdx
- product_docs/docs/pem/9/considerations/pem_pgbouncer/preparing_the_pem_database_server.mdx
Online help section was eliminated from the PEM 9 published docs - redirects should go there.
> Move online help redirects to PEM 9

- product_docs/docs/pgd/5/deployments.mdx
Added table to choosing deployments section.
> Deployment update with table

- product_docs/docs/biganimal/release/getting_started/creating_a_cluster/creating_an_eha_cluster.mdx
- product_docs/docs/biganimal/release/overview/02_high_availability.mdx
- product_docs/docs/biganimal/release/pricing_and_billing/index.mdx
When support for PGE for PGD clusters is released (most likely 9/7 but possibly 8/30), add other changes from https://github.com/EnterpriseDB/docs/pull/4618/commits/403b2e7fef829ca22f4c61f7bcea91b866d4b8a3#diff-6ed5a78a342471d0ce3af49ee9a8fcac5fab4ecc035a1480b9758feb7a174fb2 back in.
The changes in [this commit](https://github.com/EnterpriseDB/docs/pull/4618/commits/6cb995bef3c5280b900ec562e373c15ade65af15) should be reverted in this PR.
> BigAnimal: added back support for PGE for PGD

- product_docs/docs/pgd/4/harp/06_harp_manager.mdx
`harpctl unmanage node <node_name>` doesn't exist. If you try that, the command will fail.
Per [documentation](https://www.enterprisedb.com/docs/pgd/latest/harp/08_harpctl/#harpctl-unmanage), `harpctl unmanage` works only for `cluster` at the moment.
> Remove suggestion about harpctl unmanage node

- product_docs/docs/epas/15/reference/sql_reference/02_data_types/02_character_types.mdx
> EPAS: Fix note formatting

- product_docs/docs/epas/16/reference/oracle_compatibility_reference/epas_compat_bip_guide/03_built-in_packages/18_dbms_utility.mdx
Added EXPAND_SQL_TEXT to DBMS_UTILITY as per [DB-2310](https://enterprisedb.atlassian.net/browse/DB-2310)
[DB-2310]: https://enterprisedb.atlassian.net/browse/DB-2310?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> EPAS: DB-2310

- advocacy_docs/supported-open-source/postgresql/uninstalling.mdx
Changes related to https://github.com/EnterpriseDB/docs/issues/4719
> PostgreSQL: Mac uninstall

- advocacy_docs/pg_extensions/advanced_storage_pack/using.mdx
The example for refdata was improved to show the different locking pattern that replaces the row locks for a table lock, leading to a stronger lock when the reference table is changed, but a lower overhead when the referenced rows are accessed. The demonstration uses pgrowlocks, which is available for heap, and will be available in a future version of our custom TAMs.
The example for autocluster was maintained.
The advanced example that uses both TAMs was improved to show the effect that autocluster has on the query plan, leading to fewer pages touched. Previously it showed the ctid of the rows, but that is already displayed in the autocluster example, so showing the different query plans fills a gap in the overall explanation of autocluster.
The examples were reworked to not need …
> pg_extensions/ASP/using: improve examples

- product_docs/docs/biganimal/release/using_cluster/05_monitoring_and_logging/index.mdx
The Remote monitoring link in the third bullet on this [page](https://www.enterprisedb.com/docs/biganimal/latest/using_cluster/05_monitoring_and_logging/) 404s even though there is a redirect for it. This PR fixes the link, but it might be worth investigating why the redirect didn't work.
> BigAnimal: fixing PEM remote monitoring link

- product_docs/docs/efm/4/upgrading.mdx
The db.bin property is just one of many needed properties, so calling it out here in a note doesn't make sense. My guess is that we added that property some time back and an upgrade required setting it, but by now any installation that a user is upgrading from will already have it set.
The unit file comment I removed doesn't make sense here, and I don't know where it might have come from. When upgrading, the service name doesn't change, and there would be a new unit file anyway. This might be related to the multiple efm agents on a single node section, but doesn't make sense here that I can see.
> removed text that was not needed

- advocacy_docs/security/advisories/cve.mdx.template
- advocacy_docs/security/advisories/cve20074639.mdx
- advocacy_docs/security/advisories/cve201910128.mdx
- advocacy_docs/security/advisories/cve202331043.mdx
- advocacy_docs/security/advisories/cve202341113.mdx
- advocacy_docs/security/advisories/cve202341114.mdx
- advocacy_docs/security/advisories/cve202341115.mdx
- advocacy_docs/security/advisories/cve202341116.mdx
- advocacy_docs/security/advisories/cve202341117.mdx
- advocacy_docs/security/advisories/cve202341118.mdx
- advocacy_docs/security/advisories/cve202341119.mdx
- advocacy_docs/security/advisories/cve202341120.mdx
- advocacy_docs/security/advisories/index.mdx
- advocacy_docs/security/index.mdx
- advocacy_docs/security/templates/advisoriesindex.njs
- advocacy_docs/security/templates/securityindex.njs
- tools/automation/generators/advisoryindex/advisoryindex.js
- tools/automation/generators/advisoryindex/package-lock.json
- tools/automation/generators/advisoryindex/package.json
Bit of a biggie; there's slight reworks on all the existing CVE's to add some new metadata (affectedProducts).
Then there's tools/automation/generators/advisoryindex/advisoryindex.js
cd into that directory and run node advisoryindex.js --source path_to_security_folder_in_docs
And that'll make both index pages. Uses nunjucks to template content - templates are in the security directory folder templates.
> Automating index generation for the security pages

- product_docs/docs/tpa/23/INSTALL-repo.mdx
- product_docs/docs/tpa/23/INSTALL.mdx
- product_docs/docs/tpa/23/firstclusterdeployment.mdx
- product_docs/docs/tpa/23/index.mdx
- product_docs/docs/tpa/23/opensourcetpa.mdx
- product_docs/docs/tpa/23/reference/INSTALL-docker.mdx
- product_docs/docs/tpa/23/reference/tpaexec-support.mdx
- product_docs/docs/tpa/23/tpaexec-configure.mdx
New opensource and tutorial content in sidebar and promotion of install from source from reference.
> TPA 23.23 pre-import with Open Source page and Tutorial

- product_docs/docs/edb_plus/41/02_release_notes/edbplus_41.2_rel_notes.mdx
- product_docs/docs/efm/4/efm_rel_notes/03_efm_47_rel_notes.mdx
- product_docs/docs/epas/11/epas_rel_notes/index.mdx
- product_docs/docs/epas/12/epas_rel_notes/index.mdx
- product_docs/docs/epas/13/epas_rel_notes/index.mdx
- product_docs/docs/epas/14/epas_rel_notes/index.mdx
- product_docs/docs/epas/15/epas_rel_notes/index.mdx
- product_docs/docs/hadoop_data_adapter/2/hadoop_rel_notes/hadoop_rel_notes_2.3.1.mdx
- product_docs/docs/jdbc_connector/42.5.4.1/01_jdbc_rel_notes/jdbc_42.5.4.1_rel_notes.mdx
- product_docs/docs/livecompare/2/rel_notes/2.5_rel_notes.mdx
- product_docs/docs/migration_portal/4/01_mp_release_notes/mp_4.5.1_rel_notes.mdx
- product_docs/docs/migration_toolkit/55/mtk_rel_notes/mtk_5561_rel_notes.mdx
- product_docs/docs/mongo_data_adapter/5/mongo_rel_notes/mongo5.5.1_rel_notes.mdx
- product_docs/docs/mysql_data_adapter/2/mysql_rel_notes/mysql2.9.1_rel_notes.mdx
- product_docs/docs/ocl_connector/15/ocl_rel_notes/15.2.0.4_ocl_release_notes.mdx
- product_docs/docs/odbc_connector/13/01_odbc_rel_notes/odbc_13.2.0.02_rel_notes.mdx
- product_docs/docs/pem/9/pem_rel_notes/930_rel_notes.mdx
- product_docs/docs/pgbouncer/1/pgbouncer_rel_notes/06_11900_rel_notes.mdx
- product_docs/docs/pgd/5/rel_notes/pgd_5.2.0_rel_notes.mdx
- product_docs/docs/pge/15/release_notes/rel_notes15.4.mdx
- product_docs/docs/pgpool/4/pgpool_rel_notes/442_rel_notes.mdx
- product_docs/docs/postgis/3.2/01_release_notes/rel_notes321.mdx
- product_docs/docs/postgres_for_kubernetes/1/rel_notes/1_20_2_rel_notes.mdx
- EPAS: updated [release notes table](https://github.com/EnterpriseDB/docs/pull/4840)  by @nidhibhammar 
- All products: Added [release date and updated title](https://github.com/EnterpriseDB/docs/pull/4843) to the latest versions by @dwicinas
> Release: 2023-09-26

- product_docs/docs/epas/15/reference/oracle_compatibility_reference/epas_compat_sql/29_create_profile.mdx
The parameter password_life_time updated as per [DF-356](https://enterprisedb.atlassian.net/browse/DF-356)
[DF-356]: https://enterprisedb.atlassian.net/browse/DF-356?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> EPAS 15 - Profile parameter update as per DF-356

- product_docs/docs/pgd/5/reference/functions.mdx
The text was copy pasted from `bdr.run_on_all_nodes` and the wording and warnings need to be somewhat different for these two functions
> Fix notes for bdr.run_on_nodes and bdr.run_on_group

- product_docs/docs/epas/15/upgrading/05_performing_a_minor_version_update_of_an_rpm_installation.mdx
Hi team,
Greetings.
We've found that your minor upgrade page lacks the information about edb_sqlpatch description, which is needed for example v15.4.
Add edb_sqlpatch command sample and link to its manual page at bottom.
> Add edb_sqlpatch information on minor version up page for EPAS 15 manual

- advocacy_docs/pg_extensions/pg_failover_slots/installing.mdx
Failover slots files have an edb, not a pg prefix, so all the examples were wrong. Validated package existence on RHEL and Ubuntu.
> Fix installing.mdx

- gatsby-node.js
- src/components/advanced-search/form.js
- src/components/search/formComps.js
- src/components/search/index.js
- src/constants/algolia-indexing.js
- src/constants/gatsby-utils.js
- src/pages/404.js
- src/pages/search.js
- Automatically add redirects from versioned product root to latest version. E.g., /pgd/ -> /pgd/latest/
- Choose object IDs for Algolia such that the default tie-breaker ordering (descending string order by ID) will mostly match navigation order.
- Include full hierarchy of section titles in search titles. E.g., # Installing ## Overview ### Linux -> Installing >> Overview >> Linux
- Pre-render global search bar (faster loading)
- Send search result click events to Algolia for better analytics, optimization
- Enable advanced syntax for searches (quoted terms, term exclusion). E.g., `"sql patch" -advisories`
Fixes #4872
Fixes #4331
> Redirect unversioned product URLs to latest, search fixes

- gatsby-browser.js
- src/styles/_helpers.scss
Appears there were at least three different places where scrolling would potentially be forced on navigation:
1. a script injected by the autolink headers plugin (only on page load)
2. gatsby's router logic (page load and internal navigation)
3. navigation callback in gatsby-browser.js (page load and internal navigation)
...not to mention the default browser behavior, which would (should?) also work on page load.
Generally, this didn't seem to cause issues, but occasionally an odd behavior would emerge: navigating to a section within a page would jump the scroll position much further down. Oddly, this seems to disappear if the \#3 logic is eliminated in favor of a selective override of \#2.
> Move scrolling to proper callback, avoid animation 

- product_docs/docs/pgd/5/appusage/dml-ddl.mdx
- product_docs/docs/pgd/5/appusage/index.mdx
> fixed broken links and title

- product_docs/docs/biganimal/release/planning/deployment_options/index.mdx
- product_docs/docs/biganimal/release/using_cluster/01_postgres_access/index.mdx
> added info about other cloud providers and token for 

- product_docs/docs/pgd/4/cli/command_ref/pgd_show-replslots.mdx
- product_docs/docs/pgd/5/cli/command_ref/pgd_show-replslots.mdx
Fix the default value for verbose flag in show-replslots doc. This minor PR can be merged/published after review (no need to wait for PGD release).
> BDR-4220 - fix the verbose flag defaults in show-replslots cmd

- product_docs/docs/eprs/7/08_xdb_cli/03_xdb_cli_commands/20_adding_tablefilters_to_publication.mdx
Changed "edentifiers" to "identifiers" in link label (quoted_identifiers) page
> Correction of spelling typo

- product_docs/docs/tpa/23/reference/platform-shared.mdx
Empty shared instance page (and reference section block) are gone.
> Removed defunct shared entry in reference

- product_docs/docs/efm/4/04_configuring_efm/05_using_vip_addresses.mdx
- product_docs/docs/efm/4/upgrading.mdx
This is occasionally a source of confusion, and we'd like to make it clear that EFM doesn't drop the vip when it exits. This would break a cluster that uses a VIP.
Am not sure if it makes sense to have two "Note" boxes next to each other at the top of the page, so if there's a better way to handle it am happy with any changes.
> EFM does not drop the VIP when the primary agent is stopped

- product_docs/docs/tde/15/enabling_tde.mdx
Missing () in pg_control_init as per https://edb.slack.com/archives/CSE2UK3EX/p1699952398387459
> Fix missing () in pg_control_init

- install_template/config.yaml
- product_docs/docs/mysql_data_adapter/2/installing/linux_x86_64/mysql_debian_10.mdx
- product_docs/docs/odbc_connector/16/02_requirements_overview.mdx
- product_docs/docs/odbc_connector/16/index.mdx
- product_docs/docs/odbc_connector/16/installing/index.mdx
- product_docs/docs/odbc_connector/16/installing/linux_ppc64le/odbc_rhel_8.mdx
- product_docs/docs/odbc_connector/16/installing/linux_ppc64le/odbc_rhel_9.mdx
- product_docs/docs/odbc_connector/16/installing/linux_ppc64le/odbc_sles_12.mdx
- product_docs/docs/odbc_connector/16/installing/linux_ppc64le/odbc_sles_15.mdx
- product_docs/docs/odbc_connector/16/installing/linux_x86_64/odbc_centos_7.mdx
- product_docs/docs/odbc_connector/16/installing/linux_x86_64/odbc_debian_10.mdx
- product_docs/docs/odbc_connector/16/installing/linux_x86_64/odbc_debian_11.mdx
- product_docs/docs/odbc_connector/16/installing/linux_x86_64/odbc_other_linux_8.mdx
- product_docs/docs/odbc_connector/16/installing/linux_x86_64/odbc_other_linux_9.mdx
- product_docs/docs/odbc_connector/16/installing/linux_x86_64/odbc_rhel_7.mdx
- product_docs/docs/odbc_connector/16/installing/linux_x86_64/odbc_rhel_8.mdx
- product_docs/docs/odbc_connector/16/installing/linux_x86_64/odbc_rhel_9.mdx
- product_docs/docs/odbc_connector/16/installing/linux_x86_64/odbc_sles_12.mdx
- product_docs/docs/odbc_connector/16/installing/linux_x86_64/odbc_sles_15.mdx
- product_docs/docs/odbc_connector/16/installing/linux_x86_64/odbc_ubuntu_18.mdx
- product_docs/docs/odbc_connector/16/installing/linux_x86_64/odbc_ubuntu_20.mdx
- product_docs/docs/odbc_connector/16/installing/linux_x86_64/odbc_ubuntu_22.mdx
Includes generated installer files.
I've chosen to omit the version number from the index description metadata, as this is tedious to keep updated with point releases. If desired, I recommend re-adding only a major version.
Could use a sanity check on that compat table; I just guessed. Primary goal was to make the links work, but realistically... Do we need to list the v13 stuff there? Maybe just a link to the v13 table...
> Update installer metadata; update links and version numbers for v16 ODBC driver

- product_docs/docs/pgd/5/security/role-management.mdx
Text expanded to note where replication and joining may break when unreplicated roles or objects dependent on them are created.
> BDR-4288 - Docs: Improve role management documentation

- product_docs/docs/pgd/4/bdr/catalogs.mdx
`s/STREAT/STREAM/`. 
Already fixed in the 5.x docs.
> BDR: fix typo in 4.x "bdr.stat_subscription" description

- product_docs/docs/pgd/5/monitoring/sql.mdx
As of BDR 4.0, the referenced `bdr-enterprise` extension no longer exists, and the catalogue table in question is always installed.
(I checked the BDR 4.x docs, it is not present there)
> BDR: remove reference to the "bdr-enterprise" extension in 5.x docs

- product_docs/docs/pgd/5/monitoring/otel.mdx
Added OTEL/OLTP information (derived from source).
>  BDR-4362-The-docs-do-not-specify-the-OTEL-protocol-used 

- product_docs/docs/biganimal/release/free_trial/detail/experiment/backup_and_restore.mdx
- product_docs/docs/biganimal/release/free_trial/detail/experiment/data/LICENSE
- product_docs/docs/biganimal/release/free_trial/detail/experiment/import_data.mdx
Apparently the Chadwick Baseball Bureau is no longer publishing this particular file. As it is licensed permissively, I've grabbed the data from a fork, stored locally for future stability, and referenced this repo in the examples.
Also link to a fork to avoid confusing folks unnecessarily.
Fixes #5014
Note for review: the URL listed in examples won't exist until this is in production. Adjust as needed.
> Move batting data csv into this repo, reference it appropriately

- src/components/search/formComps.js
- src/components/search/index.js
When selecting alternate product (or all products) while searching from a product page, disregard current product version and return to "latest version" default filter.
> Fix for bug introduced in #5105

- product_docs/docs/pem/8/index.mdx
PGE is supported as a backend for 13 and 14
11 is now out of support
> Correct PEM compatibility table

- product_docs/docs/pgd/5/reference/commit-scopes.mdx
In editing the latest changes, realized I had never edited this.
Please check capitalization of LAG CONTROL, Lag Control, RAFT, and Raft. I didn't know if/when these terms should be capitalized and whether the inconsistency was correct.
> Edits to commit scopes topic

- product_docs/docs/epas/15/reference/oracle_compatibility_reference/epas_compat_sql/65a_merge.mdx
Removed mention of DELETE from topic describing SQL-compatible MERGE command in version 15 of EPAS
> Removed mention of DELETE from MERGE topic

- product_docs/docs/epas/15/reference/oracle_compatibility_reference/epas_compat_cat_views/pg_views/index.mdx
- product_docs/docs/epas/16/reference/oracle_compatibility_reference/epas_compat_cat_views/pg_views/pg_attribute.mdx
- product_docs/docs/epas/16/reference/oracle_compatibility_reference/epas_compat_cat_views/pg_views/pg_authid.mdx
- product_docs/docs/epas/16/reference/oracle_compatibility_reference/epas_compat_cat_views/pg_views/pg_class.mdx
- product_docs/docs/epas/16/reference/oracle_compatibility_reference/epas_compat_cat_views/pg_views/pg_collation.mdx
- product_docs/docs/epas/16/reference/oracle_compatibility_reference/epas_compat_cat_views/pg_views/pg_database.mdx
- product_docs/docs/epas/16/reference/oracle_compatibility_reference/epas_compat_cat_views/pg_views/pg_namespace.mdx
- product_docs/docs/epas/16/reference/oracle_compatibility_reference/epas_compat_cat_views/pg_views/pg_partitioned_table.mdx
- product_docs/docs/epas/16/reference/oracle_compatibility_reference/epas_compat_cat_views/pg_views/pg_proc.mdx
- product_docs/docs/epas/16/reference/oracle_compatibility_reference/epas_compat_cat_views/pg_views/pg_subscription.mdx
- product_docs/docs/epas/16/reference/oracle_compatibility_reference/epas_compat_cat_views/pg_views/pg_synonym.mdx
- product_docs/docs/epas/16/reference/oracle_compatibility_reference/epas_compat_cat_views/pg_views/pg_trigger.mdx
- product_docs/docs/epas/16/reference/oracle_compatibility_reference/epas_compat_cat_views/pg_views/pg_type.mdx
Added files for:
pg_attribute
pg_authid
pg_class
pg_collation
pg_database
pg_namespace
pg_partitioned_table
pg_proc
pg_subscription
pg_synonym
pg_trigger
pg_type
pg_user
Addresses https://enterprisedb.atlassian.net/browse/DF-368
> Documenting the delta between EDB system catalogs and information available in PostgreSQL

- product_docs/docs/pgd/5/reference/catalogs-visible.mdx
Added "bdr.node_group_summary" reference entry, which has been missing since the view was added in BDR 5.0.0.
Cross-reference from "bdr.node_group" added too (and cleaned up the column formatting there).
BDR-4467
> PGD: add "bdr.node_group_summary" reference entry.

- product_docs/docs/pgd/5/reference/functions.mdx
From PGD 5, the default group name is "global", not "normal".
> PGD: fix description of bdr.node_group_type() function

- product_docs/docs/pgd/5/reference/functions-internal.mdx
The [Internal system functions](https://www.enterprisedb.com/docs/pgd/latest/reference/functions-internal/) reference page starts off with the functions listed in alphabetical order, which breaks down part-way through, then there's a subsection titled "Task Manager Functions", which contains a couple of taskmanager functions, then a bunch of unrelated functions which were presumably just added to the end of the page.
As the functions start off in alphabetical order, a human scanning the list will tend to assume a function is not listed if it's not found where expected alphabetically. And it's a bit of a mess (I just wasted a bit of time assuming a function is not documented, when it was actually there).
This commit sorts the non-taskmanager functions alphabetically to make the page more …
> PGD: rearrange internal functions reference

- product_docs/docs/pgd/4/bdr/functions.mdx
- product_docs/docs/pgd/5/reference/functions-internal.mdx
`bdr.seq_lastval()` was written incorrectly as `bdr.sql_lastval()` in two places.
> PGD: fix name of bdr.seq_lastval() function

- product_docs/docs/pgd/5/monitoring/sql.mdx
Reworked Monitoring transaction COMMITs section to reflect the current status of transaction monitoring.
> pgd/sql monitoring: Updated for relevance

- product_docs/docs/pgd/5/reference/nodes-management-interfaces.mdx
Document bdr.alter_node_group_option so that we can expose apply_delay option
BDR-4396
Added warning to alter_node_group_config about being deprecated in favor of bdr.alter_node_group_option and properly documented options that bdr.alter_node_group_option can set.
This is for PGD 5.4 release.
> Document bdr.alter_node_group_option

- product_docs/docs/efm/4/04_configuring_efm/01_cluster_properties.mdx
Looks like someone did a bulk change of "text" to "ini" and it clobbered the information about one efm property. This change adds the proper name/text back in.
> undo text->ini change

- gatsby-config.js
- package-lock.json
- package.json
Add support for reporting page access to Fathom. Site ID should be configured in repository variables.
> Add Fathom analytics

- product_docs/docs/pgd/3.7/bdr/backup.mdx
- product_docs/docs/pgd/4/backup.mdx
- product_docs/docs/pgd/4/bdr/nodes.mdx
- product_docs/docs/pgd/5/backup.mdx
Bare minimum fixes for #5035 - remove references to recovery.conf except in PGD 3.7 where it is still nominally supported 
(Note: originally contained a somewhat iffy change to PGD 5 in a now-eliminated file.)
> Replace use of recovery.conf outside of PGD 3.7

- product_docs/docs/pgd/5/reference/nodes-management-interfaces.mdx
Current state: https://www.enterprisedb.com/docs/pgd/latest/reference/nodes-management-interfaces/#bdrjoin_node_group
This patch:
- explicitly states the default value (`all`) -> see https://github.com/EnterpriseDB/bdr/blob/5a247059b06984a7e2d50dcaee7aaa58abc2720f/bdr_functions.c#L2358
- notes that data is not synchronized for witness nodes -> see https://www.enterprisedb.com/docs/pgd/latest/node_management/witness_nodes/
BDR-4520.
> PGD: clarify bdr.join_node_group()'s synchronize_structure parameter

- advocacy_docs/supported-open-source/barman/pg-backup-api/03-tasks.mdx
The page that describes the available operations of `pg-backup-api`.
`pg-backup-api` now has not only server level operations, but also instance level operations. With these changes, a couple more endpoints were made available in the API to handle the instance level operaitons.
Besides that, `pg-backup-api` has been changed in a few fronts:
* Slight changes to output format of `GET` requests, so they include not only the operation ID, but also the operation type
* Slight changes made on the payload for requesting recovery operations
* Introduced a new server level operation: `config_switch`
* Introduced an instance level operation: `config_update`
This commit updates the `pg-backup-api` docs so it contains all the supported endpoints and operations.
References: BAR-144.
> Update `pg-backup-api` docs to cover all supported operations

- advocacy_docs/supported-open-source/pgbackrest/03-quick_start.mdx
Currently the EPAS newest major release is v15, hence pg-version-force option should be added to pgbackuprest.conf to solve below issue.
https://github.com/pgbackrest/pgbackrest/issues/2032
pgbackrest.conf sample(EPAS part) changed from:
-------------------------------------------------------
[global]
repo1-path=/var/lib/edb/as13/backups
[demo]
pg1-path=/var/lib/edb/as13/data
pg1-user=enterprisedb
pg1-port=5444
-------------------------------------------------------
to:
-------------------------------------------------------
[global]
repo1-path=/var/lib/edb/as13/backups
[demo]
pg1-path=/var/lib/edb/as13/data
pg1-user=enterprisedb
pg1-port=5444
pg-version-force=15
-------------------------------------------------------
> Add note about need for pg-force-version to pgbackrest instructions

- product_docs/docs/pgd/5/reference/nodes-management-interfaces.mdx
Updated the default value for the `pause_in_standby` parameter and note that it has been deprecated since BDR 5.0 (commit 8a453ca6).
In passing, tidy up and generally improve the reference entry wording, including adding links to referenced objects.
BDR-4555.
> pgd: fixes for bdr.join_node_group() reference documentation

- product_docs/docs/pgd/5/reference/nodes-management-interfaces.mdx
`bdr.create_node()`: https://www.enterprisedb.com/docs/pgd/latest/reference/nodes-management-interfaces/#bdrcreate_node
- added missing `node_kind` parameter, present from BDR 5.0.
> pgd: add "node_kind" parameter to bdr.create_node() reference documentation

- product_docs/docs/pgd/5/durability/limitations.mdx
Removed limitations around physical standby from durability limitations (as physical standbys are no longer supported).
> PGD: Removed physical standby reference

- product_docs/docs/pgd/5/node_management/index.mdx
- product_docs/docs/pgd/5/node_management/maintainance_with_proxies.mdx
New page in node-management: [Maintenance commands through proxies](https://deploy-preview-5172--edb-docs-staging.netlify.app/docs/pgd/latest/node_management/maintainance_with_proxies/)
Fixes: [BDR-4494](https://enterprisedb.atlassian.net/browse/BDR-4494)
[BDR-4494]: https://enterprisedb.atlassian.net/browse/BDR-4494?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Added docs on managing commands through proxies re BDR-4494

- product_docs/docs/pgd/5/reference/nodes-management-interfaces.mdx
The values for the `node_group_type` parameter were changed in BDR 5.0 (commit 205c6aa1) but the documentation still describes the values valid for BDR 4.x and earlier.
Also while I was at it, generally improved the reference entry wording.
BDR-4554.
> pgd: fixes for bdr.create_node_group() reference documentation

- product_docs/docs/epas/16/reference/oracle_compatibility_reference/04_partitioning_commands_compatible_with_oracle_databases/limitations.mdx
Limitations when creating a partitioned table that includes non-partition key column.
Also describes interval and automatic partitioning limitations.
Addresses https://enterprisedb.atlassian.net/browse/DB-2584
> Limitations to partitioning commands

- product_docs/docs/biganimal/release/overview/03a_region_support/index.mdx
Remove the southeastasia notes, the Faraway is already supported there.
> Remove note on Faraway support from southeastasia row - no longer applies

- product_docs/docs/pgd/5/durability/commit-scopes.mdx
And also consistent punctuation before a code sample.
> Consistent use of tick formatting of variable names

- scripts/fileProcessor/processors/cnp/cleanup-html.mjs
- scripts/fileProcessor/processors/cnp/update-links.mjs
- scripts/source/process-cnp-docs.sh
- scripts/source/process-pgd4k-docs.sh
A few corrections that are easier to make on import than fix at the source.
Also use a worktree for the script to avoid messing up the source repo (can now re-run local import without side-effects)
> PG4K: Perform API HTML+link corrections on import

- product_docs/docs/biganimal/release/using_cluster/extensions.mdx
The index_advisor extension has been renamed to query_advisor so this document needs to be updated to reflect that change.
Here is evidence from a BigAnimal cluster today:
edb_admin=> create extension index_advisor;
ERROR:  extension "index_advisor" is not available DETAIL:  Could not open extension control file "/usr/share/edb-as/16/extension/index_advisor.control": No such file or directory. HINT:  The extension must first be installed on the system where PostgreSQL is running.
edb_admin=> create extension query_advisor;
CREATE EXTENSION
edb_admin=> select * from pg_available_extensions where name like '%advisor%';
name      | default_version | installed_version |            comment
---------------+-----------------+-------------------+--------------------------------
query_advisor | …
> Update extensions.mdx change index_advisor to query_advisor

- src/styles/_admonitions.scss
- src/styles/_dark.scss
This is almost exclusively used in the PG4K docs, where... Many should probably be SeeAlso instead. But regardless, in MkDocs the "info" styling is a dead ringer for "Note", so I've made them the same here too to avoid shock when writing for one system and then seeing it in the other.
> Add styling for the "info" admonition tag

- product_docs/docs/tde/15/index.mdx
Starting with v16, we added the option for AES 256 encryption. Updating the 'How does TDE encrypt data?' section to include the updated choice and algorithms.
Before: 
TDE encrypts the data files using AES-128-XTS. The XTS “tweak” uses the database OID, the relfilenode, and the block number.
The WAL is encrypted using AES-128-CTR. The “counter” includes the WAL LSN.
Temporary files that are accessed by block are also encrypted using AES-128-XTS. Other temporary files are encrypted using AES-128-CBC.
After: 
Starting with version 16, EDB TDE introduces the option to choose between AES-128 and AES-256 encryption algorithms during the initialization of the Postgres cluster. The choice between AES-128 and AES-256 hinges on balancing performance and security requirements. AES-128 is commonly …
> Add AES-256 usage notes to "How does TDE encrypt data?"

- product_docs/docs/pgd/3.7/bdr/nodes.mdx
- product_docs/docs/pgd/4/bdr/nodes.mdx
- product_docs/docs/pgd/5/reference/nodes-management-interfaces.mdx
This option was removed in BDR 3.7, but hastily reinstated with a deprecation notice as it turned out it was in use by at least one customer. Since then, the customer has continued using the option but no action has been or is likely to be taken to remove, replace or otherwise modify the behaviour of the option, and the presence of the deprecation notices over multiple major releases is causing ongoing confusion, so remove the notices.
BDR-4424.
> pgd: remove deprecation notices for "check_constraints" node group option

- product_docs/docs/migration_portal/4/02_supported_platforms.mdx
Looking at the Migration Portal Web UI available at https://migration.enterprisedb.com/, it looks like the supported target EPAS versions have changed. (Dropped support for 11 and added 15 and 16)
Updating the docs to reflect that. I like to use the wording "and later versions" instead of explicitly calling out each version to avoid docs becoming outdated so quickly, but feel free to suggest otherwise.
> Updated supported EPAS versions for Migration Portal

- product_docs/docs/postgres_for_kubernetes/1/index.mdx
- product_docs/docs/postgres_for_kubernetes/1/rel_notes/0_0_1_rel_notes.mdx
- product_docs/docs/postgres_for_kubernetes/1/rel_notes/0_1_0_rel_notes.mdx
- product_docs/docs/postgres_for_kubernetes/1/rel_notes/0_2_0_rel_notes.mdx
- product_docs/docs/postgres_for_kubernetes/1/rel_notes/0_3_0_rel_notes.mdx
- product_docs/docs/postgres_for_kubernetes/1/rel_notes/0_4_0_rel_notes.mdx
- product_docs/docs/postgres_for_kubernetes/1/rel_notes/0_5_0_rel_notes.mdx
- product_docs/docs/postgres_for_kubernetes/1/rel_notes/0_6_0_rel_notes.mdx
- product_docs/docs/postgres_for_kubernetes/1/rel_notes/0_7_0_rel_notes.mdx
- product_docs/docs/postgres_for_kubernetes/1/rel_notes/0_8_0_rel_notes.mdx
- product_docs/docs/postgres_for_kubernetes/1/rel_notes/index.mdx
For https://enterprisedb.atlassian.net/browse/DOCS-148, the docs need to specify that the product has been available and in use for a long period of time.
Therefore, we add pre-GA release notes to the public documentation.
> Adding pre-GA Release Notes for transparency

- advocacy_docs/pg_extensions/pg_failover_slots/configuring.mdx
- product_docs/docs/efm/4/07_using_efm_utility.mdx
- product_docs/docs/efm/4/upgrading.mdx
- product_docs/docs/pgd/5/upgrades/upgrade_paths.mdx
- product_docs/docs/postgres_for_kubernetes/1/index.mdx
- product_docs/docs/postgres_for_kubernetes/1/rel_notes/0_0_1_rel_notes.mdx
- product_docs/docs/postgres_for_kubernetes/1/rel_notes/0_1_0_rel_notes.mdx
- product_docs/docs/postgres_for_kubernetes/1/rel_notes/0_2_0_rel_notes.mdx
- product_docs/docs/postgres_for_kubernetes/1/rel_notes/0_3_0_rel_notes.mdx
- product_docs/docs/postgres_for_kubernetes/1/rel_notes/0_4_0_rel_notes.mdx
- product_docs/docs/postgres_for_kubernetes/1/rel_notes/0_5_0_rel_notes.mdx
- product_docs/docs/postgres_for_kubernetes/1/rel_notes/0_6_0_rel_notes.mdx
- product_docs/docs/postgres_for_kubernetes/1/rel_notes/0_7_0_rel_notes.mdx
- product_docs/docs/postgres_for_kubernetes/1/rel_notes/0_8_0_rel_notes.mdx
- product_docs/docs/postgres_for_kubernetes/1/rel_notes/index.mdx
EDB Postgres for Kubernetes
- Release Notes for versions earlier than 1.0
Edits to pg_failover and efm
> Release: 2024/03/01a

- product_docs/docs/pgd/5/cli/installing_cli.mdx
Need to make it clear that BA free trial customers can also access the token from the EDB Repos
> Edits for DOCS-138 - BA repo token instructions.

- product_docs/docs/pgd/5/reference/catalogs-visible.mdx
Added descriptions for following columns:
- `generated`
- `node_kind`
Also add a link to the human-readable `bdr.node_summary` view.
BDR-4743.
> PGD: add missing columns to "bdr.nodes" reference

- product_docs/docs/pgd/5/reference/catalogs-visible.mdx
Column `node_group_default_commit_scope`, added in PGD 5.0, was missing, so added. The corresponding entry in `bdr.node_group_summary` is present.
> pgd: add missing field to "bdr.node_group" reference entry

- product_docs/docs/pgd/5/reference/pgd-settings.mdx
The default value was changed from 100 to 1000 with PGD 5.4 (BDR commit 2588f022) but the reference entry wasn't updated.
> pgd: fix "bdr.raft_keep_min_entries" reference entry

- product_docs/docs/pgd/3.7/bdr/catalogs.mdx
- product_docs/docs/pgd/4/bdr/catalogs.mdx
The field "set_repl_ops" is not present from PGC 3.7 onwards, so remove this from the 3.7 and 4 documentation (it is not in the PGD 5 docs).
BDR-4774.
> pgd: fixes for bdr.node_summary documentation

- advocacy_docs/security/assessments/cve-2024-1597.mdx
According to the official pgjdbc repo, the vulnerable versions are not those below 4.2.8 but those below 4.2.28: https://github.com/pgjdbc/pgjdbc/security/advisories/GHSA-24rp-q3w6-vc56
So here's the modification I'd suggest. I have also sent a request for a modification to https://www.cve.org/.
Regards,
Simon
> Fix: Update cve-2024-1597.mdx

- product_docs/docs/pwr/1/configuring.mdx
This commit modifies the PWR docs so it contains information about the environment variable `PWR_CONFIG_FILE`, which can be used to specify a config file for PWR.
References: PGCP-58.
Add information about `PWR_CONFIG_FILE` environment variable to the PWR documentation. That variable has always been supported by PWR to specify the path to a configuration file, but the docs were missing that information.
> Add `PWR_CONFIG_FILE` env variable to PWR documentation

- product_docs/docs/pgbouncer/1/supported_platforms.mdx
https://enterprisedb.atlassian.net/browse/DOCS-207 
- Removed EPAS 11 from all rows
- Added EPAS 16 
- Added pgbouncer versions 1.20, 1.21, and 1.22
> Updating pgBouncer support table

- product_docs/docs/pem/8/installing_pem_agent/windows_agent.mdx
- product_docs/docs/pem/9/installing_pem_agent/windows_agent.mdx
Fixing indentation and versioning issues flagged through GH issue by Simon.
https://github.com/EnterpriseDB/docs/issues/5374
https://enterprisedb.atlassian.net/browse/DOCS-199
> Fixing indentation and versioning for PEM 8 and 9

- product_docs/docs/pwr/1/using.mdx
When no time zone is explicitly set, PWR falls back to the local system time zone.
References: PGCP-71.
Added a note to the PWR docs explaining that in the absence of a time zone in the timestamp arguments, PWR falls back to the system time zone.
> Clarify that timestamp args of PWR accept input with or without time zone

- product_docs/docs/pwr/1/configuring.mdx
Although the PWR configuration file is named with a `.conf` suffix, its content must be in YAML format.
This commit adds a note with that information, so we avoid having users to face config parsing issues.
References: PGCP-63.
Adds a note that PWR config file content must be in YAML format.
> Clarify in the docs that PWR configuration file should be in YAML format

- src/components/layout.js
Always render the canonical header. If no other version of a given page is known, it should be considered the canonical path and rendered in the header with http://www.enterprisedb.com/docs/ as the base URL.
It appears we are not rendering the canonical header for unversioned pages (this includes all content under advocacy_docs, as well as the homepage, special status pages, and potentially a tiny handful of product pages contained within normally versioned products in exceptional circumstances). Most importantly, this includes most of our documentation for extensions.
Example: https://www.enterprisedb.com/docs/pg_extensions/pg_squeeze/using/ does not have a rel="canonical" header. https://deploy-preview-5402--edb-docs-staging.netlify.app/docs/pg_extensions/pg_squeeze/using/ (same page …
> DOCS-223: ensure every page has a rel="canonical" header

- product_docs/docs/efm/4/05_using_efm.mdx
- product_docs/docs/efm/4/13_troubleshooting.mdx
This changes adds notes in two places to tell the user to check the startup log if there is a problem starting efm. Too often the user only checks 'systemctl status' output, which does not contain the problem.
(I'd like to get rid of the startup log because users forget it's there and it's not needed any more. I don't know when it'll happen though: https://enterprisedb.atlassian.net/browse/EFM-1619)
> Add more information about efm startup log

- product_docs/docs/pwr/1/using.mdx
The example fails with the timestamp check library we use. Added missing seconds to timestamp and minutes to timezone
> Timestamp check fails with example

- product_docs/docs/postgres_for_kubernetes/1/kubectl-plugin.mdx
This info hasn't been synchronized with the cloudnativepg version in like 8 months.  Some information is missing; some is out of date; some is straight-up wrong.
This PR does a quick update to get correct information out. Will need to also make some corrections in the internal repo (and figure out a better sync process) as well as updates upstream.
> Sync PG4K plugin docs with upstream

- product_docs/docs/biganimal/release/getting_started/creating_a_cluster/index.mdx
- product_docs/docs/postgres_for_kubernetes/1/images/grafana-local.png
- product_docs/docs/postgres_for_kubernetes/1/installation_upgrade.mdx
- product_docs/docs/postgres_for_kubernetes/1/kubectl-plugin.mdx
- product_docs/docs/postgres_for_kubernetes/1/monitoring.mdx
- product_docs/docs/postgres_for_kubernetes/1/quickstart.mdx
PR 5451: Updates BA docs such that the option to use PGE when creating a cluster is now highlighted.
PR 5455: Re-import of PG4K 1.22.2 - Fixes missing --server side flag in installation instructions, some other small ommisions.
PR 5442: Sync PG4K plugin docs with upstream - corrects out of date information by syncing with upstream cloudnativepg version.
> Release: 2024-03-28b

- advocacy_docs/tools/edb_sqlpatch/index.mdx
Making a change to the PGD cluster section to match that off the KB article:
https://techsupport.enterprisedb.com/kb/a/august-2023-advanced-server-security-update/
Customer in 103516 also was confused when they applied the edb_sqlpatch to the leader node and not all patches were applied to other nodes in the PGD cluster, like the documentation says.
> Revise sqlpatch docs to sync with customer support content.

- product_docs/docs/biganimal/release/index.mdx
Move release notes *and* known issues down the left nav
> BA - Reorganize left nav to lower known issues - DOCS-248

- product_docs/docs/pgd/5/reference/functions.mdx
The fields in the record emitted by this function were partially renamed and two new ones added in BDR 5.0.0 (see commit [d346c453](https://github.com/EnterpriseDB/bdr/commit/d346c4536fdc0bbc2c7c8d2b2f2960dbcb652750)).
> pgd: update output columns for bdr.lag_control()

- advocacy_docs/pg_extensions/pg_squeeze/using.mdx
Added an introduction to Using section describing when lock levels are applied.
Also one small change to registering section.
Addresses information request in https://github.com/EnterpriseDB/docs/issues/5278.
> Added information about lock levels to pg_squeeze docs

- product_docs/docs/biganimal/release/using_cluster/05c_upgrading_log_rep.mdx
- product_docs/docs/biganimal/release/using_cluster/index.mdx
Tracked in [JIRA](https://enterprisedb.atlassian.net/browse/DOCS-147).
> Adding instructions for upgrading Postgres major versions in Big Animal using logical replication

- product_docs/docs/biganimal/release/migration/dha_bulk_migration.mdx
Typos, smart quoted, more detailed commands
> Post deploy fixes to BA bulk upload guide

- product_docs/docs/pgd/5/security/pgd-predefined-roles.mdx
The lists of objects for which each of these predefined roles has privileges on, are somewhat outdated.
Update the lists based on a query of the actual database privileges installed for each role.
BDR-4899 (incorporating the additional permissions added via BDR-4842 and BDR-4885).
> pgd: update bdr_read_all_stats / bdr_monitor documentation

- product_docs/docs/efm/4/installing/prerequisites.mdx
If using physical replication slots, the database user efm uses must have permissions for creating and advancing slots. This commit adds a note about it and the command needed to grant the privileges.
> Add information about slot privileges needed

- product_docs/docs/biganimal/release/using_cluster/05_monitoring_and_logging/third_party_integrations/index.mdx
This is a quick edit to get this information published for a customer. We should consider embedding these names in the list of metrics rather than a separate table as a future improvement.
> Add table of metric names for 3PM integrations

- product_docs/docs/livecompare/2/supported_technologies.mdx
Updated the supported technologies table by adding version 16 to the list of PostgreSQL, EDB PostgreSQL Extended (PGE), and EDB Postgres Advanced Server (EPAS). 
LIV-239 [https://enterprisedb.atlassian.net/browse/LIV-239] indicates that support for version 16 has been tested and supported.
Also, updated the Technology names for PGE and EPAS.
> Added PG/PGE/EPAS 16 to list of supported versions

- product_docs/docs/postgres_distributed_for_kubernetes/1/index.mdx
- product_docs/docs/postgres_distributed_for_kubernetes/1/installation_upgrade.mdx
- product_docs/docs/postgres_distributed_for_kubernetes/1/known_issues.mdx
https://enterprisedb.atlassian.net/browse/DOCS-289
https://enterprisedb.atlassian.net/browse/DOCS-363
https://enterprisedb.atlassian.net/browse/DOCS-364
https://enterprisedb.atlassian.net/browse/DOCS-371
Adding Known issues page and first issue for EDB Postgres Distributed for Kubernetes 1.0.0. 
Let's use this PR to keep adding to the list in case new issues pop up.
Note: This PR branches off the 1.0.0 release PR.
> Docs/pg4k pgd/known issues

- product_docs/docs/biganimal/release/using_cluster/extensions.mdx
Continues on from #4889 which was merged early
> Document PostGIS extension in BigAnimal

- product_docs/docs/postgres_distributed_for_kubernetes/1/group_cleanup.mdx
- product_docs/docs/postgres_distributed_for_kubernetes/1/index.mdx
- product_docs/docs/postgres_distributed_for_kubernetes/1/known_issues.mdx
- product_docs/docs/postgres_distributed_for_kubernetes/1/supported_versions.mdx
Streamline PGD4K as official abbreviation
Correct /latest/ links to /5/ links for PGD references
Corrected link that referenced PG4K instead of PGD4K
> Streamline PGD4K as official abbreviation and other minor fixes

- product_docs/docs/efm/4/efm_rel_notes/index.mdx
Back in commit 0fcdb9f1c37e24e8ca7e2e80c228e368dd5c7237, the release years for efm versions 4.0 and 4.1 got bumped up by a year (so that 4.0 and 4.1 were actually released AFTER 4.2). Fixing this based on the diff of the commit above and the dates of the changes in efm code itself.
> Fix release years that were changed for 4.0/4.1

- product_docs/docs/postgres_distributed_for_kubernetes/1/installation_upgrade.mdx
Added --wait flag to helm upgrade command in pgd4k docs.
Tracked in JIRA [here](https://enterprisedb.atlassian.net/browse/DOCS-191).
> Added --wait flag to helm upgrade command.

- product_docs/docs/pgd/3.6/index.mdx
Switched BDR 3.6 page to point at docs-archive PDF archives of the 3.6 documentation.
> DOCS-372-problem-on-https-www-enterprisedb-com-docs-pgd-3

- product_docs/docs/eprs/7/10_appendix/03_miscellaneous_xdb_processing_topics/01_publications_and_subscriptions_server_conf_options/05_specify_custom_url_for_oracle_jdbc.mdx
> Fix 05_specify_custom_url_for_oracle_jdbc.mdx - DOCS-588

- product_docs/docs/efm/4/efm_rel_notes/02_efm_48_rel_notes.mdx
We don't put supported database version information into the release notes -- users should check the platform compatibility page instead.
Adding it here was my mistake last time around, and the information is wrong now that v11 has gone out of support.
> Remove minimum db version info in 4.8 release notes

- src/components/card-decks.js
- src/templates/doc.js
Switch to [GithubSlugger](https://github.com/Flet/github-slugger) for generating card section links. This is the same library used for the rest of the ToC and should therefore avoid most issues with punctuation, etc.
One thing to note: I've made no effort to avoid collisions here between section headers and other headers already used in the same topic. While normally this is handled by incrementing a suffix, that won't happen here - so if you use a header in markdown and the same header text for a section title, the section title link will take you to the section in the markdown. This is rare, and easy enough to avoid by just using unique section titles. Note that using the same title for multiple navigation sections *will* generate a unique suffix and work just fine, but is still a …
> Use github-slugger for section header links

- product_docs/docs/pgd/5/reference/index.mdx
- product_docs/docs/pgd/5/reference/index.mdx.src
Copy edits were done to content generated from templates. This puts the changes into the templates.
> Bake in copy edit changes into the templates

- advocacy_docs/pg_extensions/wait_states/rel_notes/index.mdx
- advocacy_docs/pg_extensions/wait_states/rel_notes/wait_states_1.3_rel_notes.mdx
- advocacy_docs/pg_extensions/wait_states/using.mdx
Added 1.3 release notes and edb_wait_states_directory_size function as per [EXT-648](https://enterprisedb.atlassian.net/browse/EXT-648)/ [DOCS-438](https://enterprisedb.atlassian.net/browse/DOCS-438)
[EXT-648]: https://enterprisedb.atlassian.net/browse/EXT-648?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DOCS-438]: https://enterprisedb.atlassian.net/browse/DOCS-438?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> edb_wait_states - Added 1.3 release notes and new function

- product_docs/docs/biganimal/release/using_cluster/fault_injection_testing/index.mdx
Customer needs Azure Kubernetes Service RBAC Reader as well, added.
Added Azure Kubernetes Service RBAC Reader to Azure permissions bullet.
> improve needed permissions spec for fault injection

- product_docs/docs/pgd/4/bdr/catalogs.mdx
- product_docs/docs/pgd/4/bdr/configuration.mdx
- product_docs/docs/pgd/5/reference/catalogs-visible.mdx
- product_docs/docs/pgd/5/reference/pgd-settings.mdx
For the catalogue relations "bdr.stat_relation" and "bdr.stat_subscription", make it clear which GUCs enable/disable tracking, and also note the respective statistics reset functions.
Also add missing "stats_reset" column on "bdr.stat_relation" for PGD 5.
> PGD: improve documentation of bdr.stat_[relation|subscription] catalogue relations

- advocacy_docs/pg_extensions/advanced_storage_pack/using.mdx
The example had timestamptz as datatype and inserted only hour:minute unquoted.
Besides the obvious quoting, we should either change the data to match the datatype, or the datatype to match the hour:minute data. Using full timestamptz probably wouldn't improve the example, which is well served by simple data. So using `time` as column datatype is adequate.
This intends to cover issue #5486 .
> fix autocluster example

- product_docs/docs/biganimal/release/release_notes/2024_01_jan_rel_notes.mdx
- product_docs/docs/biganimal/release/release_notes/2024_02_feb_rel_notes.mdx
- product_docs/docs/biganimal/release/release_notes/2024_03_mar_rel_notes.mdx
- product_docs/docs/biganimal/release/release_notes/2024_04_apr_rel_notes.mdx
Added missing word and fixed typo in 2024 release notes intros; made April 2024 release note intro wording consistent with others.
> Edits to BigAnimal PR5577

- product_docs/docs/postgres_for_kubernetes/1/rel_notes/1_23_1_rel_notes.mdx
- product_docs/docs/postgres_for_kubernetes/1/rel_notes/index.mdx
PG4K 1.23.1 was added a few weeks ago, therefore adding release notes.
https://edb.slack.com/archives/CU5QEU5L7/p1716816933779659
> Release notes for pg4k 1.23.1

- product_docs/docs/eprs/7/installing/uninstalling.mdx
- product_docs/docs/eprs/7/installing/upgrading_replication_server/upgrading_with_gui_installer.mdx
- product_docs/docs/eprs/7/installing/windows.mdx
https://enterprisedb.atlassian.net/browse/DOCS-669 
References for Stack Builder Plus can remain.
> Remove references of Stack Builder from EPRS docs

- advocacy_docs/supported-open-source/patroni/index.mdx
- advocacy_docs/supported-open-source/patroni/installing_patroni.mdx
- advocacy_docs/supported-open-source/patroni/installing_with_TPA.mdx
With release 3.3.0 of Patroni we've introduced a new `edb-patroni` package which provides all the dependencies in a single package.
These dependencies will be installed in a virtual environment where Patroni will run.
This removes the need to install `python3-ydiff`, `python3-cdiff`, and others.
> Update installation instructions for Patroni to use `edb-patroni`

- product_docs/docs/pgd/4/bdr/scaling.mdx
- product_docs/docs/pgd/5/scaling.mdx
Updated autopartition to note concurrency now enabled generally.
Applied to 4.x and 5.x doc sets.
> DOCS-524 - Feature request - use attach/detach concurrently

- product_docs/docs/pgd/3.7/bdr/conflicts.mdx
- product_docs/docs/pgd/4/bdr/conflicts.mdx
- product_docs/docs/pgd/5/consistency/conflicts.mdx
Conflicts section 3.7/4.x/5.x docs inline mention of delete_recently_updated resolution changed to skip.
> DOCS-670 - update delete_recently_updated default conflict resolution in PGD docs (3.7-5)

- product_docs/docs/epas/17/epas_security_guide/05_edb_audit_logging/08_audit_log_archiving.mdx
Added a note about edb_audit_archiver_expire_command
> Windows-specific issue for archive logs in EPAS

- gatsby-node.js
- src/components/card-decks.js
- src/components/index.js
- src/components/prev-next.js
- src/components/tiles.js
- src/constants/gatsby-utils.js
- src/templates/doc.js
- src/templates/learn-doc.js
- Section headings now render for card navigation section in unversioned docs
- Full card navigation no longer renders icons, when there are no icons defined for child pages
- Navigation order no longer ignored for grandchildren in "full" card navigation cards
- Sidebar navigation now expands normally even when page title is "NULL".
- As discussed on IA call, there's a new "Up" button that takes you to the parent, and the Prev button now behaves in a consistent fashion everywhere: to the last descendant of the previous sibling (IOW, the page for which the "next" button will take you to the current page). Existing behavior took you to the last child of the previous sibling, unless filename of previous sibling sorts alphabetically before the filename of current node in which case prev …
> Full nav cards in versioned docs + bugfixes

- product_docs/docs/jdbc_connector/42.5.4.2/01_jdbc_rel_notes/12_jdbc_42.2.19.1_rel_notes.mdx
Fixed a note in the release notes of version 42.2.19.1 as per [EC-3089](https://enterprisedb.atlassian.net/browse/EC-3089)
[EC-3089]: https://enterprisedb.atlassian.net/browse/EC-3089?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> JDBC connector - 42.2.19.1 release notes

- product_docs/docs/pgd/5/appusage/table-access-methods.mdx
This commit adds some cross-references to the "EDB Advanced Storage Pack" documentation, which contains further information about the respective table access methods.
It also clarifies the procedure for installing the extensions on a PGD cluster, in particular emphasising that "shared_preload_libraries" needs to be configured on each node, whereas the "CREATE EXTENSION" command only needs to be executed on one node.
BDR-5140.
> PGD: clarify table access method extension usage

- product_docs/docs/pgd/5/consistency/conflicts.mdx
Reworked section in question to note that origin conflict, not version conflict is the default.
> Docs-670-redux - corrections post feedback

- product_docs/docs/biganimal/release/getting_started/02_connecting_to_your_cloud/connecting_aws.mdx
- product_docs/docs/biganimal/release/getting_started/02_connecting_to_your_cloud/connecting_azure.mdx
- product_docs/docs/biganimal/release/getting_started/02_connecting_to_your_cloud/connecting_gcp.mdx
- product_docs/docs/biganimal/release/getting_started/creating_a_cluster/index.mdx
- product_docs/docs/biganimal/release/getting_started/index.mdx
- product_docs/docs/biganimal/release/getting_started/overview.mdx
- product_docs/docs/biganimal/release/getting_started/preparing_cloud_account/01_preparing_azure/index.mdx
- product_docs/docs/biganimal/release/getting_started/preparing_cloud_account/02_preparing_aws.mdx
- product_docs/docs/biganimal/release/getting_started/preparing_cloud_account/preparing_gcp/index.mdx
- product_docs/docs/biganimal/release/overview/additional_tools.mdx
- product_docs/docs/biganimal/release/overview/index.mdx
- product_docs/docs/biganimal/release/overview/support/index.mdx
This is a collection of edits and new material based on documents Sales and CS uses for new customers. Most of the information in the sales/CS docs already appears in the BigAnimal technical documentation, but I've added a few pieces in information here and there. The main change is that I created a new overview topic in the "Getting started" section to supplement some of the existing getting started information, which seems a big disjointed.
Addresses: https://enterprisedb.atlassian.net/browse/DOCS-155
> Integrate CS and Sales articles into technical documentation

- product_docs/docs/eprs/7/installing/index.mdx
- product_docs/docs/eprs/7/supported_platforms.mdx
https://enterprisedb.atlassian.net/browse/DOCS-784
I deleted all mentions of Windows 19 in */eprs/7/* documentation.
> Replication Server: Removed Windows 19 versions due to end-of-support

- advocacy_docs/community/contributing/styleguide.mdx
Added clarification on future tense, conditional tense, and contractions. Cleaned up the rest of the text to better adhere to our style guide.
> Edits to style guide

- product_docs/docs/pgd/5/deploy-config/deploy-biganimal/index.mdx
- product_docs/docs/pgd/5/deploy-config/deploy-kubernetes/index.mdx
- product_docs/docs/pgd/5/deploy-config/deploy-tpa/deploying/01-configuring.mdx
- product_docs/docs/pgd/5/deploy-config/deploy-tpa/deploying/02-deploying.mdx
- product_docs/docs/pgd/5/deploy-config/deploy-tpa/deploying/index.mdx
- product_docs/docs/pgd/5/deploy-config/deploy-tpa/index.mdx
- product_docs/docs/pgd/5/deploy-config/index.mdx
- product_docs/docs/pgd/5/durability/administering.mdx
- product_docs/docs/pgd/5/durability/camo.mdx
> Re-edit of PGD - third set of edits

- product_docs/docs/migration_toolkit/55/06_building_toolkit.properties_file.mdx
The user does not require DBA privileges for the SRC_DB_USER parameter. This PR updates the documentation to reflect the actual privileges it requires.
https://enterprisedb.atlassian.net/browse/DOCS-783
> Migration Toolkit: SRC_DB_USER role

- src/components/search/index.js
- src/pages/404.js
- src/pages/search.js
Disable search insights - it's suddenly generating endless view events and crashing browsers
> Release: 2024-07-01c

- product_docs/docs/pgd/5/repsets.mdx
Fix image path (was now in planning section images)
> DOCS-804 Broken architecture image in rep sets docs

- product_docs/docs/pgd/5/durability/legacy-sync.mdx
- product_docs/docs/pgd/5/durability/limitations.mdx
- product_docs/docs/pgd/5/durability/overview.mdx
- product_docs/docs/pgd/5/monitoring/index.mdx
- product_docs/docs/pgd/5/monitoring/otel.mdx
- product_docs/docs/pgd/5/node_management/heterogeneous_clusters.mdx
- product_docs/docs/pgd/5/node_management/index.mdx
- product_docs/docs/pgd/5/node_management/node_recovery.mdx
> PGD re-edit group 5

- product_docs/docs/migration_toolkit/55/07_invoking_mtk/08_mtk_command_options.mdx
https://enterprisedb.atlassian.net/browse/DOCS-795
When `-allSchemas` is enabled, the referenced objects (tables, views, procs, etc.) must be schema-qualified. I added examples and clarifying phrasing around this to each section the `-allSchemas` applies to.
> Migration Toolkit: schema-qualified command-line options

- install_template/templates/products/postgres-enterprise-manager-server/debian-11.njk
- install_template/templates/products/postgres-enterprise-manager-server/ubuntu-20.04.njk
- install_template/templates/products/postgres-enterprise-manager-server/ubuntu-22.04.njk
- product_docs/docs/pem/8/installing/linux_x86_64/pem_debian_10.mdx
- product_docs/docs/pem/8/installing/linux_x86_64/pem_debian_11.mdx
- product_docs/docs/pem/8/installing/linux_x86_64/pem_ubuntu_20.mdx
- product_docs/docs/pem/8/installing/linux_x86_64/pem_ubuntu_22.mdx
- product_docs/docs/pem/9/installing/linux_x86_64/pem_debian_11.mdx
- product_docs/docs/pem/9/installing/linux_x86_64/pem_ubuntu_20.mdx
- product_docs/docs/pem/9/installing/linux_x86_64/pem_ubuntu_22.mdx
Fix a few un-indented un-closed admonitions. These weren't causing rendering issues due to their location in list items, but they were causing distracting warnings and could trip us up in the future.
> Correct the formatting of admonitions in pem installation docs

- product_docs/docs/pgd/3.7/bdr/column-level-conflicts.mdx
- product_docs/docs/pgd/4/bdr/column-level-conflicts.mdx
- product_docs/docs/pgd/4/bdr/ddl.mdx
- product_docs/docs/pgd/5/consistency/column-level-conflicts.mdx
- product_docs/docs/pgd/5/ddl/ddl-pgd-functions-like-ddl.mdx
Following functions:
- `bdr.column_timestamps_disable()`
- `bdr.column_timestamps_enable()`
were marked as deprecated in BDR 3.7. Their functionality is covered by the more general function `bdr.alter_table_conflict_detection()`.
However, the experimental commit timestamp feature (in place of the default current timestamp) can only be specified with `bdr.column_timestamps_enable()`, so note that.
BDR-5175
> pgd: note deprecation of bdr.column_timestamps_{disable|enable() functions

- product_docs/docs/efm/4/efm_deploy_arch/03_efm_vip.mdx
- product_docs/docs/efm/4/efm_deploy_arch/04_efm_client_connect_failover.mdx
- product_docs/docs/efm/4/efm_deploy_arch/05_efm_pgbouncer.mdx
- product_docs/docs/efm/4/efm_deploy_arch/06_efm_pgpool.mdx
From slack conversation:
https://edb.slack.com/archives/CU5QEU5L7/p1721927285903279
I suggest we add a compatibility matrix so customers can know how to "mix and match" EPAS versions with EFM versions (what is supported and has been tested?).
> Remove version-specific releases from Replication Manager documentation

- product_docs/docs/pgbouncer/1/pgbouncer_rel_notes/09_11610_rel_notes.mdx
- product_docs/docs/pgbouncer/1/pgbouncer_rel_notes/12300_rel_notes.mdx
- product_docs/docs/pgbouncer/1/pgbouncer_rel_notes/index.mdx
- product_docs/docs/pgbouncer/1/supported_platforms.mdx
New upstream merge of PgBouncer https://enterprisedb.atlassian.net/browse/RL-177 
Also edited the 1.16.1.0 topic title, as it said 1.16.0.0 when referring to a 1.16.1.0 release.
> EDB PgBouncer 1.23 release

- product_docs/docs/epas/16/upgrading/minor_upgrade/05_performing_a_minor_version_update_of_an_rpm_installation.mdx
> Edits to EPAS minor upgrades: replaced yum with dnf #5841

- install_template/config.yaml
- install_template/templates/products/edb-postgres-extended-server/index.njk
- install_template/templates/products/postgres-enterprise-manager-server/base.njk
- product_docs/docs/pem/9/installing/linux_arm64/pem_debian_12.mdx
- product_docs/docs/pem/9/installing/linux_ppc64le/pem_rhel_8.mdx
- product_docs/docs/pem/9/installing/linux_ppc64le/pem_rhel_9.mdx
- product_docs/docs/pem/9/installing/linux_ppc64le/pem_sles_12.mdx
- product_docs/docs/pem/9/installing/linux_ppc64le/pem_sles_15.mdx
- product_docs/docs/pem/9/installing/linux_x86_64/pem_debian_11.mdx
- product_docs/docs/pem/9/installing/linux_x86_64/pem_debian_12.mdx
- product_docs/docs/pem/9/installing/linux_x86_64/pem_other_linux_8.mdx
- product_docs/docs/pem/9/installing/linux_x86_64/pem_other_linux_9.mdx
- product_docs/docs/pem/9/installing/linux_x86_64/pem_rhel_8.mdx
- product_docs/docs/pem/9/installing/linux_x86_64/pem_rhel_9.mdx
- product_docs/docs/pem/9/installing/linux_x86_64/pem_sles_12.mdx
- product_docs/docs/pem/9/installing/linux_x86_64/pem_sles_15.mdx
- product_docs/docs/pem/9/installing/linux_x86_64/pem_ubuntu_20.mdx
- product_docs/docs/pem/9/installing/linux_x86_64/pem_ubuntu_22.mdx
- product_docs/docs/pge/15/installing/index.mdx
- product_docs/docs/pge/16/installing/index.mdx
One link (per installation target) was pointing to PEM 8. This was always incorrect; now it also does not work.
> Fix PEM installer links

- product_docs/docs/pem/9/pem_rel_notes/970_rel_notes.mdx
- product_docs/docs/pem/9/registering_agent.mdx
Due to an issue with the implementation,
we do not wish to document this as an official feature of PEM 9.7.0 at this time
> Remove mentions of multihost support from agent to server

- product_docs/docs/efm/4/04_configuring_efm/01_cluster_properties.mdx
I think something automated clobbered this, because the descriptive text and the property comment description both were garbled. The descriptive text now makes sense again, though it's a long sentence and I'm open to suggestions.
I changed "update" to "set" because there isn't actually a list to update since the cluster doesn't exist before starting this node. Am ok with going back though.
> fix efm auto.allow.hosts property description

- product_docs/docs/pgd/5/scaling.mdx
In https://www.enterprisedb.com/docs/pgd/latest/scaling/.
> Fix backtick line formatting

- product_docs/docs/eprs/7/05_smr_operation/03_creating_subscription/02_adding_subscription_database.mdx
- product_docs/docs/eprs/7/07_common_operations/09_offline_snapshot.mdx
https://enterprisedb.atlassian.net/browse/DOCS-950
https://enterprisedb.atlassian.net/browse/XDB-2225
- Subscription creation must happen before any other subscription objects are added. ➡️  steps have been swapped in the order. 
- Subscription creation must happen before any synchronization attempts. ➡️ added note
- As a standard in documentation, we should refrain from referring to specific numbered steps (e.g. repeat steps 5-10 for each new node). This increases the risk of steps moving, being added or deleted and the docs becoming outdated ➡️  Added level 3 headings (h3) to separate what must happen once vs. what mus happen several times for each subscription, so we don't have to refer to the step numbers. 
- Fixed a typo and improved introductory phrase on the …
> EPRS: fix to offline snapshot steps

- product_docs/docs/pgd/5/known_issues.mdx
It looks like there was a Known Issue left over from PGD version 4 that made it into 5, even though things had changed for 5. Namely, it was the case in version 4 that Group Commit was incompatible with Eager Replication, but now it is actually a conflict resolution option of Group Commit, replacing the global scope: "The global scope no longer exists. To create scope with the same behavior, use [Group Commit](https://www.enterprisedb.com/docs/pgd/latest/durability/group-commit/)."
> Changed wording to remove references to Eager All-Node Replication from Known Issue

- product_docs/docs/pem/9/monitoring_performance/probes.mdx
Added remaining probe examples to the Target type table as per [PEM-5115](https://enterprisedb.atlassian.net/browse/PEM-5115)
[PEM-5115]: https://enterprisedb.atlassian.net/browse/PEM-5115?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> PEM - Probes target type fix

- advocacy_docs/edb-postgres-ai/migration-etl/data-migration-service/getting_started/mark_completed.mdx
Adding some information regarding the point in time when a customer should stop the migration. 
In the future, the team will add statuses in the UI for this. For now, we are just adding some information for clarity.
> DMS: migration stop

- advocacy_docs/edb-postgres-ai/migration-etl/data-migration-service/getting_started/config_reader.mdx
At the moment, the staging environment string links to a page in our _preview_ documentation. 
After we go live, the string should link to the _live_ documentation. 
I have set up a permanent URL that we can embed in the UI, so the link does not become outdated, and we can change the content/location of the page without worrying about breaking links. 
The link the UI team can embed to the string will be: 
https://www.enterprisedb.com/docs/purl/dms/configure_source
> DMS: added purl for UI link

- product_docs/docs/pgd/5/monitoring/sql.mdx
- product_docs/docs/pgd/5/reference/functions.mdx
From 5.0, BDR GUC "bdr.raft_election_timeout" is obsolete and has been replaced by "bdr.raft_global_election_timeout", so update the remaining references in the PGD 5 docs.
DOCS-1024.
> PGD: fix references to deprecated GUC "bdr.raft_election_timeout"

- product_docs/docs/pgd/5/reference/functions.mdx
Current doc: https://www.enterprisedb.com/docs/pgd/latest/reference/functions/#transaction_id
This is only queryable as a reported GUC via libpq's PQparameterStatus() function, and is never accessible at SQL level. Rewrite the description to clarify this, linking to a helpful code example while we're at it.
Also rework the introductory section to make it clearer that one of the GUC-like objects about to be described is not query-able via SQL.
DOCS-1028.
> PGD: improve description of "transaction_id" pseudo-GUC

- product_docs/docs/pgd/5/reference/index.json
- product_docs/docs/pgd/5/reference/index.mdx
- product_docs/docs/pgd/5/reference/pgd-settings.mdx
> Fixed references to bdr.raft_local_election_timeout in the docs.

- product_docs/docs/pgd/5.6/reference/functions.mdx
Current doc: https://www.enterprisedb.com/docs/pgd/latest/reference/functions/#transaction_id
This is only queryable as a reported GUC via libpq's PQparameterStatus() function, and is never accessible at SQL level. Rewrite the description to clarify this, linking to a helpful code example while we're at it.
Also rework the introductory section to make it clearer that one of the GUC-like objects about to be described is not query-able via SQL.
5.6 port of PR #6048.
DOCS-1028.
> PGD: improve description of "transaction_id" pseudo-GUC (5.6)

- product_docs/docs/epas/11/epas_compat_sql/21_create_public_database_link.mdx
> Fixing up from review

- advocacy_docs/edb-postgres-ai/console/estate/agent/install-agent.mdx
The previous example doesn't work due to the improper indentation.
Update the indentation for the example yaml file
> Update indentation for the example yaml file

- advocacy_docs/community/contributing/styleguide.mdx
Since page descriptions are being used to dynamically add summary tiles to index pages, we should probably make frontmatter descriptions obligatory. I think we should then also make full stops for descriptions a style guide requirement, so that tiles look consistent when displayed next to other pages' descriptions. 
See screenshot for example:
E.g. 
WDYT?
> Style guide: full stop in frontmatter descriptions

- product_docs/docs/pgd/5/node_management/creating_and_joining.mdx
- product_docs/docs/pgd/5/security/role-management.mdx
If a node is joined with a user who does not have superuser permissions, the presence of any extensions on the source node which require superuser permissions to install, will cause the join operation to fail.
Clarify that such extensions will need to be created manually on the joining node if the user is not a superuser.
Note: this is one of those situation which gets kind of wordy to explain, improvements welcome.
[BDR-5519](https://enterprisedb.atlassian.net/browse/BDR-5519).
[BDR-5519]: https://enterprisedb.atlassian.net/browse/BDR-5519?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> pgd: clarify joining nodes with non-default extensions

- product_docs/docs/migration_toolkit/55/06_building_toolkit.properties_file.mdx
- product_docs/docs/migration_toolkit/55/07_invoking_mtk/08_mtk_command_options.mdx
- product_docs/docs/migration_toolkit/55/07_invoking_mtk/index.mdx
- product_docs/docs/migration_toolkit/55/07_invoking_mtk/mtk_command_options_in_file/creating_txt_file.mdx
- product_docs/docs/migration_toolkit/55/07_invoking_mtk/mtk_command_options_in_file/executing_migration_with_txt.mdx
- product_docs/docs/migration_toolkit/55/09_mtk_errors.mdx
- I created a new section dedicated to schema_scope [here](https://deploy-preview-6032--edb-docs-staging.netlify.app/docs/migration_toolkit/latest/07_invoking_mtk/#migrating-schemas), where I added an overview table with the three possibilities per OS (single schema, multiple schemas, all schemas). 
- I added examples for each of the three schema scope variations in expandable sections for [migrations from Oracle](https://deploy-preview-6032--edb-docs-staging.netlify.app/docs/migration_toolkit/latest/07_invoking_mtk/#migrating-schemas) and also for migrations from [non-Oracle](https://deploy-preview-6032--edb-docs-staging.netlify.app/docs/migration_toolkit/latest/07_invoking_mtk/#migrating-schemas-from-a-non-oracle-source-database). I did this using expandable snippets. 
- The original …
> Included schema scope options for `-allSchemas` and multiple schemas on Invoking MTK page

- advocacy_docs/supported-open-source/postgresql/installing/windows.mdx
Removed bold-italic emphasis. If there's something that needs to be called out here, use additional words rather than emphasis, which we don't have any standard for, and it doesn't seem apt in this case anyhow. For example, you could do something like this:
- If you're using the installation wizard to perform a system upgrade rather than a fresh install...
The added context will provide the emphasis if the concern is that readers might not see that this is referring to an upgrade. Alternatively, keep this text in its own note rather than combining with the new one and place each note more precisely within the content.
> Edits to Added note on non-ascii characters not being supported PR6024

- product_docs/docs/pgd/5/appusage/extensions.mdx
- product_docs/docs/pgd/5/appusage/index.mdx
The subject of installing other extensions in a PGD cluster has come up a couple of times recently, but the documentation doesn't really say much about it, so add a section discussing various relevant issues etc., and also explicitly list the extensions which are known to be compatible.
BDR-5141.
> PGD: add documentation section considering extension usage

- advocacy_docs/dev-guides/deploy/images/pgadmin-connected.png
- advocacy_docs/dev-guides/deploy/images/pgadmin-default.png
- advocacy_docs/dev-guides/deploy/images/pgadmin-register-server.png
- advocacy_docs/dev-guides/deploy/windows.mdx
- advocacy_docs/edb-postgres-ai/migration-etl/data-migration-service/index.mdx
- advocacy_docs/edb-postgres-ai/migration-etl/data-migration-service/known_issues.mdx
- advocacy_docs/edb-postgres-ai/migration-etl/data-migration-service/limitations.mdx
- advocacy_docs/supported-open-source/postgresql/installing/windows.mdx
- product_docs/docs/epas/12/epas_compat_sql/21_create_public_database_link.mdx
- product_docs/docs/epas/13/epas_compat_sql/21_create_public_database_link.mdx
- product_docs/docs/epas/14/epas_compat_sql/21_create_public_database_link.mdx
- product_docs/docs/epas/14/epas_guide/03_database_administration/04_pgsnmpd.mdx
- product_docs/docs/epas/15/reference/oracle_compatibility_reference/epas_compat_sql/21_create_public_database_link.mdx
- product_docs/docs/epas/16/reference/oracle_compatibility_reference/epas_compat_sql/21_create_public_database_link.mdx
- product_docs/docs/eprs/7/07_common_operations/09_offline_snapshot.mdx
- product_docs/docs/migration_toolkit/55/06_building_toolkit.properties_file.mdx
- product_docs/docs/migration_toolkit/55/07_invoking_mtk/08_mtk_command_options.mdx
- product_docs/docs/migration_toolkit/55/07_invoking_mtk/index.mdx
- product_docs/docs/migration_toolkit/55/07_invoking_mtk/mtk_command_options_in_file/creating_txt_file.mdx
- product_docs/docs/migration_toolkit/55/07_invoking_mtk/mtk_command_options_in_file/executing_migration_with_txt.mdx
- product_docs/docs/migration_toolkit/55/09_mtk_errors.mdx
- product_docs/docs/pgd/5/appusage/extensions.mdx
- product_docs/docs/pgd/5/appusage/index.mdx
- product_docs/docs/pgd/5/node_management/creating_and_joining.mdx
- product_docs/docs/pgd/5/security/role-management.mdx
- tools/user/mergeq/.gitignore
- tools/user/mergeq/README.md
- tools/user/mergeq/mergeq.js
- tools/user/mergeq/package-lock.json
- tools/user/mergeq/package.json
#6107 : Adding mergeq tool
#5789 : PGD: add documentation section considering extension usage
#6093 : Update 04_pgsnmpd.mdx
#6078 : Edits to EPRS: fix to offline snapshot steps PR5985
#6090 : Edits to Added note on non-ascii characters not being supported PR6024
#6063 : PostgreSQL on Windows dev env topic
#6032 : Included schema scope options for `-allSchemas` and multiple schemas on Invoking MTK page
#6100 : Removed "Known Issues" section and altered "Limitations" page title
#6094 : EPAS - Added oracle 21c
#6099 : pgd: clarify joining nodes with non-default extensions
> Release 2024-09-30a

- product_docs/docs/efm/4/06_monitoring_efm_cluster.mdx
This column was removed ~4 years ago, see EFM-993.
> EFM-1698 Remove "Agent" column from cluster-status output.

- product_docs/docs/pgd/5/reference/functions-internal.mdx
> Edits to Rework bdr.drop_node PGD pr6056

- product_docs/docs/postgres_for_kubernetes/1/security.mdx
Added new admonition regarding outdated images and security risks to PG4K docs. This forks from upstream and will no longer automatically receive upstream changes.
> Added new admonition regarding outdated images and security risks to PG4K docs.

- product_docs/docs/postgis/3/installing/upgrading.mdx
- product_docs/docs/postgis/3/supported_platforms.mdx
- Updated support matrix with a row for 3.4.2 and a column for EPAS 16. Removed EPAS 11 column. 
- Replaced `yum` instances with `dnf` as it is the current package manager
- Updated upgrade example and included a note clarifying that the example applies to all upgrades from versions after 3.1.4. 
https://enterprisedb.atlassian.net/browse/DB-2753
> PostGIS: 3.4 updates

- product_docs/docs/livecompare/3/command_line_usage.mdx
- product_docs/docs/livecompare/3/installation.mdx
Added basic template and supporting content to command line usage page.
> docs-1082 - LiveCompare Docs update

- product_docs/docs/migration_toolkit/55/07_invoking_mtk/08_mtk_command_options.mdx
https://enterprisedb.atlassian.net/browse/MTK-392 
Adding note for migrations from Oracle, as additional user privileges are required.
> MTK: Privileges for using parallel loading in migrations from Oracle

- product_docs/docs/pgd/5.6/reference/catalogs-visible.mdx
Added milliseconds to the description of double precision types in 5.6 docs for new commit scope statistics views
> Added milliseconds to description of double precision types in 5.6 docs for new commit scope statistics views

- tools/user/import/bareleasenotes/barelease.js
Switched the BigAnimal naming to CloudService in the generated output.
> Fix releasenotes gen for cloud service

- product_docs/docs/migration_toolkit/55/07_invoking_mtk/08_mtk_command_options.mdx
https://enterprisedb.atlassian.net/browse/DOCS-1019 
Added `-mapVirtualToRegular` to the MTK command options. Added a description of the flag, use cases, and an example. Release notes entry will be handled separately. 
This is a v55.10.0 feature. 
I have created a `DOCS-1088-Tracking-55.10-work` release branch to stage all 55.10.0 work.
This PR is branched off of said release branch, so once we get reviews and approvals, we can merge to the release branch, which will be staged and remain unmerged until release time.
> MTK 55.10.0: computed columns

- static/_redirects
Was preventing fine-grained redirects from working!
> Remove BA catch-all redirect - is being too greedy

- static/_redirects
- Remove catch-all redirect for /docs/biganimal/* path until we can ensure it isn't too greedy!
> Release: 2024-11-05b

- advocacy_docs/pg_extensions/pg_failover_slots/rel_notes/index.mdx
- advocacy_docs/pg_extensions/pg_failover_slots/rel_notes/pg_failover_slots_1.1.0_rel_notes.mdx
> Docs 1095 pg failover slots v110

- advocacy_docs/security/assessments/cve-2020-10531.mdx
- advocacy_docs/security/assessments/index.mdx
- advocacy_docs/security/index.mdx
- tools/automation/generators/advisoryindex/advisoryindex.js
> Minimal update for security

- product_docs/docs/pgd/5.6/conflict-management/conflicts/02_types_of_conflict.mdx
- product_docs/docs/pgd/5.6/reference/conflicts.mdx
[DOCS-1080
](https://enterprisedb.atlassian.net/browse/DOCS-1080)
Updating 5.6 docs to reflect multi-row conflicts possibility given unblocked EXCLUDE constraints in 5.6.
> Update 5.6 docs to reflect multi-row conflicts possibility given unblocked EXCLUDE constraints in 5.6

- product_docs/docs/net_connector/8.0.5.1/index.mdx
- product_docs/docs/net_connector/8.0.5.1/using_nested_table_types.mdx
https://enterprisedb.atlassian.net/browse/EC-3206
> dotNET: added page for nested table support

- product_docs/docs/eprs/7/01_introduction/03_certified_supported_versions.mdx
Short PR that adds PostgreSQL 17 and EPAS 17 to the supported database versions. 
https://enterprisedb.atlassian.net/browse/DOCS-975 
This PR can be merged to the eprs_7.10 release branch, where the content will be staged until release.
> EPRS: added PG and EPAS 17 support

- product_docs/docs/pgd/5.6/commit-scopes/camo.mdx
- product_docs/docs/pgd/5.6/commit-scopes/commit-scopes.mdx
- product_docs/docs/pgd/5.6/commit-scopes/group-commit.mdx
- product_docs/docs/pgd/5.6/commit-scopes/lag-control.mdx
- product_docs/docs/pgd/5.6/commit-scopes/origin_groups.mdx
- product_docs/docs/pgd/5.6/commit-scopes/synchronous_commit.mdx
- product_docs/docs/pgd/5.6/known_issues.mdx
- product_docs/docs/pgd/5.6/reference/commit-scopes.mdx
- product_docs/docs/pgd/5.6/reference/functions.mdx
- product_docs/docs/pgd/5.6/reference/index.json
- product_docs/docs/pgd/5.6/reference/index.mdx
- product_docs/docs/pgd/5.6/upgrades/compatibility.mdx
Fixed all add_commit_scope references to create_commit_scope references.
(No functional change in command)
Update: Sideeffect removed in create_commit_scope so no silent overwriting.
> Switched add_commit_scope to create_commit_scope and added reference notes

- product_docs/docs/eprs/7/eprs_rel_notes/eprs_rel_notes_7.10.0.mdx
- product_docs/docs/eprs/7/eprs_rel_notes/index.mdx
https://enterprisedb.atlassian.net/browse/XDB-2311
Added release notes for EPRS. This can be merged to the release branch `eprs_7.10` upon approval to be staged before pushing to production.
> EPRS: added relase notes for 7.10

- product_docs/docs/migration_toolkit/55/mtk_rel_notes/index.mdx
- product_docs/docs/migration_toolkit/55/mtk_rel_notes/mtk_55100_rel_notes.mdx
https://enterprisedb.atlassian.net/browse/MTK-1423
This can be merged to the release branch at any time, where it will be staged until we get the green light to publish.
> MTK: release notes for 55.10.0

- product_docs/docs/pgd/5.6/commit-scopes/group-commit.mdx
- product_docs/docs/pgd/5/durability/group-commit.mdx
> Mark group-commit.mdx with warning

- product_docs/docs/migration_toolkit/55/06_building_toolkit.properties_file.mdx
- product_docs/docs/migration_toolkit/55/09_mtk_errors.mdx
https://enterprisedb.atlassian.net/browse/DOCS-1111
Originated from Slack convo, see Jira for more details.
> MTK: added note on unquoted password for toolkit-properties

- product_docs/docs/pgd/5.6/nodes/subscriber_only/optimizing-so.mdx
> Edits to Fix default setting and type for force_full_mesh. #6188

- product_docs/docs/eprs/7/01_introduction/03_certified_supported_versions.mdx
- product_docs/docs/eprs/7/eprs_rel_notes/eprs_rel_notes_7.10.0.mdx
- product_docs/docs/eprs/7/eprs_rel_notes/index.mdx
https://enterprisedb.atlassian.net/browse/DOCS-1092 
This branch tracks all the work that will go out with EPRS 7.10.
This covers:
https://enterprisedb.atlassian.net/browse/DOCS-975 approved
https://enterprisedb.atlassian.net/browse/XDB-2311 approved
Tentatively going out on 21st Nov or 22nd.
> EPRS 7.10 release branch

- product_docs/docs/pgd/3.6/index.mdx
- product_docs/docs/pgd/3.7/index.mdx
- product_docs/docs/pgd/4/overview/index.mdx
- product_docs/docs/pgd/5.6/overview/index.mdx
- product_docs/docs/pgd/5/overview/index.mdx
Replace links to legacy, non-existent portal page with a direct reference to the public documentation, as is done with EPAS.
DOCS-1134
> PGD: Fix link to EDB Postgres Extended Server

- product_docs/docs/livecompare/3/command_line_usage.mdx
Minor edit to correct spelling of "misspelling" and a couple other small edits.
> Edits to docs-1082 - LiveCompare Docs update #6157

- product_docs/docs/pge/17/installing/component_locations.mdx
- product_docs/docs/pge/17/upgrading/major_upgrade.mdx
- product_docs/docs/pge/17/upgrading/minor_upgrade/apt_upgrade.mdx
- product_docs/docs/pge/17/upgrading/minor_upgrade/dnf_upgrade.mdx
Bumping the version number from 16 to 17 in the new documentation folder added for 17.2. 
Also updated the examples in the upgrade topic to go from 15>16 to 16>17.
> PGE 17: version bumps

- product_docs/docs/migration_portal/4/01_mp_release_notes/index.mdx
- product_docs/docs/migration_portal/4/01_mp_release_notes/mp_4.12.0_rel_notes.mdx
- product_docs/docs/migration_portal/4/02_supported_platforms.mdx
https://enterprisedb.atlassian.net/browse/MIG-5318
- added release notes for 4.12.0 
- updated supported databases list 
- set release date to 25 Nov, but we can update it if the date changes
> Migration Portal: 4.12.0 release

- product_docs/docs/edb_plus/41/02_release_notes/edbplus_41.3_rel_notes.mdx
- product_docs/docs/edb_plus/41/02_release_notes/index.mdx
- product_docs/docs/edb_plus/41/02a_supported_platforms.mdx
- product_docs/docs/edb_plus/41/04_using_edb_plus.mdx
- product_docs/docs/edb_plus/41/05_using_edb_plus_with_ssl.mdx
- product_docs/docs/edb_plus/41/06_command_summary.mdx
https://enterprisedb.atlassian.net/browse/ED-301
https://enterprisedb.atlassian.net/browse/DOCS-1124
- adds release notes 
- bumps versions in code snippets
- updates compatibility/supported dbs page
Planned for 27 Nov, possibly later.
> EDBPlus 41.3.0: release notes, version bumps, supported dbs

- product_docs/docs/efm/4/06_monitoring_efm_cluster.mdx
This leaves the existing info mostly alone, but adds an explanation of the Promote Status output and why it's there. The info that efm collects here is all related to whether or not a promotion would be safe (or a switchover allowed) and how a standby would be picked. It's not meant to be the place a user monitors replication. The existing text goes into detail a little about this, but the new text explains why this particular info is here if not meant to check replication.
> Added info about the Promote Status section of cluster status output

- src/pages/index.js
Puts PGD on the front page twice to avoid confusion
> Add PGD to HA Platform/Tools section on front page

- product_docs/docs/pgd/5.6/upgrades/manual_overview.mdx
- product_docs/docs/pgd/5.6/upgrades/tpa_overview.mdx
- product_docs/docs/pgd/5/upgrades/manual_overview.mdx
- product_docs/docs/pgd/5/upgrades/tpa_overview.mdx
* clarify the warning to always test the upgrade process.
* update version numbers in the upgrade process example
> Tweak upgrade warning for clarity, update version number in example.

- advocacy_docs/pg_extensions/pg_failover_slots/rel_notes/pg_failover_slots_1.1.0_rel_notes.mdx
> Edits to Docs 1095 pg failover slots v110 #6202

- product_docs/docs/pgd/5.6/quickstart/connecting_applications.mdx
TPA changes Docker IP addresses
This brings the IP addresses in sync again.
> Fix IP addresses for Docker

- product_docs/docs/pgd/5.6/terminology.mdx
The current documentation describes a "cluster" as a group of "multiple redundant systems," which is not universally accurate in the broader computing context. Clusters are generally defined as a group of interconnected systems working together to function as a single cohesive unit. While redundancy may be a feature of some clusters, it is not inherent to the definition. This change revises the wording to reflect a more accurate and generic definition of a cluster in computing.
Cluster
Generically, a cluster is a group of multiple redundant systems arranged to appear to end users as one system. See also [PGD cluster](https://www.enterprisedb.com/docs/pgd/latest/terminology/#pgd-cluster) and [Postgres cluster](https://www.enterprisedb.com/docs/pgd/latest/terminology/#postgres-cluster).
--> …
> Update cluster definition in  terminology.mdx

- product_docs/docs/pge/13/release_notes/index.mdx
Minor fix due to PGE using `MAJOR.MINOR` versioning for 13.x and earlier versions, unlike EPAS, that uses `MAJOR.MINOR.PATCH` semantic versioning in versions 13 and earlier.
> PGE 13.x: corrected semantic versioning

- product_docs/docs/tde/15/enabling/enabling_key_wrapper.mdx
- product_docs/docs/tde/15/enabling/index.mdx
- product_docs/docs/tde/15/secure_key/disabling_key.mdx
- product_docs/docs/tde/15/secure_key/passphrase.mdx
https://enterprisedb.atlassian.net/browse/DOCS-1147 
All feedback related to the streamlining of documentation was already introduced in https://github.com/EnterpriseDB/docs/pull/6342 
This PR focuses on introducing a new tutorial for enabling key wrapping and a section for assigning a passphrase as a key wrapper via file.
> TDE: tutorials to enable data wrapper and provide passphrase in file

- product_docs/docs/postgres_for_kubernetes/1/iron-bank.mdx
[DOCS-776](https://enterprisedb.atlassian.net/browse/DOCS-776)
- Made mention that EPAS operands can now be pulled and used from the Iron Bank
- Added a section for deploying with the downloaded operand image
[DOCS-776]: https://enterprisedb.atlassian.net/browse/DOCS-776?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Ironbank now supports EPAS operands

- product_docs/docs/mongo_data_adapter/5/06_features_of_mongo_fdw.mdx
Added documentation for accessing subfields in Mongo BSON documents using Mongo FDW.
[DOCS-1142
](https://enterprisedb.atlassian.net/browse/DOCS-1142)
> Added documentation for sub-JSON accessing feature in Mongo FDW Key Features

- advocacy_docs/pg_extensions/pg_failover_slots/configuring.mdx
- advocacy_docs/pg_extensions/pg_failover_slots/index.mdx
add note to avoid create extension cmd
> docs-1149: add note to avoid create extension cmd

- product_docs/docs/epas/17/epas_rel_notes/epas17_2_rel_notes.mdx
- product_docs/docs/epas/17/reference/oracle_compatibility_reference/epas_compat_bip_guide/03_built-in_packages/18_dbms_xmldom/appendchild.mdx
- product_docs/docs/epas/17/reference/oracle_compatibility_reference/epas_compat_bip_guide/03_built-in_packages/18_dbms_xmldom/createelement.mdx
- product_docs/docs/epas/17/reference/oracle_compatibility_reference/epas_compat_bip_guide/03_built-in_packages/18_dbms_xmldom/createtextnode.mdx
- product_docs/docs/epas/17/reference/oracle_compatibility_reference/epas_compat_bip_guide/03_built-in_packages/18_dbms_xmldom/freedocument.mdx
- product_docs/docs/epas/17/reference/oracle_compatibility_reference/epas_compat_bip_guide/03_built-in_packages/18_dbms_xmldom/getattribute.mdx
- product_docs/docs/epas/17/reference/oracle_compatibility_reference/epas_compat_bip_guide/03_built-in_packages/18_dbms_xmldom/getchildnodes.mdx
- product_docs/docs/epas/17/reference/oracle_compatibility_reference/epas_compat_bip_guide/03_built-in_packages/18_dbms_xmldom/getfirstchild.mdx
- product_docs/docs/epas/17/reference/oracle_compatibility_reference/epas_compat_bip_guide/03_built-in_packages/18_dbms_xmldom/getlength.mdx
- product_docs/docs/epas/17/reference/oracle_compatibility_reference/epas_compat_bip_guide/03_built-in_packages/18_dbms_xmldom/getnodename.mdx
- product_docs/docs/epas/17/reference/oracle_compatibility_reference/epas_compat_bip_guide/03_built-in_packages/18_dbms_xmldom/getnodevalue.mdx
- product_docs/docs/epas/17/reference/oracle_compatibility_reference/epas_compat_bip_guide/03_built-in_packages/18_dbms_xmldom/getxmltype.mdx
- product_docs/docs/epas/17/reference/oracle_compatibility_reference/epas_compat_bip_guide/03_built-in_packages/18_dbms_xmldom/index.mdx
- product_docs/docs/epas/17/reference/oracle_compatibility_reference/epas_compat_bip_guide/03_built-in_packages/18_dbms_xmldom/item.mdx
- product_docs/docs/epas/17/reference/oracle_compatibility_reference/epas_compat_bip_guide/03_built-in_packages/18_dbms_xmldom/makeelement.mdx
- product_docs/docs/epas/17/reference/oracle_compatibility_reference/epas_compat_bip_guide/03_built-in_packages/18_dbms_xmldom/makenode.mdx
- product_docs/docs/epas/17/reference/oracle_compatibility_reference/epas_compat_bip_guide/03_built-in_packages/18_dbms_xmldom/newdomdocument.mdx
- product_docs/docs/epas/17/reference/oracle_compatibility_reference/epas_compat_bip_guide/03_built-in_packages/18_dbms_xmldom/setattribute.mdx
- product_docs/docs/epas/17/reference/oracle_compatibility_reference/epas_compat_bip_guide/03_built-in_packages/18_dbms_xmldom/setversion.mdx
> Edits to PAS: DBMS_XMLDOMDOC corrections #6290

- advocacy_docs/edb-postgres-ai/console/estate/agent/beacon-agent-ref.mdx
- advocacy_docs/edb-postgres-ai/console/estate/agent/install-agent.mdx
These changes are aligned with upcoming product capabilities.
I've also eliminated trailing whitespaces in the touched docs.
> Updates beacon agent on-prem DSN examples

- product_docs/docs/postgres_for_kubernetes/1/index.mdx
Fixed LTS status (did not appear to get imported) 
Also removed \\ from text, replaced with double spaces though maybe migrate to a bulleted list upstream?
> PG4K: Patch to correct LTS status and remove backslashes

- advocacy_docs/pg_extensions/pg_tuner/configuring.mdx
- advocacy_docs/pg_extensions/pg_tuner/rel_notes/index.mdx
- advocacy_docs/pg_extensions/pg_tuner/rel_notes/pg_tuner_1.3.0_rel_notes.mdx
- advocacy_docs/pg_extensions/pg_tuner/using.mdx
Ext 525 edb pgtuner updates / add params, functions for PG 14.
> Ext 525 edb pgtuner updates

- product_docs/docs/efm/4/installing/prerequisites.mdx
This updates the firewall prereqs text to make it clear that:
1. the port that needs to be open is the one used with the bind.address property
2. the admin.port port doesn't need to be opened.
> update firewall information for efm

- advocacy_docs/edb-postgres-ai/analytics/external_tables.mdx
When creating a storage location, all parameters are required in 0.1.x of pgaa, so make them explicit and use the `=>` syntax so that it's obvious which one goes where.
> Fix `pgaa.create_storage_location` docs

- product_docs/docs/epas/13/epas_guide/14_edb_clone_schema.mdx
- product_docs/docs/epas/14/epas_guide/14_edb_clone_schema.mdx
- product_docs/docs/epas/15/database_administration/14_edb_clone_schema/cloning_with_a_non_super_user.mdx
- product_docs/docs/epas/15/database_administration/14_edb_clone_schema/copying_a_remote_schema.mdx
- product_docs/docs/epas/15/database_administration/14_edb_clone_schema/copying_a_schema.mdx
- product_docs/docs/epas/15/database_administration/14_edb_clone_schema/edb_clone_schema_overview.mdx
- product_docs/docs/epas/15/database_administration/14_edb_clone_schema/index.mdx
- product_docs/docs/epas/15/database_administration/14_edb_clone_schema/setting_up_edb_clone_schema.mdx
- product_docs/docs/epas/16/database_administration/14_edb_clone_schema/cloning_with_a_non_super_user.mdx
- product_docs/docs/epas/16/database_administration/14_edb_clone_schema/copying_a_remote_schema.mdx
- product_docs/docs/epas/16/database_administration/14_edb_clone_schema/edb_clone_schema_overview.mdx
- product_docs/docs/epas/16/database_administration/14_edb_clone_schema/index.mdx
- product_docs/docs/epas/16/database_administration/14_edb_clone_schema/setting_up_edb_clone_schema.mdx
- product_docs/docs/epas/17/database_administration/14_edb_clone_schema/cloning_with_non_super_user.mdx
- product_docs/docs/epas/17/database_administration/14_edb_clone_schema/setting_up_edb_clone_schema.mdx
Addresses [DI-1273](https://enterprisedb.atlassian.net/browse/DI-1273)
[DI-1271]: https://enterprisedb.atlassian.net/browse/DI-1271?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DI-1273]: https://enterprisedb.atlassian.net/browse/DI-1273?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> EPAS 13 - update clone schema setup steps

- advocacy_docs/pg_extensions/index.mdx
- advocacy_docs/pg_extensions/index.mdx.in
- advocacy_docs/pg_extensions/pgaudit/configuring.mdx
- advocacy_docs/pg_extensions/pgaudit/index.mdx
- advocacy_docs/pg_extensions/pgaudit/installing.mdx
- advocacy_docs/pg_extensions/pgaudit/rel_notes/index.mdx
- advocacy_docs/pg_extensions/pgaudit/rel_notes/pgaudit_17_rel_notes.mdx
- advocacy_docs/pg_extensions/pgaudit/using.mdx
> add extension pgaudit

- advocacy_docs/pg_extensions/pg_tuner/configuring.mdx
> Edits to Ext 525 edb pgtuner updates #6366

- product_docs/docs/efm/4/installing/prerequisites.mdx
> Edits to update firewall information for efm #6390

- product_docs/docs/migration_toolkit/55/installing/installing_jdbc_driver.mdx
When working on a compatibility matrix for [DOCS-1154](https://enterprisedb.atlassian.net/browse/DOCS-1154), I realized that the MTK documentation does not clearly state that it requires not one, but two JDBC drivers. 
[DOCS-1154]: https://enterprisedb.atlassian.net/browse/DOCS-1154?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> MTK: clarify that 2 drivers are required.

- advocacy_docs/edb-postgres-ai/analytics/how_to_lakehouse_sync.mdx
- advocacy_docs/edb-postgres-ai/migration-etl/data-migration-service/index.mdx
As of 28.01.2025 Cloud Service no longer offers Data Migration Service and Lakehouse Sync capabilities. 
The Data Migration Service will only be available in HCP deployments. 
For the Lakehouse Sync, it is not yet clear if we'll eventually move it to the HCP or if there will be no support at all. 
Hence the differentiated Notice banners.  
https://enterprisedb.atlassian.net/browse/DOCS-1182
> DMS/Lakehouse Sync: removal notice

- product_docs/docs/livecompare/3/supported_technologies.mdx
Fixed versions (PG17, EPAS17, PGE17 added, 12 moved to migration only), transitioned footnotes to an explicit superscript 1 to avoid Gatsby's desire to move the footnote to the bottom of the page, not the bottom of the table.
> DOCS-1181 - LiveCompare version fixes

- product_docs/docs/postgres_for_kubernetes/1/connection_pooling.mdx
-server_tls_server_tls_protocols was changed to the correct parameter name server_tls_protocols
-I have already submitted a PR to the open source upstream repo, but in the mean time while waiting for that to merge and come downstream, I wanted the fix to be in place.
[DOCS-1164](https://enterprisedb.atlassian.net/browse/DOCS-1164)
[DOCS-1164]: https://enterprisedb.atlassian.net/browse/DOCS-1164?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fixed typo

- product_docs/docs/pem/9/profiling_workloads/installing_sql_profiler.mdx
Addresses [DOCS-808](https://enterprisedb.atlassian.net/browse/DOCS-808)
[DOCS-808]: https://enterprisedb.atlassian.net/browse/DOCS-808?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> PEM - SQL Profiler package name correction

- product_docs/docs/migration_toolkit/55/installing/installing_jdbc_driver.mdx
I was getting confused about verb agreement, so I revised the sentence to remove any doubt!
> MTK: clarify that 2 drivers are required. #6434

- product_docs/docs/migration_portal/4/known_issues_notes.mdx
I didn't see any cases where object definition was capitalized, but let me know if it should be for some reason.
> Edits to MP: terminated DDL assessment due to EPAS-reserved words #6424

- product_docs/docs/pem/9/considerations/pem_security_best_practices/pem_application_configuration.mdx
Removed SQL Protect plugin as per discussion over slack thread: https://edb.slack.com/archives/CU5QEU5L7/p1738057178153449
Added a link to SQL Protect in EPAS
> PEM 9 - Removed SQL Protect plugin

- advocacy_docs/supported-open-source/postgresql/installing/linux_x86_64/postgresql_ubuntu_20.mdx
- install_template/config.yaml
- Removed EPAS 11 and 12 from install templates.
- PostgreSQL for Ubuntu 20 was missing, but I don't think there is a reason for it to be missing.
> EPAS: removing 11 and 12 templates

- product_docs/docs/eprs/7/10_appendix/02_resolving_problems/01_error_messages.mdx
- product_docs/docs/migration_toolkit/55/09_mtk_errors.mdx
https://enterprisedb.atlassian.net/browse/DOCS-1187
https://enterprisedb.atlassian.net/browse/XDB-1512
> [XDB/MTK] Read timeout error and workaround

- product_docs/docs/net_connector/8.0.5.1/12_using_advanced_queueing.mdx
- tools/automation/actions/link-check/index.js
Fix copy-paste error in logic for checking image URLs (only applies to HTML `<img>` tags)
Also update old EPAS URL in .NET connector docs
> Fix copy-paste error in logic for checking image URLs

- product_docs/docs/epas/17/epas_rel_notes/epas17_2_rel_notes.mdx
- product_docs/docs/epas/17/epas_rel_notes/epas17_3_rel_notes.mdx
- product_docs/docs/epas/17/epas_rel_notes/index.mdx
Fixed typo and spelled out EPAS.
> Edits to EPAS - Feb 2025 Minor release #6485

- product_docs/docs/pgd/3.6/index.mdx
- product_docs/docs/pgd/3.7/index.mdx
- product_docs/docs/pgd/4/index.mdx
- src/components/left-nav.js
- src/components/version-dropdown.js
- src/templates/doc.js
The PDF generator already did this, resulting in a 404 when precise version was used - e.g. download link points to `pgd_v5_documentation.pdf` but actual filename is `pgd_v5.6.1_documentation.pdf` (reported by @pnkrepps in Slack)
Also: use path version for identifying "active" version in selector - don't round precise version, as this would fail to produce the correct results when the path version already included a minor or patch version.
Added precise version for the other published PGD versions, primarily as a more thorough testbed for this stuff, but also... a bit of consistency is nice!
> Use precise version (when available) for PDF download filename

- src/components/table-of-contents.js
- src/styles/_docs.scss
- src/styles/_overrides.scss
- src/templates/doc.js
- src/templates/learn-doc.js
This avoids pushing down the nav buttons / footer when a short page is combined with a short in-page ToC. Also,
- TOC fix for hard load
- Better breaks and min-width to avoid wasting space on sidebar at normal screen sizes
> DOCS-878: Use max-height instead of height

- advocacy_docs/pg_extensions/wait_states/installing.mdx
The rpm package name for edb_wait_states has underscores instead of dashes
> Fix package name for dnf

- product_docs/docs/eprs/7/eprs_rel_notes/eprs_rel_notes_7.11.0.mdx
- product_docs/docs/eprs/7/eprs_rel_notes/index.mdx
A few notes: 
- I replaced the "primary/secondary" wording with "primary/standby" to be consistent with #6504
-  I removed the mention of XDB-2328 ticket, as its an internal Jira ticket
https://enterprisedb.atlassian.net/browse/XDB-2355
https://enterprisedb.atlassian.net/browse/DOCS-1218
> EPRS 7.11: Added 7.11.0 release notes

- install_template/templates/products/edb*plus/index.njk
- product_docs/docs/edb_plus/41/installing/index.mdx
The link to the Windows installation page, listed Windows Server 2019, 2022, and Windows 11.  Removed Windows Server 2019 from the list and adjusted the rest of the link label accordingly since Windows Server 2019 went end of life over a year ago and we no longer support EDB*Plus or any of our products on it.
> Removed Windows Server 2019 from link

- advocacy_docs/edb-postgres-ai/ai-accelerator/models/openai-api-compatibility.mdx
I found a mistake/ambiguity in the docs for model dimensions at https://www.enterprisedb.com/docs/edb-postgres-ai/ai-accelerator/models/openai-api-compatibility/#configuration
- this implies that the setting `"dimensions":2000` will limit how many dimensions we get from the model; which isn't the case (i.e. `So we pass a dimension value of 2000 in the configuration, to get the maximum dimensions available with pgvector.`)
- text mentions that pgvector only support 2000 dimensions but that only applies to the standard index type. We don't use indexing right now so it doesn't apply to us at all. Even with indexing, you'd have to use the "halfvec" types to get more dimensions
> AI: clarify model dimensions

- product_docs/docs/pgd/5.6/index.mdx
- product_docs/docs/pgd/5.7/rel_notes/pgd_5.7.0_rel_notes.mdx
- product_docs/docs/pgd/5.7/rel_notes/src/relnote_5.7.0.yml
Fix up for release notes for 5.7.0, adding omitted note and including links.
> Docs 1229 update PGD 5.7.0 release notes

- advocacy_docs/pg_extensions/wait_states/using.mdx
EDB wait states - add links to wait event tables in PG docs.
> add links to event tables

- product_docs/docs/postgres_distributed_for_kubernetes/1/known_issues.mdx
Clarified the intent of the limitation on data migration (i.e. no declarative data migration managed by the operator) and made it clear that traditional transfers work.
> PGD4K adhoc - Data Migration update

- product_docs/docs/pgd/5.7/sequences.mdx
There is a typo in the range used for NODE2. 
The correct value should be the one in the example that is coming in the next paragraph (as fixed here):
"Node Node2 is using range from 2000334 to 4000333."
> Sequence range in node2

- advocacy_docs/edb-postgres-ai/migration-etl/data-migration-service/getting_started/config_reader.mdx
The latest reader needs the user to configure the s3/s3 compatible object storage information.
> docs(ET-1813): add object storage configuration of reader

- advocacy_docs/edb-postgres-ai/ai-accelerator/models/supported-models/embeddings.mdx
- advocacy_docs/edb-postgres-ai/ai-accelerator/models/using-models.mdx
- Removes references to unsupported text-embedding-3-large model.
> Remove references to text-embedding-3-large

- product_docs/docs/eprs/7/10_appendix/02_resolving_problems/01_error_messages.mdx
https://enterprisedb.atlassian.net/browse/XDB-2364
https://enterprisedb.atlassian.net/browse/DOCS-1257
TODO: add link to https://www.enterprisedb.com/docs/eprs/latest/05_smr_operation/01_prerequisites/04_preparing_pub_database/#oracle-publication-database
> EPRS: added workaround for ORA-17056

- advocacy_docs/edb-postgres-ai/ai-accelerator/models/supported-models/embeddings.mdx
- advocacy_docs/edb-postgres-ai/ai-accelerator/models/using-models.mdx
- product_docs/docs/epas/13/epas_compat_reference/02_the_sql_language/03_functions_and_operators/07_data_type_formatting_functions.mdx
- product_docs/docs/epas/14/epas_compat_reference/02_the_sql_language/03_functions_and_operators/07_data_type_formatting_functions.mdx
- product_docs/docs/epas/15/reference/sql_reference/03_functions_and_operators/07_data_type_formatting_functions.mdx
- product_docs/docs/epas/16/reference/sql_reference/03_functions_and_operators/07_data_type_formatting_functions.mdx
- product_docs/docs/epas/17/reference/database_administrator_reference/01_audit_logging_configuration_parameters.mdx
- product_docs/docs/epas/17/reference/sql_reference/03_functions_and_operators/07_data_type_formatting_functions.mdx
- product_docs/docs/eprs/7/10_appendix/02_resolving_problems/01_error_messages.mdx
- product_docs/docs/pgbouncer/1/pgbouncer_rel_notes/12400_rel_notes.mdx
- product_docs/docs/pgbouncer/1/pgbouncer_rel_notes/index.mdx
#6593 : EPRS: added workaround for ORA-17056
#6576 : EPAS - Update to_char(timestamptz) function from v13 to 17
#6598 : pgbouncer - release notes
#6597 : EPAS - Added JSON format to edb_audit parameter
#6595 : Remove references to text-embedding-3-large
> Production release: 2025-03-11a

- advocacy_docs/pg_extensions/ldap_sync/installing.mdx
Rather than using "Note that" in text, a potential security risk deserves to be pulled out to an admonition.
> Edits to ldap sync pr6566

- product_docs/docs/pgd/5.7/compatibility.mdx
- product_docs/docs/pgd/5.7/rel_notes/pgd_5.7.0_rel_notes.mdx
- product_docs/docs/pgd/5.7/rel_notes/src/relnote_5.7.0.yml
Updated the compatibility pages
Updated release notes
Also included version clarification on PG17 versions to PGD versions.
> Docs-1267 add ubuntu 24.04 to supported list

- advocacy_docs/playground/1/01_examples/expression-replacement.mdx
- gatsby-config.js
- gatsby-node.js
- package-lock.json
- package.json
- src/components/layout.js
- src/components/product-context.js
- src/components/product-name.js
- src/components/product-version.js
- src/constants/expression-replacement.mjs
- src/constants/products.js
- src/plugins/replacement-expression.js
- src/templates/doc.js
- src/templates/learn-doc.js
Allows expressions like `{{name.ln}}` or `{{name(epas).abbr}}` or `{{version.minor}}` to be used in Markdown, title, description.
Demo: https://deploy-preview-6673--edb-docs-staging.netlify.app/docs/playground/1/01_examples/expression-replacement/
> quick and dirty product name replacement

- product_docs/docs/ocl_connector/17/04_open_client_library/03_compiling_and_linking_a_program.mdx
- Ported in instructions from eng and edited for Docs compliance.
> Adding Windows example to Compiling and linking a program page in OCL

- product_docs/docs/epas/17/reference/oracle_compatibility_reference/epas_compat_bip_guide/03_built-in_packages/15_dbms_scheduler/index.mdx
otherwise calls to the package procedures will be failing.
Added the instruction to create the required extension.
> The extension `dbms_scheduler` must be created by user

- product_docs/docs/eprs/7/08_xdb_cli/03_xdb_cli_commands/04_encrypt_password.mdx
- product_docs/docs/eprs/7/08_xdb_cli/03_xdb_cli_commands/08_printing_pub_db_details.mdx
- product_docs/docs/eprs/7/08_xdb_cli/03_xdb_cli_commands/12_removing_publication_database.mdx
- product_docs/docs/eprs/7/08_xdb_cli/03_xdb_cli_commands/13_get_tables_for_new_publication.mdx
- product_docs/docs/eprs/7/08_xdb_cli/03_xdb_cli_commands/20_adding_tablefilters_to_publication.mdx
- product_docs/docs/eprs/7/08_xdb_cli/03_xdb_cli_commands/21_updating_tablefilters_to_publication.mdx
- product_docs/docs/eprs/7/08_xdb_cli/03_xdb_cli_commands/22_removing_tablefilters_to_publication.mdx
- product_docs/docs/eprs/7/08_xdb_cli/03_xdb_cli_commands/23_print_conflict_resolution_strategy.mdx
- product_docs/docs/eprs/7/08_xdb_cli/03_xdb_cli_commands/24_updating_conflict_resolution_strategy.mdx
- product_docs/docs/eprs/7/08_xdb_cli/03_xdb_cli_commands/25_set_pdn_node.mdx
- product_docs/docs/eprs/7/08_xdb_cli/03_xdb_cli_commands/26_set_controller.mdx
- product_docs/docs/eprs/7/08_xdb_cli/03_xdb_cli_commands/27_validate_a_publication.mdx
- product_docs/docs/eprs/7/08_xdb_cli/03_xdb_cli_commands/28_validate_all_publications.mdx
- product_docs/docs/eprs/7/08_xdb_cli/03_xdb_cli_commands/29_removing_a_publication.mdx
- product_docs/docs/eprs/7/08_xdb_cli/03_xdb_cli_commands/30_replicating_ddl_changes_cli.mdx
- product_docs/docs/eprs/7/08_xdb_cli/03_xdb_cli_commands/33_printing_subscription_db_details.mdx
- product_docs/docs/eprs/7/08_xdb_cli/03_xdb_cli_commands/35_removing_subscription_database_cli.mdx
- product_docs/docs/eprs/7/08_xdb_cli/03_xdb_cli_commands/41_taking_mmr_snapshot.mdx
- product_docs/docs/eprs/7/08_xdb_cli/03_xdb_cli_commands/42_perform_synchronization.mdx
- product_docs/docs/eprs/7/08_xdb_cli/03_xdb_cli_commands/43_configure_smr_schedule.mdx
- product_docs/docs/eprs/7/08_xdb_cli/03_xdb_cli_commands/44_configure_mmr_schedule.mdx
- product_docs/docs/eprs/7/08_xdb_cli/03_xdb_cli_commands/45_print_schedule.mdx
- product_docs/docs/eprs/7/08_xdb_cli/03_xdb_cli_commands/47_removing_subscription_cli.mdx
- product_docs/docs/eprs/7/08_xdb_cli/03_xdb_cli_commands/48_schedule_shadow_table_history_clean.mdx
- product_docs/docs/eprs/7/08_xdb_cli/03_xdb_cli_commands/49_clean_shadow_table_history.mdx
- product_docs/docs/eprs/7/08_xdb_cli/03_xdb_cli_commands/50_clean_replication_history.mdx
- product_docs/docs/eprs/7/08_xdb_cli/03_xdb_cli_commands/51_clean_all_replication_history.mdx
- product_docs/docs/eprs/7/09_data_validator/02_perform_datavalidation.mdx
There is a bug where in some documented command flags/arguments, they are introduced by an em dash instead of a hyphen. This is causing customers to get the `Error: Invalid combination of arguments.` when copy-pasting from the docs. 
https://enterprisedb.atlassian.net/browse/XDB-2369
I did a global search in the */eprs/* documentation and found more instances.
PS: The difference is not that visible here in GH, but VSCode displayed it better:
> EPRS: replaces em dashes in code snippets with hyphen in commands

- product_docs/docs/pgd/5.7/index.mdx
Before: 
EDB Postgres Distributed 5 is compatible with PostgreSQL, EDB Postgres Extended, and EDB Postgres Advanced versions 12-17
After: 
EDB Postgres Distributed 5 is compatible with PostgreSQL, EDB Postgres Extended, and EDB Postgres Advanced versions 13-17
v12 is End of Life
> Corrected supported database versions index.mdx

- product_docs/docs/epas/13/epas_compat_sql/16_alter_user_role_profile_management_clauses.mdx
- product_docs/docs/epas/14/epas_compat_sql/16_alter_user_role_profile_management_clauses.mdx
- product_docs/docs/epas/15/reference/oracle_compatibility_reference/epas_compat_sql/16_alter_user_role_profile_management_clauses.mdx
- product_docs/docs/epas/16/reference/oracle_compatibility_reference/epas_compat_sql/16_alter_user_role_profile_management_clauses.mdx
- product_docs/docs/epas/17/reference/oracle_compatibility_reference/epas_compat_sql/16_alter_user_role_profile_management_clauses.mdx
- product_docs/docs/pem/10/debugger.mdx
- product_docs/docs/pem/10/installing/windows/pem_server_and_httpd_on_diff_host.mdx
Addresses - [DB-2895](https://enterprisedb.atlassian.net/browse/DB-2895)
[DB-2895]: https://enterprisedb.atlassian.net/browse/DB-2895?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> EPAS - Update password set at timestamp clause details

- product_docs/docs/pgd/6.0/compatibility.mdx
- product_docs/docs/pgd/6.0/upgrades/compatibility.mdx
Updated the compatibility table to remove compats for pre v14 PG and updated upgrades compatibility page to say that Upgrading from 4.x to 6.x is possible.
> DOCS-1432-Update-Compatibility-Table-2

- product_docs/docs/pgd/6/nodes/logical_standby_nodes.mdx
- product_docs/docs/pgd/6/reference/nodes-management-interfaces.mdx
This deprecated parameter was removed from function bdr.join_node_group() in PGD 6.
DOCS-1449.
> PGD: remove reference to "pause_in_standby"

- product_docs/docs/epas/13/ecpgplus_guide/05_building_executing_dynamic_sql_statements.mdx
- product_docs/docs/epas/14/ecpgplus_guide/05_building_executing_dynamic_sql_statements.mdx
- product_docs/docs/epas/15/application_programming/ecpgplus_guide/05_building_executing_dynamic_sql_statements.mdx
- product_docs/docs/epas/16/application_programming/ecpgplus_guide/05_building_executing_dynamic_sql_statements.mdx
- product_docs/docs/epas/17/application_programming/ecpgplus_guide/05_building_executing_dynamic_sql_statements.mdx
- product_docs/docs/epas/17/application_programming/ecpgplus_guide/06_error_handling.mdx
Addresses [DOCS-1339](https://enterprisedb.atlassian.net/browse/DOCS-1339), [DOCS-1091](https://enterprisedb.atlassian.net/browse/DOCS-1091)
[DOCS-1339]: https://enterprisedb.atlassian.net/browse/DOCS-1339?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DOCS-1091]: https://enterprisedb.atlassian.net/browse/DOCS-1091?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> EPAS - ECPG fix

- product_docs/docs/efm/5/04_configuring_efm/01_cluster_properties.mdx
We (ok, I) somehow ended up with two different notes about wal_sender_timeout when using efm's sync standby properties. Only one of these was now correct; I removed the other.
> remove redundant note on wal_sender_timeout

- advocacy_docs/community/contributing/styleguide.mdx
- src/styles/_docs.scss
- Wrote up some basic guidance for use of screenshots and diagrams: https://github.com/EnterpriseDB/docs/blob/meta/josh/image-diagram-guidance/advocacy_docs/community/contributing/styleguide.mdx#images
- Added subtle border styling for images (since not using borders *in* images is something I very much want to be part of the guidelines)
Guidelines are mildly opinionated and probably incomplete - please edit and/or critique!
> Guidelines for screenshots and diagrams

- docker/docker-compose.check-links.yaml
- package.json
- tools/automation/actions/link-check/index.js
- tools/automation/actions/link-check/package-lock.json
- tools/automation/actions/link-check/package.json
Automatically updating links that would result in redirects caused unexpected behavior - if the redirect was inappropriate, the link would be updated in a way that might lose information needed to correct the original link.
Relegate this behavior to a new npm script, `links:fix` that update links (`node tools/automation/actions/link-check --fix` will also work when running directly)
Also surface Frontmatter errors, since it's easy to do and those are hard to debug right now.
> Don't update redirected links when running checker locally

- product_docs/docs/pgd/6/reference/tables-views-functions/testingandtuning.mdx
- product_docs/docs/pgd/6/reference/testing-tuning.mdx
Explicitly note that pgd_bench does not automatically initiate database transations, so any custom scripts will need to include SQL transaction statements, particularly for running in CAMO mode.
DOCS-1529
> pgd: add some notes about pgd_bench, scripts and "-m camo"

- product_docs/docs/pgd/6/reference/tables-views-functions/functions.mdx
Also add a missing heading for the unrelated function references which follow immediately after.
DOCS-1528.
> pgd: clarify that "transaction_id" is not accessible in SQL.

- product_docs/docs/migration_toolkit/55/09_mtk_errors.mdx
https://enterprisedb.atlassian.net/browse/MTK-1465
> MTK 55.11.2: new errors

- product_docs/docs/pgd/6/rel_notes/index.mdx
- product_docs/docs/pgd/6/rel_notes/pgd_6.0.0_rel_notes.mdx
- product_docs/docs/pgd/6/rel_notes/src/relnote_6.0.0.yml
First draft release notes - to be reviewed
> DOCS-1532-pgd-6-0-release-notes

- product_docs/docs/pem/10/pem_rel_notes/pem_10.0.0_rel_notes.mdx
- product_docs/docs/pem/10/pem_rel_notes/src/pem_10.0.0_rel_notes.yml
- product_docs/docs/pem/10/upgrading/upgrading_pem_installation/upgrading_pem_installation_linux_rpm.mdx
Add details of --allowerasing option that allows dnf upgrade to work when going from PEM 9 to 10
> Docs/pem 5549/dnf option

- advocacy_docs/edb-postgres-ai/cloud-service/security/compliance_and_certifications.mdx
Removed mention of PCI from security compliance and certifications page
Scope/rationale is from
[UPM-52839](https://enterprisedb.atlassian.net/browse/UPM-52839)
which is itself derived from
[SECA-989](https://enterprisedb.atlassian.net/browse/SECA-989)
[UPM-52839]: https://enterprisedb.atlassian.net/browse/UPM-52839?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SECA-989]: https://enterprisedb.atlassian.net/browse/SECA-989?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(UPM-52839): removed mention of PCI from security page

- advocacy_docs/edb-postgres-ai/ai-accelerator/knowledge_base/performance_tuning.mdx
- advocacy_docs/edb-postgres-ai/ai-accelerator/knowledge_base/usage.mdx
- advocacy_docs/edb-postgres-ai/ai-accelerator/preparers/examples/chained_preparers.mdx
- advocacy_docs/edb-postgres-ai/ai-accelerator/preparers/examples/chunk_text.mdx
- advocacy_docs/edb-postgres-ai/ai-accelerator/preparers/examples/chunk_text_auto_processing.mdx
- advocacy_docs/edb-postgres-ai/ai-accelerator/preparers/primitives.mdx
- advocacy_docs/edb-postgres-ai/ai-accelerator/preparers/volume_destination.mdx
- advocacy_docs/edb-postgres-ai/ai-accelerator/reference/index.mdx
- advocacy_docs/edb-postgres-ai/ai-accelerator/reference/models.mdx
- advocacy_docs/edb-postgres-ai/ai-accelerator/rel_notes/ai-accelerator_4.1.1_rel_notes.mdx
- advocacy_docs/edb-postgres-ai/ai-accelerator/rel_notes/index.mdx
- advocacy_docs/edb-postgres-ai/ai-accelerator/rel_notes/src/rel_notes_4.1.1.yml
- advocacy_docs/pg_extensions/otel/using.mdx
- product_docs/docs/pgd/5.7/index.mdx
- Updated docs to reflect changes from [AID-426](https://enterprisedb.atlassian.net/browse/AID-426)
- Added `sync_hcp_models`
- Renamed `get_hcp_models` to `list_hcp_models`.
[AID-426]: https://enterprisedb.atlassian.net/browse/AID-426?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> AID-426 - Model sync and QoL changes

- advocacy_docs/pg_extensions/pg_tuner/configuring.mdx
Added a parameter as per [DOCS-1555](https://enterprisedb.atlassian.net/browse/DOCS-1555)
[DOCS-1555]: https://enterprisedb.atlassian.net/browse/DOCS-1555?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Postgres Tuner - Added a parameter

- advocacy_docs/pg_extensions/otel/configuring.mdx
- advocacy_docs/pg_extensions/otel/installing.mdx
- advocacy_docs/pg_extensions/otel/rel_notes/index.mdx
various changes to install/configure
> docs-1564 various changes to install/configure

- product_docs/docs/pgd/5.8/rel_notes/pgd_5.8.1_rel_notes.mdx
- product_docs/docs/pgd/5.8/rel_notes/src/relnote_5.8.1.yml
- product_docs/docs/pgd/6/rel_notes/pgd_6.0.1_rel_notes.mdx
- product_docs/docs/pgd/6/rel_notes/src/relnote_6.0.1.yml
Add release notes entry for v5.8.1 and v6.0.1 for [BDR-6511](https://enterprisedb.atlassian.net/browse/BDR-6511)
[BDR-6511]: https://enterprisedb.atlassian.net/browse/BDR-6511?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> cli: Add release notes entry for v5.8.1 and v6.0.1 for BDR-6511

- advocacy_docs/pg_extensions/wait_states/rel_notes/wait_states_1.5_rel_notes.mdx
Commit [e4c4b54d1462cf9f115ada932a9d19fa592359b7](https://github.com/EnterpriseDB/edb-modules/commit/e4c4b54d1462cf9f115ada932a9d19fa592359b7), contained in the release of 1.5.0, fixed a miscalculation (integer overflow) of retention time for larger values, that caused history files to be pruned sooner than they should have been.
For some reason, this was not listed in the release notes of 1.5.0.
A customer has just reported the issue while using an older version, so it's best to have it mentioned in the release notes, so we can reference the bug fix in customer cases.
> Add missing entry to wait_states_1.5_rel_notes.mdx
